#!/usr/bin/env python3
"""Conjecture-net executability audit for the latest D03 v10 physical-purity gate."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
loaded=(ROOT/'research/voevodsky/check_d03_x3_loaded_pc_endpoint_boundary.rs').read_text();corner=(ROOT/'research/voevodsky/check_d03_corner_residue_comparison.rs').read_text();latest=(ROOT/'src/ledger/20260826-2993 D03 Supplies a Formal Support-Sensitive Boolean Derived Calculus.md').read_text()
checks={'latest_frontier_is_purity':'occurrence-loaded purity/costalk comparison' in latest,'v10_first':latest.find('v_{10}',3000) < latest.find('v_{00}',3000),'formal_loaded_packet_exists':'loaded_v10_residue' in loaded and 'normal_Koszul_Cech' in loaded,'actual_PC_map_untyped':'actual_ringed_PC_extraordinary_map' in loaded and 'UNTYPED' in loaded,'supported_candidate_null_after_localization':'localized_supported_map' in corner and 'NULLHOMOTOPIC' in corner,'geometric_map_declared_unconstructed':'geometric corner restriction/residue morphism' in corner}
assert all(checks.values()),checks
out={'schema':'marici.voevodsky.CR1A-v10-PC-purity-executability.v1','prospective_action':'CR1A_v10_occurrence_loaded_PC_purity','outcome_contract':{'++':'a geometric occurrence-loaded purity map into the actual ringed-PC costalk commutes with all retained structures','+-':'the map exists but one lower-Cech/excess compatibility remains','-+':'every source-geometric candidate has a nonzero typed obstruction','--':'only the formal coefficient map exists; the geometric source morphism needed to pose purity is absent'},'resolution':'--','available':['positive formal v10 residue','full occurrence and normal Koszul-Cech maps','Tor0 and Tor1 grades','excess trace and graph-Cartier Bockstein','independent positive physical orientation'],'missing':['geometric corner restriction/residue morphism from the reciprocal-standard/original-Borel-Moore road square','identification of its codomain with the actual ringed-PC extraordinary costalk'],'rejected_shortcut':'The finite supported quotient-dual candidate becomes nullhomotopic after occurrence localization and cannot be identified with the nonzero full road trace.','refinement':['CR1A1_construct_geometric_v10_corner_restriction','CR1A2_compare_v10_local_cohomology_boundary'],'next':'Construct the geometric source restriction first; do not promote the formal supported quotient map.','checks':checks,'passed':True};p=ROOT/'research/voevodsky/results/CR1A_v10_PC_purity_executability.json';p.parent.mkdir(exist_ok=True);p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'resolution':'--','available':5,'missing':2,'next':out['refinement'][0]}))
