#!/usr/bin/env python3
"""Resolve the alternative non-gallery relative-Q source branch."""
import json,subprocess,tempfile
from pathlib import Path
R=Path(__file__).resolve().parents[2]
def run(n):
 s=R/'research/voevodsky'/n;e=Path(tempfile.gettempdir())/(s.stem+'.exe');subprocess.run(['rustc','--edition=2021','-D','warnings','-O',str(s),'-o',str(e)],check=True);return json.loads(subprocess.check_output([str(e)],text=True))
d=run('check_d03_relative_dual_star_carrier.rs');r=d['result'];k=d['checks']
checks={'strict_Q_nonzero':k['strict_D03_carrier_Q_projection']=='NONZERO','strict_boundary_fails':k['strict_D03_special_boundary'].startswith('FAIL'),'top_Q_nonzero':k['top_cone_Q_projection']=='NONZERO','top_orientation_absent':k['top_cone_D03_orientation']=='ABSENT','top_coeff_mismatch':k['top_cone_integral_boundary'].startswith('MISMATCH'),'no_canonical':r['typing_conclusion']['canonical_candidate']=='NONE'}
assert all(checks.values()),checks
out={'schema':'marici.voevodsky.CR1SP5-non-gallery-Q-source-specialization.v1','action':'CR1SP5_non_gallery_Q_source_specialization','outcome':'-+','candidates':[{'source':'strict D03-apex relative star','positive':'nonzero Q projection and D03 orientation','failure':'special trace only covers e_r; e_c coefficient is zero rather than x1'},{'source':'unique common top-coface cone','positive':'nonzero Q projection and covers all seven gallery supports','failure':'no D03 orientation and boundary coefficients (1,1,1) mismatch (x1,X_D03*x1,X_D03)'}],'obstruction':'strict normal orientation and whole-gallery lcm boundary select different quotient apices; the carrier poset has no canonical source satisfying both','refinement':['CR1SP5a_construct_sheaf_theoretic_normal_Morse_source','CR1SP5b_construct_coefficient_cosheaf_fundamental_class','CR1SP5c_compare_boundary_with_lcm_syzygy'],'next':'CR1SP3_Ext1_Cartier_Gysin_specialization','metric_delta':{'formal_coherence_survivors_percent':0.0,'geometrically_certified_complete_paths_percent':0.0,'active_local_specialization_branches':-1,'blocked_specialization_branches':1,'new_typed_interfaces':0},'checks':checks,'passed':True};p=R/'research/voevodsky/results/CR1SP5_non_gallery_Q_source_specialization.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'outcome':'-+','survivors':32,'active_specialization_branches':2,'next':out['next']}))
