#!/usr/bin/env python3
"""Audit whether formal four-edge residues have ringed-PC Gysin provenance."""
import json,subprocess,tempfile
from pathlib import Path
R=Path(__file__).resolve().parents[2]
def run(name):
 src=R/'research/voevodsky'/name;exe=Path(tempfile.gettempdir())/(src.stem+'.exe');subprocess.run(['rustc','--edition=2021','-D','warnings','-O',str(src),'-o',str(exe)],check=True);return json.loads(subprocess.check_output([str(exe)],text=True))
cox=run('check_d03_toric_cox_cousin_trace.rs');four=run('check_d03_four_corner_descent_obstruction.rs')
checks={'formal_four_corners':len(cox['trace']['formal_corner_values'])==4,'x3_edge_proved':cox['checks']['x3_occurrence_Koszul_Cech_Gysin']=='PASS','actual_PC_unconstructed':cox['checks']['actual_PC_Gysin']=='UNCONSTRUCTED','overlap_map_unconstructed':'unconstructed_localization_Gysin_PC_map' in four['claims'],'generic_section_compatible':four['factorization_test']['generic_lcm_cocycle'].startswith('PASS'),'no_supported_reconstruction':four['claims']['falsified_corner_local_cohomology_reconstruction'].startswith('the actual support ideals')}
assert all(checks.values()),checks
out={'schema':'marici.voevodsky.CR1-PK1a-remaining-ringed-edge-Gysin.v1','action':'CR1PK1a_construct_remaining_ringed_edge_Gysin_maps','outcome':'-+','outcome_contract':{'++':'all remaining edge maps have ringed-PC provenance and coherent overlaps','+-':'all maps are typed but higher coherence remains','-+':'formal target residues exist but no ringed-PC source maps construct them','--':'even the formal edge residues are unavailable'},'available':{'formal_corner_values':cox['trace']['formal_corner_values'],'formal_generic_lcm_section':True,'occurrence_geometric_edge':'x3 with v00/v10'},'obstruction':'The free cellular intersection terms survive Laurent localization and cannot be rebranded as supported local-cohomology intersections; no natural ringed-PC Gysin transformation is present.','missing_edges':['x4','x0','x1'],'refinement':['CR1PK1a1_construct_x4_ringed_PC_Gysin_span','CR1PK1a2_construct_x0_ringed_PC_Gysin_span','CR1PK1a3_construct_x1_ringed_PC_Gysin_span','CR1PK1a4_verify_edge_overlap_and_triple_coherence'],'aggregation':'first three constructions conjunctive, followed by coherence','checks':checks,'passed':True};p=R/'research/voevodsky/results/CR1_PK1a_remaining_ringed_edge_Gysin_maps.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'outcome':'-+','missing_edges':out['missing_edges'],'children':len(out['refinement'])}))
