#!/usr/bin/env python3
"""Audit one representative of the six-face mixed-sheet orbit."""
import json,subprocess,tempfile
from pathlib import Path
R=Path(__file__).resolve().parents[2]
def run(n):
 s=R/'research/voevodsky'/n;e=Path(tempfile.gettempdir())/(s.stem+'.exe');subprocess.run(['rustc','--edition=2021','-D','warnings','-O',str(s),'-o',str(e)],check=True);return json.loads(subprocess.check_output([str(e)],text=True))
n=run('check_cross_polytope_equivariant_top_trace_no_go.rs');p=run('check_d03_plus_excess_beck_chevalley.rs');f=p['factorization_test']
checks={'mixed_orbit6':n['face_orbits'][1]==6,'mixed_contribution':'-6b' in '2a-6b','marked_geometry':f['geometric_source'].startswith('PASS') and f['marked_flag'].startswith('PASS'),'eta_exact':f['excess_complex'].startswith('PASS'),'orientation':f['tor_orientation'].startswith('PASS'),'boundary_invariants':f['forced_boundary_invariants'].startswith('PASS'),'source_untyped':f['augmented_dual_block_map'].startswith('UNTYPED'),'BC_inconclusive':f['beck_chevalley'].startswith('INCONCLUSIVE')}
assert all(checks.values()),checks
out={'schema':'marici.voevodsky.CR1-mixed-sheet-face-BC-representative.v1','action':'CR1QCOUN1a2_construct_mixed_sheet_face_BC_representative','outcome':'+-','proved':['unique marked plus/D03 mixed face','canonical exact eta-wedge excess inclusion','positive Tor1 orientation','agreement of every forced occurrence, normal, endpoint, and physical boundary invariant'],'unresolved':'the augmented dual-block/Cousin source kernel is untyped, so the local coefficient map is not yet a loaded face BC morphism','orbit_effect':'if promoted, D3/reflection generates six mixed faces with ordinary top contribution -6b; this orbit cannot itself supply the odd unit','produces':['mixed_face_eta_wedge_BC_associated_grade'],'parent_effect':'eight-face loaded BC gate remains -- because pure-sheet map is impossible and mixed map is not promoted','next':'CR1QCOUN1b_identify_interior_target_with_literal_entry143_Q','metric_delta':{'active_face_BC_representatives':-1,'resolved_face_associated_grades':1,'new_typed_interfaces':1,'closed_face_orbit_refinement_groups':1},'checks':checks,'passed':True};q=R/'research/voevodsky/results/CR1_mixed_sheet_face_BC_representative.json';q.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'outcome':'+-','mixed_orbit':6,'active_representatives':0,'new_interfaces':1,'next':out['next']}))
