#!/usr/bin/env python3
"""Audit the single-road lift from supported gallery grade to full PC costalk."""
import json,subprocess,tempfile
from pathlib import Path
R=Path(__file__).resolve().parents[2]
def run(n):
 s=R/'research/voevodsky'/n;e=Path(tempfile.gettempdir())/(s.stem+'.exe');subprocess.run(['rustc','--edition=2021','-D','warnings','-O',str(s),'-o',str(e)],check=True);return json.loads(subprocess.check_output([str(e)],text=True))
b=run('check_d03_bivariant_pc_hom.rs');t=run('check_d03_q0_endpoint_relative_tor_lift.rs');f=b['factorization_test'];q=t['factorization_test']
checks={'target_trace_exists':f['existence'].startswith('PASS'),'target_trace_unique':f['uniqueness'].startswith('PASS'),'normal_duality':f['normal_duality'].startswith('PASS'),'gallery_BM_rank2':'Z^2' in q['unmarked_gallery_relative_BM'],'mark_rank1':q['x3_mark_ablation'].startswith('RANK 1'),'ringed_projection_missing':q['ringed_q_projection'].startswith('FAIL'),'AW_missing':q['relative_dualizing_AW_counit'].startswith('FAIL'),'full_lift_missing':q['full_extraordinary_PC_lift']=='UNCONSTRUCTED'}
assert all(checks.values()),checks
out={'schema':'marici.voevodsky.CR1-single-D03-full-PC-costalk-lift.v1','action':'CR1PK1a2a1a1_construct_single_D03_full_PC_costalk_lift','outcome':'-+','proved':['unique endpoint-normalized bivariant trace on Q03,partial^PC','integral twist-reversed normal Koszul duality','primitive marked carrier line and associated-grade BC square','Tor0 and eta_3,mix Tor1 are both necessarily retained'],'obstruction':'the gallery and road supports are ringed-incomparable; tau0 is not an iterated Thom costalk, and no ringed q-counit/Alexander-Whitney trace exists','negative_control':'reusing the localized entry-97 target contracts the common-base RHom to zero','new_interfaces':['unique_local_Q03partial_PC_bivariant_trace'],'refinement':['CR1PK1a2a1a1a_construct_tau0_A3_filtered_relative_Thom_costalk','CR1PK1a2a1a1b_construct_ringed_staircase_p_q','CR1PK1a2a1a1c_construct_ordered_relative_dualizing_AW_trace','CR1PK1a2a1a1d_test_full_Tor0_Tor1_counit'],'metric_delta':{'formal_coherence_survivors_percent':0.0,'geometrically_certified_complete_paths_percent':0.0,'new_typed_interfaces':1,'newly_blocked_descendant_branches':1},'checks':checks,'passed':True};p=R/'research/voevodsky/results/CR1_single_D03_full_PC_costalk_lift.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'outcome':'-+','survivors':32,'new_interfaces':1,'next':out['refinement'][0]}))
