#!/usr/bin/env python3
"""Audit the variance-changing endpoint-line to road-Tor1 map."""
import json,subprocess,tempfile
from pathlib import Path
R=Path(__file__).resolve().parents[2]
def run(n):
 s=R/'research/voevodsky'/n;e=Path(tempfile.gettempdir())/(s.stem+'.exe');subprocess.run(['rustc','--edition=2021','-D','warnings','-O',str(s),'-o',str(e)],check=True);return json.loads(subprocess.check_output([str(e)],text=True))
q=run('check_d03_q0_endpoint_relative_tor_lift.rs');b=run('check_d03_plus_excess_beck_chevalley.rs');f=q['factorization_test'];g=b['factorization_test']
checks={'can_var_pairing':f['can_var_pairing'].startswith('PASS'),'Tor_both':f['full_normal_packet'].startswith('Tor0 plus'),'formal_BC':f['formal_weighted_d_squared_BC'].startswith('PASS'),'eta_inclusion':g['excess_complex'].startswith('PASS'),'orientation':g['tor_orientation'].startswith('PASS'),'q_projection_missing':f['ringed_q_projection'].startswith('FAIL'),'AW_missing':f['relative_dualizing_AW_counit'].startswith('FAIL'),'augmented_map_untyped':g['augmented_dual_block_map'].startswith('UNTYPED'),'full_lift_missing':f['full_extraordinary_PC_lift']=='UNCONSTRUCTED'}
assert all(checks.values()),checks
out={'schema':'marici.voevodsky.CR1-variance-q0-q2-road-Tor1.v1','action':'CR1ALPHA2a1c_construct_variance_changing_q0_q2_to_road_Tor1_map','outcome':'-+','proved':['perfect reciprocal/original can-var pairing','canonical eta-wedge excess inclusion with positive Tor1 orientation','formal weighted BC square before base change','both Tor0 and Tor1 retained'],'obstruction':'no ringed q projection or relative-dualizing AW counit maps the endpoint lines into the actual road costalk; the augmented dual-block map is untyped','consequence':'the enlarged carrier cannot yet be promoted to the mixed-variance normalization-sheet kernel','next_required_input':'a ringed support correspondence implementing the endpoint q-counit before localization','metric_delta':{'active_alpha_candidate_paths':-1,'blocked_variance_edges':1,'new_typed_interfaces':0,'geometrically_complete_paths':0},'final_metrics':{'active_alpha_candidate_paths':0,'typed_interfaces_accumulated':23,'formal_signed_coherence_assignments':32,'geometrically_complete_paths':0},'checks':checks,'passed':True};p=R/'research/voevodsky/results/CR1_variance_q0_q2_to_road_Tor1.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'outcome':'-+','active_alpha_paths':0,'new_interfaces':0,'next_required':out['next_required_input']}))
