#!/usr/bin/env python3
"""Construct the relative-BM Hom class for the expanded marked log blowup."""
import json,subprocess,tempfile
from pathlib import Path
R=Path(__file__).resolve().parents[2]
def run(n):
 s=R/'research/voevodsky'/n;e=Path(tempfile.gettempdir())/(s.stem+'.exe');subprocess.run(['rustc','--edition=2021','-D','warnings','-O',str(s),'-o',str(e)],check=True);return json.loads(subprocess.check_output([str(e)],text=True))
d=run('check_d03_central_flip_dnc_obstruction.rs');g=run('check_d03_whole_gallery_tag_gysin.rs');f=d['factorization_test'];r=g['result'];k=g['checks']
checks={'log_blowup_path':f['actual_correspondence_space'].startswith('PASS'),'relative_dualizing':f['relative_dualizing_class'].startswith('EXISTS'),'expanded_gallery':k['actual_expanded_gallery']=='PASS','relative_H1':k['relative_H1']=='PASS R/(x3)','BM_class':k['whole_gallery_BM_class']=='PASS','representatives_cohomologous':k['edge_representatives_cohomologous']=='PASS','normalized_unit':r['whole_gallery_BM_Gysin']['normalization']=='(-e_r^*)(-[n])=+1','orientation_unique':'unique generator' in r['whole_gallery_BM_Gysin']['uniqueness']}
assert all(checks.values()),checks
out={'schema':'marici.voevodsky.CR1SP6-relative-BM-Hom-full-marked-log-blowup.v1','action':'CR1SP6a_construct_relative_BM_Hom_class_of_full_marked_log_blowup','outcome':'++','construction':{'source':'expanded marked path E13-prime union P1 union ED3-prime relative to endpoints','class':'negative Cartier boundary -[n] in H1 = R/(x3)','derived_Hom_representative':'-e_r^* (equivalently -e_c^* or -h_E^* modulo coboundary)','value':'+1','orientation':'positive exceptional interval and ordered D03 normal uniquely fix the generator'},'important_distinction':'This class is relative BM/costalk data and does not factor through the ordinary zero gallery-to-Q projection. It is not yet paired with transported e_F.','produces':['canonical_full_marked_log_blowup_relative_BM_class'],'next':'CR1SP6b_tensor_relative_BM_class_with_reciprocal_Kummer_packet','metric_delta':{'resolved_SP6_gates':1,'remaining_SP6_depth':-1,'new_typed_interfaces':1,'gate_entropy_bits':-2.0,'parent_branch_entropy_bits':0.0},'checks':checks,'passed':True};p=R/'research/voevodsky/results/CR1SP6_relative_BM_Hom_full_marked_log_blowup.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'outcome':'++','value':1,'resolved_gates':'1/4','remaining_depth':3,'next':out['next']}))
