#!/usr/bin/env python3
"""Resolve the Cousin/local-cohomology specialization branch."""
import json,subprocess,tempfile
from pathlib import Path
R=Path(__file__).resolve().parents[2]
def run(n):
 s=R/'research/voevodsky'/n;e=Path(tempfile.gettempdir())/(s.stem+'.exe');subprocess.run(['rustc','--edition=2021','-D','warnings','-O',str(s),'-o',str(e)],check=True);return json.loads(subprocess.check_output([str(e)],text=True))
c=run('check_d03_toric_cox_cousin_trace.rs');f=c['trace'];k=c['checks']
checks={'formal_Cox':k['principal_line_chain_inclusion']=='PASS','unique_functional':f['formal_obstruction']=='zero','x3_Gysin':k['x3_occurrence_Koszul_Cech_Gysin']=='PASS','v00v10':k['v00_v10_residues'].startswith('PASS'),'bare_Cousin_zero':k['bare_O_Cousin'].startswith('ZERO'),'regular_OD_zero':k['regular_O_D_coherent_Cousin'].startswith('ZERO'),'PC_unconstructed':k['actual_PC_Gysin']=='UNCONSTRUCTED','source_unconstructed':k['G03_source']=='UNCONSTRUCTED'}
assert all(checks.values()),checks
out={'schema':'marici.voevodsky.CR1SP4-Cousin-local-cohomology-specialization.v1','action':'CR1SP4_Cousin_local_cohomology_specialization','outcome':'-+','proved':['formal Cox principal-line resolution of O(-D)','unique normalized O(D)-valued functional','x3 occurrence Koszul-Cech Gysin with positive v00/v10 residues','all-four formal fractions and compatible generic lcm cocycle'],'falsified':['ordinary coherent Cousin residue of O_U','ordinary coherent Cousin residue of regular O_U(D) sections'],'obstruction':'the desired nonzero class must be an extraordinary supported fundamental class; neither its ringed-PC Gysin realization nor a G03/e_F source lift exists','refinement':['CR1SP4a_construct_supported_Cousin_fundamental_class','CR1SP4b_identify_Cousin_object_with_ringed_PC_costalk','CR1SP4c_construct_eF_to_Cousin_source_lift'],'next':'CR1SP5_non_gallery_Q_source_specialization','metric_delta':{'formal_coherence_survivors_percent':0.0,'geometrically_certified_complete_paths_percent':0.0,'active_local_specialization_branches':-1,'blocked_specialization_branches':1,'new_typed_interfaces':1},'new_interfaces':['formal_Cox_four_corner_trace'],'checks':checks,'passed':True};p=R/'research/voevodsky/results/CR1SP4_Cousin_local_cohomology_specialization.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'outcome':'-+','survivors':32,'active_specialization_branches':3,'next':out['next']}))
