#!/usr/bin/env python3
"""Audit existence of the loaded x3/x4 endpoint connector needed for parity."""
import json,subprocess,tempfile
from pathlib import Path
R=Path(__file__).resolve().parents[2]
def run(n):
 s=R/'research/voevodsky'/n;e=Path(tempfile.gettempdir())/(s.stem+'.exe');subprocess.run(['rustc','--edition=2021','-D','warnings','-O',str(s),'-o',str(e)],check=True);return json.loads(subprocess.check_output([str(e)],text=True))
p=run('check_physical_polarity_butterfly.rs');r=run('check_d03_physical_reflection_edge_purity.rs');x=run('check_d03_x3_loaded_pc_endpoint_boundary.rs')
f=r['factorization_test'];q=x['factorization_test']
checks={'parity_detector':p['exact_test']['reflection_detector']['restriction'].startswith('H2'),'x3_packet':q['x3_occurrence_Gysin'].startswith('PASS'),'x4_target':f['edge_exchange'].startswith('x3<->x4'),'target_square':f['loaded_target_square']=='identity','x3_actual_untyped':q['actual_ringed_PC_extraordinary_map']=='UNTYPED','connector_declared_missing':'first_missing_datum' in p['sharp_blocker'] and 'endpoint-coherent loaded reflection connector' in p['sharp_blocker']['first_missing_datum'],'source_path_absent':any('does not construct a path' in z for z in r['counterevidence'])}
assert all(checks.values()),checks
out={'schema':'marici.voevodsky.CR1SP7-f3-paired-loaded-endpoint-connector.v1','action':'CR1SP7b_construct_f3_paired_loaded_endpoint_connector','outcome':'--','available':['x3 loaded coefficient/Cousin endpoint packet','strict reflected x4 target packet','target reflection square identity','exact Z/2 reflection parity detector'],'missing':'a path between the two loaded global endpoint two-extensions in one support-PC mapping category','consequence':'omega_load(f3,f3) is undefined, so neither evenness nor oddness may be inferred','parent_resolution':'CR1SP7=--','next_required_input':'construct one endpoint-coherent support/Yoneda-to-Tate connector retaining Tor0, Tor1, and lower Cousin terms','metric_delta':{'active_specialization_branches':-1,'executable_obstruction_paths':-1,'blocked_specialization_branches':1,'formal_outcome_entropy_bits':-2.0,'new_typed_interfaces':0},'final_metrics':{'formal_signed_coherence_assignments':32,'active_specialization_branches':0,'executable_specialization_paths':0,'geometrically_certified_complete_paths':0,'typed_interfaces_accumulated':20},'checks':checks,'passed':True};outp=R/'research/voevodsky/results/CR1SP7_f3_paired_loaded_endpoint_connector.json';outp.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'outcome':'--','SP7_parent':'--','parity':'undefined','active_branches':0,'executable_paths':0}))
