#!/usr/bin/env python3
"""Resolve the Ext1/Cartier-Gysin specialization branch."""
import json,subprocess,tempfile
from pathlib import Path
R=Path(__file__).resolve().parents[2]
def run(n):
 s=R/'research/voevodsky'/n;e=Path(tempfile.gettempdir())/(s.stem+'.exe');subprocess.run(['rustc','--edition=2021','-D','warnings','-O',str(s),'-o',str(e)],check=True);return json.loads(subprocess.check_output([str(e)],text=True))
o=run('check_d03_one_sheet_cartier_conductor.rs');c=run('check_d03_corner_residue_comparison.rs');k=o['checks'];p=o['post_cartier']
checks={'pre_cartier':k['strict_pre_Cartier_map'].startswith('PASS'),'rees_symbol':k['first_Rees_symbol'].startswith('PASS'),'conormal_eval':k['oriented_conormal_evaluation'].startswith('PASS'),'free_map_fails':k['post_Cartier_strict_free_target_map'].startswith('FALSIFIED'),'Ext1_exists':p['Ext1_R(R/(x3),R)']=='R/(x3)','marking_missing':not k['tag_correspondence_derived'],'lattice_missing':not k['staggered_lattice_derived_from_entries93_94'],'corner_not_full':'full_Theta03_identification' in c['checks'] and c['checks']['full_Theta03_identification']=='FALSIFIED'}
assert all(checks.values()),checks
out={'schema':'marici.voevodsky.CR1SP3-Ext1-Cartier-Gysin-specialization.v1','action':'CR1SP3_Ext1_Cartier_Gysin_specialization','outcome':'-+','proved':['strict filtered pre-Cartier map H -> -x3 f+','first Rees symbol -[x3] tensor f+','positive conormal evaluation to -f+','Ext1_R(R/(x3),R)=R/(x3)','positive v10 corner residue from quotient dual'],'falsified':['nonzero strict R-linear post-Cartier map R/(x3) -> R','identification of the v10-supported residue with the full Theta03 trace'],'obstruction':'the Gysin class exists only in Ext1; no geometric staggered target lattice, marked-cell correspondence, or variance-correct post-Cartier realization promotes it to sp_G','refinement':['CR1SP3a_construct_geometric_staggered_x3_lattice','CR1SP3b_construct_marked_gallery_tag_correspondence','CR1SP3c_realize_Ext1_as_oriented_Gysin_map'],'next':'CR1SP2_nearby_vanishing_cycle_specialization','metric_delta':{'formal_coherence_survivors_percent':0.0,'geometrically_certified_complete_paths_percent':0.0,'active_local_specialization_branches':-1,'blocked_specialization_branches':1,'new_typed_interfaces':1},'new_interfaces':['algebraic_D03_Ext1_Gysin_class'],'checks':checks,'passed':True};pout=R/'research/voevodsky/results/CR1SP3_Ext1_Cartier_Gysin_specialization.json';pout.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'outcome':'-+','survivors':32,'active_specialization_branches':1,'next':out['next']}))
