#!/usr/bin/env python3
"""Audit the target-side unlocalized Koszul-to-Cech comparison."""
import json,subprocess,tempfile
from pathlib import Path
R=Path(__file__).resolve().parents[2]
def run(n):
 s=R/'research/voevodsky'/n;e=Path(tempfile.gettempdir())/(s.stem+'.exe');subprocess.run(['rustc','--edition=2021','-D','warnings','-O',str(s),'-o',str(e)],check=True);return json.loads(subprocess.check_output([str(e)],text=True))
x=run('check_d03_x3_loaded_pc_endpoint_boundary.rs');o=run('check_one_normal_can_var_cousin.rs');f=x['factorization_test'];c=o['checks']
checks={'one_normal_map':c['koszul_to_cech'].startswith('PASS'),'pairing_perfect':c['pairing_perfectness'].startswith('PASS'),'both_corners':f['v00_finite_corner_quotient_dual'].startswith('PASS') and f['v10_finite_corner_quotient_dual'].startswith('PASS'),'x3_Gysin':f['x3_occurrence_Gysin'].startswith('PASS'),'normal_all16':f['normal_Koszul_Cech'].startswith('PASS'),'Tor_retained':f['Tor0_quotient'].startswith('PASS') and f['Tor1_repeated_normal_excess'].startswith('PASS'),'ringed_untyped':f['actual_ringed_PC_extraordinary_map']=='UNTYPED'}
assert all(checks.values()),checks
out={'schema':'marici.voevodsky.CR1-target-unlocalized-Koszul-Cech-comparison.v1','action':'CR1PK1a2a1a1a2_construct_target_unlocalized_Koszul_Cech_comparison','outcome':'-+','proved':['finite one-normal Koszul-to-Cech simple-pole chain map','perfect reciprocal/original Verdier pairing','simultaneous x3 occurrence Gysin at v00 and v10','all 16 normal Koszul-Cech components','Tor0, Tor1 excess, Bockstein, and physical line retained'],'obstruction':'the finite coefficient codomain is not definitionally the ringed locally-finite PC extraordinary costalk; endpoint occurrence-loaded purity maps are absent','new_interfaces':['finite_x3_loaded_Koszul_Cech_comparison','simultaneous_v00_v10_loaded_residue_packet'],'refinement':['CR1PK1a2a1a1a2a_construct_v10_occurrence_loaded_PC_purity','CR1PK1a2a1a1a2b_extend_purity_along_x3_to_v00','CR1PK1a2a1a1a2c_verify_pi_trace_Bockstein_lower_Cech_naturality'],'next':'CR1PK1a2a1a1a2a_construct_v10_occurrence_loaded_PC_purity','metric_delta':{'formal_coherence_survivors_percent':0.0,'geometrically_certified_complete_paths_percent':0.0,'new_typed_interfaces':2,'newly_blocked_descendant_branches':1},'checks':checks,'passed':True};p=R/'research/voevodsky/results/CR1_target_unlocalized_Koszul_Cech_comparison.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'outcome':'-+','survivors':32,'new_interfaces':2,'next':out['next']}))
