#!/usr/bin/env python3
"""Audit the next alpha-path edge: the mixed-variance sheet kernel."""
import json,subprocess,tempfile
from pathlib import Path
R=Path(__file__).resolve().parents[2]
def run(n):
 s=R/'research/voevodsky'/n;e=Path(tempfile.gettempdir())/(s.stem+'.exe');subprocess.run(['rustc','--edition=2021','-D','warnings','-O',str(s),'-o',str(e)],check=True);return json.loads(subprocess.check_output([str(e)],text=True))
p=run('check_conductor_polarity_bockstein.rs');h=run('check_scalar_common_ring_hom.rs');f=p['factorization_test'];g=h['factorization_test']
checks={'Bockstein_iso':f['bockstein'].startswith('isomorphism'),'reflection_odd':f['reflection_square']=='c(f3,f3)=1','mapping_unconstructed':f['loaded_mapping_complex']=='unconstructed','common_Hom_zero':g['formal_H1']=='zero','equivariant_contraction':g['M_equivariant_contraction'].startswith('passed'),'direct_alpha_fails':g['direct_alpha_N_equals_qSigma'].startswith('falsified'),'geometric_RHom_untyped':g['geometric_RHom']=='untyped'}
assert all(checks.values()),checks
out={'schema':'marici.voevodsky.CR1-alpha-mixed-variance-sheet-kernel.v1','action':'CR1ALPHA2_construct_mixed_variance_normalization_sheet_kernel','outcome':'-+','proved':['coefficient conductor Bockstein is Z/2 -> Z/2 isomorphism','reflection generator maps to odd loaded obstruction','full common-ring mixed block is D3-equivariantly contractible','strict coefficientwise Hom has H1=0'],'falsified':'a direct strict coefficient map sending N_road to qSigma','interpretation':'any nonzero kernel must be genuinely support-sensitive and extraordinary; coefficientwise base change necessarily erases it','missing':'endpoint- and Q-preserving defect restriction from two sheetwise gallery homotopies, followed by a support-selected geometric RHom','refinement':['CR1ALPHA2a_construct_endpoint_Q_defect_restriction','CR1ALPHA2b_select_positive_multi_Rees_support_component','CR1ALPHA2c_form_geometric_mixed_variance_RHom'],'metric_delta':{'resolved_alpha_path_edges':1,'active_alpha_paths':-1,'new_typed_interfaces':0,'blocked_alpha_edges':1,'formal_outcome_entropy_bits':-2.0},'final_metrics':{'active_alpha_paths':0,'resolved_alpha_vertices':1,'blocked_alpha_edges':1,'typed_interfaces_accumulated':21},'checks':checks,'passed':True};q=R/'research/voevodsky/results/CR1_alpha_mixed_variance_sheet_kernel.json';q.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'outcome':'-+','common_Hom_H1':0,'active_alpha_paths':0,'next':out['refinement'][0]}))
