#!/usr/bin/env python3
"""Audit the derived comparison between the BM/Kummer class and transported e_F."""
import json,subprocess,tempfile
from pathlib import Path
R=Path(__file__).resolve().parents[2]
def run(n):
 s=R/'research/voevodsky'/n;e=Path(tempfile.gettempdir())/(s.stem+'.exe');subprocess.run(['rustc','--edition=2021','-D','warnings','-O',str(s),'-o',str(e)],check=True);return json.loads(subprocess.check_output([str(e)],text=True))
g=run('check_d03_global_log_blowup_relative_q.rs');m=run('check_multirees_cartier_pl_cap.rs');b=run('check_d03_compatible_face_bm_cech_primitive_obstruction.rs')
checks={'eF_transport':g['result']['filtered_extension']['canonical_pullback_of_e_F'].startswith('YES'),'gallery_Q_zero':g['result']['exceptional_gallery']['relative_Q_image']=='zero','local_equality_missing':g['result']['beck_chevalley_yoneda']['local_gallery_equality']=='UNCONSTRUCTED','spatial_Ext_unidentified':m['factorization_test']['derived_Ext_claim']['spatial_Yoneda_Ext']=='NOT IDENTIFIED','spatial_correspondence_false':not m['factorization_test']['negative_controls']['spatial_correspondence_to_H_Sigma_e_F_Q'],'legal_BM_primitive_fails':b['factorization_test']['legal_BM_Cech'].startswith('FAIL'),'variance_repair_unconstructed':any('reciprocal line-dual' in x for x in b['unconstructed'])}
assert all(checks.values()),checks
out={'schema':'marici.voevodsky.CR1SP6-compare-BM-Kummer-with-eF.v1','action':'CR1SP6c_compare_target_first_BM_Kummer_class_with_transported_eF','outcome':'-+','available':['canonical transported global Yoneda extension e_F','canonical oriented Kummer-loaded relative BM class of value +1','saturated PL map and labelled multi-Rees coefficient bicomplex'],'obstruction':'the two classes live in separately typed derived objects; no spatial multi-Rees extraordinary pull-push gives the comparison morphism. In the legal BM-Cech packet the required primitive violates the denominator/support rule.','key_result':'target-first ordering removes strict-representative ambiguity but does not create the missing spatial Yoneda-to-BM comparison','refinement':['construct_marked_multi_Rees_spatial_correspondence_with_ti_epsilon_offdiagonal','verify_associated_grade_is_PL_1_minus_r','intertwine_eF_while_retaining_qSigma_nonboundary'],'parent_resolution':'CR1SP6=-+ by hard comparison failure','metric_delta':{'resolved_SP6_gates':1,'active_specialization_branches':-1,'executable_specialization_paths':-1,'geometrically_certified_complete_paths_percent':0.0,'new_typed_interfaces':0},'final_metrics':{'formal_signed_coherence_assignments':32,'active_specialization_branches':0,'executable_specialization_paths':0,'geometrically_certified_complete_paths':0,'typed_interfaces_accumulated':19},'checks':checks,'passed':True};p=R/'research/voevodsky/results/CR1SP6_compare_BM_Kummer_with_eF.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'outcome':'-+','SP6_parent':'-+','active_branches':0,'executable_paths':0,'survivors':32}))
