#!/usr/bin/env python3
"""Audit construction of tau0 as an A3-filtered relative Thom costalk."""
import json,subprocess,tempfile
from pathlib import Path
R=Path(__file__).resolve().parents[2]
def run(n):
 s=R/'research/voevodsky'/n;e=Path(tempfile.gettempdir())/(s.stem+'.exe');subprocess.run(['rustc','--edition=2021','-D','warnings','-O',str(s),'-o',str(e)],check=True);return json.loads(subprocess.check_output([str(e)],text=True))
a=run('check_d03_unlocalized_road_flag_aw.rs');t=run('check_d03_thom_endpoint_bc.rs');c=a['checks'];f=t['factorization_test']
checks={'algebra_d2':c['two_route_weighted_d_squared'].startswith('PASS'),'AW_carrier':c['endpoint_relative_AW'].startswith('PASS'),'rank121':c['total_H'].startswith('PASS'),'Bockstein':c['graph_Bockstein'].startswith('PASS'),'ringed_missing':'no spatial' in a['unconstructed']['ringed_six_functor_provenance'],'target_missing':'no unlocalized' in a['unconstructed']['target_Koszul_Cech'],'extraordinary_missing':f['actual_extraordinary_push_pull']=='NOT CONSTRUCTED','road_generizations_missing':f['actual_road_generizations']=='NOT SUPPLIED by the tensor model'}
assert all(checks.values()),checks
out={'schema':'marici.voevodsky.CR1-tau0-A3-filtered-relative-Thom-costalk.v1','action':'CR1PK1a2a1a1a_construct_tau0_A3_filtered_relative_Thom_costalk','outcome':'-+','proved':['unlocalized two-route weighted Koszul diamond','normalized endpoint-relative AW carrier','torsion-free total rank profile (1,2,1)','graph-Cartier Bockstein beta_x3(top)=+[t3] eta_mix','conditional endpoint divisibility criterion before base change'],'obstruction':'tau0 remains only an algebraic carrier symbol: no spatial gallery projections, ringed relative-dualizing trace, target unlocalized Koszul-Cech comparison, or road generization maps construct the costalk','new_interfaces':['tau0_unlocalized_algebraic_AW_shadow'],'refinement':['CR1PK1a2a1a1a1_construct_ringed_unmarked_gallery_correspondence','CR1PK1a2a1a1a2_construct_target_unlocalized_Koszul_Cech_comparison','CR1PK1a2a1a1a3_compute_road_generizations_before_base_change'],'next':'CR1PK1a2a1a1a1_construct_ringed_unmarked_gallery_correspondence','metric_delta':{'formal_coherence_survivors_percent':0.0,'geometrically_certified_complete_paths_percent':0.0,'new_typed_interfaces':1,'newly_blocked_descendant_branches':1},'checks':checks,'passed':True};p=R/'research/voevodsky/results/CR1_tau0_A3_filtered_relative_Thom_costalk.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'outcome':'-+','survivors':32,'new_interfaces':1,'next':out['next']}))
