#!/usr/bin/env python3
"""Tensor the canonical marked relative-BM class with reciprocal Kummer data."""
import json,subprocess,tempfile
from pathlib import Path
R=Path(__file__).resolve().parents[2]
def run(n):
 s=R/'research/voevodsky'/n;e=Path(tempfile.gettempdir())/(s.stem+'.exe');subprocess.run(['rustc','--edition=2021','-D','warnings','-O',str(s),'-o',str(e)],check=True);return json.loads(subprocess.check_output([str(e)],text=True))
o=run('check_one_normal_can_var_cousin.rs');x=run('check_d03_x3_loaded_pc_endpoint_boundary.rs');g=run('check_d03_whole_gallery_tag_gysin.rs');c=o['checks'];f=x['factorization_test'];k=g['checks']
checks={'BM_source':k['whole_gallery_BM_class']=='PASS','can_var':c['can_var_composites']=='PASS','perfect_pairing':c['pairing_perfectness'].startswith('PASS'),'repeated_excess':c['repeated_normal_exactness'].startswith('PASS'),'simultaneous_external_product':'canonical simultaneous external product' in x['claim'],'variance_retained':f['reciprocal_BM_variance'].startswith('PASS'),'Tor0':f['Tor0_quotient'].startswith('PASS'),'Tor1':f['Tor1_repeated_normal_excess'].startswith('PASS'),'Bockstein':f['filtered_Bockstein'].startswith('PASS'),'no_extra_localization':f['extra_base_localization']=='NONE'}
assert all(checks.values()),checks
out={'schema':'marici.voevodsky.CR1SP6-tensor-BM-reciprocal-Kummer.v1','action':'CR1SP6b_tensor_relative_BM_class_with_reciprocal_Kummer_packet','outcome':'++','construction':{'BM_factor':'canonical oriented full-gallery relative class -[n]','Kummer_factor':'reciprocal regular K(u3^vee) paired with original locally-finite K(u3)','excess_factor':'eta_3,mix=(-q3,-1), trace 1','tensor_properties':['perfect integral pairing','Tor0 and Tor1 retained','graph-Cartier Bockstein commutes','all lower Cech terms retained','no support-variable localization'],'associated_grade_value':'positive supported t3 tag and simultaneous positive v00/v10 coefficient residues'},'produces':['Kummer_loaded_full_gallery_relative_BM_class'],'boundary':'This proves the derived coefficient/costalk external product, not yet its identification with the transported support-filtration Yoneda class e_F.','next':'CR1SP6c_compare_target_first_BM_Kummer_class_with_transported_eF','metric_delta':{'resolved_SP6_gates':1,'remaining_SP6_depth':-1,'new_typed_interfaces':1,'gate_entropy_bits':-2.0,'parent_branch_entropy_bits':0.0},'checks':checks,'passed':True};p=R/'research/voevodsky/results/CR1SP6_tensor_BM_with_reciprocal_Kummer.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'outcome':'++','resolved_gates':'2/4','remaining_depth':2,'new_interfaces':1,'next':out['next']}))
