"""Prove every later K-target exponent is reachable from an A12 seed by natural ambient inclusions."""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];RES=ROOT/'research'/'voevodsky'/'results';OUT=RES/'cosmology_rank26_p_normal_uniform_target_reachability.json'
def exponents(A):return [(i,d-i) for d in range(A-3) for i in range(d+1)]
def decompose(A,e):
 steps=(A-12)//2;need=max(0,(sum(e)-8+1)//2);cap0=e[0]//2;cap1=e[1]//2;assert need<=cap0+cap1 and need<=steps;a=min(cap0,need);b=need-a;e0=(e[0]-2*a,e[1]-2*b);z=steps-a-b;assert min(*e0,z)>=0 and sum(e0)<=8;return a,b,z,e0
def main():
 total=0;max_steps=0
 for A in range(12,502,2):
  for e in exponents(A):
   a,b,z,e0=decompose(A,e);assert (e0[0]+2*a,e0[1]+2*b)==e and a+b+z==(A-12)//2;total+=1;max_steps=max(max_steps,a+b+z)
 base_boundary=json.loads((RES/'cosmology_rank26_p_normal_K_q_boundary_exact_all_a12.json').read_text());base_interior=json.loads((RES/'cosmology_rank26_p_normal_K_q_exact_base_all_shifts_a12.json').read_text());assert base_boundary['targets_verified']==48 and sum(len(v) for v in base_interior['results'].values())==42 and base_boundary['passed'] and base_interior['passed']
 out={'schema':'marici.voevodsky.cosmology-rank26-p-normal-uniform-target-reachability.v1','status':'every_even_ambient_target_reachable_from_complete_A12_seeds','base_ambient':12,'base_targets':90,'checked_even_ambient_range':[12,500],'target_decompositions_checked':total,'maximum_transition_steps_checked':max_steps,'theorem':'For A=12+2n and |e|<=A-4, choose s=max(0,ceil((|e|-8)/2))<=n square shifts distributed within floor(e_0/2)+floor(e_1/2), and n-s unchanged inclusions. The residual exponent has degree at most 8 and is an A12 seed.','decision':'The natural transition semigroup generated by unchanged inclusion and either axis-square multiplication reaches every K-target exponent at every even ambient degree A>=12.','limitations':['uses complete exact A12 seed existence','constructor naturality supplies transport but not a canonical word','colimit quotient construction is separate'],'passed':True};OUT.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
if __name__=='__main__':main()
