"""Reassess supported-comparison contract after algebraic source recovery."""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];RES=ROOT/'research'/'voevodsky'/'results';OUT=RES/'cosmology_supported_comparison_interface_v2.json'
FIELDS=('source_basis','source_differential','supported_target_basis','supported_target_differential','generator_map','support_localization','chain_residual')
def main():
 source=json.loads((RES/'cosmology_algebraic_source_differential.json').read_text());target=json.loads((RES/'cosmology_exceptional_triangle_relative_localization.json').read_text());special=json.loads((RES/'cosmology_exceptional_specialization_interface.json').read_text());words=json.loads((RES/'cosmology_source_geometrization_contract.json').read_text())
 population={'source_basis':{'populated':source['generator_count']==43564,'type':'labelled algebraic C1 basis'},'source_differential':{'populated':bool(source['complex']),'type':'two-term algebraic incidence map, not geometric realization'},'supported_target_basis':{'populated':len(target['primitive_cycle_standard_basis'])==3,'type':'three exceptional edges'},'supported_target_differential':{'populated':target['edge_boundary_rank']==2,'type':'triangle incidence boundary'},'generator_map':{'populated':False,'missing':'images of all 43,564 source generators'},'support_localization':{'populated':False,'missing':'blowup-derived correspondence from K/q loci to exceptional lines'},'chain_residual':{'populated':False,'missing':'boundary commutation residual for a sourced map'}}
 assert sum(v['populated'] for v in population.values())==4
 zero={'map':'zero','chain_residual':0,'authority':'abstract linear algebra'};zero_admissible=zero['authority']=='blowup-derived source specialization';assert not zero_admissible
 out={'schema':'marici.voevodsky.cosmology-supported-comparison-interface.v2','status':'four_chain_objects_populated_three_bridge_fields_missing','population':population,'populated_count':4,'missing_count':3,'evidence_revision':'Algebraic recovery supplies source basis and incidence differential; exceptional localization supplies target basis and boundary. The original seven-field audit had all fields absent.','strongest_falsification':{'candidate':'use the abstract zero chain map','residual':'The zero map commutes formally but has no blowup-derived specialization or support-localization authority and does not identify the principal-wall first jet.','rejected':True},'surviving_scope':'Separately typed algebraic source complex and exceptional triangle target complex, plus exact all-even absorption and transport.','blocker':'The previously recorded source-derived support correspondence is still the first missing bridge; generator images and chain residual depend on it.','disposition':'Do not open another bridge request. Preserve the three-field blocker and test the independent algebraic relative-Bockstein consequence of exact absorption.','next_gate':'compute-algebraic-relative-bockstein-of-certified-words','passed':True}
 OUT.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
if __name__=='__main__':main()
