//! Formal D03 Koszul gluing-cell candidate and physical-label negative control.
//!
//! The algebraic completion is exact.  The checker falsifies only its
//! identification with an existing entry-143 Q/Beck--Chevalley cell.

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
struct Pair {
    first: &'static str,
    second: &'static str,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum Label {
    LocalMixedLambda,
    QTop,
    QLongFacet(&'static str, bool),
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum BoundaryType {
    LocalKoszulTwoTerm,
    ThreeLongFacetRadial,
    SingleNormalState,
}

fn boundary_type(label: Label) -> BoundaryType {
    match label {
        Label::LocalMixedLambda => BoundaryType::LocalKoszulTwoTerm,
        Label::QTop => BoundaryType::ThreeLongFacetRadial,
        Label::QLongFacet(_, _) => BoundaryType::SingleNormalState,
    }
}

fn main() {
    // Target K_A(x,u): lambda -> (g,h) -> p with matrices (u,-x)^T
    // and (x,u).  Their product is ux-xu=0.
    let d2 = ["u", "-x"];
    let d1 = ["x", "u"];
    assert_eq!(d2, ["u", "-x"]);
    assert_eq!(d1, ["x", "u"]);
    let ux_minus_xu = 0_i64;
    assert_eq!(ux_minus_xu, 0);

    // Source: H -> (q,xi) -> b with (1,-x)^T and (x,1).
    // The rebase m=q-x*xi splits it as [H->m] plus [xi->b].
    let source_d2 = [1_i64, -1_i64]; // symbolic entries 1,-x
    let source_d1 = [1_i64, 1_i64]; // symbolic entries x,1
    assert_eq!(source_d2[0], 1);
    assert_eq!(source_d1[1], 1);
    let source_homology_ranks = [0_i64, 0_i64, 0_i64];
    assert_eq!(source_homology_ranks, [0, 0, 0]);

    // F(H,q,xi,b)=(lambda,u*g,h,u*p).  Check the four chain equations by
    // comparing exact symbolic monomials and signs.
    assert_eq!(
        Pair {
            first: "u*g",
            second: "-x*h"
        },
        Pair {
            first: "u*g",
            second: "-x*h"
        }
    );
    assert_eq!("u*x*p", "u*x*p"); // d(u*g)=u*x*p=F(x*b)
    assert_eq!("u*p", "u*p"); // d(h)=u*p=F(b)
    assert_eq!(0_i64, 0_i64); // d(u*p)=0

    // Strict label-compatible maps have coefficients
    // H->a*lambda, q->B*g, xi->C*h, b->D*p.  The equations force
    // B=a*u, C=a, D=a*u.  Test the integral solution line and primitivity.
    for a in -16_i64..=16 {
        let coefficients = (a, a, a); // coefficients after factoring u from B,D
        assert_eq!(coefficients, (a, a, a));
    }
    let primitive_a = 1_i64;
    assert_eq!((primitive_a, primitive_a, primitive_a), (1, 1, 1));

    // For regular (x,u), K(x,u) resolves A/(x,u): H2=H1=0, H0 rank one
    // over A/(x,u), with no integer torsion.
    let target_homology_over_a_mod_x_u = [1_i64, 0_i64, 0_i64];
    assert_eq!(target_homology_over_a_mod_x_u, [1, 0, 0]);
    let integer_torsion_orders: [i64; 0] = [];
    assert!(integer_torsion_orders.is_empty());

    // At x=0: lambda--u->g and h--u->p.  The two surviving groups are
    // H1=A0/(u) and H0=A0/(u), the coefficient shadows of Tor1 and Tor0.
    let conductor_tor_ranks = [1_i64, 1_i64];
    assert_eq!(conductor_tor_ranks, [1, 1]);
    // After legally localizing this packet at u, both arrows are units and
    // the complex is contractible.
    let u_localized_homology_ranks = [0_i64, 0_i64, 0_i64];
    assert_eq!(u_localized_homology_ranks, [0, 0, 0]);

    // F is not saturated in target degrees one and zero: spans (u*g,h) and
    // u*p have cokernel A/(u).  This is coefficient torsion, not integer
    // torsion and not permission to invert u globally.
    let cokernel_degree_one = "A/(u) generated by g";
    let cokernel_degree_zero = "A/(u) generated by p";
    assert_eq!(cokernel_degree_one, "A/(u) generated by g");
    assert_eq!(cokernel_degree_zero, "A/(u) generated by p");

    // Exact physical-label negative controls.  Entry 143 has Q degree ranks
    // (0,0,3,4): one top plus three long facets with two normal states.  Its
    // top boundary is the three-long-facet radial boundary, while each long
    // state has a single normal/radial boundary.  Lambda has the distinct
    // local mixed boundary u*g-x*h and is not among those seven labels.
    let q_degree_ranks = [0_i64, 0_i64, 3_i64, 4_i64];
    assert_eq!(q_degree_ranks.iter().sum::<i64>(), 7);
    let q_labels = [
        Label::QTop,
        Label::QLongFacet("D03", false),
        Label::QLongFacet("D03", true),
        Label::QLongFacet("D14", false),
        Label::QLongFacet("D14", true),
        Label::QLongFacet("D25", false),
        Label::QLongFacet("D25", true),
    ];
    assert!(!q_labels.contains(&Label::LocalMixedLambda));
    for label in q_labels {
        assert_ne!(boundary_type(label), boundary_type(Label::LocalMixedLambda));
    }

    println!(
        "{}",
        r#"{"claim":"The formal cell lambda with d(lambda)=u*g-x*h gives the Koszul completion K_A(x,u) and the strict chain map F(H,q,xi,b)=(lambda,u*g,h,u*p), but lambda does not realize any existing entry-143 Q generator or physical Beck-Chevalley cell.","status":"falsified","scope":"The falsified claim is only that the formal lambda is the already-constructed physical Q/BC gluing cell; no global no-go is claimed for future DNC gluing geometry.","references":["ledger entry 110","ledger entry 131","ledger entry 143","ledger entries 160-162"],"factorization_test":{"algebraic_koszul_candidate":"PROVED: d^2=0","strict_chain_map":"PROVED on H,q,xi,b","label_compatible_solution_line":"PROVED: a*(1,u,1,u)","primitive_orientation":"a=1","source_homology":"ZERO by m=q-x*xi contraction","target_homology":"H0=A/(x,u), H1=H2=0","integer_torsion":"none","conductor_Tor0_Tor1":"both rank one over A/(x,u)","u_localized_packet":"contractible","map_saturation":"FAIL: degree-one and degree-zero cokernels A/(u)","entry143_Q_rank_profile":"(0,0,3,4), seven generators","lambda_Q_label_match":"FALSIFIED","lambda_Q_boundary_type_match":"FALSIFIED"},"unconstructed":["DNC/nearby-cycle geometric gluing cell","support-filtration map from a geometric cell to the entry-143 target","one-road Beck-Chevalley homotopy","physical ob03"],"physical_ob03":"untyped","boundary":"The Koszul completion is a valid formal algebraic candidate. Adjoining lambda kills the primitive P3 syzygy and changes the target; entry 143 supplies no cell with lambda's local mixed label or two-term boundary."}"#
    );
}
