"""Audit whether the computational dependency chain materializes a global carrier center."""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'research'/'voevodsky'/'results'/'cosmology_carrier_center_source_extraction.json'
def main():
 artifacts={'exceptional_localization_checker':'hardcoded P2 triangle incidence','semistable_cone_checker':'hardcoded local A3 transverse triple','DNC_factorization_checker':'rank-row result composition','full_rank26_checker':'loads algebraic result JSON and counts relation families'}
 required={'global_carrier_scheme':False,'principal_ideal_sheaf':False,'regular_embedding_certificate':False,'global_wall_sections':False,'transition_cocycle':False,'map_from_relation_module_to_geometry':False}
 assert not any(required.values())
 out={'schema':'marici.voevodsky.cosmology-carrier-center-source-extraction.v1','status':'authoritative_dependency_chain_contains_local_slice_and_relation_modules_but_no_global_carrier_center','audited_artifacts':artifacts,'missing_global_contract':required,'positive_evidence':['local ideal (U,V,U+V+P)=(U,V,P)','local Jacobian determinant one','exceptional fiber P2 with labeled triangle','rank26 p-normal relation-module absorption'],'negative_boundary':'None of the audited authoritative dependencies defines a global scheme or stack X, a sheaf ideal I_C, global wall sections, an atlas/transition cocycle, or a chain map from the rank26 presentation to the ambient blowup geometry.','consequence':'Globalization cannot be asserted or falsified from these artifacts. The local integral HomotopyLift remains valid, and the conditional regularity theorem remains the exact carrier gate.','required_source_packet':['definition of X and C','proof that I_C/I_C^2 has rank three','three globally labeled conormal sections','orientation/monodromy data','comparison from the relation presentation to the geometric DNC complex'],'decision':'The source-extraction leaf closes with a typed missing-constructor result: the programme lacks a materialized global carrier object, not merely a difficult smoothness proof.','next_gate':'universal-ordered-triple-horn: construct the lift universally over the moduli/category of ordered transverse triples so any future carrier map can pull it back','limitations':['bounded audit of the dependency chain used by the current rank26 and exceptional-triangle theorems','does not claim no global carrier definition exists outside the materialized chain','no shell-wide repository search was authorized or performed'],'passed':True};OUT.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
if __name__=='__main__':main()
