"""Relative base-fiber comparison gate for the tau_p horn.

Repeat iteration 3 tests the route left open by the gradient-pivot type gate:
retain the base-dependent c pivot in a relative total space.  This restores a
three-chart source face, but the projection to the fixed target fiber has a
kernel.  A section of that kernel to the Xi_log leg is precisely the unsourced
datum.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
VOEVODSKY_RESULTS = ROOT / "research" / "voevodsky" / "results"
NIMA_RESULTS = ROOT / "research" / "nima" / "results"
OUT = VOEVODSKY_RESULTS / "cosmology_relative_base_fiber_comparison_gate.json"


def load(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def rank_mod_prime(matrix: list[list[int]], prime: int) -> int:
    rows = [[entry % prime for entry in row] for row in matrix]
    if not rows:
        return 0
    rank = 0
    row_count = len(rows)
    col_count = len(rows[0]) if rows else 0
    for col in range(col_count):
        pivot = next((r for r in range(rank, row_count) if rows[r][col] % prime), None)
        if pivot is None:
            continue
        rows[rank], rows[pivot] = rows[pivot], rows[rank]
        inv = pow(rows[rank][col], -1, prime)
        rows[rank] = [(value * inv) % prime for value in rows[rank]]
        for r in range(row_count):
            if r == rank:
                continue
            factor = rows[r][col] % prime
            if factor:
                rows[r] = [(a - factor * b) % prime for a, b in zip(rows[r], rows[rank])]
        rank += 1
    return rank


def mat_vec(matrix: list[list[int]], vector: list[int]) -> list[int]:
    return [sum(row[i] * vector[i] for i in range(len(vector))) for row in matrix]


def main() -> None:
    native_limit = load(VOEVODSKY_RESULTS / "cosmology_native_three_chart_cover_limit.json")
    contract = load(VOEVODSKY_RESULTS / "cosmology_tau_source_map_contract.json")
    pivot = load(NIMA_RESULTS / "cosmology_tau_gradient_pivot_type_gate.json")

    assert native_limit["passed"] is True
    assert contract["passed"] is True
    assert pivot["passed"] is True
    assert pivot["normal_adapter_pivots"] == ["a", "b", "c"]
    assert pivot["target_fiber_coordinates"] == ["a", "b"]
    assert pivot["c_pivot_role"].startswith("base-dependent")

    # Relative total-space projection from pivot coordinates (a,b,c) to the
    # fixed target fiber (a,b).  It restores the three-chart domain but has a
    # kernel generated by c.
    projection = [[1, 0, 0], [0, 1, 0]]
    c_kernel = [0, 0, 1]
    assert mat_vec(projection, c_kernel) == [0, 0]

    # Retaining c supplies the Cech face leg, but the Xi_log coefficient is a
    # section choice through the projection kernel.  Current packets supply no
    # such section, so the actual sourced column remains only (0,1).
    required_tau = [1, 1]
    retained_c_without_section = [0, 1]
    hypothetical_unit_section = [1, 1]
    assert retained_c_without_section != required_tau
    assert hypothetical_unit_section == required_tau

    witnesses = {}
    for prime in (101, 103):
        projection_rank = rank_mod_prime(projection, prime)
        augmented_with_kernel_rank = rank_mod_prime([[1, 0, 0], [0, 1, 0], [0, 0, 1]], prime)
        current_rank = rank_mod_prime([[0], [1]], prime)
        current_plus_tau_rank = rank_mod_prime([[0, 1], [1, 1]], prime)
        assert projection_rank == 2
        assert augmented_with_kernel_rank == 3
        assert current_rank == 1
        assert current_plus_tau_rank == 2
        witnesses[str(prime)] = {
            "relative_total_projection_rank": projection_rank,
            "rank_after_retaining_c_kernel": augmented_with_kernel_rank,
            "current_column_rank": current_rank,
            "current_plus_required_tau_rank": current_plus_tau_rank,
            "kernel_section_to_Xi_log_supplied": False,
        }

    result = {
        "schema": "marici.voevodsky.cosmology-relative-base-fiber-comparison-gate.v1",
        "status": "relative_total_space_restores_three_charts_but_kernel_section_to_Xi_absent",
        "rechecked_inputs": [
            "research/voevodsky/results/cosmology_native_three_chart_cover_limit.json",
            "research/voevodsky/results/cosmology_tau_source_map_contract.json",
            "research/nima/results/cosmology_tau_gradient_pivot_type_gate.json",
        ],
        "source_pivots": ["a", "b", "c"],
        "target_fixed_fiber_coordinates": ["a", "b"],
        "projection_rows_a_b_cols_a_b_c": projection,
        "projection_kernel_generator": c_kernel,
        "effect_of_retaining_c": "restores a three-chart relative source domain but introduces a kernel invisible to the fixed-fiber target",
        "column_without_kernel_section_rows_Xi_minusSigma": retained_c_without_section,
        "required_tau_column_rows_Xi_minusSigma": required_tau,
        "hypothetical_unit_section_column": hypothetical_unit_section,
        "finite_field_witnesses": witnesses,
        "decision": "the relative base-fiber route is the right typed place for the c pivot, but it only converts the problem into constructing a kernel section whose Xi_log coefficient is a unit",
        "next_gate": "construct a source-derived section of the c/base kernel into the logarithmic residue exact sequence and test that its column is (1,1) up to sign",
        "relative_bockstein_constructed": False,
        "physical_period_constructed": False,
        "passed": True,
    }
    OUT.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
