"""Exact rank test for transport on the spans generated by twelve filtered classes."""
from __future__ import annotations
import json
from fractions import Fraction
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];RES=ROOT/'research'/'voevodsky'/'results';OUT=RES/'cosmology_twelve_class_cyclic_span.json'
def freeze(x):return tuple(freeze(y) for y in x) if isinstance(x,list) else x
def row(record):return {freeze(t['column_label']):Fraction(t['numerator'],t['denominator']) for t in record['residual_terms']}
def add(r,b,a):
 for c,v in b.items():
  z=r.get(c,Fraction())+a*v
  if z:r[c]=z
  else:r.pop(c,None)
def rank(rows):
 basis={}
 for raw in rows:
  r=dict(raw)
  while r:
   p=min(r)
   if p not in basis:
    inv=1/r[p];basis[p]={c:v*inv for c,v in r.items()};break
   add(r,basis[p],-r[p])
 return len(basis)
def main():
 c14=json.loads((RES/'cosmology_filtered_classification_transport.json').read_text());c16=json.loads((RES/'cosmology_filtered_A16_persistence_induction.json').read_text());A12=c14['A12_classes'];A14=c14['A14_transports'];A16=c16['A16_classes'];l14={(x['target_id'],x['axis_square']):x for x in A14};l16={(x['target_id'],x['axis_square']):x for x in A16};checks=[]
 for g in (6,7,8):
  src12=[x for x in A12 if x['grade']==g];assert len(src12)==4
  for axis in ('x2','y2'):
   images=[l14[(x['target_id'],axis)] for x in src12];rs=rank(map(row,src12));ri=rank(map(row,images));checks.append({'source_A':12,'target_A':14,'grade':g,'axis':axis,'orbit_elements':4,'source_span_rank':rs,'image_span_rank':ri,'restricted_kernel_dimension':rs-ri})
  src14=[x for x in A14 if x['grade']==g];assert len(src14)==8
  for axis in ('x2','y2'):
   paths={'x2':{'x2':'xx','y2':'yx'},'y2':{'x2':'xy','y2':'yy'}}[axis];images=[l16[(x['target_id'],paths[x['axis_square']])] for x in src14];rs=rank(map(row,src14));ri=rank(map(row,images));checks.append({'source_A':14,'target_A':16,'grade':g,'axis':axis,'orbit_elements':8,'source_span_rank':rs,'image_span_rank':ri,'restricted_kernel_dimension':rs-ri})
 total=sum(x['restricted_kernel_dimension'] for x in checks);assert total>=0
 out={'schema':'marici.voevodsky.cosmology-twelve-class-cyclic-span.v1','status':('tested_class_spans_injective_through_A16' if total==0 else 'distinguished_span_kernel_intersections_found'),'exact_checks':checks,'total_restricted_kernel_dimension':total,'decision':('The grade-wise spans generated by all twelve class orbit elements avoid every immediate transport kernel through A16.' if total==0 else 'Rank loss gives exact combinations of distinguished orbit elements killed by transport.'),'claim_boundary':'Finite span injectivity through A16 does not prove injectivity of the infinite Q[x2,y2]-cyclic module.','next_gate':('derive-twelve-class-cyclic-module-presentation' if total==0 else 'classify-distinguished-span-kernel-combinations'),'passed':True};OUT.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
if __name__=='__main__':main()
