//! Actual P_abs pullback to the seven-triangle D03 Morse carrier.
//!
//! The 215-generator absolute complex is reconstructed exactly as in
//! `check_absolute_unlocalized_support_pc.rs`.  For a face S and oriented
//! circle subset H its differential is
//!
//!   d(S,H)=sum_a eps(S,a) X_a(S+a,H)
//!          +(-1)^(3-|S|) sum_h (-1)^pos u_h(S,H-h).
//!
//! The D03 blowup face poset has the order-preserving blowdown functor which
//! replaces E by {D03,x1}.  Pulling the covariant P_abs coefficient cosheaf
//! back along this functor and taking its barycentric simplicial replacement
//! is variance-correct: a flag S0<...<Sk is loaded at S0; deleting S0 applies
//! the lcm quotient label(S1)/label(S0), while every other simplicial face is
//! a unit map.  Normal-circle differential is totalized with sign (-1)^k.
//! The checker verifies the complete weighted differential and d^2=0.
//!
//! On the mixed seven-triangle carrier this functorial differential forces
//!
//!   d H_Morse^abs = q_J^abs - x3*xi_tilde^abs.
//!
//! It does not give q_J^abs-xi_tilde^abs over the unlocalized occurrence
//! polynomial ring.  The first mismatch is the common x3 factor supplied by
//! deleting each sector apex.  The special term x3*xi lies in I3=(x3), and
//! Hom_R(I3,R) evaluates it canonically to xi without inverting x3.  But none
//! of H_Morse's seven terms or q_J's three terms lies in I3, so this evaluation
//! is not a global operation on the identity.
//!
//! There is a canonical relative-boundary Gysin repair.  With the auxiliary
//! occurrence Koszul incidence K_occ(x3)=[R<h3>--x3-->R<p],
//!
//!   d(H_Morse*p-xi*h3)=q_J*p-dxi*h3.
//!
//! The checker verifies this full identity and its square.  It is not a global
//! I3-dual evaluation and creates no nonzero ambient Q class: its right side is
//! the displayed boundary.  K_occ(x3) is an occurrence-ideal construction and
//! is kept separate from P_abs's monodromy-normal variables.
//!
//! There is nevertheless a smaller, explicitly typed relative statement.  Let
//! E be the endpoint subcomplex generated by a and c, and put
//!
//!   B=(C_carrier/E)/(R*q_J).
//!
//! Since d(q_J)=x3*d(xi) is endpoint-supported, R*q_J is a subcomplex after
//! the first quotient.  In B, d[H_Morse]=-x3*[xi].  Hence H_Morse mod x3 is a
//! cycle and the Cartier/Koszul connecting map is
//!
//!   delta([H_Morse mod x3])=[-x3*xi] in H_1(I3*B).
//!
//! With the chosen negative seven-triangle thimble and positive x3 normal
//! d(h3)=+x3*p, ideal-dual evaluation sends this to -[xi].  Reversing either
//! orientation reverses the sign.  A specialization/rank certificate proves
//! that [xi] survives in this smallest relative carrier; it is x3-torsion but
//! is not a boundary.  This relative Bockstein is not a global sp_G map.
//!
//! The coefficient of [top<D03] in q_J is +1.  This agrees with both the
//! absolute incidence eps(empty,D03)=+1 and the established ordered-normal
//! convention 0<3.  No H_cond, sp_G, purity, monodromy, or Theta map is made.

use std::collections::{BTreeMap, BTreeSet};

type Z = i64;
const N: u8 = 6;
const DIMENSION: usize = 3;
const VARIABLES: usize = 9;

#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
struct Diagonal(u8, u8);

type OldFace = BTreeSet<Diagonal>;

#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
enum Ray {
    Old(Diagonal),
    Exceptional,
}

type BlowFace = BTreeSet<Ray>;
type BarySimplex = Vec<BlowFace>;

fn diagonal(first: u8, second: u8) -> Diagonal {
    if first < second {
        Diagonal(first, second)
    } else {
        Diagonal(second, first)
    }
}

fn boundary_edge(value: Diagonal) -> bool {
    value.1 - value.0 == 1 || value == Diagonal(0, N - 1)
}

fn between(vertex: u8, first: u8, second: u8) -> bool {
    let span = (second + N - first) % N;
    let position = (vertex + N - first) % N;
    position > 0 && position < span
}

fn crosses(first: Diagonal, second: Diagonal) -> bool {
    if [first.0, first.1]
        .iter()
        .any(|endpoint| *endpoint == second.0 || *endpoint == second.1)
    {
        return false;
    }
    between(second.0, first.0, first.1) != between(second.1, first.0, first.1)
        && between(first.0, second.0, second.1) != between(first.1, second.0, second.1)
}

fn all_diagonals() -> Vec<Diagonal> {
    (0..N)
        .flat_map(|first| ((first + 1)..N).map(move |second| diagonal(first, second)))
        .filter(|value| !boundary_edge(*value))
        .collect()
}

fn short_diagonal(index: usize) -> Diagonal {
    diagonal(index as u8, (index as u8 + 2) % N)
}

fn short_index(value: Diagonal) -> Option<usize> {
    (0..6).find(|index| short_diagonal(*index) == value)
}

fn long_index(value: Diagonal) -> Option<usize> {
    (0..3).find(|index| diagonal(*index as u8, *index as u8 + 3) == value)
}

fn variable_index(value: Diagonal) -> usize {
    short_index(value).unwrap_or_else(|| 6 + long_index(value).expect("a K6 diagonal"))
}

fn noncrossing(face: &OldFace) -> bool {
    face.iter().enumerate().all(|(position, first)| {
        face.iter()
            .skip(position + 1)
            .all(|second| !crosses(*first, *second))
    })
}

fn old_faces_by_size() -> Vec<Vec<OldFace>> {
    let diagonals = all_diagonals();
    let mut result = vec![Vec::new(); DIMENSION + 1];
    for mask in 0_u16..(1_u16 << diagonals.len()) {
        let size = mask.count_ones() as usize;
        if size > DIMENSION {
            continue;
        }
        let face: OldFace = diagonals
            .iter()
            .enumerate()
            .filter(|(index, _)| mask & (1 << index) != 0)
            .map(|(_, diagonal)| *diagonal)
            .collect();
        if noncrossing(&face) {
            result[size].push(face);
        }
    }
    for faces in &mut result {
        faces.sort();
    }
    assert_eq!(
        result.iter().map(Vec::len).collect::<Vec<_>>(),
        [1, 9, 21, 14]
    );
    result
}

fn addable(face: &OldFace, value: Diagonal) -> bool {
    !face.contains(&value)
        && face.len() < DIMENSION
        && face.iter().all(|present| !crosses(*present, value))
}

fn incidence_sign(face: &OldFace, added: Diagonal) -> Z {
    if face.iter().filter(|present| **present < added).count() % 2 == 0 {
        1
    } else {
        -1
    }
}

fn subsets(face: &OldFace) -> Vec<OldFace> {
    let values: Vec<_> = face.iter().copied().collect();
    (0_u16..(1_u16 << values.len()))
        .map(|mask| {
            values
                .iter()
                .enumerate()
                .filter(|(index, _)| mask & (1 << index) != 0)
                .map(|(_, value)| *value)
                .collect()
        })
        .collect()
}

#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
struct UniversalMonomial {
    occurrence: [u8; VARIABLES],
    normal: [u8; VARIABLES],
}

impl UniversalMonomial {
    fn one() -> Self {
        Self {
            occurrence: [0; VARIABLES],
            normal: [0; VARIABLES],
        }
    }

    fn occurrence(value: Diagonal) -> Self {
        let mut result = Self::one();
        result.occurrence[variable_index(value)] = 1;
        result
    }

    fn occurrence_face(face: &OldFace) -> Self {
        face.iter().fold(Self::one(), |product, value| {
            product.multiply(Self::occurrence(*value))
        })
    }

    fn normal(value: Diagonal) -> Self {
        let mut result = Self::one();
        result.normal[variable_index(value)] = 1;
        result
    }

    fn multiply(self, other: Self) -> Self {
        Self {
            occurrence: std::array::from_fn(|index| {
                self.occurrence[index] + other.occurrence[index]
            }),
            normal: std::array::from_fn(|index| self.normal[index] + other.normal[index]),
        }
    }

    fn occurrence_lcm(self, other: Self) -> Self {
        assert!(self.normal.iter().all(|power| *power == 0));
        assert!(other.normal.iter().all(|power| *power == 0));
        Self {
            occurrence: std::array::from_fn(|index| {
                self.occurrence[index].max(other.occurrence[index])
            }),
            normal: [0; VARIABLES],
        }
    }

    fn occurrence_quotient(self, divisor: Self) -> Self {
        assert!(self.normal.iter().all(|power| *power == 0));
        assert!(divisor.normal.iter().all(|power| *power == 0));
        assert!((0..VARIABLES).all(|index| self.occurrence[index] >= divisor.occurrence[index]));
        Self {
            occurrence: std::array::from_fn(|index| {
                self.occurrence[index] - divisor.occurrence[index]
            }),
            normal: [0; VARIABLES],
        }
    }

    fn divisible_by_occurrence(self, value: Diagonal) -> bool {
        self.occurrence[variable_index(value)] > 0
    }

    fn divide_occurrence_generator(self, value: Diagonal) -> Self {
        assert!(self.divisible_by_occurrence(value));
        let mut result = self;
        result.occurrence[variable_index(value)] -= 1;
        result
    }
}

#[derive(Clone, Debug, Eq, Ord, PartialEq, PartialOrd)]
struct AbsoluteGenerator {
    face: OldFace,
    circles: OldFace,
}

impl AbsoluteGenerator {
    fn degree(&self) -> usize {
        DIMENSION - self.face.len() + self.circles.len()
    }
}

type AbsoluteCombination = BTreeMap<(AbsoluteGenerator, UniversalMonomial), Z>;

fn add_absolute(
    value: &mut AbsoluteCombination,
    generator: AbsoluteGenerator,
    monomial: UniversalMonomial,
    coefficient: Z,
) {
    *value.entry((generator.clone(), monomial)).or_default() += coefficient;
    if value[&(generator.clone(), monomial)] == 0 {
        value.remove(&(generator, monomial));
    }
}

fn absolute_boundary(generator: &AbsoluteGenerator) -> AbsoluteCombination {
    let mut result = AbsoluteCombination::new();
    for added in all_diagonals()
        .into_iter()
        .filter(|value| addable(&generator.face, *value))
    {
        let mut target = generator.face.clone();
        target.insert(added);
        add_absolute(
            &mut result,
            AbsoluteGenerator {
                face: target,
                circles: generator.circles.clone(),
            },
            UniversalMonomial::occurrence(added),
            incidence_sign(&generator.face, added),
        );
    }
    let base_dimension = DIMENSION - generator.face.len();
    for (position, removed) in generator.circles.iter().copied().enumerate() {
        let mut circles = generator.circles.clone();
        circles.remove(&removed);
        let sign = if (base_dimension + position) % 2 == 0 {
            1
        } else {
            -1
        };
        add_absolute(
            &mut result,
            AbsoluteGenerator {
                face: generator.face.clone(),
                circles,
            },
            UniversalMonomial::normal(removed),
            sign,
        );
    }
    result
}

fn absolute_boundary_combination(value: &AbsoluteCombination) -> AbsoluteCombination {
    let mut result = AbsoluteCombination::new();
    for ((generator, scalar), coefficient) in value {
        for ((target, monomial), boundary_coefficient) in absolute_boundary(generator) {
            add_absolute(
                &mut result,
                target,
                scalar.multiply(monomial),
                coefficient * boundary_coefficient,
            );
        }
    }
    result
}

fn check_actual_absolute_complex(by_size: &[Vec<OldFace>]) {
    let generators: Vec<_> = by_size
        .iter()
        .flatten()
        .flat_map(|face| {
            subsets(face).into_iter().map(|circles| AbsoluteGenerator {
                face: face.clone(),
                circles,
            })
        })
        .collect();
    assert_eq!(generators.len(), 215);
    assert_eq!(
        (0..=DIMENSION)
            .map(|degree| generators
                .iter()
                .filter(|generator| generator.degree() == degree)
                .count())
            .collect::<Vec<_>>(),
        [14, 63, 93, 45]
    );
    for generator in &generators {
        assert!(absolute_boundary_combination(&absolute_boundary(generator)).is_empty());
    }
}

fn old_as_blowup(face: &OldFace) -> BlowFace {
    face.iter().copied().map(Ray::Old).collect()
}

fn blowup_faces(old: &[Vec<OldFace>], first: Diagonal, second: Diagonal) -> BTreeSet<BlowFace> {
    let mut result = BTreeSet::new();
    for face in old.iter().flatten() {
        if !(face.contains(&first) && face.contains(&second)) {
            result.insert(old_as_blowup(face));
            continue;
        }
        let remainder: BlowFace = face
            .iter()
            .filter(|value| **value != first && **value != second)
            .copied()
            .map(Ray::Old)
            .collect();
        for retained in [None, Some(first), Some(second)] {
            let mut replacement = remainder.clone();
            replacement.insert(Ray::Exceptional);
            if let Some(value) = retained {
                replacement.insert(Ray::Old(value));
            }
            result.insert(replacement);
        }
    }
    result
}

fn blowdown(face: &BlowFace, d03: Diagonal, x1: Diagonal) -> OldFace {
    let mut result: OldFace = face
        .iter()
        .filter_map(|ray| match ray {
            Ray::Old(value) => Some(*value),
            Ray::Exceptional => None,
        })
        .collect();
    if face.contains(&Ray::Exceptional) {
        result.insert(d03);
        result.insert(x1);
    }
    assert!(noncrossing(&result));
    result
}

fn extend_barycentric_chain(
    faces: &BTreeSet<BlowFace>,
    chain: &mut BarySimplex,
    result: &mut BTreeSet<BarySimplex>,
) {
    result.insert(chain.clone());
    let last = chain.last().expect("nonempty flag");
    let successors: Vec<_> = faces
        .iter()
        .filter(|face| last.len() < face.len() && last.is_subset(face))
        .cloned()
        .collect();
    for successor in successors {
        chain.push(successor);
        extend_barycentric_chain(faces, chain, result);
        chain.pop();
    }
}

fn barycentric_subdivision(faces: &BTreeSet<BlowFace>) -> BTreeSet<BarySimplex> {
    let mut result = BTreeSet::new();
    for face in faces {
        let mut chain = vec![face.clone()];
        extend_barycentric_chain(faces, &mut chain, &mut result);
    }
    result
}

#[derive(Clone, Debug, Eq, Ord, PartialEq, PartialOrd)]
struct PullbackGenerator {
    simplex: BarySimplex,
    circles: OldFace,
}

impl PullbackGenerator {
    fn degree(&self) -> usize {
        self.simplex.len() - 1 + self.circles.len()
    }
}

type PullbackCombination = BTreeMap<(PullbackGenerator, UniversalMonomial), Z>;

fn add_pullback(
    value: &mut PullbackCombination,
    generator: PullbackGenerator,
    monomial: UniversalMonomial,
    coefficient: Z,
) {
    *value.entry((generator.clone(), monomial)).or_default() += coefficient;
    if value[&(generator.clone(), monomial)] == 0 {
        value.remove(&(generator, monomial));
    }
}

fn lcm_structure_monomial(source: &OldFace, target: &OldFace) -> UniversalMonomial {
    assert!(source.is_subset(target));
    UniversalMonomial::occurrence_face(&target.difference(source).copied().collect())
}

fn pullback_boundary(
    generator: &PullbackGenerator,
    d03: Diagonal,
    x1: Diagonal,
) -> PullbackCombination {
    let mut result = PullbackCombination::new();
    let base_dimension = generator.simplex.len() - 1;
    if generator.simplex.len() >= 2 {
        for removed in 0..generator.simplex.len() {
            let mut simplex = generator.simplex.clone();
            simplex.remove(removed);
            let sign = if removed % 2 == 0 { 1 } else { -1 };
            let monomial = if removed == 0 {
                let source = blowdown(&generator.simplex[0], d03, x1);
                let target = blowdown(&generator.simplex[1], d03, x1);
                lcm_structure_monomial(&source, &target)
            } else {
                UniversalMonomial::one()
            };
            add_pullback(
                &mut result,
                PullbackGenerator {
                    simplex,
                    circles: generator.circles.clone(),
                },
                monomial,
                sign,
            );
        }
    }
    for (position, removed) in generator.circles.iter().copied().enumerate() {
        let mut circles = generator.circles.clone();
        circles.remove(&removed);
        let sign = if (base_dimension + position) % 2 == 0 {
            1
        } else {
            -1
        };
        add_pullback(
            &mut result,
            PullbackGenerator {
                simplex: generator.simplex.clone(),
                circles,
            },
            UniversalMonomial::normal(removed),
            sign,
        );
    }
    result
}

fn pullback_boundary_combination(
    value: &PullbackCombination,
    d03: Diagonal,
    x1: Diagonal,
) -> PullbackCombination {
    let mut result = PullbackCombination::new();
    for ((generator, scalar), coefficient) in value {
        for ((target, monomial), boundary_coefficient) in pullback_boundary(generator, d03, x1) {
            add_pullback(
                &mut result,
                target,
                scalar.multiply(monomial),
                coefficient * boundary_coefficient,
            );
        }
    }
    result
}

fn check_full_pullback_complex(
    barycentric: &BTreeSet<BarySimplex>,
    d03: Diagonal,
    x1: Diagonal,
) -> (usize, Vec<usize>) {
    let generators: Vec<_> = barycentric
        .iter()
        .flat_map(|simplex| {
            let initial = blowdown(&simplex[0], d03, x1);
            subsets(&initial)
                .into_iter()
                .map(|circles| PullbackGenerator {
                    simplex: simplex.clone(),
                    circles,
                })
                .collect::<Vec<_>>()
        })
        .collect();
    for generator in &generators {
        assert!(generator
            .circles
            .is_subset(&blowdown(&generator.simplex[0], d03, x1)));
        assert!(
            pullback_boundary_combination(&pullback_boundary(generator, d03, x1), d03, x1)
                .is_empty()
        );
    }
    let max_degree = generators
        .iter()
        .map(PullbackGenerator::degree)
        .max()
        .expect("pullback generators");
    let ranks = (0..=max_degree)
        .map(|degree| {
            generators
                .iter()
                .filter(|generator| generator.degree() == degree)
                .count()
        })
        .collect();
    (generators.len(), ranks)
}

fn gallery_supports(d03: Diagonal) -> BTreeMap<&'static str, BlowFace> {
    let x0 = short_diagonal(0);
    let x1 = short_diagonal(1);
    let x3 = short_diagonal(3);
    let x5 = short_diagonal(5);
    BTreeMap::from([
        (
            "a",
            [Ray::Old(x1), Ray::Old(x3), Ray::Old(x5)]
                .into_iter()
                .collect(),
        ),
        ("ec", [Ray::Old(x1), Ray::Old(x3)].into_iter().collect()),
        (
            "b1",
            [Ray::Exceptional, Ray::Old(x1), Ray::Old(x3)]
                .into_iter()
                .collect(),
        ),
        ("h", [Ray::Exceptional, Ray::Old(x3)].into_iter().collect()),
        (
            "bD",
            [Ray::Exceptional, Ray::Old(d03), Ray::Old(x3)]
                .into_iter()
                .collect(),
        ),
        ("er", [Ray::Old(d03), Ray::Old(x3)].into_iter().collect()),
        (
            "c",
            [Ray::Old(d03), Ray::Old(x0), Ray::Old(x3)]
                .into_iter()
                .collect(),
        ),
    ])
}

fn base_generator(simplex: BarySimplex) -> PullbackGenerator {
    PullbackGenerator {
        simplex,
        circles: OldFace::new(),
    }
}

fn add_base_chain(
    chain: &mut PullbackCombination,
    simplex: BarySimplex,
    scalar: UniversalMonomial,
    coefficient: Z,
) {
    add_pullback(chain, base_generator(simplex), scalar, coefficient);
}

fn scalar_occurrence(value: Diagonal) -> UniversalMonomial {
    UniversalMonomial::occurrence(value)
}

fn multiply_combination(
    value: &PullbackCombination,
    scalar: UniversalMonomial,
) -> PullbackCombination {
    value
        .iter()
        .map(|((generator, monomial), coefficient)| {
            ((generator.clone(), monomial.multiply(scalar)), *coefficient)
        })
        .collect()
}

fn add_combinations(
    left: &PullbackCombination,
    right: &PullbackCombination,
    right_sign: Z,
) -> PullbackCombination {
    let mut result = left.clone();
    for ((generator, monomial), coefficient) in right {
        add_pullback(
            &mut result,
            generator.clone(),
            *monomial,
            right_sign * coefficient,
        );
    }
    result
}

fn scale_combination(value: &PullbackCombination, scalar: Z) -> PullbackCombination {
    value
        .iter()
        .map(|(key, coefficient)| (key.clone(), scalar * coefficient))
        .filter(|(_, coefficient)| *coefficient != 0)
        .collect()
}

fn combination_divisible_by_occurrence(value: &PullbackCombination, occurrence: Diagonal) -> bool {
    !value.is_empty()
        && value
            .keys()
            .all(|(_, monomial)| monomial.divisible_by_occurrence(occurrence))
}

fn evaluate_principal_ideal_dual(
    value: &PullbackCombination,
    occurrence: Diagonal,
) -> PullbackCombination {
    // This is ev(X^vee tensor X*r)=r on I=(X).  It decrements the grading of
    // an element already known to lie in I; no scalar X^-1 is adjoined.
    assert!(combination_divisible_by_occurrence(value, occurrence));
    value
        .iter()
        .map(|((generator, monomial), coefficient)| {
            (
                (
                    generator.clone(),
                    monomial.divide_occurrence_generator(occurrence),
                ),
                *coefficient,
            )
        })
        .collect()
}

#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
enum OccurrenceKoszulState {
    P,
    H3,
}

type OccurrenceKoszulCombination =
    BTreeMap<(PullbackGenerator, UniversalMonomial, OccurrenceKoszulState), Z>;

fn add_occurrence_koszul(
    value: &mut OccurrenceKoszulCombination,
    generator: PullbackGenerator,
    monomial: UniversalMonomial,
    state: OccurrenceKoszulState,
    coefficient: Z,
) {
    let key = (generator, monomial, state);
    *value.entry(key.clone()).or_default() += coefficient;
    if value[&key] == 0 {
        value.remove(&key);
    }
}

fn lift_occurrence_koszul(
    value: &PullbackCombination,
    state: OccurrenceKoszulState,
    sign: Z,
) -> OccurrenceKoszulCombination {
    value
        .iter()
        .map(|((generator, monomial), coefficient)| {
            ((generator.clone(), *monomial, state), sign * coefficient)
        })
        .collect()
}

fn add_occurrence_koszul_combinations(
    left: &OccurrenceKoszulCombination,
    right: &OccurrenceKoszulCombination,
) -> OccurrenceKoszulCombination {
    let mut result = left.clone();
    for ((generator, monomial, state), coefficient) in right {
        add_occurrence_koszul(
            &mut result,
            generator.clone(),
            *monomial,
            *state,
            *coefficient,
        );
    }
    result
}

fn occurrence_koszul_boundary(
    value: &OccurrenceKoszulCombination,
    d03: Diagonal,
    center_x1: Diagonal,
    x3: Diagonal,
) -> OccurrenceKoszulCombination {
    let mut result = OccurrenceKoszulCombination::new();
    for ((generator, scalar, state), coefficient) in value {
        for ((target, boundary_monomial), boundary_coefficient) in
            pullback_boundary(generator, d03, center_x1)
        {
            add_occurrence_koszul(
                &mut result,
                target,
                scalar.multiply(boundary_monomial),
                *state,
                coefficient * boundary_coefficient,
            );
        }
        if *state == OccurrenceKoszulState::H3 {
            let tensor_sign = if generator.degree() % 2 == 0 { 1 } else { -1 };
            add_occurrence_koszul(
                &mut result,
                generator.clone(),
                scalar.multiply(scalar_occurrence(x3)),
                OccurrenceKoszulState::P,
                coefficient * tensor_sign,
            );
        }
    }
    result
}

fn check_x3_dual_and_relative_gysin(
    h_morse: &PullbackCombination,
    xi: &PullbackCombination,
    q_j: &PullbackCombination,
    d_xi: &PullbackCombination,
    d03: Diagonal,
    center_x1: Diagonal,
) {
    let x3 = short_diagonal(3);
    let x3_xi = multiply_combination(xi, scalar_occurrence(x3));

    // The principal-ideal dual evaluation is canonical on the special
    // boundary submodule I3*C(G), and only there.
    assert!(combination_divisible_by_occurrence(&x3_xi, x3));
    assert_eq!(evaluate_principal_ideal_dual(&x3_xi, x3), *xi);
    assert!(!combination_divisible_by_occurrence(h_morse, x3));
    assert!(!combination_divisible_by_occurrence(q_j, x3));
    assert_eq!(h_morse.len(), 7);
    assert_eq!(q_j.len(), 3);
    let global_i3_dual_evaluation_typed = false;
    assert!(!global_i3_dual_evaluation_typed);

    // The canonical repair is relative Gysin incidence, not global dual
    // evaluation.  For K_occ(x3)=[R<h3> --x3--> R<p>], totalization gives
    //
    // d(H*p - xi*h3) = qJ*p - dxi*h3.
    //
    // The minus sign is forced because xi has spatial degree one.
    let h_p = lift_occurrence_koszul(h_morse, OccurrenceKoszulState::P, 1);
    let minus_xi_h = lift_occurrence_koszul(xi, OccurrenceKoszulState::H3, -1);
    let gysin_thimble = add_occurrence_koszul_combinations(&h_p, &minus_xi_h);
    let q_p = lift_occurrence_koszul(q_j, OccurrenceKoszulState::P, 1);
    let minus_dxi_h = lift_occurrence_koszul(d_xi, OccurrenceKoszulState::H3, -1);
    let expected_boundary = add_occurrence_koszul_combinations(&q_p, &minus_dxi_h);
    let actual_boundary = occurrence_koszul_boundary(&gysin_thimble, d03, center_x1, x3);
    assert_eq!(actual_boundary, expected_boundary);
    assert!(occurrence_koszul_boundary(&actual_boundary, d03, center_x1, x3).is_empty());

    // Equivalently, qJ*p-dxi*h3 is a cycle but is the displayed boundary, so
    // this incidence kernel does not manufacture a nonzero ambient Q class.
    assert!(!expected_boundary.is_empty());
    let relative_gysin_kernel_exists = true;
    assert!(relative_gysin_kernel_exists);
}

#[derive(Debug)]
struct EndpointGenericRelativeCone {
    endpoint_generators: BTreeSet<PullbackGenerator>,
    generic_boundary: PullbackCombination,
}

impl EndpointGenericRelativeCone {
    fn endpoint_supported(&self, value: &PullbackCombination) -> bool {
        value
            .keys()
            .all(|(generator, _)| self.endpoint_generators.contains(generator))
    }

    fn equal_mod_generic_with_unit_witness(
        &self,
        left: &PullbackCombination,
        right: &PullbackCombination,
        generic_sign: Z,
    ) -> bool {
        let difference = add_combinations(left, right, -1);
        difference == scale_combination(&self.generic_boundary, generic_sign)
    }
}

fn specialized_mod_prime_coefficient(
    monomial: UniversalMonomial,
    coefficient: Z,
    x3: Diagonal,
    prime: Z,
) -> Z {
    // Ring map R -> F_prime: x3 |-> 0; every other occurrence and normal
    // variable |-> 1.  It is used only as a non-boundary detector.
    if monomial.divisible_by_occurrence(x3) {
        0
    } else {
        coefficient.rem_euclid(prime)
    }
}

fn specialized_vector(
    value: &PullbackCombination,
    basis: &[PullbackGenerator],
    x3: Diagonal,
    prime: Z,
) -> Vec<Z> {
    let positions: BTreeMap<_, _> = basis
        .iter()
        .cloned()
        .enumerate()
        .map(|(index, generator)| (generator, index))
        .collect();
    let mut result = vec![0; basis.len()];
    for ((generator, monomial), coefficient) in value {
        let index = positions[generator];
        result[index] = (result[index]
            + specialized_mod_prime_coefficient(*monomial, *coefficient, x3, prime))
        .rem_euclid(prime);
    }
    result
}

fn modular_inverse(value: Z, prime: Z) -> Z {
    assert!(value.rem_euclid(prime) != 0);
    (1..prime)
        .find(|candidate| (value * candidate).rem_euclid(prime) == 1)
        .expect("prime-field inverse")
}

fn matrix_rank_mod_prime(mut rows: Vec<Vec<Z>>, prime: Z) -> usize {
    if rows.is_empty() {
        return 0;
    }
    let column_count = rows[0].len();
    assert!(rows.iter().all(|row| row.len() == column_count));
    let mut rank = 0;
    for column in 0..column_count {
        let Some(pivot) = (rank..rows.len()).find(|row| rows[*row][column] != 0) else {
            continue;
        };
        rows.swap(rank, pivot);
        let inverse = modular_inverse(rows[rank][column], prime);
        for entry in &mut rows[rank] {
            *entry = (*entry * inverse).rem_euclid(prime);
        }
        let pivot_row = rows[rank].clone();
        for (row_index, row) in rows.iter_mut().enumerate() {
            if row_index == rank || row[column] == 0 {
                continue;
            }
            let factor = row[column];
            for index in column..column_count {
                row[index] = (row[index] - factor * pivot_row[index]).rem_euclid(prime);
            }
        }
        rank += 1;
        if rank == rows.len() {
            break;
        }
    }
    rank
}

fn columns_rank_mod_prime(columns: &[Vec<Z>], row_count: usize, prime: Z) -> usize {
    assert!(columns.iter().all(|column| column.len() == row_count));
    let rows = (0..row_count)
        .map(|row| columns.iter().map(|column| column[row]).collect())
        .collect();
    matrix_rank_mod_prime(rows, prime)
}

fn check_endpoint_generic_relative_bockstein(
    h_morse: &PullbackCombination,
    xi: &PullbackCombination,
    q_j: &PullbackCombination,
    d_xi: &PullbackCombination,
    gallery: &BTreeMap<&'static str, BlowFace>,
    d03: Diagonal,
    center_x1: Diagonal,
) -> [usize; 3] {
    let x3 = short_diagonal(3);
    let endpoint_generators = [
        base_generator(vec![gallery["a"].clone()]),
        base_generator(vec![gallery["c"].clone()]),
    ]
    .into_iter()
    .collect();
    let relative_cone = EndpointGenericRelativeCone {
        endpoint_generators,
        generic_boundary: q_j.clone(),
    };

    // E kills exactly the two endpoint terms of dxi.  It also kills dqJ, so
    // qJ is a cycle in C/E and the second quotient by R*qJ is well-defined.
    assert_eq!(d_xi.len(), 2);
    assert!(relative_cone.endpoint_supported(d_xi));
    let d_q_j = pullback_boundary_combination(q_j, d03, center_x1);
    assert_eq!(d_q_j, multiply_combination(d_xi, scalar_occurrence(x3)));
    assert!(relative_cone.endpoint_supported(&d_q_j));

    // In B=(C/E)/(R*qJ), d[H]=-[x3*xi].  The witness is exactly +qJ:
    // dH - (-x3*xi) = qJ.
    let d_h = pullback_boundary_combination(h_morse, d03, center_x1);
    let x3_xi = multiply_combination(xi, scalar_occurrence(x3));
    let minus_x3_xi = scale_combination(&x3_xi, -1);
    assert!(relative_cone.equal_mod_generic_with_unit_witness(&d_h, &minus_x3_xi, 1));

    // Cartier/Koszul Bockstein for 0 -> I3*B -> B -> B/x3 -> 0.  The lift H
    // has boundary -x3*xi in B.  Positive x3-normal d(h3)=+x3*p and the
    // already fixed negative thimble therefore give delta=-x3*xi and ev=-xi.
    let thimble_orientation = -1;
    let x3_normal_orientation = 1;
    let bockstein_sign = thimble_orientation * x3_normal_orientation;
    assert_eq!(bockstein_sign, -1);
    assert!(combination_divisible_by_occurrence(&minus_x3_xi, x3));
    let evaluated_bockstein = evaluate_principal_ideal_dual(&minus_x3_xi, x3);
    assert_eq!(evaluated_bockstein, scale_combination(xi, bockstein_sign));

    // Test whether [xi] is a boundary in this smallest relative carrier.  The
    // degree-two carrier basis consists of the seven triangles supporting H;
    // quotienting by qJ adds qJ as an image column in degree one.  Apply the
    // ring map R -> F_101 with x3=0 and all other variables=1.  If xi were a
    // boundary over R it would remain one after specialization.
    let carrier_triangles: BTreeSet<_> = h_morse
        .keys()
        .map(|(generator, _)| generator.clone())
        .collect();
    assert_eq!(carrier_triangles.len(), 7);
    let triangle_boundaries: Vec<_> = carrier_triangles
        .iter()
        .map(|generator| pullback_boundary(generator, d03, center_x1))
        .collect();
    let degree_one_basis: Vec<_> = triangle_boundaries
        .iter()
        .flat_map(|boundary| boundary.keys().map(|(generator, _)| generator.clone()))
        .chain(q_j.keys().map(|(generator, _)| generator.clone()))
        .chain(xi.keys().map(|(generator, _)| generator.clone()))
        .collect::<BTreeSet<_>>()
        .into_iter()
        .collect();
    let prime = 101;
    let mut boundary_columns: Vec<_> = triangle_boundaries
        .iter()
        .map(|boundary| specialized_vector(boundary, &degree_one_basis, x3, prime))
        .collect();
    boundary_columns.push(specialized_vector(q_j, &degree_one_basis, x3, prime));
    let relative_boundary_rank =
        columns_rank_mod_prime(&boundary_columns, degree_one_basis.len(), prime);
    let xi_column = specialized_vector(xi, &degree_one_basis, x3, prime);
    boundary_columns.push(xi_column);
    let rank_with_xi = columns_rank_mod_prime(&boundary_columns, degree_one_basis.len(), prime);
    assert_eq!(rank_with_xi, relative_boundary_rank + 1);

    // Thus xi is a relative cycle and is not a boundary.  The displayed H
    // relation makes its class x3-torsion.  Nothing here constructs sp_G.
    assert!(!xi.is_empty());
    [degree_one_basis.len(), relative_boundary_rank, rank_with_xi]
}

fn check_morse_identity(
    gallery: &BTreeMap<&'static str, BlowFace>,
    d03: Diagonal,
    x1: Diagonal,
) -> [usize; 3] {
    let top = BlowFace::new();
    let q_d03: BlowFace = [Ray::Old(d03)].into_iter().collect();
    let x3 = short_diagonal(3);
    let top_to_d03 = lcm_structure_monomial(&blowdown(&top, d03, x1), &blowdown(&q_d03, d03, x1));
    assert_eq!(top_to_d03, scalar_occurrence(d03));

    // H_Morse is the negative of the oriented seven-triangle cobordism.  The
    // er sector coefficient XD and the transition sign are forced by the
    // variance-correct initial-vertex maps top->D03 and radial cancellation.
    let mut h_morse = PullbackCombination::new();
    for (apex, edge, left, right, scalar) in [
        (
            &top,
            &gallery["ec"],
            &gallery["a"],
            &gallery["b1"],
            UniversalMonomial::one(),
        ),
        (
            &top,
            &gallery["h"],
            &gallery["b1"],
            &gallery["bD"],
            UniversalMonomial::one(),
        ),
        (
            &q_d03,
            &gallery["er"],
            &gallery["bD"],
            &gallery["c"],
            top_to_d03,
        ),
    ] {
        add_base_chain(
            &mut h_morse,
            vec![apex.clone(), edge.clone(), right.clone()],
            scalar,
            -1,
        );
        add_base_chain(
            &mut h_morse,
            vec![apex.clone(), edge.clone(), left.clone()],
            scalar,
            1,
        );
    }
    add_base_chain(
        &mut h_morse,
        vec![top.clone(), q_d03.clone(), gallery["bD"].clone()],
        UniversalMonomial::one(),
        1,
    );
    assert_eq!(h_morse.len(), 7);

    // The gallery junction maps are derived from blowdown labels.  Their
    // primitive common lcm gives the three coefficients of xi_tilde.
    let ec_to_b1 = lcm_structure_monomial(
        &blowdown(&gallery["ec"], d03, x1),
        &blowdown(&gallery["b1"], d03, x1),
    );
    let er_to_bd = lcm_structure_monomial(
        &blowdown(&gallery["er"], d03, x1),
        &blowdown(&gallery["bD"], d03, x1),
    );
    assert_eq!(ec_to_b1, scalar_occurrence(d03));
    assert_eq!(er_to_bd, scalar_occurrence(x1));
    let junction_lcm = ec_to_b1.occurrence_lcm(er_to_bd);
    let xi_coefficients = [
        junction_lcm.occurrence_quotient(ec_to_b1),
        junction_lcm,
        junction_lcm.occurrence_quotient(er_to_bd),
    ];
    assert_eq!(
        xi_coefficients,
        [
            scalar_occurrence(x1),
            scalar_occurrence(d03).multiply(scalar_occurrence(x1)),
            scalar_occurrence(d03),
        ]
    );

    let mut xi = PullbackCombination::new();
    for (edge, left, right, scalar) in [
        (
            &gallery["ec"],
            &gallery["a"],
            &gallery["b1"],
            xi_coefficients[0],
        ),
        (
            &gallery["h"],
            &gallery["b1"],
            &gallery["bD"],
            xi_coefficients[1],
        ),
        (
            &gallery["er"],
            &gallery["bD"],
            &gallery["c"],
            xi_coefficients[2],
        ),
    ] {
        add_base_chain(&mut xi, vec![edge.clone(), right.clone()], scalar, 1);
        add_base_chain(&mut xi, vec![edge.clone(), left.clone()], scalar, -1);
    }

    let boundary_h = pullback_boundary_combination(&h_morse, d03, x1);
    let x3_xi = multiply_combination(&xi, scalar_occurrence(x3));
    let q_j = add_combinations(&boundary_h, &x3_xi, 1);

    // Inspect the derived side against its expected three supported flags.
    let mut expected_q_j = PullbackCombination::new();
    add_base_chain(
        &mut expected_q_j,
        vec![top.clone(), gallery["a"].clone()],
        UniversalMonomial::one(),
        -1,
    );
    add_base_chain(
        &mut expected_q_j,
        vec![top.clone(), q_d03.clone()],
        UniversalMonomial::one(),
        1,
    );
    add_base_chain(
        &mut expected_q_j,
        vec![q_d03.clone(), gallery["c"].clone()],
        top_to_d03,
        1,
    );
    assert_eq!(q_j, expected_q_j);
    let forced_target = add_combinations(&q_j, &x3_xi, -1);
    assert_eq!(boundary_h, forced_target);
    assert!(pullback_boundary_combination(&boundary_h, d03, x1).is_empty());
    let d_xi = pullback_boundary_combination(&xi, d03, x1);
    let d_q_j = pullback_boundary_combination(&q_j, d03, x1);
    assert_eq!(d_q_j, multiply_combination(&d_xi, scalar_occurrence(x3)));

    let desired_target = add_combinations(&q_j, &xi, -1);
    assert_ne!(boundary_h, desired_target);
    let mismatch = add_combinations(&boundary_h, &desired_target, -1);
    assert!(!mismatch.is_empty());
    assert!(mismatch
        .keys()
        .all(|(_, monomial)| monomial.normal.iter().all(|power| *power == 0)));

    check_x3_dual_and_relative_gysin(&h_morse, &xi, &q_j, &d_xi, d03, x1);
    let relative_bockstein_stats =
        check_endpoint_generic_relative_bockstein(&h_morse, &xi, &q_j, &d_xi, gallery, d03, x1);

    // Ordered 0<3 fixes +[dX03].  The absolute radial incidence and the
    // [top<D03] coefficient in q_J have the same positive sign.
    let ordered_normal_sign = if d03.0 < d03.1 { 1 } else { -1 };
    let absolute_d03_incidence = incidence_sign(&OldFace::new(), d03);
    let q_j_d03_key = (base_generator(vec![top, q_d03]), UniversalMonomial::one());
    let q_j_d03_sign = q_j[&q_j_d03_key];
    assert_eq!(ordered_normal_sign, 1);
    assert_eq!(absolute_d03_incidence, 1);
    assert_eq!(q_j_d03_sign, 1);
    relative_bockstein_stats
}

fn main() {
    let d03 = diagonal(0, 3);
    let x1 = short_diagonal(1);
    let old = old_faces_by_size();
    check_actual_absolute_complex(&old);

    let blown_up = blowup_faces(&old, d03, x1);
    assert_eq!(
        (0..=DIMENSION)
            .map(|size| blown_up.iter().filter(|face| face.len() == size).count())
            .collect::<Vec<_>>(),
        [1, 10, 24, 16]
    );
    assert!(blown_up.iter().all(|face| old
        .iter()
        .flatten()
        .any(|old_face| old_face == &blowdown(face, d03, x1))));
    for source in &blown_up {
        for target in &blown_up {
            if source.is_subset(target) {
                assert!(blowdown(source, d03, x1).is_subset(&blowdown(target, d03, x1)));
            }
        }
    }

    let barycentric = barycentric_subdivision(&blown_up);
    assert_eq!(
        (1..=DIMENSION + 1)
            .map(|length| barycentric
                .iter()
                .filter(|simplex| simplex.len() == length)
                .count())
            .collect::<Vec<_>>(),
        [51, 194, 240, 96]
    );
    let pullback_census = check_full_pullback_complex(&barycentric, d03, x1);

    let gallery = gallery_supports(d03);
    assert!(gallery.values().all(|support| blown_up.contains(support)));
    let relative_bockstein_stats = check_morse_identity(&gallery, d03, x1);

    let h_cond_constructed = false;
    let sp_g_constructed = false;
    let purity_constructed = false;
    let new_monodromy_comparison_constructed = false;
    let theta_constructed = false;
    assert!(!h_cond_constructed);
    assert!(!sp_g_constructed);
    assert!(!purity_constructed);
    assert!(!new_monodromy_comparison_constructed);
    assert!(!theta_constructed);

    println!(
        "{}",
        format!(
            r#"{{"claim":"The actual 215-generator P_abs complex pulls functorially to the D03 blown-up barycentric face poset through the order-preserving blowdown functor and the variance-correct simplicial replacement of its covariant lcm occurrence/normal cosheaf. The complete pulled-back loaded differential squares to zero. On the mixed seven-triangle carrier, all coefficients are forced by initial-vertex lcm quotients and radial cancellation, but the resulting identity is d H_Morse^abs=q_J^abs-x3*xi_tilde^abs, not q_J^abs-xi_tilde^abs. Thus entry 109's desired unlocalized equality is falsified at the common spectator occurrence x3. The [top<D03] coefficient is +1 and agrees with both eps(empty,D03)=+1 and the established ordered-normal convention 0<3. Principal-ideal duality evaluates the special submodule x3*xi to xi without inversion, but it is not globally typed because no H_Morse or q_J term lies in I3=(x3). The canonical repair is only relative: in the separate occurrence Koszul incidence K_occ(x3), d(H_Morse*p-xi*h3)=q_J*p-dxi*h3, and the right side is itself a boundary. In the explicitly defined endpoint-plus-generic relative quotient B=(C_carrier/E)/(R*q_J), d[H_Morse]=-x3*[xi_tilde]; its Cartier/Koszul Bockstein is [-x3*xi_tilde], ideal-dual evaluation is -[xi_tilde] for the chosen negative thimble and positive x3 normal, and a specialization-rank detector proves [xi_tilde] survives as a non-boundary x3-torsion class. This relative statement does not construct global sp_G.","status":"falsified","status_meaning":"The functorial P_abs pullback and weighted no-go are proved; the desired Morse identity fails integrally by a common x3 factor. The endpoint-plus-generic relative Bockstein and survival statement are proved only in the stated carrier quotient.","scope":"actual universal P_abs, functorial blowdown pullback, full loaded barycentric differential, zero-normal seven-triangle identity, and the explicitly defined endpoint-plus-generic relative carrier quotient only","result":{{"absolute_P_abs":{{"generator_count":215,"degree_ranks":[14,63,93,45],"d_squared":"PASS"}},"blowup":{{"face_census":[1,10,24,16],"barycentric_census":[51,194,240,96],"blowdown_order_preserving":true}},"pulled_back_loaded_complex":{{"generator_count":{},"degree_ranks":{:?},"variance":"covariant stalk at initial flag face; deleting the initial vertex applies label(S1)/label(S0), all other simplicial faces are units","normal_totalization_sign":"(-1)^(simplex_dimension+circle_position)","full_weighted_d_squared":"PASS"}},"seven_triangle_carrier":{{"H_Morse_triangle_count":7,"derived_identity":"d H_Morse^abs=q_J^abs-x3*xi_tilde^abs","desired_identity":"FAIL","xi_tilde_abs":"x1*sd(e_c)+XD*x1*sd(h_E)+XD*sd(e_r)","q_J_abs":"-[top,a]+[top,D03]+XD*[D03,c]","first_mismatch":"common nonunit spectator factor x3 on the special gallery","x3_inverted":false,"coefficient_fitted":false}},"orientation":{{"q_J_top_D03_sign":1,"absolute_incidence_empty_D03":1,"ordered_D03_normal":"0<3 gives +1","x3_normal":"d(h3)=+x3*p","thimble":"H_Morse is the negative oriented seven-triangle thimble","relative_Bockstein_sign":-1,"comparison":"MATCH at the carrier/occurrence sign level"}},"x3_principal_ideal_audit":{{"ideal":"I3=(x3)","dual":"I3^vee=Hom_R(I3,R)","special_boundary_module":"x3*xi_tilde lies in I3*C1(G)","special_evaluation":"ev(x3^vee tensor x3*xi_tilde)=xi_tilde","base_x3_inverted":false,"H_Morse_module":"7 terms over R; not contained in I3","q_J_module":"3 terms with coefficients (-1,+1,+XD); not contained in I3","global_I3_dual_evaluation":"UNTYPED"}},"relative_occurrence_gysin":{{"complex":"K_occ(x3)=[R<h3> --x3--> R<p>]","variance":"auxiliary occurrence ideal, not a monodromy-normal packet","gysin_thimble":"H_Morse*p-xi_tilde*h3","full_identity":"d(H_Morse*p-xi_tilde*h3)=q_J*p-dxi_tilde*h3","totalization_sign":"-xi_tilde*h3 because deg(xi_tilde)=1","d_squared":"PASS","ambient_Q_class_created":false,"interpretation":"canonical relative-boundary incidence kernel only"}},"endpoint_generic_relative_Bockstein":{{"relative_complex":"B=(C_carrier/E)/(R*q_J), E=R<a,c>","well_typed":"d(q_J)=x3*d(xi_tilde) is endpoint-supported","identity":"d_B[H_Morse]=-x3*[xi_tilde]","mod_x3_cycle":"[H_Morse mod x3]","connecting_class":"delta([H_Morse mod x3])=[-x3*xi_tilde] in H1(I3*B)","ideal_dual_evaluation":"[-x3*xi_tilde] maps to -[xi_tilde]","orientation_dependence":"negative thimble times positive x3 normal gives -1; reversing either reverses the result","xi_relative_cycle":true,"xi_boundary":false,"xi_homology":"nonzero x3-torsion in the smallest relative carrier","non_boundary_detector":{{"specialization":"R -> F_101, x3->0, all other variables->1","degree_one_generators":{},"boundary_columns":8,"boundary_rank":{},"rank_after_adjoining_xi":{}}},"global_sp_G_constructed":false}}}},"checks":{{"actual_215_generator_complex":"PASS","actual_absolute_d_squared":"PASS","functorial_blowdown_pullback":"PASS","lcm_coefficients_derived":"PASS","full_pullback_weighted_d_squared":"PASS","seven_triangle_weighted_boundary":"PASS","desired_Morse_equality":"FALSIFIED by x3","ordered_D03_sign":"PASS +1","special_I3_dual_evaluation":"PASS without x3 inversion","global_I3_dual_evaluation":"UNTYPED","relative_occurrence_Koszul_identity":"PASS","relative_occurrence_Koszul_d_squared":"PASS","ambient_Q_class_from_Koszul":"ZERO: displayed boundary","relative_B_well_typed":"PASS","relative_B_identity":"PASS d[H]=-x3[xi]","relative_Bockstein":"PASS delta=[-x3*xi]","relative_Bockstein_ideal_dual":"PASS -> -[xi]","relative_xi_survives":"PASS by F_101 rank obstruction","global_sp_G_constructed":false,"H_cond_constructed":false,"purity_constructed":false,"new_monodromy_comparison_constructed":false,"Theta_constructed":false,"occurrence_inverted":false,"normal_inverted":false}},"first_missing_datum":"A global module map extending ev:I3^vee tensor I3->R from the special boundary to the R-valued H_Morse and q_J terms. The relative Bockstein is defined only after quotienting endpoints and the generic q_J cycle and therefore is not a construction of sp_G.","boundary":"The checker proves a nonzero x3-torsion class only in the explicitly defined smallest relative carrier B. It does not identify q_J with a nonzero ambient derived-Q class, construct H_cond or sp_G, or attach purity, monodromy, Cousin, or Theta data.","next_experiment":"Construct, if geometry supplies it, a global map from the endpoint-plus-generic relative Bockstein class to the ambient derived Q-to-F0 Hom complex; the present quotient supplies neither that support map nor sp_G."}}"#,
            pullback_census.0,
            pullback_census.1,
            relative_bockstein_stats[0],
            relative_bockstein_stats[1],
            relative_bockstein_stats[2]
        )
    );
}
