"""Cokernel obstruction for current sourced tau_p candidates.

Given the formal horn, current sourced data contribute only the ordered blow-up
exceptional column (0,1).  The required filler is (1,1).  The quotient by the
current sourced image has a primitive obstruction represented by the Xi_log
coordinate.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
VOEVODSKY_RESULTS = ROOT / "research" / "voevodsky" / "results"
OUT = VOEVODSKY_RESULTS / "cosmology_tau_obstruction_cokernel.json"


def load(name: str) -> dict:
    return json.loads((VOEVODSKY_RESULTS / name).read_text(encoding="utf-8"))


def rank_mod_prime(matrix: list[list[int]], prime: int) -> int:
    rows = [[entry % prime for entry in row] for row in matrix]
    if not rows:
        return 0
    rank = 0
    row_count = len(rows)
    col_count = len(rows[0])
    for col in range(col_count):
        pivot = next((r for r in range(rank, row_count) if rows[r][col] % prime), None)
        if pivot is None:
            continue
        rows[rank], rows[pivot] = rows[pivot], rows[rank]
        inv = pow(rows[rank][col], -1, prime)
        rows[rank] = [(value * inv) % prime for value in rows[rank]]
        for r in range(row_count):
            if r == rank:
                continue
            factor = rows[r][col] % prime
            if factor:
                rows[r] = [(a - factor * b) % prime for a, b in zip(rows[r], rows[rank])]
        rank += 1
    return rank


def main() -> None:
    formal = load("cosmology_tau_lift_formal_problem.json")
    blowup = load("cosmology_blowup_exceptional_cell_gate.json")
    trichotomy = load("cosmology_tau_source_domain_trichotomy.json")

    assert formal["passed"] is True
    assert blowup["passed"] is True
    assert trichotomy["passed"] is True

    required = formal["formal_horn"]["required_d1_column"]
    sourced_exceptional = blowup["exceptional_cell_column_rows_Xi_minusSigma"]
    assert required == [1, 1]
    assert sourced_exceptional == [0, 1]

    obstruction = [required[i] - sourced_exceptional[i] for i in range(2)]
    assert obstruction == [1, 0]

    # Z^2 / <(0,1)> is generated by the Xi coordinate.  The obstruction is its
    # primitive generator.  Finite fields witness that adding the required vector
    # strictly enlarges the sourced span.
    witnesses = {}
    for prime in (101, 103):
        sourced_rank = rank_mod_prime([[0], [1]], prime)
        augmented_rank = rank_mod_prime([[0, 1], [1, 1]], prime)
        obstruction_nonzero = obstruction[0] % prime != 0
        assert sourced_rank == 1
        assert augmented_rank == 2
        assert obstruction_nonzero
        witnesses[str(prime)] = {
            "sourced_span_rank": sourced_rank,
            "sourced_plus_required_rank": augmented_rank,
            "obstruction_vector_mod_prime": [value % prime for value in obstruction],
            "obstruction_nonzero": True,
        }

    result = {
        "schema": "marici.voevodsky.cosmology-tau-obstruction-cokernel.v1",
        "status": "primitive_Xi_coordinate_obstruction_in_current_sourced_cokernel",
        "rechecked_inputs": [
            "research/voevodsky/results/cosmology_tau_lift_formal_problem.json",
            "research/voevodsky/results/cosmology_blowup_exceptional_cell_gate.json",
            "research/voevodsky/results/cosmology_tau_source_domain_trichotomy.json",
        ],
        "ambient_pair_module_basis": ["Xi_log", "minus_sigma123"],
        "current_sourced_image_generators": {"ordered_blowup_exceptional_face": sourced_exceptional},
        "required_tau_column": required,
        "cokernel": "Z<Xi_log,minus_sigma123>/<minus_sigma123> ~= Z<Xi_log>",
        "obstruction_vector": obstruction,
        "obstruction_interpretation": "the missing primitive is exactly the Xi_log unit leg modulo the currently sourced exceptional face leg",
        "finite_field_witnesses": witnesses,
        "what_would_kill_obstruction": "a sourced generator whose image has Xi_log coefficient +/-1; the minus_sigma123 coefficient is then forced by d^2",
        "what_does_not_kill_obstruction": [
            "more copies of the exceptional face column (0,1)",
            "residue equality without a pre-residue lift",
            "a nonunit Xi_log multiple",
            "a two-chart fixed-fiber gradient-pivot restriction",
        ],
        "relative_bockstein_constructed": False,
        "physical_period_constructed": False,
        "passed": True,
    }
    OUT.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
