"""Finite audit of road-leg inversion in the primitive Verdier quotient."""


def matmul(a, b):
    return [[sum(x * y for x, y in zip(row, col)) for col in zip(*b)] for row in a]


def main():
    epsilon = [[1, 1, 1]]
    identity = [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
    sections = [[[1], [0], [0]], [[0], [1], [0]], [[0], [0], [1]]]

    for section in sections:
        assert matmul(epsilon, section) == [[1]]
        projector = matmul(section, epsilon)
        defect = [[identity[i][j] - projector[i][j] for j in range(3)] for i in range(3)]
        # Every defect column lies in A2=ker(epsilon), so it vanishes after
        # quotienting by the thick contact subcategory generated by A2.
        assert matmul(epsilon, defect) == [[0, 0, 0]]
        assert projector != identity

    for first in range(3):
        for second in range(3):
            difference = [[sections[first][i][0] - sections[second][i][0]] for i in range(3)]
            assert matmul(epsilon, difference) == [[0]]

    # Cyclic road transport permutes the three representatives; their
    # primitive quotient is the same unit.
    rotation = [[0, 0, 1], [1, 0, 0], [0, 1, 0]]
    assert matmul(epsilon, rotation) == epsilon
    assert matmul(rotation, sections[0]) == sections[1]

    # Entry 406 selects the orientation character.  It is an honest unit
    # representation on the primitive line: the core is -1 and its doubled
    # outer boundary is +1.
    core_holonomy = -1
    outer_holonomy = core_holonomy**2
    assert outer_holonomy == 1
    assert core_holonomy * core_holonomy == 1

    print("road_module: Z^3")
    print("contact_kernel: A2_rank_2")
    print("full_category_road_legs_invertible: NO")
    print("primitive_Verdier_quotient_road_legs_invertible: YES")
    print("three_inverse_roofs_agree_mod_A2: YES")
    print("core_multiplicative_holonomy: -1")
    print("outer_multiplicative_holonomy: +1")
    print("scope: primitive_associated_grade_only")


if __name__ == "__main__":
    main()
