#!/usr/bin/env python3
"""Admit the exact geometric content of the marked v10 endpoint carrier."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
q0=(ROOT/'research/voevodsky/check_d03_q0_endpoint_exit_flags.rs').read_text();loaded=(ROOT/'research/voevodsky/check_d03_x3_loaded_pc_endpoint_boundary.rs').read_text()
checks={'unique_marked_carrier':'q0_compatible_central_flip' in q0 and 'UNIQUE: v10<->v+' in q0,'relative_BM_class':'endpoint_relative_BM_span' in q0 and 'H1(I,partial I)=Z' in q0,'road_coefficient_derived':'road_generization_before_base_change' in q0 and 'b0=+x1' in q0,'endpoint_coefficient_fixed':'endpoint_coefficient' in q0 and 'a0=-1' in q0,'BC_normalization_passes':'normalized_BC' in q0 and 'PASS: b0=-x1*a0=+x1' in q0,'absolute_q0_control_fails':'q0_absolute_closed' in q0 and 'FAIL: d(q0)=x5*a' in q0,'extraordinary_map_still_missing':'full_extraordinary_Tor_map' in q0 and 'NOT CONSTRUCTED' in q0,'target_still_untyped':'actual_ringed_PC_extraordinary_map' in loaded and 'UNTYPED' in loaded}
assert all(checks.values()),checks
out={'schema':'marici.voevodsky.CR1A1-geometric-v10-corner-restriction.v1','prospective_action':'CR1A1_construct_geometric_v10_corner_restriction','outcome_contract':{'++':'the marked geometric carrier and variance-changing extraordinary map to the v10 road costalk are constructed','+-':'the unique endpoint-relative carrier and its normalized coefficients are constructed, but the extraordinary Tor map is absent','-+':'the actual face poset has no compatible marked carrier','--':'the endpoint source cannot be typed'},'resolution':'+-','carrier':{'path':'F03 > Z3 > v10 <ec> v+ > e3 > q0','relative_class':'primitive H1(I,partial I)=Z','road_generization':'b0=+x1','special_endpoint':'a0=-1','Beck_Chevalley':'b0=-x1*a0'},'negative_control':'The absolute q0-only source is not closed: d(q0)=x5*a. Endpoint-relative quotient a=0 is mandatory.','remaining_gap':'Construct the reciprocal-standard to original-Borel-Moore can-var/Tor1 extraordinary map along the marked interval and identify [t3] with eta_3,mix while retaining [dX03]=+1.','refinement':['CR1A1a_construct_v10_variance_changing_Tor_map'],'next':'Build the derived Hom/exit map from Th_x3^mR tensor I_x1*(q0 relative a) to the actual F03 Tor1 costalk.','checks':checks,'passed':True};p=ROOT/'research/voevodsky/results/CR1A1_geometric_v10_corner_restriction.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'resolution':'+-','carrier':'unique endpoint-relative','b0':'+x1','a0':'-1','next':out['refinement'][0]}))
