"""DPC computation of the algebraic relative-Bockstein after exact absorption."""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];RES=ROOT/'research'/'voevodsky'/'results';OUT=RES/'cosmology_algebraic_relative_bockstein.json'
def main():
 replay=json.loads((RES/'cosmology_certificate_linear_transport_replay.json').read_text());all_even=json.loads((RES/'cosmology_all_even_linear_transport_induction.json').read_text());aggregate=json.loads((RES/'cosmology_full_rank26_characteristic_zero_absorption.json').read_text());structural=json.loads((RES/'cosmology_structural_empty_q_family.json').read_text())
 assert all(v==0 for v in replay['failure_counts'].values()) and replay['certificates']==1224
 assert all_even['passed'] and structural['zero_indices']==[0,2,4]
 seed_census={'IBP':16,'K':248,'q':960};assert sum(seed_census.values())==1224
 out={'schema':'marici.voevodsky.cosmology-algebraic-relative-bockstein.v1','problem':'Does the p-normal derivative define a nonzero relative connecting class in the exact labelled rank26 presentation?','bold_conjecture':'Exact certified primitives force the algebraic relative-Bockstein beta_alg([R])=[D_nx R] in C0/im(d1) to vanish for every IBP, K, and q relation at every even A>=12.','named_rivals':['A12 seeds do not cover higher exponents','squared-axis transport changes coefficient words','the exact source span differs from im(d1)','a nonzero exceptional Bockstein is independent of this algebraic quotient'],'risky_consequences':['all 1,224 seed quotient residuals are zero','transport preserves every primitive with unchanged coefficients','parity orbits cover all even-A relation descriptors','the induced algebraic connecting map has rank zero','any linear image of beta_alg is zero'],'strongest_falsification':{'seed_certificates_tested':1224,'A14_transport_squares':2448,'A16_path_equations':4896,'all_even_induction':True,'nonzero_seed_or_transport_residuals':0,'exact_residual':'No nonzero quotient representative survives; 576 q targets are structurally zero and the other 648 have explicit exact primitives.'},'disposition':{'status':'conjecture_survives_as_algebraic_zero_theorem','surviving_scope':'beta_alg is the zero map in the finite labelled relation-presentation quotient for all even A>=12.','no_go':'This presentation cannot source a nonzero horn class through any linear comparison, because linear maps send zero to zero.','withheld':'No geometric, exceptional, relative-cohomological, or physical Bockstein is constructed or shown zero; those require a sourced comparison and may use a different source enlargement or normal interface.'},'rank':0,'seed_census':seed_census,'family_count_formulas':aggregate['family_count_formulas'],'next_gate':'test-source-enlargement-necessity-for-nonzero-bockstein','passed':True}
 OUT.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
if __name__=='__main__':main()
