//! Exact combinatorial certificate for the alternating-fusion conductor square.
//!
//! Write
//!   B_+ = R[x1,x3,x5],  B_- = R[x0,x2,x4],  C = R,
//! with both maps to C given by the zero section.  The fiber product consists
//! of pairs with the same constant (R-valued) term.  This checker certifies:
//!
//! * the monomial normal form for
//!     R[x0,...,x5]/(x_even x_odd) = B_+ x_C B_-;
//! * the componentwise exactness of 0 -> B -> B_+ (+) B_- -> C -> 0;
//! * the six supported coefficients of the polarity-odd first-normal symbol;
//! * anti-equivariance under one-step rotation, and its cancellation by the
//!   polarity sign line.
//!
//! The normalization and cdh conclusions use the algebraic proof in ledger
//! entry 93: the two polynomial branches are normal, the product is obtained
//! by adjoining an integral idempotent, and the conductor is J_+ (+) J_-.

const EVEN: [usize; 3] = [0, 2, 4];
const ODD: [usize; 3] = [1, 3, 5];

/// Coefficients in the R-basis (y0,y1,y2).
type LinearY = [i32; 3];

fn contains(mask: usize, variable: usize) -> bool {
    mask & (1 << variable) != 0
}

fn has_parity(mask: usize, variables: &[usize; 3]) -> bool {
    variables.iter().any(|&variable| contains(mask, variable))
}

fn mixed(mask: usize) -> bool {
    has_parity(mask, &EVEN) && has_parity(mask, &ODD)
}

fn add(left: LinearY, right: LinearY) -> LinearY {
    [left[0] + right[0], left[1] + right[1], left[2] + right[2]]
}

fn negate(value: LinearY) -> LinearY {
    [-value[0], -value[1], -value[2]]
}

fn rotate_y(value: LinearY) -> LinearY {
    // y0 -> y1, y1 -> y2, y2 -> y0.
    [value[2], value[0], value[1]]
}

fn rotate_form(value: &[LinearY; 6]) -> [LinearY; 6] {
    let mut result = [[0; 3]; 6];
    for (short, coefficient) in value.iter().enumerate() {
        result[(short + 1) % 6] = rotate_y(*coefficient);
    }
    result
}

fn main() {
    // A monomial is killed exactly when its support contains an even and an
    // odd variable.  Exponent sizes are irrelevant, so the 2^6 support audit
    // is exhaustive for the monomial presentation in every degree.
    let survivors: Vec<_> = (0..1_usize << 6).filter(|&mask| !mixed(mask)).collect();
    assert_eq!(survivors.len(), 15);
    assert_eq!(survivors.iter().filter(|&&mask| mask == 0).count(), 1);
    assert_eq!(
        survivors
            .iter()
            .filter(|&&mask| mask != 0 && has_parity(mask, &ODD))
            .count(),
        7
    );
    assert_eq!(
        survivors
            .iter()
            .filter(|&&mask| mask != 0 && has_parity(mask, &EVEN))
            .count(),
        7
    );

    // Componentwise exactness is tautological on every nonconstant monomial:
    // it belongs to exactly one branch and maps identically there.  On the
    // constant component the universal integer matrices are
    //       Z --(1,1)--> Z^2 --(1,-1)--> Z.
    let diagonal = [1_i32, 1];
    let difference = [1_i32, -1];
    assert_eq!(diagonal[0] * difference[0] + diagonal[1] * difference[1], 0);
    assert_eq!(difference.iter().copied().fold(0_i32, gcd).abs(), 1);
    // ker(1,-1) is generated by (1,1).
    for a in -8_i32..=8 {
        for b in -8_i32..=8 {
            assert_eq!(a - b == 0, [a, b] == [a, a]);
        }
    }

    // Branchwise first-normal coefficients of entry 66.  The common A0 term
    // disappears.  Columns are ordered x0,...,x5.
    let mut plus = [[0; 3]; 6];
    plus[1] = [0, 0, 1]; // y2 dx1
    plus[3] = [0, 1, 0]; // y1 dx3
    plus[5] = [1, 0, 0]; // y0 dx5

    let mut minus = [[0; 3]; 6];
    minus[0] = [0, 1, 0]; // y1 dx0
    minus[2] = [1, 0, 0]; // y0 dx2
    minus[4] = [0, 0, 1]; // y2 dx4

    let sigma = std::array::from_fn(|column| add(plus[column], negate(minus[column])));
    let expected = [
        [0, -1, 0],
        [0, 0, 1],
        [-1, 0, 0],
        [0, 1, 0],
        [0, 0, -1],
        [1, 0, 0],
    ];
    assert_eq!(sigma, expected);
    assert_eq!(
        sigma
            .iter()
            .filter(|&&coefficient| coefficient != [0; 3])
            .count(),
        6
    );

    // One-step cyclic rotation exchanges the two normalization sheets and
    // sends the raw difference to its negative.  Hence it is not equivariant
    // in the untwisted conormal module over Z.  Tensoring with the polarity
    // line, on which the sheet exchange acts by -1, cancels this sign.
    let rotated = rotate_form(&sigma);
    assert_eq!(rotated, sigma.map(negate));
    assert_ne!(rotated, sigma);
    let polarity_character = -1;
    assert_eq!(
        rotated.map(|coefficient| {
            if polarity_character == -1 {
                negate(coefficient)
            } else {
                coefficient
            }
        }),
        sigma
    );

    println!("alternating conductor square certificate: PASS");
    println!("monomial support types: 64 total, 15 surviving, 49 mixed killed");
    println!("normalization constants: diagonal kernel of the branch difference");
    println!("conductor symbol supports: 6/6 with entry-66 signs");
    println!("one-step rotation: raw sign -1, polarity-loaded sign +1");
}

fn gcd(a: i32, b: i32) -> i32 {
    if b == 0 {
        a.abs()
    } else {
        gcd(b, a % b)
    }
}
