"""Universal cell classifier for the cosmology relative residue cocycle.

This is the Voevodsky-style replacement for another ad hoc search: isolate the
exact typed datum whose absence blocks the construction.  The minimal residue
complex has degree-2 generators Xi_log and minus_sigma123 with residue
differential D.  A total lift exists exactly after adjoining a degree-1 cell tau
whose differential is the kernel generator Xi_log+minus_sigma123, or after a
source-derived complex maps to that universal cell attachment.
"""

from __future__ import annotations

import json
from math import gcd
from pathlib import Path
from functools import reduce

ROOT = Path(__file__).resolve().parents[2]
VOEVODSKY_RESULTS = ROOT / "research" / "voevodsky" / "results"
OUT = VOEVODSKY_RESULTS / "cosmology_universal_total_lift_cell.json"


def load(name: str) -> dict:
    return json.loads((VOEVODSKY_RESULTS / name).read_text(encoding="utf-8"))


def mat_vec(matrix: list[list[int]], vector: list[int]) -> list[int]:
    return [sum(row[i] * vector[i] for i in range(len(vector))) for row in matrix]


def rank_mod_prime(matrix: list[list[int]], prime: int) -> int:
    rows = [[entry % prime for entry in row] for row in matrix]
    if not rows:
        return 0
    rank = 0
    row_count = len(rows)
    col_count = len(rows[0]) if rows else 0
    for col in range(col_count):
        pivot = next((r for r in range(rank, row_count) if rows[r][col] % prime), None)
        if pivot is None:
            continue
        rows[rank], rows[pivot] = rows[pivot], rows[rank]
        inv = pow(rows[rank][col], -1, prime)
        rows[rank] = [(value * inv) % prime for value in rows[rank]]
        for r in range(row_count):
            if r == rank:
                continue
            factor = rows[r][col] % prime
            if factor:
                rows[r] = [(a - factor * b) % prime for a, b in zip(rows[r], rows[rank])]
        rank += 1
    return rank


def primitive_kernel_generator_for_rank_one_rows(matrix: list[list[int]]) -> list[int]:
    # For the 3x2 matrix with rows (1,-1) up to sign, the integer kernel is
    # generated by (1,1).  Keep this explicit and assert every row annihilates it.
    generator = [1, 1]
    assert mat_vec(matrix, generator) == [0 for _ in matrix]
    assert reduce(gcd, (abs(x) for x in generator)) == 1
    return generator


def main() -> None:
    total_blocker = load("cosmology_total_lift_blocker.json")
    relative = load("cosmology_relative_residue_cocycle.json")

    assert total_blocker["passed"] is True
    assert total_blocker["status"] == "blocked_at_absent_total_chain_level_lift"
    d_residue = relative["differential_to_pair_residues_rows_q1q2_q1q3_q2q3_cols_Xi_minusSigma"]
    assert d_residue == [[1, -1], [-1, 1], [1, -1]]

    kernel_generator = primitive_kernel_generator_for_rank_one_rows(d_residue)
    assert kernel_generator == [1, 1]

    # Universal attachment: add tau in degree 1 with d(tau)=Xi_log+minus_sigma123.
    d_tau = [[1], [1]]
    composite = [sum(d_residue[row][col] * d_tau[col][0] for col in range(2)) for row in range(3)]
    assert composite == [0, 0, 0]

    # Any one-cell integral attachment d(e)=(a,b) has d^2=0 iff a=b; then it
    # factors through tau by multiplication by a.  It kills the primitive class
    # iff a=b is a unit over Z, i.e. +/-1.  Nonunit multiples kill only multiples.
    sample_attachments = []
    for a, b in [(-1, -1), (0, 0), (1, 1), (2, 2), (1, 0), (0, 1), (1, -1)]:
        closed = mat_vec(d_residue, [a, b]) == [0, 0, 0]
        factors_through_tau = closed
        kills_primitive_integrally = (a, b) in [(1, 1), (-1, -1)]
        sample_attachments.append({
            "d_e": [a, b],
            "d_squared_zero": closed,
            "factors_through_universal_tau": factors_through_tau,
            "kills_primitive_integrally": kills_primitive_integrally,
        })

    witnesses = {}
    for prime in (101, 103):
        rank_before = rank_mod_prime([[0, 0]], prime)  # no incoming image
        rank_after = rank_mod_prime([[1], [1]], prime)
        residue_rank = rank_mod_prime(d_residue, prime)
        assert (rank_before, rank_after, residue_rank) == (0, 1, 1)
        witnesses[str(prime)] = {
            "incoming_rank_before_tau": rank_before,
            "incoming_rank_after_tau": rank_after,
            "residue_differential_rank": residue_rank,
            "tau_kills_relative_class": True,
        }

    result = {
        "schema": "marici.voevodsky.cosmology-universal-total-lift-cell.v1",
        "status": "universal_missing_cell_classified_not_sourced",
        "rechecked_inputs": [
            "research/voevodsky/results/cosmology_total_lift_blocker.json",
            "research/voevodsky/results/cosmology_relative_residue_cocycle.json",
        ],
        "residue_differential_rows_pair_faces_cols_Xi_minusSigma": d_residue,
        "primitive_kernel_generator": kernel_generator,
        "universal_cell": {
            "name": "tau_p",
            "degree": 1,
            "differential": "d(tau_p)=Xi_log+minus_sigma123",
            "d_squared_zero": True,
            "universal_property": "any one-cell integral attachment with d^2=0 maps to degree vector (a,a) and factors through tau_p by multiplication by a; it kills the primitive class integrally only for a=+/-1",
        },
        "sample_attachments": sample_attachments,
        "finite_field_witnesses": witnesses,
        "source_status": "tau_p is a classifier for the missing datum, not a sourced generator",
        "admissible_next_source_tests": [
            "find a resolved/Rees exceptional generator whose differential maps to tau_p with unit coefficient",
            "construct a logarithmic Cech-de Rham chain map whose cone cell maps to tau_p with unit coefficient",
            "construct a Cayley-Menger face cone whose compensating residue maps to tau_p with unit coefficient",
        ],
        "forbidden_shortcuts": [
            "declaring tau_p as physical source data without a source map",
            "quotienting by Xi_log or by the circuit row",
            "using a nonunit multiple as if it killed the primitive integral class",
            "dividing by p",
        ],
        "relative_bockstein_constructed": False,
        "physical_period_constructed": False,
        "passed": True,
    }
    OUT.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
