"""Record the correct Gersten/motivic degrees and the data missing from the comparison cone."""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'research'/'voevodsky'/'results'/'cosmology_integral_total_complex_degree_reconciliation.json'
def main():
 gersten=[{'codim':0,'term':'K2^M(Q(P2))','motivic_degree':2},{'codim':1,'term':'sum_D k(D)^x','motivic_degree':3},{'codim':2,'term':'sum_p Z','motivic_degree':4}]
 assert [x['motivic_degree'] for x in gersten]==[2,3,4]
 assert gersten[1]['motivic_degree']==gersten[0]['motivic_degree']+1
 out={'schema':'marici.voevodsky.cosmology-integral-total-complex-degree-reconciliation.v1','status':'degrees_reconciled_pair_exactness_reopened_pending_comparison_cone','Gersten_weight_two_complex':gersten,'differentials':['K2 tame symbols to divisor K1 units','divisor valuations to point integers'],'symbol_data':{'degree_two':'{u,v}','degree_three_boundary_cochain':['v^-1','u','-v/u'],'degree_four_secondary_sums':'zero by reciprocity'},'regulator_data':'The logarithmic regulator sends the symbol to Xi_log and its tame units to logarithmic residue data. Constant signs have zero dlog but remain integral K1 information.','flag_data':'sigma123 is an oriented cycle in the uncontracted flag/dual-complex resolution and represents the top-weight part of the same degree-two de Rham class; it is not the isolated Gersten degree-three sign class.','cone_gate':'Pair notation (Xi_log,-sigma123) does not define a complex. One must specify the flag complex, logarithmic complex, degree shifts, chain map f, and whether the desired equation is d h=Xi_log-f(sigma123) or a shifted-cone variant.','correction':'Nonvanishing of Xi_log alone does not rule out a comparison homotopy, because projection from a mapping cone need not be a chain map.','decision':'Exactness is reopened. The valid next test is construction of the chain-level comparison, followed by a distinction between abstract cone acyclicity and source-natural horn provenance.','next_gate':'comparison-cone-definition: define B_flag, A_log, f, shifts, and the exact degree-one homotopy equation','limitations':['degree reconciliation does not construct f or h','former pair-nonexactness and universal horn no-go are superseded','rank26 absorption and degree-two status of {u,v} remain valid'],'passed':True};OUT.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
if __name__=='__main__':main()
