"""Compute torus cohomology with a rank-one character local system."""
from __future__ import annotations
import json
from fractions import Fraction
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'research'/'voevodsky'/'results'/'cosmology_twisted_coefficient_character_gate.json'
def ranks(a,b):
 # Koszul cochains K -> K^2 -> K for (a-1,b-1).
 trivial=(a==1 and b==1)
 return {'H0':1 if trivial else 0,'H1':2 if trivial else 0,'H2':1 if trivial else 0}
def primitive(a,b):
 if a!=1:return {'edge_v':Fraction(1,a-1)}
 if b!=1:return {'edge_u':Fraction(-1,b-1)}
 return None
def main():
 assert ranks(1,1)=={'H0':1,'H1':2,'H2':1}
 for a,b in ((2,1),(1,3),(2,3),(-1,1)):
  assert ranks(a,b)=={'H0':0,'H1':0,'H2':0} and primitive(a,b) is not None
 assert primitive(1,1) is None
 out={'schema':'marici.voevodsky.cosmology-twisted-coefficient-character-gate.v1','status':'nontrivial_character_kills_class_but_specialization_is_singular','cellular_complex':'K -> K^2 -> K with Koszul differentials generated by a-1 and b-1','cohomology':'For the trivial character (a,b)=(1,1), ranks are (1,2,1). If either monodromy is nontrivial over a field, the complex is acyclic.','family_module':'Over Q[a^+/-1,b^+/-1], top cohomology is Q[a^+/-1,b^+/-1]/(a-1,b-1), supported only at the trivial character.','primitive_gate':'For a!=1 a primitive divides by a-1; for b!=1 it divides by b-1. Every such primitive has a pole or becomes undefined at the trivial character where Xi_log lives.','coefficient_gate':'A nontrivial local system changes the coefficient object and has no integral Parshin comparison to the fixed trivial-coefficient sigma123 without additional transport data.','decision':'Twisted coefficients make the generic character complex exact only by removing the target class. The jump at the trivial character is nonflat, and no faithful regular specialization transports a primitive to Xi_log.','next_gate':'character-specialization-residue: compute the two-parameter Koszul residue at (1,1) and determine whether it adds information beyond the existing unit obstruction','limitations':['rank-one local systems over a characteristic-zero field','does not classify nonabelian coefficient systems','no physical monodromy source inferred'],'passed':True};OUT.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
if __name__=='__main__':main()
