"""Test preservation of the twisted Cartier lattice by the exact cross-term."""

from fractions import Fraction


def multiply(first, second):
    result = {}
    for i, x in first.items():
        for j, y in second.items():
            result[i + j] = result.get(i + j, Fraction(0)) + x * y
    return {degree: coefficient for degree, coefficient in result.items() if coefficient}


def power(polynomial, exponent):
    result = {0: Fraction(1)}
    for _ in range(exponent):
        result = multiply(result, polynomial)
    return result


def evaluate(polynomial, value):
    return sum(coefficient * value**degree for degree, coefficient in polynomial.items())


def derivative(polynomial):
    return {degree - 1: degree * coefficient for degree, coefficient in polynomial.items() if degree}


def vanishing_order(polynomial, point):
    current = dict(polynomial)
    for order in range(20):
        if evaluate(current, point):
            return order
        current = derivative(current)
    raise AssertionError("order exceeds audit bound")


def main():
    b_minus_one = {1: Fraction(1), 0: Fraction(-1)}
    b_plus_one = {1: Fraction(1), 0: Fraction(1)}
    w = multiply(power(b_minus_one, 3), power(b_plus_one, 4))
    w = {degree: coefficient / 8 for degree, coefficient in w.items()}
    assert vanishing_order(w, Fraction(1)) == 3
    assert vanishing_order(w, Fraction(-1)) == 4

    # Frozen D_b=a(1-c*d_c) sends the even constant 1 to the untwisted odd
    # element a.  The derived odd Cartier lattice is generated by w*a, so the
    # matrix coefficient of this cross-term is 1/w.
    cross_term_on_unit = "a"
    odd_lattice_generator = "w*a"
    assert cross_term_on_unit != odd_lattice_generator

    # A regular map O -> wO must have image coefficient divisible by w.
    # The coefficient 1 is not divisible because w has positive degree and
    # boundary zeros.  Its expression in the w-frame has pole orders (3,4).
    assert evaluate(w, Fraction(1)) == 0
    assert evaluate(w, Fraction(-1)) == 0
    assert max(w) == 7

    print("exact_cross_term: D_b(1)=a")
    print("derived_odd_lattice_generator: w*a")
    print("cross_term_in_odd_frame: 1/w")
    print("pole_order_b_plus_1: 3")
    print("pole_order_b_minus_1: 4")
    print("regular_lattice_morphism: NO")
    print("log_connection_alone_repairs_cross_term: NO")
    print("naive_even_plus_odd_de_Rham_split: INVALID")
    print("required_structure: TWO_LATTICE_PARABOLIC_OR_HEECKE_COMPLEX")
    print("next_gate: DERIVE_SOURCE_AND_TARGET_LATTICES_FOR_THE_OFF_DIAGONAL_EXACT_MAP")


if __name__ == "__main__":
    main()
