"""Transport the 390 exact second-direction words through squared-axis shifts."""
from __future__ import annotations
import json,os,sys
from fractions import Fraction
from pathlib import Path
os.environ['MARICI_AMBIENT']='12'
ROOT=Path(__file__).resolve().parents[2];sys.path[:0]=[str(ROOT/'research'/'benincasa'),str(ROOT/'research'/'voevodsky')]
import physical_four_mark_residue_twisted_derham as base
import check_rank26_total_energy_triple_relation_module as rees
import check_cosmology_rank26_p_normal_raw_relation_adapter as adapter
import check_cosmology_rank26_p_normal_K_q_seed_exact_rational_minor as ex
import check_cosmology_source_word_axis_square_transport as tr
RES=ROOT/'research'/'voevodsky'/'results';OUT=RES/'cosmology_second_direction_all_even_transport.json'
def add(r,b,a):
 for c,v in b.items():
  z=r.get(c,Fraction())+a*v
  if z:r[c]=z
  else:r.pop(c,None)
def shifted(d,path):
 for a in path:d=tr.shift(d,a)
 return d
def main():
 gate=json.loads((RES/'cosmology_rank26_p_normal_protocol_gate.json').read_text());point=tuple(gate['test_point_xyz']);t1=tuple(gate['integral_unit_normals']['p_tangent_difference']);t2=(3,0,-1);certs=(json.loads((RES/'cosmology_second_direction_exact_certificate_words.json').read_text())['records']+json.loads((RES/'cosmology_second_direction_local_exact_words.json').read_text())['records']);assert len(certs)==1224 and len({c['target_id'] for c in certs})==1224
 induction=json.loads((RES/'cosmology_all_even_linear_transport_induction.json').read_text());assert induction['passed']
 desc12=tr.descs(12);all12=desc12[0]+desc12[1]+desc12[2];decode={'T':all12,'S_K':desc12[1],'Q':desc12[2]};targets={}
 for family,name in [('IBP','cosmology_IBP_exact_source_certificates_a12.json'),('K','cosmology_nonmarked_K_exact_seeds_a12.json'),('q','cosmology_q_exact_source_certificates_a12.json')]:
  for rec in json.loads((RES/name).read_text())['records']:targets[rec['source_certificate']['canonical_target_id']]=tr.target_desc(family,rec)
 plans={14:[(0,),(1,)],16:[(0,0),(0,1),(1,0),(1,1)]};requests={}
 oldA=rees.AMBIENT
 for A,paths in plans.items():
  rees.AMBIENT=A;_,cols=rees.column_packet();ds=tr.descs(A);alls=ds[0]+ds[1]+ds[2];idx={'T':{d:i for i,d in enumerate(alls)},'S_K':{d:i for i,d in enumerate(ds[1])},'Q':{d:i for i,d in enumerate(ds[2])},'D2':{d:i for i,d in enumerate(alls)}};req={k:set() for k in idx};items=[]
  for c in certs:
   for path in paths:
    src=[]
    for term in c['word_terms']:
     kind=term['kind'];d=shifted(decode[kind][term['row_index']],path);i=idx[kind][d];req[kind].add(i);src.append((kind,i,Fraction(term['numerator'],term['denominator'])))
    ti=idx['D2'][shifted(targets[c['target_id']],path)];req['D2'].add(ti);items.append((c['target_id'],path,src,ti))
  requests[A]=(cols,req,items)
 rees.AMBIENT=oldA
 exact_rows={}
 try:
  for A,(cols,req,items) in requests.items():
   ds=tr.descs(A);nI=len(ds[0]);nK=len(ds[1]);per={k:{i:[] for i in ids} for k,ids in req.items()}
   rees.AMBIENT=A
   for p in ex.PS:
    base.PRIME=p;raw=list(rees.raw_relations(point,cols));T,_=adapter.derivative_rows(cols,point,t1);D2,_=adapter.derivative_rows(cols,point,t2);pack={'T':T,'S_K':raw[nI:nI+nK],'Q':raw[nI+nK:],'D2':D2}
    for k,ids in req.items():
     for i in ids:per[k][i].append(pack[k][i])
   exact_rows[A]={k:{i:ex.exact_row(rows) for i,rows in vals.items()} for k,vals in per.items()}
 finally:
  base.PRIME=ex.PS[0];rees.AMBIENT=oldA
 checks={};fail=[]
 for A,(cols,req,items) in requests.items():
  count=0;by={}
  for tid,path,src,ti in items:
   recon={}
   for k,i,a in src:add(recon,exact_rows[A][k][i],a)
   target={c:Fraction(v) for c,v in exact_rows[A]['D2'][ti].items()}
   if recon!=target:fail.append({'A':A,'target_id':tid,'path':path})
   count+=1;by[(tid,path)]=(tuple((k,i,a) for k,i,a in src),target)
  checks[str(A)]={'path_replays':count,'failures':sum(1 for x in fail if x['A']==A)}
  if A==16:
   for c in certs:
    a=by[(c['target_id'],(0,1))];b=by[(c['target_id'],(1,0))];assert a==b
   checks[str(A)]['mixed_path_equalities']=1224
 assert not fail
 out={'schema':'marici.voevodsky.cosmology-second-direction-all-even-transport.v1','status':'second_direction_exact_absorption_transports_to_all_even_A','seed_certificates':1224,'A14':checks['14'],'A16':checks['16'],'exact_arithmetic':'four-prime CRT integer-row reconstruction followed by rational word replay','induction':'Squared-axis descriptor maps preserve source kinds and coefficients; A16 mixed paths commute; the established parity-orbit induction covers every even A>=12.','consequence':'The second tangent and derived unit-normal quotient classes vanish for the formerly unresolved families at every even A>=12. Together with the 834 local replays, algebraic zero-class normal independence holds on the full integral unit-normal torsor generated by nx and the two tangent-lattice generators.','scope':'Labelled algebraic relation presentation only; no geometric normal bundle, supported specialization, or exceptional Bockstein.','next_gate':'classify-algebraic-normal-torsor-zero-theorem','passed':True};OUT.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
if __name__=='__main__':main()
