"""Formulate the primitive obstruction without choosing a signed torus basis."""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'research'/'voevodsky'/'results'/'cosmology_orientation_free_obstruction.json'
def det(a):return a[0][0]*a[1][1]-a[0][1]*a[1][0]
def main():
 gl2=[[[1,0],[0,1]],[[0,1],[1,0]],[[1,1],[0,1]],[[-1,0],[0,1]]]
 signs=[det(a) for a in gl2];assert signs==[1,-1,1,-1]
 primitive_generators={-1,1};assert len(primitive_generators)==2
 out={'schema':'marici.voevodsky.cosmology-orientation-free-obstruction.v1','status':'canonical_object_is_primitive_determinant_line_not_signed_generator','character_lattice':'M=Hom(G_m,T) or equivalently the rank-two lattice generated by u and v','orientation_line':'det(M)=exterior_square M, a free rank-one integral lattice','comparison':'Normalized de Rham classes, Betti top classes, Parshin cycles, and character residues define compatible integral realizations of det(M). Milnor symbols agree after rationalization or projection away from diagonal 2-torsion corrections.'','generator_torsor':'The two primitive generators form a torsor under {+1,-1}. An ordered basis modulo SL(2,Z), an oriented Betti torus, or a cyclic orientation of the boundary triangle selects one.','coordinate_covariance':'A GL(2,Z) coordinate change acts on every signed realization by its determinant. Determinant-one changes preserve the generator; determinant-minus-one changes reverse it.','no_go_invariance':'The horn obstruction needs only nonvanishing and primitivity, both invariant under sign. It does not depend on choosing which generator is positive.','physical_boundary':'A signed physical value would require external orientation authority. The unoriented mathematical obstruction requires none.','decision':'The canonical result is the nonzero primitive determinant/Tate line. Statements assigning +1 are shorthand for this line plus an explicit orientation choice.','next_gate':'GL2Z-covariance: verify the determinant law for general monomial coordinate changes across regulator, period, and residue realizations','limitations':['rank-two split torus','does not choose physical orientation','Tate twist convention remains explicit'],'passed':True};OUT.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
if __name__=='__main__':main()
