"""Specify and validate the minimal contract for a physical K2 period readout."""
from __future__ import annotations
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'research'/'voevodsky'/'results'/'cosmology_external_boundary_condition_contract.json'
REQUIRED=('physical_source','kinematic_map','cycle_map','avoidance_certificate','orientation_authority','boundary_prescription','normalization','state_effect_pairing','record_map')
def valid(x):return all(x.get(k) for k in REQUIRED)
def main():
 abstract={k:'typed' for k in REQUIRED};assert valid(abstract)
 for missing in REQUIRED:
  bad=dict(abstract);bad[missing]=None;assert not valid(bad)
 out={'schema':'marici.voevodsky.cosmology-external-boundary-condition-contract.v1','status':'minimal_physical_period_contract_defined_uninstantiated','contract':{'physical_source':'typed kinematic or configuration object P','kinematic_map':'source-derived map kappa:P -> U(C)','cycle_map':'a closed oriented two-cycle c:T2 -> U(C), or an equivalent class in H2, selected from P','avoidance_certificate':'c avoids the boundary divisor and every singular locus required by the integrand','orientation_authority':'source datum fixing the order (u,v) and the sign of the cycle','boundary_prescription':'declared real form, i-epsilon rule, or other physical condition selecting c','normalization':'map from the normalized Betti-de Rham period to the claimed quantity and units','state_effect_pairing':'positive typed state/effect pairing when a probabilistic or operational value is claimed','record_map':'map from the pairing or amplitude contribution to a stable physical record'},'mathematical_consequence':'The first six contour fields determine a signed period; for the primitive torus generator its normalized value is +1 or -1 according to orientation.','physical_consequence':'Only the complete contract can promote that period to a physical readout. A contour without the normalization, pairing, and record arrows remains mathematical.','falsifiers':['cycle intersects a pole or boundary divisor','orientation changes without source change','kinematic map does not land in U','claimed record is invariant under neither homology nor the declared boundary prescription','normalization is fitted after observing the desired value'],'current_instantiation':'none of the required physical fields is instantiated by the audited characteristic-zero programme','decision':'The external authority boundary is now explicit. No physical claim is admissible until one source supplies all nine typed fields and their compatibility checks.','next_gate':'contract-instantiation-search: test candidate cosmological boundary data against all nine fields without inferring missing arrows from coordinate similarity','limitations':['contract is a gate, not evidence that an instantiation exists','positivity is required only for state-effect probability claims','no physical-time map is assumed unless the candidate uses physical time'],'passed':True};OUT.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
if __name__=='__main__':main()
