"""Classify integral degree-one source enlargements capable of filling the primitive horn."""
from __future__ import annotations
import json,math
from functools import reduce
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];OUT=ROOT/'research'/'voevodsky'/'results'/'cosmology_minimal_source_enlargement_classification.json'
def gcd(xs):return reduce(math.gcd,(abs(x) for x in xs),0)
def bezout(ns):
 coeff=[1];g=ns[0]
 for n in ns[1:]:
  old_g=g
  def eg(a,b):
   if b==0:return (abs(a),1 if a>=0 else -1,0)
   h,x,y=eg(b,a%b);return h,y,x-(a//b)*y
  g,x,y=eg(old_g,n);coeff=[x*c for c in coeff]+[y]
 return g,coeff
def main():
 cases={}
 for ns in ([1],[2],[2,3],[6,10,15],[2,4]):
  g,c=bezout(list(ns));cases[','.join(map(str,ns))]={'gcd':g,'kills_primitive':g==1,'coefficients':c,'pairing':sum(a*n for a,n in zip(c,ns))}
 assert cases['1']['kills_primitive'] and not cases['2']['kills_primitive'] and cases['2,3']['pairing']==1 and cases['6,10,15']['pairing']==1 and not cases['2,4']['kills_primitive']
 # Deliberate failure: even attachment degrees cannot generate the primitive unit.
 assert gcd([2,4])==2 and all((2*a+4*b)!=1 for a in range(-10,11) for b in range(-10,11))
 out={'schema':'marici.voevodsky.cosmology-minimal-source-enlargement-classification.v1','status':'integral_horn_enlargements_classified_by_primitive_boundary_and_residue_matching','current_obstruction':{'exceptional_boundary_group':'Z on primitive Xi_log','rank26_DNC_image':'zero','fixed_open_SNC_modifications':'preserve the primitive class'},'extension_contract':{'generators':'degree-one sourced generators h_j','differentials':'d h_j = n_j Xi_log + r_j sigma123 plus independently typed components','Xi_condition':'the ideal generated by n_j must be Z','full_horn_condition':'there must be integers a_j with sum a_j n_j=1 and sum a_j r_j=-1, with every other differential component cancelling'},'minimal_cases':{'one_generator':'necessary and sufficient coefficients n=+/-1 and matching residue coefficient -/+1','multiple_generators':'nonunit generators suffice exactly when their full boundary vectors admit the required integral Bezout combination; gcd(n_j)=1 alone addresses only Xi_log'},'excluded_loci':['rank26 IBP+K+q derivative module and its DNC/Rees image','ordinary blow-up and fixed-open toroidal/SNC resolutions','all smooth proper SNC compactifications of the fixed G_m^2 open','mapping-cone packaging without an independently sourced nullhomotopy'],'geometric_consequence':'Any realization must change the source pair/category by adding genuine degree-one incidence data. Combinatorially it must attach a primitive filling of the exceptional triangle; subdivisions cannot do this.','tested_cases':cases,'decision':'The smallest admissible enlargement is one genuinely sourced degree-one generator with primitive unit boundary (Xi_log,-sigma123). If unavailable, a multi-generator enlargement is admissible only when its complete boundary matrix has that vector in its integral column lattice.','next_gate':'search source geometry outside fixed-open SNC modifications for an integral primitive face/precycle and test its complete boundary vector','limitations':['classification is universal algebra once boundary vectors are sourced','does not construct a geometric generator','does not authorize tautological cell attachment'],'passed':True};OUT.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
if __name__=='__main__':main()
