"""Formal audit: p-tangent quotient identifies normal choices but does not tautologically kill them."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
RES = ROOT / "research" / "voevodsky" / "results"
OUT = RES / "cosmology_rank26_p_normal_absorption_not_tautological.json"


def load(name: str) -> dict:
    return json.loads((RES / name).read_text(encoding="utf-8"))


def main() -> None:
    raw = load("cosmology_rank26_p_normal_raw_relation_adapter.json")
    protocol = load("cosmology_rank26_p_normal_protocol_gate.json")
    packets = {
        8: load("cosmology_rank26_p_normal_two_prime_quotient.json"),
        10: load("cosmology_rank26_p_normal_degree10_two_prime.json"),
        12: load("cosmology_rank26_p_normal_degree12_two_prime.json"),
        14: load("cosmology_rank26_p_normal_degree14_two_prime.json"),
        16: load("cosmology_rank26_p_normal_degree16_two_prime.json"),
        18: load("cosmology_rank26_p_normal_degree18_two_prime.json"),
    }
    assert raw["passed"] and protocol["passed"]
    assert raw["tangent_identity"]["passed"]
    assert raw["tangent_identity"]["failures"] == 0
    assert raw["tangent_identity"]["identity"] == "D_nx(row)-D_ny(row)=D_(nx-ny)(row) for every raw labelled relation row"

    witnesses = {}
    for degree, packet in packets.items():
        assert packet["passed"] and packet["ambient_relation_degree"] == degree
        degree_witness = {}
        for prime in ("32003", "32009"):
            sig = packet["rank_signatures"][prime]
            tangent_rank = sig["p_tangent_over_special"]
            nx_zero = sig["nx_over_special_plus_p_tangent"] == 0
            ny_zero = sig["ny_over_special_plus_p_tangent"] == 0
            both_zero = sig["nx_and_ny_over_special_plus_p_tangent"] == 0
            assert tangent_rank > 0
            assert nx_zero and ny_zero and both_zero
            degree_witness[prime] = {
                "p_tangent_quotient_relation_nonzero_before_quotient": tangent_rank,
                "normal_choices_identified_mod_tangent": True,
                "common_normal_image_zero_mod_special_plus_tangent": True,
            }
        witnesses[str(degree)] = degree_witness

    # Linear-algebra contract:
    # T is generated by D_nx-D_ny. Killing T alone imposes [D_nx]=[D_ny];
    # it does not imply this common class is zero. Zero is a separate containment
    # certified by the extension-rank calculations.
    result = {
        "schema": "marici.voevodsky.cosmology-rank26-p-normal-absorption-not-tautological.v1",
        "status": "tangent_quotient_only_identifies_normal_choices_zero_common_image_is_extra_rank_fact",
        "rechecked_inputs": [
            "research/voevodsky/results/cosmology_rank26_p_normal_raw_relation_adapter.json",
            "research/voevodsky/results/cosmology_rank26_p_normal_two_prime_quotient.json",
            "research/voevodsky/results/cosmology_rank26_p_normal_degree10_two_prime.json",
            "research/voevodsky/results/cosmology_rank26_p_normal_degree12_two_prime.json",
            "research/voevodsky/results/cosmology_rank26_p_normal_degree14_two_prime.json",
            "research/voevodsky/results/cosmology_rank26_p_normal_degree16_two_prime.json",
            "research/voevodsky/results/cosmology_rank26_p_normal_degree18_two_prime.json",
        ],
        "formal_lemma": {
            "raw_identity": "D_nx-D_ny=D_t with t=nx-ny p-tangent",
            "effect_of_quotient_by_T": "identifies [D_nx] and [D_ny]",
            "not_implied_by_quotient": "the common class [D_nx]=[D_ny] is zero",
            "extra_computed_fact": "both normal derivative spans have extension rank zero over S+T",
        },
        "two_prime_degree_witnesses": witnesses,
        "anti_tautology_check": {
            "T_mod_S_is_nonzero_at_every_tested_degree": True,
            "vanishing_of_common_normal_image_requires_rank_computation": True,
            "forbidden_inference_rejected": "D_nx-D_ny in T does not by itself imply D_nx or D_ny lies in S+T",
        },
        "conclusion": "The finite absorption result is not manufactured by quotienting the two normal choices against each other. T enforces normal-choice independence; the zero common image is an additional two-prime rank fact at degrees 8,10,12,14,16,18.",
        "scope": "finite tested degrees and primes only; no uniform chain homotopy or induction constructed",
        "relative_bockstein_constructed": False,
        "physical_period_constructed": False,
        "passed": True,
    }
    OUT.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
