#!/usr/bin/env python3
"""Require the nonlocal Gram-completion inequality in every positive prototype."""
import copy,json,hashlib
from pathlib import Path
root=Path(__file__).parents[1];res=root/'results';src=json.loads((res/'positive_prototype_certificate_contracts_with_relative_witnesses.json').read_text());gate=json.loads((res/'first_forward_reverse_positive_filler_gate.json').read_text());out=copy.deepcopy(src)
for name,rec in out['contracts'].items():
 rec['obligations']['coupled_kernel_positive_completion']={'required':True,'witness':None,'verified':False,'criterion':'for normalized three-reading restriction: 1-b>=0 and 1+b-2a^2>=0; higher-rank analogue requires directed Gram/Schur positivity'}
 rec['positive_certified']=False
out['schema']='marici.voevodsky.positive-prototype-certificate-contracts-coupled-kernel.v2';out['coupled_kernel_gate']={'witness':'results/first_forward_reverse_positive_filler_gate.json','lower_faces_not_sufficient':True,'hostile_fixture_all_lower_faces_psd':gate['fixtures'][1]['all_rank_two_faces_psd'],'hostile_full_filler_exists':gate['fixtures'][1]['rank_three_positive_filler_exists'],'exact_normalized_interval':gate['positive_filler_interval']};out['positive_certified_count']=0;out['universal_positive_realization']=False;out['artifact_hash']=hashlib.sha256((res/'first_forward_reverse_positive_filler_gate.json').read_bytes()).hexdigest();checks={'all_contracts_have_coupled_gate':all('coupled_kernel_positive_completion' in x['obligations'] for x in out['contracts'].values()),'hostile_fixture_proves_gate_independent':gate['fixtures'][1]['all_rank_two_faces_psd'] and not gate['fixtures'][1]['rank_three_positive_filler_exists'],'no_false_promotion':not any(x['positive_certified'] for x in out['contracts'].values())};out['coupled_gate_checks']=checks;p=res/'positive_prototype_certificate_contracts_coupled_kernel_v2.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'schema':out['schema'],'prototype_contracts':len(out['contracts']),'coupled_kernel_gate':out['coupled_kernel_gate'],'checks':checks,'positive_certified_count':0},indent=2));assert all(checks.values())
