#!/usr/bin/env python3
"""Audit whether recent geometric pairings are typed as the missing total-energy extension column."""
import json
from pathlib import Path
R=Path(__file__).resolve().parents[3]
res=json.loads((R/'research/benincasa/total-energy-nine-master-residue.json').read_text())
soft=json.loads((R/'research/benincasa/results/rank12-u2-v0-node-to-e6-gysin.json').read_text())
local=(R/'research/voevodsky/paired_local_thimbles_collapse_to_one_mod_two_direction.md').read_text()
checks={'total_energy_e6_residue_zero':res['gysin_kernel_check']['e6_residue']==0,'total_energy_valg_kernel_component_zero':'zero algebraic-kernel component' in res['gysin_kernel_check']['conclusion'],'missing_object_is_rank12_top_column':'off-diagonal marked top-column' in res['classification']['remaining_problem'],'soft_comparison_at_distinct_locus':soft['center']['u']==2 and soft['center']['v']==0,'soft_scope_denies_global_Betti':'no global Betti normalization claim' in soft['scope'],'local_pair_denies_ambient_image':'does not identify their image' in local,'physical_cut_pairing_not_computed':True}
assert all(checks.values()),checks
out={'schema':'marici.voevodsky.claimed-direct-parity-pairings-audit.v1','typed_target':'off-diagonal marked rank-twelve top-column residue at total energy E=0','e6_argument':{'input':'soft-node comparison at (u,v)=(2,0)','failure':'no proved transport from that soft center to the generic total-energy marked extension and no integral e6 Betti normalization','bit_established':False},'valg_argument':{'input':'Poincare residue of a rank-nine algebraic form on the conductor','failure':'the rank-nine total-energy residue has zero algebraic-kernel component; the desired datum is the absent marked top-column, so this computes a diagonal/algebraic pairing rather than the extension entry','bit_established':False},'source_total_energy_result':{'e6_residue':0,'algebraic_kernel_component':'zero','remaining_problem':res['classification']['remaining_problem']},'conclusion':'Neither recent computation is yet typed as one of the two required off-diagonal integral intersections. The boxed pair (1,0) must be withdrawn.','checks':checks,'passed':True,'surviving_new_geometry':'global double-conic model, four-point smoothing section, BD-oriented Cech half-boundary','next':'construct the marked rank-twelve specialization of its top relative generator and pair that exact column with integral e6 and v_alg duals'}
(R/'research/voevodsky/results/claimed_direct_parity_pairings_audit.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'e6_bit_established':False,'valg_bit_established':False,'conclusion':out['conclusion'],'next':out['next']}))
