#!/usr/bin/env python3
"""Final seven-gate audit for the universal positive-filler program."""
import json,hashlib
from pathlib import Path
root=Path(__file__).parents[1];res=root/'results';files=['positive_prototype_certificate_contracts_coupled_kernel_v2.json','robust_complement_block_registry.json','moving_bundle_certificate_L0649_L065.json','eight_lattice_compatibility_frontier.json','terminal_relative_positive_pair_filler.json','terminal_positive_row_uniqueness_no_go.json','zero_free_region_remainder_no_asymptotic_N0.json','L075_directed_certificate_contract.json','uniform_weil_proof_gate_audit_v2.json'];D={n:json.loads((res/n).read_text()) for n in files};gates={
 '1_source_faithful_positive_every_prototype':{'closed':False,'certified':D[files[0]]['positive_certified_count'],'total':len(D[files[0]]['contracts']),'blocker':'coupled-kernel/Douglas completion witnesses absent'},
 '2_directed_robust_complements':{'closed':D[files[1]]['all_blocks_directed'],'certified_registered':D[files[1]]['directed_certified_count'],'blocker':'L=.55 and [.649,.65] directed blocks open'},
 '3_moving_bundle_every_slab':{'closed':False,'local_L0649_L065_closed':D[files[2]]['closed'],'blocker':'directed frame, robust block, ellipse remainder, and remaining slabs'},
 '4_positive_compatibility':{'closed':D[files[3]]['positive_compatibility_certified'],'signed_relative_closed':D[files[3]]['signed_relative_compatibility_certified'],'blocker':'ordinary positive compatibility/all-rank uniformity not proved'},
 '5_terminal_6_to_7':{'closed_relative':D[files[4]]['relative_pro_filler'],'closed_ordinary':False,'ordinary_impossible_current_category':D[files[5]]['passed'],'disposition':'resolved only after explicit change to relative positive-pair target'},
 '6_unconditional_hankel_and_N0':{'closed':False,'classical_PNT_route_excluded':D[files[6]]['passed'],'blocker':'RH-strength signed weighted-Hankel cancellation theorem absent'},
 '7_directed_finite_thresholds':{'closed':False,'L075_closed':D[files[7]]['closed'],'blocker':'L=.75 residual assembly, L=.55, and all thresholds below unavailable N0'}
};out={'schema':'marici.voevodsky.universal-positive-filler-gate-audit.v3','gates':gates,'closed_gate_count':sum(bool(x.get('closed',False)) for x in gates.values()),'relative_terminal_resolution_counted_separately':True,'universal_positive_filler_certified':False,'global_weil_positivity_established':False,'rh_proved':False,'next_nonredundant_actions':['implement 113-bit directed reduced assembly on [.649,.65]','implement Arb degree-149 residual norm at L=.75','construct coupled-kernel witnesses prototype-by-prototype','prove new signed weighted-Hankel discrepancy theorem or state an explicit hypothesis'],'artifact_hashes':{n:hashlib.sha256((res/n).read_bytes()).hexdigest() for n in files},'passed_audit':True};p=res/'universal_positive_filler_gate_audit_v3.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2));assert out['passed_audit'] and not out['universal_positive_filler_certified']
