#!/usr/bin/env python3
"""Select the active relative minor by exact Gauss-Manin zero patterns."""
from hashlib import sha256
from pathlib import Path
import json
import sympy as s
from sympy.matrices.normalforms import smith_normal_form
from sympy.polys.domains import ZZ
ROOT=Path(__file__).resolve().parents[3];PACKET=ROOT/'research/voevodsky/gauss_manin_stability_selects_one_active_relative_parity_minor.md';RESULT=ROOT/'research/voevodsky/results/gauss_manin_stable_relative_minor.json';PAGE=ROOT/'references/extractions/pdf-search-all/cosmology-meets-cohomology-2308-03753/pdf-page-0021.txt'
C=s.Matrix([[0,-1,1,0],[1,0,0,0],[1,1,0,1],[-1,0,1,-1]]);active=[0,2,3];C1=C.extract(active,[1,2,3]);C4=C.extract(active,[0,1,2]);d11,d13,d14,d22,d33,d44=s.symbols('d11 d13 d14 d22 d33 d44');Adual=s.Matrix([[d11,0,d13,d14],[0,d22,0,0],[0,0,d33,0],[0,0,0,d44]]);x11,x12,x13,x22,x23,x24,x32,x33,x34,x42,x43,x44=s.symbols('x11 x12 x13 x22 x23 x24 x32 x33 x34 x42 x43 x44');Acan=s.Matrix([[x11,x12,x13,0],[0,x22,x23,x24],[0,x32,x33,x34],[0,x42,x43,x44]]);stable=lambda A,idx:all(A[i,j]==0 for i in idx for j in range(A.cols) if j not in idx);checks={'dual_active_stable':stable(Adual,active),'dual_inactive_line_stable':stable(Adual,[1]),'canonical_omit1_stable':stable(Acan,[1,2,3]),'canonical_omit4_not_stable':not stable(Acan,[0,1,2]),'omit4_leakage_two':Acan[1,3]==x24 and Acan[2,3]==x34,'selected_matrix_exact':C1==s.Matrix([[-1,1,0],[1,0,1],[0,1,-1]]),'selected_det_two':C1.det()==2,'selected_smith_112':[abs(int(smith_normal_form(C1,domain=ZZ)[i,i])) for i in range(3)]==[1,1,2],'rejected_minor_nondegenerate_but_unstable':C4.det()==2 and not stable(Acan,[0,1,2]),'transport_gate_retained':'transport to either conductor wall remains unconstructed' in PACKET.read_text(encoding='utf-8')};checks={k:bool(v) for k,v in checks.items()}
result={'schema':'marici.voevodsky.gauss-manin-stable-relative-minor.v1','packet_sha256':sha256(PACKET.read_bytes()).hexdigest(),'source_page_sha256':sha256(PAGE.read_bytes()).hexdigest(),'dual_active_indices':[1,3,4],'canonical_selected_indices':[2,3,4],'selected_matrix':[list(map(int,C1.row(i))) for i in range(3)],'rejected_nondegenerate_omission':4,'checks':checks,'passed':all(checks.values()),'disposition':{'connection_stable_candidate':'omit canonical column 1','omit_column_4':'rejected by generic leakage','conductor_transport':'missing'}}
RESULT.write_text(json.dumps(result,indent=2)+'\n',encoding='utf-8');print(json.dumps({'passed':result['passed'],'checks':checks,'disposition':result['disposition']}));raise SystemExit(0 if result['passed'] else 1)
