#!/usr/bin/env python3
"""Verify the conductor discriminant equalizer and E=0 Kummer specialization."""
from hashlib import sha256
from pathlib import Path
import json
import sympy as s
ROOT=Path(__file__).resolve().parents[3];PACKET=ROOT/'research/voevodsky/common_kummer_parameter_exists_on_total_energy_specialization.md';RESULT=ROOT/'research/voevodsky/results/common_kummer_total_energy_parameter.json';SOURCE=ROOT/'research/benincasa/moving-wall-residue-kummer-connection.json'
data=json.loads(SOURCE.read_text(encoding='utf-8'));E,x,y,r=s.symbols('E x y r');a1=E*x;b1=2*x*y;c1=-2*x*y+E*(x+2*y-E);a2=E*y;b2=-2*x*y;c2=-2*x*y+E*(2*x+y-E);Delta1=s.factor(b1**2-4*a1*c1);Delta2=s.factor(b2**2-4*a2*c2);diff=s.factor(Delta1-Delta2);Yrel=2*x*y;X1=s.expand(2*a1*r+b1);X2=s.expand(2*a2*r+b2);checks={'source_discriminant_1':s.expand(Delta1-s.sympify(data['wall_1']['discriminant'].split('=')[1].replace('^','**'),locals={'E':E,'x':x,'y':y}))==0,'source_discriminant_2':s.expand(Delta2-s.sympify(data['wall_2']['discriminant'].split('=')[1].replace('^','**'),locals={'E':E,'x':x,'y':y}))==0,'equalizer_factorization':diff==4*E*(x-y)*(E**2-E*x-E*y+2*x*y),'common_E0_discriminant':s.simplify(Delta1.subs(E,0)-4*x**2*y**2)==0 and s.simplify(Delta2.subs(E,0)-4*x**2*y**2)==0,'affine_coordinate_1':s.simplify(X1.subs(E,0)-Yrel)==0,'affine_coordinate_2':s.simplify(X2.subs(E,0)+Yrel)==0,'opposite_vanishing_factors':s.simplify((X1-Yrel).subs(E,0))==0 and s.simplify((X2+Yrel).subs(E,0))==0,'wall_roots_E0':s.factor((a1*r**2+b1*r+c1).subs(E,0))==2*x*y*(r-1) and s.factor((a2*r**2+b2*r+c2).subs(E,0))==-2*x*y*(r+1),'generic_gate_retained':'not a generic Gauss–Manin identification' in PACKET.read_text(encoding='utf-8'),'geometric_map_missing':'remaining blocker is a geometric map' in PACKET.read_text(encoding='utf-8')};checks={k:bool(v) for k,v in checks.items()}
result={'schema':'marici.voevodsky.common-kummer-total-energy-parameter.v1','packet_sha256':sha256(PACKET.read_bytes()).hexdigest(),'source_sha256':sha256(SOURCE.read_bytes()).hexdigest(),'discriminant_difference':str(diff),'equalizer_components':['E=0','x=y','E^2-E*(x+y)+2*x*y=0'],'E0_common_discriminant':'4*x^2*y^2','orientation_branches':['Y_rel=2*x*y','Y_rel=-2*x*y'],'E0_wall_factors':['2*x*y*(r-1)','-2*x*y*(r+1)'],'checks':checks,'passed':all(checks.values()),'disposition':{'parameter_comparison':'exists on E=0 up to square-root orientation','generic_comparison':'absent','geometric_support_map':'missing','physical_status':'unverified'}}
RESULT.write_text(json.dumps(result,indent=2)+'\n',encoding='utf-8');print(json.dumps({'passed':result['passed'],'equalizer':result['equalizer_components'],'checks':checks,'disposition':result['disposition']}));raise SystemExit(0 if result['passed'] else 1)
