#!/usr/bin/env python3
"""Verify that J1,J2 remove the two primitive half-connections separately."""
from hashlib import sha256
from pathlib import Path
import json
import sympy as s
ROOT=Path(__file__).resolve().parents[3];PACKET=ROOT/'research/voevodsky/elementary_parity_factors_remove_kummer_half_connections_one_wall_at_a_time.md';RESULT=ROOT/'research/voevodsky/results/wallwise_kummer_half_connection_factors.json';SOURCE=ROOT/'research/benincasa/primitive-conductor-top-connection.json'
data=json.loads(SOURCE.read_text(encoding='utf-8'));a1,a2=s.symbols('a1 a2');Ap=s.Matrix([[a1,0,a1/2],[0,a2,a2/2],[0,0,0]]);Ae=s.diag(a1,a2,0);J=s.Matrix(data['enhanced_intertwiner_J']);J1=s.Matrix([[2,0,1],[0,1,0],[0,0,1]]);J2=s.Matrix([[1,0,0],[0,2,1],[0,0,1]]);A1=s.simplify(J1*Ap*J1.inv());A2=s.simplify(J2*Ap*J2.inv());checks={'source_primitive_shape':data['connection_primitive']==[['a1',0,'a1/2'],[0,'a2','a2/2'],[0,0,0]],'source_top_connection':data['top_connection']=='nabla(g111_tilde)=a1/2*g101+a2/2*g110','full_factorization':J1*J2==J and J2*J1==J,'J1_clears_wall1_only':A1==s.Matrix([[a1,0,0],[0,a2,a2/2],[0,0,0]]),'J2_clears_wall2_only':A2==s.Matrix([[a1,0,a1/2],[0,a2,0],[0,0,0]]),'J2_then_J1_diagonal':s.simplify(J1*A2*J1.inv())==Ae,'J1_then_J2_diagonal':s.simplify(J2*A1*J2.inv())==Ae,'full_intertwiner':Ae*J==J*Ap,'factors_site_exchanged':s.Matrix([[0,1,0],[1,0,0],[0,0,1]])*J1*s.Matrix([[0,1,0],[1,0,0],[0,0,1]])==J2,'geometric_gate_retained':'does not provide the required basis map' in PACKET.read_text(encoding='utf-8')};checks={k:bool(v) for k,v in checks.items()}
result={'schema':'marici.voevodsky.wallwise-kummer-half-connection-factors.v1','packet_sha256':sha256(PACKET.read_bytes()).hexdigest(),'source_sha256':sha256(SOURCE.read_bytes()).hexdigest(),'after_J1':[[str(v) for v in A1.row(i)] for i in range(3)],'after_J2':[[str(v) for v in A2.row(i)] for i in range(3)],'final_diagonal':['a1','a2','0'],'checks':checks,'passed':all(checks.values()),'disposition':{'J1':'removes wall-one half-extension','J2':'removes wall-two half-extension','composition':'diagonal enhanced connection','relative_geometric_realization':'missing'}}
RESULT.write_text(json.dumps(result,indent=2)+'\n',encoding='utf-8');print(json.dumps({'passed':result['passed'],'checks':checks,'disposition':result['disposition']}));raise SystemExit(0 if result['passed'] else 1)
