"""Exact test of a rank-one symmetric quadratic law in the actual source ideal.

Typed products use path-algebra zero for mismatched corners. A separate
explicit reanchoring compares both orders of disjoint event-pair relations.
"""
from pathlib import Path
from fractions import Fraction as Q
import importlib.util
import gzip
import json
import hashlib
ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / 'research/voevodsky/results'
source_path = ROOT / 'research/voevodsky/certificates/verify_filtered_obstruction.py'
pres_path = ROOT / 'research/nima/results/actual-observer-full-finite-presentation.json.gz'
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def save(p, x): p.write_text(json.dumps(x, indent=2) + '\n')
contract = {'source_sha256': sha(source_path), 'presentation_sha256': sha(pres_path),
 'domain': 'Actual rational source recorder ideal; zero-mark two-event relations and their four-event products.',
 'candidate': 'Symmetric products in I^2/I^3 lie in a single fixed line generated by omega.',
 'typing': 'Path-algebra multiplication is zero on noncomposable corners. Reanchored block exchange is separately declared.',
 'I3_gate': 'Source ideal has no length-zero/one pieces; therefore every I^3 term has at least six events.',
 'scope': 'Source associated graded, not arbitrary observer pushforward or a separately imposed Clifford quotient.'}
cp = OUT / 'source-quadratic-clifford-contract.json'; save(cp, contract)
spec = importlib.util.spec_from_file_location('source', source_path)
s = importlib.util.module_from_spec(spec); spec.loader.exec_module(s)
with gzip.open(pres_path, 'rt') as stream: pres = json.load(stream)
for name, digest in pres['inputs'].items():
    assert sha(ROOT / 'research/nima/results' / name) == digest
# Independently verify absence of ideal components of length zero and one.
for start in range(64):
    assert s.rank([s.record(start, (), ())]) == 1
    for e in range(6):
        if not start & (1 << e):
            assert s.rank([s.record(start, (e,), (m,)) for m in (0, 1)]) == 2

def add(*cols):
    out = {}
    for col in cols:
        for p, v in col.items(): out[p] = out.get(p, Q(0)) + v
    return {p: v for p, v in out.items() if v}
partitions = [((0, 1), (2, 3)), ((0, 2), (1, 3)), ((0, 3), (1, 2))]
products = []; symmetric = []
for left, right in partitions:
    x, y = s.relation(left, 0), s.relation(right, 0)
    left_mask = sum(1 << e for e in left)
    right_mask = sum(1 << e for e in right)
    assert not s.rho_column(0, x) and not s.rho_column(left_mask, y)
    assert not s.rho_column(0, y) and not s.rho_column(right_mask, x)
    xy, yx = s.multiply(x, y), s.multiply(y, x)
    assert not s.rho_column(0, xy) and not s.rho_column(0, yx)
    products.append(xy); symmetric.append(add(xy, yx))
assert s.rank(products) == 3
assert s.rank(symmetric) == 3
# Bind each ordered product and reverse order to the actual exported I^2 span.
corner = next(c for c in pres['source_corners'] if c['corner'] == [0, 15])
paths = [(tuple(w), tuple(m)) for w, m in corner['paths']]
free = {paths[p]: i for i, p in enumerate(corner['free_path_indices'])}
def coordinates(col):
    local = {free[p]: v for p, v in col.items() if p in free}
    rebuilt = {}
    for i, v in local.items():
        for p, c in corner['ideal_basis_columns'][i]:
            key = paths[p]; rebuilt[key] = rebuilt.get(key, Q(0)) + v * Q(c)
    assert {p: v for p, v in rebuilt.items() if v} == col
    return {corner['generator_offset'] + i: v for i, v in local.items()}
def normalized(col):
    v = col[min(col)]
    return tuple(sorted((i, c / v) for i, c in col.items()))
J1 = {normalized({i: Q(v) for i, v in col}) for col in pres['J1_I_squared_columns']}
checks = 0
for left, right in partitions:
    for a, b in ((left, right), (right, left)):
        assert normalized(coordinates(s.multiply(s.relation(a, 0), s.relation(b, 0)))) in J1
        checks += 1
# In total typed path algebra x:0->3 and y:3->15 have xy nonzero,
# xx=yx=yy=0. Thus a=x+y satisfies a^2=xy and a^3=0.
def typed_multiply(a, b):
    result = {}
    for (u, v), left in a.items():
        for (w, z), right in b.items():
            if v == w:
                key = (u, z)
                result[key] = add(result.get(key, {}), s.multiply(left, right))
    return {key: col for key, col in result.items() if col}
a = {(0, 3): s.relation((0, 1), 0), (3, 15): s.relation((2, 3), 0)}
a2 = typed_multiply(a, a)
assert a2 == {(0, 15): products[0]}
assert not typed_multiply(a2, a)
report = {'passed': True, 'verdict': 'RANK_ONE_CLIFFORD_LIKE_LAW_REFUTED_IN_SOURCE',
 'contract_sha256': sha(cp),
 'corner': [0, 15], 'I3_on_corner': 'zero by independently checked minimum ideal event length',
 'ordered_product_rank_mod_I3': 3, 'reanchored_symmetric_product_rank_mod_I3': 3,
 'actual_J1_product_bindings_checked': checks,
 'pair_partitions': partitions,
 'symmetric_witnesses': [[{'word': list(w), 'marks': list(m), 'coefficient': str(v)} for (w, m), v in sorted(col.items())] for col in symmetric],
 'typed_square_example': 'For x:0->3 and y:3->15, a=x+y has a^2=xy !=0 and a^3=0. A single off-diagonal homogeneous path element squares to zero.',
 'conclusion': 'I^2/I^3 carries genuinely multidimensional quadratic composition. No single omega spans all tested symmetric products. A vector-valued pairing or an additional justified quotient is required.',
 'scope': 'Reanchored block exchange is explicit and distinct from reversing two fixed typed arrows. No claim that all possible Clifford representations or observer quotients are excluded.'}
save(OUT / 'source-quadratic-clifford.json', report)
print(json.dumps({k: v for k, v in report.items() if k != 'symmetric_witnesses'}, indent=2))
