#!/usr/bin/env python3
"""Verify integral conjugacy of quarter-twisted relative and combined conductor monodromy."""
from hashlib import sha256
from pathlib import Path
import json
import sympy as s
from sympy.matrices.normalforms import smith_normal_form
from sympy.polys.domains import ZZ
ROOT=Path(__file__).resolve().parents[3];PACKET=ROOT/'research/voevodsky/quarter_twisted_relative_residue_matches_combined_but_not_separate_wall_monodromy.md';SOURCE=ROOT/'research/benincasa/primitive-conductor-top-connection.json';RESULT=ROOT/'research/voevodsky/results/relative_combined_wall_monodromy.json';src=json.loads(SOURCE.read_text(encoding='utf-8'));W=s.Matrix([[-1,1,0],[1,0,-1],[0,1,1]]);D=s.diag(-1,-1,1);Mrel=s.simplify(W*D*W.inv());M1=s.Matrix(src['monodromy_recovery']['M1']);M2=s.Matrix(src['monodromy_recovery']['M2']);M12=M1*M2;T=s.Matrix([[0,-1,0],[0,0,1],[1,1,-1]]);Srel=smith_normal_form(Mrel-s.eye(3),domain=ZZ);S12=smith_normal_form(M12-s.eye(3),domain=ZZ);diag=lambda S:[abs(int(S[i,i])) for i in range(3)];checks={'relative_monodromy_integral':all(x.q==1 for x in Mrel),'relative_matrix_exact':Mrel==s.Matrix([[-1,0,0],[1,0,-1],[-1,-1,0]]),'relative_involution':Mrel**2==s.eye(3),'conductor_factors_commute':M1*M2==M2*M1,'combined_exact':M12==s.Matrix([[-1,0,-1],[0,-1,-1],[0,0,1]]),'T_unimodular':abs(T.det())==1,'integral_conjugacy':T*Mrel==M12*T,'relative_minus_identity_smith':diag(Srel)==[1,2,0],'combined_minus_identity_smith':diag(S12)==[1,2,0],'full_conductor_cokernel_source':src['enhanced_intertwiner_J']==[[2,0,1],[0,2,1],[0,0,1]],'separate_wall_gate':'must retain separate monodromy operators before gluing' in PACKET.read_text(encoding='utf-8'),'twist_authority_gate':'quarter-twist exponent still lacks contour authority' in PACKET.read_text(encoding='utf-8')};checks={k:bool(v) for k,v in checks.items()};result={'schema':'marici.voevodsky.relative-combined-wall-monodromy.v1','packet_sha256':sha256(PACKET.read_bytes()).hexdigest(),'conductor_source_sha256':sha256(SOURCE.read_bytes()).hexdigest(),'M_relative':[[int(x) for x in Mrel.row(i)] for i in range(3)],'M_conductor_combined':[[int(x) for x in M12.row(i)] for i in range(3)],'conjugacy_T':[[int(x) for x in T.row(i)] for i in range(3)],'checks':checks,'passed':all(checks.values()),'disposition':{'combined_integral_monodromy':'matched conditionally','independent_wall_parities':'not recovered by product','quarter_twist_authority':'missing'}};RESULT.write_text(json.dumps(result,indent=2)+'\n',encoding='utf-8');print(json.dumps({'passed':result['passed'],'checks':checks,'disposition':result['disposition']}));raise SystemExit(0 if result['passed'] else 1)
