from scanning_set_program import ScanningSetProgram
from offline_replay import contract,digest,replay
from copy import deepcopy
from pathlib import Path
import subprocess,sys,json
class Recorded(ScanningSetProgram):
 def step(self,n):self.before=self.serial;return super().step(n)
 def replace(self,names,edges,new):
  self.certificates.append(deepcopy({'names':names,'edges':edges,'new':new,'before':self.before,'after':self.serial}))
  super().replace(names,edges,new)
net=Recorded((),[('scan',(0,2)),('ifadd',(0,1,2)),('member',1)]);net.certificates=[]
initial=deepcopy({'types':net.types,'wires':net.wires,'serial':net.serial})
penultimate=None
while net.enabled():
 penultimate=deepcopy({'types':net.types,'wires':net.wires,'serial':net.serial})
 net.step(net.enabled()[0])
trace={'schema':'recurrent-trace-v3','declaration':{'bits':[],'program':[['scan',[0,2]],['ifadd',[0,1,2]],['member',1]]},'provenance_status':'unverified-constructor','output_types':net.output_types,'contract_digest':digest(contract()),'initial':initial,'outputs':net.outputs,'steps':net.certificates,'complete':True,'final_digest':digest({'types':net.types,'wires':net.wires,'serial':net.serial}),'provenance':'Generated by production constructor; initial compilation not independently certified.'}
base=Path(__file__).resolve().parents[1];path=base/'results/replay-example.json';path.write_text(json.dumps(trace,indent=2)+'\n')
assert replay(json.loads(path.read_text()))['provenance_status']=='structurally-matched-declaration'
mutants=[]
bad=deepcopy(trace);bad['steps']=bad['steps'][:-1];mutants.append(bad)
bad=deepcopy(trace);bad['contract_digest']='bad';mutants.append(bad)
bad=deepcopy(trace);bad['steps'][0]['before']+=1;mutants.append(bad)
bad=deepcopy(trace);bad['steps'][0]['edges'][0]=('INVALID.p','INVALID.p');mutants.append(bad)
bad=deepcopy(trace);bad['schema']='recurrent-trace-v1';mutants.append(bad)
bad=deepcopy(trace);bad['output_types'][0]='boolean';mutants.append(bad)
bad=deepcopy(trace);bad['complete']='true';mutants.append(bad)
bad=deepcopy(trace);bad['provenance_status']='verified';mutants.append(bad)
# Self-consistent prefix digest must not license a false terminal claim.
prefix=deepcopy(trace);prefix['steps']=prefix['steps'][:-1];prefix['final_digest']=digest(penultimate)
bad=deepcopy(prefix);mutants.append(bad)
prefix['complete']=False;assert replay(prefix)['complete'] is False
bad=deepcopy(trace);bad['declaration']['bits']=[1];mutants.append(bad)
bad=deepcopy(trace);bad['declaration']['program'][0][1][1]=1;mutants.append(bad)
bad=deepcopy(trace);bad['schema']='recurrent-trace-v2';mutants.append(bad)
# A zero-step, declaration-bound empty program is complete.
empty=Recorded((),[])
empty_graph={'types':empty.types,'wires':empty.wires,'serial':empty.serial}
zero=dict(trace,initial=empty_graph,steps=[],outputs=[],output_types=[],declaration={'bits':[],'program':[]},final_digest=digest(empty_graph))
assert replay(zero)['complete']
# Well-formed disconnected garbage with a recomputed digest must still reject.
bad=deepcopy(zero);g=bad['initial'];s=g['serial'];a=f'N_{s+1}';b=f'N_{s+2}'
g['types'].update({a:('p',),b:('p',)});g['wires'].update({a+'.p':b+'.p',b+'.p':a+'.p'});g['serial']+=2
bad['final_digest']=digest(g);mutants.append(bad)
for bad in mutants:
 try:replay(bad)
 except (ValueError,KeyError):pass
 else:raise AssertionError('tamper accepted')
# Separate interpreter, assert no production net implementation was imported.
code="import json,sys; from pathlib import Path; from offline_replay import replay; replay(json.loads(Path(sys.argv[1]).read_text())); assert 'scanning_set_program' not in sys.modules and 'retained_membership' not in sys.modules"
subprocess.run([sys.executable,'-E','-c',code,str(path)],cwd=Path(__file__).resolve().parent,check=True)
report={'passed':True,'replayed_steps':len(trace['steps']),'tampered_histories_rejected':len(mutants),'self_consistent_prefix_checked':True,'separate_process_without_production_reducer':True,'scope':'Portable example with local trusted manifest/signature artifact; initial graph structurally matched to source declarations, not authenticated construction history.'}
(base/'results/offline-replay.json').write_text(json.dumps(report,indent=2)+'\n');print(json.dumps(report))
