"""Formal-concept closure of history/continuation admission, actual 638 states.

Common compatibility uses universal quantification: intents are continuations
admitted by EVERY history in an extent. The finite transformation monoid below
computes exact admission languages, including arbitrarily long words.
"""
from pathlib import Path
from collections import deque
import json
import hashlib
import subprocess
import sys
ROOT = Path(__file__).resolve().parents[3]
N = ROOT / 'research/nima'
OUT = ROOT / 'research/voevodsky/results'
p = N / 'results/actual-source-evidence-coupling.json'
subprocess.run([sys.executable, str(N / 'checkers/verify_source_evidence_coupling.py')], check=True, capture_output=True, text=True)
d = json.loads(p.read_text()); states = d['states']; n = len(states)
labels = [('source', e, m) for e in range(6) for m in (0, 1)] + [('acquire',), ('deliver',), ('issue', 0), ('issue', 1)]
# For joint word admission, rejection ends compatibility. It is not silently
# counted as a successful unchanged-state continuation.
step = []
for s in states:
    edges = {tuple(a): j for a, j in s['transitions']}
    step.append([edges.get(a, -1) for a in labels])
# Enumerate distinct partial transformations generated by accepted words.
identity = tuple(range(n))
words = {identity: ()}; queue = deque([identity])
while queue:
    f = queue.popleft()
    for a in range(len(labels)):
        g = tuple(-1 if x == -1 else step[x][a] for x in f)
        if g not in words:
            words[g] = words[f] + (a,)
            queue.append(g)
        if len(words) > 100000:
            raise RuntimeError('Explicit finite-monoid budget exceeded; no closure claim')
# A relation column is a word's domain; equal domains have identical compatibility.
domains = {}
for f, word in words.items():
    mask = sum(1 << i for i, j in enumerate(f) if j != -1)
    domains.setdefault(mask, word)
full = (1 << n) - 1

def closure(mask):
    result = full
    for domain in domains:
        if mask & ~domain == 0:
            result &= domain
    return result

# Test forward-image descent: cl(A)=cl(B) => cl(eA)=cl(eB), restricting
# to extents all of whose histories admit e. Singleton fibers give exact
# necessary witnesses; arbitrary-subset success is not inferred from them.
single = [closure(1 << i) for i in range(n)]
found = None
for i in range(n):
    for j in range(i + 1, n):
        if single[i] != single[j]:
            continue
        for a in range(len(labels)):
            x, y = step[i][a], step[j][a]
            if x >= 0 and y >= 0 and single[x] != single[y]:
                found = {'histories': [i, j], 'extension': labels[a], 'successors': [x, y]}
                break
        if found: break
    if found: break
# Independent structural theorem: same admitted word language is a right
# congruence because residual language after e is {w : ew was admitted}.
assert found is None
# Stronger closure stability on ALL extents follows from inverse images:
# e^-1(dom(w))=dom(ew). Verify complete domain-family closure under preimage.
preimage_checks = 0
for a in range(len(labels)):
    for domain in domains:
        pre = sum(1 << i for i in range(n) if step[i][a] >= 0 and domain & (1 << step[i][a]))
        assert pre in domains
        preimage_checks += 1
# Candidate exact equality f(cl(A)) closure == closure(f(A)), for A subset dom(e).
# Preimage closure proves inclusion cl(f(cl(A))) subset cl(f(A)); extensivity
# supplies reverse inclusion. cl(A) stays inside dom(e) since dom(e) is a column.
for mask in domains:
    assert closure(mask) == mask
assert closure(closure(0)) == closure(0)
# Record how many history distinctions admission alone retains.
classes = {}
for i, value in enumerate(single):
    classes.setdefault(value, []).append(i)
report = {
    'passed': True,
    'compatibility': 'history state admits the complete continuation word; universal Galois operators',
    'history_states': n,
    'partial_word_transformations': len(words),
    'distinct_compatibility_columns': len(domains),
    'distinct_singleton_closures': len(classes),
    'preimage_closure_checks': preimage_checks,
    'singleton_descent_counterexample': found,
    'general_certificate': 'Every domain column is closed under every source-action preimage, with rejected histories excluded. Therefore for A contained in dom(e), cl(e(cl(A)))=cl(e(A)).',
    'scope': 'Admission-only relation on actual coupled states and all finite words in its 16-label alphabet. Outputs, audit extensions and richer homotopies are not included. Galois duality is definitional; preimage closure certifies forward composition compatibility.',
    'source_sha256': hashlib.sha256(p.read_bytes()).hexdigest(),
}
(OUT / 'reciprocal-history-closure.json').write_text(json.dumps(report, indent=2) + '\n')
print(json.dumps(report, indent=2))
