#!/usr/bin/env python3
"""Verify transported site exchange on the full extended target."""
from hashlib import sha256
from pathlib import Path
import json
import sympy as s
ROOT=Path(__file__).resolve().parents[3];PACKET=ROOT/'research/voevodsky/full_extended_target_restores_site_exchange_but_mixes_routes_with_support.md';RESULT=ROOT/'research/voevodsky/results/full_extended_target_site_exchange.json';INC=ROOT/'research/benincasa/enhanced-conductor-unimodular-gluing.json';TARGET=ROOT/'research/aspect/contracts/relative-cech-de-rham-interferometer.v1.json'
a=json.loads(INC.read_text(encoding='utf-8'));b=json.loads(TARGET.read_text(encoding='utf-8'));Phi=s.Matrix(a['Phi_exc']);D=s.Matrix(b['residue_map']);r=D[:,0];q1=Phi[:,0];q2=Phi[:,2];Dext=s.Matrix.hstack(D,q1,q2);P=s.Matrix([[0,0,0,1],[0,1,0,0],[1,0,0,-1],[0,0,1,-1]]);T=s.Matrix([[1,0,0,0],[0,0,1,0],[0,1,0,0],[0,0,0,1]]);S=s.Matrix([[0,1,0],[1,0,0],[0,0,1]]);A=P*T*P.inv();route=s.Matrix.hstack(s.eye(4)[:,0],s.eye(4)[:,1]);cycle=s.Matrix([1,1,0,0]);checks={'P_unimodular':P.det()==1,'transport_exact':A==s.Matrix([[1,0,0,0],[1,0,0,1],[0,0,1,0],[-1,1,0,0]]),'A_integral':all(v.q==1 for v in A),'A_involution':A*A==s.eye(4),'ambient_equivariance':A*P==P*T,'differential_equivariance':Dext*A==S*Dext,'route_subspace_not_invariant':any((A*route)[i,j]!=0 for i in (2,3) for j in range(2)),'closed_cycle_fixed':A*cycle==cycle,'cycle_closed':Dext*cycle==s.zeros(3,1),'support_interpretation_unverified':'analogy remains unverified' in PACKET.read_text(encoding='utf-8')};checks={k:bool(v) for k,v in checks.items()}
result={'schema':'marici.voevodsky.full-extended-target-site-exchange.v1','packet_sha256':sha256(PACKET.read_bytes()).hexdigest(),'source_digests':{'incidence':sha256(INC.read_bytes()).hexdigest(),'aspect':sha256(TARGET.read_bytes()).hexdigest()},'transported_action':[list(map(int,A.row(i))) for i in range(4)],'checks':checks,'passed':all(checks.values()),'disposition':{'full_extended_target':'site-exchange equivariant','original_route_span':'not invariant','closed_two_leg_cycle':'fixed','physical_support_typing':'unverified'}}
RESULT.write_text(json.dumps(result,indent=2)+'\n',encoding='utf-8');print(json.dumps({'passed':result['passed'],'action':result['transported_action'],'checks':checks,'disposition':result['disposition']}));raise SystemExit(0 if result['passed'] else 1)
