#!/usr/bin/env python3
"""Construct the local Legendre thimble algebra and prove ambient parity underdetermination."""
from hashlib import sha256
from itertools import product
from pathlib import Path
import json
import sympy as s
from sympy.matrices.normalforms import smith_normal_form
from sympy.polys.domains import ZZ
ROOT=Path(__file__).resolve().parents[3];PACKET=ROOT/'research/voevodsky/local_integral_legendre_thimble_does_not_select_the_ambient_two_bit_lift.md';MONO=ROOT/'research/benincasa/results/total-energy-legendre-integral-monodromy.json';GYSIN=ROOT/'research/benincasa/results/integral-del-pezzo2-gysin-lattice.json';CUT=ROOT/'src/ledger/20260821-1751 The Physical Cut Pairing Does Not Resolve the Integral Cusp Extension.md';RESULT=ROOT/'research/voevodsky/results/local_legendre_thimble_and_ambient_parity.json';src=json.loads(MONO.read_text(encoding='utf-8'));gysin=json.loads(GYSIN.read_text(encoding='utf-8'));T=s.Matrix(src['integral_monodromy']);N=T-s.eye(2);delta=s.Matrix([1,0]);beta=s.Matrix([0,1]);candidates=[]
for a,b in product((0,1),repeat=2):
 P=s.Matrix([[-a,-b,2]]);S=smith_normal_form(P,domain=ZZ);content=s.gcd_list([a,b,2]);candidates.append({'parity':[a,b],'relation':[-a,-b,2],'relation_content':int(content),'group': 'Z^2 plus Z/2' if content==2 else 'Z^2','extension_class_distinct_by_labels':True})
text=PACKET.read_text(encoding='utf-8');cut=CUT.read_text(encoding='utf-8');checks={'source_monodromy':T==s.Matrix([[1,2],[0,1]]),'vanishing_cycle_fixed':T*delta==delta,'transverse_cycle_shift':T*beta==beta+2*delta,'nilpotent_image_twice_delta':N*beta==2*delta and N*delta==s.zeros(2,1),'coinvariant_smith':[abs(int(smith_normal_form(N,domain=ZZ)[i,i])) for i in range(2)]==[2,0],'four_labelled_classes':len(candidates)==4 and len({tuple(c['parity']) for c in candidates})==4,'split_class_has_torsion':candidates[0]['group']=='Z^2 plus Z/2','three_nonsplit_groups_free':all(c['group']=='Z^2' for c in candidates[1:]),'primitive_gysin_kernel':gysin['algebraic_quotient_torsion']==[] and gysin['algebraic_kernel_rank']==7,'physical_cut_zero':'is zero' in cut,'local_thimble_constructed':'local Lefschetz thimble' in text,'ambient_parity_refused':'requested ambient parity remains underdetermined' in text,'missing_chain_exact':'integral del Pezzo thimble embedding is absent' in text};checks={k:bool(v) for k,v in checks.items()};result={'schema':'marici.voevodsky.local-legendre-thimble-ambient-parity.v1','packet_sha256':sha256(PACKET.read_bytes()).hexdigest(),'monodromy_sha256':sha256(MONO.read_bytes()).hexdigest(),'gysin_sha256':sha256(GYSIN.read_bytes()).hexdigest(),'cut_entry_sha256':sha256(CUT.read_bytes()).hexdigest(),'local_thimble':{'boundary':'delta','intersection_delta_beta':1,'monodromy':'beta -> beta + 2 delta','coinvariants':'Z[beta] plus Z/2[delta]'},'ambient_candidates':candidates,'checks':checks,'passed':all(checks.values()),'disposition':{'local_integral_thimble':'constructed','elliptic_torsion_generator':'constructed','twice_ambient_lift_parity':'underdetermined among four classes','missing':'integral del Pezzo relative thimble and two intersection pairings'}};RESULT.write_text(json.dumps(result,indent=2)+'\n',encoding='utf-8');print(json.dumps({'passed':result['passed'],'checks':checks,'disposition':result['disposition']}));raise SystemExit(0 if result['passed'] else 1)
