#!/usr/bin/env python3
"""Check the source-backed typing and stop conditions of the RH mate cell."""
import hashlib,json,platform
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];FIX=ROOT/'research/voevodsky/fixtures/rh_forward_backward_beck_chevalley_mate_cell.v1.json';OUT=ROOT/'research/voevodsky/results/rh_forward_backward_beck_chevalley_mate_cell.json';D=json.loads(FIX.read_text());texts={p:(ROOT/p).read_text(encoding='utf-8') for p in D['sources']}
arch=texts[D['sources'][0]];nogo=texts[D['sources'][1]];pdf=texts[D['sources'][2]]
checks={'three_plus_two_plus_one_source':['Three primary state towers','Two directed witness towers','One mate and equalizer coherence tower'] and all(x in arch for x in ['Three primary state towers','Two directed witness towers','One mate and equalizer coherence tower']),'mate_equation_source':'W_X(c)=B_{X,s}(y)' in arch,'forward_status_source':'forward witness   global Tate and Poisson construction established' in arch,'backward_partial_source':'backward witness  only the zero-to-two-endpoint state bridge is established' in arch,'finite_reordering_residual_source':'\\mathfrak A_X=P_XF(I-P_X)' in nogo and '\\operatorname{rank}\\mathfrak A_X=1' in nogo,'completion_order_exact':D['completion_order']==['global restricted-product source','completed rigged boundary correspondence','finite diagnostic projection','controlled realization'],'pdf_correspondence_clue':'Beck--Chevalley' in pdf and 'anti-involution' in pdf,'mate_not_conflated_with_boundary_sewing':D['disposition']['candidate_for_previous_Xi_W'].endswith('not reciprocal boundary sewing W'),'backward_map_gate_retained':'backward boundary-defect map' in D['disposition']['first_missing_typed_datum'],'no_false_completion':D['disposition']['current_status']=='blocked'}
out={'schema':'marici.voevodsky.rh-forward-backward-beck-chevalley-mate-cell-check.v1','passed':all(checks.values()),'checks':checks,'disposition':'The source-backed candidate top cell is the cutoff-natural completed family of forward-Ward/backward-Green mates. Reciprocal boundary sewing is a lower internal transport. The backward defect map remains absent.','claim_boundary':D['claim_boundary'],'execution_receipt':{'command':'python research/voevodsky/checkers/check_rh_forward_backward_beck_chevalley_mate_cell.py','python':platform.python_version(),'fixture_sha256':hashlib.sha256(FIX.read_bytes()).hexdigest(),'source_sha256':{p:hashlib.sha256((ROOT/p).read_bytes()).hexdigest() for p in D['sources']},'checker_sha256':hashlib.sha256(Path(__file__).read_bytes()).hexdigest()}}
OUT.parent.mkdir(parents=True,exist_ok=True);OUT.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n');print(json.dumps(out,indent=2,sort_keys=True));raise SystemExit(0 if out['passed'] else 1)
