#!/usr/bin/env python3
"""Exact rank/kernel audit for the valuation value-plus-log-jet observer."""
import hashlib,json,platform
from fractions import Fraction as Q
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];FIX=ROOT/'research/voevodsky/fixtures/valuation_boundary_log_jet_rank_audit.v1.json';OUT=ROOT/'research/voevodsky/results/valuation_boundary_log_jet_rank_audit.json';D=json.loads(FIX.read_text());N=D['depth'];J=[[Q(1) for _ in range(N+1)],[Q(k) for k in range(N+1)]];kernel=[[Q(1),Q(-2),Q(1),Q(0)],[Q(2),Q(-3),Q(0),Q(1)]]
def mv(a,v):return [sum(a[i][k]*v[k] for k in range(len(v))) for i in range(len(a))]
def rank2(a):return 2 if any(a[0][i]*a[1][j]-a[0][j]*a[1][i] for i in range(len(a[0])) for j in range(i+1,len(a[0]))) else 1
checks={'jet_matrix_is_mass_and_first_moment':J==[[1,1,1,1],[0,1,2,3]],'jet_rank_two':rank2(J)==D['expected']['jet_rank'],'kernel_dimension_two_by_rank_nullity':len(J[0])-rank2(J)==D['expected']['kernel_dimension'],'first_kernel_witness_invisible':mv(J,kernel[0])==[0,0],'second_kernel_witness_invisible':mv(J,kernel[1])==[0,0],'kernel_witnesses_independent':kernel[0]!=kernel[1] and kernel[0][2]!=0 and kernel[1][2]==0,'terminal_detected_but_not_separated':mv(J,[0,0,0,1])==[1,3],'full_register_retained':D['disposition']['policy'].startswith('retain the full atomic')}
out={'schema':'marici.voevodsky.valuation-boundary-log-jet-rank-audit-check.v1','passed':all(checks.values()),'checks':checks,'computed':{'jet_matrix':[[str(x) for x in row] for row in J],'rank':rank2(J),'kernel_dimension':len(J[0])-rank2(J),'kernel_witnesses':[[str(x) for x in v] for v in kernel],'jet_of_terminal':['1','3']},'disposition':'The logarithmic jet is a useful mass-and-first-moment observer but has a two-dimensional kernel at depth three. It cannot replace the cutoff-natural atomic valuation register used by the Green-Ward mate.','claim_boundary':D['claim_boundary'],'execution_receipt':{'command':'python research/voevodsky/checkers/check_valuation_boundary_log_jet_rank_audit.py','python':platform.python_version(),'fixture_sha256':hashlib.sha256(FIX.read_bytes()).hexdigest(),'source_sha256':{p:hashlib.sha256((ROOT/p).read_bytes()).hexdigest() for p in D['sources']},'checker_sha256':hashlib.sha256(Path(__file__).read_bytes()).hexdigest()}}
OUT.parent.mkdir(parents=True,exist_ok=True);OUT.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n');print(json.dumps(out,indent=2,sort_keys=True));raise SystemExit(0 if out['passed'] else 1)
