#!/usr/bin/env python3
"""Compute homology and cone defect of the completed target chain map."""
from hashlib import sha256
from itertools import combinations
from pathlib import Path
import json
import sympy as s
from sympy.matrices.normalforms import smith_normal_form
from sympy.polys.domains import ZZ
ROOT=Path(__file__).resolve().parents[3];PACKET=ROOT/'research/voevodsky/completed_target_is_rationally_equivalent_but_has_integral_two_torsion_defect.md';RESULT=ROOT/'research/voevodsky/results/completed_target_integral_defect.json';INC=ROOT/'research/benincasa/enhanced-conductor-unimodular-gluing.json';INTER=ROOT/'research/benincasa/orientation-twisted-conductor-rees-intertwiner.json';TARGET=ROOT/'research/aspect/contracts/relative-cech-de-rham-interferometer.v1.json'
g=json.loads(INC.read_text(encoding='utf-8'));a=json.loads(INTER.read_text(encoding='utf-8'));b=json.loads(TARGET.read_text(encoding='utf-8'));K=s.Matrix(g['K']);J=s.Matrix(g['J']);Phi=s.Matrix(g['Phi_exc']);D=s.Matrix(b['residue_map']);Dext=s.Matrix.hstack(D,Phi[:,0],Phi[:,2]);P=s.Matrix([[0,0,0,1],[0,1,0,0],[1,0,0,-1],[0,0,1,-1]]);d2=P.col_join(-K);d1=Dext.row_join(J);SJ=smith_normal_form(J,domain=ZZ);SD=smith_normal_form(Dext,domain=ZZ);zA=s.ones(4,1);zB=s.Matrix([1,1,0,0]);checks={'chain_square':Dext*P==J*K,'P_unimodular':P.det()==1,'J_smith_122':[abs(int(SJ[i,i])) for i in range(3)]==[1,2,2],'target_smith_122':[abs(int(SD[i,i])) for i in range(3)]==[1,2,2],'source_h1_generator':K*zA==s.zeros(3,1) and len(K.nullspace())==1,'target_h1_generator':Dext*zB==s.zeros(3,1) and len(Dext.nullspace())==1 and P*zA==zB,'source_H0_zero':K.rank()==3 and any(abs(int(K[:,c].det()))==1 for c in combinations(range(4),3)),'cone_square':d1*d2==s.zeros(3,4),'cone_H2_zero':d2.rank()==4,'cone_H1_rational_zero':d1.nullspace().__len__()==4 and d2.rank()==4,'cone_H1_integral_zero_from_unimodular_P':P.det() in (-1,1) and J.det()!=0,'cone_H0_smith_122':[abs(int(x)) for x in [smith_normal_form(d1,domain=ZZ)[i,i] for i in range(3)]]==[1,2,2],'period_gate_retained':'real or complex period pairing cannot by itself detect' in PACKET.read_text(encoding='utf-8')};checks={k:bool(v) for k,v in checks.items()}
result={'schema':'marici.voevodsky.completed-target-integral-defect.v1','packet_sha256':sha256(PACKET.read_bytes()).hexdigest(),'source_digests':{'incidence':sha256(INC.read_bytes()).hexdigest(),'intertwiner':sha256(INTER.read_bytes()).hexdigest(),'aspect':sha256(TARGET.read_bytes()).hexdigest()},'source_homology':{'H1':'Z','H0':'0'},'target_homology':{'H1':'Z','H0':'(Z/2)^2'},'cone_homology':{'H2':'0','H1':'0','H0':'(Z/2)^2'},'checks':checks,'passed':all(checks.values()),'disposition':{'characteristic_zero':'chain equivalence','odd_primes':'chain equivalence','prime_two':'degree-zero saturation defect','physical_status':'unverified'}}
RESULT.write_text(json.dumps(result,indent=2)+'\n',encoding='utf-8');print(json.dumps({'passed':result['passed'],'checks':checks,'homology':{'source':result['source_homology'],'target':result['target_homology'],'cone':result['cone_homology']},'disposition':result['disposition']}));raise SystemExit(0 if result['passed'] else 1)
