#!/usr/bin/env python3
"""Verify the Geiser Picard action and its mod-two triviality on the E7 kernel."""
from hashlib import sha256
from pathlib import Path
import json
import sympy as s
R=Path(__file__).resolve().parents[3];P=R/'research/voevodsky/the_geiser_involution_is_mod_two_trivial_on_the_algebraic_kernel.md';GYS=R/'research/benincasa/results/integral-del-pezzo2-gysin-lattice.json';SITE=R/'research/voevodsky/results/visible_site_exchange_parity_action.json';OUT=R/'research/voevodsky/results/geiser_mod_two_action.json';Q=s.diag(1,*([-1]*7));K=s.Matrix([-3]+[1]*7);I=s.eye(8);G=K*(K.T*Q)-I;roots=[];roots.append(s.Matrix([1,-1,-1,-1,0,0,0,0]))
for i in range(1,7):
 v=s.zeros(8,1);v[i]=1;v[i+1]=-1;roots.append(v)
A=s.Matrix.hstack(*roots);gys=json.loads(GYS.read_text());site=json.loads(SITE.read_text());text=P.read_text();checks={'canonical_square_two':int((K.T*Q*K)[0])==2,'geiser_involution':G*G==I,'geiser_isometry':G.T*Q*G==Q,'canonical_fixed':G*K==K,'root_basis_rank_seven':A.rank()==7,'roots_perpendicular':K.T*Q*A==s.zeros(1,7),'minus_identity_on_roots':G*A==-A,'mod_two_identity_on_kernel':all(int(x)%2==0 for x in G*A-A),'gysin_kernel_rank_seven':gys['algebraic_kernel_rank']==7,'prior_site_action_identity':site['disposition']['visible_site_exchange_on_parity']=='identity','quartic_identification_missing':'has not been identified with the Geiser deck coordinate' in text,'selector_scope':'If that identification were established' in text};checks={k:bool(v) for k,v in checks.items()};result={'schema':'marici.voevodsky.geiser-mod-two-action.v1','packet_sha256':sha256(P.read_bytes()).hexdigest(),'gysin_source_sha256':sha256(GYS.read_bytes()).hexdigest(),'site_exchange_sha256':sha256(SITE.read_bytes()).hexdigest(),'canonical_class':list(map(int,K)),'picard_action':[[int(x) for x in G.row(i)] for i in range(8)],'checks':checks,'passed':all(checks.values()),'disposition':{'Geiser_on_E7_integrally':'minus identity','Geiser_on_E7_mod2':'identity','parity_selector':'fails','remaining_identification':'surface lift of quartic t -> -t'}};OUT.write_text(json.dumps(result,indent=2)+'\n');print(json.dumps({'passed':result['passed'],'checks':checks,'disposition':result['disposition']}));raise SystemExit(0 if result['passed'] else 1)
