#!/usr/bin/env python3
"""Verify number-conserving dual-rail encoding, exchange, and X/Y/Z tomography."""
from hashlib import sha256
from itertools import product
from pathlib import Path
import json
import sympy as s
ROOT=Path(__file__).resolve().parents[3];PACKET=ROOT/'research/voevodsky/dual_rail_encoder_exposes_coherent_null_sector_leakage.md';MIX=ROOT/'research/voevodsky/results/codeword_mixture_identifiability.json';RESULT=ROOT/'research/voevodsky/results/dual_rail_coherence_probe.json';I=s.eye(2);X=s.Matrix([[0,1],[1,0]]);Y=s.Matrix([[0,-s.I],[s.I,0]]);Z=s.diag(1,-1);H=s.Matrix([[1,1],[1,-1]])/s.sqrt(2);P=s.diag(1,s.I);logical=list(product((0,1),repeat=2));code={str((a,b)):[1-a,a,1-b,b] for a,b in logical};Swap=s.zeros(4)
for j,(a,b) in enumerate(logical):Swap[logical.index((b,a)),j]=1
X1=s.kronecker_product(X,I);X2=s.kronecker_product(I,X);Y1=s.kronecker_product(Y,I);Y2=s.kronecker_product(I,Y);Z1=s.kronecker_product(Z,I);Z2=s.kronecker_product(I,Z);text=PACKET.read_text(encoding='utf-8');mix=json.loads(MIX.read_text(encoding='utf-8'));checks={'four_distinct_codewords':len({tuple(v) for v in code.values()})==4,'fixed_total_number':all(sum(v)==2 for v in code.values()),'one_per_pair':all(sum(v[:2])==1 and sum(v[2:])==1 for v in code.values()),'logical_pauli_relations':X*Y==s.I*Z and Y*Z==s.I*X and Z*X==s.I*Y,'balanced_beamsplitter_diagonalizes_X':s.simplify(H*X*H)==Z,'phase_plus_beamsplitter_accesses_Y':s.simplify(P*X*P.conjugate().T)==Y,'site_swap_involution':Swap*Swap==s.eye(4),'site_swap_observables':Swap*X1*Swap==X2 and Swap*Y1*Swap==Y2 and Swap*Z1*Swap==Z2,'null_not_vacuum':code[str((0,0))]==[1,0,1,0],'prior_diagonal_limitation':mix['disposition']['coherent_superposition']=='not identifiable by count POVM','setting_distinction':'supplies the missing complementary settings rather than extracting phase from diagonal counts alone' in text,'physical_gate':'Physical promotion requires preparation of one photon in each rail pair' in text};checks={k:bool(v) for k,v in checks.items()};result={'schema':'marici.voevodsky.dual-rail-coherence-probe.v1','packet_sha256':sha256(PACKET.read_bytes()).hexdigest(),'mixture_result_sha256':sha256(MIX.read_bytes()).hexdigest(),'codewords':code,'logical_settings':['Z: direct rail counts','X: balanced beam splitter then counts','Y: pi/2 relative phase then balanced beam splitter then counts'],'checks':checks,'passed':all(checks.values()),'disposition':{'number_conserving_encoder':'constructed','site_exchange':'verified','coherence_tomography':'constructed in separate settings','physical_preparation_and_calibration':'missing'}};RESULT.write_text(json.dumps(result,indent=2)+'\n',encoding='utf-8');print(json.dumps({'passed':result['passed'],'checks':checks,'disposition':result['disposition']}));raise SystemExit(0 if result['passed'] else 1)
