#!/usr/bin/env python3
"""Falsify natural site-exchange equivariance of the selected support pair."""
from hashlib import sha256
from pathlib import Path
import json
import sympy as s
ROOT=Path(__file__).resolve().parents[3];PACKET=ROOT/'research/voevodsky/natural_site_exchange_falsifies_the_selected_support_identification.md';RESULT=ROOT/'research/voevodsky/results/natural_site_exchange_support_falsifier.json';GLUE=ROOT/'research/benincasa/enhanced-conductor-unimodular-gluing.json';INTER=ROOT/'research/benincasa/orientation-twisted-conductor-rees-intertwiner.json';MONO=ROOT/'research/benincasa/two-wall-conductor-monodromy.json'
g=json.loads(GLUE.read_text(encoding='utf-8'));a=json.loads(INTER.read_text(encoding='utf-8'));m=json.loads(MONO.read_text(encoding='utf-8'));Phi=s.Matrix(g['Phi_exc']);J=s.Matrix(g['J']);De=s.diag(*a['enhanced_character_action']['epsilon_flip']);M1=s.Matrix(m['root_swap_1']['matrix_columns_in_basis']).T;S=s.Matrix([[0,1,0],[1,0,0],[0,0,1]]);selected={tuple(Phi[:,0]),tuple(Phi[:,2])};site_image={tuple(S*Phi[:,0]),tuple(S*Phi[:,2])};expected={tuple(Phi[:,0]),tuple(Phi[:,1])};checks={'epsilon_intertwines_root_swap_1':De*J==J*(-M1),'natural_site_column_action':S*Phi[:,0]==Phi[:,0] and S*Phi[:,1]==Phi[:,2] and S*Phi[:,2]==Phi[:,1] and S*Phi[:,3]==Phi[:,3],'selected_pair_not_invariant':site_image!=selected,'selected_pair_site_image_exact':site_image==expected,'relative_pair_setwise_invariant_by_source_description':'active support pair is invariant as a set' in PACKET.read_text(encoding='utf-8'),'natural_identification_rejected':'natural equivariant identification is rejected' in PACKET.read_text(encoding='utf-8'),'conditional_result_not_erased':'retained only as a formal result under an unsupported transport hypothesis' in PACKET.read_text(encoding='utf-8')};checks={k:bool(v) for k,v in checks.items()}
result={'schema':'marici.voevodsky.natural-site-exchange-support-falsifier.v1','packet_sha256':sha256(PACKET.read_bytes()).hexdigest(),'source_digests':{'gluing':sha256(GLUE.read_bytes()).hexdigest(),'intertwiner':sha256(INTER.read_bytes()).hexdigest(),'monodromy':sha256(MONO.read_bytes()).hexdigest()},'selected_pair':['Phi_++','Phi_-+'],'natural_site_image':['Phi_++','Phi_+-'],'checks':checks,'passed':all(checks.values()),'disposition':{'natural_equivariant_identification':'rejected','conditional_epsilon_identification':'unsupported transport hypothesis','algebraic_completion':'unchanged','physical_status':'unverified'}}
RESULT.write_text(json.dumps(result,indent=2)+'\n',encoding='utf-8');print(json.dumps({'passed':result['passed'],'checks':checks,'disposition':result['disposition']}));raise SystemExit(0 if result['passed'] else 1)
