#!/usr/bin/env python3
"""Exact construction of the common carrier generated by positive mesh charges."""
import json
from fractions import Fraction
from pathlib import Path

def inner(v,w):return sum(a*b for a,b in zip(v,w))
def main():
 weights=[Fraction(1),Fraction(2),Fraction(3),Fraction(5)]
 regions={'P':[0,1,3],'Q':[1,2],'R':[0,2,3]}
 vec={name:[(weights[i] if i in cells else 0) for i in range(4)] for name,cells in regions.items()}
 # Use coordinates sqrt(weight) formally: inner equals sum weights on intersections.
 gram={}
 for a,A in regions.items():
  for b,B in regions.items():gram[f'{a},{b}']=sum(weights[i] for i in set(A)&set(B))
 G=[[gram[f'{a},{b}'] for b in regions] for a in regions]
 minors2=[]
 names=list(regions)
 for i in range(3):
  for j in range(i+1,3):minors2.append(G[i][i]*G[j][j]-G[i][j]**2)
 assert all(x>=0 for x in minors2)
 # determinant
 det=G[0][0]*(G[1][1]*G[2][2]-G[1][2]**2)-G[0][1]*(G[1][0]*G[2][2]-G[1][2]*G[2][0])+G[0][2]*(G[1][0]*G[2][1]-G[1][1]*G[2][0]);assert det>=0
 result={'schema':'marici.voevodsky.positive-mesh-charge-common-carrier.v1','cell_weights':[str(x) for x in weights],'regions':regions,'carrier':'l2(cells,c), with Phi(D)_alpha=sqrt(c_alpha) 1_(alpha in D)','pairing':'<Phi(D),Phi(E)>=charge(D intersection E)','gram':[[str(x) for x in row] for row in G],'rank_two_determinants':[str(x) for x in minors2],'full_determinant':str(det),'positive':True,'source_scope':'This follows from positive additive kinematic mesh charge.','rh_boundary':'A separate source map must identify RH prime and prime-prime readings with region charges and overlaps; the signed endpoint-gamma-prime formula does not provide that identification automatically.'}
 out=Path(__file__).parents[1]/'results'/'positive_mesh_charge_common_carrier.json';out.write_text(json.dumps(result,indent=2)+'\n');print(json.dumps(result,indent=2))
if __name__=='__main__':main()
