#!/usr/bin/env python3
"""Exact endpoint classification for expanding and contracting valuation charts."""
import hashlib,json,platform
from fractions import Fraction as Q
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];FIX=ROOT/'research/voevodsky/fixtures/valuation_endpoint_irregular_chart_audit.v1.json';OUT=ROOT/'research/voevodsky/results/valuation_endpoint_irregular_chart_audit.json';D=json.loads(FIX.read_text());N=12
expanding=[2**k for k in range(N+1)];contracting=[Q(1,2)**k for k in range(N+1)];irregular_finite={Q(-1),Q(0)}
checks={'expanding_primitive_is_one':expanding[0]==1,'contracting_primitive_is_one':contracting[0]==1,'one_is_regular':Q(1) not in irregular_finite,'expanding_terminal_escapes_toward_infinity':all(expanding[k+1]>expanding[k] for k in range(N)) and expanding[-1]>1000,'contracting_terminal_converges_toward_zero':all(contracting[k+1]<contracting[k] for k in range(N)) and contracting[-1]<Q(1,1000),'neither_source_chart_makes_primitive_irregular':expanding[0] not in irregular_finite and contracting[0] not in irregular_finite,'affine_shift_would_change_primitive_locus':expanding[0]-1==0,'affine_shift_not_authorized':'no admitted source' in D['unsupported_shift'],'fourier_asymptotic_routing_retained':len(D['asymptotic_routing'])==3,'previous_candidate_withdrawn':D['disposition']['previous_two_irregular_slot_candidate']=='not source-derived'}
out={'schema':'marici.voevodsky.valuation-endpoint-irregular-chart-audit-check.v1','passed':all(checks.values()),'checks':checks,'computed':{'expanding_prefix':expanding[:5],'contracting_prefix':[str(x) for x in contracting[:5]],'depth_12_expanding':expanding[-1],'depth_12_contracting':str(contracting[-1]),'primitive_projective_locus':'1 (regular)','possible_terminal_completion_loci':['infinity','0']},'disposition':'The primitive Green endpoint is regular at coordinate one in both admitted valuation charts; only the completion end approaches an irregular locus. Mapping both endpoints to one split irregular germ is unsupported until a base-coordinate chart is sourced.','claim_boundary':D['claim_boundary'],'execution_receipt':{'command':'python research/voevodsky/checkers/check_valuation_endpoint_irregular_chart_audit.py','python':platform.python_version(),'fixture_sha256':hashlib.sha256(FIX.read_bytes()).hexdigest(),'source_sha256':hashlib.sha256((ROOT/D['sources'][0]).read_bytes()).hexdigest(),'pdf_sha256':hashlib.sha256((ROOT/D['sources'][1]).read_bytes()).hexdigest(),'checker_sha256':hashlib.sha256(Path(__file__).read_bytes()).hexdigest()}}
OUT.parent.mkdir(parents=True,exist_ok=True);OUT.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n');print(json.dumps(out,indent=2,sort_keys=True));raise SystemExit(0 if out['passed'] else 1)
