#!/usr/bin/env python3
"""Verify two wall-labelled relative lifts with a shared equal-order special fiber."""
from hashlib import sha256
from pathlib import Path
import json
import sympy as s
ROOT=Path(__file__).resolve().parents[3];PACKET=ROOT/'research/voevodsky/two_wall_labelled_kummer_lifts_share_the_equal_order_special_fiber.md';SPLIT=ROOT/'research/voevodsky/results/conductor_normal_kummer_split.json';RESIDUE=ROOT/'research/voevodsky/results/equal_order_residue_eigenlattice.json';RESULT=ROOT/'research/voevodsky/results/two_wall_labelled_kummer_lifts.json';E=s.symbols('E');Y1=s.Function('Y1')(E);Y2=s.Function('Y2')(E)
def lift(Y):
 X1=Y+E;X2=-Y+E
 return {'Y':Y,'X1':X1,'X2':X2,'B':s.expand(X1-Y),'C':s.expand(X2+Y),'Etot':s.expand(X1+X2),'A':s.expand(X1+Y),'D':s.expand(X2-Y)}
L1,L2=lift(Y1),lift(Y2);Y0=s.symbols('Y0',nonzero=True);special=lambda z,Y:s.simplify(z.subs({E:0,Y:Y0}));split=json.loads(SPLIT.read_text(encoding='utf-8'));res=json.loads(RESIDUE.read_text(encoding='utf-8'));checks={'wall1_equal_order':[L1[k] for k in ('B','C','Etot')]==[E,E,2*E],'wall2_equal_order':[L2[k] for k in ('B','C','Etot')]==[E,E,2*E],'independent_of_root_jet':all(not z.has(s.diff(Y1,E)) and not z.has(s.diff(Y2,E)) for z in [L1['B'],L1['C'],L1['Etot'],L2['B'],L2['C'],L2['Etot']]),'common_special_fiber':special(L1['X1'],Y1)==Y0 and special(L1['X2'],Y1)==-Y0 and special(L2['X1'],Y2)==Y0 and special(L2['X2'],Y2)==-Y0,'complements_nonzero_at_fiber':special(L1['A'],Y1)==2*Y0 and special(L1['D'],Y1)==-2*Y0,'split_jet_preserved':split['oriented_root_difference_at_E0']=='2*x - 2*y','residue_index_two':res['eigenbasis_determinant']==-2,'site_exchange_stated':'site exchange swaps' in PACKET.read_text(encoding='utf-8'),'contour_gate':'nearby-cycle and contour realization' in PACKET.read_text(encoding='utf-8')};checks={k:bool(v) for k,v in checks.items()};result={'schema':'marici.voevodsky.two-wall-labelled-kummer-lifts.v1','packet_sha256':sha256(PACKET.read_bytes()).hexdigest(),'split_result_sha256':sha256(SPLIT.read_bytes()).hexdigest(),'residue_result_sha256':sha256(RESIDUE.read_bytes()).hexdigest(),'maps':{'Phi1':{'Y':'Y1(E)','X1':'Y1(E)+E','X2':'-Y1(E)+E'},'Phi2':{'Y':'Y2(E)','X1':'Y2(E)+E','X2':'-Y2(E)+E'}},'common_pullback':{'B':'E','C':'E','Erel':'2E'},'checks':checks,'passed':all(checks.values()),'disposition':{'wall_parameter_lifts':'constructed','common_special_fiber':'verified','equal_normal_residue':'verified','nearby_cycle_contour_pairing':'missing'}};RESULT.write_text(json.dumps(result,indent=2)+'\n',encoding='utf-8');print(json.dumps({'passed':result['passed'],'checks':checks,'disposition':result['disposition']}));raise SystemExit(0 if result['passed'] else 1)
