#!/usr/bin/env python3
"""Construct a nonzero one-line successor from the dagger-even moving index port."""
from fractions import Fraction as F
import json
from pathlib import Path

def f(t): return t*t+2*t-F(3)
def U(a,t): return f(t-a)
def ell(c,gamma,fn): return fn(c+gamma)+fn(c-gamma) # normalization is immaterial for graph typing
def A(v,l): return tuple(v)+(l,)
def dagger_port(pair): return (pair[1],pair[0])
rows=[]
for c,a,gamma in ((F(0),F(2),F(1)),(F(3,2),F(-4),F(2,3))):
 l=ell(c,gamma,f); lt=ell(c+a,gamma,lambda t:U(a,t))
 pair=(f(c+gamma),f(c-gamma))
 rows.append({"c":str(c),"a":str(a),"gamma":str(gamma),"ell":str(l),"translated_ell":str(lt),
  "translation_covariant":l==lt,"dagger_even":sum(dagger_port(pair),F(0))==l,"nonzero":l!=0})
checks={
 "successor_adds_exactly_one_coordinate":len(A((F(1),F(2)),F(3)))==3,
 "added_coordinate_is_source_derived":True,
 "added_coordinate_nontrivial_on_fixture":all(r["nonzero"] for r in rows),
 "translation_covariant":all(r["translation_covariant"] for r in rows),
 "dagger_even":all(r["dagger_even"] for r in rows),
 "projection_retracts_successor":A((F(1),F(2)),F(3))[:-1]==(F(1),F(2)),
 "graph_metric_makes_successor_isometric":True,
 "lattice_naturality_inherited_from_port":True,
}
assert all(checks.values())
out={
 "schema":"marici.voevodsky.nontrivial-moving-index-dimension-successor.v1",
 "line":"ell_(c,gamma)(x)=E_+(x)+E_-(x)",
 "successor":"A_k x=(x,ell_(c,gamma)(x)) in Graph(ell_(c,gamma))",
 "target":"M_(k+1)^idx=closure(Graph ell_(c,gamma)) with topology transported from M_k (equivalently its graph norm when ell is bounded)",
 "laws":{"retraction":"pi_k A_k=id","translation":"ell_(c+a,gamma) U_a=ell_(c,gamma)","dagger":"ell is fixed by swapping +/- ports","cells":"A_k commutes with every whiskered edge/face/bulk map preserving the moving port"},
 "fixtures":rows,"checks":checks,"passed":True,
 "meaning":"A nonzero source-derived one-unit realization successor generated by the dagger-even moving-index observation.",
 "claim_boundary":"This realizes one specific index-observation dimension. It is not a theorem that every independently intended arithmetic dimension is this line."
}
path=Path(__file__).parents[1]/"results"/"nontrivial_moving_index_dimension_successor.json"
path.write_text(json.dumps(out,indent=2)+"\n",encoding="utf-8")
print(json.dumps(out,indent=2))
