#!/usr/bin/env python3
"""Check the A6/A7 level retyping against the owner-authored rung packet."""
import hashlib,json,platform
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];FIX=ROOT/'research/voevodsky/fixtures/a6_a7_realization_fiber_level_retyping.v1.json';SRC=ROOT/'research/kitaev/realization-fiber-coherence-rung.md';OUT=ROOT/'research/voevodsky/results/a6_a7_realization_fiber_level_retyping.json';D=json.loads(FIX.read_text());text=SRC.read_text(encoding='utf-8')
phrases=['A6  law of compositions','A7  realization-fiber coherence','C1_6`, law-to-realization fiber comparison','realization-intertwiner groupoid','Pairwise intertwiners are promoted to global fiber coherence without triangle and higher checks.']
cons=D['retyping_consequences'];checks={'owner_source_fragments_present':all(x in text for x in phrases),'a7_groupoid_valued_fiber':D['canonical_rung']['A7']['object_kind'].startswith('groupoid-valued fiber'),'c1_6_not_linear_state_map':'not a linear state map' in D['canonical_rung']['C1_6']['object_kind'],'six_morphism_requirements':len(D['verified_morphism_requirements'])==6,'finite_core_retains_constructor_observer_form':D['finite_linear_core']==['T A_c = A_d T','O_d T = R O_c','T* W_d T = W_c'],'all_five_level_errors_retyped':len(cons)==5,'radial_carrier_placed_inside_fiber':D['placement_of_current_finite_evidence']['radial_history_carrier']=='candidate realization object c','profile_map_is_first_gate':D['disposition']['first_missing_typed_datum']=='the exact profile map alpha(c)=a for the radial candidate'}
out={'schema':'marici.voevodsky.a6-a7-realization-fiber-level-retyping-check.v1','passed':all(checks.values()),'checks':checks,'disposition':'The prior Hilbert-state reading of the canonical A6/A7 edge is rejected. A7 is a realization-intertwiner fiber groupoid; finite radial data can supply one object and its internal certification, not the fiber itself.','claim_boundary':D['claim_boundary'],'execution_receipt':{'command':'python research/voevodsky/checkers/check_a6_a7_realization_fiber_level_retyping.py','python':platform.python_version(),'fixture_sha256':hashlib.sha256(FIX.read_bytes()).hexdigest(),'source_sha256':hashlib.sha256(SRC.read_bytes()).hexdigest(),'checker_sha256':hashlib.sha256(Path(__file__).read_bytes()).hexdigest()}}
OUT.parent.mkdir(parents=True,exist_ok=True);OUT.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n');print(json.dumps(out,indent=2,sort_keys=True));raise SystemExit(0 if out['passed'] else 1)
