#!/usr/bin/env python3
"""Verify the integral eigenlattice defect of the equal-order triple residue."""
from hashlib import sha256
from itertools import product
from pathlib import Path
import json
import sympy as s
from sympy.matrices.normalforms import smith_normal_form
from sympy.polys.domains import ZZ
ROOT=Path(__file__).resolve().parents[3];PACKET=ROOT/'research/voevodsky/equal_order_triple_residue_recovers_one_integral_parity_step.md';PREV=ROOT/'research/voevodsky/results/total_energy_triple_relative_divisor.json';RESULT=ROOT/'research/voevodsky/results/equal_order_residue_eigenlattice.json';R=s.Matrix([[2,0,0],[-1,1,1],[1,1,1]]);e1=s.Matrix([-1,1,0]);e2=s.Matrix([1,0,1]);k=s.Matrix([0,-1,1]);W=s.Matrix.hstack(e1,e2,k);D=s.diag(2,2,0);S=smith_normal_form(W,domain=ZZ);chars=[list(bits) for bits in product((0,1),repeat=3) if any(bits) and all(int(x)%2==0 for x in s.Matrix([bits])*W)];checks={'previous_residue_exact':json.loads(PREV.read_text(encoding='utf-8'))['equal_order_residue']==[[2,0,0],[-1,1,1],[1,1,1]],'e1_eigenvalue_two':R*e1==2*e1,'e2_eigenvalue_two':R*e2==2*e2,'k_flat':R*k==s.zeros(3,1),'diagonalization':W.inv()*R*W==D,'eigenlattice_index_two':abs(W.det())==2,'smith_112':[abs(int(S[i,i])) for i in range(3)]==[1,1,2],'unique_character':chars==[[1,1,1]],'no_unimodular_eigenbasis':'every integral eigenbasis has even determinant' in PACKET.read_text(encoding='utf-8'),'equal_order_conditional':'Conditional on equal-order transverse specialization' in PACKET.read_text(encoding='utf-8')};checks={x:bool(y) for x,y in checks.items()};result={'schema':'marici.voevodsky.equal-order-residue-eigenlattice.v1','packet_sha256':sha256(PACKET.read_bytes()).hexdigest(),'previous_result_sha256':sha256(PREV.read_bytes()).hexdigest(),'residue':[[int(x) for x in R.row(i)] for i in range(3)],'eigenbasis':[[int(x) for x in W.row(i)] for i in range(3)],'eigenbasis_determinant':int(W.det()),'smith_invariants':[1,1,2],'parity_character':[1,1,1],'checks':checks,'passed':all(checks.values()),'disposition':{'rational_diagonalization':'verified','integral_index_two_defect':'verified','equal_order_authority':'missing','two_wall_nearby_totalization':'missing'}};RESULT.write_text(json.dumps(result,indent=2)+'\n',encoding='utf-8');print(json.dumps({'passed':result['passed'],'checks':checks,'disposition':result['disposition']}));raise SystemExit(0 if result['passed'] else 1)
