"""Frozen local-to-global test using independent continuation quotients.

Source is the actual four-state admitted evidence family. Local views are
A-only and B-only continuation observers. Overlap is independently fixed as
common frozen-problem binding and current certified status, not joint image.
"""
from pathlib import Path
from itertools import product
import subprocess
import sys
import json
import hashlib
ROOT = Path(__file__).resolve().parents[3]
DIR = ROOT / 'research/voevodsky/results/continuation-quotient'
source_path = DIR / 'incomparable-proof-branch-merge.json'
contract_path = DIR / 'incomparable-proof-branch-contract.json'
def load(p): return json.loads(p.read_text())
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def save(p, v): p.write_text(json.dumps(v, indent=2) + '\n')
c, data = load(contract_path), load(source_path)
contract = {
    'source_sha256': sha(source_path), 'source_contract_sha256': sha(contract_path),
    'source_domain': 'P,A,B,AB, the closed actual primitive-evidence family for one frozen input.',
    'local_views': 'Minimal output/continuation quotients for merge-A-only and merge-B-only, derived independently.',
    'overlap': 'Frozen problem binding plus present certified status. Equality only; no joint-image test included.',
    'local_admission': 'Each local class has at least one source-state preimage.',
    'prediction': 'Every locally admitted pair with equal overlap has a common source-state preimage.',
    'scope': 'Same retained evidence state. Distributed local histories and common future extensions are a distinct contract.'
}
cp = DIR / 'local-to-global-source-assembly-contract.json'; save(cp, contract)
# Fresh owning reconstruction and source-bound common refinement checks.
subprocess.run([sys.executable, str(Path(__file__).with_name('check_common_continuation_refinement.py'))], check=True, capture_output=True, text=True)
common = load(DIR / 'common-continuation-refinement.json')
assert common['input_sha256'] == contract['source_sha256']
a = common['quotients']['A_only']; b = common['quotients']['B_only']
states = tuple(a)
output = {s: (c['task_sha256'], data['task_results'][s]['status']) for s in states}
def fibers(q): return {v: {s for s in states if q[s] == v} for v in set(q.values())}
fa, fb = fibers(a), fibers(b)
def overlap(fiber):
    values = {output[s] for s in fiber}
    assert len(values) == 1
    return next(iter(values))
trials = []
for x, y in product(sorted(fa), sorted(fb)):
    assert fa[x] and fb[y]
    agree = overlap(fa[x]) == overlap(fb[y])
    joint = fa[x] & fb[y]
    trials.append({'local_pair': [x, y], 'overlap_agrees': agree,
                   'left_witnesses': sorted(fa[x]), 'right_witnesses': sorted(fb[y]),
                   'global_fiber': sorted(joint)})
failures = [t for t in trials if t['overlap_agrees'] and not t['global_fiber']]
assert len(failures) == 1
assert failures[0]['left_witnesses'] == ['B'] and failures[0]['right_witnesses'] == ['A']
# Check whether a stronger common DETERMINISTIC overlap of the same local views
# could repair this. Any such overlap is constant on equivalences generated by
# both local kernels. Compute their join independently of the failed pair.
parent = {s: s for s in states}
def root(s):
    while parent[s] != s: s = parent[s]
    return s
def union(x, y): parent[root(x)] = root(y)
for fiber in list(fa.values()) + list(fb.values()):
    first = next(iter(fiber))
    for s in fiber: union(first, s)
groups = {}
for s in states: groups.setdefault(root(s), []).append(s)
join_classes = sorted((sorted(v) for v in groups.values()), key=repr)
assert sorted(['P', 'A', 'B']) in join_classes
assert root('A') == root('B')
# Hence any common overlap function constant on both local fibers identifies
# A and B, so the spurious local pair always passes equality of such overlaps.
assert sha(source_path) == contract['source_sha256'] and sha(contract_path) == contract['source_contract_sha256']
report = {
    'verdict': 'REFUTED_FOR_FROZEN_LOCAL_VIEWS_AND_OVERLAP',
    'contract_sha256': sha(cp), 'locally_admitted_pairs': len(trials),
    'overlap_compatible_pairs': sum(t['overlap_agrees'] for t in trials),
    'globally_realizable_pairs': sum(bool(t['global_fiber']) for t in trials),
    'counterexamples': failures, 'all_pairs': trials,
    'join_of_local_kernel_equivalences': join_classes,
    'stronger_overlap_obstruction': 'Every deterministic common factor of these same local views identifies A and B; equality over any such factor still admits the spurious pair.',
    'scope': 'Finite evidence source. To repair same-state assembly requires richer local views, an additional joint compatibility relation, or a changed assembly contract. A common extension AB does not restrict to this supplied pair.'
}
save(DIR / 'local-to-global-source-assembly.json', report)
print(json.dumps({k: v for k, v in report.items() if k != 'all_pairs'}, indent=2))
