#!/usr/bin/env python3
"""Exact grade and cutoff reconciliation with the retained G1 joint graph."""
import hashlib,json,platform
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];FIX=ROOT/'research/voevodsky/fixtures/transported_defect_register_to_retained_g1_graph.v1.json';OUT=ROOT/'research/voevodsky/results/transported_defect_register_to_retained_g1_graph.json';D=json.loads(FIX.read_text());N=D['depth']
def register(depth):return [{'projector':f'P{j}','grade':j+1,'summand':'Gamma_12' if j+1<=2 else 'Gamma_ge3','terminal':j==depth} for j in range(depth+1)]
rN=register(N);rNext=register(N+1);prefix=[{**x,'terminal':False} for x in rN]
# Existing grade identities persist; only the role flag terminal changes at extension.
checks={'grade_shift_exact':[x['grade'] for x in rN]==[1,2,3,4],'primitive_square_land_in_Gamma12':all(x['summand']=='Gamma_12' for x in rN[:2]),'connected_grades_land_in_separate_summand':all(x['summand']=='Gamma_ge3' for x in rN[2:]),'finite_terminal_is_highest_grade':rN[-1]=={'projector':'P3','grade':4,'summand':'Gamma_ge3','terminal':True},'old_terminal_reclassified_not_deleted':rNext[3]=={'projector':'P3','grade':4,'summand':'Gamma_ge3','terminal':False},'new_terminal_appended':rNext[-1]=={'projector':'P4','grade':5,'summand':'Gamma_ge3','terminal':True},'prefix_labels_natural':all(rNext[i]['projector']==rN[i]['projector'] and rNext[i]['grade']==rN[i]['grade'] and rNext[i]['summand']==rN[i]['summand'] for i in range(len(rN))),'codiagonal_after_graph_construction':D['constructor_order'].index('apply within-prime Wronskian codiagonal')>D['constructor_order'].index('form polarized Green direct sum'),'all_prime_scalar_last':D['constructor_order'][-1].endswith('terminally'),'output_only_gate_not_reopened':D['disposition']['output_only_mate'].startswith('not required')}
out={'schema':'marici.voevodsky.transported-defect-register-to-retained-g1-graph-check.v1','passed':all(checks.values()),'checks':checks,'computed':{'depth_three_register':rN,'depth_four_register':rNext,'retained_carrier':'Gamma_12 direct-sum Gamma_ge3','within_prime_codiagonal_position':4,'terminal_scalar_evaluator_position':5},'disposition':'The transported Green register is exactly the grade source of the selected retained G1 graph after k=j+1 reindexing. Terminal status is cutoff-relative, while the grade coordinate persists under extension.','claim_boundary':D['claim_boundary'],'execution_receipt':{'command':'python research/voevodsky/checkers/check_transported_defect_register_to_retained_g1_graph.py','python':platform.python_version(),'fixture_sha256':hashlib.sha256(FIX.read_bytes()).hexdigest(),'source_sha256':{p:hashlib.sha256((ROOT/p).read_bytes()).hexdigest() for p in D['sources']},'checker_sha256':hashlib.sha256(Path(__file__).read_bytes()).hexdigest()}}
OUT.parent.mkdir(parents=True,exist_ok=True);OUT.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n');print(json.dumps(out,indent=2,sort_keys=True));raise SystemExit(0 if out['passed'] else 1)
