#!/usr/bin/env python3
"""Exact rational sign certificate for finite prime-two Euler/theta incidence grades."""
import hashlib,json,platform
from fractions import Fraction as Q
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];FIX=ROOT/'research/voevodsky/fixtures/prime_two_gradewise_euler_theta_incidence_mate.v1.json';OUT=ROOT/'research/voevodsky/results/prime_two_gradewise_euler_theta_incidence_mate.json';D=json.loads(FIX.read_text());grades=D['grades']
def poly(x):return 8*x*x-30*x+15
def derivative(x):return 16*x-30
# Use lambda>1, so x=lambda*2^(2k)>the rational lower bound shown here.
lower={k:Q(2)**(2*k) for k in grades};q_lower={k:poly(lower[k]) for k in grades};weights={k:Q(2)**(-k) for k in grades} # squared half-density, enough to certify nonzero loading
checks={'grades_match_transported_green_indices':grades==[1,2,3,4],'minimum_x_bound_four':lower[1]==4,'Q_positive_at_four':poly(Q(4))>0,'Q_increasing_from_four':derivative(Q(4))>0,'all_grade_Q_lower_bounds_positive':all(v>0 for v in q_lower.values()),'all_euler_half_density_squares_positive':all(v>0 for v in weights.values()),'all_theta_derivative_components_strictly_negative':all(q_lower[k]>0 for k in grades),'diagonal_incidence_components_nonzero':all(q_lower[k]*weights[k]>0 for k in grades),'primitive_square_connected_separated':grades[:2]==[1,2] and grades[2:]==[3,4],'completion_metric_not_promoted':'sampling pullback metric' in D['disposition']['remaining_gate']}
out={'schema':'marici.voevodsky.prime-two-gradewise-euler-theta-incidence-mate-check.v1','passed':all(checks.values()),'checks':checks,'computed':{'grade_to_green_atomic_index':{str(k):k-1 for k in grades},'rational_x_lower_bounds':{str(k):str(v) for k,v in lower.items()},'Q_at_lower_bounds':{str(k):str(v) for k,v in q_lower.items()},'squared_half_density_weights':{str(k):str(v) for k,v in weights.items()},'incidence_sign_by_grade':{str(k):'strictly negative' for k in grades}},'disposition':'Each retained prime-two grade has a source-derived nonzero Euler-to-theta incidence component, so the finite diagonal grade mate is faithful. Completion remains metric-dependent because these coefficients decay with prime and grade.','claim_boundary':D['claim_boundary'],'execution_receipt':{'command':'python research/voevodsky/checkers/check_prime_two_gradewise_euler_theta_incidence_mate.py','python':platform.python_version(),'fixture_sha256':hashlib.sha256(FIX.read_bytes()).hexdigest(),'source_sha256':{p:hashlib.sha256((ROOT/p).read_bytes()).hexdigest() for p in D['sources']},'checker_sha256':hashlib.sha256(Path(__file__).read_bytes()).hexdigest()}}
OUT.parent.mkdir(parents=True,exist_ok=True);OUT.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n');print(json.dumps(out,indent=2,sort_keys=True));raise SystemExit(0 if out['passed'] else 1)
