#!/usr/bin/env python3
"""Check generic common-residue-kernel obstruction to constant conductor transport."""
from hashlib import sha256
from pathlib import Path
import json
import sympy as s
ROOT=Path(__file__).resolve().parents[3];PACKET=ROOT/'research/voevodsky/generic_relative_subconnection_has_no_constant_flat_line_for_conductor_transport.md';RESULT=ROOT/'research/voevodsky/results/generic_relative_connection_flat_line_obstruction.json';PAGE=ROOT/'references/extractions/pdf-search-all/cosmology-meets-cohomology-2308-03753/pdf-page-0021.txt';names=['A','B','C','D','E'];R={n:s.zeros(3) for n in names};entries={(0,0):{'B':1,'E':1},(0,1):{'C':1,'E':-1},(0,2):{'C':1,'E':-1},(1,0):{'A':1,'E':-1},(1,1):{'D':1,'E':1},(1,2):{'E':1,'A':-1},(2,0):{'B':1,'A':-1},(2,1):{'C':1,'D':-1},(2,2):{'A':1,'C':1}}
for (i,j),terms in entries.items():
 for n,v in terms.items():R[n][i,j]=v
stack=s.Matrix.vstack(*[R[n] for n in names]);K1=s.Matrix([[1,0,s.Rational(1,2)],[0,0,0],[0,0,0]]);K2=s.Matrix([[0,0,0],[0,1,0],[0,0,0]]);v=s.Matrix([-1,0,2]);checks={'relative_stacked_rank_three':stack.rank()==3,'relative_common_kernel_zero':stack.nullspace()==[],'conductor_flat_vector_nonzero':v!=s.zeros(3,1),'conductor_a1_residue_kills_v':K1*v==s.zeros(3,1),'conductor_a2_residue_kills_v':K2*v==s.zeros(3,1),'conductor_common_kernel_dimension_one':s.Matrix.vstack(K1,K2).rank()==2,'constant_gauge_obstruction_stated':'generic connection transport by constant integral bases is obstructed' in PACKET.read_text(encoding='utf-8'),'specialization_not_excluded':'does not exclude a parameter-dependent gauge or a specialization' in PACKET.read_text(encoding='utf-8')};checks={k:bool(vv) for k,vv in checks.items()};result={'schema':'marici.voevodsky.generic-relative-flat-line-obstruction.v1','packet_sha256':sha256(PACKET.read_bytes()).hexdigest(),'source_page_sha256':sha256(PAGE.read_bytes()).hexdigest(),'relative_residue_matrices':{n:[[int(x) for x in R[n].row(i)] for i in range(3)] for n in names},'relative_common_kernel_dimension':0,'conductor_common_kernel_dimension':1,'conductor_flat_vector':[-1,0,2],'checks':checks,'passed':all(checks.values()),'disposition':{'constant_integral_connection_transport':'obstructed generically','parameter_specialization':'still open','parameter_dependent_gauge':'still open'}};RESULT.write_text(json.dumps(result,indent=2)+'\n',encoding='utf-8');print(json.dumps({'passed':result['passed'],'checks':checks,'disposition':result['disposition']}));raise SystemExit(0 if result['passed'] else 1)
