#!/usr/bin/env python3
"""Audit determinant, Smith form, and inverse of source equation (3.44)."""
from hashlib import sha256
from pathlib import Path
import json
import sympy as s
from sympy.matrices.normalforms import smith_normal_form
from sympy.polys.domains import ZZ
ROOT=Path(__file__).resolve().parents[3];PACKET=ROOT/'research/voevodsky/relative_intersection_matrix_exhibits_one_half_integral_parity_defect.md';RESULT=ROOT/'research/voevodsky/results/relative_intersection_parity_defect.json';PAGE=ROOT/'references/extractions/pdf-search-all/cosmology-meets-cohomology-2308-03753/pdf-page-0021.txt';INTER=ROOT/'research/benincasa/orientation-twisted-conductor-rees-intertwiner.json'
C=s.Matrix([[0,-1,1,0],[1,0,0,0],[1,1,0,1],[-1,0,1,-1]]);Sinv=smith_normal_form(C,domain=ZZ);Ci=C.inv();a=json.loads(INTER.read_text(encoding='utf-8'));J=s.Matrix(a['intertwiner_matrix_row_major']);SJ=smith_normal_form(J,domain=ZZ);halves=sum(1 for i in range(4) if any(v.q==2 for v in Ci.row(i)));checks={'determinant_minus_two':C.det()==-2,'smith_1112':[abs(int(Sinv[i,i])) for i in range(4)]==[1,1,1,2],'inverse_exact':Ci==s.Matrix([[0,1,0,0],[s.Rational(-1,2),0,s.Rational(1,2),s.Rational(1,2)],[s.Rational(1,2),0,s.Rational(1,2),s.Rational(1,2)],[s.Rational(1,2),-1,s.Rational(1,2),s.Rational(-1,2)]]),'half_integral_rows_three':halves==3,'conductor_smith_122':[abs(int(SJ[i,i])) for i in range(3)]==[1,2,2],'source_page_contains_matrix':'0 ΓêÆ1 1 0' in PAGE.read_text(encoding='utf-8'),'integral_lattice_gate_retained':'no automatic integral lattice' in PACKET.read_text(encoding='utf-8'),'no_torsion_promotion':'does not verify the conductor torsion' in PACKET.read_text(encoding='utf-8')};checks={k:bool(v) for k,v in checks.items()}
result={'schema':'marici.voevodsky.relative-intersection-parity-defect.v1','packet_sha256':sha256(PACKET.read_bytes()).hexdigest(),'source_page_sha256':sha256(PAGE.read_bytes()).hexdigest(),'conductor_intertwiner_sha256':sha256(INTER.read_bytes()).hexdigest(),'intersection_matrix':[list(map(int,C.row(i))) for i in range(4)],'determinant':int(C.det()),'smith_invariants':[1,1,1,2],'inverse':[[str(v) for v in C.inv().row(i)] for i in range(4)],'checks':checks,'passed':all(checks.values()),'disposition':{'relative_display_basis':'one index-two defect','conductor_lattice':'two index-two defects','comparison':'arithmetic analogue only','physical_status':'unverified'}}
RESULT.write_text(json.dumps(result,indent=2)+'\n',encoding='utf-8');print(json.dumps({'passed':result['passed'],'checks':checks,'disposition':result['disposition']}));raise SystemExit(0 if result['passed'] else 1)
