#!/usr/bin/env python3
"""Audit whether existing Aspect packets authorize the same-parity physical record lattice."""
from hashlib import sha256
from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[3];PACKET=ROOT/'research/voevodsky/same_parity_lattice_is_not_yet_a_physical_detector_record_space.md';RESULT=ROOT/'research/voevodsky/results/same_parity_physical_record_gate.json';CONTRACT=ROOT/'research/aspect/contracts/relative-cech-de-rham-interferometer.v1.json';COUNT=ROOT/'research/aspect/calibrated-photon-counting-intensity-statistics.md';CONTROL=ROOT/'research/aspect/connected-route-coherent-control-apparatus.md'
a=json.loads(CONTRACT.read_text(encoding='utf-8'));ct=COUNT.read_text(encoding='utf-8');ctrl=CONTROL.read_text(encoding='utf-8');text=PACKET.read_text(encoding='utf-8');same=lambda u,v:(u-v)%2==0;checks={'contract_simulation_only':'simulation-only structural classifier' in a['scope'],'linear_readout_exact':a['readouts']['complementary_phase_sensitive']==[[1,-1],[1,1]],'elementary_records_excluded':not same(1,0) and not same(0,1),'count_packet_admits_ordered_records':'Records `(1,0)` and `(0,1)` in two' in ct,'count_records_are_temporal_bins':'in two\ntime bins' in ct,'phase_reference_required':'A local oscillator or another coherent phase reference is required' in ct,'control_is_not_raw_counts':'ideal deterministic means, not fabricated detector counts' in ctrl,'physical_packet_requires_trials':'must replace ideal means with raw trial counts' in ctrl,'typed_map_distinction_retained':'These are different typed maps' in text,'no_automatic_transport':'would require a detector-mode map' in text,'physical_authority_absent':'No current Aspect artifact authorizes the same-parity lattice' in text};checks={k:bool(v) for k,v in checks.items()}
result={'schema':'marici.voevodsky.same-parity-physical-record-gate.v1','packet_sha256':sha256(PACKET.read_bytes()).hexdigest(),'source_digests':{'contract':sha256(CONTRACT.read_bytes()).hexdigest(),'counting':sha256(COUNT.read_bytes()).hexdigest(),'control':sha256(CONTROL.read_bytes()).hexdigest()},'same_parity_membership':{'(1,0)':False,'(0,1)':False,'(0,2)':True},'checks':checks,'passed':all(checks.values()),'disposition':{'linear_lattice_repair':'valid algebraically','literal_detector_lattice':'unauthorized','strongest_reading':'characteristic-zero structural or estimator map','missing':['detector-mode map','raw-trial model','parity-sensitive calibration']}}
RESULT.write_text(json.dumps(result,indent=2)+'\n',encoding='utf-8');print(json.dumps({'passed':result['passed'],'checks':checks,'disposition':result['disposition']}));raise SystemExit(0 if result['passed'] else 1)
