#!/usr/bin/env python3
"""Verify primitive anticanonical class, Gysin ranks, and exclusion of zero parity."""
from hashlib import sha256
from itertools import product
from math import gcd
from pathlib import Path
import json
import sympy as s
R=Path(__file__).resolve().parents[3];P=R/'research/voevodsky/the_regular_anticanonical_del_pezzo_complement_is_torsion_free.md';SYM=R/'research/voevodsky/results/klein_four_parity_representations.json';LOCAL=R/'research/benincasa/local-pl-parity-ambiguity.md';OUT=R/'research/voevodsky/results/del_pezzo_complement_torsion.json';D=[3]+[-1]*7;primitive=gcd(*map(abs,D));# rank H2(U)=(8-1)+2 because H3(S)=0 and H1(D)=Z2
rank_U=7+2;torsion={(a,b):gcd(2,a,b) for a,b in product((0,1),repeat=2)};sym=json.loads(SYM.read_text());local=LOCAL.read_text();text=P.read_text();checks={'anticanonical_primitive':primitive==1,'picard_rank_eight':len(D)==8,'quotient_rank_seven':len(D)-1==7,'elliptic_H1_rank_two':2==2,'complement_rank_nine':rank_U==9,'zero_presentation_has_Z2':torsion[(0,0)]==2,'three_nonzero_presentations_free':all(torsion[v]==1 for v in [(1,0),(0,1),(1,1)]),'four_candidates_prior':'all four parity vectors' in local,'conditional_symmetry_selector':sym['checks']['nontrivial_image_unique_nonzero_fixed'],'smooth_scope':'does not assert that the singular fiber complement has the same cohomology' in text,'nonzero_conclusion':'ambient parity is therefore nonzero' in text};checks={k:bool(v) for k,v in checks.items()};result={'schema':'marici.voevodsky.del-pezzo-complement-torsion.v1','packet_sha256':sha256(P.read_bytes()).hexdigest(),'symmetry_result_sha256':sha256(SYM.read_bytes()).hexdigest(),'anticanonical_vector':D,'anticanonical_content':primitive,'gysin_ranks':{'H2_S':8,'image_D':1,'quotient':7,'H1_D':2,'H2_U':rank_U},'presentation_torsion_orders':{str(k):v for k,v in torsion.items()},'checks':checks,'passed':all(checks.values()),'disposition':{'H2_regular_complement':'free rank 9','excluded_parity':[0,0],'remaining_parities':[[1,0],[0,1],[1,1]],'next_selector':'nontrivial induced involution or one direct integral intersection'}};OUT.write_text(json.dumps(result,indent=2)+'\n');print(json.dumps({'passed':result['passed'],'checks':checks,'disposition':result['disposition']}));raise SystemExit(0 if result['passed'] else 1)
