#!/usr/bin/env python3
"""Verify exact estimator range and conservative two-parity Hoeffding bound."""
from hashlib import sha256
from itertools import product
from pathlib import Path
import json
import sympy as s
from sympy import kronecker_product as kron
ROOT=Path(__file__).resolve().parents[3];PACKET=ROOT/'research/voevodsky/inverse_calibration_makes_naive_parity_sampling_expensive.md';CAL=ROOT/'research/voevodsky/results/finite_count_parity_calibration.json';E2E=ROOT/'research/voevodsky/results/end_to_end_null_channel.json';RESULT=ROOT/'research/voevodsky/results/inverse_calibration_parity_sample_bound.json';cal=json.loads(CAL.read_text(encoding='utf-8'));R=s.Matrix([[s.Rational(x) for x in row] for row in cal['single_response']]);L=s.Matrix([[s.Rational(x) for x in row] for row in cal['single_left_inverse']]);L3=kron(L,L,L);occ=list(product(range(3),repeat=3));f1=s.Matrix([[(-1)**(n[0]+n[2]) for n in occ]]);f2=s.Matrix([[(-1)**(n[1]+n[2]) for n in occ]]);gs=[f1*L3,f2*L3];mins=[min(g) for g in gs];maxs=[max(g) for g in gs];ranges=[s.factor(b-a) for a,b in zip(mins,maxs)];B=s.Rational(33840211000,43046721);N=s.ceiling(2*B**2*s.log(80));perfect=s.ceiling(8*s.log(80));text=PACKET.read_text(encoding='utf-8');e2e=json.loads(E2E.read_text(encoding='utf-8'));checks={'prior_calibration':cal['passed'],'prior_end_to_end':e2e['passed'],'common_exact_range':ranges==[B,B],'exact_minima':mins==[s.Rational(-8408362000,43046721)]*2,'exact_maxima':maxs==[s.Rational(2825761000,4782969)]*2,'union_hoeffding_trials':N==5416154,'perfect_detector_comparison':perfect==36,'scope_gate':'not an optimal estimator, a measured noise model, or an acquisition result' in text,'conditioning_warning':'Invertibility alone does not imply practical acquisition efficiency' in text};checks={k:bool(v) for k,v in checks.items()};result={'schema':'marici.voevodsky.inverse-calibration-parity-sample-bound.v1','packet_sha256':sha256(PACKET.read_bytes()).hexdigest(),'calibration_result_sha256':sha256(CAL.read_bytes()).hexdigest(),'end_to_end_result_sha256':sha256(E2E.read_bytes()).hexdigest(),'weight_min':str(mins[0]),'weight_max':str(maxs[0]),'weight_range':str(B),'total_error_bound':'0.05','sign_margin':'1/2','sufficient_trials':int(N),'perfect_detector_bound':int(perfect),'checks':checks,'passed':all(checks.values()),'disposition':{'naive_inverse_estimator':'executable but poorly conditioned','trial_bound':int(N),'optimization':'not performed'}};RESULT.write_text(json.dumps(result,indent=2)+'\n',encoding='utf-8');print(json.dumps({'passed':result['passed'],'checks':checks,'disposition':result['disposition']}));raise SystemExit(0 if result['passed'] else 1)
