#!/usr/bin/env python3
"""Verify that optical decode tests leave the cusp-to-conductor comparison unresolved."""
from hashlib import sha256
from itertools import product
from pathlib import Path
import json
import sympy as s
ROOT=Path(__file__).resolve().parents[3];PACKET=ROOT/'research/voevodsky/the_optical_null_channel_decodes_but_does_not_determine_the_cusp_extension.md';PROBE=ROOT/'research/voevodsky/results/minimal_cut_null_complementary_probe.json';ENC=ROOT/'research/voevodsky/results/single_rail_conductor_encoder.json';E2E=ROOT/'research/voevodsky/results/end_to_end_null_channel.json';CUT=ROOT/'src/ledger/20260821-1751 The Physical Cut Pairing Does Not Resolve the Integral Cusp Extension.md';RESULT=ROOT/'research/voevodsky/results/optical_decoder_circularity_gate.json';S=s.Matrix([[0,1],[1,0]]);I=s.eye(2);gl=[]
for bits in product((0,1),repeat=4):
 M=s.Matrix(2,2,bits)
 if int(M.det())%2==1 and all(int(x)%2==0 for x in M*S-S*M):gl.append(M)
probe=json.loads(PROBE.read_text(encoding='utf-8'));enc=json.loads(ENC.read_text(encoding='utf-8'));e2e=json.loads(E2E.read_text(encoding='utf-8'));cut=CUT.read_text(encoding='utf-8');text=PACKET.read_text(encoding='utf-8');classes=[s.Matrix(v) for v in product((0,1),repeat=2)];decode=lambda M,v:tuple(int(x)%2 for x in M*v);id_outputs=[decode(I,v) for v in classes];swap_outputs=[decode(S,v) for v in classes];checks={'probe_constructed':probe['passed'],'encoder_constructed':enc['passed'],'decode_roundtrip':e2e['checks']['all_classes_decoded'],'two_exchange_compatible_comparisons':len(gl)==2 and any(M==I for M in gl) and any(M==S for M in gl),'comparisons_differ':id_outputs!=swap_outputs,'both_are_bijections':len(set(id_outputs))==4 and len(set(swap_outputs))==4,'cut_is_zero':'is zero' in cut,'domain_distinction':'Equal abstract group structure does not identify these spaces' in text,'presupposition_exposed':'presupposes the input bits' in text,'missing_comparison':'isolated as the missing comparison' in text};checks={k:bool(v) for k,v in checks.items()};result={'schema':'marici.voevodsky.optical-decoder-circularity-gate.v1','packet_sha256':sha256(PACKET.read_bytes()).hexdigest(),'probe_sha256':sha256(PROBE.read_bytes()).hexdigest(),'encoder_sha256':sha256(ENC.read_bytes()).hexdigest(),'end_to_end_sha256':sha256(E2E.read_bytes()).hexdigest(),'exchange_compatible_phi_count':len(gl),'identity_outputs':id_outputs,'swap_outputs':swap_outputs,'checks':checks,'passed':all(checks.values()),'disposition':{'optical_decoder':'verified conditional on supplied conductor class','cusp_to_conductor_phi':'missing','ambient_cusp_parity':'not determined','required_input':'global Picard marking or source coupling from thimble to syndromes'}};RESULT.write_text(json.dumps(result,indent=2)+'\n',encoding='utf-8');print(json.dumps({'passed':result['passed'],'checks':checks,'disposition':result['disposition']}));raise SystemExit(0 if result['passed'] else 1)
