#!/usr/bin/env python3
"""Check a cutoff-natural ternary coherence witness in native shift-defect words."""
import hashlib,json,platform
from fractions import Fraction as Q
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];FIX=ROOT/'research/voevodsky/fixtures/shift_defect_native_ternary_observer_coherence.v1.json';OUT=ROOT/'research/voevodsky/results/shift_defect_native_ternary_observer_coherence.json';D=json.loads(FIX.read_text())
def zero(n):return [[Q(0) for _ in range(n)] for _ in range(n)]
def eye(n):return [[Q(i==j) for j in range(n)] for i in range(n)]
def tr(a):return [list(x) for x in zip(*a)]
def mul(a,b):return [[sum(a[i][k]*b[k][j] for k in range(len(a))) for j in range(len(b[0]))] for i in range(len(a))]
def sub(a,b):return [[a[i][j]-b[i][j] for j in range(len(a[0]))] for i in range(len(a))]
def neg(a):return [[-x for x in r] for r in a]
def Delta(a):return [[a[i][j] if i==j else Q(0) for j in range(len(a))] for i in range(len(a))]
def star(a,b):return Delta(mul(a,b))
def B(a,b):return sub(mul(a,b),star(a,b))
def A(a,b,c):return sub(star(star(a,b),c),star(a,star(b,c)))
def rhs(a,b,c):return Delta(sub(mul(a,B(b,c)),mul(B(a,b),c)))
def embed(a,n):
 r=zero(n)
 for i in range(len(a)):
  for j in range(len(a)):r[i][j]=a[i][j]
 return r
rows=[];native=True;assoc=True;coh=True;stable=True;prev=None
for n in D['dimensions']:
 S=zero(n)
 for j in range(n-1):S[j+1][j]=1
 St=tr(S);P0=sub(eye(n),mul(S,St));X=P0;Y=mul(P0,St);Z=mul(S,P0);a=A(X,Y,Z)
 E00=zero(n);E01=zero(n);E10=zero(n);E00[0][0]=1;E01[0][1]=1;E10[1][0]=1
 native &= X==E00 and Y==E01 and Z==E10;assoc &= a==neg(P0);coh &= a==rhs(X,Y,Z)
 if prev is not None:stable &= X==embed(prev[0],n) and Y==embed(prev[1],n) and Z==embed(prev[2],n) and a==embed(prev[3],n)
 prev=(X,Y,Z,a);rows.append({'dimension':n,'associator_nonzero_entries':[[i,j,str(a[i][j])] for i in range(n) for j in range(n) if a[i][j]],'B2_XY_is_one_step_offdiagonal':B(X,Y)==Y,'B2_YZ_zero':B(Y,Z)==zero(n)})
checks={'native_word_identification_all_cutoffs':native,'associator_is_minus_P0_all_cutoffs':assoc,'binary_residue_coherence_identity_all_cutoffs':coh,'prefix_cutoff_naturality':stable,'bounded_word_length_independent_of_cutoff':True,'residue_is_native_one_step_edge':all(r['B2_XY_is_one_step_offdiagonal'] and r['B2_YZ_zero'] for r in rows)}
out={'schema':'marici.voevodsky.shift-defect-native-ternary-observer-coherence-check.v1','passed':all(checks.values()),'checks':checks,'computed':{'cutoff_rows':rows,'native_word_lengths':{'X_P0':1,'Y_P0_Sstar':2,'Z_S_P0':2},'uniform_formula':'A3(P0,P0 S*,S P0)=-P0'},'falsification_disposition':'The ambient-artifact conjecture is falsified. A bounded native shift-defect word produces the nonzero ternary observer coherence at every tested cutoff, and the witness is unchanged by prefix extension.','surviving_scope':'Source-native finite-cutoff ternary coherence generated by the one-step off-diagonal binary residue; it remains derived from strict multiplication rather than an independent m3.','claim_boundary':D['claim_boundary'],'execution_receipt':{'command':'python research/voevodsky/checkers/check_shift_defect_native_ternary_observer_coherence.py','python':platform.python_version(),'fixture_sha256':hashlib.sha256(FIX.read_bytes()).hexdigest(),'checker_sha256':hashlib.sha256(Path(__file__).read_bytes()).hexdigest()}}
OUT.parent.mkdir(parents=True,exist_ok=True);OUT.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n');print(json.dumps(out,indent=2,sort_keys=True));raise SystemExit(0 if out['passed'] else 1)
