#!/usr/bin/env python3
"""Verify critical specializations and permutation shadow of quartic root monodromy."""
from hashlib import sha256
from pathlib import Path
import json
import sympy as s
ROOT=Path(__file__).resolve().parents[3];PACKET=ROOT/'research/voevodsky/global_quartic_root_monodromy_has_two_repeated_collision_types.md';DISC=ROOT/'research/voevodsky/results/global_quartic_discriminant_and_path_gate.json';AUTO=ROOT/'research/voevodsky/results/quartic_automorphism_obstruction.json';RESULT=ROOT/'research/voevodsky/results/global_quartic_root_monodromy.json';t,x,y,E=s.symbols('t x y E',nonzero=True);h=x**2+y**2-(E-x-y)**2;F=s.expand(x**2*t**4-h*t**2+y**2);D=s.factor(s.discriminant(x**2*s.Symbol('u')**2-h*s.Symbol('u')+y**2,s.Symbol('u')));critical=[0,2*x,2*y,2*(x+y)];special=[s.factor(F.subs(E,c)) for c in critical];target=[(x*t**2+y)**2,(x*t**2-y)**2,(x*t**2-y)**2,(x*t**2+y)**2];# permutation on labels (+,+),(+,-),(-,+),(-,-)
p=(1,0,3,2)
def compose(a,b):return tuple(a[b[i]] for i in range(4))
power=(0,1,2,3)
for _ in range(4):power=compose(p,power)
disc=json.loads(DISC.read_text(encoding='utf-8'));auto=json.loads(AUTO.read_text(encoding='utf-8'));text=PACKET.read_text(encoding='utf-8');checks={'discriminant_exact':s.expand(D+E*(2*x-E)*(2*y-E)*(2*x+2*y-E))==0,'root_product':s.factor(y**2/x**2)==y**2/x**2,'critical_specializations':all(s.expand(a-b)==0 for a,b in zip(special,target)),'double_transposition':p==(1,0,3,2),'fourfold_product_identity':power==(0,1,2,3),'prior_critical_values':disc['critical_values']==['0','2x','2y','2(x+y)'],'automorphism_prior':auto['checks']['reciprocity'],'middle_order_changes':s.simplify((2*x-2*y).subs({x:y,y:x},simultaneous=True)+(2*x-2*y))==0,'permutation_insufficient':'root permutations alone do not determine the integral Picard--Lefschetz matrices' in text,'picard_lift_missing':'unresolved part is precisely the braid-to-integral-Picard lift' in text};checks={k:bool(v) for k,v in checks.items()};result={'schema':'marici.voevodsky.global-quartic-root-monodromy.v1','packet_sha256':sha256(PACKET.read_bytes()).hexdigest(),'discriminant_result_sha256':sha256(DISC.read_bytes()).hexdigest(),'automorphism_result_sha256':sha256(AUTO.read_bytes()).hexdigest(),'critical_specializations':[str(q) for q in special],'puncture_permutation':[2,1,4,3],'collision_types':{'negative':['0','2(x+y)'],'positive':['2x','2y']},'checks':checks,'passed':all(checks.values()),'disposition':{'root_permutation_monodromy':'computed','middle_chamber_hurwitz_exchange':'identified','integral_Picard_Lefschetz_lift':'missing'}};RESULT.write_text(json.dumps(result,indent=2)+'\n',encoding='utf-8');print(json.dumps({'passed':result['passed'],'checks':checks,'disposition':result['disposition']}));raise SystemExit(0 if result['passed'] else 1)
