#!/usr/bin/env python3
"""Verify the full two-wall symmetry representation on the extended target."""
from hashlib import sha256
from pathlib import Path
import json
import sympy as s
ROOT=Path(__file__).resolve().parents[3];PACKET=ROOT/'research/voevodsky/extended_target_carries_the_full_two_wall_symmetry_group.md';RESULT=ROOT/'research/voevodsky/results/extended_target_two_wall_symmetry.json';INC=ROOT/'research/benincasa/enhanced-conductor-unimodular-gluing.json';ACT=ROOT/'research/benincasa/orientation-twisted-conductor-rees-intertwiner.json';TARGET=ROOT/'research/aspect/contracts/relative-cech-de-rham-interferometer.v1.json'
g=json.loads(INC.read_text(encoding='utf-8'));a=json.loads(ACT.read_text(encoding='utf-8'));b=json.loads(TARGET.read_text(encoding='utf-8'));Phi=s.Matrix(g['Phi_exc']);D=s.Matrix(b['residue_map']);Dext=s.Matrix.hstack(D,Phi[:,0],Phi[:,2]);P=s.Matrix([[0,0,0,1],[0,1,0,0],[1,0,0,-1],[0,0,1,-1]]);Te=s.Matrix([[0,0,1,0],[0,0,0,1],[1,0,0,0],[0,1,0,0]]);Td=s.Matrix([[0,1,0,0],[1,0,0,0],[0,0,0,1],[0,0,1,0]]);Ts=s.Matrix([[1,0,0,0],[0,0,1,0],[0,1,0,0],[0,0,0,1]]);Ae=P*Te*P.inv();Ad=P*Td*P.inv();As=P*Ts*P.inv();De=s.diag(*a['enhanced_character_action']['epsilon_flip']);Dd=s.diag(*a['enhanced_character_action']['delta_flip']);S=s.Matrix([[0,1,0],[1,0,0],[0,0,1]]);z=s.Matrix([1,1,0,0]);checks={'transported_epsilon_exact':Ae==s.Matrix([[0,1,0,0],[1,0,0,0],[1,-1,0,1],[1,-1,1,0]]),'transported_delta_exact':Ad==s.Matrix([[1,0,0,1],[1,0,1,0],[-1,1,0,-1],[0,0,0,-1]]),'root_involutions':Ae**2==s.eye(4) and Ad**2==s.eye(4),'root_swaps_commute':Ae*Ad==Ad*Ae,'wall_conjugates_roots':As*Ae*As==Ad,'ambient_intertwiners':Ae*P==P*Te and Ad*P==P*Td,'differential_intertwiners':Dext*Ae==De*Dext and Dext*Ad==Dd*Dext and Dext*As==S*Dext,'closed_line_fixed':Ae*z==z and Ad*z==z and As*z==z and Dext*z==s.zeros(3,1),'physical_gate_retained':'construction of the contour/readout map' in PACKET.read_text(encoding='utf-8')};checks={k:bool(v) for k,v in checks.items()}
result={'schema':'marici.voevodsky.extended-target-two-wall-symmetry.v1','packet_sha256':sha256(PACKET.read_bytes()).hexdigest(),'source_digests':{'incidence':sha256(INC.read_bytes()).hexdigest(),'actions':sha256(ACT.read_bytes()).hexdigest(),'aspect':sha256(TARGET.read_bytes()).hexdigest()},'A_epsilon':[list(map(int,Ae.row(i))) for i in range(4)],'A_delta':[list(map(int,Ad.row(i))) for i in range(4)],'A_site':[list(map(int,As.row(i))) for i in range(4)],'checks':checks,'passed':all(checks.values()),'disposition':{'full_symmetry_closure':'verified integrally','closed_aspect_line':'trivial subrepresentation','support_source_typing':'missing','physical_status':'unverified'}}
RESULT.write_text(json.dumps(result,indent=2)+'\n',encoding='utf-8');print(json.dumps({'passed':result['passed'],'checks':checks,'disposition':result['disposition']}));raise SystemExit(0 if result['passed'] else 1)
