#!/usr/bin/env python3
"""Exact finite-prefix witnesses for the compact-correspondence completion type."""
import hashlib,json,platform
from fractions import Fraction as Q
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];FIX=ROOT/'research/voevodsky/fixtures/completed_incidence_mate_is_compact_correspondence.v1.json';OUT=ROOT/'research/voevodsky/results/completed_incidence_mate_is_compact_correspondence.json';D=json.loads(FIX.read_text());N=10;eta=[Q(1,2**(n*n)) for n in range(1,N+1)]
# e_n are unit Euler vectors; images have norm eta_n. y=(eta_n) has formal preimage (1,1,...).
partial_y_norm2=[sum(x*x for x in eta[:m]) for m in range(1,N+1)];inverse_partial_norm2=[Q(m) for m in range(1,N+1)]
checks={'all_finite_components_nonzero':all(x>0 for x in eta),'singular_values_strictly_decay':all(eta[i+1]<eta[i] for i in range(N-1)),'finite_cutoff_maps_injective':all(x!=0 for x in eta),'no_uniform_lower_bound':eta[-1]<Q(1,10**20),'image_witness_partial_norms_bounded':partial_y_norm2[-1]<1,'preimage_witness_partial_norms_diverge':inverse_partial_norm2[-1]==N,'inverse_norms_grow':all(1/eta[i+1]>1/eta[i] for i in range(N-1)),'mate_typed_noninvertibly':D['mate_modality'].startswith('noninvertible'),'forbidden_promotions_retained':len(D['forbidden_promotions'])==4,'full_mate_still_open':'forward Ward seam' in D['disposition']['remaining_full_mate_gate']}
out={'schema':'marici.voevodsky.completed-incidence-mate-is-compact-correspondence-check.v1','passed':all(checks.values()),'checks':checks,'computed':{'toy_singular_values':[str(x) for x in eta],'image_witness_partial_norm_squared':[str(x) for x in partial_y_norm2],'formal_preimage_partial_norm_squared':[str(x) for x in inverse_partial_norm2],'smallest_prefix_singular_value':str(eta[-1])},'disposition':'Finite mates remain injective and cutoff-natural, but their least singular values collapse. The completed incidence is therefore retained as a compact forward correspondence with no bounded inverse in the Euler topology.','claim_boundary':D['claim_boundary'],'execution_receipt':{'command':'python research/voevodsky/checkers/check_completed_incidence_mate_is_compact_correspondence.py','python':platform.python_version(),'fixture_sha256':hashlib.sha256(FIX.read_bytes()).hexdigest(),'source_sha256':{p:hashlib.sha256((ROOT/p).read_bytes()).hexdigest() for p in D['sources']},'checker_sha256':hashlib.sha256(Path(__file__).read_bytes()).hexdigest()}}
OUT.parent.mkdir(parents=True,exist_ok=True);OUT.write_text(json.dumps(out,indent=2,sort_keys=True)+'\n');print(json.dumps(out,indent=2,sort_keys=True));raise SystemExit(0 if out['passed'] else 1)
