#!/usr/bin/env python3
"""Falsify C1's four-mark image against the frozen physical ET/Cut model."""
import json
from pathlib import Path
R=Path(__file__).resolve().parents[3]
loc=json.loads((R/'research/benincasa/et-cut-nearby-normal-form.json').read_text())
split=json.loads((R/'research/benincasa/total-energy-split-model.json').read_text())
cech=json.loads((R/'research/voevodsky/results/BD_oriented_conductor_cech_chain.json').read_text())
three=json.loads((R/'research/benincasa/three-cut-relative-chain-pairing-certificate.json').read_text())
physical_corner_count=1
cech_support=sum(v!=0 for v in cech['primitive_half_boundary'])
checks={'source_selects_one_physical_real_corner':loc['physical_real_corner']=='(a,b)=(y,x); the other sign corners are occurrence/deck companions','split_packet_selects_one_physical_mark':split['enhanced_points']['physical_marked_collision']=='[-y:-x:1]','local_physical_chain_is_interval':loc['canonical_leray_interval']=='oriented interval [pminus,pplus] fixed by the lower-half-plane E continuation and da wedge db orientation','local_boundary_is_two_endpoint':loc['canonical_boundary_vector']==[-1,1],'global_Cech_candidate_uses_four_marks':cech_support==4,'literal_chain_incidence_is_zero_before_continuation':three['chain_boundary_cut_incidence']==[0,0,0],'support_mismatch':physical_corner_count!=cech_support}
assert all(checks.values()),checks
out={'schema':'marici.voevodsky.C1-physical-corner-support-falsifier.v1','C1':'Gamma_res_BD specializes with multiplicity one to the four-mark primitive half-boundary (1,-1,1,-1).','risky_consequence':'The physical specialization activates all four sign-labelled conductor marks in the checkerboard combination.','frozen_source_result':{'physical_corner_count':physical_corner_count,'physical_corner_convention_A':loc['physical_real_corner'],'physical_corner_convention_B':split['enhanced_points']['physical_marked_collision'],'sign_convention_note':'The two packets use opposite affine sign conventions; each selects one corner.','local_relative_boundary':loc['canonical_boundary_vector'],'companion_status':'the remaining sign corners are occurrence/deck companions'},'candidate_Cech_result':{'half_boundary':cech['primitive_half_boundary'],'support_count':cech_support,'meaning':'global coefficient/vanishing-chain checkerboard across all four marks'},'disposition':'rejected as a source physical-current identification','surviving_geometric_statement':'The four-mark Cech class remains the oriented global coefficient-side vanishing chain.','replacement_physical_problem':'Sew the single physical-corner interval through the marked relative complex and compute its image in the integral e6,v_alg plane.','effect':'The unit logarithmic jump and parity (1,0) remain coefficient-side or conditional predictions; they cease to be established physical scalar readouts.','checks':checks,'passed':True}
(R/'research/voevodsky/results/C1_physical_corner_support_falsifier.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'C1_disposition':out['disposition'],'physical_support':physical_corner_count,'Cech_support':cech_support,'replacement':out['replacement_physical_problem'],'effect':out['effect']}))
