#!/usr/bin/env python3
"""Stack every frozen Cut-corner projection and compute rank/Smith data."""
import json,math
from fractions import Fraction
from pathlib import Path
R=Path(__file__).resolve().parents[3]
c9=json.loads((R/'research/voevodsky/results/C9_mixed_corner_packet_attack.json').read_text())
cyc=json.loads((R/'research/benincasa/results/clifford_e6_cyclic_equivariance.json').read_text())
full=json.loads((R/'research/benincasa/full-rank12-cut-nearby-layers-certificate.json').read_text())
columns=[];labels=[]
for sector in range(3):
 for p in c9['packets']:
  for gen in ('g101','g110','g111_tilde'):
   columns.append(p['projection_e6_v0'][gen]);labels.append(f'sector{sector+1}:{p["corner"]}:{gen}')
# Matrix target rows (e6,v_alg), one column per sourced local generator.
M=[[c[i] for c in columns] for i in range(2)]
def rank(A):
 A=[[Fraction(x) for x in r] for r in A];m=len(A);n=len(A[0]);q=0
 for j in range(n):
  p=next((i for i in range(q,m) if A[i][j]),None)
  if p is None:continue
  A[q],A[p]=A[p],A[q];z=A[q][j];A[q]=[x/z for x in A[q]]
  for i in range(m):
   if i!=q and A[i][j]:z=A[i][j];A[i]=[A[i][k]-z*A[q][k] for k in range(n)]
  q+=1
 return q
r=rank(M);nonzero=[abs(x) for row in M for x in row if x];smith=[math.gcd(*nonzero)] if nonzero else []
# Every pair of columns has zero 2x2 determinant.
minors=[M[0][i]*M[1][j]-M[0][j]*M[1][i] for i in range(len(columns)) for j in range(i+1,len(columns))]
checks={'36_generator_projections':len(columns)==36,'three_cyclic_profiles':full['cyclic_sector_profiles_log_rank_cut_rank_intersection_rank']==[[3,3,1]]*3,'stack_rank_one':r==1,'smith_invariant_unit':smith==[1],'all_two_column_minors_zero':all(v==0 for v in minors),'image_exactly_e6_axis':all(c in ([0,0],[1,0]) for c in columns) and [1,0] in columns,'v_alg_row_zero':all(v==0 for v in M[1]),'cyclic_relational_detector_zero':cyc['detector_values']==[0,0,0]}
assert all(checks.values()),checks
out={'schema':'marici.voevodsky.C10-all-sourced-corner-projection-rank.v1','target_basis':['primitive e6 Betti line','v_alg'],'column_count':len(columns),'column_labels':labels,'stacked_matrix':M,'rank':r,'smith_nonzero':smith,'image':'Z*(1,0)','cokernel':'Z generated by v_alg','maximal_rank_two_minors_unique_values':sorted(set(minors)),'C10':'Two suitably chosen physical iterated discontinuities span the integral plane <e6,v_alg>.','status':'rejected for every pair in the frozen total-energy/Cut corner and cyclic orbit','reason':'All 36 sourced generator projections lie on the primitive e6 axis; every 2x2 minor vanishes.','next_detector_requirement':'a physical operation with an e7,e8,e9 tail proportional to v_alg, likely from a logarithmic mixed column or a different iterated discriminant rather than a Cut corner','checks':checks,'passed':True}
(R/'research/voevodsky/results/C10_all_sourced_corner_projection_rank.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'columns':len(columns),'rank':r,'smith':smith,'image':out['image'],'cokernel':out['cokernel'],'C10':out['status']}))
