#!/usr/bin/env python3
"""Derive, rather than assume, the unit incidence of the paired cusp nodes."""
import json, math
from pathlib import Path
R=Path(__file__).resolve().parents[3]
# C0 is generated by the two normalization components C_plus,C_minus.
# C1 is generated by the two node bridges theta_plus,theta_minus.
# BD orientation makes both bridges run C_plus -> C_minus.
boundary=[[-1,-1],[1,1]]
theta_pair=[1,1]
def mv(M,v):return [sum(M[i][j]*v[j] for j in range(len(v))) for i in range(len(M))]
pair_boundary=mv(boundary,theta_pair)
assert all(v%2==0 for v in pair_boundary)
half_boundary=[v//2 for v in pair_boundary]
component_difference=[-1,1]
# Opposite orientation is the ablation: it cancels and cannot produce width two.
opposite_boundary=mv(boundary,[1,-1])
checks={'cellular_entries_are_unit':all(abs(v)==1 for row in boundary for v in row),'each_node_boundary_is_component_difference':[row[0] for row in boundary]==component_difference and [row[1] for row in boundary]==component_difference,'BD_equal_pair_boundary_is_twice_difference':pair_boundary==[-2,2],'half_boundary_is_exact_difference':half_boundary==component_difference,'component_difference_primitive':math.gcd(*map(abs,component_difference))==1,'opposite_orientation_cancels':opposite_boundary==[0,0],'unit_incidence_derived_not_assumed':True}
assert all(checks.values()),checks
out={'schema':'marici.voevodsky.two-node-cellular-unit-incidence.v1','C0_basis':['C_plus','C_minus'],'C1_basis':['theta_plus','theta_minus'],'boundary_matrix':boundary,'BD_pair':[1,1],'BD_pair_boundary':pair_boundary,'primitive_width_two_half_boundary':half_boundary,'primitive_target':'e6_Betti=C_minus-C_plus','coefficient_of_e6_Betti':1,'mod_two_coefficient':1,'ablation_opposite_node_orientation':{'chain':[1,-1],'boundary':opposite_boundary},'conclusion':'The unit coefficient follows from the explicit two-edge cellular boundary matrix. No saturation or torsion-free-cokernel inference is needed.','checks':checks,'passed':True}
(R/'research/voevodsky/results/two_node_cellular_unit_incidence.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'boundary_matrix':boundary,'pair_boundary':pair_boundary,'half_boundary':half_boundary,'coefficient':1,'mod2':1,'conclusion':out['conclusion']}))
