"""Exact gates for the completed puncture-jet source category."""

import json
import math
import os

import sympy as sp


checks = []


def record(gate, statement, passed, detail):
    checks.append({
        "gate": gate,
        "statement": statement,
        "passed": bool(passed),
        "detail": detail,
    })


z, zb, x, xb = sp.symbols("z zb x xb", nonzero=True)
u = z * zb
K = ((zb - xb) * (1 + zb * x) ** 2
     / ((z - x) * (1 + u) ** 3 * (1 + x * xb)))


# Re-derive the generator from the source Green kernel.
S = (z - x) * (zb - xb) / ((1 + u) * (1 + x * xb))
G = S * sp.log(S)
Gamma = -2 * zb / (1 + u)
D2G = sp.factor(sp.diff(G, z, 2) - Gamma * sp.diff(G, z))
record(
    "SOURCE.generator",
    "the completed category is generated by the source-derived Green shear",
    sp.simplify(D2G - K) == 0,
    "Khat=(zb-xb)(1+zb*x)^2/((z-x)(1+z*zb)^3(1+x*xb))",
)


# Holomorphic source jets have strictly increasing principal-part order.
pole_ok = True
leading = []
for order in range(0, 9):
    jet = sp.diff(K, x, order)
    coefficient = sp.factor(sp.limit((z - x) ** (order + 1) * jet, z, x))
    expected = sp.factor(
        math.factorial(order) * (zb - xb)
        / ((1 + x * zb) * (1 + x * xb))
    )
    pole_ok &= sp.simplify(coefficient - expected) == 0
    leading.append(sp.sstr(coefficient))
record(
    "JET.pole_order",
    "source derivative order r has exact pole order r+1 and nonzero leading germ",
    pole_ok,
    "orders 0..8",
)


# Number of complex multiindices (r,s) with r+s<=J.
dimension_ok = True
strict_ok = True
for punctures in range(1, 8):
    prior = 0
    for jet_order in range(0, 11):
        multiindices = sum(1 for r in range(jet_order + 1)
                           for s in range(jet_order + 1 - r))
        expected = (jet_order + 1) * (jet_order + 2) // 2
        dimension = punctures * multiindices
        dimension_ok &= multiindices == expected
        if jet_order:
            strict_ok &= dimension > prior
        prior = dimension
record(
    "LF.dimension",
    "every bounded jet stage is finite dimensional with triangular multiindex count",
    dimension_ok,
    "punctures 1..7; jet bounds 0..10",
)
record(
    "LF.strict",
    "successive finite jet stages are strict inclusions",
    strict_ok,
    "dimension increases at every stage",
)


# Principal-part ports at distinct labelled punctures form a block identity.
for_count_ok = True
for punctures in range(1, 16):
    ports = sp.eye(punctures)
    for_count_ok &= ports.rank() == punctures
record(
    "SUPPORT.labels",
    "distinct puncture germs retain every labelled source coordinate",
    for_count_ok,
    "principal-part port blocks for 1..15 punctures",
)


# Collision moments: two symmetric labels isolate value and first derivative.
eps = sp.symbols("eps", nonzero=True)
t = sp.symbols("t")
phi = 3 + 5 * t + 7 * t ** 2 + 11 * t ** 3 + 13 * t ** 4
plus = sp.expand(phi.subs(t, eps))
minus = sp.expand(phi.subs(t, -eps))
value_limit = sp.limit((plus + minus) / 2, eps, 0)
jet_limit = sp.limit((plus - minus) / (2 * eps), eps, 0)
record(
    "COLLISION.moments",
    "collision moments retain both value and first-jet records",
    value_limit == phi.subs(t, 0) and jet_limit == sp.diff(phi, t).subs(t, 0),
    "symmetric two-label collision",
)


# A coherent geometric tail is fixed by one coefficient; a free perturbation
# violates the recurrence c_(n+1)=-c_n.
coefficients = [(-1) ** n * math.comb(n + 2, 2) for n in range(21)]
locked = all((n + 1) * coefficients[n + 1] == -(n + 3) * coefficients[n]
             for n in range(20))
perturbed = list(coefficients)
perturbed[9] += 3
unlocked = any((n + 1) * perturbed[n + 1] != -(n + 3) * perturbed[n]
               for n in range(20))
record(
    "COMPLETION.not_product",
    "the physical completion retains coherent tails rather than arbitrary coefficient products",
    locked and unlocked,
    "a one-coordinate perturbation breaks the source recurrence",
)


# Mixed source derivatives commute, so multiindex labels are coherent.
commute_ok = True
for r in range(0, 4):
    for s in range(0, 4):
        left = sp.diff(sp.diff(K, x, r), xb, s)
        right = sp.diff(sp.diff(K, xb, s), x, r)
        commute_ok &= sp.simplify(left - right) == 0
record(
    "JET.commute",
    "source-label jet derivatives commute on the rational generator",
    commute_ok,
    "r,s=0..3",
)


passed = sum(item["passed"] for item in checks)
total = len(checks)
payload = {
    "checker": "completed_physical_source_category_checks.py",
    "strength": "source-typed completed-category definition",
    "passed": passed,
    "total": total,
    "checks": checks,
    "verdict": (
        "The completed physical source is the strict LF union of finite "
        "labelled puncture-jet stages. Its generators and support filtration "
        "are source-derived, collision moments retain jets, and arbitrary "
        "Laurent coefficient products are excluded."
    ),
}

outdir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "results")
os.makedirs(outdir, exist_ok=True)
outpath = os.path.join(outdir, "completed_physical_source_category.json")
with open(outpath, "w", encoding="ascii") as handle:
    json.dump(payload, handle, indent=2, sort_keys=True)
    handle.write("\n")

for item in checks:
    label = "PASS" if item["passed"] else "FAIL"
    print(f"{label} {item['gate']}: {item['statement']} - {item['detail']}")
print(f"SUMMARY {passed}/{total}")

if passed != total:
    raise SystemExit(1)
