#!/usr/bin/env python3
"""Exact fixed-state constructor recurrence for the neutral decoration orbit."""

from __future__ import annotations

import contextlib
import io
import json
from pathlib import Path
import runpy


ROOT = Path(__file__).resolve().parents[3]
SOURCE = ROOT / "research/strominger/checkers/eta_squared_faithful_artin_action_checks.py"
with contextlib.redirect_stdout(io.StringIO()):
    state = runpy.run_path(str(SOURCE))


def multiply(*matrices):
    total = [[int(i == j) for j in range(4)] for i in range(4)]
    for matrix in reversed(matrices):
        total = [[sum(matrix[i][k] * total[k][j] for k in range(4)) for j in range(4)] for i in range(4)]
    return total


def elementary(index, parameter):
    matrix = [[int(i == j) for j in range(4)] for i in range(4)]
    matrix[index][index] = 1 + parameter
    matrix[index][index + 1] = -parameter
    matrix[index + 1][index] = parameter
    matrix[index + 1][index + 1] = 1 - parameter
    return matrix


def rho(word):
    pure = state["abstract_to_pure"](word)
    sigma = state["expand_pure"](pure)
    total = [[int(i == j) for j in range(4)] for i in range(4)]
    for letter in sigma:
        total = multiply(elementary(abs(letter) - 1, 1 if letter > 0 else -1), total)
    return total


def inverse_word(word):
    return tuple(-letter for letter in reversed(word))


def matrix_power(matrix, inverse, exponent):
    atom = matrix if exponent >= 0 else inverse
    total = [[int(i == j) for j in range(4)] for i in range(4)]
    for _ in range(abs(exponent)):
        total = multiply(atom, total)
    return total


def anti_commutator(left, left_inverse, right, right_inverse):
    # rho([a,b]) = rho(b^-1) rho(a^-1) rho(b) rho(a).
    return multiply(right_inverse, left_inverse, right, left)


commutator = state["abstract_commutator"]((1,), (2,))
Z, Zi = rho((3,)), rho((-3,))
X, Xi = rho((1,)), rho((-1,))
Yneg, Yneg_i = rho((-2,)), rho((2,))
C, Ci = rho(commutator), rho(inverse_word(commutator))
right_block = anti_commutator(Z, Zi, Yneg, Yneg_i)
right_block_i = anti_commutator(Yneg, Yneg_i, Z, Zi)

records = []
states = {}
for exponent in range(-3, 4):
    U = matrix_power(C, Ci, exponent)
    V = matrix_power(Ci, C, exponent)
    states[exponent] = (U, V)
    tail = multiply(U, X)
    tail_i = multiply(Xi, V)
    left_block = anti_commutator(Z, Zi, tail, tail_i)
    left_block_i = anti_commutator(tail, tail_i, Z, Zi)
    compressed = anti_commutator(left_block, left_block_i, right_block, right_block_i)

    tail_word = (1,) + (commutator if exponent >= 0 else inverse_word(commutator)) * abs(exponent)
    abstract = state["abstract_commutator"](
        state["abstract_commutator"]((3,), tail_word),
        state["abstract_commutator"]((3,), (-2,)),
    )
    expanded = rho(abstract)
    records.append({
        "exponent": exponent,
        "compressed_equals_expanded": compressed == expanded,
        "state_inverse_exact": multiply(U, V) == [[int(i == j) for j in range(4)] for i in range(4)],
    })

recurrence_records = []
for exponent in range(-3, 3):
    U, V = states[exponent]
    next_u, next_v = states[exponent + 1]
    recurrence_records.append({
        "from": exponent,
        "to": exponent + 1,
        "forward_state_exact": multiply(C, U) == next_u,
        "inverse_state_exact": multiply(Ci, V) == next_v,
    })

gates = {
    "compressed_constructor_matches_all_expanded_words": all(r["compressed_equals_expanded"] for r in records),
    "all_two_sided_states_are_exact": all(r["state_inverse_exact"] for r in records),
    "fixed_forward_update_generates_orbit": all(r["forward_state_exact"] for r in recurrence_records),
    "fixed_inverse_update_generates_orbit": all(r["inverse_state_exact"] for r in recurrence_records),
}
payload = {
    "schema": "marici.strominger.integral_constructor_recurrence_checks.v1",
    "status": "passed" if all(gates.values()) else "failed",
    "classification": "full_orbit_has_a_fixed_two_sided_integral_constructor_recurrence",
    "state_type": "(U_n,V_n)=(C^n,C^-n) in GL(4,Z)^2",
    "update": "(U,V) maps to (CU,C^-1 V)",
    "readout": "nested anti-representation commutator followed by Smith divisors",
    "records": records,
    "recurrence_records": recurrence_records,
    "gates": gates,
    "gate_count": len(gates),
    "passed_gate_count": sum(gates.values()),
    "interpretation": (
        "The complete neutral-decoration orbit is generated by a fixed 32-entry "
        "two-sided integral state. The nonlinear Smith arithmetic is downstream "
        "of an exact local recurrence; no bounded congruence projection is needed "
        "and no expanded source word must be retained."
    ),
}
print(json.dumps(payload, indent=2))
