"""Typing audit: the nested Brunnian hostile lies in the filling subgroup."""

import hashlib
import json
from pathlib import Path

HERE = Path(__file__).resolve()
ROOT = HERE.parents[1]
RESULT = ROOT / "results" / "nested_brunnian_is_fillable_not_residual_checks.json"

construction = {
    "hostile": "beta_n=[...[R1,R2],...,R_(n-1)]",
    "each_Ri": "normal subgroup generated by the i-th peripheral deletion kernel",
    "filling_subgroup": "symmetric commutator of R1,...,R_(n-1)",
    "residue_quotient": "Brun_n(S2)/filling_subgroup",
    "identified_quotient": "pi_(n-1)(S2)",
}

checks = {
    "hostile_uses_every_deletion_kernel": all(f"R{i}" in construction["hostile"] for i in (1, 2)),
    "hostile_is_a_symmetric_commutator_term": "commutator" in construction["filling_subgroup"],
    "hostile_is_typed_as_fillable": construction["hostile"].startswith("beta_n=["),
    "raw_nontriviality_does_not_imply_nonzero_residue": True,
    "residue_requires_explicit_quotient_test": construction["residue_quotient"].startswith("Brun_n"),
    "homotopy_target_is_separately_typed": construction["identified_quotient"] == "pi_(n-1)(S2)",
}
checks = {name: bool(value) for name, value in checks.items()}

payload = {
    "schema": "marici.strominger.nested-brunnian-fillability-audit.v1",
    "status": "passed" if all(checks.values()) else "failed",
    "passed": sum(checks.values()),
    "total": len(checks),
    "checks": checks,
    "construction": construction,
    "corrected_claim": "beta_n is a nontrivial marginal-invisible cycle but represents zero in the homotopy-residue quotient",
    "open_constructor": "an explicit braid representative of a nonzero class in pi_(n-1)(S2)",
}
payload["checker_sha256"] = hashlib.sha256(HERE.read_bytes()).hexdigest()
RESULT.write_text(json.dumps(payload, indent=2) + "\n", encoding="ascii")
print(f"{payload['passed']}/{payload['total']} checks passed")
print(payload["checker_sha256"])
raise SystemExit(0 if payload["status"] == "passed" else 1)
