import json
from fractions import Fraction as Q
from pathlib import Path

M=((0,0,-2,2),(0,0,-2,2),(-2,-2,0,0),(2,2,0,0))
S=(1,1,0,0)
R=(0,0,-1,1)
plus=tuple(S[i]+R[i] for i in range(4))
minus=tuple(S[i]-R[i] for i in range(4))
k1=(1,-1,0,0)
k2=(0,0,1,1)

def mv(v):return tuple(sum(Q(M[i][j])*v[j] for j in range(4)) for i in range(4))
def dot(a,b):return sum(Q(x)*y for x,y in zip(a,b))
def q(v):return dot(v,mv(v))
def scale(c,v):return tuple(c*x for x in v)
checks={
 "positive_eigenline_has_eigenvalue_four":mv(plus)==scale(4,plus) and q(plus)>0,
 "negative_eigenline_has_eigenvalue_minus_four":mv(minus)==scale(-4,minus) and q(minus)<0,
 "radical_has_dimension_two":mv(k1)==(0,0,0,0) and mv(k2)==(0,0,0,0) and k1!=k2,
 "value_and_derivative_axes_are_isotropic":q(S)==0 and q(R)==0,
 "isotropic_axes_pair_nontrivially":dot(S,mv(R))!=0,
 "nondegenerate_quotient_signature_is_one_one":q(plus)>0 and q(minus)<0 and dot(plus,mv(minus))==0,
}
prior=Path(__file__).parents[1]/"results"/"rh_bilateral_mixed_sewing_kernel_audit.json"
source=json.loads(prior.read_text(encoding="utf-8"))
checks["prior_source_matrix_matches_fresh_readback"]=tuple(tuple(row) for row in source["matrix"])==M
result={
 "schema":"marici.strominger.rh_bilateral_mixed_current_krein_signature_audit.v1",
 "status":"passed" if all(checks.values()) else "failed",
 "sources":["research/strominger/results/rh_bilateral_mixed_sewing_kernel_audit.json","research/nima/theta-prime-scale-recursive-clark-repair.md"],
 "verdict":"The bilateral mixed current has exact signature (1,1,0,0): eigenvalue +4 on S+R, eigenvalue -4 on S-R, and a two-dimensional radical generated by the antisymmetric value coordinate and symmetric derivative coordinate. The source value and derivative axes S,R are individually isotropic but pair nontrivially. Thus the current supplies a genuine Pontryagin/Krein plane only after quotienting its radical; it is not a positive completion and it does not yet orient a divisor. The next gate is whether coupling this (1,1) plane to the three-port characteristic creates seam kernels without destroying off-seam invertibility.",
 "checks":checks,"gate_count":len(checks),"passed_gate_count":sum(checks.values()),
 "signature":{"positive":1,"negative":1,"radical":2},
 "eigenvectors":{"positive":list(plus),"negative":list(minus),"radical":[list(k1),list(k2)]}
}
out=Path(__file__).parents[1]/"results"/"rh_bilateral_mixed_current_krein_signature_audit.json"
out.write_text(json.dumps(result,indent=2)+"\n",encoding="utf-8")
print(json.dumps(result,indent=2))
