import contextlib,io,json,runpy
from pathlib import Path
base=Path(__file__).parents[1];checks_dir=Path(__file__).parent
backends=['rh_quarter_source_canonical_monotone_transport.py','rh_quarter_source_capacity_proportional_branching.py','rh_quarter_source_canonical_augmenting_rerouting.py']
with contextlib.redirect_stdout(io.StringIO()):
 for name in backends:runpy.run_path(str(checks_dir/name),run_name='__main__')
mono=json.loads((base/'results'/'rh_quarter_source_canonical_monotone_transport.json').read_text())
local=json.loads((base/'results'/'rh_quarter_source_capacity_proportional_branching.json').read_text())
aug=json.loads((base/'results'/'rh_quarter_source_canonical_augmenting_rerouting.json').read_text())
checks={'all_backends_passed':all(x['status']=='passed' for x in [mono,local,aug]),'same_769_case_scope':mono['case_count']==local['case_count']==aug['case_count']==769,'all_canonical_orders_nonuniversal':all(x['feasible']<769 for x in mono['orders'].values()),'local_kernel_nonuniversal':local['feasible_case_count']<769,'canonical_augmenting_flow_universal':aug['feasible_case_count']==769,'canonical_algorithm_requires_rerouting_somewhere':0<aug['rerouting_case_count']<769}
result={'schema':'marici.strominger.rh_quarter_source_branching_network_governing_audit.v1','status':'passed' if all(checks.values()) else 'failed','verdict':'One governing DPC audit rejects all preregistered canonical monotone couplings and the capacity-proportional local kernel while retaining exact globally coordinated augmenting flow as bounded evidence only. Reverse-edge use characterizes the canonical algorithm and does not exclude every forward-only allocation.','canonical_order_feasible_counts':{k:v['feasible'] for k,v in mono['orders'].items()},'capacity_proportional_feasible_count':local['feasible_case_count'],'canonical_augmenting_feasible_count':aug['feasible_case_count'],'canonical_augmenting_rerouting_count':aug['rerouting_case_count'],'first_local_kernel_failure':local['first_failure'],'first_canonical_rerouting_case':aug['first_rerouting_case'],'excluded_recursive_endpoint_backends':['rh_quarter_endpoint_direct_coupling_obstruction','rh_quarter_endpoint_sign_gauge_obstruction','rh_quarter_endpoint_rectangular_positive_lift_obstruction'],'residual':'No source-derived all-order recurrence for globally coordinated branching weights or augmenting choices is known.','checks':checks}
(base/'results'/'rh_quarter_source_branching_network_governing_audit.json').write_text(json.dumps(result,indent=2)+'\n',encoding='utf-8');print(json.dumps(result,indent=2))
