#!/usr/bin/env python3
"""Audit which constructor capabilities are already generated by the source grammar."""

from __future__ import annotations

import contextlib
import io
import json
from pathlib import Path
import runpy


ROOT = Path(__file__).resolve().parents[3]
SOURCE = ROOT / "research/strominger/checkers/integral_constructor_recurrence_checks.py"
with contextlib.redirect_stdout(io.StringIO()):
    source = runpy.run_path(str(SOURCE))

rho = source["rho"]
inverse_word = source["inverse_word"]
matrix_power = source["matrix_power"]
multiply = source["multiply"]
C, Ci = source["C"], source["Ci"]
commutator = source["commutator"]
I4 = [[int(i == j) for j in range(4)] for i in range(4)]


def concatenate(left, right):
    return tuple(left) + tuple(right)


def source_power(word, exponent):
    atom = tuple(word) if exponent >= 0 else inverse_word(word)
    return atom * abs(exponent)


words = [
    (1,),
    (-2,),
    (1, 2, -1),
    commutator,
    concatenate((3,), commutator),
]

inverse_records = []
for word in words:
    response = rho(word)
    inverse_response = rho(inverse_word(word))
    inverse_records.append({
        "word": list(word),
        "inverse_in_source_grammar": True,
        "response_inverse_exact": multiply(response, inverse_response) == I4,
        "inverse_is_involutive": inverse_word(inverse_word(word)) == word,
    })

power_records = []
for exponent in range(-12, 13):
    word_power = source_power(commutator, exponent)
    power_records.append({
        "exponent": exponent,
        "source_power_matches_matrix_power":
            rho(word_power) == matrix_power(C, Ci, exponent),
        "source_word_length": len(word_power),
    })

bit_records = []
for exponent in [0, 1, 2, 4, 8, 16, 32]:
    U = matrix_power(C, Ci, exponent)
    maximum = max(abs(entry) for row in U for entry in row)
    bit_records.append({
        "exponent": exponent,
        "matrix_coordinate_count": 16,
        "max_entry_bit_length": max(1, maximum.bit_length()),
        "source_word_length": len(source_power(commutator, exponent)),
    })

hostile_monoid = {
    "generators": ["x", "y", "z"],
    "constructors": ["identity", "concatenation"],
    "inverse_constructor": False,
    "negative_grade_constructible": False,
    "classification": "does_not_generate_the_same_Z_orbit",
}

gates = {
    "inverse_is_generated_by_the_free_group_source": all(
        r["response_inverse_exact"] and r["inverse_is_involutive"]
        for r in inverse_records
    ),
    "integer_power_is_generated_by_repeated_source_composition": all(
        r["source_power_matches_matrix_power"] for r in power_records
    ),
    "fixed_coordinate_count_is_not_fixed_bit_storage":
        bit_records[-1]["max_entry_bit_length"] > bit_records[1]["max_entry_bit_length"],
    "removing_inverse_changes_the_constructible_orbit":
        not hostile_monoid["negative_grade_constructible"],
}

payload = {
    "schema": "marici.strominger.source_grammar_capability_checks.v1",
    "status": "passed" if all(gates.values()) else "failed",
    "classification": "magnetic_source_grammar_collapses_the_authority_hierarchy_to_a_resource_hierarchy",
    "inverse_records": inverse_records,
    "power_records": power_records,
    "bit_records": bit_records,
    "hostile_monoid": hostile_monoid,
    "gates": gates,
    "gate_count": len(gates),
    "passed_gate_count": sum(gates.values()),
    "interpretation": (
        "The free-group source already generates inversion and every integral "
        "power. The 0/1/2 retained-matrix presentations therefore do not differ "
        "in source authority on this orbit. They differ in constructor depth, "
        "retained coordinates, and integer bit cost."
    ),
}
print(json.dumps(payload, indent=2))
