"""Generate a Three.js CSS3D viewer for the SCC RH net."""
import json
from pathlib import Path
from rh_net_state_compiler import compile_rh_net_state
def render_rh_net(c):
 r=compile_rh_net_state(c)
 if not r.get("passed"):raise ValueError(str(r))
 data=json.dumps({"contract":c,"report":r},separators=(",",":")).replace("</","<\\/")
 return '''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>SCC RH coherence net · Three.js</title>
<style>:root{color-scheme:dark;font-family:Inter,system-ui;background:#071117;color:#e9f0f3}*{box-sizing:border-box}body{margin:0;display:grid;grid-template-rows:auto 1fr;height:100vh}header{padding:15px 20px;border-bottom:1px solid #20333d;display:flex;justify-content:space-between;align-items:end}h1{margin:0;font-size:25px}p{color:#9db0b9;margin:4px 0}main{min-height:0;display:grid;grid-template-columns:1fr 330px}#scene{position:relative;overflow:hidden}.css3d-root{position:absolute!important;inset:0}aside{border-left:1px solid #20333d;padding:16px;background:#0a161d;overflow:auto}.controls{display:flex;gap:6px;flex-wrap:wrap}button{border:1px solid #36505c;background:#10232d;color:#d7e5ea;padding:7px;border-radius:7px;cursor:pointer}button.active{background:#244653}.cell{width:230px;min-height:76px;padding:10px;border:2px solid var(--color);border-radius:7px;background:#0b1a22;color:#eaf4f7;box-shadow:0 6px 15px #0009;text-align:left;cursor:grab;touch-action:none}.cell.dragging{cursor:grabbing;transform:scale(1.08)}.cell:hover,.cell.selected{transform:scale(1.06);box-shadow:0 0 18px var(--color)}.cell small,.cell code{display:block;color:#9db0b9;font:10px ui-monospace;white-space:normal}.cell.muted,.link.muted{opacity:.06}.cell.frontier{border-width:4px;box-shadow:0 0 18px #ffbd59}.link{height:3px;background:transparent;opacity:0!important;transform-origin:center;pointer-events:auto}#detail{border:1px solid #29414c;border-radius:8px;padding:12px;font:12px ui-monospace;white-space:pre-wrap}code{color:#b9d7ff;white-space:pre-wrap}.good{color:#42d392}.bad{color:#ff8996}@media(max-width:800px){main{grid-template-columns:1fr;grid-template-rows:58vh auto}aside{border-left:0}}</style>
<script type="importmap">{"imports":{"three":"https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js","three/addons/":"https://cdn.jsdelivr.net/npm/three@0.180.0/examples/jsm/","d3-force-3d":"https://cdn.jsdelivr.net/npm/d3-force-3d@3/+esm"}}</script></head>
<body><header><div><h1>SCC · RH coherence net</h1><p>Orbit, zoom, filter, inspect, and simulate constructor admission.</p></div><span id="status"></span></header><main><div id="scene"><div id="guide" style="position:absolute;z-index:20;top:14px;left:14px;width:285px;padding:12px 14px;border:1px solid #29414c88;border-radius:9px;background:#071117c9;color:#8197a2;font-size:11px;line-height:1.45;pointer-events:none;backdrop-filter:blur(5px)"><section><strong style="color:#a8bac2">How to read this graph</strong><div>Cards are constructors. Green cells are source-derived; cyan cells are algebraically established without source-realization authority. Small left sockets are typed auxiliary inputs; the larger right socket is the principal output. Matching cable colors carry the same mathematical type. Amber outlines mark the exact admissible frontier.</div></section><section style="margin-top:9px"><strong style="color:#a8bac2">How to interact with this graph</strong><div>Drag a card to perturb the elastic net; release it to settle. Drag empty space to orbit, scroll to zoom, click a card to inspect it, and use the right-hand filters or construction simulator.</div></section></div></div><aside><div class="controls" id="filters"><button class="active" data-v="all">all</button><button data-v="source">source</button><button data-v="algebraic">algebraic</button><button data-v="frontier">frontier</button><button data-v="coherence">coherence</button><button data-v="domain">domain</button><button data-v="analysis">analysis</button><button data-v="identification">identification</button></div><h3>Selection</h3><div id="detail">Select a cell.</div><p><button id="toggle" disabled>Construct selected</button> <button id="reset">Reset</button></p><div id="gate">Simulation is local; contract unchanged.</div><h3>Composite-path control</h3><code id="control"></code></aside></main>
<script id="payload" type="application/json">'''+data+'''</script><script type="module">
import * as THREE from "three";import{CSS3DRenderer,CSS3DObject}from"three/addons/renderers/CSS3DRenderer.js";import{OrbitControls}from"three/addons/controls/OrbitControls.js";
import{forceSimulation,forceLink,forceManyBody,forceCenter,forceCollide}from"d3-force-3d";
const payload=document.querySelector("#payload"),status=document.querySelector("#status"),filters=document.querySelector("#filters"),detail=document.querySelector("#detail"),toggle=document.querySelector("#toggle"),reset=document.querySelector("#reset"),gate=document.querySelector("#gate"),control=document.querySelector("#control");
const D=JSON.parse(payload.textContent),N=D.contract.constructors,B=Object.fromEntries(N.map(x=>[x.id,x])),IN=D.report.interaction_net,AG=new Map(IN.agents.map(x=>[x.id,x])),W=IN.wires,orig=new Set(N.filter(x=>x.status==="constructed").map(x=>x.id));let built=new Set(orig),pick=null,mode="all";
function wireColor(t){let h=[...t].reduce((a,c)=>(a*31+c.charCodeAt(0))%360,0);return "hsl("+h+" 78% 64%)"}
const co=new Set(["typed_three_way_associator","left_unitor","right_unitor","four_input_pentagon_cocycle_coherence","triangle_unit_associator_coherence","completion_stable_frontier_coherence"]);
function layer(x){if(orig.has(x))return B[x].authority_class==="algebraic_derived_nonrealization"?"algebraic":"source";if(["type_fiber_adams_composition","endpoint_operator_attachment","archimedean_determinant_operator_lift"].includes(x))return"frontier";if(x.startsWith("overlap_")||co.has(x))return"coherence";if(/nine_operation|naturality|sewing|fourier_transport|determinant_line/.test(x))return"domain";if(x.includes("margin"))return"analysis";return"identification"}function frontier(){return new Set(N.filter(x=>!built.has(x.id)&&x.depends_on.every(y=>built.has(y))).map(x=>x.id))}
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(42,1,1,8000),host=document.querySelector("#scene");camera.position.set(0,0,2800);const glRenderer=new THREE.WebGLRenderer({alpha:true,antialias:true});glRenderer.domElement.style.cssText="position:absolute;inset:0;z-index:2;pointer-events:none";host.append(glRenderer.domElement);const renderer=new CSS3DRenderer();renderer.domElement.className="css3d-root";renderer.domElement.style.zIndex="1";host.append(renderer.domElement);scene.add(new THREE.HemisphereLight(0xb9d9ff,0x17202a,2.2));const keyLight=new THREE.DirectionalLight(0xffffff,3.4);keyLight.position.set(800,1100,1600);scene.add(keyLight);const orbit=new OrbitControls(camera,renderer.domElement);orbit.enableDamping=true;orbit.minDistance=500;orbit.maxDistance=6500;
const objects=new Map(),cardMasks=new Map(),positions=new Map(),links=[];const maskGeometry=new THREE.PlaneGeometry(240,112),maskMaterial=new THREE.MeshBasicMaterial({colorWrite:false,depthWrite:true,depthTest:true,side:THREE.DoubleSide});const colors={source:"#42d392",algebraic:"#38d6e8",frontier:"#ffbd59",coherence:"#65a7ff",domain:"#b68cff",analysis:"#e96b78",identification:"#fff"};
const layoutNodes=N.map((n,i)=>({id:n.id,x:Math.cos(i*2.399)*480,y:Math.sin(i*1.713)*480,z:Math.sin(i*2.399)*480})),layoutLinks=W.map(w=>({source:w.source_agent,target:w.target_agent,strong:/comparison|associator|unitor|witness/.test(w.wire_type),wire_type:w.wire_type}));
let seed=117;const random=()=>((seed=Math.imul(48271,seed)%2147483647)&2147483647)/2147483647;
const simulation=forceSimulation(layoutNodes,3).randomSource(random).force("link",forceLink(layoutLinks).id(d=>d.id).distance(d=>d.strong?210:285).strength(d=>d.strong?.82:.36)).force("charge",forceManyBody().strength(-780)).force("collision",forceCollide(145).strength(.9)).force("center",forceCenter(0,0,0)).stop();for(let i=0;i<520;i++)simulation.tick();const layoutById=new Map(layoutNodes.map(n=>[n.id,n]));layoutNodes.forEach(n=>positions.set(n.id,new THREE.Vector3(n.x,n.y,n.z)));
function describe(n){let m=n.depends_on.filter(x=>!built.has(x));detail.textContent=n.id+"\\n\\nlayer: "+layer(n.id)+"\\nauthority: "+n.authority_class+"\\nsource: "+(n.source_locator||"not supplied")+"\\n\\ndependencies:\\n"+(n.depends_on.join("\\n")||"none")+"\\n\\nmissing:\\n"+(m.join("\\n")||"none");toggle.disabled=orig.has(n.id);toggle.textContent=built.has(n.id)?"Reopen selected":"Construct selected"}
function describeWire(w,el,hit){document.querySelectorAll(".link").forEach(x=>{x.style.opacity=".25";x.style.height="10px"});document.querySelectorAll(".wire-handle").forEach(x=>x.style.transform="scale(1)");el.style.opacity="1";el.style.height="15px";hit.style.transform="scale(1.65)";detail.textContent="TYPED WIRE\\n\\n"+w.id+"\\n\\nsource agent: "+w.source_agent+"\\nprincipal source port: "+w.source_port+"\\n\\ntarget agent: "+w.target_agent+"\\nauxiliary target port: "+w.target_port+"\\n\\ntransported type: "+w.wire_type+"\\nport discipline: principal output → auxiliary input\\ntyping authority: "+IN.typing_authority;toggle.disabled=true}
function behindCard(p){return p.clone().add(p.clone().sub(camera.position).normalize().multiplyScalar(24))}
function clearSelection(){document.querySelectorAll(".selected").forEach(x=>x.classList.remove("selected"));document.querySelectorAll(".link").forEach(x=>{x.style.opacity=".06";x.style.height="10px"});document.querySelectorAll(".wire-handle").forEach(x=>x.style.transform="scale(1)");for(const l of links){l.tube.material.emissiveIntensity=.14;l.glow.material.opacity=0}pick=null;detail.textContent="Select a cell or typed wire.";toggle.disabled=true;toggle.textContent="Construct selected"}
for(const n of N){let e=document.createElement("button"),a=AG.get(n.id),dot=p=>"<i style='display:inline-block;width:12px;height:12px;border-radius:50%;margin:3px;background:"+wireColor(p.type)+";box-shadow:0 0 8px "+wireColor(p.type)+"' title='"+p.role+" · "+p.type+" · "+(p.label||p.id)+"'></i>";e.className="cell";e.style.setProperty("--color",colors[layer(n.id)]);e.innerHTML="<b>"+n.id+"</b><small>"+layer(n.id)+" · "+n.authority_class+"</small><code>"+(n.source_locator||"formal slot")+"</code><span style='display:flex;border-top:1px solid #29414c;margin-top:6px;padding-top:4px'>"+a.auxiliaries.map(dot).join("")+"<small style='margin:auto'>aux → principal</small>"+dot(a.principal)+"</span>";e.onclick=()=>{clearSelection();e.classList.add("selected");pick=n.id;describe(n)};let o=new CSS3DObject(e);o.position.copy(positions.get(n.id));e.addEventListener("pointerdown",ev=>beginDrag(ev,n,o));scene.add(o);objects.set(n.id,o);const mask=new THREE.Mesh(maskGeometry,maskMaterial);mask.position.copy(o.position);mask.renderOrder=-10;scene.add(mask);cardMasks.set(n.id,mask)}
for(const w of W){let a=behindCard(positions.get(w.source_agent)),b=behindCard(positions.get(w.target_agent)),v=new THREE.Vector3().subVectors(b,a),mid=a.clone().add(b).multiplyScalar(.5),el=document.createElement("div"),hit=document.createElement("button"),color=new THREE.Color(wireColor(w.wire_type)),tube=new THREE.Mesh(new THREE.CylinderGeometry(6,6,1,18),new THREE.MeshStandardMaterial({color,metalness:.92,roughness:.2,emissive:color,emissiveIntensity:.14})),glow=new THREE.Mesh(new THREE.CylinderGeometry(13,13,1,18),new THREE.MeshBasicMaterial({color,transparent:true,opacity:0,depthWrite:false,blending:THREE.AdditiveBlending})),pickTube=new THREE.Mesh(new THREE.CylinderGeometry(20,20,1,10),new THREE.MeshBasicMaterial({transparent:true,opacity:0,depthWrite:false}));el.className="link";el.style.width=v.length()+"px";el.style.height="10px";el.style.opacity=".06";el.style.cursor="pointer";el.title=w.source_port+" → "+w.target_port+" · "+w.wire_type;hit.className="wire-handle";hit.textContent="●";hit.style.cssText="width:28px;height:28px;padding:0;border-radius:50%;color:"+wireColor(w.wire_type)+";background:#071117e8;border:2px solid "+wireColor(w.wire_type)+";box-shadow:0 0 12px "+wireColor(w.wire_type)+";cursor:pointer;font-size:15px;z-index:10000";hit.title="Inspect wire · "+w.wire_type;const selectWire=()=>{for(const l of links){l.tube.material.emissiveIntensity=.14;l.glow.material.opacity=0}tube.material.emissiveIntensity=1.1;glow.material.opacity=.48;describeWire(w,el,hit)},select=ev=>{ev.preventDefault();ev.stopPropagation();selectWire()};tube.userData.selectWire=selectWire;pickTube.userData.selectWire=selectWire;el.onclick=select;hit.onclick=select;let o=new CSS3DObject(el),h=new CSS3DObject(hit);o.position.copy(mid);h.position.copy(mid);tube.position.copy(mid);glow.position.copy(mid);pickTube.position.copy(mid);o.quaternion.setFromUnitVectors(new THREE.Vector3(1,0,0),v.clone().normalize());tube.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),v.clone().normalize());glow.quaternion.copy(tube.quaternion);pickTube.quaternion.copy(tube.quaternion);tube.scale.set(1,v.length(),1);glow.scale.set(1,v.length(),1);pickTube.scale.set(1,v.length(),1);scene.add(tube);scene.add(glow);scene.add(pickTube);scene.add(o);scene.add(h);links.push({o,hit:h,tube,glow,pickTube,a:w.source_agent,b:w.target_agent,type:w.wire_type})}
const raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();let pointerStart=null;renderer.domElement.addEventListener("pointerdown",ev=>{pointerStart={x:ev.clientX,y:ev.clientY}},true);renderer.domElement.addEventListener("pointerup",ev=>{if(!pointerStart)return;const moved=Math.hypot(ev.clientX-pointerStart.x,ev.clientY-pointerStart.y);pointerStart=null;if(moved>6||ev.target.closest?.(".cell,.wire-handle"))return;const rect=host.getBoundingClientRect();pointer.x=((ev.clientX-rect.left)/rect.width)*2-1;pointer.y=-((ev.clientY-rect.top)/rect.height)*2+1;raycaster.setFromCamera(pointer,camera);const picked=raycaster.intersectObjects(links.map(l=>l.pickTube),false)[0];if(picked){ev.preventDefault();ev.stopPropagation();picked.object.userData.selectWire()}else clearSelection()},true);
function syncPhysics(){for(const n of layoutNodes){objects.get(n.id).position.set(n.x,n.y,n.z);cardMasks.get(n.id).position.set(n.x,n.y,n.z)}for(const l of links){let a=behindCard(objects.get(l.a).position),b=behindCard(objects.get(l.b).position),v=new THREE.Vector3().subVectors(b,a),length=v.length(),mid=a.clone().add(b).multiplyScalar(.5),unit=v.clone().normalize();l.o.position.copy(mid);l.hit.position.copy(mid);l.tube.position.copy(mid);l.glow.position.copy(mid);l.pickTube.position.copy(mid);l.o.element.style.width=length+"px";l.o.quaternion.setFromUnitVectors(new THREE.Vector3(1,0,0),unit);l.tube.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),unit);l.glow.quaternion.copy(l.tube.quaternion);l.pickTube.quaternion.copy(l.tube.quaternion);l.tube.scale.set(1,length,1);l.glow.scale.set(1,length,1);l.pickTube.scale.set(1,length,1)}}
function beginDrag(ev,n,o){ev.preventDefault();ev.stopPropagation();let p=layoutById.get(n.id),sx=ev.clientX,sy=ev.clientY,start=new THREE.Vector3(p.x,p.y,p.z),distance=camera.position.distanceTo(o.position),units=2*distance*Math.tan(THREE.MathUtils.degToRad(camera.fov/2))/Math.max(1,renderer.domElement.clientHeight),right=new THREE.Vector3(1,0,0).applyQuaternion(camera.quaternion),up=new THREE.Vector3(0,1,0).applyQuaternion(camera.quaternion);o.element.classList.add("dragging");orbit.enabled=false;p.fx=p.x;p.fy=p.y;p.fz=p.z;simulation.alphaTarget(.22).restart();o.element.setPointerCapture(ev.pointerId);const move=e=>{let next=start.clone().addScaledVector(right,(e.clientX-sx)*units).addScaledVector(up,-(e.clientY-sy)*units);p.fx=next.x;p.fy=next.y;p.fz=next.z};const end=e=>{o.element.releasePointerCapture(e.pointerId);o.element.removeEventListener("pointermove",move);o.element.removeEventListener("pointerup",end);o.element.removeEventListener("pointercancel",end);o.element.classList.remove("dragging");p.fx=null;p.fy=null;p.fz=null;simulation.alphaTarget(0);orbit.enabled=true};o.element.addEventListener("pointermove",move);o.element.addEventListener("pointerup",end);o.element.addEventListener("pointercancel",end)}
simulation.alpha(.12).alphaDecay(.035).on("tick",syncPhysics).restart();
function paint(){let f=frontier();for(const n of N){let e=objects.get(n.id).element;e.classList.toggle("frontier",f.has(n.id));e.classList.toggle("muted",mode!=="all"&&layer(n.id)!==mode)}for(const l of links){let muted=mode!=="all"&&layer(l.a)!==mode&&layer(l.b)!==mode;l.o.element.classList.toggle("muted",muted);l.hit.element.classList.toggle("muted",muted)}status.textContent=N.length+" cells · "+built.size+" constructed · "+f.size+" frontier"}
filters.onclick=e=>{if(!e.target.dataset.v)return;mode=e.target.dataset.v;filters.querySelectorAll("button").forEach(x=>x.classList.toggle("active",x===e.target));paint()};toggle.onclick=()=>{let m=B[pick].depends_on.filter(x=>!built.has(x));if(!built.has(pick)&&m.length){gate.className="bad";gate.textContent="First failed gate: "+m.join(", ");return}built.has(pick)?built.delete(pick):built.add(pick);gate.className="good";gate.textContent="Accepted locally; frontier recomputed.";paint();describe(B[pick])};reset.onclick=()=>{built=new Set(orig);paint()};control.textContent=JSON.stringify(D.contract.completion_control_contract,null,2);paint();
function resize(){let h=document.querySelector("#scene"),w=h.clientWidth,y=h.clientHeight;renderer.setSize(w,y);glRenderer.setPixelRatio(Math.min(devicePixelRatio,2));glRenderer.setSize(w,y);camera.aspect=w/y;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(document.querySelector("#scene"));function animate(){requestAnimationFrame(animate);orbit.update();syncPhysics();for(const o of objects.values())o.quaternion.copy(camera.quaternion);for(const m of cardMasks.values())m.quaternion.copy(camera.quaternion);for(const l of links){l.hit.quaternion.copy(camera.quaternion);l.hit.position.copy(l.tube.position).lerp(camera.position,.035)}glRenderer.render(scene,camera);renderer.render(scene,camera)}resize();animate();
</script></body></html>'''
def write_rh_net_viewer(source:Path,out:Path):
 c=json.loads(source.read_text(encoding="utf-8"));out.parent.mkdir(parents=True,exist_ok=True);out.write_text(render_rh_net(c),encoding="utf-8");return {"schema":"marici.scc.rh-net-view.v3","passed":True,"output":str(out),"nodes":len(c["constructors"]),"renderer":"three-css3d+d3-force-3d"}
