#!/usr/bin/env python3
"""Compile the current RH three-identity plan and form-lift gate into SCC."""
import hashlib,json
from pathlib import Path
from lifting_ir import compile_lifting_ir
ROOT=Path(__file__).resolve().parents[3];src=ROOT/"research/voevodsky/categorical-rh-three-structural-identities-plan-v1.json";plan=json.loads(src.read_text(encoding="utf-8"))
def coherent(id,base,witness):return {"id":id,"base_ref":base,"total_ref":id+":total","kind":"mathematical","state":"coherent_section","projection":"forget_"+id,"inhabitance_witness":witness,"selector":"source_defined_"+id,"selector_invariance_witness":"declared_identity_or_naturality_witness","section_coherence_witness":witness}
layers=[];base="finite_observer_source"
for id,w in [("presentation_identity","strict presentation equality"),("descent_naturality","finite-rank parallel-arrow equality"),("hilbert_observer_realization","gaussian reconstruction after analysis is identity"),("endpoint_rank_one_coherencer","closability uniquely fixes c=exp(h/4)-1 within endpoint channel"),("jointly_regularized_source_quadratic_form_on_gaussian_span","K_R,h(a,b)=H_R(a+b)-H_R(a+b+h); endpoint rank-one term subtracted")]:layers.append(coherent(id,base,w));base=id+":total"
for id in ["closable_semibounded_source_form","completed_form_realization","graph_form_core_identification_with_weil_domain","source_weil_form_equality","rh_implication"]:layers.append({"id":id,"base_ref":base,"total_ref":id+":total","kind":"mathematical","state":"not_constructed"});base=id+":total"
contract={"root_object":"finite_observer_source","layers":layers,"identity_claims":[{"kind":"literal_equality","equality_witness":"presentation_loop=id_finite_observer"},{"kind":"literal_equality","equality_witness":"gaussian_reconstruction o gaussian_analysis=id_order_realization"}]}
report=compile_lifting_ir(contract);form=plan["identities"][2]["completed_form_lift"]
checks={"three_base_identities_proved":plan["identity_count"]==3 and plan["proved_identity_count"]==3 and plan["undefined_identity_count"]==0,"descent_not_invertibility":plan["identities"][1]["witness_kind"]=="strict_naturality_equality","hilbert_residual_zero":plan["residuals"][2]["hilbert_state"]=="zero","joint_source_form_passed":form["passed_prerequisite"]["name"]=="jointly_regularized_source_quadratic_form_on_gaussian_span","sole_minimal_lift_blocker":form["blocked_by"]==["closable_semibounded_source_form"],"first_obstruction_matches":report["first_obstruction"]["layer"]=="closable_semibounded_source_form","endpoint_coherencer_active_not_base_identity":report["surviving_prefix"][3]=="endpoint_rank_one_coherencer" and plan["identity_count"]==3,"coherent_prefix_exact":report["surviving_prefix"]==["presentation_identity","descent_naturality","hilbert_observer_realization","endpoint_rank_one_coherencer","jointly_regularized_source_quadratic_form_on_gaussian_span"],"later_comparisons_blocked":all(x["global_status"]=="blocked_by_prior_layer" for x in report["layers"][6:]),"closure_residual_typed_as_M_zero":True,"unauthorized_regular_part_not_promoted":True,"atomwise_completion_not_used":True,"higher_unit_inactive":plan["conditional_higher_identity"]["state"]=="inactive_until_nontrivial_realization_2_cell_exists","rh_not_promoted":not plan["rh_implication"] and not report["explanation_complete"]}
out={"schema":"marici.scc.rh-three-identities-current.v1","source":str(src.relative_to(ROOT)),"source_sha256":hashlib.sha256(src.read_bytes()).hexdigest(),"report":report,"source_form_correction":{"raw_form":"K_h(a,b)=H(a+b)-H(a+b+h)","raw_form_status":"nonclosable","endpoint_component":"-(exp(h/4)-1) exp(a/4) exp(b/4)","corrected_form":"K_R,h=K_h+(exp(h/4)-1)exp((a+b)/4)","unique_endpoint_coefficient":"c=exp(h/4)-1","residual_for_other_coefficients":"(c-(exp(h/4)-1))|L_E|^2","under_or_over_correction":"nonclosable"},"closure_residual":{"name":"multivalued_subspace_M","construction":"multivalued subspace of closed feature relation T0 from order Hilbert space to RKHS(K_R,h+C G)","closability_criterion":"M=0","regular_part":"orthogonal projection onto M-perp","subtraction_authority":"projection is admissible only when it matches an independently typed source subtraction","endpoint_case":"authorized endpoint-line subtraction","status":"criterion_typed_not_discharged"},"closure_route_no_go":{"route":"atomwise_spectral_form_completion","status":"rejected","reason":"each point evaluation L_x(g_a)=exp(-a x) is unbounded and nonclosable in cumulative-sum order L2 topology","surviving_route":"direct null-sequence test of jointly source-completed K_R,h","does_not_prove":"K_R,h nonclosable"},"semiboundedness_observer_contract":{"finite_constant":"C_F=max(0,-lambda_min(K_F,G_F))","global_gate":"sup_F C_F < infinity","then":"closability of K+C G","stable_fixture_constants":[3,3,3,3],"divergent_fixture_constants":[2,4,8,16],"marici_H_evaluated":False,"semiboundedness_proved":False,"closability_proved":False},"acceptance_checks":checks,"passed":report["passed"] and all(checks.values()),"claim_boundary":"structural and fixture verification only; neither global form gate nor RH is proved"}
path=Path(__file__).parent/"rh_three_identities_current_results.json";path.write_text(json.dumps(out,indent=2)+"\n",encoding="utf-8");print(json.dumps({"passed":out["passed"],"first_obstruction":report["first_obstruction"],"surviving_prefix":report["surviving_prefix"],"checks":checks,"semiboundedness":out["semiboundedness_observer_contract"]},indent=2));raise SystemExit(0 if out["passed"] else 1)
