#!/usr/bin/env python3
"""Compile the current RH model as three branches over its proved local core."""
import hashlib,json
from pathlib import Path
from lifting_ir import compile_lifting_ir
ROOT=Path(__file__).resolve().parents[3];identity_path=ROOT/"research/voevodsky/categorical-rh-three-structural-identities-plan-v1.json";local_path=ROOT/"research/voevodsky/local-sobolev-weil-tower-plan-v1.json";ident=json.loads(identity_path.read_text(encoding="utf-8"));local=json.loads(local_path.read_text(encoding="utf-8"))
def coh(id,base,w):return {"id":id,"base_ref":base,"total_ref":id+":total","kind":"mathematical","state":"coherent_section","projection":"forget_"+id,"inhabitance_witness":w,"selector":"source_defined_"+id,"selector_invariance_witness":"source_typed","section_coherence_witness":w}
def prefix():
 layers=[];base="source_normalized_RH_problem"
 for id,w in [("presentation_identity","strict"),("finite_rank_descent_naturality","parallel-arrow equality, not inverse"),("hilbert_observer_realization","S o A=id"),("local_sobolev_core","C_c^infinity((-L,L)) into H_0^s((-L,L))"),("local_compact_self_adjoint_operator","bounded compact self-adjoint A_(L,s)"),("local_form_identity","Q_L=<A_(L,s)f,g>_(H^s)")]:layers.append(coh(id,base,w));base=id+":total"
 return layers,base
def branch(id,gate):
 layers,base=prefix();layers.append({"id":gate,"base_ref":base,"kind":"mathematical","state":"not_constructed"});return compile_lifting_ir({"root_object":"source_normalized_RH_problem","layers":layers})
reports={"rh_positivity":branch("rh_positivity","all_L_positivity_by_signed_tail_or_Schur_certificate"),"support_coherence":branch("support_coherence","extension_by_zero_form_naturality"),"gaussian_enrichment":branch("gaussian_enrichment","source_derived_cutoff_or_rigging_comparison")}
checks={"local_completed_form_constructed":local["status"]=="local_completed_form_constructed_global_coherence_open","operators_typed":local["local_objects"]["operator"]=="bounded compact self_adjoint A_(L,s)","rh_gate_is_all_L_positivity":local["local_objects"]["rh_local_condition"]=="A_(L,s)>=0","finite_positive_not_promoted":not local["galerkin"]["finite_positive_compression_proves_positivity"],"negative_eigenvalue_finitely_falsifiable":local["galerkin"]["negative_eigenvalue_finitely_falsifiable"],"gaussian_comparison_absent":not local["gaussian_comparison"]["constructed"],"global_carrier_absent":not local["global_candidate"]["admissibility_proved"],"raw_H_order_closure_not_prerequisite":not local["raw_H_order_closure_is_prerequisite"],"three_branches_compile":all(r["passed"] for r in reports.values()),"branch_obstructions_exact":{k:r["first_obstruction"]["layer"] for k,r in reports.items()}=={"rh_positivity":"all_L_positivity_by_signed_tail_or_Schur_certificate","support_coherence":"extension_by_zero_form_naturality","gaussian_enrichment":"source_derived_cutoff_or_rigging_comparison"},"rh_not_promoted":not local["rh_implication"] and not ident["rh_implication"]}
out={"schema":"marici.scc.current-rh-model.v1","sources":{"identity_plan":{"path":str(identity_path.relative_to(ROOT)),"sha256":hashlib.sha256(identity_path.read_bytes()).hexdigest()},"local_tower":{"path":str(local_path.relative_to(ROOT)),"sha256":hashlib.sha256(local_path.read_bytes()).hexdigest()}},"representation":"branch family over shared coherent prefix; branches are incomparable gates, not one linear dependency chain","reports":reports,"acceptance_checks":checks,"passed":all(checks.values()),"disposition":{"proved":"three structural identities and each local bounded compact self-adjoint A_(L,s)","open":["positivity for every L","extension-by-zero form naturality","Gaussian cutoff/rigging comparison","global carrier admissibility"],"retracted":"raw H-kernel closability on H_ord as RH prerequisite","rh_implication":False}}
path=Path(__file__).parent/"current_rh_model_results.json";path.write_text(json.dumps(out,indent=2)+"\n",encoding="utf-8");print(json.dumps({"passed":out["passed"],"representation":out["representation"],"branch_obstructions":{k:r["first_obstruction"] for k,r in reports.items()},"checks":checks},indent=2));raise SystemExit(0 if out["passed"] else 1)
