"""SCC backend contract for externally checked UniMath/Rocq formalizations."""
import hashlib,re
HEX64=re.compile(r"^[0-9a-f]{64}$");IDENT=re.compile(r"^[A-Za-z_][A-Za-z0-9_]*$")
BASE_IMPORTS=("UniMath.Foundations.All","UniMath.CategoryTheory.Core.Categories","UniMath.CategoryTheory.Core.Functors","UniMath.CategoryTheory.Core.Univalence","UniMath.CategoryTheory.WeakEquivalences.Core","UniMath.CategoryTheory.RezkCompletions.RezkCompletions")
DISPLAYED_IMPORTS=("UniMath.CategoryTheory.DisplayedCats.Core","UniMath.CategoryTheory.DisplayedCats.Total","UniMath.CategoryTheory.DisplayedCats.Univalence","UniMath.CategoryTheory.DisplayedCats.SIP")
BICAT_IMPORTS=("UniMath.Bicategories.Core.Bicat","UniMath.Bicategories.DisplayedBicats.DispBicat","UniMath.Bicategories.RezkCompletions.RezkCompletionOfBicategory")

def fail(gate,reason,**evidence):return {"schema":"marici.scc.unimath-backend.v1","passed":False,"first_failed_gate":gate,"reason":reason,"evidence":evidence}
def _ident(x):return isinstance(x,str) and bool(IDENT.fullmatch(x))
def _obligation(kind,name,unimath_object,depends=()):return {"id":name,"kind":kind,"unimath_object":unimath_object,"depends_on":list(depends),"status":"unproved"}

def compile_unimath_backend(c):
 module=c.get("module");digest=c.get("source_contract_sha256")
 if not _ident(module):return fail("module","module must be a safe Rocq identifier")
 if not isinstance(digest,str) or not HEX64.fullmatch(digest):return fail("source_digest","source contract needs lowercase SHA-256")
 w=c.get("weak_equivalence",{});required=("source_category","target_univalent_category","functor","essential_surjectivity_witness","fully_faithful_witness")
 missing=[x for x in required if not _ident(w.get(x))]
 if missing:return fail("weak_equivalence","Rezk input lacks safe symbolic names",missing=missing)
 obligations=[_obligation("category", "source_category_well_typed","category"),_obligation("univalent_category","target_category_univalent","univalent_category"),_obligation("essential_surjectivity","completion_functor_essentially_surjective","essentially_surjective",("source_category_well_typed","target_category_univalent")),_obligation("full_faithfulness","completion_functor_fully_faithful","fully_faithful",("source_category_well_typed","target_category_univalent")),_obligation("rezk_completion","rezk_completion_constructed","make_rezk_completion",("completion_functor_essentially_surjective","completion_functor_fully_faithful"))]
 imports=list(BASE_IMPORTS);displayed=[]
 for i,d in enumerate(c.get("displayed_layers",[])):
  if not _ident(d.get("name")) or not _ident(d.get("displayed_category")):return fail("displayed_layer","displayed layer needs safe name and category",index=i)
  imports.extend(x for x in DISPLAYED_IMPORTS if x not in imports);oid="displayed_layer_"+d["name"]
  obligations.append(_obligation("displayed_category",oid,"disp_cat",("rezk_completion_constructed",)));displayed.append(d["name"])
  if d.get("require_univalence"):obligations.append(_obligation("displayed_univalence",oid+"_univalent","is_univalent_disp",(oid,)))
  if d.get("require_SIP"):obligations.append(_obligation("structure_identity",oid+"_SIP","SIP",(oid+"_univalent",)))
 for i,q in enumerate(c.get("comparison_squares",[])):
  if not _ident(q.get("name")) or not all(_ident(q.get(k)) for k in ("top","left","right","bottom")):return fail("comparison_square","square needs safe symbolic arrows",index=i)
  obligations.append(_obligation("commutative_square","square_"+q["name"],"functor_composite",("rezk_completion_constructed",)))
 heavy=bool(c.get("requires_bicategories"))
 if heavy:imports.extend(BICAT_IMPORTS);obligations.append(_obligation("bicategorical_coherence","bicategorical_cells_coherent","bicat",()))
 if c.get("observational_quotient"):
  external={"status":"external_to_unimath_backend","reason":"physical readout authority is not generated by categorical formalization","locator":c["observational_quotient"].get("locator")}
 else:external="not_supplied"
 lines=[f"Require Import {x}." for x in imports]+["","Local Open Scope cat.",f"Module {module}.",f"(* SCC source contract SHA-256: {digest} *)","Section CompletionContract.",f"Context ({w['source_category']} : category).",f"Context ({w['target_univalent_category']} : univalent_category).",f"Context ({w['functor']} : functor {w['source_category']} {w['target_univalent_category']}).",f"Context ({w['essential_surjectivity_witness']} : essentially_surjective {w['functor']}).",f"Context ({w['fully_faithful_witness']} : fully_faithful {w['functor']}).",f"Definition SCC_rezk_completion : rezk_completion {w['source_category']} :=",f"  make_rezk_completion {w['target_univalent_category']} {w['functor']} {w['essential_surjectivity_witness']} {w['fully_faithful_witness']}.","End CompletionContract."]
 for d in c.get("displayed_layers",[]):
  lines += [f"Section Displayed_{d['name']}.",f"Context (Base_{d['name']} : univalent_category).",f"Context ({d['displayed_category']} : disp_cat Base_{d['name']}).",f"Context ({d['name']}_univalent : is_univalent_disp {d['displayed_category']}).",f"Definition SCC_total_{d['name']} : univalent_category :=",f"  total_univalent_category (make_disp_univalent_category {d['name']}_univalent).",f"End Displayed_{d['name']}." ]
 for q in c.get("comparison_squares",[]):
  lines += [f"Section Square_{q['name']}.",f"Context (A_{q['name']} B_{q['name']} C_{q['name']} D_{q['name']} : category).",f"Context ({q['top']} : functor A_{q['name']} B_{q['name']}).",f"Context ({q['left']} : functor A_{q['name']} C_{q['name']}).",f"Context ({q['right']} : functor B_{q['name']} D_{q['name']}).",f"Context ({q['bottom']} : functor C_{q['name']} D_{q['name']}).",f"Context ({q['name']}_commutes : functor_composite {q['top']} {q['right']} = functor_composite {q['left']} {q['bottom']}).",f"Definition SCC_square_{q['name']} := {q['name']}_commutes.",f"End Square_{q['name']}." ]
 lines += [f"(* OBLIGATION {o['id']}: {o['unimath_object']} *)" for o in obligations if o['kind'] in ('structure_identity','bicategorical_coherence')]+[f"End {module}."]
 source="\n".join(lines)+"\n"
 return {"schema":"marici.scc.unimath-backend.v1","passed":True,"first_failed_gate":None,"status":"emitted_unchecked","module":module,"source_contract_sha256":digest,"imports":imports,"heavy_bicategory_dependency":heavy,"displayed_layers":displayed,"obligations":obligations,"rocq_skeleton":source,"rocq_skeleton_sha256":hashlib.sha256(source.encode()).hexdigest(),"external_physical_readout":external,"claim_boundary":"emission only; no Rocq kernel check or source/physical authority"}

def verify_unimath_result(compiled,result):
 if not compiled.get("passed"):return fail("compiled_contract","cannot verify a failed emission")
 for k in ("module_sha256","unimath_commit","rocq_version"):
  if not result.get(k):return fail("result_provenance","checked result lacks provenance",missing=k)
 if not HEX64.fullmatch(result["module_sha256"]):return fail("result_provenance","module digest is malformed")
 if result.get("source_contract_sha256")!=compiled["source_contract_sha256"]:return fail("source_drift","checked result targets another source contract")
 if result.get("kernel_checked") is not True:return fail("kernel_check","Rocq kernel check not established")
 theorems=result.get("obligations",{});missing=[o["id"] for o in compiled["obligations"] if theorems.get(o["id"])!="proved"]
 if missing:return fail("formal_obligations","formal obligations remain",missing=missing)
 if result.get("physical_backend_certified") is True:return fail("authority_boundary","UniMath result cannot certify a physical backend")
 return {"schema":"marici.scc.unimath-result.v1","passed":True,"status":"kernel_checked_conditional","module_sha256":result["module_sha256"],"unimath_commit":result["unimath_commit"],"rocq_version":result["rocq_version"],"declared_axioms":result.get("declared_axioms",[]),"proved_obligations":sorted(theorems),"claim_boundary":"formal implication under declared axioms; no physical or source promotion"}
