"""Theorem-gated certifier for a total, confluent and faithfully represented SCC core."""

def fail(gate,reason,**evidence):
    return {"passed":False,"first_failed_gate":gate,"reason":reason,"evidence":evidence}

def lex_decreases(lhs,rhs):
    if not(lhs and len(lhs)==len(rhs) and all(isinstance(x,int) and x>=0 for x in lhs+rhs)):return False
    return lhs>rhs

def compile_universal_core(c):
    if c.get("scope")!="closed_admitted_rule_schema":return fail("scope","certificate must close one admitted rule schema")
    rules=c.get("rules",[])
    if not rules:return fail("termination","no rewrite schemas")
    pairs={}
    for r in rules:
        pair=tuple(r.get("active_pair",[]))
        if len(pair)!=2:return fail("active_pair_typing","rule lacks a binary typed active pair",rule=r.get("id"))
        key=tuple(sorted(pair))
        if key in pairs:return fail("orthogonality","more than one rule for a typed active pair",pair=key,rules=[pairs[key],r.get("id")])
        pairs[key]=r.get("id")
        if not lex_decreases(r.get("lhs_measure"),r.get("rhs_measure")):
            return fail("termination","rule lacks a strict well-founded lexicographic decrease",rule=r.get("id"))
        if r.get("preserves_interface") is not True:return fail("interface_soundness","rewrite changes its typed external interface",rule=r.get("id"))
    for cp in c.get("critical_pairs",[]):
        if not cp.get("join") or not cp.get("higher_coherence_witness"):
            return fail("local_confluence","critical pair has no coherent join",critical_pair=cp.get("id"))
    q=c.get("quotient_category",{});els=q.get("morphisms",[]);identity=q.get("identity");table=q.get("composition",{})
    if not els or identity not in els or len(set(els))!=len(els):return fail("quotient_category","invalid finite morphism carrier")
    def comp(a,b):
        v=table.get(a+","+b)
        if v not in els:raise KeyError((a,b))
        return v
    try:
        for a in els:
            if comp(identity,a)!=a or comp(a,identity)!=a:return fail("category_identity","identity law fails",morphism=a)
        for a in els:
            for b in els:
                for d in els:
                    if comp(comp(a,b),d)!=comp(a,comp(b,d)):return fail("category_associativity","associativity fails",triple=[a,b,d])
    except KeyError as e:return fail("category_closure","composition table is incomplete",pair=list(e.args[0]))
    yoneda={a:[comp(a,x) for x in els] for a in els}
    signatures={}
    for a,row in yoneda.items():signatures.setdefault(tuple(row),[]).append(a)
    collisions=[v for v in signatures.values() if len(v)>1]
    if collisions:return fail("yoneda_faithfulness","regular/Yoneda representation does not separate quotient morphisms",collisions=collisions)
    sector_kernels={}
    for name,rep in c.get("sector_representations",{}).items():
        if set(rep)!=set(els):return fail("sector_totality","sector representation is not defined on every quotient morphism",sector=name)
        groups={}
        for a,v in rep.items():groups.setdefault(str(v),[]).append(a)
        sector_kernels[name]=[sorted(v) for v in groups.values() if len(v)>1]
    return {
      "schema":"marici.scc.universal-interaction-net-core.v1","passed":True,"first_failed_gate":None,
      "termination":{"universal_over_admitted_rules":True,"order":"lexicographic natural-number product","rule_count":len(rules)},
      "confluence":{"universal_over_admitted_rules":True,"orthogonal_active_pairs":True,"critical_pairs_joined":True,"coherence_level":"declared higher witnesses"},
      "faithfulness":{"universal_over_finite_quotient_category":True,"construction":"left regular representable/Yoneda action","signatures":yoneda},
      "sector_kernels":sector_kernels,
      "claim_boundary":"universal means every term and reduction generated by this closed admitted schema; adding a rule or quotient morphism invalidates the certificate until rechecked"
    }
