#!/usr/bin/env python3
"""Resolve whether the planned stage-2 overlap differential is currently typable."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
stage=json.loads((ROOT/'research/benincasa/results/G12_multistage_primitive_complex_stage1.json').read_text())
core=json.loads((ROOT/'research/benincasa/results/filtered_IBP_normal_crossing_core.json').read_text())
four=json.loads((ROOT/'research/benincasa/results/G12_four_component_Hermite_image.json').read_text())
checks={'stage1_is_only_modular':all('prime' in r for r in stage['two_prime_fibers']),'stage1_has_no_char0_basis':'basis' not in stage and 'quotient_matrix' not in stage,'local_overlap_coherence_exists':'pairwise Koszul coherence on transverse normal-crossing charts' in core['constructed_interfaces'],'global_cross_wall_coherence_missing':'global ordering proof preventing cross-wall pole cycling' in core['not_yet_constructed'],'residual_only_given_mod_primes':all('residual_support' in r for r in four['modular_tests']),'no_overlap_to_H1_map':all(k not in stage for k in ('overlap_domain','stage2_matrix','comparison_map'))}
assert all(checks.values()),checks
out={'schema':'marici.benincasa.VC2b-overlap-differential-typing-audit.v1','prospective_action':'VC2b_construct_stage2_overlap_differential','resolution':'--','available':{'local_Koszul_overlap_identity':'H_i H_j+H_j H_i=0','stage1_modular_quotient_dimensions':[r['H1_quotient_dimension'] for r in stage['two_prime_fibers']],'target_modular_residual_support':[r['target_normal_form_support'] for r in stage['two_prime_fibers']]},'missing':['a characteristic-zero presentation/basis of H1=coker(d0)','a source-labelled overlap-primitive domain','a comparison map from overlap primitives to that H1 presentation','integral/exchange transport of the comparison across the two modular fibers'],'reason':'The local Koszul identity does not define a differential into the stage-1 quotient. That quotient is currently materialized only by ranks and target residuals over two finite fields, with no characteristic-zero object or source-labelled overlap comparison.','planner_finding':'VC2b was admitted from VC2_stage1_quotient alone, but it also requires char0_H1_presentation and overlap_domain interfaces.','repair':'Split VC2b into VC2b0_reconstruct_char0_H1_presentation, VC2b1_construct_overlap_domain, and VC2b2_compare_overlap_to_H1.','checks':checks,'passed':True}
d=ROOT/'research/benincasa/results/VC2b_overlap_differential_typing_audit.json';d.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'VC2b':'--','repair':out['repair']}))
