#!/usr/bin/env python3
"""PS1C1a1: inventory the data required for the higher-normal coefficient lift."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
central=json.loads((ROOT/'research/benincasa/central-versus-moving-wall-falsifier.json').read_text());bridge=json.loads((ROOT/'research/benincasa/bridge-face-first-rees-lift.json').read_text());cm=json.loads((ROOT/'research/benincasa/et-cut-nearby-normal-form.json').read_text());one=json.loads((ROOT/'research/benincasa/one-wall-universal-cleared-certificate.json').read_text())
checks={'higher_normal_lift_named_missing':central['classification']['missing_datum']=='higher-normal relative coefficient lift','carrier_lift_exists':bridge['checks']['leading_mixed_residue_has_an_actual_canonical_form_lift'],'coefficient_pushforward_uncomputed':bridge['coefficient_gate'].endswith('complete moving-fiber coefficient pushforward'),'complete_K_normal_expansion_available':'complete_expansion' in cm,'central_primitive_available':one['certificate']['verified_remaining_terms']==0,'moving_and_central_points_distinct':central['exceptional_intersections']['central_wall_b_plus_x']!='r=1'}
assert all(checks.values()),checks
out={'schema':'marici.benincasa.PS1C1a1-higher-normal-lift-executability.v1','prospective_action':'PS1C1a1_higher_normal_relative_coefficient_lift','outcome_contract':{'++':'explicit moving-fiber coefficient primitive satisfies the relative identity through the required normal order','+-':'first normal coefficient is lifted but higher orders remain','-+':'first normal obstruction survives in the relative cokernel','--':'moving-fiber source coefficient packet needed to pose the lift is absent'},'resolution':'--','available':['complete K_E normal expansion','central rational primitive eta101','free rank-one leading carrier Rees line'],'missing':['E-dependent Theta101 numerator in the moving-wall frame','complete moving-fiber coefficient pushforward','declared normal order required by the physical pairing'],'reason':'Carrier geometry and K_E are known, but the coefficient-side moving form to be lifted is not materialized. Translating the central primitive alone is prohibited by the r=0 versus r=+-1 falsifier.','refinement':['PS1C1a1i_materialize_moving_Theta101_coefficient','PS1C1a1ii_first_normal_relative_image_test','PS1C1a1iii_iterate_to_pairing_required_order'],'parent_status':'PS1C remains unresolved; no terminal specialization outcome is inferred.','next':'Materialize the E-dependent Theta101 numerator and wall equations in one exact common frame.','checks':checks,'passed':True};p=ROOT/'research/benincasa/results/PS1C1a1_higher_normal_lift_executability.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'resolution':'--','available':len(out['available']),'missing':len(out['missing']),'next':out['refinement'][0]}))
