#!/usr/bin/env python3
"""PS1M2: audit whether the nearby-cycle packet can be projected to degree 15."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
def load(p):return json.loads((ROOT/p).read_text())
sig=load('research/benincasa/results/PS1M1_Leray_Cech_homology_signature.json');exact=load('research/benincasa/results/G12_exact_degree15_reconstruction.json');near=load('research/benincasa/full-rank12-cut-nearby-layers-certificate.json');cyclic=load('research/benincasa/cyclic-cut-nearby-sewing.json')
projection_keys=('degree15_projection','column_to_nearby_map','nearby_pairing','endpoint_augmentation_map')
checks={'target_signature_typed':sig['resolution']=='++','exact_degree15_vector_available':exact['passed'] and len(exact['solution'])==exact['nonzero_solution_terms'],'nearby_basis_available':near['cut_nearby_algebraic_rank']==3,'cyclic_occurrences_available':len(cyclic['cyclic_residue_orders'])==3,'no_declared_source_target_matrix':all(k not in exact and k not in near and k not in cyclic for k in projection_keys),'common_line_insufficient':near['intersection_rank']==1 and near['strict_equality_of_algebraic_images'] is False}
assert all(checks.values()),checks
out={'schema':'marici.benincasa.PS1M2-nearby-degree15-projection-audit.v1','prospective_action':'PS1M2_project_nearby_cycle_to_degree15','outcome_contract':{'++':'exact degree-15 representative maps to an oriented integral nearby-cycle augmentation','+-':'a rational projection is known but integral normalization remains','-+':'the degree-15 class has zero or incompatible nearby projection','--':'the source-to-nearby projection matrix is absent'},'resolution':'--','available':{'degree15_sparse_terms':exact['nonzero_solution_terms'],'source_columns':exact['ambient_shape'][1],'nearby_rank':near['cut_nearby_algebraic_rank'],'shared_algebraic_line':near['intersection_generator'],'cyclic_sectors':len(cyclic['cyclic_residue_orders'])},'missing':'An indexed linear map from the 6040 degree-15 source columns (and d0 columns) to the oriented cyclic cut-nearby occurrence basis.','reason':'The primitive e6 intersection only identifies one common line. It does not determine the projection or normalization of the 984-term degree-15 representative, so comparing its scalar with the PS1A H0 signature would be underdetermined.','refinement':['PS1M2a_materialize_degree15_to_nearby_column_map','PS1M2b_apply_projection_and_augment'],'next':'Recover the source column dictionary used by exact reconstruction and evaluate every supported column in the cyclic nearby basis.','checks':checks,'passed':True};p=ROOT/'research/benincasa/results/PS1M2_nearby_degree15_projection_audit.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'resolution':'--','source_columns':exact['ambient_shape'][1],'nonzero_terms':exact['nonzero_solution_terms'],'next':out['refinement'][0]}))
