#!/usr/bin/env python3
"""Check whether signed-minor restrictions can precede exact weight reconstruction."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
weighted=json.loads((ROOT/'research/benincasa/results/G12_polynomial_weighted_overlap_span.json').read_text())
base=json.loads((ROOT/'research/benincasa/results/G12_coefficient_overlap_representatives.json').read_text())
endpoints=json.loads((ROOT/'research/benincasa/physical-cycle-endpoint-normal-lifts.json').read_text())
pre=json.loads((ROOT/'research/benincasa/results/VC2g_weighted_overlap_support_boundary_audit.json').read_text())
checks={'weighted_result_modular_only':'Modular span membership' in weighted['qualification'],'minimum_degree_known':weighted['minimum_weight_degree']==15,'six_unweighted_columns_only':len(base['columns'])==6 and all('weight' not in c for c in base['columns']),'endpoint_incidence_available':endpoints['incidence_tangency_checks']==9,'boundary_was_unresolved':pre['relative_boundary']['status']=='unresolved','no_exact_weight_coefficients':all(k not in weighted for k in ('solution','weights','rational_coefficients'))}
assert all(checks.values()),checks
out={'schema':'marici.benincasa.VC2g1-signed-minor-restriction-executability.v1','prospective_action':'VC2g1_signed_minor_boundary_restrictions','resolution':'--','reason':'Signed-minor restriction is a property of the actual degree-15 weighted linear combination. Only modular existence and the six unweighted cofactor columns are available; no exact weights have been reconstructed. Different solutions in the large modular affine fiber can have different endpoint restrictions.','available_boundary_geometry':{'endpoint_faces':['c=0','a=0','b=0'],'incidence_tangency_checks':endpoints['incidence_tangency_checks']},'missing_interface':'exact_weighted_overlap_solution','dependency_correction':'VC2g1 requires VC2f_exact_weighted_overlap_reconstruction. The prior interface-centrality graph incorrectly treated exact reconstruction and boundary audit as independently orderable complementary interfaces.','topology_repair':'add dependency VC2f -> VC2g1; then VC2g1 -> support_boundary_admissible','next_recommendation':'VC2f_exact_weighted_overlap_reconstruction, preceded by a cheap coefficient-height/pivot scout if runtime risk is prioritized','checks':checks,'passed':True};p=ROOT/'research/benincasa/results/VC2g1_signed_minor_restriction_executability.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'resolution':'--','dependency':'VC2f -> VC2g1','next':'VC2f'}))
