#!/usr/bin/env python3
"""Classify logarithmic extension forms on the two-soft homogeneous base."""

import json
from pathlib import Path

import sympy as sp


v = sp.symbols("v")
r0, r2 = sp.symbols("r0 r2")

omega = r0 / v + r2 / (v - 2)
residue_infinity = sp.factor(-r0 - r2)
residue_matrix = sp.Matrix([[1, 1]])
no_infinity_kernel = residue_matrix.nullspace()
primitive = sp.factor(1 / v - 1 / (v - 2))
candidate = sp.factor(1 / (4 * v * (v - 2)))
C2 = -sp.Rational(1, 8)

checks = {
    "logarithmic_space_dimension_two": len((r0, r2)) == 2,
    "no_infinity_kernel_is_one_dimensional": len(no_infinity_kernel) == 1,
    "no_infinity_kernel_is_primitive_opposite_pair": no_infinity_kernel[0] == sp.Matrix([-1, 1]),
    "primitive_is_dlog_ratio": sp.simplify(primitive - sp.diff(sp.log(v / (v - 2)), v)) == 0,
    "primitive_residue_v0": sp.residue(primitive, v, 0) == 1,
    "primitive_residue_v2": sp.residue(primitive, v, 2) == -1,
    "candidate_equals_C2_primitive": sp.simplify(candidate - C2 * primitive) == 0,
}

packet = {
    "schema": "marici.benincasa.soft_logarithmic_ext_line.v1",
    "base": "P1_v",
    "boundary": ["v=0 (X3=0)", "v=2 (X2=0)", "v=infinity"],
    "general_log_form": "r0*dv/v + r2*dv/(v-2)",
    "residue_infinity": str(residue_infinity),
    "no_infinity_constraint": "r0+r2=0",
    "admissible_line_generator": "dlog(v/(v-2))",
    "integral_residue_generator": [1, -1, 0],
    "candidate_scalar_C2": str(C2),
    "checks": checks,
    "verdict": (
        "Simple poles only at the two soft divisors and zero infinity residue "
        "leave a unique logarithmic extension line, generated by dlog(v/(v-2))."
    ),
    "non_identifiability": (
        "Uniqueness of the admissible line does not identify which rank-twelve "
        "extension coordinate carries it; that requires the source transition map."
    ),
}

if not all(bool(value) for value in checks.values()):
    raise SystemExit(f"failed checks: {[key for key, ok in checks.items() if not ok]}")

out = Path(__file__).resolve().parents[1] / "results" / "soft_logarithmic_ext_line.json"
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(json.dumps(packet, indent=2) + "\n", encoding="utf-8")
print(json.dumps(packet, indent=2))
