#!/usr/bin/env python3
"""Audit whether the uniqueness/moduli question opened by PS1 can now be decided."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
def load(p):return json.loads((ROOT/p).read_text())
witness=load('research/benincasa/results/PS1A_alternate_signed_minor_specialization.json');near=load('research/benincasa/full-rank12-cut-nearby-layers-certificate.json');cyclic=load('research/benincasa/cyclic-cut-nearby-sewing.json')
checks={'PS1_witness_exists':witness['resolution']=='++','witness_has_integral_Cech_packet':witness['global_current']['integrality']=='all coefficients integral','nearby_cycle_packet_exists':near['combined_rank']==5 and near['cut_nearby_algebraic_rank']==3,'cyclic_sewing_exists':cyclic['survivors']>0 and len(cyclic['cyclic_residue_orders'])==3,'no_common_homology_signature_in_witness':all(k not in witness for k in ('relative_homology_class','monodromy_signature','intersection_pairing_matrix'))}
assert all(checks.values()),checks
out={'schema':'marici.benincasa.PS1M0-realization-moduli-executability.v1','prospective_action':'PS1M0_realization_moduli_census','outcome_contract':{'++':'all candidate physical realizations are represented in a common relative-homology invariant and classified','+-':'multiple construction packets exist but lack a common comparison invariant','-+':'the PS1A witness is uniquely forced by the available relative category','--':'the moduli question cannot yet be posed'},'resolution':'+-','available':['integral PS1A Leray-Cech witness','full rank-twelve cut-nearby layer packet','cyclic cut-nearby sewing certificate'],'missing':['canonical relative-homology signature of the PS1A current','degree-15 projection of the nearby-cycle packet','common monodromy/intersection pairing used to compare the two'],'interpretation':'PS1 proves existence, not uniqueness. The repository contains enough nearby-cycle structure to define a second candidate route, but not enough typed comparison data to decide whether it is the same realization.','refinement':['PS1M1_encode_Leray_Cech_homology_signature','PS1M2_project_nearby_cycle_to_degree15','PS1M3_compare_realization_classes'],'next':'Encode the admitted PS1A current in a basis that the nearby-cycle packet can also inhabit.','checks':checks,'passed':True};p=ROOT/'research/benincasa/results/PS1M0_realization_moduli_executability.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'resolution':'+-','candidate_packets':2,'missing_invariants':3,'next':out['refinement'][0]}))
