#!/usr/bin/env python3
"""Detect central/moving-wall mismatch before constructing the GM connection."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
claimed=json.loads((ROOT/'research/benincasa/results/PS1C1a_moving_wall_residue_totalization.json').read_text());fals=json.loads((ROOT/'research/benincasa/central-versus-moving-wall-falsifier.json').read_text());dual=json.loads((ROOT/'research/benincasa/log-residue-duality-type-correction.json').read_text())
checks={'claimed_walls_are_central':claimed['relative_fibers']=='(a,b) with moving walls W1:{b+x=0}, W2:{a+y=0}','actual_moving_points_shift':fals['exceptional_intersections']['moving_wall_b_plus_x_minus_E']=='r=1' and fals['exceptional_intersections']['moving_wall_a_plus_y_minus_E']=='r=-1','central_point_is_distinct':fals['exceptional_intersections']['central_wall_b_plus_x']=='r=0','direct_restriction_falsified':fals['falsified_claim']=='central-fiber primitives can be directly restricted to moving-wall exceptional intervals','higher_normal_lift_missing':fals['classification']['missing_datum']=='higher-normal relative coefficient lift','correct_complex_known':dual['correct_complex']['space']=='U_E = S_E minus W_E'}
assert all(checks.values()),checks
out={'schema':'marici.benincasa.PS1C1a-central-moving-wall-correction.v1','prospective_action':'PS1C1b_orientation_twisted_GM_connection_executability','corrected_action':'PS1C1a_moving_wall_residue_totalization','corrected_outcome_contract':{'++':'totalization uses the actual E-moving walls and higher-normal primitive lifts','+-':'central universal residue totalization exists, but moving-wall lift is missing','-+':'central relative totalization fails','--':'relative complex cannot be typed'},'corrected_resolution':'+-','reason':'The admitted packet used b+x=0 and a+y=0. The physical moving walls are b+x-E=0 and a+y-E=0, meeting the exceptional chart at r=1 and r=-1 rather than the central r=0 pole. This is a one-step wall-shift error, not a valid moving-wall totalization.','PS1C1b_executable':False,'missing_interface':'higher_normal_relative_coefficient_lift','next':'PS1C1a1 construct the E/Rees higher-normal primitive lift on U_E=S_E\\W_E, then retry the orientation-twisted connection.','checks':checks,'passed':True};p=ROOT/'research/benincasa/results/PS1C1a_central_moving_wall_correction.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'corrected_outcome':'+-','PS1C1b_executable':False,'next':'PS1C1a1_higher_normal_relative_coefficient_lift'}))
