#!/usr/bin/env python3
"""Compare the faithful labelled observer family with physical cyclic descent."""

import json
from fractions import Fraction
from pathlib import Path


P = [[0, 0, 1], [1, 0, 0], [0, 1, 0]]
L = [[2, -1, -1], [-1, 2, -1], [-1, -1, 2]]
w = [Fraction(1, 4), Fraction(1, 4), Fraction(1, 4)]


def matvec(matrix, vector):
    return [sum(matrix[i][j] * vector[j] for j in range(len(vector))) for i in range(len(matrix))]


def rowvec(vector, matrix):
    return [sum(vector[i] * matrix[i][j] for i in range(len(vector))) for j in range(len(matrix[0]))]


def rank(matrix):
    work = [[Fraction(value) for value in row] for row in matrix]
    rows = len(work)
    cols = len(work[0]) if rows else 0
    pivot_row = 0
    for col in range(cols):
        pivot = next((row for row in range(pivot_row, rows) if work[row][col]), None)
        if pivot is None:
            continue
        work[pivot_row], work[pivot] = work[pivot], work[pivot_row]
        scale = work[pivot_row][col]
        work[pivot_row] = [value / scale for value in work[pivot_row]]
        for row in range(rows):
            if row == pivot_row:
                continue
            factor = work[row][col]
            if factor:
                work[row] = [work[row][j] - factor * work[pivot_row][j] for j in range(cols)]
        pivot_row += 1
    return pivot_row


def dot(left, right):
    return sum(left[i] * right[i] for i in range(len(left)))


# Row invariance cP=c gives two independent equations, hence a one-dimensional
# invariant dual line generated by (1,1,1).
invariance_system = [
    [P[i][j] - (1 if i == j else 0) for i in range(3)]
    for j in range(3)
]

a2_test_vectors = [[0, -1, 1], [1, 0, -1], [-1, 1, 0], [3, -5, 2]]
labelled_packets = {str(vector): matvec(L, vector) for vector in a2_test_vectors}
physical_values = {str(vector): dot(w, vector) for vector in a2_test_vectors}
post_observer_physical_values = {str(vector): dot(w, labelled_packets[str(vector)]) for vector in a2_test_vectors}

checks = {
    "entry_1135_covector_is_cyclic_invariant": rowvec(w, P) == w,
    "cyclic_invariant_dual_line_is_one_dimensional": rank(invariance_system) == 2,
    "physical_covector_annihilates_a2": all(value == 0 for value in physical_values.values()),
    "labelled_observer_remains_faithful_before_descent": all(
        labelled_packets[str(vector)] == [3 * value for value in vector] for vector in a2_test_vectors
    ),
    "physical_descent_annihilates_every_labelled_packet": all(
        value == 0 for value in post_observer_physical_values.values()
    ),
    "physical_covector_annihilates_observer_matrix": rowvec(w, L) == [0, 0, 0],
}

if not all(checks.values()):
    raise SystemExit(f"failed checks: {[name for name, ok in checks.items() if not ok]}")

packet = {
    "schema": "marici.benincasa.physical_cycle_occurrence_descent.v1",
    "cyclic_transport": P,
    "labelled_observer": L,
    "entry_1135_physical_covector": [str(value) for value in w],
    "invariant_dual_dimension": 1,
    "a2_test_vectors": a2_test_vectors,
    "labelled_packets": labelled_packets,
    "physical_values": {key: str(value) for key, value in physical_values.items()},
    "post_observer_physical_values": {
        key: str(value) for key, value in post_observer_physical_values.items()
    },
    "checks": checks,
    "verdict": (
        "The source Bunch-Davies pairing factors through the one-dimensional "
        "cyclic coinvariant readout and annihilates the relational A2 grade. "
        "The labelled observer family is faithful only before physical chart "
        "descent; the frozen source does not promote its three chart rows to "
        "three independent outcome ports."
    ),
}

out = Path(__file__).resolve().parents[1] / "results" / "physical_cycle_occurrence_descent.json"
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text(json.dumps(packet, indent=2) + "\n", encoding="utf-8")
print(json.dumps(packet, indent=2))
