"""Exact Keldysh source-response typing of Bogoliubov Berry connection."""
import json
from fractions import Fraction as Q
from pathlib import Path

A=Q(-8,9)  # i<psi|partial_theta psi>

# theta_c=(theta_+ + theta_-)/2, theta_q=theta_+-theta_-.
# The local geometric influence factor is exp(i A theta_q).
# W=-i log Z therefore has geometric contribution A theta_q.
dW_dtheta_c=Q(0)
dW_dtheta_q=A
assert dW_dtheta_c==0
assert dW_dtheta_q==Q(-8,9)

packet={
 "schema":"marici.bogoliubov-keldysh-source-response.v1",
 "keldysh_coordinates":{"theta_c":"(theta_+ + theta_-)/2","theta_q":"theta_+ - theta_-"},
 "geometric_influence_factor":"Z_geom=exp(i*A_theta*theta_q)",
 "berry_connection_A_theta":"-8/9",
 "equal_source_value":"Z_geom(theta_q=0)=1",
 "common_source_derivative":"dW/dtheta_c=0",
 "difference_source_derivative":"dW/dtheta_q=-8/9",
 "physical_typing":"the generalized force conjugate to the protocol is generated by the quantum-source derivative at theta_q=0",
 "classification":"native in-in source calculus detects the Berry connection as response while preserving Z[J,J]=1; no appended laboratory control is needed",
 "conclusion":"Closed-contour cancellation and physical activation are compatible: the phase vanishes as a diagonal value but survives as the first transverse Keldysh jet. The physical datum is a source-normalized response covector, not a scalar value of the closed trace.",
}
out=Path(__file__).parent/'results'/'bogoliubov-keldysh-source-response.json'
out.write_text(json.dumps(packet,indent=2)+'\n')
print(json.dumps(packet,indent=2))
