#!/usr/bin/env python3
"""DPC capability audit for provenance-preserving Rees elimination."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];B=ROOT/'research/benincasa';N=ROOT/'research/nima';R=B/'results'
prior=json.loads((R/'cosmology_first_missing_arrow_source_generator_gate.json').read_text());assert prior['passed']
engine=(B/'sparse_modular_rank_stream.rs').read_text();caller=(N/'checkers/check_cosmology_p_normal_rank26_rees_census.py').read_text()
checks={'engine_source_available':True,'deterministic_row_stream':"for rows in zip(*samples,check,strict=True)" in caller,'raw_labelled_columns_available':"raw_relations(shifted(o),cols)" in caller,'pivot_rows_retained_in_memory':'pivots.insert(pivot, row)' in engine,'input_row_ids_transmitted':'row_id' in engine,'provenance_combinations_retained':False,'output_contains_only_counts':'relation_ranks' in engine and 'image_ranks' in engine,'arithmetic_is_single_prime_modular':'prime:u32' in engine}
assert checks['deterministic_row_stream'] and checks['pivot_rows_retained_in_memory'] and not checks['input_row_ids_transmitted'] and checks['output_contains_only_counts']
out={'schema':'marici.benincasa.cosmology-rees-labelled-generator-capability-constructor.v1','problem':'decide whether the current Rees computation can directly produce an integral labelled exceptional generator','bold_conjecture':'the existing engine retains enough structure to serialize a labelled generator and verify its boundary and connecting image','rivals':['rank-only interface is irreparable','modular provenance replay suffices','exact or cross-prime provenance reconstruction is additionally required'],'risky_consequences':'if the stream has stable source rows and the reducer can carry combination vectors, modular labelled pivots are recoverable; if only one prime is used, they do not define an integral generator','strongest_falsification_attempt':checks,'exact_residual':'stable rows and pivot rows permit a provenance upgrade, but row identities and combinations are not retained, output is counts only, and single-prime vectors have no integral lift or cross-prime identity','conjecture_disposition':'revised','survivor':'the engine can be extended to emit modular provenance certificates, not an integral source generator from the current receipts','required_protocol_upgrade':['stable row id with relation family, source label, filtration kind, and raw index','carry sparse input-row combination through every reduction','emit pivot row and provenance vector with replay digest','match candidates across primes or use exact arithmetic','verify integral boundary, connecting image, primitiveness, and source labels'],'current_receipts_replayable_to_labelled_generator':False,'modular_provenance_upgrade_constructible':True,'integral_generator_constructed':False,'next_conjecture':'a bounded provenance-carrying reducer reproduces pivots and input combinations exactly and exposes the memory contract for the full engine','next_falsifier':'implement a small exact/modular prototype with replay tests and deliberate corrupted-certificate failure','passed':True};(R/'cosmology_rees_labelled_generator_capability_constructor.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
