#!/usr/bin/env python3
"""PS1C0: audit whether the modified logarithmic operation is frozen-source admissible."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
va2=json.loads((ROOT/'research/voevodsky/results/noncorner_logarithmic_valg_channel.json').read_text());freeze=json.loads((ROOT/'research/conjecture_replay/results/prospective_valg_frontier.json').read_text())
log=va2['operation_families']['logarithmic_mixed_columns'];basis=log['source_basis']
checks={'prospective_VA2_present':any(x['name']=='VA2_alternative_discriminant_census' for x in freeze['actions']),'VA2_was_partial_not_invalid':va2['VA2_resolution']=='+-','source_basis_explicit':basis==['Theta101','Theta110','Theta111_filt'],'primitive_integral_pair':log['smith_nonzero']==[1,1] and abs(log['determinant'])==1,'physical_realization_separately_missing':va2['missing_interface']=='physical_Betti_realization_of_mixed_log_column'}
assert all(checks.values()),checks
out={'schema':'marici.benincasa.PS1C0-modified-operation-source-admissibility.v1','prospective_action':'PS1C0_source_admissibility','outcome_contract':{'++':'candidate operation is explicitly source-derived and integrally primitive','+-':'source relation exists but operation requires carrier modification','-+':'candidate is not source-admissible','--':'source status cannot be typed'},'candidate':'Theta101 (equivalently Theta110) logarithmic mixed column','resolution':'++','established':'The modified logarithmic operation belongs to the frozen source basis and forms a primitive unimodular pair with Theta111_filt. No carrier modification is required to define the algebraic operation.','withheld':'No physical relative-cycle/Leray realization or pairing follows from source admissibility alone. PS1C remains unresolved.','interface_added':'source_admissible_modified_log_operation','next':'PS1C1 construct the physical Betti/Leray realization of Theta101 and test its specialization of the degree-15 algebraic class.','checks':checks,'passed':True};p=ROOT/'research/benincasa/results/PS1C0_modified_operation_source_admissibility.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'resolution':'++','candidate':out['candidate'],'next':out['next']}))
