#!/usr/bin/env python3
"""Finite theorem: global nonmonicity does not kill the principal tau_p line."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];R=ROOT/'research/benincasa/results'
k=json.loads((R/'cosmology_rees_exact_faithful_kernel_lift.json').read_text());t4=json.loads((R/'cosmology_rees_exact_assembled_target_membership.json').read_text());t5=json.loads((R/'cosmology_rees_tau_residue_stabilization.json').read_text());tr=json.loads((R/'cosmology_rees_ambient_quotient_transition.json').read_text())
checks={'exact_global_kernel_nonzero':k['passed'] and k['primitive_content']==1,'tau_A4_nonzero':not t4['membership'],'tau_A5_nonzero':all(x['nonzero'] for x in t5['strongest_falsification_attempt']['comparisons']),'tau_representative_preserved':tr['strongest_falsification_attempt']['target_preserved_exactly']}
assert all(checks.values())
out={'schema':'marici.benincasa.cosmology-rees-tau-line-restriction-vs-global-kernel.v1','problem':'determine whether exact global nonmonicity invalidates finite persistence of the principal tau_p line','claim':'the A4-to-A5 quotient map is globally nonmonic but restricts injectively to the one-dimensional line spanned by tau_p','premises':checks,'derivation':['the primitive integral vector (1,-1,-6,3) is a nonzero global kernel class','tau_p is nonzero in Q_A4','the transition preserves its labelled representative','its image is nonzero in Q_A5','a linear map on a one-dimensional span with nonzero image is injective'],'exact_kernel_vector':k['primitive_integral_coefficients'],'tau_A4_residual_nnz':t4['strongest_falsification_attempt']['exact_residual_nnz'],'tau_A5_residual_nnz':t5['strongest_falsification_attempt']['ambient_five']['residual_nnz'],'result_strength':'finite-cutoff source-typed morphism restricted to a proved one-dimensional subspace','scope':'does not prove global monicity, eventual persistence, a colimit class, a relation-span lift of tau_p, or physical readout','principal_relation_lift_exists':False,'principal_quotient_line_persists_A4_to_A5':True,'passed':True};(R/'cosmology_rees_tau_line_restriction_vs_global_kernel.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
