#!/usr/bin/env python3
"""DPC typed comparison of norm doubling with the principal 2Z obstruction."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];R=ROOT/'research/benincasa/results'
norm=json.loads((R/'cosmology_sign_twist_untwisted_lattice_descent.json').read_text());gate=json.loads((R/'cosmology_quotient_colimit_tau_p_gate.json').read_text());enlarge=json.loads((R/'cosmology_minimal_primitive_source_enlargement.json').read_text());status=json.loads((R/'cosmology_primitive_tau_current_source_envelope_status.json').read_text());assert norm['passed'] and gate['passed'] and enlarge['passed']
assert norm['norm_descent']['logarithmic_correction']=='2*dlog(g)' and enlarge['existing_principal_lattice']=='2Z'
missing=status['missing_arrows'];assert 'weighted specialization into the Gysin coefficient block' in missing and 'projection to (Xi_log,-sigma123)' in missing
out={'schema':'marici.benincasa.cosmology-sign-norm-principal-2Z-comparison.v1','conjecture':'the norm image is the same typed even sublattice as the principal 2Z source','norm_object':{'type':'ordinary meromorphic connection correction on the punctured p divisor','generator':'2*dlog(g)','evenness_origin':'norm from a sign-twisted line'},'principal_object':{'type':'integral Xi_log coefficient lattice in the tau_p target column','lattice':'2Z','required_column':enlarge['required_column'],'evenness_origin':'evaluated principal source generators'},'required_comparison_arrow':'norm correction -> weighted Gysin block -> (Xi_log,-sigma123)','comparison_arrow_constructed':False,'missing_arrows':[x for x in missing if x in ['weighted specialization into the Gysin coefficient block','projection to (Xi_log,-sigma123)','integral physical readout']],'same_parity_is_typed_identification':False,'conjecture_disposition':'falsified as a typed equality','survivor':'two parallel parity obstructions both prevent a primitive unit, but no causal or comparison identification is established','next_conjecture':'an existing weighted specialization maps the norm correction to twice the Xi_log generator','next_falsifier':'find an explicit chain-level specialization and projection, or confirm the required arrows remain absent','passed':True};(R/'cosmology_sign_norm_principal_2Z_comparison.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
