#!/usr/bin/env python3
"""Audit whether the NNMHV source defines the requested Coherent Resolution."""
import json
from pathlib import Path
R=Path(__file__).resolve().parents[2]
law=(R/'nima/coherent-construction-law.md').read_text(encoding='utf-8')
atlas=(R/'nima/coherent-construction-bridge-atlas.md').read_text(encoding='utf-8')
source={'construction_chain':'Gamma=' in law or 'Gamma_n' in law,'pushforward':'Phi_Z' in law,'internal_facet_cancellation':'shared internal facets occur with opposite orientations' in law,'roots':'positive roots' in atlas,'cluster_faces':'commuting square' in atlas and 'Mac Lane pentagon' in atlas,'mobius_operator':'\\Box_d=\\Delta_u\\Delta_v' in atlas,'cutoff_filtration':'newly created shell at cutoff' in atlas}
missing={'named_coherent_resolution': 'Coherent Resolution' not in law and 'Coherent Resolution' not in atlas,'graded_chain_groups':True,'one_typed_differential':True,'signed_relation_cell_boundaries':True,'higher_homotopies':True,'augmentation_of_the_resolution':True,'admissible_quotient':True,'boundary_transport_on_all_generators':True,'arbitrary_n_positroid_compiler':True}
# The source itself states the last item remains open.
assert all(source.values()) and all(missing.values()) and 'arbitrary-`n` history-to-positroid compiler remains open' in law
out={'schema':'marici.benincasa.coherent-resolution-source-authority.v1','authoritative_object':{'name':'Coherent Construction Law','data':'oriented top-dimensional history-cell chain Gamma, positive-cell canonical forms, and pushforward Phi_Z','theorem':'internal facets cancel and the pushed canonical forms sum to Omega'},'sourced_structural_images':source,'requested_CR_fields_absent':missing,'maximal_reconstruction_only':{'degree0_candidate':'history cells / positive-root intervals','degree1_candidate':'endpoint covers and cluster flips','degree2_candidate':'square and pentagon relation cells','operators_not_proved_one_differential':['cellular boundary','Box_d=Delta_u Delta_v'],'filtrations':['cutoff n','root length','AF/Wedderburn shell tower']},'finite_strength':{'n7':'certified cells, canonical forms, permutations, necklaces, rank tables','n8':'20 histories matched coefficientwise to sourced rational positroid cells','arbitrary_n':'open by explicit source statement'},'boundary_transport_test':'not typeable as CR chain map, twisting cochain, cocycle, or obstruction class until CR differential and edge transport maps are supplied','face_coherence':'combinatorial square/pentagon faces are sourced; physical-weight chain identities are not','cohomology':'undefined for the requested physical CR; the separate Z2 sign-line candidate is underdetermined, and if closed on the associahedron is cohomologically trivial because the associahedron is a ball','exact_physical_residual':'-64467252153401672951924968453/53071490355838506213038595387901777500','disposition':'premise failure / missing source-defined Coherent Resolution','repair_contract':['declare graded generators C_k and coefficient ring','give signed d_k with d^2=0','give relation 2-cells and higher homotopies','give filtration and augmentation as chain maps','give boundary-transport maps on every generator','prove compatibility with canonical-form weights','then compute square/pentagon residuals and arbitrary-cutoff compiler'],'passed':True}
p=R/'benincasa/results/coherent_resolution_source_authority.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
