#!/usr/bin/env python3
"""Preregistered finite-cutoff stabilization gate for the tau_p programme."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];R=ROOT/'research/benincasa/results'
# Frozen sufficient gate, declared before extracting the measured series.
criterion={'transition_coherence':True,'target_nonzero_at_each_cutoff':True,'last_two_rank_increments_equal':True,'last_two_residual_support_increments_zero':True,'meaning':'a deliberately strong finite stabilization gate; passing is sufficient to allocate another cutoff but is not a theorem of eventual stabilization'}
a4=json.loads((R/'cosmology_rees_exact_assembled_target_membership.json').read_text());a5=json.loads((R/'cosmology_rees_tau_residue_stabilization.json').read_text());a6=json.loads((R/'cosmology_rees_ambient_transition_coherence.json').read_text())
ranks=[a4['strongest_falsification_attempt']['assembled_rank'],a5['strongest_falsification_attempt']['ambient_five']['rank'],a6['strongest_falsification_attempt']['ambient_six']['rank']];supports=[a4['strongest_falsification_attempt']['exact_residual_nnz'],a5['strongest_falsification_attempt']['ambient_five']['residual_nnz'],a6['strongest_falsification_attempt']['ambient_six']['residual_nnz']];rank_deltas=[ranks[i+1]-ranks[i] for i in range(2)];support_deltas=[supports[i+1]-supports[i] for i in range(2)]
checks={'transition_coherence':a6['strongest_falsification_attempt']['composition_equals_direct_on_A4_relations'],'target_nonzero_at_each_cutoff':(not a4['membership']) and all(x['nonzero'] for x in a5['strongest_falsification_attempt']['comparisons']) and all(x['nonzero'] for x in a6['strongest_falsification_attempt']['comparisons']),'last_two_rank_increments_equal':rank_deltas[0]==rank_deltas[1],'last_two_residual_support_increments_zero':support_deltas==[0,0]};gate_passed=all(checks.values());assert checks['transition_coherence'] and checks['target_nonzero_at_each_cutoff'] and not gate_passed
out={'schema':'marici.benincasa.cosmology-rees-finite-stabilization-criterion.v1','problem':'decide whether finite A4,A5,A6 evidence justifies another brute-force cutoff or colimit language','bold_conjecture':'the coherent finite diagram satisfies a preregistered sufficient stabilization gate','rivals':['stable increments and support justify another cutoff','coherence with continuing growth requires graded analysis','finite persistence already implies a colimit class'],'preregistered_criterion':criterion,'risky_consequences':'both rank increments must agree and target normal-form support must stop growing, in addition to coherence and nonvanishing','strongest_falsification_attempt':{'ambient_cutoffs':[4,5,6],'ranks':ranks,'rank_increments':rank_deltas,'residual_supports':supports,'residual_support_increments':support_deltas,'checks':checks},'exact_residual':'rank increments are 1742 and 2036, while residual supports are 69, 219, and 315; coherence and nonvanishing hold but the sufficient stabilization gate fails','conjecture_disposition':'falsified','gate_passed':gate_passed,'another_bruteforce_cutoff_justified_by_stabilization':False,'colimit_promotion_supported':False,'scope':'failure of a sufficient resource-allocation gate is not proof that eventual stabilization is impossible','next_conjecture':'graded transition-cokernel dimensions explain rank and support growth and determine whether a renormalized stable quotient coordinate exists','next_falsifier':'derive the new-degree relation and quotient contributions from labelled A4,A5,A6 differences; reject any fitted law that fails an exact held-out stratum','passed':True};(R/'cosmology_rees_finite_stabilization_criterion.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
