#!/usr/bin/env python3
"""Exact nonvanishing and kernel test on the pole-2 target-generated line."""
import contextlib,io,json,runpy
from fractions import Fraction as F
from pathlib import Path
HERE=Path(__file__).resolve();base=HERE.with_name('check_cosmology_rees_correct_K_depth_scalar_solve.py')
with contextlib.redirect_stdout(io.StringIO()):h=runpy.run_path(str(base))
g=h['g'];mul=h['mul'];H,Q,target=g['H'],h['Q'],h['target'];one={(0,0):F(1)};R=mul(H,Q)
def pw(a,n):
 r=one
 for _ in range(n):r=mul(r,a)
 return r
def pf(s):
 a,b=s.split('/') if '/' in s else (s,'1');return F(int(a),int(b))
def pull(l,P):
 out={};mx=max(a for a,b in l);my=max(b for a,b in l)
 for i in range(mx+1):
  for j in range(my+1):
   v=sum(c*l.get((i+a,j+b),F(0)) for (a,b),c in P.items())
   if v:out[(i,j)]=v
 return out
def ev(l,f):return sum(l.get(m,F(0))*v for m,v in f.items())
def cert(n):
 x=json.loads((HERE.parents[1]/'results'/f'cosmology_rees_affine_H{n}Q{n}_exact_certificate.json').read_text());return {tuple(q['monomial']):pf(q['coefficient']) for q in x['certificate']}
mu2=pull(cert(2),R);mu3=pull(cert(3),pw(R,2));t2=mul(target,pw(R,3));t3=mul(target,pw(R,4));p2=ev(mu2,t2);p3=ev(mu3,t3);transported=mul(R,t2)==t3
out={'schema':'marici.benincasa.cosmology-rees-affine-R-target-kernel.v1','source_order':2,'target_order':3,'source_target_pairing':str(p2),'target_target_pairing':str(p3),'R_maps_target_representative':transported,'source_class_nonzero':p2!=0,'image_class_nonzero':p3!=0,'kernel_on_source_target_line_dimension':0 if p2!=0 and p3!=0 and transported else None,'conclusion':'the induced R map is injective on the one-dimensional line generated by the order-2 target class','scope':'does not establish injectivity on the full cokernel or nonvanishing at pole orders above three'};(HERE.parents[1]/'results'/'cosmology_rees_affine_R_target_kernel.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
