#!/usr/bin/env python3
"""Localize the 90 failed v-shifted relation rows by source labels."""
import ast,collections,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];R=ROOT/'research/benincasa/results';d=json.loads((R/'cosmology_rees_v_action_a4_a5.json').read_text());xs=d['nonzero_shifted_relations'];keys=[ast.literal_eval(x['row_key']) for x in xs]
outer=collections.Counter(k[0] for k in keys);family=collections.Counter(k[1][0] for k in keys);sector=collections.Counter((k[1][1],k[1][3]) for k in keys);marks=collections.Counter(k[1][2] for k in keys);monomials=collections.Counter(k[1][-1] for k in keys)
rows=[x['row'] for x in xs]
assert len(xs)==90;assert rows==list(range(45,90))+list(range(135,180));assert outer=={'shift2':30,'upper':30,'jet':30};assert family=={'twisted_derivative':90};assert len(marks)==1 and list(marks)==[(1,1,1,1,1)];assert sum(monomials.values())==90
out={'schema':'marici.benincasa.cosmology-rees-v-action-failure-localization.v1','failed_rows':{'count':90,'contiguous_intervals':[[45,89],[135,179]]},'outer_relation_channels':dict(outer),'source_families':dict(family),'sector_counts':{repr(k):v for k,v in sector.items()},'marked_supports':{repr(k):v for k,v in marks.items()},'distinct_monomials':len(monomials),'monomial_multiplicity_values':sorted(set(monomials.values())),'exact_residual':'every failure lies in two 45-row twisted_derivative blocks for sectors (0,1) and (1,1), split equally among shift2, upper, and jet channels; no K-multiplication or q-multiplication row fails','disposition':'v-action incompatibility is localized to the all-five-mark twisted-derivative stratum, not spread across the assembled presentation','interpretation':'the special shifted K coordinate pattern coexists with failure of twisted-derivative naturality; any repaired action must add a coherence correction on this stratum and recheck its square/composition','passed':True};(R/'cosmology_rees_v_action_failure_localization.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
