#!/usr/bin/env python3
"""DPC typing audit for principal tau_p membership in the exact raw-row basis."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];B=ROOT/'research/benincasa';R=B/'results'
global_basis=json.loads((R/'cosmology_rees_global_checkpoint_basis_merge.json').read_text());identity=json.loads((R/'cosmology_principal_three_wall_p_identity.json').read_text());gate=json.loads((R/'cosmology_rees_generator_extraction_interface_gate.json').read_text());assert global_basis['passed'] and identity['passed']
point=(3,6,-3);p_value=point[0]+point[1]+3*point[2]
checks={'source_coefficient_cell_exists':identity['principal_three_wall_coefficient_cell_constructed'],'tau_p_column_previously_computed':identity['tau_p_column_computed'],'special_point_lies_on_p_wall':p_value==0,'raw_basis_width_is_single_parameter_fiber':True,'tau_p_requires_normal_jet_assembly':True,'raw_receipt_serializes_row_or_column_transformations':gate['interface_checks']['row_or_column_transformations_serialized'],'raw_receipt_serializes_labelled_kernel_or_cokernel_vectors':gate['interface_checks']['labelled_kernel_or_cokernel_vectors_serialized']}
assert checks['source_coefficient_cell_exists'] and checks['special_point_lies_on_p_wall'] and not checks['tau_p_column_previously_computed']
out={'schema':'marici.benincasa.cosmology-rees-principal-target-exact-membership.v1','problem':'test whether the principal three-wall tau_p target belongs to the exact rank-1382 raw-row space','bold_conjecture':'the principal tau_p target is already a typed vector in the single-fiber ambient-four column packet and reduces to zero against the exact basis','rivals':['raw-fiber membership is defined','tau_p exists only in the assembled normal-jet space','the affine p identity alone selects a target vector'],'risky_consequences':'a target must have an explicit labelled coordinate vector in the same width as the exact basis; at the wall p=0 its normal-jet grade and assembly map must be declared','strongest_falsification_attempt':{'point':list(point),'p_at_point':p_value,'global_raw_row_rank':global_basis['strongest_falsification_attempt']['global_rank'],'checks':checks,'source_identity':identity['source_identity']},'exact_residual':'the source supplies p=-q_g1-q_g2+q_g3, but explicitly records tau_p_column_computed=false; at the chosen wall p=0, tau_p is a normal-jet object assembled from interpolation grades, whereas the exact rank-1382 basis has only single-fiber raw columns','conjecture_disposition':'rejected as ill-typed for the current basis','membership_test_executed':False,'zero_residual_claimed':False,'minimal_interface_upgrade':['exact raw rows at all seven interpolation offsets','exact rational degree-one and degree-two interpolation weights','labelled width-three jet assembly matching assemble((r0,r1,r2),width)','explicit principal tau_p coordinate vector in that assembled space','target provenance back to the p coefficient cell'],'scope':'this is a typing obstruction, not nonmembership of a future assembled target','next_conjecture':'an exact assembled normal-jet iterator and explicit p-cell map define tau_p in a width-three labelled space whose row-space membership is decidable','next_falsifier':'construct the assembled exact basis, derive tau_p coordinates from the p identity, then retain any nonzero reduction residual','passed':True};(R/'cosmology_rees_principal_target_exact_membership.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
