#!/usr/bin/env python3
"""Terminal PS1A gate: assemble the corrected Leray-Cech packet and specialize G."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
def load(name):return json.loads((ROOT/'research/benincasa/results'/name).read_text())
a0=load('PS1A0_alternate_signed_minor_incidence.json');a1=load('PS1A1_matching_source_Leray_germs.json');a2c=load('PS1A2c_correct_Cech_pair_weights.json');g=load('G_degree15_relative_gluing.json')
v=a2c['vertex_vector'];pairs={z['edge']:z['cochain_coefficient'] for z in a2c['corrected_pair_currents']};triple=pairs['ab']-pairs['cb']+pairs['ca']
checks={'algebraic_gluing_was_partial':g['resolution']=='+-','prior_failure_was_specific_to_marked_corner_chart':'available marked-corner exceptional divisor' in g['physical_failure'] and 'a=0 and b=0' in g['physical_failure'],'matching_source_incidence':a0['resolution']=='++','exact_integral_local_packet':a1['correction_vector']==g['integral_collar_correction']==v,'source_oriented_integral_Cech_totalization':a2c['resolution']=='++' and triple==0,'algebraic_boundary_corrected':all(x==0 for x in g['corrected_boundary']),'nonzero_specialized_packet':any(v)}
assert all(checks.values()),checks
out={'schema':'marici.benincasa.PS1A-alternate-signed-minor-specialization.v1','prospective_action':'PS1A_alternate_signed_minor_specialization','outcome_contract':{'++':'a source-admissible Bunch-Davies Leray-Cech current realizes the integral degree-15 collar correction','+-':'physical current exists but its degree-15 pairing is unresolved','-+':'the corrected current has zero or incompatible specialization','--':'global specialization remains untyped'},'resolution':'++','global_current':{'vertex_Leray_coefficients':v,'pair_double_Leray_coefficients':pairs,'triple_Cech_boundary':triple,'boundary_value':'all marked cuts approached from Im(q)<0','integrality':'all coefficients integral'},'specialization_pairing':{'degree15_endpoint_correction':v,'corrected_algebraic_boundary':g['corrected_boundary'],'nonzero':True},'established':'The previously algebraic-only degree-15 correction has a source-admissible Bunch-Davies physical specialization. The local endpoint germs, corrected double-Leray transitions, and zero triple coboundary form one integral relative total current.','PS1_resolution':'++ via the PS1A witness; the alternate PS1B branch is no longer required for existence.','withheld':'No claim is made that PS1B fails or that this witness is unique among all physical relative currents.','next':'Close PS1 existential and prune the unneeded PS1B branch while retaining it as an unexplored alternative witness.','checks':checks,'passed':True};p=ROOT/'research/benincasa/results/PS1A_alternate_signed_minor_specialization.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'resolution':'++','PS1':'++','pairing_nonzero':True,'triple_boundary':0,'next':'close_PS1'}))
