#!/usr/bin/env python3
"""Separate parity-gate reopening data from sufficient lift data."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];R=ROOT/'research/benincasa/results'
def load(n):
 d=json.loads((R/n).read_text());assert d['passed'];return d
syn=load('cosmology_active_source_envelope_obstruction_synthesis.json');enlarge=load('cosmology_minimal_primitive_source_enlargement.json');status=load('cosmology_primitive_tau_current_source_envelope_status.json');base=load('cosmology_p_locus_to_Gysin_base_map.json')
proposed=enlarge['necessary_new_data'];assert proposed['odd_Xi_log_coefficient'] and proposed['integral_chain_map_and_d_squared_zero'];assert not base['Gysin_denominator_pullback_defined']
additional=['source-labelled generator with boundary and connecting image','source-derived base map and shared relative pair','relative homology-de Rham pairing','weighted specialization into the Gysin coefficient block','projection to (Xi_log,-sigma123)','integral physical readout with orientation authority']
assert all(x in status['missing_arrows'] for x in ['relative homology-de Rham pairing','weighted specialization into the Gysin coefficient block','projection to (Xi_log,-sigma123)','integral physical readout'])
out={'schema':'marici.benincasa.cosmology-obstruction-reopening-condition.v1','conjecture':'odd Xi coefficient, ordered Cech correction, routing, and an integral chain map form a complete sufficient reopening condition','proposed_package':proposed,'package_role':'necessary algebraic data to evade the even-lattice and total-complex gates','additional_typed_requirements':additional,'typed_derivation_chain':['source geometry/support G','integral coefficient object C','transport/coherence T','canonical comparison Q','physical readout R'],'complete_sufficient_condition':False,'conjecture_disposition':'falsified as a sufficiency claim','weak_reopening_condition':'an odd sourced Xi coefficient reopens the parity gate only','strong_reopening_condition':'construct and verify every arrow G->C->T->Q->R, including primitive [1,1] image and integral readout','current_package_constructs_source_generator':False,'current_package_constructs_base_map':False,'current_package_constructs_projection_and_readout':False,'not_a_global_impossibility_theorem':syn['not_a_global_impossibility_theorem'],'next_conjecture':'the final strength boundary is exactly active-envelope nonexistence, with the strong reopening chain as its falsifier','next_falsifier':'produce one source-authorized G->C->T->Q->R chain carrying a primitive generator to [1,1]','passed':True};(R/'cosmology_obstruction_reopening_condition.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
