#!/usr/bin/env python3
"""Test compatibility of equivariant even specialization with nonzero linking readout."""
import json
from pathlib import Path
import sympy as s
p,k=s.symbols('p k', nonzero=True);I=s.I;A=I*s.pi/(32*p**4*(k+1))
period_minus=-A;period_kappa=A;period_even=s.simplify(period_minus+period_kappa)
assert period_minus!=0 and period_kappa!=0 and period_even==0
out={'schema':'marici.benincasa.cosmology-even-root-pair-physical-pairing-dpc.v1','problem':'Can the equivariant even root-pair specialization simultaneously produce the claimed nonzero exceptional linking readout?','bold_conjecture':'A source contour specializing to n(gamma_-1+gamma_kappa) pairs nontrivially with the recorded grade-minus-one sewn form and supplies the physical record.','named_rivals':['the two meridian periods are equal and opposite','every equivariant even image lies in the kernel of this linking functional','a nonzero readout requires an odd or individually oriented cycle, conflicting with the current even target gate'],'risky_consequences':['the period of gamma_-1+gamma_kappa must be nonzero','the linking functional must not annihilate the transposition-invariant line'],'strongest_falsification_attempt':{'period_gamma_minus1':str(period_minus),'period_gamma_kappa':str(period_kappa),'period_even_sum':str(period_even),'period_of_n_even_sum':'0 for every integer n'},'disposition':{'status':'falsified','residual':'the equivariant symmetric root class is annihilated by the recorded linking functional, so gates two and four cannot both hold with this form','surviving_scope':'individual meridian periods remain nonzero; obtaining a nonzero physical record requires a source-authorized asymmetric cycle, sign local system, or different target form','reopening_test':'supply a physical target form whose pairing is nonzero on the invariant line, or a source contour action that justifies an odd/asymmetric target'},'passed':True};R=Path(__file__).resolve().parents[1]/'results';(R/'cosmology_even_root_pair_physical_pairing_dpc.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
