#!/usr/bin/env python3
"""PS1A2c: replace chain-incidence weights by the actual vertex Cech coboundary."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
triple=json.loads((ROOT/'research/benincasa/results/PS1A2b_triple_cut_closure.json').read_text());pairs=json.loads((ROOT/'research/benincasa/results/PS1A2a_pair_overlap_currents.json').read_text());local=json.loads((ROOT/'research/benincasa/results/PS1A2_global_marked_cut_Cech_gluing.json').read_text())
v=local['local_vector'];e=triple['repair_edge_coefficients'];delta={'ca':v[1]-v[0],'cb':v[2]-v[0],'ab':v[2]-v[1]};res=e['ab']-e['cb']+e['ca'];weighted=[{**p,'cochain_coefficient':e[p['edge']]} for p in pairs['pair_currents']]
checks={'repair_is_vertex_coboundary':e==delta,'triple_closes':res==0,'all_pair_germs_available':len(weighted)==3 and pairs['resolution']=='++','integral_weights':all(isinstance(x['cochain_coefficient'],int) for x in weighted),'local_vertices_recovered':e['ca']==v[1]-v[0] and e['cb']==v[2]-v[0] and e['ab']==v[2]-v[1]}
assert all(checks.values()),checks
out={'schema':'marici.benincasa.PS1A2c-correct-Cech-pair-weights.v1','prospective_action':'PS1A2c_correct_Cech_pair_weights','outcome_contract':{'++':'corrected integral pair packet equals delta(vertex data) and has zero triple coboundary','+-':'triple closure holds only rationally or with unresolved orientation','-+':'corrected packet still has a triple obstruction','--':'replacement cannot be typed'},'resolution':'++','vertex_vector':v,'corrected_pair_currents':weighted,'triple_coboundary':res,'established':'The three source-oriented double-Leray germs with coefficients delta(v) form an integral Cech 1-cocycle and reproduce all pairwise differences of the local endpoint packet.','withheld':'The terminal PS1A claim still requires assembling the diagonal germ and this cocycle into one global continued current and evaluating its specialization map.','next':'Resolve PS1A_alternate_signed_minor_specialization by assembling and pairing the corrected global current.','checks':checks,'passed':True};p=ROOT/'research/benincasa/results/PS1A2c_correct_Cech_pair_weights.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'resolution':'++','weights':e,'triple':res,'next':'PS1A_alternate_signed_minor_specialization'}))
