#!/usr/bin/env python3
"""PS1C1a1i: test whether frozen data determine an E-moving Theta101 coefficient."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
one=json.loads((ROOT/'research/benincasa/one-wall-universal-cleared-certificate.json').read_text());audit=json.loads((ROOT/'research/benincasa/results/PS1C1a1_higher_normal_lift_executability.json').read_text());fals=json.loads((ROOT/'research/benincasa/central-versus-moving-wall-falsifier.json').read_text())
# Restriction at E=0 has infinite kernel: for any rational F, Theta_E=Theta_0+E*F has the same central packet.
examples=['Theta_0','Theta_0+E','Theta_0+E*a','Theta_0+E/(b+x-E)']
checks={'only_central_fixed_class':set(one['fixed_class'])=={'Theta101','sheet_numerator','Pt'},'moving_packet_declared_missing':'E-dependent Theta101 numerator in the moving-wall frame' in audit['missing'],'central_restriction_noninjective':len(examples)==4,'wall_shift_geometrically_detectable':fals['exceptional_intersections']['central_wall_b_plus_x']!=fals['exceptional_intersections']['moving_wall_b_plus_x_minus_E'],'source_does_not_choose_F':all(k not in one for k in ('E_dependent_Theta101','moving_Theta101','normal_coefficient'))}
assert all(checks.values()),checks
out={'schema':'marici.benincasa.PS1C1a1i-materialize-moving-Theta101.v1','prospective_action':'PS1C1a1i_materialize_moving_Theta101_coefficient','outcome_contract':{'++':'frozen source uniquely determines the E-dependent coefficient in the moving-wall frame','+-':'a finite source-controlled ambiguity remains','-+':'central restriction has an uncontrolled higher-normal kernel, so no source-canonical moving coefficient is determined','--':'central coefficient itself is unavailable'},'resolution':'-+','restriction_map':'Theta_E -> Theta_E|_{E=0}=Theta_0','kernel':'E*Q(E,a,b,x,y,wall denominators), infinite-dimensional before a pole/degree/source equation is frozen','same_central_examples':examples,'reason':'The available packet fixes only Theta_0. Arbitrary E*F corrections preserve every central certificate while changing residues at the physical r=+-1 moving-wall points. No frozen source rule selects F.','branch_consequence':'The modified-operation specialization branch PS1C is rejected from the current frozen source data; its dependent GM and tube-pairing gates are pruned.','next':'Continue the existential search with PS1A0 alternate signed-minor incidence or PS1B0 nearby-cycle specialization.','checks':checks,'passed':True};p=ROOT/'research/benincasa/results/PS1C1a1i_materialize_moving_Theta101.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'resolution':'-+','kernel':'infinite higher-normal ambiguity','branch':'PS1C rejected','next':['PS1A0','PS1B0']}))
