#!/usr/bin/env python3
"""Synthesize the strongest primitive-lift obstruction in the active envelope."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];R=ROOT/'research/benincasa/results'
def load(n):
 d=json.loads((R/n).read_text());assert d['passed'];return d
status=load('cosmology_primitive_tau_current_source_envelope_status.json');gate=load('cosmology_quotient_colimit_tau_p_gate.json');sign=load('cosmology_sign_twist_untwisted_lattice_descent.json');source=load('cosmology_p_gauge_sign_local_system_source.json');compare=load('cosmology_sign_norm_principal_2Z_comparison.json');base=load('cosmology_p_locus_to_Gysin_base_map.json');affine2=load('cosmology_principal_q_affine_leading_degree_no_go.json');affine1=load('cosmology_rank_one_affine_Gysin_constant_line.json');enlarge=load('cosmology_minimal_primitive_source_enlargement.json')
assert gate['primitive_integral_tau_p']['known_principal_coefficient_lattice']=='2Z';assert not sign['nonzero_integral_linear_descent_exists'];assert not source['gauge_sign_system_source_authorized'];assert not compare['comparison_arrow_constructed'];assert not base['Gysin_denominator_pullback_defined'];assert not affine2['cancellation_possible'];assert not affine1['nonconstant_line_with_nonzero_constant_pullback_exists']
out={'schema':'marici.benincasa.cosmology-active-source-envelope-obstruction-synthesis.v1','conjecture':'the audited sign, parity, source-authority, and base-map gates leave a source-authorized primitive integral route','audited_routes':{'existing_principal_lattice':'2Z cannot contain the required primitive unit','formal_sign_gauge':'matching source sign local system absent; sign-to-trivial integral map is zero','norm_descent':'ordinary but doubled and nonprimitive','norm_to_principal_identification':'comparison arrow absent','weighted_Gysin_route':'no source-derived p-locus base map','X_candidate':'exact singular-support mismatch','q_candidate':'fiber-valued rather than a base map','general_affine_q_routes':'rank two retains degree-five leading term; rank one has no nonzero constant line'},'surviving_non_solution_data':status['established'],'missing_arrows':status['missing_arrows'],'source_authorized_primitive_integral_route_exists':False,'conjecture_disposition':'falsified under the active source envelope','strongest_result':'no source-authorized primitive tau_p lift exists in the audited source envelope','not_a_global_impossibility_theorem':True,'reopening_requires':enlarge['necessary_new_data'],'reason_not_sufficient':enlarge['reason_not_sufficient'],'next_conjecture':'the listed odd Xi coefficient, ordered Cech correction, routing, and integral chain-map package is a complete reopening condition','next_falsifier':'check necessity and sufficiency separately; exhibit any additional missing source, support, transport, or readout datum','passed':True};(R/'cosmology_active_source_envelope_obstruction_synthesis.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
