#!/usr/bin/env python3
"""Test algebraic and physical gluing of the exact degree-15 endpoint defect."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
b=json.loads((ROOT/'research/benincasa/results/B_degree15_signed_minor_restriction.json').read_text());inc=json.loads((ROOT/'research/benincasa/results/VC2m1_axis_exceptional_incidence.json').read_text());lifts=json.loads((ROOT/'research/benincasa/physical-cycle-endpoint-normal-lifts.json').read_text())
defect=[int(x['first']) for x in b['restriction_coefficients']];correction=[-x for x in defect];total=[x+y for x,y in zip(defect,correction)]
checks={'typed_defect':b['resolution']=='-+','three_integral_coefficients':len(defect)==3 and all(isinstance(x,int) for x in defect),'algebraic_mapping_cylinder_cancels':total==[0,0,0],'local_normal_lifts_exist':lifts['incidence_tangency_checks']==9,'axis_exceptional_incidence_empty':inc['incidence']=={'a_axis':False,'b_axis':False}}
assert all(checks.values()),checks
out={'schema':'marici.benincasa.G-degree15-relative-gluing.v1','prospective_action':'G_relative_gluing','outcome_contract':{'++':'integral algebraic correction with source-admissible BD physical specialization','+-':'integral algebraic correction exists but physical specialization is absent','-+':'endpoint vector is not algebraically glueable','--':'gluing data are untyped'},'endpoint_order':['c=0','a=0','b=0'],'defect':defect,'integral_collar_correction':correction,'corrected_boundary':total,'resolution':'+-','positive_result':'The rank-three integral mapping-cylinder correction cancels the complete first-order defect exactly.','physical_failure':'The a=0 and b=0 collar strata do not meet the available marked-corner exceptional divisor for x,y>0, so the correction has no source-admissible global BD specialization through that chart.','coherence_consequence':'Observed G=+- contradicts the previously unique formal skeleton G=++; the frozen *+ solution-existence hypothesis has no surviving assignment under the current arrow contracts.','next':'Audit the composite-path model: separate algebraic relative class from physical BD class, then rebuild the pyramid without identifying those codomains.','checks':checks,'passed':True};p=ROOT/'research/benincasa/results/G_degree15_relative_gluing.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'resolution':'+-','defect':defect,'correction':correction,'coherence_survivors':0,'next':out['next']}))
