#!/usr/bin/env python3
"""PS1M2a: determine whether frozen packets define a canonical column-level nearby map."""
import json,collections
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
def load(p):return json.loads((ROOT/p).read_text())
exact=load('research/benincasa/results/G12_exact_degree15_reconstruction.json');ov=load('research/benincasa/results/G12_coefficient_overlap_representatives.json');near=load('research/benincasa/full-rank12-cut-nearby-layers-certificate.json');audit=load('research/benincasa/results/PS1M2_nearby_degree15_projection_audit.json')
kinds=collections.Counter(z['kind'] for z in exact['solution']);source_labels={z['kind'] for z in exact['solution']};near_names=('g101','g110','g111_tilde');serialized=json.dumps({'exact':exact['solution'][:3],'overlap':ov.get('columns',[])[:3]})
checks={'projection_was_missing':audit['resolution']=='--','exact_basis_is_d0_plus_overlap':source_labels=={'d0','overlap'},'nearby_packet_has_three_columns':len(near['cut_nearby_algebraic_image'])==3,'no_generator_identification':all(n not in serialized for n in near_names),'only_one_common_line_fixed':near['intersection_rank']==1 and near['combined_rank']>near['intersection_rank'],'maps_nonunique_on_complement':exact['ambient_shape'][1]>near['intersection_rank']}
assert all(checks.values()),checks
out={'schema':'marici.benincasa.PS1M2a-degree15-to-nearby-column-map.v1','prospective_action':'PS1M2a_materialize_degree15_to_nearby_column_map','outcome_contract':{'++':'source descriptors canonically map every degree-15 column to the nearby basis','+-':'the map is fixed only on a finite-index sublattice','-+':'the frozen data constrain only the common e6 line, leaving arbitrary maps on the source complement','--':'one of the two bases is absent'},'resolution':'-+','degree15_basis':{'total_columns':exact['ambient_shape'][1],'supported_solution_columns':exact['nonzero_solution_terms'],'supported_kinds':dict(kinds),'labels':'presentation d0 indices and g1|g2 overlap monomials'},'nearby_basis':{'semantic_names':near_names,'images':near['cut_nearby_algebraic_image']},'fixed_comparison':{'rank':near['intersection_rank'],'generator':near['intersection_generator']},'nonuniqueness':'Any map agreeing on e6 may be changed by an arbitrary homomorphism from the unresolved source complement to span(g101,g110,g111_tilde). The certificates provide no naturality equation selecting one extension.','consequence':'The existing nearby packet is not yet a second degree-15 realization. It cannot be counted as a distinct universe or compared to PS1A from frozen data.','next':'PS1M3 close the current census as one typed realization with uniqueness and nearby equivalence both unresolved. A future comparison requires a new chain-level natural transformation, not inference from the common e6 line.','checks':checks,'passed':True};p=ROOT/'research/benincasa/results/PS1M2a_degree15_to_nearby_column_map.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'resolution':'-+','fixed_rank':1,'unmapped_columns':exact['ambient_shape'][1]-1,'next':'PS1M3_compare_realization_classes'}))
