#!/usr/bin/env python3
"""Audit which root-pair invariant line is selected by the Kummer character."""
import json
from pathlib import Path
import sympy as s
P=s.Matrix([[0,1],[1,0]]);I=s.eye(2)
untwisted=(P-I).nullspace();twisted=(-P-I).nullspace()
assert untwisted==[s.Matrix([1,1])]
assert twisted==[s.Matrix([-1,1])]
out={'schema':'marici.benincasa.qg12-kummer-twisted-root-invariants-dpc.v1','problem':'Does a sign-local-system ambiguity leave the canonical root-pair line undecided after the q_g2 Kummer audit?','bold_conjecture':'Even after restricting K to q_g2, both the symmetric and antisymmetric root-pair lines remain equally admissible invariant targets.','named_rivals':['trivial Kummer character selects the ordinary transposition action','a nontrivial character would twist transposition by minus one','only the overall orientation sign remains free'],'risky_consequences':['the restricted Kummer character must fail to distinguish P from -P','both sum and difference must be fixed for the same action'],'strongest_falsification_attempt':{'ordinary_action':[[0,1],[1,0]],'ordinary_fixed_generator':[1,1],'sign_twisted_action':[[0,-1],[-1,0]],'twisted_fixed_generator':[-1,1],'restricted_Kummer_character':1},'disposition':{'status':'falsified locally','surviving_scope':'the trivial q_g2 Kummer character selects the symmetric invariant line generated by gamma_plus+gamma_minus','remaining_orientation_gate':'the generator is still determined only up to overall sign until a source contour orientation is declared'},'passed':True};R=Path(__file__).resolve().parents[1]/'results';(R/'qg12_kummer_twisted_root_invariants_dpc.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
