#!/usr/bin/env python3
"""Test the unique C3-invariant line in the labelled square-free normal grade."""

import ast
import json
import os
import re
import subprocess
from fractions import Fraction
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
CRATE = ROOT / "marici-gm"
CASES = (
    ("A", 32003),
    ("A", 65521),
    ("B", 65521),
    ("HOMA", 32003),
    ("SOFT1", 32003),
)


def signed(value, prime):
    value %= prime
    return value if value <= prime // 2 else value - prime


def rational_rank(rows):
    matrix = [[Fraction(value) for value in row] for row in rows]
    rank = 0
    for column in range(len(matrix[0])):
        pivot = next(
            (row for row in range(rank, len(matrix)) if matrix[row][column]),
            None,
        )
        if pivot is None:
            continue
        matrix[rank], matrix[pivot] = matrix[pivot], matrix[rank]
        scale = matrix[rank][column]
        matrix[rank] = [value / scale for value in matrix[rank]]
        for row in range(len(matrix)):
            if row != rank and matrix[row][column]:
                scale = matrix[row][column]
                matrix[row] = [
                    value - scale * pivot_value
                    for value, pivot_value in zip(matrix[row], matrix[rank])
                ]
        rank += 1
    return rank


def run_case(point, prime):
    environment = os.environ.copy()
    environment.update(
        NORMAL_TOWER="1",
        KINEMATIC_POINT=point,
        PRIME=str(prime),
    )
    environment.pop("CM_TOTAL_ENERGY_SECOND", None)
    completed = subprocess.run(
        ["cargo", "run", "--quiet", "--bin", "cm_normal_tower_rank"],
        cwd=CRATE,
        env=environment,
        text=True,
        capture_output=True,
        check=True,
    )
    summary = re.search(
        r"cohomology_rank=(\d+) labelled_class_rank=(\d+) label_count=(\d+)",
        completed.stdout,
    )
    kernel = ast.literal_eval(
        re.search(r"NORMAL_TOWER_KERNEL=(.*)", completed.stdout).group(1)
    )
    # Echelon rows 2,3,4 correspond to nu1*nu2, nu1*nu3, nu2*nu3.
    pair_rows = kernel[2:5]
    pair_coordinates = [signed(-row[3], prime) for row in pair_rows]
    invariant_coordinate = signed(sum(pair_coordinates), prime)
    return {
        "point": point,
        "prime": prime,
        "cohomology_rank": int(summary.group(1)),
        "labelled_class_rank": int(summary.group(2)),
        "label_count": int(summary.group(3)),
        "pair_quadratic_quotient_coordinates": pair_coordinates,
        "s2_quadratic_quotient_coordinate": invariant_coordinate,
        "s2_nonzero": invariant_coordinate != 0,
        "gb_complete": "GB_COMPLETE" in completed.stderr,
    }


def main():
    runs = [run_case(*case) for case in CASES]
    # The permutation matrix of (12,13,23) -> (23,12,13) has fixed kernel
    # of P-I generated by (1,1,1).
    permutation = [[0, 0, 1], [1, 0, 0], [0, 1, 0]]
    generator = [1, 1, 1]
    fixed = [
        sum(permutation[row][column] * generator[column] for column in range(3))
        for row in range(3)
    ]
    permutation_minus_identity = [
        [
            permutation[row][column] - (1 if row == column else 0)
            for column in range(3)
        ]
        for row in range(3)
    ]
    checks = {
        "cyclic_sum_is_invariant": fixed == generator,
        "invariant_subspace_rank_is_one": rational_rank(
            permutation_minus_identity
        )
        == 2,
        "all_cm_ranks_match_entry_2554": all(
            run["cohomology_rank"] == 7
            and run["labelled_class_rank"] == 4
            and run["label_count"] == 10
            for run in runs
        ),
        "cyclic_sum_reaches_quadratic_quotient": all(
            run["s2_nonzero"] for run in runs
        ),
        "all_groebner_runs_completed": all(run["gb_complete"] for run in runs),
    }
    packet = {
        "schema": "marici.cyclic_invariant_quadratic_normal.v1",
        "status": "pass" if all(checks.values()) else "fail",
        "label_order": ["nu1*nu2", "nu1*nu3", "nu2*nu3"],
        "cyclic_permutation_matrix": permutation,
        "invariant_generator": generator,
        "runs": runs,
        "checks": checks,
        "conclusion": (
            "The unique C3-invariant square-free quadratic normal line has a "
            "nonzero image in Entry 2554's unique quadratic quotient at every "
            "tested packet. This identifies the only possible projective target "
            "of an equivariant scalar-normal map; it does not prove such a map exists."
        ),
    }
    output = ROOT / "results" / "cyclic-invariant-quadratic-normal.json"
    output.write_text(json.dumps(packet, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"status": packet["status"], "checks": checks}, indent=2))
    raise SystemExit(0 if packet["status"] == "pass" else 1)


if __name__ == "__main__":
    main()
