#!/usr/bin/env python3
"""Compare the admitted PS1A current with the primitive cyclic nearby e6 class."""
import json
from pathlib import Path
R=Path(__file__).resolve().parents[1]
a=json.loads((R/'results/PS1A_alternate_signed_minor_specialization.json').read_text())
h=json.loads((R/'results/PS1M1_Leray_Cech_homology_signature.json').read_text())
n=json.loads((R/'cyclic-cut-nearby-sewing.json').read_text())
c=json.loads((R/'three-cut-cousin-cocycle-certificate.json').read_text())
v=a['global_current']['vertex_Leray_coefficients']; A=sum(v)
assert A==h['augmentation_signature'] and A%6==0
assert a['global_current']['triple_Cech_boundary']==0
assert c['pairwise_cut_residues']==[0,0,0]
assert n['occurrence_signs']==[1]*6
k=A//6; occurrence=[k]*6
assert [occurrence[0]+occurrence[1],occurrence[2]+occurrence[3],occurrence[4]+occurrence[5]]==h['symmetric_diagonal_representative']
out={'schema':'marici.benincasa.PS1M9-current-level-nearby-comparison.v1','prospective_action':'PS1M9_compare_admitted_current_on_common_e6_quotient','resolution':'++','domain':'the rank-one sublattice generated by the admitted PS1A relative current, not the full 6040-column presentation','source_class':{'vertex_vector':v,'augmentation':A,'pair_double_Leray_coefficients':a['global_current']['pair_double_Leray_coefficients'],'triple_boundary':0},'target_class':{'carrier':'primitive cyclic e6 nearby line','six_occurrence_vector':occurrence,'forgotten_three_sector_vector':h['symmetric_diagonal_representative'],'orientation':'positive'},'chain_rule':'send every source Cech boundary/pair-gauge component to zero and send the admitted H0 generator to its normalized cyclic e6 occurrence class','compatibility':{'source_pair_packet_closed':True,'target_pairwise_differential_zero':True,'augmentations_match':True,'integral_on_admitted_rank_one_lattice':True},'conclusion':'The admitted PS1A realization and the cut-nearby packet define the same normalized class on their common primitive e6 quotient. This repairs the prior blanket noncomparability claim at current level.','withheld':'No natural transformation on the full degree-15 presentation is constructed; uniqueness of realization and equality before quotient remain open.','passed':True}
(R/'results/PS1M9_current_level_nearby_comparison.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
