#!/usr/bin/env python3
"""DPC comparison of source occurrence monodromy with the gauge sign system."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];B=ROOT/'research/benincasa';R=B/'results'
gauge=json.loads((R/'cosmology_p_gauge_deck_sign_descent.json').read_text());occ=json.loads((B/'soft-endpoint-occurrence-monodromy.json').read_text());rel=json.loads((B/'soft-endpoint-relative-variance.json').read_text());assert gauge['passed'] and occ['status']=='pass'
assert occ['monodromy_matrix']==[[0,1],[1,0]] and occ['anti_invariant_generator']==[1,-1]
endpoint_support=sorted(rel['endpoint_types'].keys());assert endpoint_support==['xi=+1','xi=-1']
out={'schema':'marici.benincasa.cosmology-p-gauge-sign-local-system-source.v1','conjecture':'an existing occurrence-monodromy object supplies the gauge sign local system','gauge_system':{'base':'p=0 with coordinate u','branch_support':'four roots of D(u)','local_monodromies':[-1,-1,-1,-1]},'strongest_source_candidate':{'artifact':'soft-endpoint-occurrence-monodromy.json','labelled_occurrences':occ['labelled_occurrences'],'monodromy_matrix':occ['monodromy_matrix'],'anti_invariant_generator':occ['anti_invariant_generator'],'base_support':endpoint_support},'abstract_character_matches':True,'typed_base_map_to_p_locus':False,'branch_support_matches':False,'square_class_identified':False,'conjecture_disposition':'falsified as a source identification','reason':'the abstract minus character agrees, but a sign local system is determined by its cover or branch square class; endpoint support at xi=plus/minus one is not identified with D=0','gauge_sign_system_source_authorized':False,'next_conjecture':'even if adjoined formally, the sign twist changes the coefficient system and cannot yield the requested integral lift over the original source lattice','next_falsifier':'construct a descent map from the twisted lattice to the untwisted rank-twelve target, or exhibit the residual minus monodromy','passed':True};(R/'cosmology_p_gauge_sign_local_system_source.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
