#!/usr/bin/env python3
"""VC2j: pair endpoint collars with the source physical marked-cut system."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
total=json.loads((ROOT/'research/benincasa/results/VC2i_endpoint_corrected_relative_totalization.json').read_text())
chain=json.loads((ROOT/'research/benincasa/three-cut-relative-chain-pairing-certificate.json').read_text())
checks={'algebraic_correction_exists':total['resolution']=='+-','physical_chain_positive':chain['physical_chain'].startswith('a,b,c>=0'),'all_marked_cuts_bounded_by_E':set(chain['lower_bound_on_chain'].values())=={'E>0'},'closure_avoids_marked_cuts':chain['physical_chain_closure_intersects_marked_cut_union'] is False,'boundary_faces_avoid_marked_cuts':chain['physical_boundary_faces_intersect_marked_cut_union'] is False,'boundary_cut_incidence_zero':chain['chain_boundary_cut_incidence']==[0,0,0],'occurrence_pairing_zero':chain['six_occurrence_relative_boundary_pairing']==[0,0,0,0,0,0]}
assert all(checks.values()),checks
out={'schema':'marici.benincasa.VC2j-endpoint-collar-marked-residue-pairing.v1','prospective_action':'VC2j_endpoint_collar_marked_residue_pairing','literal_positive_chain':{'marked_cut_lower_bounds':chain['lower_bound_on_chain'],'boundary_cut_incidence':chain['chain_boundary_cut_incidence'],'collar_pairing':[0,0]},'algebraic_correction':total['differential']['collar_correction'],'resolution':'-+','reason':'The source positive semialgebraic chain and all its endpoint faces avoid the marked-cut union because q_Gij=E+(a,b,c)>0. Hence both endpoint collar marked-residue pairings vanish. The algebraic mapping-cylinder correction cannot cancel a physical marked residue on this literal chain.','consequence':'The degree-17 endpoint-corrected representative does not acquire physical_relative_descent from the source positive chain. Nonzero Cut germs live only after Bunch-Davies analytic continuation and require a separately constructed continued collar current.','interface_added':'literal_endpoint_collar_pairing_zero','interface_withheld':'physical_relative_descent','next_options':['construct a Bunch-Davies-continued endpoint collar current with oriented boundary','reject the degree-17 lowering as a physical channel'],'checks':checks,'passed':True};p=ROOT/'research/benincasa/results/VC2j_endpoint_collar_marked_residue_pairing.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'resolution':'-+','collar_pairing':[0,0],'next':out['next_options']}))
