#!/usr/bin/env python3
"""Observe the prospectively selected exchange-transport arrow."""
import gzip,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
domain=json.loads((ROOT/'research/benincasa/results/G12_source_labelled_overlap_domain.json').read_text());cols=json.loads((ROOT/'research/benincasa/results/G12_coefficient_overlap_representatives.json').read_text());pres=json.loads((ROOT/'research/benincasa/results/G12_char0_H1_presentation.json').read_text())
transport=cols['exchange_transport'];targets={v['target'] for v in transport.values()};names=set(transport)
# Contract frozen here at interface granularity: ++ requires both coefficient-module and quotient-presentation chain maps.
checks={'domain_exchange_equivariant':domain['checks']['d1_exchange_equivariant'] and domain['checks']['d2_exchange_equivariant'],'six_column_transport':len(transport)==6 and targets==names,'transport_involutive':all(transport[transport[k]['target']]['target']==k and transport[k]['sign']*transport[transport[k]['target']]['sign']==1 for k in names),'exact_H1_matrix_exists':pres['checks']['nonempty_exact_entries'],'H1_exchange_chain_map_absent':'exchange_transport' not in pres and 'exchange_chain_map' not in pres}
assert all(checks.values()),checks
out={'schema':'marici.benincasa.X-exchange-transport.v1','prospective_action':'X_exchange_transport','outcome_contract':{'++':'exact exchange chain maps on overlap module and d0 presentation, hence on degree-15 solution torsor','+-':'exact exchange on overlap coefficients, but no certified exchange chain map on the d0 presentation','-+':'exchange unavailable on coefficients but replaceable after quotient','--':'transport cannot be typed'},'observed_outcome':'+-','established':'The six exact overlap columns carry the involution (g1 g2)(s23 s31), including orientation signs. Polynomial weights inherit a<->b transport without increasing degree.','missing':'A row/column chain-map certificate intertwining the 1330x1144 exact d0 matrix with exchange; without it, transport of the full solution torsor modulo im(d0) is not certified.','next':'Construct permutation/sign matrices S1,S0 and verify S1*d0=d0*S0 exactly (or modularly first).','checks':checks,'passed':True};p=ROOT/'research/benincasa/results/X_exchange_transport.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'outcome':'+-','next':out['next']}))
