#!/usr/bin/env python3
"""Exact graded accounting and the unresolved quotient-kernel term."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];R=ROOT/'research/benincasa/results';a4=json.loads((R/'cosmology_rees_exact_assembled_target_membership.json').read_text());a5=json.loads((R/'cosmology_rees_tau_residue_stabilization.json').read_text());a6=json.loads((R/'cosmology_rees_ambient_transition_coherence.json').read_text())
def monomials(d):return (d+1)*(d+2)//2
def raw_families(A):return {'twisted_derivative':4*monomials(A),'K_multiplication':64*monomials(A-4),'q_multiplication':240*monomials(A-1)}
cutoffs=[4,5,6];families=[raw_families(A) for A in cutoffs];raw=[sum(x.values()) for x in families];width=[96*monomials(A+4) for A in cutoffs];assembled_dim=[3*x for x in width];ranks=[a4['strongest_falsification_attempt']['assembled_rank'],a5['strongest_falsification_attempt']['ambient_five']['rank'],a6['strongest_falsification_attempt']['ambient_six']['rank']];quotient_dim=[d-r for d,r in zip(assembled_dim,ranks)];deltas=lambda x:[x[i+1]-x[i] for i in range(2)];supports=[a4['strongest_falsification_attempt']['exact_residual_nnz'],a5['strongest_falsification_attempt']['ambient_five']['residual_nnz'],a6['strongest_falsification_attempt']['ambient_six']['residual_nnz']]
assert raw==[2524,3876,5536] and [3*x for x in raw]==[7572,11628,16608]
# For f:Q_A->Q_B, dim coker(f)-dim ker(f)=dim Q_B-dim Q_A; non-monicity leaves both terms unresolved.
euler_differences=deltas(quotient_dim)
out={'schema':'marici.benincasa.cosmology-rees-graded-transition-cokernel-growth.v1','problem':'separate combinatorial new-degree growth from actual quotient-transition cokernel dimensions','bold_conjecture':'labelled degree strata determine transition cokernel growth and a stable renormalized tau_p coordinate','rivals':['raw family growth explains only presentation size','quotient dimension differences determine cokernels','unknown transition kernels obstruct cokernel identification'],'risky_consequences':'the derived data must determine kernel and cokernel separately, not only their Euler difference; target supports must admit a stable labelled comparison','strongest_falsification_attempt':{'cutoffs':cutoffs,'raw_family_counts':families,'raw_row_counts':raw,'assembled_coordinate_widths':width,'assembled_dimensions':assembled_dim,'relation_ranks':ranks,'quotient_dimensions':quotient_dim,'increments':{'raw_rows':deltas(raw),'assembled_dimensions':deltas(assembled_dim),'relation_rank':deltas(ranks),'quotient_dimension_euler_difference':euler_differences,'tau_normal_form_support':deltas(supports)},'tau_supports':supports,'exact_identity':'dim(coker f)-dim(kernel f)=dim(Q_target)-dim(Q_source)','global_monicity_available':False},'exact_residual':'new-degree strata explain raw-row increments 1352 and 1660; quotient dimensions are 8814,9952,11084 with differences 1138 and 1132, but these are cokernel-minus-kernel, not cokernel dimensions, because global monicity was never proved','conjecture_disposition':'revised: graded presentation growth is derived, while transition cokernel growth and a renormalized stable coordinate remain underdetermined','transition_cokernel_dimensions_computed':False,'renormalized_tau_coordinate_defined':False,'scope':'finite exact dimension accounting; no silent coercion of quotient-dimension differences to cokernels','next_conjecture':'relative exact reduction computes the kernel rank of A4-to-A5 and A5-to-A6, separating kernel and cokernel dimensions and testing whether tau_p lies outside each kernel','next_falsifier':'reduce source quotient complement vectors against the target relation space and retain every killed nonzero source normal form','passed':True};(R/'cosmology_rees_graded_transition_cokernel_growth.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
