#!/usr/bin/env python3
"""Derive the exact cross-K-level syzygy for corrected scalar operators."""
import json
from pathlib import Path
# B(H^a f)=H^a B(f)+a H^(a-1)Q grad(H).f, K=H^2, grad K=2H grad H.
# L0=H^4B-H^3Q gradH; L1=H^2B-3HQ gradH.
# L0(Hf)=H^5B(f); L1(H^3f)=H^5B(f).
assert 1-1==0
out={'schema':'marici.benincasa.cosmology-rees-correct-cross-level-syzygy.v1','problem':'control higher-degree cancellation between the corrected kp=0 and kp=1 scalar blocks','bold_conjecture':'the corrected twist coefficients destroy the cross-level conjugation and allow uncontrolled independent leading inputs','named_rivals':['no cross-level reduction','an exact syzygy generated by the square root H of K'],'risky_consequences':['no polynomial pair with degree shift two may have identical L0 and L1 output','Leibniz coefficients -1/2 and -3/2 must fail to align'],'strongest_falsification_attempt':{'definitions':['K=H^2','L0=H^4B-H^3Q gradH','L1=H^2B-3HQ gradH'],'Leibniz':['L0(Hf)=H^5B(f)','L1(H^3f)=H^5B(f)'],'exact_syzygy':'L0(Hf)-L1(H^3f)=0','weighted_degree_alignment':'kp0 input degree d+2 and kp1 input degree d+6 both produce output degree d+14','exact_residual':0},'disposition':'the corrected operator has an exact cross-level syzygy; kp1 components divisible by H^3 can be traded for kp0 components divisible by H','surviving_scope':'this controls one cross-level submodule but does not classify within-level kernels or prove the global cutoff','next_test':'compute the corrected combined homogeneous kernel modulo this exact syzygy and test whether every remaining high-degree class is coercive','passed':True};R=Path(__file__).resolve().parents[1]/'results';(R/'cosmology_rees_correct_cross_level_syzygy.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
