#!/usr/bin/env python3
"""Type gate for replaying a modular kernel DAG over exact rational relations."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];R=ROOT/'research/benincasa/results'
c=json.loads((R/'cosmology_rees_first_modular_kernel_candidate.json').read_text());candidate=c['candidate']
checks={'candidate_label_present':bool(candidate.get('label')),'zero_image_replayed_modularly':c['zero_image_replayed'],'coefficient_field_serialized':'coefficient_prime' in c,'reachable_relation_checkpoints_serialized':'reachable_relation_checkpoints' in c,'reachable_source_checkpoints_serialized':'reachable_source_checkpoints' in c,'cross_prime_matched_candidate_serialized':'cross_prime_matches' in c,'rational_coefficients_serialized':'rational_coefficients' in c}
assert checks['candidate_label_present'] and checks['zero_image_replayed_modularly'] and not checks['rational_coefficients_serialized']
out={'schema':'marici.benincasa.cosmology-rees-exact-kernel-dag-replay-gate.v1','problem':'determine whether the serialized modulo-101 candidate DAG can be replayed over exact rational relations','bold_conjecture':'the modular checkpoint factors define rational coefficients for an exact source vector and zero-image witness','rivals':['centered residue lifts are exact coefficients','cross-prime reconstruction is required','an independently rerun exact elimination supplies coefficients'],'risky_consequences':'the receipt must type its coefficient field, serialize every reachable checkpoint, and provide rational coefficients or matched residues at enough primes','strongest_falsification_attempt':{'candidate_digest':c['candidate_digest'],'candidate_step_count':len(candidate['steps']),'checks':checks},'exact_residual':'the candidate has a stable label and modular zero replay, but its factors are untyped residues from one field; reachable checkpoint records and cross-prime or rational coefficients are absent','conjecture_disposition':'falsified for the current DAG receipt','exact_replay_executed':False,'centered_lift_rejected':True,'first_missing_typed_object':'a self-contained reachable checkpoint DAG with coefficient prime plus label-matched candidate coefficients at additional primes or independently exact coefficients','acceptance_test':'replay each modular DAG, reconstruct bounded rationals coefficientwise, rerun the exact source combination, and require exact nonzero source with exact zero target','scope':'receipt/interface obstruction; no conclusion about the characteristic-zero kernel','passed':True};(R/'cosmology_rees_exact_kernel_dag_replay_gate.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
