#!/usr/bin/env python3
"""Match the first quotient-kernel checkpoint DAG at primes 101 and 103."""
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];R=ROOT/'research/benincasa/results';a=json.loads((R/'cosmology_rees_first_modular_kernel_candidate.json').read_text());b=json.loads((R/'cosmology_rees_first_modular_kernel_candidate_p103.json').read_text());c=json.loads((R/'cosmology_rees_first_modular_kernel_candidate_p107.json').read_text())
def topology(d):
 def steps(xs):return [(x[0],tuple(x[2])) for x in xs]
 return {'candidate_label':d['candidate']['label'],'candidate_grade':d['candidate']['grade'],'candidate_target_coordinate':d['candidate']['target_coordinate'],'candidate_steps':steps(d['candidate']['steps']),'relation':{k:(v['added'],v['pivot'][0] if v['pivot'] else None,steps(v['steps'])) for k,v in d['reachable_relation_checkpoints'].items()},'source':{k:(v['label'],v['grade'],v['added'],v['pivot'][0] if v['pivot'] else None,steps(v['steps'])) for k,v in d['reachable_source_checkpoints'].items()}}
ta,tb,tc=topology(a),topology(b),topology(c);same=ta==tb==tc;assert [a['coefficient_prime'],b['coefficient_prime'],c['coefficient_prime']]==[101,103,107]
out={'schema':'marici.benincasa.cosmology-rees-cross-prime-kernel-candidate-match.v2','problem':'determine whether the first modular kernel candidate has a prime-independent labelled checkpoint topology','bold_conjecture':'the first dependency at primes 101, 103, and 107 names the same source coordinate and the same reachable operation DAG','rivals':['the p101 dependency is prime-specific','labels agree but checkpoint topology differs','one common candidate admits coefficient reconstruction'],'risky_consequences':'candidate grade, source label, target coordinate, reachable checkpoint keys, pivots, and owner edges must agree after deleting field coefficients','strongest_falsification_attempt':{'primes':[101,103,107],'candidate_label':a['candidate']['label'],'candidate_grade':a['candidate']['grade'],'reachable_relation_count':a['reachable_relation_count'],'reachable_source_count':a['reachable_source_count'],'topology_matches_all_three':same,'pairwise_matches':{'101_103':ta==tb,'101_107':ta==tc,'103_107':tb==tc},'topology_digests':{str(p):hashlib.sha256(repr(t).encode()).hexdigest() for p,t in [(101,ta),(103,tb),(107,tc)]}},'exact_residual':'the candidate label and closure counts agree at all three primes, but the prime-107 checkpoint topology differs from the common 101/103 topology','conjecture_disposition':'falsified for a single three-prime operation DAG','coefficient_reconstruction_executed':False,'scope':'prime-dependent elimination topology; no conclusion yet about whether expanded source-vector coordinates match','next_test':'expand each candidate to labelled source coordinates before cross-prime comparison; do not CRT operation factors across different DAGs','passed':True};(R/'cosmology_rees_cross_prime_kernel_candidate_match.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
