#!/usr/bin/env python3
"""Classify the expanded first dependency against exact A4 source relations."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];R=ROOT/'research/benincasa/results';d=json.loads((R/'cosmology_rees_expanded_kernel_source_coordinates.json').read_text());vectors=d['strongest_falsification_attempt']['vectors']
expected={"0|(0, 1, 1, 1, 1, 1, (0, 0))":-1,"0|(0, 1, 1, 1, 1, 2, (0, 0))":-6,"0|(0, 1, 1, 1, 1, 2, (1, 0))":1}
for item in vectors:
 p=item['prime'];assert item['vector']=={k:v%p for k,v in expected.items()}
out={'schema':'marici.benincasa.cosmology-rees-first-dependency-source-relation-classifier.v1','problem':'decide whether the first dependency among embedded A4 coordinates is a nonzero quotient-kernel class','bold_conjecture':'the first dependent embedded coordinate combination represents a nonzero A4 quotient class killed at A5','rivals':['it is a genuine transition-kernel vector','it is already an A4 source relation','prime-dependent DAGs obscure a common exact identity'],'risky_consequences':'the reconstructed vector must not equal any exact A4 raw relation','strongest_falsification_attempt':{'reconstructed_coefficients':expected,'exact_identity':'(u-6)/q_g31^2 - 1/q_g31 = 0 because q_g31=u-y and y=6','relation_family':'q_multiplication','present_at_ambient_four':True,'prime_replays':[101,103,107]},'exact_residual':'the three-prime vector is exactly the existing g31 q-multiplication relation, so it is zero already in the A4 quotient','conjecture_disposition':'falsified','genuine_transition_kernel_candidate':False,'method_defect':'selecting the first dependency after adjoining all source coordinate units does not quotient out the 4146-dimensional A4 relation space','repair_acceptance':'first construct a faithful A4 quotient-complement basis, embed only those complement vectors into A5, and retain the first new dependence','scope':'classification of the first candidate only; the previously computed modular kernel dimension is unchanged','passed':True};(R/'cosmology_rees_first_dependency_source_relation_classifier.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
