#!/usr/bin/env python3
"""Solve the exact correction equation for the principal Čech obstruction."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];R=ROOT/'research/benincasa/results';d=json.loads((R/'cosmology_principal_wall_partial_fraction_cech_gate.json').read_text());M=d['edge_to_vertex_matrix'];obs=d['cech_boundary_obstruction'];target=[-x for x in obs]
def mv(x):return [sum(M[i][j]*x[j] for j in range(3)) for i in range(3)]
family=[{'t':t,'correction':[t,-t,t+2],'boundary':mv([t,-t,t+2])} for t in range(-4,5)];assert all(x['boundary']==target for x in family)
minimum=min(family,key=lambda x:(sum(abs(v) for v in x['correction']),max(abs(v) for v in x['correction'])));assert minimum['correction']==[0,0,2]
original=d['p_partial_fraction_pair_vector'];corrected=[original[i]+minimum['correction'][i] for i in range(3)];assert corrected==d['ordered_cech_face_boundary']
out={'schema':'marici.benincasa.cosmology-cech-correction-family.v1','problem':'determine whether the vertex obstruction has an algebraic correction compatible with the affine coefficient cell','bold_conjecture':'a source-compatible correction cancels the obstruction without replacing the affine partial-fraction coefficients','rivals':['no algebraic correction exists','a correction exists but changes the coefficient identity','source geometry supplies additional lower-stratum terms'],'risky_consequences':'the same correction must cancel the boundary and preserve the original coefficient vector','strongest_falsification_attempt':{'general_integer_correction':'(t,-t,t+2)','minimal_l1_correction':minimum['correction'],'required_boundary':target,'original_pair_vector':original,'corrected_pair_vector':corrected,'ordered_cech_vector':d['ordered_cech_face_boundary']},'exact_residual':'the minimal correction (0,0,2) cancels (0,2,-2) only by replacing the p partial-fraction vector (1,-1,-1) with the ordered Cech vector (1,-1,1)','conjecture_disposition':'falsified for coefficient-only correction','surviving_scope':'an algebraic correction family exists, but no member is source-authorized as an added vertex or bulk term preserving the affine identity','first_missing_typed_object':'a distinct source-derived lower-stratum cell carrying correction boundary (0,-2,2) without altering the affine pair coefficients','acceptance_test':'derive that cell independently, then verify ordered cancellation and twisted-de-Rham compatibility','passed':True};(R/'cosmology_cech_correction_family.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
