#!/usr/bin/env python3
"""DPC audit of exact coefficient provenance in actual Rees raw rows."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];B=ROOT/'research/benincasa';N=ROOT/'research/nima';R=B/'results'
prior=json.loads((R/'cosmology_rees_exact_integral_boundary_replay.json').read_text());assert prior['passed']
source=(B/'check_rank26_total_energy_triple_relation_module.py').read_text();caller=(N/'checkers/check_cosmology_p_normal_rank26_rees_census.py').read_text();base=(B/'physical_four_mark_residue_twisted_derham.py').read_text()
checks={'column_labels_are_structural_tuples':'label := (k_pole, *levels, monomial)' in source,'row_enumeration_is_deterministic':'for k_pole in range(charts.K_DEPTH)' in source and 'for axis in range(2)' in source,'raw_rows_emit_labels':False,'row_coefficients_reduced_on_insertion':'% base.PRIME' in source,'fiber_polynomials_are_prime_field':('PRIME =' in base or 'PRIME=' in base) and '% PRIME' in base,'half_twist_is_prime_dependent_inverse':"charts.GAMMA=-(pow(2,-1,prime))%prime" in caller,'caller_streams_unlabelled_row_dicts':'for rows in zip(*samples,check,strict=True)' in caller}
assert checks['column_labels_are_structural_tuples'] and checks['row_coefficients_reduced_on_insertion'] and checks['half_twist_is_prime_dependent_inverse']
out={'schema':'marici.benincasa.cosmology-rees-actual-row-integral-lift-interface.v1','problem':'determine whether actual raw Rees rows can be lifted from current modular receipts to exact labelled rows','bold_conjecture':'raw_relations preserves prime-independent row labels and exact integer or rational coefficients, including the half twist','rivals':['current modular rows suffice','source formulas can be rerun over an exact coefficient ring','cross-prime reconstruction can recover rows without row identities'],'risky_consequences':'a current row receipt must carry a stable source label and coefficients before modular reduction; half-twist values must share one rational normalization','strongest_falsification_attempt':checks,'exact_residual':'columns have stable tuple labels and loop order is deterministic, but rows have no explicit labels, coefficients are reduced modulo the active prime during construction, fiber polynomials already live in that field, and the half twist is inserted as a prime-dependent inverse of two','conjecture_disposition':'falsified for the current raw-row interface','survivor':'the source formulas and deterministic enumeration can support a new exact rational backend; existing modular row receipts cannot be uniquely lifted','existing_receipts_define_exact_rows':False,'exact_backend_constructible_from_source':True,'actual_integral_generator_constructed':False,'required_upgrade':['explicit row label from relation family and loop indices','coefficient-ring abstraction','rational half-twist normalization -1/2','exact input digest before reduction','mod-prime projection test against existing rows'],'next_conjecture':'a bounded exact-row backend reproduces actual modular raw rows at multiple primes from one rational source row','next_falsifier':'construct labelled rational rows for a bounded prefix and compare every projected coefficient at primes 101, 103, and 107','passed':True};(R/'cosmology_rees_actual_row_integral_lift_interface.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
