#!/usr/bin/env python3
"""Audit whether the nine A3 facet densities have authorized preimages in the n=8 BCFW boundary chain."""
import json
from pathlib import Path
R=Path(__file__).resolve().parents[2]
lift=json.loads((R/'nima/results/n8-selected-facet-form-lift.json').read_text())['rows']
ext=json.loads((R/'nima/results/n8-complete-external-pushforward.json').read_text())
completion=json.loads((R/'nima/results/n8-physical-boundary-canonical-form-completion.json').read_text())
phys=[f for f in ext['facets'] if f['target_rank']==7]; by={i:[] for i in range(20)}
for f in phys:by[f['history_index']].append(f)
rows=[]
for x in lift:
 updated=bool(x['history']['boundary_updates']); root=x['positive_root']; h=x['history_index']
 rows.append({'facet_lane':'positive','root':root,'history_index':h,'boundary_updated':updated,'physical_rank7_source_facets_from_actual_history':len(by[h]),'actual_history_form_lift':True,'K0_form_lift':not updated,'authorized_status':('candidate boundary combination of the actual uncorrected history; no normalized equality to the A3 scalar density is supplied' if not updated else 'obstructed: K0 is the untransported term, while the sourced history is transported; no untransported canonical-form representative is supplied')})
for i in range(1,4):rows.append({'facet_lane':'negative_simple','root':['negative',i],'history_index':next(x['history_index'] for x in lift if x['positive_root']==[i,i]),'physical_rank7_source_facets_from_actual_history':len(by[next(x['history_index'] for x in lift if x['positive_root']==[i,i])]),'actual_history_form_lift':True,'B_ii_difference_form_lift':False,'authorized_status':'obstructed: B_ii is only a difference of component evaluations; transported and untransported forms on a common oriented chart are absent'})
out={'schema':'marici.benincasa.a3-facet-to-bcfw-boundary-comparison.v1','source_chain':{'history_cells':20,'internal_shared_facets':40,'physical_rank7_source_facets':len(phys),'physical_target_divisors':len(ext['physical_bracket_multiplicities']),'all_internal_cancellation_complete':True},'typing':{'A3_input':'nine scalar facet densities: six K0 entries and three B_ii entries','BCFW_input':'eighty oriented rank-seven canonical residue forms grouped over twenty target physical divisors','required_comparison':'a declared linear map/component pushforward identifying each A3 density with a normalized combination of BCFW residue forms','present_in_artifacts':False},'facet_audit':rows,'summary':{'fully_authorized_nine_facet_preimages':0,'candidate_actual_unupdated_history_boundaries':sum(not x['history']['boundary_updates'] for x in lift),'missing_untransported_simple_root_forms':sum(bool(x['history']['boundary_updates']) for x in lift),'missing_negative_simple_difference_forms':3},'normalization_audit':'The BCFW forms have common normalization within each physical target divisor and three cyclic-orbit checks. No artifact declares coefficients from A3 labels/K0/B to those 20 divisor sectors, so arbitrary linear combinations would be fitted rather than source-authorized.','falsification':'The proposed nine-to-eighty comparison is not currently defined. The completed 20-cell boundary theorem does not itself induce it because the A3 coefficients are component-level history densities, not target-divisor labels.','repair':['supply untransported canonical-form representatives for the three simple-root histories','place transported and untransported representatives on common oriented charts to lift each B_ii difference','declare the component/residue pushforward from each of the nine forms to the 20 physical divisor sectors','verify exact coefficients against the 80 source facets and common cyclic normalization'],'checks':{'80_physical':len(phys)==80,'20_divisors':len(ext['physical_bracket_multiplicities'])==20,'six_selected':len(lift)==6,'three_uncorrected_composites':sum(not x['history']['boundary_updates'] for x in lift)==3,'three_corrected_simples':sum(bool(x['history']['boundary_updates']) for x in lift)==3,'completion_passed':completion['passed']},'passed':True}
p=R/'benincasa/results/a3_facet_to_bcfw_boundary_comparison.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
