#!/usr/bin/env python3
"""Exact deck and reciprocal transport of the endpoint divisor class."""

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / "research/benincasa/results/endpoint-torsion-native-transport.json"

# Ordered divisor basis: infinity+, zero+, infinity-, zero-.
tau = (1, -1, -1, 1)


def permute(vector, permutation):
    result = [0] * len(vector)
    for source, target in enumerate(permutation):
        result[target] += vector[source]
    return tuple(result)


# W -> -W exchanges sheets at fixed endpoint.
deck = (2, 3, 0, 1)
# t -> 1/t, together with x <-> y, exchanges zero and infinity on each sheet.
reciprocal = (1, 0, 3, 2)

deck_tau = permute(tau, deck)
reciprocal_tau = permute(tau, reciprocal)
combined_tau = permute(deck_tau, reciprocal)

minus_tau = tuple(-x for x in tau)
mod_two_tau = tuple(x % 2 for x in tau)

checks = {
    "deck_sends_integral_lift_to_negative": deck_tau == minus_tau,
    "reciprocal_sends_integral_lift_to_negative": reciprocal_tau == minus_tau,
    "combined_action_fixes_integral_lift": combined_tau == tau,
    "deck_fixes_two_torsion_class": tuple(x % 2 for x in deck_tau) == mod_two_tau,
    "reciprocal_fixes_two_torsion_class": (
        tuple(x % 2 for x in reciprocal_tau) == mod_two_tau
    ),
    "source_involutions_commute_on_divisors": (
        permute(permute(tau, deck), reciprocal)
        == permute(permute(tau, reciprocal), deck)
    ),
}
assert all(checks.values()), {k: v for k, v in checks.items() if not v}

packet = {
    "schema": "marici.endpoint-torsion-native-transport.v1",
    "basis": ["p_infinity_plus", "p_0_plus", "p_infinity_minus", "p_0_minus"],
    "tau_integral_lift": list(tau),
    "deck_tau": list(deck_tau),
    "reciprocal_tau": list(reciprocal_tau),
    "combined_tau": list(combined_tau),
    "torsion_relation": "2 tau = 0",
    "induced_action_on_Z_mod_2_tau": {
        "deck": "identity",
        "reciprocal": "identity",
        "deck_then_reciprocal": "identity",
    },
    "scope": (
        "Transport generated by sheet exchange and reciprocal endpoint exchange "
        "on the generic locus; no claim about additional discriminant braids."
    ),
    "checks": checks,
    "all_checks_pass": True,
}
OUT.write_text(json.dumps(packet, indent=2, sort_keys=True) + "\n", encoding="utf-8")

print(f"PASS {sum(checks.values())}/{len(checks)}")
print("deck", deck_tau, "reciprocal", reciprocal_tau, "combined", combined_tau)
print(OUT)
