#!/usr/bin/env python3
"""DPC search for chart-specific E6 occurrence connection artifacts."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];B=ROOT/'research/benincasa';R=B/'results'
prior=json.loads((R/'cosmology_E6_occurrence_line_connection_census.json').read_text());torsor=json.loads((R/'cyclic_leray_transition_torsor.json').read_text());radial=json.loads((B/'marked-radial-pullback-certificate.json').read_text());exc=json.loads((B/'rank12-u0-v2-exceptional-line.json').read_text());assert prior['passed']
frames=torsor['source_frames'];ids=[x for x in ('G12','G23','G31') if x in frames];assert len(ids)==3 and torsor['cocycle_product']=='1' and torsor['checks']['cech_cocycle_closes']
assert len(radial['charts'])==2 and exc['chart']=='p_nonzero'
out={'schema':'marici.benincasa.cosmology-E6-chart-specific-connection-artifact-search.v1','conjecture':'the source envelope contains three chart-specific e6 line restrictions with pullbacks to a common base','strongest_candidate':'cyclic_leray_transition_torsor.json','candidate_frame_ids':ids,'candidate_transition_count':len(torsor['transition_functions']),'candidate_cocycle_closes':True,'common_projective_coordinates':['X1','X2','X3'],'explicit_homogeneous_pullback_edges':1,'explicit_homogeneous_edge':'G31_to_G12','individual_E6_occurrence_connection_restrictions':0,'other_chart_candidates':{'marked_radial_pullback_chart_count':len(radial['charts']),'exceptional_line_chart':exc['chart']},'falsification_result':'the full three-restriction conjecture is falsified; no candidate gives three individual E6 line connection restrictions','revised_survivor':'a three-frame occurrence torsor with a closed transition cocycle and one explicit homogeneous logarithmic edge','survivor_does_not_prove':['horizontal A2-to-E6 grade comparison','full rank-twelve connection','selection of the transition class as extension shear'],'next_test':'test whether the cyclic Leray transition torsor itself defines the missing horizontal grade comparison or only an occurrence-descent class','passed':True};(R/'cosmology_E6_chart_specific_connection_artifact_search.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
