#!/usr/bin/env python3
"""Fix the exact strength, falsifier, and supersession boundary."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];R=ROOT/'research/benincasa/results'
def load(n):
 d=json.loads((R/n).read_text());assert d['passed'];return d
syn=load('cosmology_active_source_envelope_obstruction_synthesis.json');reopen=load('cosmology_obstruction_reopening_condition.json');status=load('cosmology_primitive_tau_current_source_envelope_status.json')
assert not syn['source_authorized_primitive_integral_route_exists'];assert syn['not_a_global_impossibility_theorem'];assert not reopen['complete_sufficient_condition'];assert status['current_disposition'].lower().rstrip('.')==syn['strongest_result'].lower().rstrip('.')
chain=reopen['typed_derivation_chain']
out={'schema':'marici.benincasa.cosmology-final-source-envelope-strength-boundary.v1','conjecture':'the exact strongest conclusion is active-envelope nonexistence with a typed primitive-chain falsifier','fixed_envelope_claim':syn['strongest_result'],'claim_strength':'source-envelope nonexistence','excluded_overstatement':'global impossibility across future source enlargements','excluded_understatement':'mere failure to find a gauge; parity, equivariance, source authority, comparison, and base-map routes were each obstructed','fixed_envelope_internal_falsifier':'an already-admitted but omitted source-authorized chain G->C->T->Q->R carrying a primitive generator to [1,1] in the untwisted integral target','future_envelope_supersession':'a newly source-authorized chain with the same properties enlarges the envelope and supersedes rather than retroactively falsifies the fixed-envelope audit','required_chain_objects':chain,'required_tests':['source-labelled support and generator','integral chain map with d^2=0 and routing','base-compatible transport and relative pairing','canonical weighted specialization and Xi projection','primitive image [1,1]','untwisted integral physical readout with orientation authority'],'conditional_data_not_promoted':status['established'],'conjecture_disposition':'retained after strength audit','objective_disposition':'strongest typed obstruction established under the active source envelope','next_conjecture':'an envelope delta reopens the programme only if it supplies at least one previously missing typed arrow or a complete primitive chain','next_falsifier':'audit each new source artifact against the missing-arrow list; reject relevance-by-proximity','passed':True};(R/'cosmology_final_source_envelope_strength_boundary.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
