#!/usr/bin/env python3
"""DPC memory bound for all-pivot Rees provenance certificates."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];R=ROOT/'research/benincasa/results';N=ROOT/'research/nima/results'
prior=json.loads((R/'cosmology_rees_modular_provenance_prototype.json').read_text());assert prior['passed']
d=json.loads((N/'cosmology_p_normal_rank26_rees_census_half_x_p32003.json').read_text());assert d['passed']
n=d['raw_relation_count'];r=d['relation_ranks'];rows={'special':n,'dual':2*n,'triple':3*n};ranks={k:r[k] for k in rows}
# Dense provenance uses one (row_id, coefficient) pair of two u32 values per entry.
entries={k:rows[k]*ranks[k] for k in rows};bytes_by_kind={k:8*v for k,v in entries.items()};total=sum(bytes_by_kind.values())
assert total==4_689_079_680
out={'schema':'marici.benincasa.cosmology-rees-provenance-memory-scaling-bound.v1','problem':'decide whether retaining every sparse provenance vector is feasible for the full Rees presentation','bold_conjecture':'provenance density remains bounded enough for direct all-pivot retention or is already controlled by the current interface','rivals':['direct sparse vectors','dense all-pivot vectors','checkpointed elimination DAG with replay','target-only certificate extraction'],'risky_consequences':'the existing receipts must contain density or operation counts for a feasibility conclusion; dense storage provides a hard raw-payload ceiling','strongest_falsification_attempt':{'column_count':d['column_count'],'raw_relation_count':n,'relation_rows':rows,'relation_ranks':ranks,'dense_provenance_entries':entries,'dense_raw_bytes_by_kind':bytes_by_kind,'dense_raw_bytes_total':total,'dense_raw_gib':total/(1024**3),'excludes_hashmap_and_allocator_overhead':True},'exact_residual':'the dense raw payload is 4,689,079,680 bytes before container overhead, while current receipts report no provenance density or elimination-operation count','conjecture_disposition':'revised; direct feasibility is unestablished','survivor':'the exact dense ceiling is finite, but the bounded prototype does not predict full density; checkpointed or target-only replay remains a rival architecture','measured_full_provenance_density':False,'full_run_authorized_or_launched':False,'next_conjecture':'instrumenting reduction counts and pivot-support densities on bounded prefixes is sufficient to choose between direct vectors and checkpointed replay','next_falsifier':'add count-only instrumentation and test whether operation or support growth invalidates the projected architecture','passed':True};(R/'cosmology_rees_provenance_memory_scaling_bound.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
