#!/usr/bin/env python3
"""PS1A0: test each signed-minor axis against its matching marked-cut continuation."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
chain=json.loads((ROOT/'research/benincasa/three-cut-relative-chain-pairing-certificate.json').read_text());lifts=json.loads((ROOT/'research/benincasa/physical-cycle-endpoint-normal-lifts.json').read_text());unique=(ROOT/'research/benincasa/published_boundary_value_leray_uniqueness.md').read_text()
marked=chain['marked_cuts'];incidence={'c=0':{'cut':'q_G12','equation':marked['q_G12'],'limit':'c=-E -> 0','jacobian':'dc','multiplicity':1},'a=0':{'cut':'q_G23','equation':marked['q_G23'],'limit':'a=-E -> 0','jacobian':'da','multiplicity':1},'b=0':{'cut':'q_G31','equation':marked['q_G31'],'limit':'b=-E -> 0','jacobian':'db','multiplicity':1}}
checks={'three_matching_cuts':marked=={'q_G12':'E+c','q_G23':'E+a','q_G31':'E+b'},'three_axis_faces':{x['endpoint'] for x in lifts['checks']}==set(incidence),'endpoint_lifts_tangent':lifts['incidence_tangency_checks']==9,'negative_imaginary_orientation_unique':'multiplicity one' in unique and 'Im}q<0' in unique,'unit_transverse_jacobians':all(x['multiplicity']==1 for x in incidence.values())}
assert all(checks.values()),checks
out={'schema':'marici.benincasa.PS1A0-alternate-signed-minor-incidence.v1','prospective_action':'PS1A0_axis_incidence','outcome_contract':{'++':'each endpoint axis is reached transversely by its matching source marked-cut continuation','+-':'some but not all axes are reached','-+':'matching marked cuts miss the axes','--':'incidence cannot be typed'},'resolution':'++','incidence':incidence,'distinction_from_failed_channel':'VC2m1 tested a=0,b=0 against the q_G12 marked-corner blowup centered at (a,b)=(y,x), which they miss. PS1A0 instead uses the matching q_G23 and q_G31 cuts, whose equations directly specialize to those axes.','established':'All three axes have source-oriented transverse marked-cut germs with unit local multiplicity.','withheld':'Incidence does not yet glue the three local germs into one global physical relative current or pair it with the degree-15 correction.','next':'PS1A1 construct the three matching source Leray germs and compare their oriented boundary vector with the degree-15 collar correction.','checks':checks,'passed':True};p=ROOT/'research/benincasa/results/PS1A0_alternate_signed_minor_incidence.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'resolution':'++','axes':3,'multiplicities':[1,1,1],'next':'PS1A1_matching_source_Leray_germs'}))
