#!/usr/bin/env python3
"""PS1C1: audit executability of the mixed-log physical Betti/Leray realization."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
audit=json.loads((ROOT/'research/voevodsky/results/mixed_log_physical_Betti_realization_audit.json').read_text());c15=json.loads((ROOT/'research/voevodsky/results/C15_canonical_physical_mixed_detector.json').read_text())
checks={'candidate_matches':audit['requested_candidate'].startswith('Theta101'),'existing_audit_invalid':audit['resolution']=='--','global_primitive_known':audit['checks']['Theta101_has_global_meromorphic_primitive'],'naive_pairing_rejected':audit['checks']['naive_contraction_does_not_descend'],'GM_connection_missing':audit['checks']['GM_pairing_still_missing'],'canonical_symmetric_detector_rejected':c15['C15a_status']=='rejected','antisymmetric_detector_open':c15['C15b_status']=='open'}
assert all(checks.values()),checks
out={'schema':'marici.benincasa.PS1C1-physical-Betti-Leray-realization.v1','prospective_action':'PS1C1_physical_Betti_Leray_realization','outcome_contract':{'++':'source-oriented Leray tube realizes Theta101 physically','+-':'moving-wall horizontal class exists but global pairing remains open','-+':'physical realization is obstructed','--':'required residue-compatible moving-wall connection is absent'},'resolution':'--','reason':audit['reason'],'typing_correction':'The algebraic v0 coordinate cannot be contracted directly into a physical scalar; that would fail gauge descent.','missing_interface':audit['missing_interface'],'refinement':['PS1C1a_moving_wall_residue_totalization','PS1C1b_orientation_twisted_GM_connection','PS1C1c_source_Leray_tube_pairing'],'parent_branch':'PS1C remains unresolved; -- is an executability failure, not a negative terminal specialization.','next':'Run the cheapest next-rung gate PS1C1a before attempting the connection or pairing.','checks':checks,'passed':True};p=ROOT/'research/benincasa/results/PS1C1_physical_Betti_Leray_realization.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'resolution':'--','missing':out['missing_interface'],'next':out['refinement'][0]}))
