#!/usr/bin/env python3
"""PS1M3: compare the typed PS1A class with the proposed nearby-cycle route."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
def load(p):return json.loads((ROOT/p).read_text())
sig=load('research/benincasa/results/PS1M1_Leray_Cech_homology_signature.json');mapping=load('research/benincasa/results/PS1M2a_degree15_to_nearby_column_map.json');m0=load('research/benincasa/results/PS1M0_realization_moduli_executability.json')
checks={'PS1A_signature_nonzero':sig['resolution']=='++' and sig['augmentation_signature']!=0,'nearby_map_rejected':mapping['resolution']=='-+','only_common_line_known':mapping['fixed_comparison']['rank']==1,'candidate_packet_not_a_typed_realization':'not yet a second degree-15 realization' in mapping['consequence'],'existence_not_uniqueness':m0['resolution']=='+-'}
assert all(checks.values()),checks
out={'schema':'marici.benincasa.PS1M3-realization-class-comparison.v1','prospective_action':'PS1M3_compare_realization_classes','outcome_contract':{'++':'PS1A and nearby constructions have equal normalized relative-homology/monodromy signatures','+-':'one class is typed but the alternative lacks the comparison map, so equality and distinction are both undecidable','-+':'both classes are typed and have unequal invariant signatures','--':'the admitted PS1A class lacks a comparison invariant'},'resolution':'+-','typed_realizations':[{'name':'PS1A_Leray_Cech','H0_augmentation':sig['augmentation_signature'],'common_coefficient':sig['normalized_common_coefficient']}],'untyped_candidate_packets':[{'name':'cut_nearby','known_overlap':'primitive e6 line','missing':'chain-level natural transformation from degree-15 presentation'}],'classification_bounds':{'at_least':1,'typed_distinct_count':1,'uniqueness_proved':False,'second_realization_proved':False},'logical_conclusion':'There is one established physical realization. Current evidence supports neither “there is exactly one” nor “there are multiple.” Equality cannot be inferred from a shared line, and difference cannot be inferred from presentation mismatch.','next':'Close PS1M census with cardinality lower bound one and uniqueness status open; register the chain-level natural transformation as the sole reopening interface.','checks':checks,'passed':True};p=ROOT/'research/benincasa/results/PS1M3_realization_class_comparison.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'resolution':'+-','typed_realizations':1,'uniqueness':None,'multiple':None,'next':'PS1M_realization_moduli_classification'}))
