#!/usr/bin/env python3
"""DPC audit: does the cyclic Leray torsor determine a horizontal E6 comparison?"""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];R=ROOT/'research/benincasa/results'
t=json.loads((R/'cyclic_leray_transition_torsor.json').read_text());search=json.loads((R/'cosmology_E6_chart_specific_connection_artifact_search.json').read_text());cmp=json.loads((R/'cosmology_qtop_A2_to_E6_grade_comparison.json').read_text());assert search['passed'] and cmp['passed']
assert t['cocycle_product']=='1' and len(t['source_frames'])>=3 and len(t['transition_functions'])==3
edge=t['homogeneous_G31_to_G12'];assert edge['logarithmic_connection']=='-2/(v*(v - 2))' and edge['residue_vector_v0_v2']==['1','-1']
out={'schema':'marici.benincasa.cosmology-cyclic-Leray-torsor-horizontal-comparison.v1','conjecture':'the closed three-frame torsor and one logarithmic edge determine a horizontal A2-to-E6 comparison','risky_consequence':'the torsor must select local connection forms rather than only their gauge differences','falsifier':'exhibit two distinct compatible connection families on the same transition cocycle','torsor_determines':'transition functions and the differences A_j-A_i=dlog(g_ij)','torsor_does_not_determine':'a common additive global one-form shared by all A_i','nonzero_global_shift_candidate':{'form':'dlog(v/(v-2))','residues':['1','-1']},'affine_freedom_test':'if {A_i} is compatible, then {A_i+omega} has identical transition residuals for every global omega','distinct_compatible_families_exist':True,'conjecture_disposition':'falsified','revised_survivor':'the torsor source-types occurrence descent and relative logarithmic connection differences, not an absolute horizontal comparison','E6_restriction_match_verified':False,'rank12_shear_selected':False,'next_conjecture':'the C2 normalization together with the known E6 corner coefficient fixes the additive global one-form','next_falsifier':'construct a nonzero allowed global logarithmic shift preserving that normalization and corner datum, or prove none exists','passed':True};(R/'cosmology_cyclic_Leray_torsor_horizontal_comparison.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
