#!/usr/bin/env python3
"""Audit the contractible-pair repair of Gamma physical descent."""
import json, math
from pathlib import Path
rank_R=26;rank_E=27
boundary_coordinates=(1,-1)
primitive=math.gcd(*(abs(z) for z in boundary_coordinates))==1
assert primitive
rank_R_mod_boundary=rank_R-1
assert rank_R_mod_boundary==25
out={'schema':'marici.benincasa.cosmology-gamma-boundary-pair-cancellation-dpc.v1','problem':'Can killing the differential-closed pair generated by Gamma and D(Gamma) repair physical descent while retaining the original rank-26 target?','bold_conjecture':'Replacing the invalid Gamma-only quotient by cancellation of the pair Gamma -> (Xi_rel,-sigma123) yields the original rank-26 complex R.','named_rivals':['the boundary class is primitive and its quotient lowers R rank to 25','the two-term pair is contractible but its quotient is not literally R','a quasi-isomorphism does not provide the claimed canonical rank-26 identification'],'risky_consequences':['quotienting R by the boundary must preserve rank 26','the boundary class must vanish or be nonprimitive torsion'],'strongest_falsification_attempt':{'rank_R':rank_R,'rank_E':rank_E,'boundary_coordinates_in_declared_pair_basis':list(boundary_coordinates),'boundary_primitive':primitive,'rank_after_quotienting_boundary':rank_R_mod_boundary,'killed_pair':['Gamma','Xi_rel-minus-sigma123']},'disposition':{'status':'falsified as a rank-26 identification','residual':'the valid subcomplex kernel contains both Gamma and its primitive boundary, so its lower-degree quotient has rank 25 rather than 26','surviving_scope':'the Gamma-boundary pair may be contractible and cancellable up to quasi-isomorphism, but that does not identify the quotient with the original R','reopening_test':'provide a degree-resolved physical complex and an explicit chain equivalence whose target ranks and differentials are computed; generator counting alone cannot restore R'},'passed':True};R=Path(__file__).resolve().parents[1]/'results';(R/'cosmology_gamma_boundary_pair_cancellation_dpc.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
