#!/usr/bin/env python3
"""Build the source Bockstein-to-sheet specialization cone and compute homology."""

from __future__ import annotations

import importlib
import json
import os
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[3]
P = int(os.environ.get("MARICI_FIELD_PRIME", "32009"))
suffix = "" if P == 32009 else f"-p{P}"
OUT = ROOT / "research" / "benincasa" / "results" / f"rank26-conductor-specialization-cone-homology{suffix}.json"
os.environ["MARICI_FIELD_PRIME"] = str(P)
sys.path.insert(0, str(ROOT / "research" / "benincasa"))
base = importlib.import_module("physical_four_mark_residue_twisted_derham")


def rank(vectors: list[dict[int,int]]) -> int:
    pivots = {}
    for vector in vectors:
        base.add_pivot({c:value%P for c,value in vector.items() if value%P}, pivots)
    return len(pivots)


def dot(row, vector):
    return sum(row.get(j,0)*value for j,value in vector.items())%P


def root(n):
    return next(r for r in range(1,P) if r*r%P==n)


def proportional_scalar(left, right):
    coordinates=sorted(set(left)|set(right))
    pivot=next(c for c in coordinates if right.get(c,0))
    scalar=left.get(pivot,0)*pow(right[pivot],-1,P)%P
    if any(left.get(c,0)!=scalar*right.get(c,0)%P for c in coordinates): return None
    return scalar


packet_path=ROOT/"research"/"benincasa"/"results"/f"rank26-conductor-gamma-bockstein{suffix}.json"
packet=json.loads(packet_path.read_text(encoding="utf-8"))
relations=[{int(c):int(v)%P for c,v in vector.items()} for vector in packet["relation_vectors"]]
bocksteins=[{int(c):int(v)%P for c,v in vector.items()} for vector in packet["bockstein_vectors"]]
visible=packet["root_visible_relation_index"]
beta_generator=bocksteins[visible]
beta_scalars=[proportional_scalar(vector,beta_generator) if vector else 0 for vector in bocksteins]

x,y,z=2,3,4
monomials=[(i,j) for i in range(7) for j in range(7-i)]
C1=x*x*y+x*x*z+x*y*y+2*x*y*z+2*x*z*z-y**3-y*y*z+y*z*z+z**3
C2=x**3-x*x*y+x*x*z-x*y*y-2*x*y*z-x*z*z-y*y*z-2*y*z*z-z**3
r1=root(C1*pow(x,-1,P)%P); r2=root(-C2*pow(y,-1,P)%P)
b1=(y+z)%P; a2=(x+z)%P

def weight1(a):
    d=(-2*x*a)%P
    for factor in (a-x-z,a+y+2*z,y+z-x,a-y): d=d*factor%P
    return pow(d,-1,P)

def weight2(b):
    d=(2*y*b)%P
    for factor in (b-y-z,x+2*z+b,b-x,x+z-y): d=d*factor%P
    return (b+z-y)*pow(d,-1,P)%P

sheet_rows=[]
for a in (r1,-r1%P):
    w=weight1(a); sheet_rows.append({j:w*pow(a,i,P)*pow(b1,k,P)%P for j,(i,k) in enumerate(monomials)})
for b in (r2,-r2%P):
    w=weight2(b); sheet_rows.append({j:w*pow(a2,i,P)*pow(b,k,P)%P for j,(i,k) in enumerate(monomials)})

# C=[R -> N], D=[B -> S].  B is generated by beta(r_visible), and
# d_D sends that generator to the complete four-sheet defect vector.
sheet_on_relations=[{s:dot(sheet_rows[s],relation) for s in range(4)} for relation in relations]
lambda_vector=sheet_on_relations[visible]
chain_residuals=[]
for i in range(2):
    expected={s:beta_scalars[i]*lambda_vector.get(s,0)%P for s in range(4)}
    residual={s:(sheet_on_relations[i].get(s,0)-expected.get(s,0))%P for s in range(4)}
    chain_residuals.append({s:v for s,v in residual.items() if v})

# Explicit homology dimensions.
rank_dC=rank(relations)
rank_dD=rank([lambda_vector])
sheet_columns=[{s:sheet_rows[s][j] for s in range(4) if sheet_rows[s][j]} for j in range(len(monomials))]
rank_J=rank(sheet_columns)
rank_J_plus_boundary=rank(sheet_columns+[lambda_vector])
induced_rank=rank_J_plus_boundary-rank_dD

# Hostile change of relation basis.  The same fixed B generator must retain
# the chain identity without selecting a new visible representative.
change=((1,1),(1,2))
changed_relations=[]; changed_beta=[]
for row in change:
    relation={}; scalar=0
    for coefficient,source in zip(row,relations):
        for c,v in source.items():
            value=(relation.get(c,0)+coefficient*v)%P
            if value: relation[c]=value
            else: relation.pop(c,None)
    for coefficient,value in zip(row,beta_scalars): scalar=(scalar+coefficient*value)%P
    changed_relations.append(relation); changed_beta.append(scalar)
changed_residuals=[]
for relation,scalar in zip(changed_relations,changed_beta):
    image={s:dot(sheet_rows[s],relation) for s in range(4)}
    changed_residuals.append({s:(image[s]-scalar*lambda_vector.get(s,0))%P for s in range(4) if (image[s]-scalar*lambda_vector.get(s,0))%P})

# Full cochain mapping cone Cone(f):
# R[-2] -> (B direct_sum N)[-1] -> S4[0].
# d_-2(r)=(beta(r),-r), d_-1(b,n)=lambda*b+J(n).
cone_dminus2=[]
for relation,scalar in zip(relations,beta_scalars):
    column={0:scalar}
    for j,value in relation.items():
        if value: column[1+j]=(-value)%P
    cone_dminus2.append(column)
cone_dminus1=[dict(lambda_vector)]+sheet_columns
cone_square_residuals=[]
for column in cone_dminus2:
    image={}
    for middle_index,coefficient in column.items():
        target_column=cone_dminus1[middle_index]
        for s,value in target_column.items():
            image[s]=(image.get(s,0)+coefficient*value)%P
    cone_square_residuals.append({s:v for s,v in image.items() if v})
rank_cone_dminus2=rank(cone_dminus2)
rank_cone_dminus1=rank(cone_dminus1)
cone_hminus2=2-rank_cone_dminus2
cone_hminus1=(29-rank_cone_dminus1)-rank_cone_dminus2
cone_h0=4-rank_cone_dminus1

# The defect vector lambda is a degree-zero boundary with the canonical
# coherence primitive (1_B,0_N).  Cyclic Entry 3911 units transport it to itself.
primitive={0:1}
primitive_boundary=dict(cone_dminus1[0])
primitive_residual={s:(primitive_boundary.get(s,0)-lambda_vector.get(s,0))%P for s in range(4)}
primitive_residual={s:v for s,v in primitive_residual.items() if v}
cyclic_suffix="" if P==32009 else f"-p{P}"
cyclic_path=ROOT/"research"/"benincasa"/"results"/f"rank26-dual-gamma-cyclic-atlas-closure{cyclic_suffix}.json"
cyclic_units=json.loads(cyclic_path.read_text(encoding="utf-8"))["bockstein_line_edge_units"]
primitive_cyclic_product=1
for unit in cyclic_units: primitive_cyclic_product=primitive_cyclic_product*unit%P

checks={
    "source_relation_complex_has_h0_rank26": len(monomials)-rank_dC==26 and rank_dC==2,
    "naive_sheet_chain_defect_rank_one": rank(sheet_on_relations)==1,
    "bockstein_map_rank_one": rank([vector for vector in bocksteins if vector])==1,
    "chain_map_identity_holds": chain_residuals==[{},{}],
    "boundary_is_injective": rank_dD==1,
    "target_hminus1_vanishes": 1-rank_dD==0,
    "target_h0_rank_three": 4-rank_dD==3,
    "one_and_only_one_sheet_direction_becomes_exact": rank_dD==rank(sheet_on_relations)==1,
    "induced_readout_surjects_on_target_h0": induced_rank==3,
    "relation_basis_change_preserves_chain_identity": changed_residuals==[{},{}],
    "full_cone_square_zero": cone_square_residuals==[{},{}],
    "full_cone_differential_ranks_are_2_and_4": (rank_cone_dminus2,rank_cone_dminus1)==(2,4),
    "full_cone_homology_is_0_23_0": (cone_hminus2,cone_hminus1,cone_h0)==(0,23,0),
    "sheet_defect_has_explicit_B_primitive": primitive_residual=={},
    "primitive_cyclic_transport_is_identity": primitive_cyclic_product==1,
}
payload={
    "schema":"marici.rank26-conductor-specialization-cone-homology.v1",
    "prime":P,
    "source_complex":{"degrees":{"minus_one":2,"zero":28},"differential_rank":rank_dC,"homology":{"minus_one":0,"zero":26}},
    "target_complex":{"degrees":{"minus_one":1,"zero":4},"differential_rank":rank_dD,"homology":{"minus_one":0,"zero":3}},
    "beta_scalars_on_relation_basis":beta_scalars,
    "weighted_sheet_boundary":{str(s):v for s,v in sorted(lambda_vector.items())},
    "chain_residuals":[{str(s):v for s,v in residual.items()} for residual in chain_residuals],
    "naive_sheet_defect_rank":rank(sheet_on_relations),
    "sheet_map_rank":rank_J,
    "sheet_plus_boundary_rank":rank_J_plus_boundary,
    "induced_h0_readout_rank":induced_rank,
    "hostile_relation_basis_change":change,
    "hostile_change_residuals":[{str(s):v for s,v in residual.items()} for residual in changed_residuals],
    "mapping_cone":{
        "graded_dimensions":{"minus_two":2,"minus_one":29,"zero":4},
        "differential_ranks":{"minus_two_to_minus_one":rank_cone_dminus2,"minus_one_to_zero":rank_cone_dminus1},
        "square_zero_residuals":[{str(s):v for s,v in residual.items()} for residual in cone_square_residuals],
        "homology":{"minus_two":cone_hminus2,"minus_one":cone_hminus1,"zero":cone_h0},
        "d_minus_two_columns":[{str(c):v for c,v in sorted(column.items())} for column in cone_dminus2],
        "d_minus_one_columns":[{str(c):v for c,v in sorted(column.items())} for column in cone_dminus1],
    },
    "defect_primitive":{
        "middle_degree_vector":{"B":1,"N":{}},
        "boundary":{str(s):v for s,v in sorted(primitive_boundary.items())},
        "target_defect":{str(s):v for s,v in sorted(lambda_vector.items())},
        "residual":{str(s):v for s,v in primitive_residual.items()},
        "cyclic_edge_units":cyclic_units,
        "cyclic_product":primitive_cyclic_product,
    },
    "checks":checks,
    "passed":all(checks.values()),
    "conclusion":"The gamma-Bockstein line and four weighted sheets form a genuine target complex, and the full three-term mapping cone has square-zero differential ranks (2,4) and homology (0,23,0). The sheet-defect vector is the boundary of the explicit B primitive, whose cyclic transport is identity. The residual rank 23 is exactly the kernel of the descended rank-three readout from the rank-26 absolute quotient.",
}
OUT.write_text(json.dumps(payload,indent=2)+"\n",encoding="utf-8")
print(json.dumps(payload,indent=2))
if not payload["passed"]: raise SystemExit(1)
