#!/usr/bin/env python3
"""PS1C1a: assemble the universal one/two-wall relative residue totalization."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
one=json.loads((ROOT/'research/benincasa/one-wall-universal-cleared-certificate.json').read_text());two=json.loads((ROOT/'research/benincasa/two-wall-universal-filtered-residue.json').read_text());cospan=json.loads((ROOT/'research/voevodsky/results/C4_log_Cut_Gysin_cospan.json').read_text())
checks={'same_open_locus':one['open_locus']==two['open_locus']=='x*y*(x+y)!=0','Theta101_relative_primitive_exact':one['certificate']['verified_remaining_terms']==0,'Theta110_by_exchange':one['symmetric_W2']['status']=='universal by pullback of cleared identity','two_wall_incidence_exact':two['incidence_class']['remaining_terms']==0 and two['incidence_class']['identity']=='d eta_inc=G da wedge db','filtered_tail_closes':two['tail_relation'].endswith('=0'),'integral_overlap_cospan_commutes':cospan['checks']['square_commutes'],'no_new_carrier':one['classification']['new_carrier_datum'] is False and two['result']['new_carrier_datum'] is False}
assert all(checks.values()),checks
out={'schema':'marici.benincasa.PS1C1a-moving-wall-residue-totalization.v1','prospective_action':'PS1C1a_moving_wall_residue_totalization','base':'Spec Q[x,y,1/(x*y*(x+y))]','relative_fibers':'(a,b) with moving walls W1:{b+x=0}, W2:{a+y=0}','total_complex':{'bulk_generators':['Theta101','Theta110','Theta111_filt'],'one_wall_primitives':['eta101','eta110'],'two_wall_homotopy':'eta_inc','composite_top_primitive':'eta111_rat','relative_differential_identities':['d_rel eta101=Theta101','d_rel eta110=Theta110','d_rel eta_inc=Omega111-Omega101/(2y)-Omega110/(2x)'],'integral_overlap_constraint':'2*Theta111_filt maps to the common 2*e6 line'},'resolution':'++','established':'A universal relative residue/Cech totalization exists over Q(x,y), including both moving one-wall primitives and their two-wall incidence homotopy.','withheld':'No horizontal connection in the x,y directions is asserted; d_rel closure does not imply Gauss-Manin horizontality or a physical period.','interface_added':'moving_wall_residue_totalization','next':'PS1C1b compute the orientation-twisted Gauss-Manin connection on this total complex.','checks':checks,'passed':True};p=ROOT/'research/benincasa/results/PS1C1a_moving_wall_residue_totalization.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'resolution':'++','generators':3,'one_wall_primitives':2,'next':out['next']}))
