#!/usr/bin/env python3
"""PS1M1: encode the admitted witness in the integral three-cut Cech lattice."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3]
w=json.loads((ROOT/'research/benincasa/results/PS1A_alternate_signed_minor_specialization.json').read_text());a2=json.loads((ROOT/'research/benincasa/results/PS1A2_global_marked_cut_Cech_gluing.json').read_text());a2c=json.loads((ROOT/'research/benincasa/results/PS1A2c_correct_Cech_pair_weights.json').read_text())
v=w['global_current']['vertex_Leray_coefficients'];augmentation=sum(v);assert augmentation%3==0;m=augmentation//3;diag=[m]*3;gauge=[v[i]-m for i in range(3)]
# Oriented edge chain ca,cb,ab with boundary (-x-y,x-z,y+z)=gauge.
edge_chain=[gauge[1],gauge[2],0];boundary=[-edge_chain[0]-edge_chain[1],edge_chain[0]-edge_chain[2],edge_chain[1]+edge_chain[2]];pair=w['global_current']['pair_double_Leray_coefficients']
checks={'terminal_witness_admitted':w['resolution']=='++','connected_three_cut_cover':len(v)==3 and len(pair)==3,'integral_symmetric_representative':augmentation%3==0,'gauge_is_zero_sum':sum(gauge)==0,'gauge_is_integral_boundary':boundary==gauge,'Cech_pair_cocycle_closed':w['global_current']['triple_Cech_boundary']==0,'signature_nonzero':m!=0}
assert all(checks.values()),checks
out={'schema':'marici.benincasa.PS1M1-Leray-Cech-homology-signature.v1','prospective_action':'PS1M1_encode_Leray_Cech_homology_signature','outcome_contract':{'++':'PS1A witness has a canonical nonzero integral class in the connected three-cut Cech quotient','+-':'a rational but not integral quotient signature exists','-+':'the admitted packet is quotient-trivial','--':'no common integral Cech lattice can be typed'},'resolution':'++','lattice':{'C0_basis':['q_G12/c','q_G23/a','q_G31/b'],'C1_basis':['ca','cb','ab'],'boundary_formula':'partial(x_ca,x_cb,x_ab)=(-x_ca-x_cb,x_ca-x_ab,x_cb+x_ab)','H0':'Z via augmentation'},'vertex_vector':v,'augmentation_signature':augmentation,'symmetric_diagonal_representative':diag,'normalized_common_coefficient':m,'zero_sum_gauge_part':gauge,'gauge_edge_chain':edge_chain,'independent_transition_cocycle':pair,'interpretation':'Within the frozen connected three-cut cover, all chart-dependent endpoint imbalance is integral boundary/gauge data. The realization carries the nonzero common quotient coefficient 8105232304.','comparison_interface':'Compare a nearby-cycle candidate by mapping its occurrence/conductor lattice to the same oriented H0 generator; equality requires the same augmentation normalization, not merely the same rational line.','next':'PS1M2 project the cut-nearby packet to the degree-15 correction and compute its oriented integral augmentation.','checks':checks,'passed':True};p=ROOT/'research/benincasa/results/PS1M1_Leray_Cech_homology_signature.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'resolution':'++','augmentation':augmentation,'common_coefficient':m,'gauge_boundary':True,'next':'PS1M2_project_nearby_cycle_to_degree15'}))
