use std::fs;

#[derive(Clone,Copy,Debug,PartialEq,Eq)]
struct C{r:i64,i:i64}
fn add(a:C,b:C)->C{C{r:a.r+b.r,i:a.i+b.i}}
fn sub(a:C,b:C)->C{C{r:a.r-b.r,i:a.i-b.i}}
fn scale(a:C,n:i64)->C{C{r:n*a.r,i:n*a.i}}
fn mul_i(a:C)->C{C{r:-a.i,i:a.r}}

fn main(){
 let mut checks=0_u64;
 for a0 in -2..=2 {for b0 in -2..=2 {for a1 in -2..=2 {for b1 in -2..=2 {
 for a2 in -2..=2 {for b2 in -2..=2 {for a3 in -2..=2 {for b3 in -2..=2 {
   let h00=C{r:a0,i:b0};let h01=C{r:a1,i:b1};
   let h10=C{r:a2,i:b2};let h11=C{r:a3,i:b3};
   let qx=add(add(h00,h11),add(h01,h10));
   let symmetric=sub(qx,add(h00,h11));
   let first=mul_i(sub(h01,h10));
   for e in 1_i64..=4 {
     // Effect generated by |0>+(1+i epsilon)|1>.
     let qeps=add(qx,add(scale(first,e),scale(h11,e*e)));
     let reduced=sub(sub(qeps,qx),scale(h11,e*e));
     assert_eq!(reduced,scale(first,e));
     assert_eq!(sub(symmetric,mul_i(first)),scale(h01,2));
     assert_eq!(add(symmetric,mul_i(first)),scale(h10,2));
     checks+=3;
   }
 }}}}}}}}
 let output=format!(concat!(
 "{{\n",
 "  \"schema\": \"marici.degenerate_tomography_rees.v1\",\n",
 "  \"exact_checks\": {},\n",
 "  \"zeroth_grade_rank\": 3,\n",
 "  \"first_grade_rank_gain\": 1,\n",
 "  \"first_grade\": \"i(h01-h10)\",\n",
 "  \"second_grade\": \"h11\",\n",
 "  \"full_matrix_recovered_from_labelled_jet\": true,\n",
 "  \"unparametrized_tangent_sufficient\": false,\n",
 "  \"new_cut_carrier_stratum\": false\n",
 "}}\n"),checks);
 fs::write("research/benincasa/results/degenerate-tomography-rees.json",output).unwrap();
}
