"""Genus audit for generic marked sections of the four-site infinity boundary."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / "research/benincasa/results/four-site-marked-sections-elliptic.json"

# X -> P2 is a double cover branched over a quartic.  A source denominator
# is linear in edge variables, so its infinity section is a line L in P2.
# Generically L meets the branch quartic in four simple points.
cover_degree = 2
branch_points = 4
base_genus = 0

# Riemann-Hurwitz: 2g(C)-2 = d(2g(L)-2) + r.
lhs = cover_degree * (2 * base_genus - 2) + branch_points
genus = (lhs + 2) // 2
assert lhs == 0 and genus == 1

# Adjunction cross-check: C=pi^*H=-K_X, so C.(C+K_X)=0.
anticanonical_square = 2
adjunction_degree = anticanonical_square - anticanonical_square
assert adjunction_degree == 0

packet = {
    "schema": "marici.benincasa.four_site_marked_sections_elliptic.v1",
    "surface": "degree-two del Pezzo double cover of P2 branched over a quartic",
    "source_mark_type": "linear cosmological denominator q_g",
    "infinity_image": "line L in P2",
    "generic_branch_intersections": branch_points,
    "marked_curve_cover_degree": cover_degree,
    "marked_curve_genus": genus,
    "marked_curve_class": "pi^*H=-K_X",
    "marked_curve_h1_rank": 2,
    "relative_residue_contribution": "H1(C_g)(-1), rank two before incidence relations",
    "classification": "Legendre/elliptic coefficient data generated by existing marked hyperplanes",
    "scope": "generic transverse line; tangencies, collisions, and incidence relations remain separate supported tests",
    "new_carrier_datum": False,
}

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(json.dumps(packet, indent=2) + "\n")
print(json.dumps(packet))
