const P:i64=1_000_000_007;
fn add(a:i64,b:i64)->i64{(a+b).rem_euclid(P)}
fn mul(a:i64,b:i64)->i64{((a as i128*b as i128)%P as i128)as i64}
fn pow(mut a:i64,mut n:i64)->i64{let mut r=1;while n>0{if n&1==1{r=mul(r,a);}a=mul(a,a);n>>=1;}r}
fn inv(a:i64)->i64{pow(a.rem_euclid(P),P-2)}
#[derive(Clone,Copy)]struct L{v:i64,g:[i64;3]}
fn jet(a:L,b:L)->[i64;10]{let ia=inv(a.v);let ib=inv(b.v);let f=mul(ia,ib);let mut o=[0;10];o[0]=f;let mut l=[0;3];for i in 0..3{l[i]=add(mul(a.g[i],ia),mul(b.g[i],ib));o[1+i]=-mul(f,l[i]);}let ps=[(0,0),(0,1),(0,2),(1,1),(1,2),(2,2)];for(k,(i,j))in ps.iter().enumerate(){let aa=mul(mul(a.g[*i],a.g[*j]),mul(ia,ia));let bb=mul(mul(b.g[*i],b.g[*j]),mul(ib,ib));o[4+k]=mul(f,add(add(mul(l[*i],l[*j]),aa),bb));}o}
fn jet_many(fs:&[L])->[i64;10]{let f=fs.iter().fold(1,|z,q|mul(z,inv(q.v)));let mut o=[0;10];o[0]=f;let mut l=[0;3];for i in 0..3{l[i]=fs.iter().fold(0,|z,q|add(z,mul(q.g[i],inv(q.v))));o[1+i]=-mul(f,l[i]);}let ps=[(0,0),(0,1),(0,2),(1,1),(1,2),(2,2)];for(k,(i,j))in ps.iter().enumerate(){let diagonal=fs.iter().fold(0,|z,q|add(z,mul(mul(q.g[*i],q.g[*j]),mul(inv(q.v),inv(q.v)))));o[4+k]=mul(f,add(mul(l[*i],l[*j]),diagonal));}o}
fn packet(x:[i64;3],y:[i64;3])->[[i64;10];6]{let e=x.iter().sum::<i64>();let[a,b,c]=y;let[x1,x2,x3]=x;let ga=L{v:e+a,g:[1,1,1]};let gb=L{v:e+b,g:[1,1,1]};let gc=L{v:e+c,g:[1,1,1]};let s23=L{v:x2+x3+a+c,g:[0,1,1]};let s31=L{v:x3+x1+a+b,g:[1,0,1]};let s12=L{v:x1+x2+b+c,g:[1,1,0]};[jet(ga,s23),jet(ga,s31),jet(gb,s31),jet(gb,s12),jet(gc,s12),jet(gc,s23)]}
fn packet_full(x:[i64;3],y:[i64;3])->[[i64;10];6]{let e=x.iter().sum::<i64>();let[a,b,c]=y;let[x1,x2,x3]=x;let total=L{v:e,g:[1,1,1]};let q1=L{v:c+x1+a,g:[1,0,0]};let q2=L{v:a+x2+b,g:[0,1,0]};let q3=L{v:b+x3+c,g:[0,0,1]};let ga=L{v:e+a,g:[1,1,1]};let gb=L{v:e+b,g:[1,1,1]};let gc=L{v:e+c,g:[1,1,1]};let s23=L{v:x2+x3+a+c,g:[0,1,1]};let s31=L{v:x3+x1+a+b,g:[1,0,1]};let s12=L{v:x1+x2+b+c,g:[1,1,0]};[(ga,s23),(ga,s31),(gb,s31),(gb,s12),(gc,s12),(gc,s23)].map(|(r,s)|jet_many(&[total,q1,q2,q3,r,s]))}
fn rank(mut m:Vec<Vec<i64>>)->usize{let rows=m.len();let cols=m[0].len();let mut r=0;for c in 0..cols{let Some(p)=(r..rows).find(|&i|m[i][c]!=0)else{continue};m.swap(r,p);let z=inv(m[r][c]);for j in c..cols{m[r][j]=mul(m[r][j],z);}for i in 0..rows{if i==r||m[i][c]==0{continue}let t=m[i][c];for j in c..cols{m[i][j]=add(m[i][j],-mul(t,m[r][j]));}}r+=1;if r==rows{break}}r}
fn projector_gate(packets:&[[[i64;10];6];3])->(usize,Vec<usize>,usize){let mut coefficient=Vec::new();for q in packets.iter(){for route in 0..6{coefficient.push((0..10).map(|row|q[route][row].rem_euclid(P)).collect::<Vec<_>>());}}let base_rank=rank(coefficient.clone());let mut consistent=0;let mut augmented_ranks=Vec::new();for target in 0..6{let mut aug=coefficient.clone();for(sample,row)in aug.iter_mut().enumerate(){row.push(i64::from(sample%6==target));}let ar=rank(aug);augmented_ranks.push(ar);if ar==base_rank{consistent+=1;}}(base_rank,augmented_ranks,consistent)}
fn main(){let x=[2,3,5];let samples=[[7,11,13],[17,19,23],[29,31,37]];let reduced=samples.map(|y|packet(x,y));let full=samples.map(|y|packet_full(x,y));let(rb,ra,rc)=projector_gate(&reduced);let(fb,fa,fc)=projector_gate(&full);assert_eq!((rb,rc),(10,0));assert_eq!((fb,fc),(10,0));assert!(ra.iter().all(|&r|r==11));assert!(fa.iter().all(|&r|r==11));println!("{{\"status\":\"pass\",\"fiber_samples\":3,\"external_jet_order\":2,\"route_factor_gate\":{{\"coefficient_rank\":10,\"augmented_ranks\":[11,11,11,11,11,11],\"common_projectors\":0}},\"full_common_denominator_gate\":{{\"coefficient_rank\":10,\"augmented_ranks\":[11,11,11,11,11,11],\"common_projectors\":0}},\"cayley_menger_note\":\"K^gamma is X-independent in the source three-site edge-weight integral\",\"conclusion\":\"no loop-variable-independent second-order external-energy projector recovers any individual complete simplex route\"}}");}
