const P:i64=1_000_000_007;
fn add(a:i64,b:i64)->i64{(a+b).rem_euclid(P)}
fn mul(a:i64,b:i64)->i64{((a as i128*b as i128)%P as i128)as i64}
fn pow(mut a:i64,mut n:i64)->i64{let mut r=1;while n>0{if n&1==1{r=mul(r,a);}a=mul(a,a);n>>=1;}r}
fn inv(a:i64)->i64{pow(a.rem_euclid(P),P-2)}
#[derive(Clone,Copy)]struct L{v:i64,g:[i64;3]}
fn exponents(d:usize)->Vec<[usize;3]>{let mut e=Vec::new();for n in 0..=d{for i in 0..=n{for j in 0..=n-i{e.push([i,j,n-i-j]);}}}e}
fn index_of(es:&[[usize;3]],x:[usize;3])->usize{es.iter().position(|&e|e==x).unwrap()}
fn series_mul(a:&[i64],b:&[i64],es:&[[usize;3]],d:usize)->Vec<i64>{let mut o=vec![0;es.len()];for(i,&x)in es.iter().enumerate(){if a[i]==0{continue}for(j,&y)in es.iter().enumerate(){if b[j]==0{continue}let z=[x[0]+y[0],x[1]+y[1],x[2]+y[2]];if z.iter().sum::<usize>()<=d{let k=index_of(es,z);o[k]=add(o[k],mul(a[i],b[j]));}}}o}
fn inverse_linear(q:L,es:&[[usize;3]],d:usize)->Vec<i64>{let iq=inv(q.v);let mut z=vec![0;es.len()];if d>0{for i in 0..3{let mut e=[0;3];e[i]=1;z[index_of(es,e)]=mul(q.g[i],iq);}}let mut out=vec![0;es.len()];let zero=index_of(es,[0,0,0]);out[zero]=iq;let mut power=vec![0;es.len()];power[zero]=1;for n in 1..=d{power=series_mul(&power,&z,es,d);let sign=if n%2==0{1}else{-1};for i in 0..out.len(){out[i]=add(out[i],mul(sign,mul(iq,power[i])));}}out}
fn route_series(fs:&[L],es:&[[usize;3]],d:usize)->Vec<i64>{let mut out=vec![0;es.len()];out[index_of(es,[0,0,0])]=1;for &q in fs{out=series_mul(&out,&inverse_linear(q,es,d),es,d);}out}
fn packet(x:[i64;3],y:[i64;3],es:&[[usize;3]],d:usize)->[Vec<i64>;6]{let e=x.iter().sum::<i64>();let[a,b,c]=y;let[x1,x2,x3]=x;let common=[L{v:e,g:[1,1,1]},L{v:c+x1+a,g:[1,0,0]},L{v:a+x2+b,g:[0,1,0]},L{v:b+x3+c,g:[0,0,1]}];let ga=L{v:e+a,g:[1,1,1]};let gb=L{v:e+b,g:[1,1,1]};let gc=L{v:e+c,g:[1,1,1]};let s23=L{v:x2+x3+a+c,g:[0,1,1]};let s31=L{v:x3+x1+a+b,g:[1,0,1]};let s12=L{v:x1+x2+b+c,g:[1,1,0]};[(ga,s23),(ga,s31),(gb,s31),(gb,s12),(gc,s12),(gc,s23)].map(|(r,s)|{let mut fs=common.to_vec();fs.extend([r,s]);route_series(&fs,es,d)})}
fn rank(mut m:Vec<Vec<i64>>)->usize{let rows=m.len();let cols=m[0].len();let mut r=0;for c in 0..cols{let Some(p)=(r..rows).find(|&i|m[i][c]!=0)else{continue};m.swap(r,p);let z=inv(m[r][c]);for j in c..cols{m[r][j]=mul(m[r][j],z);}for i in 0..rows{if i==r||m[i][c]==0{continue}let t=m[i][c];for j in c..cols{m[i][j]=add(m[i][j],-mul(t,m[r][j]));}}r+=1;if r==rows{break}}r}
fn main(){let x=[2,3,5];let ys=(0..36).map(|k|[7+6*k,11+10*k,13+12*k]).collect::<Vec<_>>();let mut records=Vec::new();for d in 0..=8{let es=exponents(d);let samples=((es.len()+1+5)/6+2).min(ys.len());let packets=ys.iter().take(samples).map(|&y|packet(x,y,&es,d)).collect::<Vec<_>>();let mut m=Vec::new();for q in &packets{for route in 0..6{m.push(q[route].clone());}}let br=rank(m.clone());let mut consistent=0;let mut ars=Vec::new();for target in 0..6{let mut aug=m.clone();for(i,row)in aug.iter_mut().enumerate(){row.push(i64::from(i%6==target));}let ar=rank(aug);ars.push(ar);if ar==br{consistent+=1;}}records.push((d,es.len(),samples,br,ars.clone(),consistent));assert_eq!(consistent,0);assert!(ars.iter().all(|&r|r==br+1));}print!("{{\"status\":\"pass\",\"max_order\":8,\"records\":[");for(i,(d,n,s,r,a,c))in records.iter().enumerate(){if i>0{print!(",");}print!("{{\"order\":{d},\"jet_coordinates\":{n},\"fiber_samples\":{s},\"coefficient_rank\":{r},\"augmented_ranks\":{:?},\"common_projectors\":{c}}}",a);}println!("],\"conclusion\":\"no complete simplex route has a loop-variable-independent external-energy projector through order eight\"}}");}
