"""Anti-invariant conductor complex over the transported Z/4 quotient."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
OUT = ROOT / "research/benincasa/results/rank12-e6-mod4-conductor.json"

def kernel_mul(modulus, multiplier):
    return [x for x in range(modulus) if multiplier * x % modulus == 0]

def image_mul(modulus, multiplier):
    return sorted({multiplier * x % modulus for x in range(modulus)})

ker4 = kernel_mul(4, 2)
im4 = image_mul(4, 2)
ker2 = kernel_mul(2, 2)
im2 = image_mul(2, 2)
assert ker4 == [0, 2]
assert im4 == [0, 2]
assert ker2 == [0, 1]
assert im2 == [0]

faces = ["generic", "s=0", "B-1=0", "s=B-1=0"]
packet = {
    "schema": "marici.benincasa.rank12_e6_mod4_conductor.v1",
    "coefficient_quotient": "D_e6=Z/4",
    "conductor_complex": "[D_e6 --2--> D_e6]",
    "kernel_mod4": ker4,
    "image_mod4": im4,
    "H0_mod4": "Z/2 generated by 2",
    "H1_mod4": "Z/2",
    "mod2_reduction_differential": 0,
    "H0_mod2": "Z/2",
    "H1_mod2": "Z/2",
    "supported_restrictions": {face: {"H0": "Z/2", "H1": "Z/2"} for face in faces},
    "rational_contraction_descends_mod4": False,
    "reason": "1/2 is not defined in Z/4",
    "gysin_simplex_identified_with_conductor_totalization": False,
    "physical_cohomology_claim": False,
    "interpretation": "The quarter-lattice quotient has a genuine two-term Cartier/parity layer invisible over Q. Its attachment to the labelled Gysin simplex remains a separate typed totalization problem.",
    "new_carrier_datum": False,
}

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(json.dumps(packet, indent=2) + "\n")
print(json.dumps(packet))
