"""Integral saturation of the global quarter-occurrence line."""
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parents[3]
OUT=ROOT/'research/benincasa/results/rank12-e6-global-integral-saturation.json'

# On the primitive diagonal line, use g=(1,...,1)/4 as the ambient
# saturated rational-frame generator.  The intermediate and source lines
# are generated by 2g and 4g.
source_in_saturated=4
intermediate_in_saturated=2
assert source_in_saturated//intermediate_in_saturated==2
assert intermediate_in_saturated==2

packet={
 'schema':'marici.benincasa.rank12_e6_global_integral_saturation.v1',
 'primitive_source_vector':'c1=(1,1,1,1,1,1)',
 'rational_pair_vector':'g=(1/4)*c1',
 'source_line_in_saturated_frame':'4*Z*g',
 'intermediate_line':'2*Z*g',
 'saturated_rational_frame_line':'Z*g',
 'total_index':4,
 'total_cokernel':'Z/4',
 'two_stage_indices':[2,2],
 'candidate_stage_provenance':['normalization sheet-difference to odd-coinvariant parity','two lower-denominator occurrences per marked Cut'],
 'typed_stage_composition_proved':False,
 'physical_torsion_proved':False,
 'qualification':'Z/4 is the denominator/saturation defect in the frozen rational source frame; it becomes physical torsion only if g is independently shown integral in the e6 Betti lattice',
 'new_carrier_datum':False
}
OUT.parent.mkdir(parents=True,exist_ok=True);OUT.write_text(json.dumps(packet,indent=2)+'\n');print(json.dumps(packet))
