#!/usr/bin/env python3
"""Typing gate for a cyclic soft-Tate to total-energy e6 comparison."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
OUTPUT = ROOT / "research/benincasa/results/rank12-soft-tate-to-e6-typing-gate.json"
sigma = [[0, 0, 1], [1, 0, 0], [0, 1, 0]]

# The target e6 line is cyclically invariant, so an intertwiner satisfies
# h*sigma=h.  Direct multiplication sends (c1,c2,c3) to (c2,c3,c1),
# so the exact solution is c1=c2=c3 without choosing c.
def row_times_matrix(row, matrix):
    return [sum(row[k] * matrix[k][j] for k in range(3)) for j in range(3)]


augmentation = [1, 1, 1]
assert row_times_matrix(augmentation, sigma) == augmentation

result = {
    "schema": "marici.benincasa.rank12_soft_tate_to_e6_typing_gate.v1",
    "status": "passed",
    "domain": "Q[C3] generated by (tau_soft_1,tau_soft_2,tau_soft_3), deck character -1",
    "candidate_target": "cyclic-invariant e6 bridge line, normalization deck character -1",
    "equivariant_hom_dimension": 1,
    "general_equivariant_map": "c*(1,1,1)",
    "normalization_status": "undetermined",
    "frozen_maps_present": [
        "physical soft Gysin maps into each tau_soft_i",
        "cyclic occurrence transitions among tau_soft_i",
        "marked-top map g111_top -> e6/(8*(x+y))"
    ],
    "missing_map": "No frozen source morphism from a soft nodal Tate line (or its augmentation) to g111_top or e6.",
    "decision": "The invariant-sum-to-e6 comparison is permitted by characters but currently untyped. Neither c=0 nor c!=0 is established.",
    "next_test": "Derive the complete source-normalized rank-twelve specialization at the u=2,v=0 center and read the soft-node-to-e6 component before quotienting by cyclic symmetry."
}
OUTPUT.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
print(json.dumps(result))
