#!/usr/bin/env python3
"""Compile the resolved n=8 exceptional ambient transition and positive-chamber split."""
from pathlib import Path
import json,sys
ROOT=Path(__file__).resolve().parents[3];sys.path.insert(0,str(ROOT/'research/aspect/scc'))
from categorical_compiler import compile_diagram
transition=json.loads((ROOT/'research/nima/results/n8-GE-boundary-transition.json').read_text());boundary=json.loads((ROOT/'research/nima/results/n8-full-history-boundary-cancellation.json').read_text());src=ROOT/'research/nima/contracts/n8-exceptional-boundary-transition.scc.json';d=json.loads(src.read_text());r=compile_diagram(d);cell=r['cells'][0];inv=r['inverse_design']['full_history_source_orientation'];sol=transition['solutions'][0]
checks={'diagram_well_typed':not r['errors'],'ambient_route_cell_verified':cell['passed'],'unique_exact_transition':transition['solution_count']==1,'literal_Grassmannian_transition_no_column_scaling':transition['pivot_columns']==[1,3] and transition['equation_count']==7,'log_jacobian_plus_one':transition['log_jacobian_det']=='1' and transition['transition_orientation']==1,'positive_chambers_disjoint':sol['b7'].startswith('-') and sol['b8'].startswith('-'),'coarse_collision_split_once':boundary['false_positive_chamber_collisions']==1,'source_orientation_claim_admitted':inv['status']=='admitted'}
out={'schema':'marici.nima.n8-exceptional-boundary-transition-scc.v2','diagram':d['id'],'coherence_facet':'route/coherencer compatibility','analytic_transition':transition,'positive_domain_conclusion':'For positive G-boundary coordinates, b7=-1/(a3*a7) and b8=-a1/(a3*a7) are negative. The ambient Gr(2,8) charts are birationally related with orientation +1, but their positive boundary chambers are disjoint and must not be cancelled as one source branch.','compilation':r,'checks':checks,'passed':all(checks.values())};p=ROOT/'research/nima/results/n8-exceptional-boundary-transition-scc.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'schema':out['schema'],'cell_passed':cell['passed'],'claim_status':inv['status'],'positive_domain_conclusion':out['positive_domain_conclusion'],'checks':checks,'passed':out['passed']},indent=2));raise SystemExit(0 if out['passed'] else 1)
