#!/usr/bin/env python3
"""Integrate the exact six-point BCJ chain obstruction into a bounded no-go certificate."""
from pathlib import Path
import json
R=Path(__file__).resolve().parents[3]
def j(p):return json.loads((R/p).read_text())
c=j(Path('research/nima/results/six-point-nmhv-bcj-chain-relation.json'));r=j(Path('research/nima/results/six-point-minimal-bcj-chain-repair.json'));s=j(Path('research/strominger/results/six_point_cr_bcj_enrichment_attempt.json'));q=j(Path('research/nima/results/six-point-bcj-quotient-rank.json'))
checks={'24_relations':len(c['relations'])==24,'all_evaluated_zero':c['assertions']['all_24_bcj_component_forms_zero'],'no_raw_relation':not c['assertions']['any_raw_chain_relation'],'no_PT_dressed_relation':not c['assertions']['any_parke_taylor_dressed_chain_relation'],'defect_rank_four':r['ranks']['residue_defect_span']==4,'corrected_rank_four':r['ranks']['corrected_bcj_cycle_span']==4,'formal_repair_H4_zero':r['ranks']['repaired_H4_dimension']==0,'all_24_formally_repaired':r['checks']['all_24_relations_repaired'],'no_source_forced_repair_generators':s['repair_provenance']['source_forced_generators']==0,'ordering_quotient_dimension_six':q['quotient_dimension']==6}
out={'schema':'marici.nima.six-point-cr-bcj-no-go-certificate.v1','checks':checks,'passed':all(checks.values()),'accepted':'The six-point evaluated ordering quotient Q6 exists, but evaluation is nonfaithful on the proposed CR chain carrier: all 24 BCJ forms vanish only after evaluation, while raw and Parke-Taylor-dressed chains remain nonzero with defect span rank four.','formal_repair':'A minimal rank-four mapping-cone repair kills H4, but all eight added defect/null-homotopy generators are free linear-algebraic additions and none is sourced by cubic-graph Jacobi data.','first_missing_arrow':'A source-derived cubic-graph numerator assignment on CR generators, with generalized-gauge quotient and differential compatibility.','downstream_gate':'Second copy, state pairing, graviton projection, soft/Bondi map remain inactive.','claim_boundary':'This is a no-go for the present CR assignment and sources, not for standard amplitude-level BCJ or double copy.'}
p=R/'research/nima/results/six-point-cr-bcj-no-go-certificate.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2));raise SystemExit(0 if out['passed'] else 1)
