import json
from pathlib import Path


OUT = Path(__file__).resolve().parents[1] / "results" / "three_channel_splitting_falsifier.json"

# Basis (v, c): v is boundary/value data and c is coherence-defect data.
# Transport is the smallest nontrivial unipotent extension.
T = ((1, 0), (1, 1))

# The defect line C=<c> is invariant and the quotient E/C is the value line.
def matvec(matrix, vector):
    return tuple(sum(matrix[i][j] * vector[j] for j in range(2)) for i in range(2))


def matmul(a, b):
    return tuple(
        tuple(sum(a[i][k] * b[k][j] for k in range(2)) for j in range(2))
        for i in range(2)
    )


defect_invariant = matvec(T, (0, 1)) == (0, 1)
quotient_value_preserved = matvec(T, (1, 0))[0] == 1

# Any complement is generated by v+a c. Invariance would require
# T(v+a c)=v+a c, but its c coefficient is a+1, hence 1=0.
invariant_complement_exists = False

identity = ((1, 0), (0, 1))
powers = []
current = identity
for n in range(6):
    powers.append({"n": n, "matrix": current})
    current = matmul(T, current)
power_law_pass = all(item["matrix"] == ((1, 0), (item["n"], 1)) for item in powers)

result = {
    "checker": "three_channel_splitting_falsifier",
    "transport": T,
    "defect_subobject_invariant": defect_invariant,
    "value_quotient_preserved": quotient_value_preserved,
    "invariant_complement_exists": invariant_complement_exists,
    "power_law_Tn": powers,
    "power_law_pass": power_law_pass,
    "separate_transport_falsified": bool(defect_invariant and quotient_value_preserved and power_law_pass and not invariant_complement_exists),
    "surviving_structure": "filtered extension 0 -> C -> E -> V -> 0; record maps are typed morphisms out of E",
}

assert result["separate_transport_falsified"]
OUT.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
print(json.dumps(result, indent=2))
