#!/usr/bin/env python3
"""Assemble the n=8 physical boundary canonical-form completion certificate."""
from pathlib import Path
import json
R=Path(__file__).resolve().parents[3]
def load(n):return json.loads((R/'research/nima/results'/n).read_text())
chain=load('n8-complete-oriented-boundary-chain.json');nonphys=load('n8-nonphysical-transported-residue-cancellation.json');contract=load('n8-contracted-external-facets.json');orient=load('n8-physical-bcfw-residue-orientations.json');bridge_equiv=load('n8-physical-bcfw-to-polygon-residue-transitions.json');fib=load('n8-physical-facet-inverse-fibers.json');sums={q:load(f'n8-{q}-transported-residue-sum.json') for q in ('1234','1245','1256')};expected={'1234':'2142334982949130699885875527880740700904013/15030331577814564833151558761384414062500','1245':'489876537004459736215599/81925411575413069256425','1256':'-50856213217011485649641904317231/13429199110623174050844672000'}
checks={'complete_oriented_source_chain':chain['passed'],'all_nonphysical_images_cancel_as_forms':nonphys['passed'],'contracted_facets_have_no_divisorial_pushforward':contract['passed'],'eleven_representative_bcfw_residues_oriented':orient['passed'],'bcfw_residue_forms_equal_evaluated_polygon_forms':bridge_equiv['passed'],'all_open_physical_facet_maps_locally_degree_one':fib['passed'] and fib['checks']['all_open_facet_maps_degree_one_at_samples'],'three_exact_representative_sums':all(sums[q]['passed'] and sums[q]['summed_coefficient']==expected[q] for q in sums),'eighty_physical_source_facets':chain['boundary_chain_summary']['external_rank7_physical']==80,'twenty_physical_divisors':len(load('n8-complete-external-pushforward.json')['physical_bracket_multiplicities'])==20}
out={'schema':'marici.nima.n8-physical-boundary-canonical-form-completion.v1','source_authority':{'file':'research/sources/nima/papers/six-point-nmhv/1212.5605/positive_grassmannian_update.tex','section':'(Diagrammatic) Proof of the BCFW Recursion Relations','statement':'The BCFW boundary contains every required factorization channel; spurious factorization boundaries occur symmetrically and cancel in the sum.'},'representative_exact_evaluations':{q:{'physical_bracket':sums[q]['physical_bracket'],'summed_coefficient':sums[q]['summed_coefficient'],'target_sample':sums[q]['target_sample']} for q in sums},'cyclic_completion':{'orbit_1234':8,'orbit_1245':8,'orbit_1256':4,'total_physical_divisors':20,'total_rank7_source_facets':80},'checks':checks,'passed':all(checks.values()),'conclusion':'The complete oriented pushforward has precisely the sourced BCFW factorization boundary: internal nonphysical residues cancel, contracted facets do not contribute divisors, and all 80 remaining degree-one facet maps sum over the 20 physical brackets. Exact common-chart Jacobian sums fix the normalization on one representative of each cyclic orbit; exact unit bridge-to-polygon residue transitions transfer those sums to the genuine BCFW atlas.','claim_boundary':'Equality to the expected amplituhedron boundary canonical form uses the sourced BCFW factorization theorem plus exact chain/Jacobian calculations. No independent closed rational formula for the bosonized seven-form was found in the repository, so the three displayed point evaluations are normalization checks rather than a separate symbolic-form derivation.'};p=R/'research/nima/results/n8-physical-boundary-canonical-form-completion.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2));raise SystemExit(0 if out['passed'] else 1)
