"""Two twelve-triangle bodies from one seed, with an explicit shared core.

Construction rule: cyclic seed walks act as permutations; oriented area packets
use the exterior-square (cofactor) action on the three contrast directions.
For orthogonal R this action is det(R)*R, always orientation preserving.
The seed already contains AB and BA, supplying the two-cycle (AB).
"""
from collections import Counter
from fractions import Fraction as F
from itertools import combinations, product
from pathlib import Path
import json
from check_twelve_triangle_positive_geometry import (
    POINTS, LABELS, I, ONE, ZERO, OMEGA, mean, compose, rotation,
    transpose, mm, mv, det, dot, sub, cross, zmv, zmul, zscale, znorm,
    boundary,
)
from check_collective_four_state_identity import rank


A=(1,2,0,3);B=(3,0,2,1);SWAP=(1,0,2,3)

def closure(generators):
    group={(0,1,2,3)};front=list(group)
    while front:
        p=front.pop()
        for g in generators:
            q=compose(g,p)
            if q not in group: group.add(q);front.append(q)
    return sorted(group)

def proper(p):
    R=rotation(p);s=det(R)
    return tuple(tuple(s*x for x in row) for row in R)

def permutation_sign(items):
    return (-1)**sum(items[i]>items[j] for i in range(len(items)) for j in range(i+1,len(items)))

def cell_boundary(tet):
    out=Counter()
    for i in range(4):
        face=tet[:i]+tet[i+1:]
        out[tuple(sorted(face))]+=(-1)**i*permutation_sign(face)
    return out

def surface_check(chain):
    faces={f:n for f,n in chain.items() if n}
    assert all(abs(n)==1 for n in faces.values())
    edge_chain=Counter();edge_degrees=Counter()
    for f,n in faces.items():
        for i in range(3):
            e=f[:i]+f[i+1:]
            edge_chain[e]+=n*(-1)**i
            edge_degrees[e]+=1
    assert all(n==0 for n in edge_chain.values())
    assert all(n==2 for n in edge_degrees.values())
    vertices={v for f in faces for v in f}
    assert len(vertices)-len(edge_degrees)+len(faces)==2
    return faces

def laplacian(nodes,generators):
    index={p:i for i,p in enumerate(nodes)};edges=set()
    for p in nodes:
        for g in generators:
            q=compose(g,p)
            assert q in index
            if p!=q: edges.add(tuple(sorted((index[p],index[q]))))
    L=[[F(0)]*len(nodes) for _ in nodes]
    for i,j in edges:
        L[i][i]+=1;L[j][j]+=1;L[i][j]-=1;L[j][i]-=1
    assert all(sum(row)==0 for row in L)
    return L,edges


def main():
    seed_arrows={('A','B'),('B','C'),('C','A'),('A','D'),('D','B'),('B','A')}
    assert ('A','B') in seed_arrows and ('B','A') in seed_arrows
    even=closure((A,B));whole=closure((A,B,SWAP))
    assert len(even)==12 and len(whole)==24
    assert all(det(rotation(p))==1 for p in even)
    Rs={p:proper(p) for p in whole}
    for p in whole:
        assert det(Rs[p])==1 and mm(transpose(Rs[p]),Rs[p])==I
        for g in (A,B,SWAP): assert mm(Rs[g],Rs[p])==Rs[compose(g,p)]
    # The same operation without its area-packet lift has negative orientation.
    assert det(rotation(SWAP))==-1 and det(Rs[SWAP])==1
    axis=sub(POINTS['A'],POINTS['B'])
    assert mv(Rs[SWAP],axis)==axis and mm(Rs[SWAP],Rs[SWAP])==I
    points={};triangles={1:[],-1:[]};vectors={}
    reference=transpose((mean([POINTS[k] for k in 'ABC']),POINTS['A'],POINTS['B']))
    c=(ONE,OMEGA,zmul(OMEGA,OMEGA));v0=zmv(reference,c)
    for p in whole:
        s=int(det(rotation(p)));prefix='+' if s==1 else '-'
        a,b,cname=[LABELS[p[i]] for i in range(3)]
        for k in LABELS: points[prefix+k]=tuple(s*x for x in POINTS[k])
        centre=prefix+'F_'+''.join(sorted((a,b,cname)))
        points[centre]=mean([points[prefix+k] for k in (a,b,cname)])
        tri=(centre,prefix+a,prefix+b);triangles[s].append(tri)
        X=transpose(tuple(points[k] for k in tri))
        assert X==mm(Rs[p],reference)
        v=zmv(X,(ONE,OMEGA,zmul(OMEGA,OMEGA)));vectors[p]=v
        assert zmv(transpose(Rs[p]),v)==v0
        normal=cross(sub(points[tri[1]],points[tri[0]]),sub(points[tri[2]],points[tri[0]]))
        assert dot(normal,points[tri[0]])>0
        assert all(dot(normal,sub(points[prefix+k],points[tri[0]]))<=0 for k in LABELS)
    volumes={}
    for sign,tris in triangles.items():
        assert len(tris)==12 and boundary(tris)=={}
        assert len({tuple(sorted(t)) for t in tris})==12
        volume=sum(det(transpose(tuple(points[k] for k in t)))/6 for t in tris)
        assert volume==F(8,3);volumes[sign]=volume
    assert {points['+'+k] for k in LABELS}.isdisjoint({points['-'+k] for k in LABELS})
    for p in even:
        q=compose(SWAP,p)
        assert q not in even
        assert zmv(Rs[SWAP],vectors[p])==vectors[q]
    assert sum(znorm(z) for v in vectors.values() for z in v)==160
    # One positive phase-consensus identity is generated by the seed relations.
    L,edges=laplacian(whole,(A,B,SWAP));assert rank(L)==23
    Le,ee=laplacian(even,(A,B));assert rank(Le)==11
    negative=[p for p in whole if p not in even]
    Ln,en=laplacian(negative,(A,B));assert rank(Ln)==11
    cross_edges=[(i,j) for i,j in edges if (whole[i] in even)!=(whole[j] in even)]
    assert len(cross_edges)==12
    # Positive, aperiodic coupling generated by the same seed moves.
    # Each node has four within-body neighbors and one cross-body neighbor.
    assert all(L[i][i]==5 for i in range(24))
    transition=tuple(tuple(F(i==j)-L[i][j]/6 for j in range(24)) for i in range(24))
    assert all(x>=0 for row in transition for x in row)
    assert all(sum(row)==1 for row in transition)
    relative=tuple(F(1 if p in even else -1) for p in whole)
    assert mv(transition,relative)==tuple(F(2,3)*x for x in relative)
    Q=tuple(tuple(F(1,24) for _ in whole) for _ in whole)
    assert mm(Q,Q)==Q and all(x==0 for row in mm(L,Q) for x in row)
    disconnected,_=laplacian(whole,(A,B));assert rank(disconnected)==22
    # Actual intersection: all eight sign inequalities sigma.dot(x)<=1.
    normals={tuple(s*x for x in v) for s in (-1,1) for v in POINTS.values()}
    assert normals==set(product((-1,1),repeat=3))
    mids={tuple((POINTS[a][i]+POINTS[b][i])/2 for i in range(3)) for a,b in combinations(LABELS,2)}
    axis_vertices={tuple(F(s if i==j else 0) for i in range(3)) for j in range(3) for s in (-1,1)}
    assert mids==axis_vertices
    # A positive cell refinement makes the overlap explicit: one octahedral core
    # plus eight disjoint tetrahedral tips. Nothing is counted twice in the union.
    cp={'O':(F(0),)*3}
    def ax(i,s): return ('+' if s>0 else '-')+'xyz'[i]
    def apex(s): return 'V'+''.join('+' if x>0 else '-' for x in s)
    for i in range(3):
        for s in (-1,1): cp[ax(i,s)]=tuple(F(s if j==i else 0) for j in range(3))
    for s in product((-1,1),repeat=3): cp[apex(s)]=tuple(map(F,s))
    def orient(t):
        a,b,c,d=[cp[k] for k in t]
        value=det(transpose((sub(b,a),sub(c,a),sub(d,a))))/6
        if value<0: t=(t[0],t[1],t[3],t[2]);value=-value
        assert value>0
        return t,value
    gray=((1,1,1),(1,1,-1),(1,-1,-1),(1,-1,1),(-1,-1,1),(-1,-1,-1),(-1,1,-1),(-1,1,1))
    core=[];tips={1:[],-1:[]}
    for s in gray:
        base=tuple(ax(i,s[i]) for i in range(3))
        t,v=orient(('O',)+base);assert v==F(1,6);core.append((t,v))
        t,v=orient((apex(s),)+base);assert v==F(1,3)
        tips[s[0]*s[1]*s[2]].append((t,v))
        # Separation certificate: tip interiors have this sign pattern and
        # sigma.dot(x)>1; the core has sigma.dot(x)<=1. Different tips have
        # different octants. Thus positive 3-cell interiors are disjoint.
        assert dot(s,cp[apex(s)])==3
        assert all(dot(s,cp[k])==1 for k in base)
        assert all(all(s[i]*cp[k][i]>=0 for i in range(3)) for k in (apex(s),)+base)
    chain=Counter();volume=F(0);stages=[]
    for i,(t,v) in enumerate(core+tips[1]+tips[-1]):
        old={f:n for f,n in chain.items() if n}
        bdy=cell_boundary(t)
        shared=[f for f,n in bdy.items() if f in old and old[f]==-n]
        if i: assert shared, 'new cell lacks a shared boundary face'
        for f,n in bdy.items(): chain[f]+=n
        volume+=v;surface=surface_check(chain)
        stages.append({'stage':i+1,'positive_added_volume':str(v),'total_volume':str(volume),
                       'boundary_triangles':len(surface),'shared_faces_glued':len(shared),
                       'boundary_closed':True,'boundary_euler_characteristic':2})
    assert volume==4 and len(surface)==24
    assert stages[7]['total_volume']=='4/3'
    assert stages[11]['total_volume']=='8/3'
    for sign in (1,-1):
        b=Counter()
        for t,v in core+tips[sign]:
            for f,n in cell_boundary(t).items(): b[f]+=n
        out=surface_check(b)
        assert len(out)==16
        # The two bodies are convex tetrahedra with these four apex vertices.
        for t,v in core+tips[sign]:
            for k in t:
                assert all(1+sign*dot(vertex,cp[k])>=0 for vertex in POINTS.values())
    # Shared core phase identity: constants on the eight core cells restrict
    # equally from the two twelve-cell bodies and extend to the sixteen-cell pair.
    assert len(core)==8 and len(core+tips[1])==len(core+tips[-1])==12
    def cell_identity(cells):
        n=len(cells);J=[[F(0)]*n for _ in cells]
        bds=[cell_boundary(t) for t,v in cells]
        for i,j in combinations(range(n),2):
            if any(f in bds[j] and bds[j][f]==-c for f,c in bds[i].items()):
                J[i][i]+=1;J[j][j]+=1;J[i][j]-=1;J[j][i]-=1
        assert rank(J)==n-1 and all(sum(row)==0 for row in J)
        return n-rank(J)
    core_identity=cell_identity(core)
    body_identities=[cell_identity(core+tips[s]) for s in (1,-1)]
    union_identity=cell_identity(core+tips[1]+tips[-1])
    assert core_identity==union_identity==1 and body_identities==[1,1]
    # The amplitude-one constant sections on both bodies restrict to the same
    # amplitude-one core section, and extend to the constant union section.
    assert (F(1),)*12==((F(1),)*8)+((F(1),)*4)
    # Negative controls: no exchange -> one geometric orbit; coincident second
    # copy has no distinct support; omitting the core leaves two open tip sets.
    assert len(closure((A,B)))==12
    for sign in (1,-1):
        exposed=Counter()
        for t,v in tips[sign]:
            for f,n in cell_boundary(t).items(): exposed[f]+=n
        assert any(set(f).issubset(set(cp)-{'O'}-{apex(s) for s in gray}) and n for f,n in exposed.items())
    result={'audit_assertions_passed':True,
            'construction_rule':'Seed cycles act on oriented area packets through the exterior-square representation det(R)*R.',
            'seed_arrows':[''.join(e) for e in sorted(seed_arrows)],
            'seed_cycles':['ABC','ADB','AB'],'even_group_order':12,'full_group_order':24,
            'bodies':{'positive':{'fan_triangles':12,'volume':'8/3'},
                      'negative':{'fan_triangles':12,'volume':'8/3'},
                      'distinct_support':True,'congruent':True},
            'shared_geometry':{'intersection':'octahedron |x|+|y|+|z|<=1',
                               'vertices':'six seed-derived edge midpoints','volume':'4/3',
                               'positive_cell_refinement':{'core_tetrahedra':8,'tips_per_body':4,'union_tetrahedra':16},
                               'union_volume':'4','union_external_triangles':24,
                               'refined_boundary_triangles_per_closed_body':16,
                               'triangle_count_warning':'24 fan triangles describes two complete overlapping surfaces. The compatible cell refinement gives 16 boundary triangles per body and 24 on their union; 12 external faces alone do not close either refined body.'},
            'eigenline_coupling':{'transported_triangle_lines_equal':True,
                                  'cross_exchange_edges':len(cross_edges),
                                  'pair_laplacian_rank':rank(L),'pair_identity_dimension':1,
                                  'body_identity_dimensions':[1,1],
                                  'without_cross_exchange_identity_dimension':2,
                                  'common_mode_normalization':160,
                                  'positive_consensus_transition':'I-L/6',
                                  'relative_body_mode_multiplier':'2/3',
                                  'same_core_identity_under_restriction':True,
                                  'cell_identity_dimensions':{'core':core_identity,'bodies':body_identities,'union':union_identity}},
            'negative_controls':{'three_cycles_only_group_order':12,
                                  'unlifted_exchange_determinant':-1,
                                  'uncoupled_phase_identity_dimension':2,
                                  'core_omission_leaves_extra_base_faces':True},
            'assembly_stages':stages,
            'scope':'Explicit two-body geometric candidate, generated from seed loops with a declared area-packet lift. Stagewise positive cells and compatible shared core are checked. No minimality, electron identification, dynamical binding, or total primitive construction cost is established.'}
    dest=Path(__file__).resolve().parents[1]/'results'
    (dest/'twenty-four-triangle-shared-seed.json').write_text(json.dumps(result,indent=2)+'\n')
    names=list(points)
    obj=['# Two closed 12-triangle bodies, with their overlap described by the shared-core certificate.']
    obj+=['v '+' '.join(str(float(x)) for x in points[k]) for k in names]
    for sign in (1,-1):
        obj.append('g body_'+('positive' if sign==1 else 'negative'))
        obj+=['f '+' '.join(str(names.index(k)+1) for k in t) for t in triangles[sign]]
    (dest/'twenty-four-triangle-pair.obj').write_text('\n'.join(obj)+'\n')
    cnames=list(cp)
    obj=['# Positive cell union: octahedral core plus eight tips.']
    obj+=['v '+' '.join(str(float(x)) for x in cp[k]) for k in cnames]
    for f,n in surface.items():
        t=f if n==1 else (f[0],f[2],f[1])
        obj.append('f '+' '.join(str(cnames.index(k)+1) for k in t))
    (dest/'twenty-four-triangle-union.obj').write_text('\n'.join(obj)+'\n')
    print('PASS: seed area-packet action generates 24 triangles in two distinct closed bodies. Shared octahedral core, 16 positive assembly cells, one coupled eigenline identity. Compatible refinement and triangle counts recorded explicitly.')

if __name__=='__main__': main()
