// Read-only validation of the public tetrahedral update and generated Markdown.
import assert from 'node:assert/strict'
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import MarkdownIt from 'markdown-it'
import { katex } from '@mdit/plugin-katex'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..')
const read = name => fs.readFile(path.join(root, name), 'utf8')
const routeContent = source => source
  .replaceAll('](/results/#bridges)', '](#postnikov-descent)')
  .replaceAll('](/results/#control)', '](#the-universe-as-a-feedback-system)')
  .replaceAll('](/results/#frontier)', '](/research/results/)')
  .replaceAll('](/results/', '](/research/results/')
  .replaceAll('](/theory/', '](/research/theory/')
  .replace(/\]\(\.\.\/research\/([^)]*)\)/g, (_, relative) => `](https://github.com/andrey-kokoev/marici/blob/main/research/${relative})`)
  .replaceAll('](theory-page.md', '](/research/theory/')
const pairs = [
  ['docs/landing-page.md', 'website/index.md'],
  ['docs/theory-page.md', 'website/research/theory/index.md'],
  ['docs/results-page.md', 'website/research/results/index.md'],
  ['docs/system-characteristics.md', 'website/research/system-characteristics/index.md'],
]
const pages = new Map()
for (const [source, target] of pairs) {
  const generated = await read(target)
  assert.equal(generated, routeContent(await read(source)), `${target} is stale`)
  pages.set(target, generated)
}
const data = JSON.parse(await read('src/data/results-physics.json'))
const slugs = ['spin-transport', 'proton-electron-ratio', 'sm-gauge-group', 'higgs-mechanism']
for (const slug of slugs) {
  const item = data.find(x => x.slug === slug)
  assert(item)
  assert.notEqual(item.status, 'Established')
  const expected = `<!-- Generated by scripts/prepare-website.mjs. Edit src/data/results-physics.json instead. -->\n\n# ${item.domain}\n\n**${item.status}**\n\n${item.details}\n\n${item.checker ? `**Checker:** \`${item.checker}\`\n\n` : ''}${item.result ? `**Result artifact:** \`${item.result}\`\n\n` : ''}[Back to results](/research/results/)\n`
  const target = `website/research/results/${slug}.md`
  const generated = await read(target)
  assert.equal(generated, expected, `${target} is stale`)
  pages.set(target, generated)
}
const landing = await read('docs/landing-page.md')
const start = landing.indexOf('## Predictions')
const end = landing.indexOf('**Construction and formalizations**', start)
assert(start >= 0 && end > start)
const predictions = '# Falsifiable predictions\n\n' + landing.slice(start, end)
  .replace(/^## Predictions\s*/, '')
  .replaceAll('](/results/', '](/research/results/')
  .replaceAll('](/theory/', '](/research/theory/')
const predictionPath = 'website/research/predictions/index.md'
assert.equal(await read(predictionPath), predictions)
pages.set(predictionPath, predictions)

const theory = pages.get('website/research/theory/index.md')
assert(theory.includes('### Tetrahedral geometry, spinors, and the native-loop test'))
assert(theory.includes('T_{zy}T_{yx}=T_{zx}'))
assert(theory.includes('Every closed selected-line route therefore returns +1'))
assert(theory.includes('variance 8'))
assert(!theory.includes('4 = **1** (trivial) ⊕ **1\'** (sign) ⊕ **2** (doublet)'))
const spin = data.find(x => x.slug === 'spin-transport')
assert(spin.details.includes('native-loop test'))
assert(spin.details.includes('broader physical conjecture is untested'))
assert(spin.details.includes('explicit extra input'))
assert(!predictions.includes('\\frac{m_p}{m_e} ='))

const markdown = new MarkdownIt().use(katex, { throwOnError: true, strict: 'error' })
let formulas = 0
for (const [name, text] of pages) {
  const html = markdown.render(text)
  assert(!html.includes('katex-error'), name)
  formulas += (html.match(/class="katex"/g) ?? []).length
  // Source links are checked against this checkout; no remote publication is inferred.
  for (const match of text.matchAll(/https:\/\/github\.com\/andrey-kokoev\/marici\/blob\/main\/(research\/[^)#\s]+)(?:#[^)]*)?\)/g)) {
    assert((await fs.stat(path.join(root, match[1]))).isFile(), `${name}: missing ${match[1]}`)
  }
}
console.log(`PASS: ${pages.size} public pages match their sources; ${formulas} KaTeX formulas render; linked research files exist.`)
console.log('PASS: native-selection failure, added-factor boundary, charge correction and non-mass count retained.')
