#!/usr/bin/env python3
"""Final consistency and claim-boundary manifest for the n=8 boundary programme."""
from pathlib import Path
import json
R=Path(__file__).resolve().parents[3];D=R/'research/nima/results'
def j(n):return json.loads((D/n).read_text())
art={'coverage':j('n8-coordinate-to-bruhat-boundary-coverage.json'),'atlas':j('n8-complete-cyclic-bcfw-bridge-atlas.json'),'hidden_transitions':j('n8-bcfw-bridge-orientation-anchors.json'),'oriented_chain':j('n8-complete-oriented-boundary-chain.json'),'nonphysical':j('n8-nonphysical-bcfw-transported-cancellation.json'),'external':j('n8-complete-external-pushforward.json'),'contracted':j('n8-contracted-external-facets.json'),'inverse_fibers':j('n8-physical-facet-inverse-fibers.json'),'physical_completion':j('n8-physical-boundary-canonical-form-completion.json'),'second_Z':j('n8-external-pushforward-second-positive-Z.json'),'saturation':j('n8-history2-inverse-fiber-saturation.json')}
checks={'coverage_107_plus_59':len(art['coverage']['visible_facet_incidences'])==107 and len(art['coverage']['missing_facet_incidences'])==59,'positive_atlas_covers_166':art['atlas']['passed'] and sum(x['covered'] for x in art['atlas']['coverage_by_history'].values())==166,'all_40_shared_cancel_directly':art['oriented_chain']['passed'] and art['oriented_chain']['checks']['all_forty_explicit_residues_cancel'],'all_16_nonphysical_images_cancel':art['nonphysical']['passed'],'external_80_plus_6':art['external']['passed'] and art['oriented_chain']['boundary_chain_summary']['external_rank7_physical']==80 and art['oriented_chain']['boundary_chain_summary']['external_contracted']==6,'six_contracted_no_divisor':art['contracted']['passed'],'eleven_orbit_representatives_invert':art['inverse_fibers']['passed'],'physical_boundary_completion':art['physical_completion']['passed'],'second_positive_Z_facetwise_crosscheck':art['second_Z']['passed'],'history2_open_fiber_saturation':art['saturation']['passed']}
status={'explicit_17_hidden_transition_jacobians':'complete','physical_residue_pushforward_three_cyclic_orbits':'complete_with_source_theorem_and_exact_representative_normalizations','complete_cyclic_positive_rank2_dlog_atlas':'complete','complete_cyclic_colored_bcfw_bridge_atlas':'complete','source_lexicographic_convention':'chains use deterministic lexicographic positive-bridge search; equivalence to every tie-breaking detail of the paper prose is not separately asserted','nonstandard_and_quartic_cancellation':'complete','contracted_external_facet_analysis':'complete'};out={'schema':'marici.nima.n8-boundary-programme-manifest.v1','status':status,'checks':checks,'passed':all(checks.values()),'artifacts':{k:str((D/( {'coverage':'n8-coordinate-to-bruhat-boundary-coverage.json','atlas':'n8-complete-cyclic-bcfw-bridge-atlas.json','hidden_transitions':'n8-bcfw-bridge-orientation-anchors.json','oriented_chain':'n8-complete-oriented-boundary-chain.json','nonphysical':'n8-nonphysical-bcfw-transported-cancellation.json','external':'n8-complete-external-pushforward.json','contracted':'n8-contracted-external-facets.json','inverse_fibers':'n8-physical-facet-inverse-fibers.json','physical_completion':'n8-physical-boundary-canonical-form-completion.json','second_Z':'n8-external-pushforward-second-positive-Z.json','saturation':'n8-history2-inverse-fiber-saturation.json'}[k])).relative_to(R)) for k in art},'claim_boundary':'The authoritative atlas now consists of positive colored single-column BCFW bridges and covers all 166 incidences. Search order is deterministic and lexicographic; exact equivalence to every unstated tie-breaking choice in the paper is not needed for the atlas or residue results.'};p=D/'n8-boundary-programme-manifest.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2));raise SystemExit(0 if out['passed'] else 1)
