#!/usr/bin/env python3
"""Finite verification of the generic polygon incidence Smith theorem."""
import importlib.util
import json
from pathlib import Path
from sympy import Matrix, ZZ
from sympy.matrices.normalforms import smith_normal_form

helper_path=Path(__file__).with_name("check_generic_polygon_face_product.py")
spec=importlib.util.spec_from_file_location("polygon_faces",helper_path)
poly=importlib.util.module_from_spec(spec)
spec.loader.exec_module(poly)

def crosses(a,b,n):
    x,y=sorted(a); u,v=sorted(b)
    return (x<u<y<v) or (u<x<v<y)

def connected_crossing_graph(channels,n):
    seen={channels[0]}; stack=[channels[0]]
    while stack:
        current=stack.pop()
        for other in channels:
            if other not in seen and crosses(current,other,n):
                seen.add(other); stack.append(other)
    return len(seen)==len(channels)

stages=[]
for n in range(4,9):
    channels=tuple(sorted(poly.diagonals(n)))
    triangulations=sorted((tuple(sorted(t)) for t in poly.dissections_on(channels) if len(t)==n-3),key=repr)
    A=Matrix([[int(c in t) for c in channels] for t in triangulations])
    D=smith_normal_form(A,domain=ZZ)
    invariants=[abs(int(D[i,i])) for i in range(len(channels))]
    expected=[1]*(len(channels)-1)+[n-3]
    assert invariants==expected
    assert connected_crossing_graph(channels,n)
    stages.append({"n":n,"channels":len(channels),"triangulations":len(triangulations),"crossing_graph_connected":True,"smith_invariants":invariants})

result={
    "schema":"marici.polygon-incidence-smith-theorem.v1",
    "status":"passed",
    "strength":"generic lattice proof for every n>=4 plus finite Smith and connectivity checks n=4..8",
    "theorem":"the triangulation-channel incidence lattice is {v in Z^F: sum(v)=0 mod n-3}; its Smith invariants are F-1 copies of 1 and one copy of n-3",
    "proof_edges":[
        "a flip difference is e_c-e_c' for crossing diagonals c,c'",
        "the crossing graph is connected because every diagonal crosses a short diagonal at an endpoint and consecutive short diagonals cross",
        "therefore all zero-sum lattice vectors are generated by flip differences",
        "every triangulation row has coordinate sum n-3, and one row supplies that residue class"
    ],
    "stages":stages,
    "consequence":"the complex facet-scale kernel is exactly the diagonal group of (n-3)rd roots of unity",
    "boundary":"the theorem concerns combinatorial incidence; it supplies neither source coefficient values nor embedding provenance",
}
out=Path("research/nima/results/polygon_incidence_smith_theorem.json")
out.write_text(json.dumps(result,indent=2,sort_keys=True)+"\n",encoding="utf-8")
print(json.dumps(result,sort_keys=True))
