#!/usr/bin/env python3
"""All-cutoff support theorem for boundary corrections as negative-simple coordinates."""
from pathlib import Path
import json,sys
ROOT=Path(__file__).resolve().parents[3];sys.path.insert(0,str(ROOT/'research/nima'))
from nnmhv_coherence_paths import compile_nnmhv_histories,supports_component_23
rows=[]
for n in range(6,31):
 hs=[h for h in compile_nnmhv_histories(n) if supports_component_23(h)];m=n-5
 labels=[(h.inner_pair[1]-4,h.outer_pair[1]-4) for h in hs]
 upd=[(h.inner_pair[1]-4,h.outer_pair[1]-4) for h in hs if h.boundary_updates]
 rows.append({'n':n,'m':m,'supported_histories':len(hs),'expected_positive_roots':m*(m+1)//2,'boundary_updated_histories':len(upd),'expected_negative_simples':m,'labels_unique':len(set(labels))==len(labels),'labels_are_all_intervals':set(labels)=={(i,j) for i in range(1,m+1) for j in range(i,m+1)},'updates_are_exactly_simple_roots':set(upd)=={(i,i) for i in range(1,m+1)},'all_updates_are_upper':all(len(h.boundary_updates)==1 and h.boundary_updates[0].side=='upper' for h in hs if h.boundary_updates)})
checks={'tested_n6_through_n30':len(rows)==25,'positive_root_bijection':all(r['supported_histories']==r['expected_positive_roots'] and r['labels_unique'] and r['labels_are_all_intervals'] for r in rows),'boundary_count_equals_rank':all(r['boundary_updated_histories']==r['expected_negative_simples'] for r in rows),'boundary_support_equals_simple_roots':all(r['updates_are_exactly_simple_roots'] and r['all_updates_are_upper'] for r in rows)}
out={'schema':'marici.nima.arbitrary-n-boundary-cluster-completion.v1','map':'supported history (b1,b2) -> positive root [b2-4,b1-4]','boundary_rule':'upper endpoint replacement occurs iff b2=b1, hence exactly on positive simple roots [i,i]','cluster_completion':'pair each transported simple-root correction beta_i with the missing negative-simple coordinate -alpha_i','theorem':'For every n>=6, the selected component has m(m+1)/2 supported histories and m boundary-updated diagonal histories, with m=n-5. Thus boundary transport supplies the correct number and labels for completion from positive roots to almost-positive roots.','genericity_condition':'Mutation ratios require each beta_i and positive-root weight to be nonzero. The support theorem does not exclude zeros on special kinematic loci.','rows':rows,'checks':checks,'passed':all(checks.values()),'claim_boundary':'The all-n statement is a support and labeling theorem from the history compiler. It does not prove arbitrary-n positroid matching or that product cluster weights equal canonical forms.'};p=ROOT/'research/nima/results/arbitrary-n-boundary-cluster-completion.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'schema':out['schema'],'map':out['map'],'boundary_rule':out['boundary_rule'],'theorem':out['theorem'],'checks':checks,'passed':out['passed']},indent=2));raise SystemExit(0 if out['passed'] else 1)
