"""Exact D3 audit of the unequal-energy cotangent Tate candidate."""

from fractions import Fraction
import json
from pathlib import Path


def mm(a, b):
    return [[sum(a[i][k] * b[k][j] for k in range(len(b)))
             for j in range(len(b[0]))] for i in range(len(a))]


def modq(x, p=3):
    return (x.numerator * pow(x.denominator, -1, p)) % p


def modm(a, p=3):
    return [[modq(Fraction(x), p) for x in row] for row in a]


I = [[Fraction(1), Fraction(0)], [Fraction(0), Fraction(1)]]
J = [
    [Fraction(-1, 2), Fraction(3, 2)],
    [Fraction(-1, 2), Fraction(-1, 2)],
]
K = [[Fraction(1), Fraction(0)], [Fraction(0), Fraction(-1)]]
assert mm(mm(J, J), J) == I
assert mm(K, K) == I
assert mm(mm(K, J), K) == mm(J, J)

J3 = modm(J)
K3 = modm(K)
assert J3 == [[1, 0], [1, 1]]
assert K3 == [[1, 0], [0, 2]]

JT3 = [list(row) for row in zip(*J3)]
N_tangent = [[(I[i][j] + J[i][j] + mm(J, J)[i][j]) for j in range(2)] for i in range(2)]
assert N_tangent == [[0, 0], [0, 0]]

# Tangent coinvariants: im(J-I)=<e_v>, quotient generated by e_u.
# Reflection is +1 there.
tangent_reflection_character = 1

# Cotangent coinvariants: im(J^T-I)=<du>, quotient generated by dv.
# Reflection sends dv to -dv.
cotangent_reflection_character = 2
assert tangent_reflection_character != cotangent_reflection_character
assert cotangent_reflection_character == (-1) % 3

result = {
    "schema": "marici.rs3.asymmetry-cotangent-tate-character.v1",
    "base_action": {
        "rho": "(u,v) -> (2u/(u-v), 2(2-v)/(u-v))",
        "fixed_point": [3, 1],
        "jacobian": [["-1/2", "3/2"], ["-1/2", "-1/2"]],
        "reflection": "(u,v) -> (u,2-v)",
    },
    "mod3_tangent_action": J3,
    "D3_relations": True,
    "tangent_coinvariant": {
        "generator": "du",
        "reflection_character": tangent_reflection_character,
        "matches_road_tate_line": False,
    },
    "cotangent_coinvariant": {
        "generator": "dv=d(X2-X3)",
        "reflection_character": cotangent_reflection_character,
        "matches_road_tate_character": True,
        "dimension": 1,
    },
    "physical_response_status": "not computed",
    "verdict": (
        "The first unequal-energy cotangent jet supplies a canonical odd D3 "
        "line with the same character as the road/Tate extension. The tangent "
        "line has the wrong character. A Gauss-Manin response calculation is "
        "still required to show physical activation."
    ),
}

out = Path(__file__).parents[1] / "results" / "rs3-asymmetry-cotangent-tate-character.json"
out.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
print(json.dumps(result, indent=2))
