"""Find the transverse line generated by transport of the two-branch source."""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(ROOT / "research" / "benincasa"))
import physical_four_mark_residue_twisted_derham as m

OUT = Path(__file__).resolve().parents[1] / "results" / "physical_union_transverse_line.json"
NAMES = ("g1", "g2", "g3", "g23", "g31")
GAMMA, AMBIENT, CUTOFF = 5, 14, 7


def add_scaled(target, vector, scale=1):
    for column, value in vector.items():
        m.add_value(target, column, scale * value)


def main() -> None:
    target = tuple(int(x) for x in os.environ.get("MARICI_KINEMATICS", "2,3,4").split(","))
    if len(target) != 3:
        raise ValueError("MARICI_KINEMATICS must be x,y,z")
    original_fiber_data = m.fiber_data

    def translated_fiber_data(x, y, z):
        # The imported reducer is centered at (2,3,4).  Translating its calls
        # makes both presentation() and its exact five-point derivatives run
        # at an arbitrary finite-field kinematic point without editing the
        # frozen collaborator source.
        return original_fiber_data(
            target[0] + x - 2, target[1] + y - 3, target[2] + z - 4
        )

    m.fiber_data = translated_fiber_data
    low, columns, pivots, free = m.presentation(
        NAMES, GAMMA, AMBIENT, CUTOFF, minimum_q_level=1
    )
    _, q = m.fiber_data(2, 3, 4)
    base = (0, 1, 1, 1, 1, 1)

    def branch_image(domain_names, missing):
        dlow, _, _, dfree = m.presentation(
            domain_names, GAMMA, AMBIENT, CUTOFF, minimum_q_level=1
        )
        span = {}
        for free_column in dfree:
            exponent = dlow[free_column][-1]
            row = {}
            for term, coefficient in m.multiply_monomial(q[missing], exponent):
                add_scaled(row, m.quotient_coordinates((*base, term), columns, pivots, free), coefficient)
            m.add_pivot(row, span)
        return len(dfree), span

    d23, image23 = branch_image(("g1", "g2", "g3", "g23"), "g31")
    d31, image31 = branch_image(("g1", "g2", "g3", "g31"), "g23")
    branch_sum = {}
    for row in list(image23.values()) + list(image31.values()):
        m.add_pivot(dict(row), branch_sum)

    numerator = dict(q["g23"])
    for exponent, coefficient in q["g31"].items():
        numerator[exponent] = (numerator.get(exponent, 0) + coefficient) % m.PRIME
    source = {}
    for exponent, coefficient in numerator.items():
        add_scaled(source, m.quotient_coordinates((*base, exponent), columns, pivots, free), coefficient)
    source_mod_sum = m.reduce_row(source, branch_sum)

    label_by_column = {columns[label]: label for label in low}
    derivative_rows = []
    for axis in range(2):
        image = {}
        for column, coefficient in source.items():
            label = label_by_column[column]
            add_scaled(image, m.connection_image(label, NAMES, GAMMA, axis, columns), coefficient)
        _, qd = m.parameter_derivative_data(axis)
        numerator_d = dict(qd["g23"])
        for exponent, coefficient in qd["g31"].items():
            numerator_d[exponent] = (numerator_d.get(exponent, 0) + coefficient) % m.PRIME
        for exponent, coefficient in numerator_d.items():
            m.add_value(image, columns[(*base, exponent)], coefficient)
        reduced = m.reduce_row(image, pivots)
        derivative_rows.append({column: reduced[column] for column in free if column in reduced})

    enlarged = {pivot: dict(row) for pivot, row in branch_sum.items()}
    before = len(enlarged)
    transverse_derivatives = []
    for row in derivative_rows:
        residual = m.reduce_row(row, branch_sum)
        transverse_derivatives.append(bool(residual))
        m.add_pivot(dict(row), enlarged)
    transverse_rank = len(enlarged) - before

    payload = {
        "schema": "marici.physical-union-transverse-line.v1",
        "prime": m.PRIME,
        "kinematics": target,
        "Q_value": (
            3*target[0]**4
            + 4*target[0]**3*(target[1]+target[2])
            - 2*target[0]**2*(7*target[1]**2 + 2*target[1]*target[2] + 3*target[2]**2)
            + 4*target[0]*(target[1]-3*target[2])*(target[1]+target[2])**2
            + (3*target[1]-5*target[2])*(target[1]+target[2])**3
        ) % m.PRIME,
        "ambient": AMBIENT,
        "cutoff": CUTOFF,
        "union_dimension": len(free),
        "branch_dimensions": [d23, d31],
        "branch_image_dimensions": [len(image23), len(image31)],
        "branch_intersection_dimension": len(image23) + len(image31) - len(branch_sum),
        "branch_sum_dimension": len(branch_sum),
        "source_lies_in_branch_sum": not bool(source_mod_sum),
        "first_derivatives_transverse": transverse_derivatives,
        "transverse_first_jet_rank": transverse_rank,
        "branch_sum_plus_first_jet_dimension": len(enlarged),
        "interpretation": "one transport-generated quotient line V26/(V23+V31)",
    }
    payload["passed"] = (
        payload["branch_dimensions"] == [20, 20]
        and payload["branch_image_dimensions"] == [20, 20]
        and payload["branch_intersection_dimension"] == 15
        and payload["branch_sum_dimension"] == 25
        and payload["source_lies_in_branch_sum"]
        and payload["transverse_first_jet_rank"] == 1
        and payload["branch_sum_plus_first_jet_dimension"] == 26
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(payload, indent=2))
    if not payload["passed"]:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
