#!/usr/bin/env python3
"""Validate the refined three-lane SCC model for the exceptional G/E transition."""
from pathlib import Path
import json,sys
R=Path(__file__).resolve().parents[3];sys.path.insert(0,str(R/'research/aspect/scc'))
from categorical_compiler import compile_diagram
p=R/'research/nima/contracts/n8-exceptional-boundary-transition-refined.scc.json';d=json.loads(p.read_text());r=compile_diagram(d);t=json.loads((R/'research/nima/results/n8-GE-boundary-transition.json').read_text());lanes=d['semantic_lanes'];inv=r['inverse_design'];sol=t['solutions'][0]
checks={'compiler_accepts':not r['errors'],'three_semantic_lanes':set(lanes)=={'literal_grassmannian','decorated_column','positive_domain'},'literal_lane_excludes_column_scaling':'no column scaling' in lanes['literal_grassmannian']['equivalence'],'separate_decorated_quotient_object':any(o['id']=='decorated_positroid_class' for o in d['objects']),'positive_domains_are_distinct_objects':all(any(o['id']==x for o in d['objects']) for x in ['G_positive_boundary_domain','E_positive_boundary_domain']),'ambient_claim_admitted':inv['ambient_route_coherence']['status']=='admitted','decorated_claim_admitted':inv['decorated_class_agreement']['status']=='admitted','positive_incidence_not_admitted':inv['positive_branch_incidence']['status'] in ('blocked','missing_witnesses'),'exact_transition_unique':t['solution_count']==1,'orientation_plus_one':t['log_jacobian_det']=='1','positive_image_exits_E_domain':sol['b7'].startswith('-') and sol['b8'].startswith('-')}
out={'schema':'marici.nima.n8-exceptional-boundary-transition-refined-scc.v1','checks':checks,'passed':all(checks.values()),'claim_status':{k:v['status'] for k,v in inv.items()},'representation_verdict':'Ambient Grassmannian equality, decorated-column quotient equivalence, and positive-domain incidence are distinct typed lanes. Ambient and decorated claims pass; positive branch incidence is blocked because the unique transition sends positive G coordinates to negative b7,b8.','required_transition_contract_fields':['source_chart_id','target_chart_id','ambient_space','transition_rational_map','inverse_or_uniqueness_witness','row_gauge','column_scaling_mode','source_domain_inequalities','target_domain_inequalities','image_sign_certificate','log_coordinate_order','log_jacobian_determinant','orientation_sign','decorated_permutation','exceptional_locus','provenance'],'atlas_relation':'The complete cyclic BCFW atlas supersedes this isolated seed-pair chart as a basis for global invariant facet orientation, but does not make the two original positive G/E domains overlap.'}
p=R/'research/nima/results/n8-exceptional-boundary-transition-refined-scc.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2));raise SystemExit(0 if out['passed'] else 1)
