from itertools import combinations, permutations, product
import json
from pathlib import Path


states = tuple(range(4))
permutation_processes = tuple(permutations(states))
all_function_processes = tuple(product(states, repeat=4))


def kernel(processes, domain):
    classes = {}
    for process in processes:
        signature = tuple(process[x] for x in domain)
        classes.setdefault(signature, []).append(process)
    return tuple(tuple(group) for group in classes.values())


def recoverable_domain(classes):
    recovered = []
    for x in states:
        if all(len({process[x] for process in group}) == 1 for group in classes):
            recovered.append(x)
    return tuple(recovered)


def closure(processes, domain):
    return recoverable_domain(kernel(processes, domain))


permutation_closures = {}
for size in range(5):
    closures = {closure(permutation_processes, domain) for domain in combinations(states, size)}
    permutation_closures[size] = closures

assert permutation_closures[0] == {()}
assert all(result == domain for domain in combinations(states, 1) for result in [closure(permutation_processes, domain)])
assert all(result == domain for domain in combinations(states, 2) for result in [closure(permutation_processes, domain)])
assert all(closure(permutation_processes, domain) == states for domain in combinations(states, 3))
assert closure(permutation_processes, states) == states

# For arbitrary functions, three probes do not force the fourth coordinate.
triple = (0, 1, 2)
assert closure(all_function_processes, triple) == triple

# Verify the defining Galois equivalence on every permutation-kernel relation
# generated by every domain pair in the finite fixture.
for generating_domain_size in range(5):
    for generating_domain in combinations(states, generating_domain_size):
        classes = kernel(permutation_processes, generating_domain)
        recovered = set(recoverable_domain(classes))
        for candidate_size in range(5):
            for candidate in combinations(states, candidate_size):
                left = set(candidate).issubset(recovered)
                right = all(
                    all(process[x] == group[0][x] for process in group for x in candidate)
                    for group in classes
                )
                assert left == right

# Intensional hostile: distinct two-stage histories have the same composite.
identity = (0, 1, 2, 3)
swap = (1, 0, 2, 3)


def compose(left, right):
    return tuple(left[right[x]] for x in states)


history_identity = (identity, identity)
history_cancel = (swap, swap)
assert history_identity != history_cancel
assert compose(*history_identity) == identity
assert compose(*history_cancel) == identity

result = {
    "schema": "marici.provenance-recovery-galois.v1",
    "permutation_process_count": len(permutation_processes),
    "all_function_process_count": len(all_function_processes),
    "permutation_domain_closure_sizes": {"0": 0, "1": 1, "2": 2, "3": 4, "4": 4},
    "three_probe_permutation_closure": 4,
    "three_probe_arbitrary_function_closure": 3,
    "galois_equivalence_checked": True,
    "full_state_action_recovers_factorization": False,
    "finite_falsifier": "equivalent processes differing on a claimed recovery input",
    "claim_boundary": "provenance determines maximal extensional recovery scope, not factorization history or execution",
    "status": "pass",
}

output = Path(__file__).resolve().parents[1] / "results" / "provenance-recovery-galois.json"
output.parent.mkdir(parents=True, exist_ok=True)
output.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
print(json.dumps(result, indent=2))
