"""Exact UDW-versus-QND same-effect instrument comparison."""
import json
from pathlib import Path
import sympy as sp

I=sp.I
c,s=sp.Rational(3,5),sp.Rational(4,5)
dag=lambda a:a.conjugate().T
rho00,rho01,rho10,rho11=sp.symbols("rho00 rho01 rho10 rho11")
rho=sp.Matrix([[rho00,rho01],[rho10,rho11]])
zero=sp.zeros(2)
eye=sp.eye(2)

# Absorptive one-mode UDW instrument.
A0=sp.diag(1,c)
A1=sp.Matrix([[0,-I*s],[0,0]])
# QND controlled-pointer instrument generated by
# H_QND = g |1><1| tensor sigma_x, ancilla initially |0>.
Q0=sp.diag(1,c)
Q1=sp.Matrix([[0,0],[0,-I*s]])

def branch(K): return sp.simplify(K*rho*dag(K))
def effect(K): return sp.simplify(dag(K)*K)
def channel(Ks): return sp.simplify(sum((branch(K) for K in Ks),zero))
def complete(Ks): return sp.simplify(sum((effect(K) for K in Ks),zero))

A=(A0,A1); Q=(Q0,Q1)
AE=[effect(k) for k in A]; QE=[effect(k) for k in Q]
AC=channel(A); QC=channel(Q)
Aclick=branch(A1); Qclick=branch(Q1)

# Sequential click-click branch.
AA11=sp.simplify(A1*A1)
QQ11=sp.simplify(Q1*Q1)

# Phase covariance under |1> -> z|1>. Scalar Kraus phases leave maps fixed.
z=sp.symbols("z", nonzero=True)
R=sp.diag(1,z); Ri=sp.diag(1,1/z)
A1p=sp.simplify(R*A1*Ri)
Q1p=sp.simplify(R*Q1*Ri)

checks={
 "absorptive_complete":complete(A)==eye,
 "qnd_complete":complete(Q)==eye,
 "identical_effects":all(AE[i]==QE[i] for i in range(2)),
 "identical_outcome_probabilities":all(sp.simplify(sp.trace(branch(A[i]))-sp.trace(branch(Q[i])))==0 for i in range(2)),
 "different_click_successors":sp.simplify(Aclick-Qclick)!=zero,
 "different_nonselective_updates":sp.simplify(AC-QC)!=zero,
 "absorptive_double_click_zero":AA11==zero,
 "qnd_double_click_nonzero":QQ11!=zero,
 "absorptive_phase_descent":sp.simplify(A1p-z**-1*A1)==zero,
 "qnd_phase_descent":sp.simplify(Q1p-Q1)==zero,
 "absorptive_tp":sp.simplify(sp.trace(AC)-sp.trace(rho))==0,
 "qnd_tp":sp.simplify(sp.trace(QC)-sp.trace(rho))==0,
}
assert all(checks.values())

def mat(m): return [[str(sp.simplify(x)) for x in m.row(i)] for i in range(m.rows)]
result={
 "schema":"marici.same-effect-different-capability.v1",
 "parameter":{"cos_theta":str(c),"sin_theta":str(s)},
 "absorptive_udw":{"kraus":[mat(A0),mat(A1)],"channel":mat(AC),"click_successor":mat(Aclick)},
 "qnd_controlled_pointer":{"kraus":[mat(Q0),mat(Q1)],"channel":mat(QC),"click_successor":mat(Qclick)},
 "shared_effects":[mat(x) for x in AE],
 "checks":checks,
 "verdict":(
  "The absorptive UDW and QND controlled-pointer interactions induce exactly "
  "the same effect algebra and outcome probabilities for every input state, "
  "but different selective, nonselective, and sequential updates. The "
  "interaction capability is not reconstructible from the public record law."
 )
}
out=Path(__file__).parents[1]/"results"/"same_effect_different_capability.json"
out.write_text(json.dumps(result,indent=2)+"\n",encoding="utf-8")
print(json.dumps(result,indent=2))
