"""Dimension matching: our 4D phase space vs 12D ADM per point.
Our Clifford generators {e1, e2, J} as spatial triad."""
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]

# Our phase space: (q, p, s, z) = 4D symplectic manifold T*R^2 × T*R^2
# Clifford generators: e1, e2, J = e1*e2  (3 generators, span Cl(2,0))
# The rotation generated by J is U(1) in the e1-e2 plane

# ADM phase space per spatial point:
# gamma_ab (metric, 6 comp) + pi^ab (momentum, 6 comp) = 12 comp
# After 3+1 decomposition, the spatial slice has:
# - 3-metric gamma_ab (symmetric, 6 comp)
# - Extrinsic curvature K_ab (symmetric, 6 comp)
# - Lapse N (1) + shift N^a (3) = 4 gauge

# LQG per spatial point:
# A^i_a (SU(2) connection, 9 comp) + E^a_i (densitized triad, 9 comp)
# After Gauss constraint: 6+6-3-3 = 6 physical comp per point
# After diffeomorphism: 2 physical comp per point

# Our phase space: 4 comp per point -> 2 physical (after U(1) gauge)
# This matches the 2 gravitational degrees of freedom per point!

# So the dimension matching IS possible:
# Our (q,p) -> 2 gravitational wave polarizations
# Our (s,z) -> 2 conjugate modes
# The U(1) gauge generated by J -> Gauss-like constraint

# Conjecture: our 4D phase space per spatial point IS the physical phase
# space of gravity after all constraints (Gauss + diffeomorphism + Hamiltonian).
# The 4 dimensions {q,p,s,z} correspond to the 2 gravitational wave
# polarizations and their conjugate momenta at each spatial point.

check = {
    'our_phase_space_dim': '4 (q,p,s,z)',
    'lqg_physical_dim': '2 (two gravitational wave polarizations per spatial point)',
    'matching': '4 -> 2 after U(1) gauge constraint (our J = e1*e2 generates U(1), one constraint)',
    'discrepancy': 'ADM has 12 -> 8 after 4 diffeomorphism constraints -> 2 after Hamiltonian + momentum constraints = 2',
    'clue': 'Our SU(2) promotion would add 3 Gauss constraints + 3 diffeomorphism constraints + 1 Hamiltonian constraint = 7 constraints, giving 9+9-7 = 11 per point. NOT matching 2!',
    'correction': 'The SU(2) promotion must be accompanied by spatial diffeomorphism invariance, which our model does not yet have.',
    'next': 'Test: can our U(1) gauge constraint (from J) be promoted to SU(2) Gauss constraint, AND can our system also implement spatial diffeomorphism constraints?',
}

result = {
    'schema': 'marici.nima.dimension-matching.v1',
    'classification': 'dimensions_promising_but_promotion_requires_spatial_diffeomorphism_invariance',
    'checks': [check],
}

out = ROOT / 'results/dimension-matching.json'
out.write_text(json.dumps(result, indent=2) + '\n', encoding='utf-8')
print(json.dumps(result, indent=2))