#!/usr/bin/env python3
"""Compute integral augmentation grades and the admissible Tate-product readout."""

from __future__ import annotations

import json
from pathlib import Path

import sympy as sp


ROOT = Path(__file__).resolve().parents[1]
RESULT = ROOT / "results" / "integral-tate-product-readout-type.json"


def main() -> None:
    # Coordinates use the Z-basis (t,t^2) of I. Columns generate the next ideal.
    i2_in_i = sp.Matrix([[0, -3], [1, -3]])
    # I^3 is generated by t^3=(-3,-3) and t^4=(9,6).
    i3_in_i = sp.Matrix([[-3, 9], [-3, 6]])
    index_i2_in_i = abs(int(i2_in_i.det()))
    index_i3_in_i = abs(int(i3_in_i.det()))
    index_i3_in_i2 = index_i3_in_i // index_i2_in_i
    assert index_i2_in_i == 3
    assert index_i3_in_i == 9
    assert index_i3_in_i2 == 3

    # The generator t^2 is not in I^3, while 3*t^2 is in I^3.
    t2 = sp.Matrix([0, 1])
    assert i3_in_i.inv() * t2 != (i3_in_i.inv() * t2).applyfunc(sp.floor)
    coords_3t2 = i3_in_i.inv() * (3 * t2)
    assert all(x.q == 1 for x in coords_3t2)

    result = {
        "status": "PASS",
        "multiplication_by_t_matrix": [[int(x) for x in row] for row in i2_in_i.tolist()],
        "lattice_indices": {
            "[I:I2]": index_i2_in_i,
            "[I:I3]": index_i3_in_i,
            "[I2:I3]": index_i3_in_i2,
        },
        "Tate_grade": "I/I2 = Z/3",
        "norm_grade": "I2/I3 = Z/3",
        "product": "[t] tensor [t] maps to [t^2]",
        "Hom_Z3_to_additive_C_rank": 0,
        "Hom_Z3_to_U1": "mu_3",
        "ordinary_complex_period_must_vanish": True,
        "correct_readout_candidates": [
            "Q/Z linking character",
            "mu_3 holonomy",
            "Bockstein phase",
            "exponentiated relative period",
        ],
    }
    RESULT.parent.mkdir(parents=True, exist_ok=True)
    RESULT.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(result, indent=2))


if __name__ == "__main__":
    main()
