#!/usr/bin/env python3
"""Exact quadratic realization of a separating five-point planar probe."""
import json
from fractions import Fraction
from pathlib import Path


def solve(matrix, rhs):
    a = [[Fraction(x) for x in row] + [Fraction(y)] for row, y in zip(matrix, rhs)]
    n = len(a)
    for column in range(n):
        pivot = next(row for row in range(column, n) if a[row][column])
        a[column], a[pivot] = a[pivot], a[column]
        scale = a[column][column]
        a[column] = [x / scale for x in a[column]]
        for row in range(n):
            if row != column and a[row][column]:
                scale = a[row][column]
                a[row] = [x - scale * y for x, y in zip(a[row], a[column])]
    return [a[i][-1] for i in range(n)]


def rank(matrix):
    a = [[Fraction(x) for x in row] for row in matrix]
    rows, columns, pivot_row = len(a), len(a[0]), 0
    for column in range(columns):
        pivot = next((r for r in range(pivot_row, rows) if a[r][column]), None)
        if pivot is None:
            continue
        a[pivot_row], a[pivot] = a[pivot], a[pivot_row]
        scale = a[pivot_row][column]
        a[pivot_row] = [x / scale for x in a[pivot_row]]
        for row in range(rows):
            if row != pivot_row and a[row][column]:
                scale = a[row][column]
                a[row] = [x - scale * y for x, y in zip(a[row], a[pivot_row])]
        pivot_row += 1
    return pivot_row


# a_i is the cyclic adjacent invariant s_{i,i+1}; b_i is s_{i,i+2}.
adjacent = [Fraction(p) for p in [2, 3, 5, 7, 11]]
# Momentum conservation paired with p_i requires
# a_{i-1} + a_i + b_i + b_{i-2} = 0 for every i modulo five.
matrix = [[int(j == i) + int(j == (i - 2) % 5) for j in range(5)] for i in range(5)]
rhs = [-(adjacent[(i - 1) % 5] + adjacent[i]) for i in range(5)]
chords = solve(matrix, rhs)

s = [[Fraction(0) for _ in range(5)] for _ in range(5)]
for i, value in enumerate(adjacent):
    j = (i + 1) % 5
    s[i][j] = s[j][i] = value
for i, value in enumerate(chords):
    j = (i + 2) % 5
    s[i][j] = s[j][i] = value

assert all(s[i][i] == 0 for i in range(5))  # masslessness
assert all(sum(row) == 0 for row in s)  # the all-ones vector is radical
assert rank(s) == 4

# In V = Q^5 / <(1,1,1,1,1)>, the basis images sum to zero and the
# descended symmetric form B=s/2 gives Q(p_i+p_{i+1})=a_i.
gram = [[entry / 2 for entry in row] for row in s]
recovered = [2 * gram[i][(i + 1) % 5] for i in range(5)]
assert recovered == adjacent

# The five triangulation Laurent monomials use distinct pairs of these five
# variables, hence distinct prime products provide exact finite separation.
triangulation_pairs = [(0, 1), (0, 4), (1, 2), (2, 3), (3, 4)]
probe_values = [Fraction(1, int(adjacent[i] * adjacent[j])) for i, j in triangulation_pairs]
assert len(set(probe_values)) == 5

fmt = lambda x: str(x.numerator) if x.denominator == 1 else f"{x.numerator}/{x.denominator}"
result = {
    "schema": "marici.fact5-quadratic-kinematic-probe.v1",
    "status": "passed",
    "strength": "exact five-point algebraic quadratic realization; no physical signature, normalization, or unbounded detection theorem",
    "ambient_construction": "Q^5 modulo the radical generated by the all-ones vector",
    "bilinear_rank": rank(s),
    "massless_diagonal": True,
    "momentum_conservation_descends": True,
    "adjacent_channel_invariants": list(map(fmt, adjacent)),
    "nonadjacent_invariants_for_conservation": list(map(fmt, chords)),
    "separating_triangulation_values": list(map(fmt, probe_values)),
    "finite_image_separated": True,
}
out = Path("research/nima/results/fact5_quadratic_kinematic_probe.json")
out.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
print(json.dumps(result, sort_keys=True))
