"""Test whether a spatial reader R exists such that D = R*H.

D = displacement matrix (3 x N_words)
H = retained-history matrix (various carrier dimensions x N_words)

ker(H) subset ker(D)  ⇔  a linear map R exists.

We test several candidate carriers:
  1. 6-D final-occurrence summary     (last primitive, one-hot)
  2. 10-D first-composable-pair carrier (word[0], word[1], one-hot)
  3. 16-D joint record (6-D + 10-D concatenated)
  4. 4-D source of first primitive    (one-hot on {A,B,C,D})
  5. 4-D target of last primitive     (one-hot on {A,B,C,D})
  6. 8-D source+target concatenated

For each carrier:
  - Carrier collision check:  ∃ h: two words with H(word)=h but D(word)≠D(word').
  - If no collision, solve D = R*H over exact Fractions via Gaussian elimination.
  - Report the outcome, including the explicit matrix R when it exists.

Additionally, we construct the explicit depth-independent reader:
  R_16 = [ V_target(p) | -V_source(a) ]
where the first 6 columns are V_target(last primitive) and the last 10 columns
are -V_source(first element of first pair).  This satisfies
  R_16 * h_16(w) = V_target(w[-1]) - V_source(w[0]) = displacement(w)
for every word of length >= 2 whose first pair is composable.
"""
from fractions import Fraction as F
from pathlib import Path
from collections import defaultdict
import json

from photon_native_spatial_step import REGISTRY, VERTICES, ClockedHistory

# -- Constants ------------------------------------------------------------

LABELS = [p.label for p in REGISTRY]
# Index: 0=AB, 1=BC, 2=CA, 3=BA, 4=AD, 5=DB

VERTEX_LABELS = ('A', 'B', 'C', 'D')
VERTEX_IX = {v: i for i, v in enumerate(VERTEX_LABELS)}

# Ordered list of the 10 composable primitive pairs.
PAIR_LIST = [
    ('AB', 'BA'),   # 0
    ('AB', 'BC'),   # 1
    ('AD', 'DB'),   # 2
    ('BA', 'AB'),   # 3
    ('BA', 'AD'),   # 4
    ('BC', 'CA'),   # 5
    ('CA', 'AB'),   # 6
    ('CA', 'AD'),   # 7
    ('DB', 'BA'),   # 8
    ('DB', 'BC'),   # 9
]
PAIR_MAP = {pair: i for i, pair in enumerate(PAIR_LIST)}

# -- Helpers --------------------------------------------------------------

def label_to_source(label):
    return next(p.source for p in REGISTRY if p.label == label)


def label_to_target(label):
    return next(p.target for p in REGISTRY if p.label == label)


def word_displacement(path):
    """Displacement = V_target(last) - V_source(first)."""
    pkts = path.packets
    src = pkts[0].source
    tgt = pkts[-1].target
    return tuple(VERTICES[tgt][k] - VERTICES[src][k] for k in range(3))


# -- Carrier functions ----------------------------------------------------

def carrier_6d(word):
    """One-hot on last primitive.  word: tuple of label strings."""
    c = [F(0)] * 6
    c[LABELS.index(word[-1])] = F(1)
    return tuple(c)


def carrier_10d(word):
    """One-hot on first composable pair (word[0], word[1]).

    Raises ValueError if the pair is not in PAIR_MAP (should not happen
    for any word generated by ClockedHistory, since every step composes).
    """
    key = (word[0], word[1])
    idx = PAIR_MAP.get(key)
    if idx is None:
        raise ValueError(f'Unknown first pair {key!r} in word {word}')
    c = [F(0)] * 10
    c[idx] = F(1)
    return tuple(c)


def carrier_16d(word):
    """Concatenation of 6-D final summary and 10-D first-pair carrier."""
    return carrier_6d(word) + carrier_10d(word)


def endpoint_source_4d(word):
    """One-hot on source of first primitive."""
    src = label_to_source(word[0])
    c = [F(0)] * 4
    c[VERTEX_IX[src]] = F(1)
    return tuple(c)


def endpoint_target_4d(word):
    """One-hot on target of last primitive."""
    tgt = label_to_target(word[-1])
    c = [F(0)] * 4
    c[VERTEX_IX[tgt]] = F(1)
    return tuple(c)


def endpoint_joint_8d(word):
    """Concatenation of 4-D source + 4-D target."""
    return endpoint_source_4d(word) + endpoint_target_4d(word)


# -- Carrier registry -----------------------------------------------------

CARRIER_DEFS = {
    '6d_final_summary':             (carrier_6d,           6,  1),
    '10d_first_pair':               (carrier_10d,         10,  2),
    '16d_joint':                    (carrier_16d,         16,  2),
    '4d_source_first_primitive':    (endpoint_source_4d,   4,  1),
    '4d_target_last_primitive':     (endpoint_target_4d,   4,  1),
    '8d_source_plus_target':        (endpoint_joint_8d,    8,  1),
}


def carrier_name_to_min_len(name):
    """Return the minimum word length required for this carrier."""
    for n, (_, _, min_len) in CARRIER_DEFS.items():
        if n == name:
            return min_len
    return 1


# -- Gaussian elimination over Fractions ---------------------------------

def solve_linear_system(H_rows, rhs):
    """Solve H*x = rhs over Fractions.

    Returns tuple (solution vector) of length dim, or None if inconsistent.

    H_rows: list of dim-length coefficient rows (each a tuple of F).
    rhs:    list of RHS values (F).
    """
    if not H_rows:
        return None
    dim = len(H_rows[0])
    aug = [list(row) + [rhs[i]] for i, row in enumerate(H_rows)]
    n_rows = len(aug)

    row = 0
    for col in range(dim):
        pivot = None
        for r in range(row, n_rows):
            if aug[r][col] != F(0):
                pivot = r
                break
        if pivot is None:
            continue
        aug[row], aug[pivot] = aug[pivot], aug[row]
        pv = aug[row][col]
        aug[row] = [x / pv for x in aug[row]]
        for r in range(n_rows):
            if r != row and aug[r][col] != F(0):
                factor = aug[r][col]
                aug[r] = [x - factor * y for x, y in zip(aug[r], aug[row])]
        row += 1

    solution = [F(0) for _ in range(dim)]
    for r in range(n_rows):
        for c in range(dim):
            if aug[r][c] != F(0):
                solution[c] = aug[r][-1]
                break
        else:
            if aug[r][-1] != F(0):
                return None  # inconsistent

    # Full verification
    for row_vec, d_val in zip(H_rows, rhs):
        if sum(row_vec[i] * solution[i] for i in range(dim)) != d_val:
            return None
    return tuple(solution)


def build_R(words, displacements, fn, dim, carrier_map):
    """Build 3xdim matrix R such that D = R*H.

    Uses Gaussian elimination over Fractions.
    Returns None if the system is inconsistent.
    """
    unique_carriers = sorted(carrier_map.keys(), key=str)
    H_rows = [list(c) for c in unique_carriers]

    cols = []
    for axis in range(3):
        rhs = [carrier_map[c][axis] for c in unique_carriers]
        col = solve_linear_system(H_rows, rhs)
        if col is None:
            return None
        cols.append(col)

    # cols[axis][col] -> R[axis][col]
    return tuple(tuple(cols[axis][col] for col in range(dim)) for axis in range(3))


# -- Explicit depth-independent readers ----------------------------------

def explicit_reader_16d():
    """Construct the explicit 3x16 reader.

    R_16 = [ V_target(last primitive)  |  -V_source(first-element-of-pair) ]

    First 6 columns (index = LABELS.index(p)):
      R_16[:, i] = VERTICES[target(p)]

    Last 10 columns (index = PAIR_LIST.index((a,b))):
      R_16[:, 6+j] = -VERTICES[source(a)]
    """
    # Left block: last primitive -> target position
    left = []
    for label in LABELS:
        tgt = label_to_target(label)
        left.append(tuple(VERTICES[tgt][k] for k in range(3)))
    # Right block: first element of first pair -> -source
    right = []
    for a, _ in PAIR_LIST:
        src = label_to_source(a)
        right.append(tuple(-VERTICES[src][k] for k in range(3)))
    # Transpose: R[axis] = [left[j][axis] for all j] ++ [right[j][axis] for all j]
    full = []
    for axis in range(3):
        row = tuple(left[j][axis] for j in range(6)) + tuple(right[j][axis] for j in range(10))
        full.append(row)
    return tuple(full)


def explicit_reader_8d():
    """Construct the explicit 3x8 reader.

    R_8 = [ -V_source  |  V_target ]
    where the first 4 columns correspond to source vertices (A,B,C,D)
    and the last 4 columns correspond to target vertices (A,B,C,D).
    """
    left = [tuple(-VERTICES[v][k] for k in range(3)) for v in VERTEX_LABELS]
    right = [tuple(VERTICES[v][k] for k in range(3)) for v in VERTEX_LABELS]
    full = []
    for axis in range(3):
        row = tuple(left[j][axis] for j in range(4)) + tuple(right[j][axis] for j in range(4))
        full.append(row)
    return tuple(full)


# -- Collision count helper ----------------------------------------------

def count_mismatches(displacements):
    """Count unordered word pairs that share a carrier group but differ in
    displacement.

    Within a carrier group (list of displacements for words sharing the same
    carrier value), the number of mismatched pairs is:
        C(n,2) - Σ C(n_d, 2)
    where n_d is the count of words with displacement d.
    """
    n = len(displacements)
    if n < 2:
        return 0, 0
    from collections import Counter
    counts = Counter(displacements)
    total_pairs = n * (n - 1) // 2
    match_pairs = sum(cnt * (cnt - 1) // 2 for cnt in counts.values())
    return total_pairs - match_pairs, total_pairs


# -- Kernel test ---------------------------------------------------------

def test_carrier(words, displacements, fn, dim):
    """Test ker(H) subset ker(D).

    Returns a dict:
        passed: bool
        status: str — 'pass', 'collision', 'inconsistent', 'empty'
        mismatches: int — number of carrier-sharing pairs with ≠ displacement
        total_sharing_pairs: int — number of unordered pairs sharing a carrier
        carrier_map: dict — carrier -> displacement (or None if ambiguous)
        R: 3xdim tuple or None
        R_source: str — 'explicit', 'solved', or None
    """
    groups = defaultdict(list)
    for word, disp in zip(words, displacements):
        h = fn(word)
        groups[h].append(disp)

    carrier_map = {}
    total_mismatches = 0
    total_sharing = 0
    collision = False

    for h, disps in groups.items():
        mm, pp = count_mismatches(disps)
        total_mismatches += mm
        total_sharing += pp
        if mm > 0:
            collision = True
            carrier_map[h] = None
        else:
            carrier_map[h] = disps[0]

    if collision:
        return {
            'passed': False,
            'status': 'collision',
            'mismatches': total_mismatches,
            'total_sharing_pairs': total_sharing,
            'carrier_map': carrier_map,
            'R': None,
            'R_source': None,
        }

    if not carrier_map:
        return {
            'passed': False,
            'status': 'empty',
            'mismatches': 0,
            'total_sharing_pairs': 0,
            'carrier_map': {},
            'R': None,
            'R_source': None,
        }

    # Try the explicit reader first (for known carriers).
    explicit = None
    if dim == 16:
        explicit = explicit_reader_16d()
    elif dim == 8:
        explicit = explicit_reader_8d()

    if explicit is not None:
        # Verify D = R*H
        ok = True
        for word, disp in zip(words, displacements):
            h = fn(word)
            predicted = tuple(
                sum(h[i] * explicit[axis][i] for i in range(dim))
                for axis in range(3)
            )
            if predicted != disp:
                ok = False
                break
        if ok:
            return {
                'passed': True,
                'status': 'pass',
                'mismatches': 0,
                'total_sharing_pairs': total_sharing,
                'carrier_map': carrier_map,
                'R': explicit,
                'R_source': 'explicit',
            }

    # Fall back to solving the linear system.
    R = build_R(words, displacements, fn, dim, carrier_map)
    if R is None:
        return {
            'passed': False,
            'status': 'inconsistent',
            'mismatches': total_mismatches,
            'total_sharing_pairs': total_sharing,
            'carrier_map': carrier_map,
            'R': None,
            'R_source': None,
        }

    # Verify
    for word, disp in zip(words, displacements):
        h = fn(word)
        predicted = tuple(
            sum(h[i] * R[axis][i] for i in range(dim))
            for axis in range(3)
        )
        if predicted != disp:
            return {
                'passed': False,
                'status': 'inconsistent',
                'mismatches': total_mismatches,
                'total_sharing_pairs': total_sharing,
                'carrier_map': carrier_map,
                'R': None,
                'R_source': None,
            }

    return {
        'passed': True,
        'status': 'pass',
        'mismatches': 0,
        'total_sharing_pairs': total_sharing,
        'carrier_map': carrier_map,
        'R': R,
        'R_source': 'solved',
    }


# -- Per-depth runner ----------------------------------------------------

def run_depth(depth, words, displacements, results):
    depth_result = {'word_count': len(words), 'carriers': {}}

    for name, (fn, dim, min_len) in sorted(CARRIER_DEFS.items()):
        if any(len(w) < min_len for w in words):
            depth_result['carriers'][name] = {
                'passed': None,
                'dim': dim,
                'reason': 'insufficient word length',
            }
            continue

        out = test_carrier(words, displacements, fn, dim)

        info = {
            'passed': out['passed'],
            'status': out['status'],
            'dim': dim,
            'total_carrier_values': len(out['carrier_map']),
            'pairs_sharing_carrier': out['total_sharing_pairs'],
            'pairs_with_mismatched_displacement': out['mismatches'],
            'R_exists': out['passed'],
            'R_source': out['R_source'],
        }
        if out['R'] is not None:
            info['R'] = [[str(x) for x in row] for row in out['R']]

        depth_result['carriers'][name] = info

    results['depths'][depth] = depth_result


# -- Main -----------------------------------------------------------------

def main():
    ROOT = Path(__file__).resolve().parents[3]
    DEST = ROOT / 'research/nima/results/factor-history-to-displacement.json'
    DEST.unlink(missing_ok=True)

    results = {'depths': {}}

    hist = ClockedHistory.initial()
    for depth in range(7):  # 0 … 6
        if depth > 0:
            hist = hist.advance()
        words = [tuple(p.label for p in path.packets) for path in hist.paths]
        displacements = [word_displacement(path) for path in hist.paths]
        run_depth(depth, words, displacements, results)

    # ── Console summary ──────────────────────────────────────────────
    print('Factorisation test:  D = R * H')
    print('  Status codes:')
    print('    PASS      - same carrier => same displacement, linear R exists')
    print('    COLLISION - two words share carrier but differ in displacement')
    print('    INCONSIST - no collision, but no linear R solves D=RH')
    print('    SKIP      - word too short for this carrier')
    print()

    for d, dr in sorted(results['depths'].items()):
        line = f'  depth {d}  ({dr["word_count"]:4d} words)'
        for name, info in sorted(dr['carriers'].items()):
            if info.get('passed') is True:
                tag = 'PASS'
                rsrc = info.get('R_source', '')
                if rsrc == 'explicit':
                    tag = 'PASS*'  # verified by explicit depth-independent reader
            elif info.get('passed') is False:
                st = info.get('status', 'FAIL')
                if st == 'collision':
                    tag = f'COLL({info["pairs_with_mismatched_displacement"]}/{info["pairs_sharing_carrier"]})'
                else:
                    tag = 'INCONS'
            else:
                tag = 'SKIP'
            line += f'  |  {name}: {tag}'
        print(line)

    print()

    # ── Aggregate verdicts ────────────────────────────────────────────
    tested_16d = [dr for dr in results['depths'].values()
                  if dr['carriers']['16d_joint'].get('passed') is not None]
    ok_16d = all(dr['carriers']['16d_joint'].get('passed') is True
                 for dr in tested_16d)
    if ok_16d:
        print('The 16-D joint record determines displacement at every tested depth (1-6).')
    else:
        print('WARNING: 16-D joint record does NOT determine displacement at some depth.')

    ok_8d = all(
        dr['carriers']['8d_source_plus_target'].get('passed') is True
        for dr in results['depths'].values()
        if dr['carriers']['8d_source_plus_target'].get('passed') is not None
    )
    if ok_8d:
        print('The 8-D endpoint joint determines displacement at every tested depth (0-6).')
    else:
        print('WARNING: 8-D endpoint joint does NOT determine displacement at some depth.')

    ok_6d = all(
        dr['carriers']['6d_final_summary'].get('passed') is True
        for dr in results['depths'].values()
        if dr['carriers']['6d_final_summary'].get('passed') is not None
    )
    if ok_6d:
        print('The 6-D final summary determines displacement at every tested depth.')
    else:
        print('The 6-D final summary does NOT always determine displacement.')

    # ── Explicit reader verification ──────────────────────────────────
    print()
    r16 = explicit_reader_16d()
    r8 = explicit_reader_8d()

    # Verify on all depth>=1 words
    errors_16d = 0
    errors_8d = 0
    total_long = 0
    hist = ClockedHistory.initial()
    for depth in range(7):
        if depth > 0:
            hist = hist.advance()
        for path in hist.paths:
            word = tuple(p.label for p in path.packets)
            disp = word_displacement(path)
            total_long += 1

            # 8-D
            h8 = endpoint_joint_8d(word)
            pred8 = tuple(
                sum(h8[i] * r8[axis][i] for i in range(8))
                for axis in range(3)
            )
            if pred8 != disp:
                errors_8d += 1

            # 16-D (only for depth >= 1, i.e. words of length >= 2)
            if len(word) >= 2:
                h16 = carrier_16d(word)
                pred16 = tuple(
                    sum(h16[i] * r16[axis][i] for i in range(16))
                    for axis in range(3)
                )
                if pred16 != disp:
                    errors_16d += 1

    print(f'Explicit reader R_8 verified on all {total_long} words:  '
          f'{errors_8d} errors.')
    print(f'Explicit reader R_16 verified on all words of length >= 2:  '
          f'{errors_16d} errors.')
    print()
    print('Proof sketch:')
    print('  R_16 * h_16(w) = V_target(w[-1]) + (-V_source(w[0]))')
    print('                 = V_target(w[-1]) - V_source(w[0])')
    print('                 = displacement(w)')
    print('  This holds for every composable word of length >= 2.')
    print()
    print('  R_8 * h_8(w)  = -V_source(w[0]) + V_target(w[-1])')
    print('                 = displacement(w)')
    print('  This holds for every word of length >= 1.')

    # ── Original 42/46 reproduction ──────────────────────────────────
    d3 = results['depths'][3]
    d3_words = []
    d3_disp = []
    hist = ClockedHistory.initial()
    for _ in range(3):
        hist = hist.advance()
    for path in hist.paths:
        d3_words.append(tuple(p.label for p in path.packets))
        d3_disp.append(word_displacement(path))

    six_groups = defaultdict(list)
    for i, w in enumerate(d3_words):
        s6 = carrier_6d(w)
        six_groups[s6].append(i)

    pairs_same6_diff10_diffD = 0
    pairs_same6_diff10_sameD = 0
    examples_sameD = []
    for s6, idxs in six_groups.items():
        for i in range(len(idxs)):
            for j in range(i + 1, len(idxs)):
                a, b = idxs[i], idxs[j]
                c10a = carrier_10d(d3_words[a])
                c10b = carrier_10d(d3_words[b])
                if c10a == c10b:
                    continue
                da = d3_disp[a]
                db = d3_disp[b]
                if da == db:
                    pairs_same6_diff10_sameD += 1
                    if len(examples_sameD) < 4:
                        examples_sameD.append({
                            'a': d3_words[a], 'b': d3_words[b],
                            'disp': [str(x) for x in da],
                            '6d_summary': str([str(s) for s in s6]),
                            '10d_a': str(c10a), '10d_b': str(c10b),
                        })
                else:
                    pairs_same6_diff10_diffD += 1

    results['depth3_reproduce_original'] = {
        'total_pairs_same6d_diff10d': pairs_same6_diff10_diffD + pairs_same6_diff10_sameD,
        'pairs_with_diff_displacement': pairs_same6_diff10_diffD,
        'pairs_with_same_displacement': pairs_same6_diff10_sameD,
        'examples_sameD': examples_sameD,
    }
    print()
    print(f'depth 3 reproduce: '
          f'{pairs_same6_diff10_diffD + pairs_same6_diff10_sameD} pairs sharing '
          f'6D summary and differing in 10D carrier')
    print(f'  {pairs_same6_diff10_diffD} have different displacement, '
          f'{pairs_same6_diff10_sameD} have same displacement')
    if examples_sameD:
        print(f'  Same-displacement examples (different internal paths, same endpoints):')
        for ex in examples_sameD:
            print(f'    {ex["a"]}  ~  {ex["b"]}  ->  {ex["disp"]}')

    results['interpretation'] = (
        "A carrier 'PASS' means ker(H) subset ker(D): the retained data "
        "determines displacement uniquely, so a linear map from carrier to R^3 "
        "exists. 'COLLISION' means two words share a carrier value but have "
        "different displacement — this is a definitive obstruction. "
        "'INCONSIST' means no collision occurred, yet no linear map exists "
        "for ALL observed carriers (the rank condition fails). "
        "The explicit readers R_8 and R_16 are verified depth-independent "
        "constructors; they prove existence directly without solving."
    )

    DEST.parent.mkdir(parents=True, exist_ok=True)
    DEST.write_text(json.dumps(results, indent=2) + '\n', encoding='utf-8')


if __name__ == '__main__':
    main()