#!/usr/bin/env python3
import json,sys
from dataclasses import asdict
from pathlib import Path
R=Path(__file__).resolve().parents[2];sys.path.insert(0,str(R/'research/conjecture_net'))
from event_log import *
from refinement import *
prior=json.loads((R/'research/conjecture_replay/results/NET6_split_codomain_pyramid_admitted.json').read_text());q=prior['projection'];p=Projection(q['graph_digest'],q['state_id'],frozenset(q['interfaces']),frozenset(q['facts']),q['sunk_cost'],frozenset(tuple(x) for x in q['resolved_actions']),tuple(q['event_ids']))
parent='PS1_exists_source_admissible_physical_specialization';gates=(
 Gate('PS1a_alternate_signed_minor_incidence',frozenset({'degree15_algebraic_relative_class'}),(InterfaceType('alternate_signed_minor_incidence','algebraic relative support','physical signed-minor strata'),),1,3,2,2,True),
 Gate('PS1b_nearby_cycle_current_specialization',frozenset({'degree15_algebraic_relative_class'}),(InterfaceType('nearby_cycle_specialization','algebraic relative class','physical BD nearby-cycle current'),),2,2,2,2,True),
 Gate('PS1c_modified_operation_source_admissibility',frozenset({'degree15_algebraic_relative_class'}),(InterfaceType('modified_operation_admissibility','candidate physical operation','frozen source operations'),),1,3,2,3,True),)
plan=RefinementPlan(parent,gates,(),ExistentialAggregationRule('*+'));plan.validate();first=plan.next_gate(p.interfaces);assert first and first.name=='PS1c_modified_operation_source_admissibility'
contract={'question':'Does at least one source-admissible specialization carry the exact degree-15 algebraic class to a physical BD class?','start':'algebraic_relative_class','terminal':'physical_BD_class','required_terminal_polarity':'*+','failed_frozen_branch':{'marked_corner_specialization':'+-'},'active_children':[{'name':g.name,'requires':sorted(g.requires),'produces':[asdict(x) for x in g.produces],'cost':g.estimated_cost,'score':g.score()} for g in gates],'aggregation':{'kind':'existential','early_success':'any child ending + resolves parent ++','failure':'all children resolved with terminal - gives parent -+'}}
g1=digest({'parent':p.graph_digest,'existential_specialization':contract});ev=RefinementEvent(p.graph_digest,parent,tuple(g.name for g in gates),digest(contract['active_children']),(),digest(contract['aggregation']),g1,'the marked-corner channel failed but does not exhaust source-admissible physical specializations',(prior['events'][-1]['event_id'],),'2026-09-11T00:01:29Z');log=EventLog.resume(p).append(ev)
pct={'active_specialization_branches':None,'codomain_alias_count':0.0,'minimum_next_test_cost':0.0,'formal_assignment_space_after_existential_constraint':-12.5}
out={'schema':'marici.conjecture-replay.PS1-existential-physical-specialization.v1','refinement_event':{'event_id':ev.event_id,**asdict(ev)},'projection':asdict(log.project()),'contract':contract,'recommendation':first.name,'metric_projection':{'base':'immediately previous corrected zero-solution branch','percent_change_from_previous_base':pct,'zero_base_note':'active branch count rose from zero, so its percentage is undefined','absolute_values_omitted_by_policy':True},'projection_scope_warning':'EventLog.resume preserves the complete available NET6 projection, but NET6 itself descends from historical segment-local projections; global pre-VC2 cumulative metrics still require ledger reconstruction.','passed':True};(R/'research/conjecture_replay/results/PS1_existential_physical_specialization.json').write_text(json.dumps(out,indent=2,default=list)+'\n');print(json.dumps({'passed':True,'parent':parent,'branches':3,'first':first.name,'percent_delta':pct,'event_count_preserved':len(p.event_ids)}))
