#!/usr/bin/env python3
import json,sys
from dataclasses import asdict,replace
from pathlib import Path
R=Path(__file__).resolve().parents[2];sys.path.insert(0,str(R/'research/conjecture_net'));from event_log import *
from graph_metrics import MetricAction,MetricGraph,percent_change
prior=json.loads((R/'research/conjecture_replay/results/PS1C1a1_admitted_authoritative_metrics.json').read_text());q=prior['projection'];p=Projection(q['graph_digest'],q['state_id'],frozenset(q['interfaces']),frozenset(q['facts']),q['sunk_cost'],frozenset(tuple(x) for x in q['resolved_actions']),tuple(q['event_ids']));src=R/'research/benincasa/results/PS1C1a1i_materialize_moving_Theta101.json';x=json.loads(src.read_text());snap=prior['metric_projection']['after_snapshot']
def act(z):return MetricAction(z['name'],frozenset(z['dependencies']),frozenset(z['requires']),frozenset(z['outcome_domain']),z['status'],z['terminal'])
bg=MetricGraph(tuple(act(z) for z in snap['actions']),frozenset(snap['interfaces']),tuple(frozenset(c) for c in snap['coherence_constraints']));before=bg.metrics();s1=digest({'parent':p.state_id,'PS1C1a1i':'-+','PS1C':'-+'});ev=ResolutionEvent('PS1C1a1i_materialize_moving_Theta101_coefficient',digest(x['outcome_contract']),p.graph_digest,p.state_id,'-+',('++','+-','--'),(f'{src.relative_to(R).as_posix()}#{digest(x)}',),1.,(('runtime','subsecond'),('kernel','infinite')),StateDelta(add_interfaces=('moving_Theta101_not_source_determined',),add_facts=('PS1C1a1i=-+','PS1C=-+')),(( 'PS1C1a1i=-+','entails','modified-operation branch rejected'),),('moving_Theta101_coefficient','PS1C_modified_operation_specialization'),s1,'2026-09-11T00:01:40Z');pruned=('PS1C1a1ii_first_normal_relative_image_test','PS1C1a1iii_iterate_to_pairing_required_order','PS1C1b_orientation_twisted_GM_connection','PS1C1c_source_Leray_tube_pairing');g1=digest({'parent':p.graph_digest,'prune':pruned});top=TopologyEvent(p.graph_digest,'remove',(),pruned,(),(),g1,'hard source-determination failure makes downstream modified-operation gates unreachable',(ev.event_id,),'2026-09-11T00:01:41Z');log=EventLog.resume(p).append(ev).append(top)
after_actions=[]
for a in bg.actions:
 if a.name=='PS1C1a1i_materialize_moving_Theta101_coefficient':after_actions.append(replace(a,status='resolved'))
 elif a.name in pruned:after_actions.append(replace(a,status='pruned'))
 elif a.name=='PS1C_modified_operation_specialization':after_actions.append(replace(a,status='resolved'))
 else:after_actions.append(a)
ag=MetricGraph(tuple(after_actions),bg.interfaces|{'moving_Theta101_not_source_determined'},bg.coherence_constraints);after=ag.metrics();pct=percent_change(before,after)
out={'schema':'marici.conjecture-replay.PS1C1a1i-admitted-authoritative-metrics.v1','events':[{'event_id':e.event_id,**asdict(e)} for e in (ev,top)],'projection':asdict(log.project()),'existential_parent_status':'unresolved; PS1A and PS1B remain','metric_projection':{'derived_metric_schema':'research/conjecture_net/graph_metrics.py','before_snapshot':snap,'after_snapshot':{'actions':[asdict(a) for a in ag.actions],'interfaces':sorted(ag.interfaces),'coherence_constraints':[sorted(c) for c in ag.coherence_constraints]},'before':before,'after':after,'percent_change_from_previous_base':pct},'next_recommendation':'PS1A0_axis_incidence','passed':True};(R/'research/conjecture_replay/results/PS1C1a1i_admitted_authoritative_metrics.json').write_text(json.dumps(out,indent=2,default=list)+'\n');print(json.dumps({'passed':True,'outcome':'-+','PS1C':'rejected','percent_delta':pct,'next':out['next_recommendation']}))
