#!/usr/bin/env python3
import json,sys
from dataclasses import asdict,replace
from pathlib import Path
R=Path(__file__).resolve().parents[2];sys.path.insert(0,str(R/'research/conjecture_net'));from event_log import *
from graph_metrics import MetricAction,MetricGraph,percent_change
prior=json.loads((R/'research/conjecture_replay/results/PS1A0_admitted_authoritative_metrics.json').read_text());q=prior['projection'];p=Projection(q['graph_digest'],q['state_id'],frozenset(q['interfaces']),frozenset(q['facts']),q['sunk_cost'],frozenset(tuple(x) for x in q['resolved_actions']),tuple(q['event_ids']));snap=prior['metric_projection']['after_snapshot'];src=R/'research/benincasa/results/PS1A1_matching_source_Leray_germs.json';x=json.loads(src.read_text())
def act(z):return MetricAction(z['name'],frozenset(z['dependencies']),frozenset(z['requires']),frozenset(z['outcome_domain']),z['status'],z['terminal'])
bg=MetricGraph(tuple(act(z) for z in snap['actions']),frozenset(snap['interfaces']),tuple(frozenset(c) for c in snap['coherence_constraints']));before=bg.metrics();s1=digest({'parent':p.state_id,'PS1A1':'++'});ev=ResolutionEvent('PS1A1_matching_source_Leray_germs',digest(x['outcome_contract']),p.graph_digest,p.state_id,'++',('+-','-+','--'),(f'{src.relative_to(R).as_posix()}#{digest(x)}',),1.,(('runtime','subsecond'),('germs','3')),StateDelta(add_interfaces=('weighted_matching_source_Leray_germs',),add_facts=('PS1A1=++',)),(('PS1A1=++','enables','PS1A2 global Cech gluing'),),(),s1,'2026-09-11T00:01:44Z');g1=digest({'parent':p.graph_digest,'add':'PS1A2'});top=TopologyEvent(p.graph_digest,'add',('PS1A2_global_marked_cut_Cech_gluing',),(),(),('PS1A1 -> PS1A2 -> PS1A',),g1,'local germs require simultaneous-cut compatibility',(ev.event_id,),'2026-09-11T00:01:45Z');log=EventLog.resume(p).append(ev).append(top)
aa=[]
for a in bg.actions:
 if a.name=='PS1A1_matching_source_Leray_germs':aa.append(replace(a,status='resolved'))
 elif a.name=='PS1A_alternate_signed_minor_specialization':aa.append(replace(a,dependencies=frozenset({'PS1A2_global_marked_cut_Cech_gluing'})))
 else:aa.append(a)
aa.append(MetricAction('PS1A2_global_marked_cut_Cech_gluing',frozenset({'PS1A1_matching_source_Leray_germs'}),frozenset({'weighted_matching_source_Leray_germs'})));ag=MetricGraph(tuple(aa),bg.interfaces|{'weighted_matching_source_Leray_germs'},bg.coherence_constraints);after=ag.metrics();pct=percent_change(before,after)
out={'schema':'marici.conjecture-replay.PS1A1-admitted-authoritative-metrics.v1','events':[{'event_id':e.event_id,**asdict(e)} for e in (ev,top)],'projection':asdict(log.project()),'metric_projection':{'derived_metric_schema':'research/conjecture_net/graph_metrics.py','before_snapshot':snap,'after_snapshot':{'actions':[asdict(a) for a in ag.actions],'interfaces':sorted(ag.interfaces),'coherence_constraints':[sorted(c) for c in ag.coherence_constraints]},'before':before,'after':after,'percent_change_from_previous_base':pct},'next_recommendation':'PS1A2_global_marked_cut_Cech_gluing','passed':True};(R/'research/conjecture_replay/results/PS1A1_admitted_authoritative_metrics.json').write_text(json.dumps(out,indent=2,default=list)+'\n');print(json.dumps({'passed':True,'outcome':'++','percent_delta':pct,'next':out['next_recommendation']}))
