#!/usr/bin/env python3
import json,sys
from dataclasses import asdict,replace
from pathlib import Path
R=Path(__file__).resolve().parents[2];sys.path.insert(0,str(R/'research/conjecture_net'));from event_log import *
from graph_metrics import MetricAction,MetricGraph,percent_change
prior=json.loads((R/'research/conjecture_replay/results/PS1M0_admitted_authoritative_metrics.json').read_text());q=prior['projection'];p=Projection(q['graph_digest'],q['state_id'],frozenset(q['interfaces']),frozenset(q['facts']),q['sunk_cost'],frozenset(tuple(x) for x in q['resolved_actions']),tuple(q['event_ids']));snap=prior['metric_projection']['after_snapshot'];src=R/'research/benincasa/results/PS1M1_Leray_Cech_homology_signature.json';x=json.loads(src.read_text())
def act(z):return MetricAction(z['name'],frozenset(z['dependencies']),frozenset(z['requires']),frozenset(z['outcome_domain']),z['status'],z['terminal'])
bg=MetricGraph(tuple(act(z) for z in snap['actions']),frozenset(snap['interfaces']),tuple(frozenset(c) for c in snap['coherence_constraints']));before=bg.metrics();s1=digest({'parent':p.state_id,'PS1M1':'++'});ev=ResolutionEvent('PS1M1_encode_Leray_Cech_homology_signature',digest(x['outcome_contract']),p.graph_digest,p.state_id,'++',('+-','-+','--'),(f'{src.relative_to(R).as_posix()}#{digest(x)}',),1.,(('runtime','subsecond'),('augmentation',str(x['augmentation_signature']))),StateDelta(add_interfaces=('PS1A_integral_H0_signature',),add_facts=('PS1M1=++',f"PS1A_H0={x['augmentation_signature']}")),(('PS1M1=++','enables','PS1M2 nearby-cycle projection'),),(),s1,'2026-09-11T00:01:57Z');log=EventLog.resume(p).append(ev);aa=[replace(a,status='resolved') if a.name=='PS1M1_encode_Leray_Cech_homology_signature' else a for a in bg.actions];ag=MetricGraph(tuple(aa),bg.interfaces|{'PS1A_integral_H0_signature'},bg.coherence_constraints);after=ag.metrics();pct=percent_change(before,after)
out={'schema':'marici.conjecture-replay.PS1M1-admitted-authoritative-metrics.v1','event':{'event_id':ev.event_id,**asdict(ev)},'projection':asdict(log.project()),'scope':'post-PS1 moduli classification','metric_projection':{'derived_metric_schema':'research/conjecture_net/graph_metrics.py','before_snapshot':snap,'after_snapshot':{'actions':[asdict(a) for a in ag.actions],'interfaces':sorted(ag.interfaces),'coherence_constraints':[sorted(c) for c in ag.coherence_constraints]},'before':before,'after':after,'percent_change_from_previous_base':pct},'next_recommendation':'PS1M2_project_nearby_cycle_to_degree15','passed':True};(R/'research/conjecture_replay/results/PS1M1_admitted_authoritative_metrics.json').write_text(json.dumps(out,indent=2,default=list)+'\n');print(json.dumps({'passed':True,'outcome':'++','signature':x['augmentation_signature'],'percent_delta':pct,'next':out['next_recommendation']}))
