#!/usr/bin/env python3
import json,sys
from dataclasses import asdict
from pathlib import Path
R=Path(__file__).resolve().parents[2];sys.path.insert(0,str(R/'research/conjecture_net'));from event_log import *
from graph_metrics import MetricAction,MetricGraph,percent_change
prior=json.loads((R/'research/conjecture_replay/results/PS1A_terminal_admitted_authoritative_metrics.json').read_text());q=prior['projection'];p=Projection(q['graph_digest'],q['state_id'],frozenset(q['interfaces']),frozenset(q['facts']),q['sunk_cost'],frozenset(tuple(x) for x in q['resolved_actions']),tuple(q['event_ids']));snap=prior['metric_projection']['after_snapshot'];src=R/'research/benincasa/results/PS1M0_realization_moduli_executability.json';x=json.loads(src.read_text())
def act(z):return MetricAction(z['name'],frozenset(z['dependencies']),frozenset(z['requires']),frozenset(z['outcome_domain']),z['status'],z['terminal'])
bg=MetricGraph(tuple(act(z) for z in snap['actions']),frozenset(snap['interfaces']),tuple(frozenset(c) for c in snap['coherence_constraints']));before=bg.metrics();s1=digest({'parent':p.state_id,'PS1M0':'+-'});ev=ResolutionEvent('PS1M0_realization_moduli_census',digest(x['outcome_contract']),p.graph_digest,p.state_id,'+-',('++','-+','--'),(f'{src.relative_to(R).as_posix()}#{digest(x)}',),1.,(('runtime','subsecond'),('candidate_packets','2')),StateDelta(add_interfaces=('PS1_realization_moduli_question_typed',),add_facts=('PS1M0=+-',)),(('PS1M0=+-','entails','existence proved but uniqueness open'),),(),s1,'2026-09-11T00:01:55Z');children=tuple(x['refinement']);g1=digest({'parent':p.graph_digest,'open_moduli':children});ref=RefinementEvent(p.graph_digest,'PS1M0_realization_moduli_census',children,digest({'sequence':children}),tuple(zip(children,children[1:])),digest({'comparison_requires_both_signatures':True}),g1,'classify whether the nearby-cycle packet is the same physical realization as PS1A',(ev.event_id,),'2026-09-11T00:01:56Z');log=EventLog.resume(p).append(ev).append(ref)
aa=list(bg.actions);aa.extend((MetricAction(children[0],frozenset(),frozenset({'degree15_physical_BD_specialization'})),MetricAction(children[1],frozenset({children[0]})),MetricAction(children[2],frozenset({children[1]})),MetricAction('PS1M_realization_moduli_classification',frozenset({children[2]}),terminal=True)));ag=MetricGraph(tuple(aa),bg.interfaces|{'PS1_realization_moduli_question_typed'},bg.coherence_constraints+(frozenset(children),));after=ag.metrics();pct=percent_change(before,after)
out={'schema':'marici.conjecture-replay.PS1M0-admitted-authoritative-metrics.v1','events':[{'event_id':e.event_id,**asdict(e)} for e in (ev,ref)],'projection':asdict(log.project()),'scope':'post-PS1 uniqueness/moduli extension; does not alter PS1=++','metric_projection':{'derived_metric_schema':'research/conjecture_net/graph_metrics.py','before_snapshot':snap,'after_snapshot':{'actions':[asdict(a) for a in ag.actions],'interfaces':sorted(ag.interfaces),'coherence_constraints':[sorted(c) for c in ag.coherence_constraints]},'before':before,'after':after,'percent_change_from_previous_base':pct},'next_recommendation':children[0],'passed':True};(R/'research/conjecture_replay/results/PS1M0_admitted_authoritative_metrics.json').write_text(json.dumps(out,indent=2,default=list)+'\n');print(json.dumps({'passed':True,'outcome':'+-','metrics':after,'percent_delta':pct,'next':out['next_recommendation']}))
