#!/usr/bin/env python3
import json,sys
from dataclasses import asdict,replace
from pathlib import Path
R=Path(__file__).resolve().parents[2];sys.path.insert(0,str(R/'research/conjecture_net'));from event_log import *
from graph_metrics import MetricAction,MetricGraph,percent_change
prior=json.loads((R/'research/conjecture_replay/results/PS1A2c_admitted_authoritative_metrics.json').read_text());q=prior['projection'];p=Projection(q['graph_digest'],q['state_id'],frozenset(q['interfaces']),frozenset(q['facts']),q['sunk_cost'],frozenset(tuple(x) for x in q['resolved_actions']),tuple(q['event_ids']));snap=prior['metric_projection']['after_snapshot'];src=R/'research/benincasa/results/PS1A_alternate_signed_minor_specialization.json';x=json.loads(src.read_text())
def act(z):return MetricAction(z['name'],frozenset(z['dependencies']),frozenset(z['requires']),frozenset(z['outcome_domain']),z['status'],z['terminal'])
bg=MetricGraph(tuple(act(z) for z in snap['actions']),frozenset(snap['interfaces']),tuple(frozenset(c) for c in snap['coherence_constraints']));before=bg.metrics();s1=digest({'parent':p.state_id,'PS1A':'++','PS1':'++'});ev=ResolutionEvent('PS1A_alternate_signed_minor_specialization',digest(x['outcome_contract']),p.graph_digest,p.state_id,'++',('+-','-+','--'),(f'{src.relative_to(R).as_posix()}#{digest(x)}',),1.,(('runtime','subsecond'),('terminal','PS1 witness')),StateDelta(add_interfaces=('degree15_physical_BD_specialization',),add_facts=('PS1A=++','PS1=++')),(( 'PS1A=++','witnesses','PS1 existential'),),(),s1,'2026-09-11T00:01:53Z');pruned=('PS1B0_current_specialization','PS1B_nearby_cycle_specialization');g1=digest({'parent':p.graph_digest,'prune':pruned,'PS1':'++'});top=TopologyEvent(p.graph_digest,'remove',(),pruned,(),(),g1,'PS1A supplies an existential witness; PS1B is retained historically but no longer active',(ev.event_id,),'2026-09-11T00:01:54Z');log=EventLog.resume(p).append(ev).append(top)
aa=[]
for a in bg.actions:
 if a.name=='PS1A_alternate_signed_minor_specialization':aa.append(replace(a,status='resolved'))
 elif a.name in pruned:aa.append(replace(a,status='pruned'))
 else:aa.append(a)
ag=MetricGraph(tuple(aa),bg.interfaces|{'degree15_physical_BD_specialization'},bg.coherence_constraints);after=ag.metrics();pct=percent_change(before,after)
out={'schema':'marici.conjecture-replay.PS1A-terminal-admitted-authoritative-metrics.v1','events':[{'event_id':e.event_id,**asdict(e)} for e in (ev,top)],'projection':asdict(log.project()),'PS1_resolution':'++','witness':'PS1A_alternate_signed_minor_specialization','metric_projection':{'derived_metric_schema':'research/conjecture_net/graph_metrics.py','before_snapshot':snap,'after_snapshot':{'actions':[asdict(a) for a in ag.actions],'interfaces':sorted(ag.interfaces),'coherence_constraints':[sorted(c) for c in ag.coherence_constraints]},'before':before,'after':after,'percent_change_from_previous_base':pct},'next_recommendation':None,'passed':True};(R/'research/conjecture_replay/results/PS1A_terminal_admitted_authoritative_metrics.json').write_text(json.dumps(out,indent=2,default=list)+'\n');print(json.dumps({'passed':True,'PS1':'++','percent_delta':pct,'open_actions':after['active_action_count']}))
