#!/usr/bin/env python3
"""Admit entries 434-435/544 as the actual CR1 alpha-kernel realization."""
import json,subprocess
from pathlib import Path
R=Path(__file__).resolve().parents[2]
def run(n):return subprocess.check_output(['python',str(R/'research/voevodsky'/n)],text=True)
s=run('check_multirees_conductor_stalk_kernel.py');g=run('check_global_mixed_variance_transform.py');a=run('check_global_log_artin_mixed_variance_realization.py')
checks={'stalks':'loaded_conductor_stalks: 215' in s,'squares':'face_localization_squares: 522' in s and 'all_multirees_conductor_squares: COMMUTE' in s,'routes':'two_step_localization_routes: 840' in s,'Cech':'three_chart_branch_unit_Cech_H1: ZERO' in s,'transform':'mixed_variance_transform_components: ALL_CONSTRUCTED' in g,'signature':'distinguished_sheet_object_image_signature: EXACT_MATCH' in g,'unique':'transform_image_equals_unique_framed_connector: YES' in g,'Kato':'normalization_sheet_kernel_in_Kato_sector: COMPLETE' in g,'Artin':'global_log_Artin_mixed_variance_realization: COMPLETE_IN_KATO_SECTOR' in a,'sixops':'connector_six_operations_preserve_Kato_sector: YES' in a}
assert all(checks.values()),checks
out={'schema':'marici.conjecture-replay.CR1-global-Kato-mixed-variance-transform.v1','actions':{'CR1ALPHA3_instantiate_kernel_on_actual_occurrence_multi_Rees_PC_stalks':'++','alpha_sh_mixed_variance_connector':'++ in the Kato-pulled trivial-inertia sector'},'construction':'Phi(M)=Rq_!(K(M) tensor^L omega_q^log tensor^L C_Cartier)','verified_counts':{'PC_stalks':215,'localization_squares':522,'evaluation_base_change_checks':4698,'two_step_routes':840},'image_signature':{'generic_Q_roof':1,'generic_Rees_factor':'x_D','closed_Cartier_residue':1,'endpoint_matrix':[[0,1],[1,0]],'Tor1_orientation':1,'Cech_residual':0,'Cartier_commutator':0,'reflection_defect':0,'Jordan_associator':0},'uniqueness':{'relative_deformation_group':0,'global_lift_torsor':0,'automorphisms':0,'connector_components':1},'scope_boundary':['complete in fs/Kato trivial-inertia constructible sector','not a raw global scheme span','physical derived pullback still next'],'produces':['instantiated_global_mixed_variance_transform','unique_global_framed_filtered_connector','global_log_Artin_Kato_realization'],'next':'CR1ALPHA4_form_physical_derived_pullback_and_evaluate_primitive','metric_delta':{'active_alpha_paths':1,'resolved_highest_centrality_interfaces':1,'new_typed_interfaces':3,'remaining_alpha_path_depth':-1,'immediate_downstream_unlocks':1},'checks':checks,'passed':True};p=R/'research/conjecture_replay/results/CR1_global_Kato_mixed_variance_transform.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'alpha':'++ (Kato sector)','stalks':215,'squares':522,'routes':840,'new_interfaces':3,'next':out['next']}))
