#!/usr/bin/env python3
import json,sys
from dataclasses import asdict,replace
from pathlib import Path
R=Path(__file__).resolve().parents[2];sys.path.insert(0,str(R/'research/conjecture_net'));from event_log import *
from graph_metrics import MetricAction,MetricGraph,percent_change
prior=json.loads((R/'research/conjecture_replay/results/PS1M1_admitted_authoritative_metrics.json').read_text());q=prior['projection'];p=Projection(q['graph_digest'],q['state_id'],frozenset(q['interfaces']),frozenset(q['facts']),q['sunk_cost'],frozenset(tuple(x) for x in q['resolved_actions']),tuple(q['event_ids']));snap=prior['metric_projection']['after_snapshot'];src=R/'research/benincasa/results/PS1M2_nearby_degree15_projection_audit.json';x=json.loads(src.read_text())
def act(z):return MetricAction(z['name'],frozenset(z['dependencies']),frozenset(z['requires']),frozenset(z['outcome_domain']),z['status'],z['terminal'])
bg=MetricGraph(tuple(act(z) for z in snap['actions']),frozenset(snap['interfaces']),tuple(frozenset(c) for c in snap['coherence_constraints']));before=bg.metrics();s1=digest({'parent':p.state_id,'PS1M2':'--'});ev=ResolutionEvent('PS1M2_project_nearby_cycle_to_degree15',digest(x['outcome_contract']),p.graph_digest,p.state_id,'--',('++','+-','-+'),(f'{src.relative_to(R).as_posix()}#{digest(x)}',),1.,(('runtime','subsecond'),('source_columns','6040')),StateDelta(add_interfaces=('degree15_to_nearby_projection_missing',),add_facts=('PS1M2=--',)),(('PS1M2=--','entails','materialize indexed column map before comparison'),),('nearby_degree15_signature',),s1,'2026-09-11T00:01:58Z');ch=tuple(x['refinement']);g1=digest({'parent':p.graph_digest,'refine':ch});ref=RefinementEvent(p.graph_digest,'PS1M2_project_nearby_cycle_to_degree15',ch,digest({'sequence':ch}),((ch[0],ch[1]),),digest({'map_then_apply':True}),g1,'projection is underdetermined without the source-column dictionary',(ev.event_id,),'2026-09-11T00:01:59Z');log=EventLog.resume(p).append(ev).append(ref)
aa=[]
for a in bg.actions:
 if a.name=='PS1M2_project_nearby_cycle_to_degree15':aa.append(replace(a,status='resolved'))
 elif a.name=='PS1M3_compare_realization_classes':aa.append(replace(a,dependencies=frozenset({ch[1]})))
 else:aa.append(a)
aa.extend((MetricAction(ch[0],frozenset({'PS1M2_project_nearby_cycle_to_degree15'})),MetricAction(ch[1],frozenset({ch[0]}))));ag=MetricGraph(tuple(aa),bg.interfaces|{'degree15_to_nearby_projection_missing'},bg.coherence_constraints+(frozenset((*ch,'PS1M3_compare_realization_classes')),));after=ag.metrics();pct=percent_change(before,after)
out={'schema':'marici.conjecture-replay.PS1M2-admitted-authoritative-metrics.v1','events':[{'event_id':e.event_id,**asdict(e)} for e in (ev,ref)],'projection':asdict(log.project()),'scope':'post-PS1 moduli classification; PS1 remains ++','metric_projection':{'derived_metric_schema':'research/conjecture_net/graph_metrics.py','before_snapshot':snap,'after_snapshot':{'actions':[asdict(a) for a in ag.actions],'interfaces':sorted(ag.interfaces),'coherence_constraints':[sorted(c) for c in ag.coherence_constraints]},'before':before,'after':after,'percent_change_from_previous_base':pct},'next_recommendation':ch[0],'passed':True};(R/'research/conjecture_replay/results/PS1M2_admitted_authoritative_metrics.json').write_text(json.dumps(out,indent=2,default=list)+'\n');print(json.dumps({'passed':True,'outcome':'--','percent_delta':pct,'next':out['next_recommendation']}))
