#!/usr/bin/env python3
import json,sys
from dataclasses import asdict,replace
from pathlib import Path
R=Path(__file__).resolve().parents[2];sys.path.insert(0,str(R/'research/conjecture_net'));from event_log import *
from graph_metrics import MetricAction,MetricGraph,percent_change
prior=json.loads((R/'research/conjecture_replay/results/PS1M3_admitted_authoritative_metrics.json').read_text());q=prior['projection'];p=Projection(q['graph_digest'],q['state_id'],frozenset(q['interfaces']),frozenset(q['facts']),q['sunk_cost'],frozenset(tuple(x) for x in q['resolved_actions']),tuple(q['event_ids']));snap=prior['metric_projection']['after_snapshot'];src=R/'research/benincasa/results/PS1M_realization_moduli_classification.json';x=json.loads(src.read_text())
def act(z):return MetricAction(z['name'],frozenset(z['dependencies']),frozenset(z['requires']),frozenset(z['outcome_domain']),z['status'],z['terminal'])
bg=MetricGraph(tuple(act(z) for z in snap['actions']),frozenset(snap['interfaces']),tuple(frozenset(c) for c in snap['coherence_constraints']));before=bg.metrics();s1=digest({'parent':p.state_id,'PS1M':'+-'});ev=ResolutionEvent('PS1M_realization_moduli_classification',digest(x['outcome_contract']),p.graph_digest,p.state_id,'+-',('++','-+','--'),(f'{src.relative_to(R).as_posix()}#{digest(x)}',),1.,(('runtime','subsecond'),('lower_bound','1')),StateDelta(add_interfaces=('PS1M_census_closed','degree15_to_nearby_chain_natural_transformation_missing'),add_facts=('PS1M=+-','realization_space_nonempty','uniqueness_unresolved')),(( 'PS1M=+-','entails','one classified point and open uniqueness'),),(),s1,'2026-09-11T00:02:03Z');log=EventLog.resume(p).append(ev);aa=[replace(a,status='resolved') if a.name=='PS1M_realization_moduli_classification' else a for a in bg.actions];ag=MetricGraph(tuple(aa),bg.interfaces|{'PS1M_census_closed','degree15_to_nearby_chain_natural_transformation_missing'},bg.coherence_constraints);after=ag.metrics();pct=percent_change(before,after)
out={'schema':'marici.conjecture-replay.PS1M-terminal-admitted-authoritative-metrics.v1','event':{'event_id':ev.event_id,**asdict(ev)},'projection':asdict(log.project()),'classification':x['theorem'],'reopening_interface':x['reopening_interface'],'PS1_resolution':'++ unchanged','metric_projection':{'derived_metric_schema':'research/conjecture_net/graph_metrics.py','before_snapshot':snap,'after_snapshot':{'actions':[asdict(a) for a in ag.actions],'interfaces':sorted(ag.interfaces),'coherence_constraints':[sorted(c) for c in ag.coherence_constraints]},'before':before,'after':after,'percent_change_from_previous_base':pct},'next_recommendation':None,'passed':True};(R/'research/conjecture_replay/results/PS1M_terminal_admitted_authoritative_metrics.json').write_text(json.dumps(out,indent=2,default=list)+'\n');print(json.dumps({'passed':True,'outcome':'+-','nonempty':True,'lower_bound':1,'uniqueness':None,'percent_delta':pct,'open_actions':after['active_action_count']}))
