#!/usr/bin/env python3
"""Admit the repository's analytic theta/Euler normalization and refine the bridge gap."""
import json,subprocess
from pathlib import Path
R=Path(__file__).resolve().parents[2]
a=(R/'research/grothendieck/the-additive-theta-euler-determinant-comparison-is-canonical-but-divisor-neutral.md').read_text(encoding='utf-8')
c=(R/'research/grothendieck/the-completed-theta-section-is-a-three-channel-codiagonal-not-a-product-of-local-determinants.md').read_text(encoding='utf-8')
r=subprocess.check_output(['python',str(R/'research/grothendieck/checkers/check_typed_theta_euler_tail_correspondence.py')],text=True)
checks={'EulerFock':'Unique factorization supplies the canonical basis identification' in a,'Mellin':'termwise Mellin transformation' in a,'rigidity':'Analytic continuation forces' in a,'codiagonal':'xi(s)=C(s)+U(s)+V(s)' in c,'typed':"'passed': 5" in r};assert all(checks.values()),checks
out={'schema':'marici.conjecture-replay.CR1-theta-Euler-normalization-source.v1','action':'locate_source_derived_theta_normalization','outcome':'++','canonical_chain':['prime occupation Fock basis -> integer labels by unique factorization','integer Gaussian samples -> theta source','theta source -> Mellin boundary section','Poisson sewing -> reciprocal completion'],'normalized_section':'xi(s)=C(s)+U(s)+V(s), with C=1/2 and reciprocal U,V','rigidity':'agreement in Re(s)>1 forces any holomorphic scalar gauge Q to equal 1 globally by analytic continuation','typing_control':'theta-source incidence and Euler-current evaluation remain distinct before scalarization (5/5 executable checks)','frontier_correction':'The theta-to-Euler normalization is not absent. The unresolved comparison is specifically between the Kato physical determinant generator and the Euler determinant/common carrier before applying the canonical theta readout.','remaining':['identify Det H(C_phys) with the Euler determinant/commonLine carrier','prove the Kato generator maps to the normalized three-channel theta codiagonal'],'metric_delta':{'sourced_theta_normalizations':1,'remaining_external_interfaces':-1,'new_active_comparison_paths':1},'checks':checks,'passed':True};p=R/'research/conjecture_replay/results/CR1_theta_Euler_normalization_source.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'outcome':'++','theta_normalization':'SOURCE_DERIVED_CANONICAL','remaining_interfaces':2,'next':out['remaining'][0]}))
