#!/usr/bin/env python3
import json,sys
from dataclasses import asdict,replace
from pathlib import Path
R=Path(__file__).resolve().parents[2];sys.path.insert(0,str(R/'research/conjecture_net'));from event_log import *
from graph_metrics import MetricAction,MetricGraph,percent_change
prior=json.loads((R/'research/conjecture_replay/results/PS1A2a_admitted_authoritative_metrics.json').read_text());q=prior['projection'];p=Projection(q['graph_digest'],q['state_id'],frozenset(q['interfaces']),frozenset(q['facts']),q['sunk_cost'],frozenset(tuple(x) for x in q['resolved_actions']),tuple(q['event_ids']));snap=prior['metric_projection']['after_snapshot'];src=R/'research/benincasa/results/PS1A2b_triple_cut_closure.json';x=json.loads(src.read_text())
def act(z):return MetricAction(z['name'],frozenset(z['dependencies']),frozenset(z['requires']),frozenset(z['outcome_domain']),z['status'],z['terminal'])
bg=MetricGraph(tuple(act(z) for z in snap['actions']),frozenset(snap['interfaces']),tuple(frozenset(c) for c in snap['coherence_constraints']));before=bg.metrics();s1=digest({'parent':p.state_id,'PS1A2b':'-+'});ev=ResolutionEvent('PS1A2b_triple_cut_closure',digest(x['outcome_contract']),p.graph_digest,p.state_id,'-+',('++','+-','--'),(f'{src.relative_to(R).as_posix()}#{digest(x)}',),1.,(('runtime','subsecond'),('triple_residual',str(x['triple_residual']))),StateDelta(add_interfaces=('PS1A_pair_weight_incidence_mistyped','correct_Cech_pair_weights_available'),add_facts=('PS1A2b=-+',)),(('PS1A2b=-+','entails','replace chain-boundary weights by Cech coboundary'),),('admitted_pair_packet_triple_closed',),s1,'2026-09-11T00:01:50Z');g1=digest({'parent':p.graph_digest,'add':'PS1A2c'});top=TopologyEvent(p.graph_digest,'add',('PS1A2c_correct_Cech_pair_weights',),(),(),('PS1A2b -> PS1A2c -> PS1A',),g1,'triple test exposed dual-incidence mismatch and an exact closing replacement',(ev.event_id,),'2026-09-11T00:01:51Z');log=EventLog.resume(p).append(ev).append(top)
aa=[]
for a in bg.actions:
 if a.name=='PS1A2b_triple_cut_closure':aa.append(replace(a,status='resolved'))
 elif a.name=='PS1A_alternate_signed_minor_specialization':aa.append(replace(a,dependencies=frozenset({'PS1A2c_correct_Cech_pair_weights'})))
 else:aa.append(a)
aa.append(MetricAction('PS1A2c_correct_Cech_pair_weights',frozenset({'PS1A2b_triple_cut_closure'}),frozenset({'source_oriented_pair_overlap_currents','correct_Cech_pair_weights_available'})));ag=MetricGraph(tuple(aa),bg.interfaces|{'PS1A_pair_weight_incidence_mistyped','correct_Cech_pair_weights_available'},bg.coherence_constraints);after=ag.metrics();pct=percent_change(before,after)
out={'schema':'marici.conjecture-replay.PS1A2b-admitted-authoritative-metrics.v1','events':[{'event_id':e.event_id,**asdict(e)} for e in (ev,top)],'projection':asdict(log.project()),'metric_projection':{'derived_metric_schema':'research/conjecture_net/graph_metrics.py','before_snapshot':snap,'after_snapshot':{'actions':[asdict(a) for a in ag.actions],'interfaces':sorted(ag.interfaces),'coherence_constraints':[sorted(c) for c in ag.coherence_constraints]},'before':before,'after':after,'percent_change_from_previous_base':pct},'next_recommendation':'PS1A2c_correct_Cech_pair_weights','passed':True};(R/'research/conjecture_replay/results/PS1A2b_admitted_authoritative_metrics.json').write_text(json.dumps(out,indent=2,default=list)+'\n');print(json.dumps({'passed':True,'outcome':'-+','residual':x['triple_residual'],'percent_delta':pct,'next':out['next_recommendation']}))
