#!/usr/bin/env python3
"""Bounded synthesis of past-research clues for the endpoint connector."""
import json
from pathlib import Path
R=Path(__file__).resolve().parents[2]
refs={'pointed_butterfly':'src/ledger/20260814-147 Pointed-Butterfly Reformulation of the Scalar NLSM Primitive.md','polarity_first':'src/ledger/20260815-144 Polarity-First Endpoint Pullback and the Single Sheet-Kernel Frontier.md','vertex_audit':'research/voevodsky/conductor_vertex_purity_audit.md','full_Q':'research/chatgpt/full_q_support_relative_morse_proof.md','anti_diag':'research/voevodsky/check_d03_antidiagonal_central_bockstein_obstruction.rs'}
texts={k:(R/v).read_text() for k,v in refs.items()};checks={'pointing_open':'endpoint_pointing": "open' in texts['pointed_butterfly'],'single_kernel_named':'alpha_{\\rm sh}^{!,\\check C}' in texts['polarity_first'],'purity_conditional':'source purity equivalence' in texts['vertex_audit'],'full_Q_roof_exact':'actual degree-one corrected roof cannot be a primitive nonzero Q-homology class' in texts['full_Q'],'parity_sequence_untyped':'typed loaded mapping-fiber' in texts['anti_diag'] and 'not asserted' in texts['anti_diag']}
assert all(checks.values()),checks
out={'schema':'marici.conjecture-replay.CR1-past-research-connector-clues-audit.v1','searched_clues':refs,'conclusions':['The pointed-butterfly reformulation explicitly leaves endpoint pointing open.','Polarity-first loading reduces the gap to alpha_sh^{!,Cech}, but does not construct it.','The Verdier-dual Yoneda route requires an independently constructed loaded absolute PC object and source purity equivalence.','The complete Q quotient makes the corrected roof exact, excluding coordinate-based nonzero-Q arguments.','The anti-diagonal parity class is nonzero in the coefficient shadow, but applying it physically requires the same untyped mapping-fiber connector.'],'positive_spatial_connector_found':False,'remaining_single_gate':'construct mixed-variance normalization-sheet kernel alpha_sh^{!,Cech} with two endpoint 2-cells','nonredundant_repository_experiments_remaining':False,'metric_delta':{'active_specialization_branches':0,'executable_specialization_paths':0,'geometrically_certified_complete_paths':0,'formal_signed_coherence_assignments':32,'typed_interfaces':20},'checks':checks,'passed':True};p=R/'research/conjecture_replay/results/CR1_past_research_connector_clues_audit.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'positive_connector':False,'executable_paths':0,'remaining_gate':out['remaining_single_gate']}))
