#!/usr/bin/env python3
"""Closure and leakage audit for the ten-iteration replay."""
import hashlib,json
from pathlib import Path
R=Path(__file__).resolve().parents[2]
names=['del_pezzo_entrance_freeze','del_pezzo_entrance_conjectures','del_pezzo_typed_quiver','del_pezzo_holdout_sequence','del_pezzo_cost_model','del_pezzo_probability_model','del_pezzo_policy_engine','del_pezzo_adaptive_policies','del_pezzo_replay_and_coupling','del_pezzo_stateful_policies']
packets={n:json.loads((R/f'research/conjecture_replay/results/{n}.json').read_text()) for n in names}
freeze=packets['del_pezzo_entrance_freeze'];inventory=packets['del_pezzo_entrance_conjectures'];stateful=packets['del_pezzo_stateful_policies'];old=packets['del_pezzo_adaptive_policies']
origin=R/freeze['cutoff']['artifact'];origin_hash=hashlib.sha256(origin.read_bytes()).hexdigest();holdout={x['path'] for x in freeze['holdout_manifest']}
prov={p for c in inventory['conjectures'] for p in c['provenance']}
checks={'all_packets_passed':all(x['passed'] for x in packets.values()),'origin_hash_unchanged':origin_hash==freeze['cutoff']['sha256'],'inventory_has_no_holdout_provenance':not(prov&holdout),'old_policy_uses_policy_safe_probabilities':packets['del_pezzo_policy_engine']['checks']['policy_probability_is_uniform'],'holdout_declared_scoring_only':packets['del_pezzo_holdout_sequence']['role'].startswith('retrospective scoring'),'naive_policy_misses_historical_first':old['solutions']['balanced']['expected']['best_first_action']=='DP6','stateful_expected_recovers_historical_first':stateful['solutions']['balanced']['expected']['best_first_action']=='DP1','stateful_credal_recovers_historical_first':stateful['solutions']['balanced']['credal_worst']['best_first_action']=='DP1','no_false_guarantee':stateful['solutions']['balanced']['minimax']['readout_success']==0}
assert all(checks.values()),checks
out={'schema':'marici.conjecture-replay.del-pezzo-final-audit.v1','packet_count':len(packets),'checks':checks,'limitations':['The M,E,L,P interpretation guard was reconstructed after inspecting the holdout; its policy success is retrospective, not out-of-sample validation.','Modification time reconstructs order but is weaker than a ledger-head or Git-commit snapshot.','Ordinal prior costs are sensitivity inputs; static AST/byte costs are not runtime measurements.','The eight-conjecture inventory may omit unrecorded historical alternatives.','Uniform and epsilon-credal probabilities are deliberately weak and do not model scientific dependence beyond the reconstructed guard.'],'verdict':'The replay falsifies an independent-edge planner and shows that a typed hypothesis-conditioned interpretation interface recovers the historical expected and robust first move. It does not yet validate the coupling prospectively.','passed':True}
dest=R/'research/conjecture_replay/results/del_pezzo_final_audit.json';dest.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'checks':checks,'verdict':out['verdict']}))
