#!/usr/bin/env python3
"""Coarse uniform margin for history + window + oriented Wronskian tail cell."""
import json
from fractions import Fraction as F
from pathlib import Path
from evidence_policy import write_result
R=Path(__file__).resolve().parents[2]
kappa=F(142,1000); half=kappa/2; lower=F(1,8)-half; det_lower=F(1,64)-half*half
checks={'half_kappa_lt_history_margin':half<F(1,8),'eigen_lower_positive':lower==F(54,1000),'det_lower_positive':det_lower>0};assert all(checks.values())
out={'schema':'marici.conjecture-replay.CR1-tail-block-coarse-margin.v1','passed':True,'claim_status':'proved','evidence':[{'class':'SOURCE_DERIVED','claim':'Each reciprocal retained history square has the uniform lower bound Q_L,+/-^*Q_L,+/- >=1/8 I.','source':'research/nima/the-retained-history-graph-realizes-the-g1-1-shifted-squares-with-the-theta-mass-bound.md'},{'class':'SOURCE_DERIVED','claim':'The source Euler-theta incidence satisfies |kappa_p|<0.142 uniformly.','source':'research/nima/the-euler-theta-incidence-is-uniformly-too-small-to-exhaust-the-window-area.md'},{'class':'SYMBOLIC','claim':'Exact rational Weyl and determinant bounds show that adding the oriented matrix with magnitude |kappa_p|/2 to a form bounded below by 1/8 leaves a positive margin; the window correction is positive semidefinite.','checker':'research/conjecture_replay/check_CR1_tail_block_coarse_margin.py'}],'outcome':'++ coarse source tail Green margin','cell':'G_tail,p=G_hist,p+diag(0,g_win,p)+[[0,-i c_p],[i c_p,0]], with c_p=-kappa_p/2 and g_win,p>=0','bounds':['G_hist,p >= (1/8)I','diag(0,g_win,p)>=0','||G_Wr,p||=|c_p|<0.071'],'weyl':'G_tail,p >= (1/8-0.071)I=0.054 I','determinant_coarse':'det lower in the diagonal 1/8 baseline is 1/64-0.071^2=0.010584>0','checks':checks,'fixture':'Applies in particular to p=2,3 without using their pilot decimal window energies.','meaning':'The oriented indefinite Wronskian correction cannot destroy local tail positivity in the retained source normalization.','qualification':'This is a lower-bound theorem for the assembled source tail cell, not an entrywise identification with the G4 target tail matrix. It assumes the history and Wronskian blocks are represented on the common retained two-output basis established by the source graph construction.','remaining':'G4 target readback of the same common basis and within-plane matrix; global completion/source equalizer remains open.','next':'add_the_0.054_tail_lower_margin_to_the_finite_fixture_and_form_the_complete_source_boundary_lower_bound_min(1/8,0.054)'}
write_result(R/'research/conjecture_replay/results/CR1_tail_block_coarse_margin.json',out);print(json.dumps({'passed':True,'tail_lower':float(lower),'det_lower':float(det_lower)}))
