#!/usr/bin/env python3
"""Assemble the exact finite source boundary metric packet and its lower bound."""
import json
from fractions import Fraction as F
from pathlib import Path
from evidence_policy import write_result
R=Path(__file__).resolve().parents[2]
lower=min(F(1,8),F(54,1000));assert lower==F(54,1000)
out={'schema':'marici.conjecture-replay.CR1-complete-finite-source-boundary-metric.v1','passed':True,'claim_status':'proved','evidence':[{'class':'SYMBOLIC','claim':'Block orthogonality and the proved wall/tail lower bounds assemble to a complete finite source boundary metric with lower margin 0.054.','checker':'research/conjecture_replay/check_CR1_complete_finite_source_boundary_metric.py'},{'class':'SOURCE_DERIVED','claim':'The retained history graph gives exact reciprocal shifted-square forms Q_+^*Q_+ and Q_-^*Q_- on one common carrier.','source':'research/nima/the-retained-history-graph-realizes-the-g1-1-shifted-squares-with-the-theta-mass-bound.md'}],'outcome':'++ complete exact source boundary metric packet','fixture':'p in {2,3}, grades 1,2, forward/reciprocal outputs retained','wall_block':'G_wall=diag(1/2,1/8) in the half-density even/odd trace basis','cross_block':'C_wt=0 in the Fourier-saturated topology','history_exact':'Q_(p,+/-)=2^(-1/2)(I +/- i H_(log p)); G_hist outputs are Q_(p,alpha)^*Q_(p,beta), retaining all four alpha,beta pairings rather than their diagonal sum','window_exact':'K_p=d_p tensor ell_jump, d_p=W_(2log p)-W_(log p); G_window,p=K_p^*G_win,pK_p=diag(0,G_win,p(d_p,d_p))','Wronskian_exact':'G_Wr,p=[[0,-i c_p],[i c_p,0]], c_p=-kappa_p/2, kappa_p=2 log(p) sum_(k>=1)p^(-k/2)Phi_prime(k log p)','tail_block':'G_tail,p=G_hist,p+G_window,p+G_Wr,p on the common two-output basis','boundary_block':'G_boundary,X=G_wall direct_sum G_tail,2 direct_sum G_tail,3, with primitive/square labels not summed','lower_bounds':{'wall':'1/8','tail_each':'0.054','complete':'0.054'},'exactness':'Expected values are operator/integral formulas; decimal quadrature is not part of their definition.','hostiles':['replace four history pairings by diagonal Pauli sum','insert a nonzero saturated wall-tail block','renormalize d_p to unit norm','erase imaginary Wronskian mixed entry','sum p=2 and p=3 before comparison'],'target_residual':'Delta_G,X=T_X^* G_G4,X T_X-G_boundary,X','acceptance':'Delta_G,X=0 entrywise as a closed form on the finite common core, separately on graph and rigged boundary rows; a shared positive lower bound is insufficient for equality.','consequence':'The source side of the joint Green comparison is now a single exact packet, not a list of missing within-plane values. Only the G4 target matrix/readback is absent.','next':'update_the_fixture_joint_slot_to_reference_this_packet_and_request_T_X^*G_G4T_X_entrywise'}
write_result(R/'research/conjecture_replay/results/CR1_complete_finite_source_boundary_metric.json',out);print(json.dumps({'passed':True,'source_metric_exact':True,'complete_lower':float(lower),'G4_target':False}))
