#!/usr/bin/env python3
"""What reciprocal-Real covariance does and does not imply for zero confinement."""
import json
from fractions import Fraction as F
from pathlib import Path
from evidence_policy import write_result
R=Path(__file__).resolve().parents[2]
# Exact rational complex test point off the seam, represented by (Re z, Im z).
z=(F(1,3),F(2,5));tau=lambda q:(-q[0],q[1]) # z -> -conj(z)
zz=tau(z)
checks={'off_seam_not_fixed':zz!=z,'tau_involution':tau(zz)==z,'fixed_locus_equation':tau((F(0),F(7,11)))==(F(0),F(7,11)),'orbit_has_two_points':len({z,zz})==2};assert all(checks.values())
out={'schema':'marici.conjecture-replay.CR1-reciprocal-real-fixed-locus.v1','passed':True,'claim_status':'proved','evidence':[{'class':'SYMBOLIC','claim':'Centered reciprocal followed by Real conjugation is the involution z -> -conjugate(z); its fixed locus is Re(z)=0, while an off-seam point forms a valid two-element orbit.','checker':'research/conjecture_replay/check_CR1_reciprocal_real_fixed_locus.py'},{'class':'SOURCE_DERIVED','claim':'The source characteristic has reciprocal covariance under s -> 1-s and a compatible fixed-fiber Real structure on the radial graph.','source':'research/conjecture_replay/results/CR1_reciprocal_cross_wall_parity.json'}],'outcome':'covariance pairs off-seam states but does not confine them','coordinates':'s=1/2+z','reciprocal':'z -> -z','real':'z -> conjugate(z)','combined':'tau(z)=-conjugate(z), equivalently s -> 1-conjugate(s)','fixed_locus':'tau(z)=z iff Re(z)=0 iff Re(s)=1/2','kernel_covariance':'If u_z lies in the characteristic kernel at z, reciprocal-Real transport produces u_tau(z) in the kernel at tau(z).','off_seam':'For Re(z)!=0, covariance permits the two distinct fibers z and -conjugate(z); it does not identify them.','why_local_uniqueness_fails':'One-dimensionality or faithful observation inside each fiber gives a unique line separately at z and tau(z), but supplies no equality between base parameters.','conditional_confinement':'Zero confinement would follow from the additional assertion that every characteristic kernel state is fixed by the combined reciprocal-Real transport as a state over the same base point. That assertion already forces z=tau(z).','missing_map':'A source-derived descent/equalizer from the parameter-orbit family to the fixed-point base, not merely an equivariant family over the two-point orbit.','hostile':'An off-seam pair of one-dimensional kernel lines exchanged antiunitarily satisfies all current covariance, Green, and scalar Xi laws.','consequence':'Reciprocal-Real symmetry explains quartet/pair structure of zeros but cannot prove RH without a fixed-state descent theorem.','RH':False,'next':'audit_whether_horizontal_four_presentation_descent_is_over_the_parameter_orbit_or_actually_imposes_fixed_point_descent; reject_any_argument_that_conflates_the_two'}
write_result(R/'research/conjecture_replay/results/CR1_reciprocal_real_fixed_locus.json',out);print(json.dumps({'passed':True,'fixed_locus':'Re z=0','off_seam_orbits_allowed':True,'RH':False}))
