#!/usr/bin/env python3
"""Metric audit for smoothed/literal theta sampling ports."""
import json
from pathlib import Path
from evidence_policy import write_result
R=Path(__file__).resolve().parents[2]
# Coefficient-space hostile: v_delta=(1,-1).
v=(1,-1);metrics={'positive_direct_sum':((1,0),(0,1)),'incoming_outgoing_Krein':((1,0),(0,-1)),'collapsed_codiagonal':((1,1),(1,1))}
def quad(G):return sum(v[i]*G[i][j]*v[j] for i in range(2) for j in range(2))
q={k:quad(G) for k,G in metrics.items()};assert q=={'positive_direct_sum':2,'incoming_outgoing_Krein':0,'collapsed_codiagonal':0}
out={'schema':'marici.conjecture-replay.CR1-sampling-heat-defect-supply.v1','passed':True,'claim_status':'proved','evidence':[{'class':'SYMBOLIC','claim':'The heat-defect vector inertia was computed exactly for the three candidate two-port metrics.','checker':'research/conjecture_replay/check_CR1_sampling_heat_defect_supply.py'},{'class':'SOURCE_DERIVED','claim':'Smoothed and literal sampling are distinct outputs with a structurally nonzero difference under the ordinary pairing.','source':'research/nima/the-comoving-window-transpose-produces-gaussian-smoothed-theta-sampling.md'}],'outcome':'-+','canonical_safe_form':'Before an input/output variance assignment is source-derived, independently typed outputs carry the positive direct-sum form ||y_sm||^2+||y_lit||^2.','heat_defect':'v_delta=(1,-1)','inertia':q,'conclusions':['Under the safe positive direct sum, the heat defect has strictly positive norm and is not neutral.','The Krein metric diag(1,-1) makes it neutral, but requires declaring one sampling as input and the other as output; no current source theorem provides that variance assignment.','The degenerate all-ones metric makes the difference radical and merely collapses the two distinct ports, recreating the forbidden identification.'],'operator_version':'With positive metrics G_sm,G_lit, ||Delta|| is not itself the graph norm, but a nonzero pair (S_sm psi,S_lit psi) cannot be declared neutral without a cross/Krein supply law.','decision':'Retain both with positive direct-sum metric for topology and observability. Do not use heat-defect neutrality in the Green cancellation equation until a source-derived variance-changing interconnection exists.','next':'search_for_or_construct_a_source_variance_arrow_that_types_smoothed_sampling_as_input_and_literal_sampling_as_output'}
write_result(R/'research/conjecture_replay/results/CR1_sampling_heat_defect_supply.json',out);print(json.dumps({'passed':True,'outcome':'-+','positive_norm':q['positive_direct_sum'],'Krein_neutral':True,'Krein_authorized':False}))
