#!/usr/bin/env python3
"""Final v2 audit after saturation and complete source Green assembly."""
import json
from pathlib import Path
from evidence_policy import write_result
R=Path(__file__).resolve().parents[2]
fixture=json.loads((R/'research/conjecture_replay/contracts/CR1-minimal-G4-five-port-conformance-fixture.v1.json').read_text())
g4=json.loads((R/'research/aspect/contracts/theta-rh-interaction-net-state.v3.json').read_text())
metric=json.loads((R/'research/conjecture_replay/results/CR1_complete_finite_source_boundary_metric.json').read_text())
ctors={x['id']:x['status'] for x in g4['constructors']}
checks={'source_metric_exact':metric['passed'] and metric['lower_bounds']['complete']=='0.054','all_fixture_slots_materialized':all(v is not None for v in fixture['target_readback_slots'].values()),'target_owner_readback_absent':g4['loading']['g4_owner_readback_constructed'] is False,'target_carrier_open':ctors['g4_radial_carrier_and_loading_readback']=='open','target_sewing_open':ctors['g4_half_turn_sewing_readback']=='open','conformance_false':fixture['terminal']['conforms'] is False};assert all(checks.values())
out={'schema':'marici.conjecture-replay.CR1-finite-G4-conformance-final.v2','passed':True,'claim_status':'proved','evidence':[{'class':'SYMBOLIC','claim':'The audit checks the current finite fixture, complete source boundary metric, and authoritative G4 constructor statuses.','checker':'research/conjecture_replay/check_CR1_finite_G4_conformance_final_v2.py'},{'class':'DECLARED','claim':'The G4 owner carrier/loading and half-turn readback constructors remain open.','source':'research/aspect/contracts/theta-rh-interaction-net-state.v3.json'}],'outcome':'source conformance packet exhausted; one authoritative target equalizer remains','checks':checks,'source_packet':{'comparison':'T_X=I_endpoint direct_sum I_label direct_sum C_u','metric':'G_boundary,X=G_wall direct_sum G_tail,2 direct_sum G_tail,3','lower_bound':'0.054 I','wall_tail_cross':'zero by Fourier-square character','linking':'graph -1/2(k0 wedge k1), rigged -1/2(delta0 wedge 1)','reciprocal':'full retained Fourier-Poisson graph candidate plus wall parity','archimedean':'faithful H observation and cross-wall normalization','jets':'all source families holomorphic/weakly entire on their declared rungs'},'single_target_witness':{'range':'T_X(range R_source,X)=range R_G4,joint,X','green':'T_X^* G_G4,X T_X=G_boundary,X entrywise','response':'T_X intertwines the retained four-presentation response and its contragredient dual','rigged':'T_X^times transports -1/2(delta0 wedge 1) to the G4 linking distribution','jets':'all equalities through order m-1 at a zero of order m'},'residual':'Delta_X is now evaluable immediately if and only if the authoritative target witness supplies G_G4,X and range R_G4,joint,X.','no_local_substitute':['same Xi determinant','same scalar codiagonal','same positivity margin','declared interface membership'],'verdict':{'source_side':'complete at finite fixture scope','target_side':'not exposed','G4_conformance':'open','RH':False},'next_external':'G4 owner instantiates the single target witness; then run entrywise and jet comparisons without coefficient fitting.'}
write_result(R/'research/conjecture_replay/results/CR1_finite_G4_conformance_final_v2.json',out);print(json.dumps(out['verdict']))
