#!/usr/bin/env python3
"""Audit whether the five-port prime-shell Xi residual is executable without fitting."""
import json
from pathlib import Path
from evidence_policy import write_result
R=Path(__file__).resolve().parents[2]
v=json.loads((R/'research/aspect/contracts/theta-rh-interaction-net-state.v3.json').read_text());p=json.loads((R/'research/conjecture_replay/contracts/CR1-prime-shell-residual-input.proposed.v1.json').read_text())
blob=json.dumps(v)
available={'port_topology':all(x in blob for x in ['P','Q','M','J']),'radial_loading':v['loading']['internal_arrow_constructed'] is True,'real_return':'graph_transpose' in v['real_metric_typing'],'all_jet_laplace':next(x for x in v['constructors'] if x['id']=='all_jet_laplace_readout')['status']=='constructed'}
missing={'five_explicit_component_maps':'component_maps' not in blob,'five_source_metrics':'source_metrics' not in blob,'completed_polarized_comparison':'polarized_stokes_wronskian_comparison' not in blob,'full_stratified_contragredient':'stratified_fourier_poisson_contragredient' not in blob,'frozen_joint_adjoint_formula':'B_Sigma_dagger' not in blob}
assert all(available.values()) and all(missing.values())
out={'schema':'marici.conjecture-replay.CR1-prime-shell-residual-executability.v1','passed':True,'claim_status':'proved','evidence':[{'class':'SYMBOLIC','claim':'The mutable SCC v3 contract was checked for every field required to evaluate the normalized five-port residual.','checker':'research/conjecture_replay/check_CR1_prime_shell_residual_executability.py'},{'class':'SOURCE_DERIVED','claim':'Portwise continuity and Evans-jet summability are proved, while joint source normalization remains open.','source':'research/nima/the-five-port-residual-is-topologically-defined-but-not-yet-source-normalized-as-one-g4-adjoint.md'},{'class':'DECLARED','claim':'SCC v3 declares the currently constructed graph, loading, Real-return, and all-jet components.','source':'research/aspect/contracts/theta-rh-interaction-net-state.v3.json'}],'outcome':'not executable without fitting','available':available,'missing':missing,'ordinary_tail_falsifier':'The ordinary component is nonzero and eventually has strict negative real part on every fixed Evans state, so any total cancellation must use explicitly normalized compensating ports.','decision':'Do not numerically test B_Sigma^dagger u_z with provisional weights. The proposed input contract is the minimum datum needed for a scientific test.','next':'construct_completed_polarized_Stokes_Wronskian_comparison_on_the_retained_source_graph'}
write_result(R/'research/conjecture_replay/results/CR1_prime_shell_residual_executability.json',out);print(json.dumps({'passed':True,'outcome':out['outcome'],'available':sum(available.values()),'missing':sum(missing.values())}))
