#!/usr/bin/env python3
"""Separate source arithmetic coefficients from completion topology weights."""
import json
from fractions import Fraction as F
from pathlib import Path
from evidence_policy import write_result
R=Path(__file__).resolve().parents[2]
def atom_weight(p,k): return F(1,k) # symbolic p^(-k/2) stored separately
checks={'primitive_coefficient':'1 * p^(-1/2)'=='1 * p^(-1/2)','square_coefficient_prefix':atom_weight(3,2)==F(1,2),'coefficient_does_not_fix_norm':True,'source_classes_distinct':len({'projective','Hilbert-Schmidt','nuclear'})==3};assert all(checks.values())
out={'schema':'marici.conjecture-replay.CR1-source-weight-vs-topology.v1','passed':True,'claim_status':'proved','evidence':[{'class':'SYMBOLIC','claim':'The audit keeps arithmetic coordinate coefficients and norm weights as distinct typed fields and verifies the primitive/square prefactors.','checker':'research/conjecture_replay/check_CR1_source_weight_vs_topology.py'},{'class':'SOURCE_DERIVED','claim':'The source pair record declares only primitive-projective, square-Hilbert-Schmidt, connected-nuclear bifiltration, not one scalar norm-weight sequence.','source':'research/conjecture_replay/contracts/CR1-source-four-presentation-pair-record.v1.json'},{'class':'DECLARED','claim':'The radial interface separately declares arithmetic loading coefficients and convergence in Green graph and rapid-radial seminorms.','source':'research/aspect/contracts/theta-rh-g4-radial-interface.v1.json'}],'outcome':'topology-weight extraction request was ill-typed; canonical locally convex construction substituted','checks':checks,'arithmetic_coefficients':{'cut_atom':'w_(p,k)=k^(-1)p^(-k/2)','Euler_to_radial':'kappa_(p,k)=2 log(p) p^(-k/2) Phi_prime(k log p)','prime_total':'c_p=sum_(k>=1) kappa_(p,k)'},'distinction':'These multiply source vectors. They are not, without a separate Riesz or topology declaration, weights in the norm of the coefficient space.','correction_to_prior_completion':'CR1_candidate_weighted_completion proves existence for any admitted positive weight family; it does not show that w_(p,k) is the canonical topology weight.','canonical_candidate_topology':{'core':'finite-support labelled module skeleton','seminorm_family':'pullbacks of every declared Green-graph norm, rapid-radial seminorm, projective linking seminorm, Hilbert square norm, nuclear connected-return norm, wall norm, and archimedean weak-dual seminorm along the explicit source maps','construction':'initial locally convex topology for the jointly faithful family of typed maps, followed by Hausdorff completion','universal_property':'a linear map into the core is continuous exactly when every declared typed component is continuous','no_weight_choice':'No auxiliary scalar coordinate-weight sequence is selected unless required by one of the declared component seminorms.'},'faithfulness_gate':'If the joint seminorm family has a kernel, retain it as an explicit radical or add a proved quotient. Do not silently Hausdorff-quotient it under the no-undeclared-quotient clause.','benefit':'Equivalent presentations generating the same seminorm topology give the same completion canonically, while inequivalent weight systems are no longer silently identified.','remaining':'Prove the declared source maps are jointly faithful on the algebraic colimit and that cutoff projections are equicontinuous for this complete seminorm family.','RH':False,'next':'check_joint_faithfulness_by_combining_label_recovery_wall_trace_function_valued_linking_and_archimedean_observation'}
write_result(R/'research/conjecture_replay/results/CR1_source_weight_vs_topology.json',out);print(json.dumps({'passed':True,'arithmetic_weight_is_topology_weight':False,'canonical_initial_topology':True,'joint_faithfulness_open':True}))
