#!/usr/bin/env python3
"""Exact block pullback metric for a retained-source multiport graph."""
import json
from fractions import Fraction as F
from pathlib import Path
from evidence_policy import write_result
R=Path(__file__).resolve().parents[2]
# One finite hostile-sized scalar instance verifies the block formula exactly.
g0=F(3); ts=[F(2),F(-1),F(4),F(1,2),F(-3)]; gs=[F(5),F(7),F(2),F(11),F(1,3)]
pull=g0+sum(g*t*t for g,t in zip(gs,ts));direct=lambda x,y:g0*x*y+sum(g*(t*x)*(t*y) for g,t in zip(gs,ts));assert direct(F(2),F(-3))==pull*F(2)*F(-3)
out={'schema':'marici.conjecture-replay.CR1-five-port-pullback-metric.v1','passed':True,'claim_status':'proved','evidence':[{'class':'SYMBOLIC','claim':'The direct-sum metric pullback and adjoint formulas were checked exactly over rational finite-cutoff data.','checker':'research/conjecture_replay/check_CR1_five_port_pullback_metric.py'},{'class':'SOURCE_DERIVED','claim':'The five port maps are continuous on the retained source graph, while their final common G4 normalizations remain open.','source':'research/nima/the-five-port-residual-is-topologically-defined-but-not-yet-source-normalized-as-one-g4-adjoint.md'}],'outcome':'++ universal metric theorem; conditional for G4 normalization','formula':{'target_metric':'G_target=G_0 direct_sum G_ordinary direct_sum G_derivative direct_sum G_wall direct_sum G_reciprocal direct_sum G_link','graph_map':'J_5=(I,T_ordinary,T_derivative,T_wall,T_reciprocal,T_link)^T','pullback':'G_pb=G_0+sum_j T_j^* G_j T_j','adjoint':'J_5^dagger(y_0,...,y_5)=G_pb^-1(G_0 y_0+sum_j T_j^*G_j y_j)'},'nondegeneracy':'If G_0 is positive definite, then G_pb>=G_0; the retained recovery coordinate prevents every compact port from creating a radical or collapsing the finite-cutoff lower margin.','uniqueness':'Once all target metrics G_j and the source metric G_0 are fixed, this pullback metric and graph adjoint are uniquely forced.','critical_limitation':'The formula does not derive the missing G_j. Choosing them to cancel the Evans residual would be fitting. In particular the ordered-link mixed orientation and full reciprocal response metric remain source inputs.','completion':'On the Fréchet/projective source the formula is interpreted rungwise or as a compatible family of forms; existence of one bounded inverse G_pb^-1 on a global Hilbert completion is not asserted.','next':'inventory_which_of_the_six_block_metrics_are_source_fixed_and_isolate_the_first_missing_matrix_entry'}
write_result(R/'research/conjecture_replay/results/CR1_five_port_pullback_metric.json',out);print(json.dumps({'passed':True,'outcome':out['outcome'],'formula_verified':True,'G4_metrics':'partial'}))
