#!/usr/bin/env python3
"""Classify which candidate conformance laws survive changes of completion weights."""
import json
from fractions import Fraction as F
from pathlib import Path
from evidence_policy import write_result
R=Path(__file__).resolve().parents[2]
N=12; w={n:F(1) for n in range(1,N+1)}; veq={n:F(2) for n in w}; vbad={n:F(n) for n in w}
def ratios(a,b): return [b[n]/a[n] for n in a]
eq=ratios(w,veq);bad=ratios(w,vbad)
checks={'equivalent_ratio_bounds':[min(eq),max(eq)]==[F(2),F(2)],'inequivalent_upper_constants_grow':bad[-1]==N and all(bad[i]<bad[i+1] for i in range(N-1)),'finite_support_identity_same':set(w)==set(vbad),'no_uniform_inverse_from_growing_ratio':max(bad)==N};assert all(checks.values())
out={'schema':'marici.conjecture-replay.CR1-candidate-weight-dependence.v1','passed':True,'claim_status':'proved','evidence':[{'class':'SYMBOLIC','claim':'Exact weighted-sequence calculations distinguish uniformly equivalent weights from a family whose finite-cutoff comparison constants diverge.','checker':'research/conjecture_replay/check_CR1_candidate_weight_dependence.py'}],'outcome':'completion canonical only up to uniformly equivalent source-compatible weights','criterion':'For weighted l1 or l2 coordinate sums, identity extends bi-boundedly iff weight ratios v_lambda/w_lambda are bounded above and below away from zero.','equivalent_case':'v=2w gives constants 2 on l1 and sqrt(2) on l2 and the same completed vectors/topology.','hostile_case':'v_n=n w_n has finite-cutoff identity maps but comparison constants grow with cutoff; finite-stage conformance does not identify the completions.','checks':checks,'weight_invariant':['label skeleton and cutoff category','algebraic source incidence','reciprocal/Fourier/Real identities on finite support','C_wt=0 from character orthogonality when both actions extend','function-valued Stokes and multiplicity-jet equations on the common core'],'weight_sensitive':['boundedness and compactness classes','which infinite loading vectors converge','uniform Green lower bounds','closed range and surjectivity','continuity of terminal scalar readout'],'canonicality_boundary':'The completed candidate is canonical in the category whose objects use one declared equivalence class of source-compatible weights. Finite universal properties alone do not select that class.','source_selection':'The existing primitive-projective, square-Hilbert-Schmidt, connected-nuclear and rapid-radial estimates constrain an admissible class, but a uniqueness theorem must compare any rival weights by uniform ratio bounds.','falsifier':'Produce an admissible rival weight family with unbounded ratios that still supports every declared loading, response, metric, and readout law. That would refute global uniqueness while preserving all finite candidates.','remaining':'Freeze the actual source weight family from the arithmetic loading and test rival admissible families against the terminal readout and Green lower bound.','RH':False,'next':'extract_the_exact_declared_source_weights_per_prime_grade_and_form_the_uniform_ratio_acceptance_test'}
write_result(R/'research/conjecture_replay/results/CR1_candidate_weight_dependence.json',out);print(json.dumps({'passed':True,'finite_canonical':True,'global_weight_independent':False,'max_hostile_ratio':N}))
