#!/usr/bin/env python3
"""Final finite fixture comparison: source/interface candidates versus authoritative G4 readback."""
import json
from pathlib import Path
from evidence_policy import write_result
R=Path(__file__).resolve().parents[2]
fixture=json.loads((R/'research/conjecture_replay/contracts/CR1-minimal-G4-five-port-conformance-fixture.v1.json').read_text())
g4=json.loads((R/'research/aspect/contracts/theta-rh-interaction-net-state.v3.json').read_text())
ctors={x['id']:x for x in g4['constructors']}
checks={'fixture_all_slots_materialized':all(v is not None for v in fixture['target_readback_slots'].values()),'owner_loading_readback_false':g4['loading']['g4_owner_readback_constructed'] is False,'owner_carrier_open':ctors['g4_radial_carrier_and_loading_readback']['status']=='open','owner_halfturn_open':ctors['g4_half_turn_sewing_readback']['status']=='open','fixture_not_conformant':fixture['terminal']['conforms'] is False,'no_RH':fixture['terminal']['rh_implication'] is False};assert all(checks.values())
out={'schema':'marici.conjecture-replay.CR1-finite-G4-conformance-final.v1','passed':True,'claim_status':'proved','evidence':[{'class':'SYMBOLIC','claim':'The final audit reads the mutable fixture and authoritative G4 contract and verifies that every source/interface candidate is materialized while both owner readback constructors remain explicitly open.','checker':'research/conjecture_replay/check_CR1_finite_G4_conformance_final.py'},{'class':'DECLARED','claim':'The authoritative contract marks G4 carrier/loading and half-turn readbacks open and the owner readback flag false.','source':'research/aspect/contracts/theta-rh-interaction-net-state.v3.json'}],'outcome':'finite conformance fixture complete; target identity authority-blocked','checks':checks,'fixture':fixture['schema'],'finite_packet':{'shell':'p=2,3','grades':'k=1 primitive, k=2 square','orientations':'forward and reciprocal','retained':'regular/wall traces, function-valued Wronskian, archimedean radial coordinate, all local jets'},'source_expected':{'linking':'-1/2(k_0 wedge k_1) on graph; -1/2(delta_0 wedge 1) on rigged dual','reciprocal':'coherent/transverse W parity +1/-1 and Green cross values -2/+2','archimedean':'A_z(G_theta)=2xi(s), H=(A-1)/(s(s-1)), faithful state line and cross-wall scale','comparison':'T_X=I_endpoint direct_sum I_label direct_sum C_u'},'surviving_delta':{'owner_range_equalizer':'T_X(range source_X) minus range(G4_joint_X)','joint_Green_cross_block':'pullback(T_X,target joint Green)-source endpoint/radial/linking Green','linking_transport':'target graph and rigged linking images minus transported source images','four_presentation_readback':'target F/W readback minus T_X-transported source action'},'multiplicity_gate':'At every zero s0 of order m, each surviving function-valued residual and derivatives j=0,...,m-1 must vanish uniformly on completion-bounded sets.','authority_boundary':'No repository object supplies the target side of these residuals. Filling them from scalar Xi agreement would manufacture the owner readback and violate the declared universal-Riesz and cross-metric restrictions.','verdict':{'source_fixture':'complete','interface_candidate':'complete','G4_conformance':'not_established','RH':False},'next_external_action':'G4 owner must instantiate g4_radial_carrier_and_loading_readback and g4_half_turn_sewing_readback, then this exact packet can be evaluated without fitting.'}
write_result(R/'research/conjecture_replay/results/CR1_finite_G4_conformance_final.json',out);print(json.dumps(out['verdict']))
