#!/usr/bin/env python3
"""Conformance audit: relative-Haar ordered-pair response vs declared G4 radial interface."""
import json
from pathlib import Path
R=Path(__file__).resolve().parents[2];g=json.loads((R/'research/aspect/contracts/theta-rh-g4-radial-interface.v1.json').read_text());v=json.loads((R/'research/aspect/contracts/theta-rh-interaction-net-state.v3.json').read_text());i=g['interface'];flat=json.dumps(i)
required={'ordered_pair_tensor_carrier':('completed_tensor' in flat or 'ordered pair' in flat),'one_leg_relative_Haar_J_pair':('J_pair' in flat or 'relative-Haar' in flat),'energy_multiplier_p':('energy multiplier' in flat or 'p^(1-2 Re(s))' in flat),'radial_R_plus_2E_response':('R+2E' in flat or 'R + 2E' in flat),'pair_to_joint_adjoint_law':('joint-column' in flat or 'joint column' in flat),'Evans_divisor_preservation':('Evans divisor' in flat or 'Xi-adic' in flat)}
base={'carrier_declared':g['status']=='declared','fold':i['sewing']['comparison_law']=='C_u F^2=W_u C_u','loading':i['arithmetic_loading']['finite_cutoff_declaration']=='U_X^G4=P_X L_rad','wronskian':'function_valued_wronskian_incidence' in i['response_preservation']}
assert all(base.values());assert not all(required.values())
contradiction={'amendment_status':g['status'],'v3_owner_readback_constructed':v['loading']['g4_owner_readback_constructed'],'v3_open_ids':[x['id'] for x in v['constructors'] if x['status']=='open']}
out={'schema':'marici.conjecture-replay.CR1-G4-pair-response-conformance.v1','outcome':'-+','base_interface':base,'pair_requirements':required,'missing':[k for k,x in required.items() if not x],'versioning_conflict':contradiction,'conclusion':'The radial amendment declares carrier/loading/fold coordinates, but does not declare the relative-Haar pair carrier, J_pair, R+2E response law, joint-adjoint comparison, or Evans-divisor preservation. Interaction-net v3 also still marks owner readback open. Pair-response conformance is therefore not established.','required_fix':'Publish a successor contract explicitly amending v3 and declaring the pair-response crossing laws; do not infer them from coordinate retention.','passed':True};p=R/'research/conjecture_replay/results/CR1_G4_pair_response_conformance.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'outcome':'-+','missing':out['missing'],'versioning_conflict':True}))
