#!/usr/bin/env python3
"""Exact terminal wall-tail scalar cancellation on the Xi divisor."""
import json
from fractions import Fraction as F
from pathlib import Path
from evidence_policy import write_result
R=Path(__file__).resolve().parents[2]
# At a nontrivial Xi zero: 2xi=1+s(s-1)H=0.
wall=F(1);tail=-F(1);total=wall+tail
checks={'wall_nonzero':wall!=0,'tail_nonzero':tail!=0,'scalar_zero':total==0,'absolute_cancellation_ratio':abs(total)/(abs(wall)+abs(tail))==0,'normalized_scalar_phase':wall*tail/(abs(wall)*abs(tail))==-1};assert all(checks.values())
out={'schema':'marici.conjecture-replay.CR1-terminal-mixed-cancellation.v1','passed':True,'claim_status':'proved','evidence':[{'class':'SYMBOLIC','claim':'At every nontrivial Xi zero, the exact bordered identity forces endpoint contribution 1 and tail contribution -1, giving zero scalar margin with both typed components nonzero.','checker':'research/conjecture_replay/check_CR1_terminal_mixed_cancellation.py'},{'class':'SOURCE_DERIVED','claim':'The radial gluing observation satisfies 2xi(s)=1+s(s-1)H(s) without division by xi.','source':'research/conjecture_replay/results/CR1_radial_gluing_to_bulk_H.json'}],'outcome':'terminal scalar readout has exact mixed cancellation on the Xi divisor','readout':'r_s(w,t)=r_wall,s(w)+r_tail,s(t)=1+s(s-1)H(s)=2xi(s)','at_nontrivial_zero':{'wall':'1','tail':'s(s-1)H(s)=-1','total':'0','scalar_relative_margin':'0','relative_phase':'-1'},'checks':checks,'typed_state':'The wall and tail modules remain orthogonal in the saturated Green metric and individually nonzero; only their terminal scalar images cancel.','kernel':'The scalar readout has a nontrivial kernel on the retained candidate. At each Xi zero the characteristic source section lies in that kernel while its function-valued/radial H response is nonzero.','jets':'At a zero of order m, derivatives through m-1 of the sum vanish, but derivatives of wall and tail components need not vanish separately; the jet cancellation remains terminal.','consequence':'The completed candidate can be faithful, closed-range, and uniformly Green-positive while the scalar readout margin is exactly zero at every Xi zero.','zero_confinement':'Nothing in this cancellation distinguishes Re(s)=1/2 from an off-line zero: the identity holds at every nontrivial Xi zero.','falsifier_for_energy_route':'Any claimed RH deduction from positive source Green energy alone must provide an additional theorem forbidding this typed nonzero wall-tail scalar cancellation off the seam.','remaining':'Find a pre-readout symmetry, self-adjoint pencil, or sign/phase constraint that permits cancellation only when Re(s)=1/2; current source identities do not supply one.','RH':False,'next':'test_whether_reciprocal_Real_covariance_constrains_the_wall_tail_relative_phase_off_the_seam_or_only_pairs_s_with_1-conjugate(s)'}
write_result(R/'research/conjecture_replay/results/CR1_terminal_mixed_cancellation.json',out);print(json.dumps({'passed':True,'wall':1,'tail':-1,'scalar_margin':0,'zero_confinement':False,'RH':False}))
