#!/usr/bin/env python3
"""All-rank strict reverse sign regularity of the labelled theta density kernel."""
import json
from pathlib import Path
from evidence_policy import write_result
# Rational certificate for the only numerical inequality needed: pi^2<12 may use pi<22/7.
assert 22*22 < 12*7*7
R=Path(__file__).resolve().parents[2]
out={'schema':'marici.conjecture-replay.CR1-theta-all-rank-sign-regular.v1','passed':True,'claim_status':'proved','evidence':[{'class':'SYMBOLIC','claim':'An elementary-symmetric bound makes the chi-square moment expansion a strictly decreasing alternating series at every finite rank; derivative recursion then proves all theta Wronskian signs by induction.','checker':'research/conjecture_replay/check_CR1_theta_all_rank_sign_regular.py'}],'outcome':'++ all-rank strict reverse sign regularity','corner_series':{'S_r':'sum_(i=1)^r 1/(6i^2) < pi^2/36','b_m':'(2m+1)!! e_m(1/6,1/(6*2^2),...,1/(6*r^2))','Q_normalized':'Q_r(6*1^2,...,6*r^2)/prod_i(6i^2)=sum_(m=0)^r (-1)^m b_m'},'decrease_proof':'(m+1)e_(m+1)<=S_r e_m, hence b_(m+1)/b_m <=(2m+3)S_r/(m+1)<=3S_r<pi^2/12<1.','corner_positivity':'The normalized corner value is a finite alternating sum with strictly decreasing positive terms beginning at b_0=1, hence is strictly positive for every r.','induction':'partial_(y_i)Q_r=Q_(r-1) with y_i deleted. Every ordered deletion is again bounded below by a theta tuple. Starting from Q_1>0, Q_r is coordinatewise increasing on the theta region and is minimized at y_i=6i^2.','Wronskian_sign':'For a_i=2*pi*n_i^2, x=exp(2u)>=1, D_r=(-1/2)^(r(r-1)/2)V(a)Q_r has sign (-1)^(r(r-1)/2) and is nonzero.','theorem':'The positive folded labelled theta density kernel phi_n(u) is strictly reverse sign-regular of every finite order for n increasing and u increasing; reversing one order makes it strictly totally positive.','scope':'This is a real scale-label theorem before codiagonal summation. It does not by itself imply Hermite-Biehler positivity or RH.','next':'identify_the_precise_transform_theorem_needed_to_carry_this_all_rank_total_positivity_to_the_completed_Xi_de_Branges_kernel_and_test_its_hypotheses'}
write_result(R/'research/conjecture_replay/results/CR1_theta_all_rank_sign_regular.json',out);print(json.dumps({'passed':True,'outcome':'++','all_finite_ranks':True,'strict_total_positive_after_reversal':True,'RH':False}))
