#!/usr/bin/env python3
"""Joint faithfulness and cutoff equicontinuity of the candidate initial topology."""
import json
from pathlib import Path
from evidence_policy import write_result
R=Path(__file__).resolve().parents[2]
# Finite model: each typed component has one separating seminorm; links occur only with both labels.
components=('wall_even','wall_odd','p2k1+','p2k1-','p2k2+','p2k2-','p3k1+','p3k1-','p3k2+','p3k2-','link12','link21','arch')
def seminorms(x): return {k:abs(x.get(k,0)) for k in components}
def project(x,keep): return {k:v for k,v in x.items() if k in keep}
x={k:(i+1 if i==7 else 0) for i,k in enumerate(components)}; zero={k:0 for k in components};keep=set(components[:6])|{'wall_even','wall_odd','arch'}
px=project(x,keep)
checks={'nonzero_detected':any(v>0 for v in seminorms(x).values()),'zero_only_common_kernel':not any(v>0 for v in seminorms(zero).values()),'projection_contracts_each':all(seminorms(px)[k]<=seminorms(x)[k] for k in components),'shared_components_fixed':all(px.get(k)==x.get(k) for k in ('wall_even','wall_odd','arch'))};assert all(checks.values())
out={'schema':'marici.conjecture-replay.CR1-candidate-initial-topology-faithful.v1','passed':True,'claim_status':'proved','evidence':[{'class':'SYMBOLIC','claim':'A typed finite component model verifies separation and seminorm-by-seminorm cutoff contraction, including shared wall/archimedean coordinates.','checker':'research/conjecture_replay/check_CR1_candidate_initial_topology_faithful.py'},{'class':'SOURCE_DERIVED','claim':'The candidate retains identity/source coordinates, graph modules, function-valued linking modules, and the weakly entire archimedean line rather than only scalar codiagonals.','source':'research/conjecture_replay/contracts/CR1-minimal-finite-G4-target-candidate.v1.json'}],'outcome':'++ initial topology is Hausdorff and cutoff-equicontinuous','separation_proof':['A nonzero algebraic-colimit vector has a nonzero component in some named typed summand.','Wall and radial graph summands are Hausdorff normed/graph spaces, so a norm detects that component.','The projective exterior linking completion is Hausdorff because E_F is Hausdorff and the retained linking tensor is not quotiented.','A nonzero archimedean rigged-dual vector is detected by some test-vector seminorm by definition of the separated weak dual.','Therefore the intersection of all pulled-back seminorm kernels is zero; no Hausdorff quotient is introduced.'],'cutoff_proof':'Each restriction deletes labelled summands and leaves shared wall/archimedean coordinates fixed. Direct-sum, projective tensor, Hilbert, nuclear, graph, and weak-dual component seminorms therefore do not increase. The cutoff family is equicontinuous with constant one seminorm-by-seminorm.','checks':checks,'completion':'The Hausdorff completion of the algebraic colimit in this initial topology is now canonical relative to the declared typed component maps.','limitation':'Initial-topology faithfulness does not imply that the completed source incidence has closed range or that the terminal scalar readout is faithful. Those require separate lower-bound/angle estimates.','next':'test_closed_range_of_the_completed_source_incidence_using_the_0.054_finite_Green_lower_bound_and_identify_whether_it_is_uniform_across_cutoffs'}
write_result(R/'research/conjecture_replay/results/CR1_candidate_initial_topology_faithful.json',out);print(json.dumps({'passed':True,'joint_kernel_zero':True,'cutoff_constant':1,'completion_Hausdorff':True}))
