#!/usr/bin/env python3
"""Completion model and cutoff bounds for the minimal G4 candidates."""
import json,math
from pathlib import Path
from evidence_policy import write_result
R=Path(__file__).resolve().parents[2]
# Exact finite tests use rational positive coordinate weights; the proof is weight-independent.
w={2:3,3:5,5:7}; x={2:2,3:-1,5:4}
def l1(v,P): return sum(w[p]*abs(v.get(p,0)) for p in P)
def l2(v,P): return math.sqrt(sum(w[p]*abs(v.get(p,0))**2 for p in P))
def proj(v,P): return {p:v[p] for p in P if p in v}
P=(2,3);Q=(2,3,5);px=proj(x,P)
checks={'primitive_l1_projection_contractive':l1(px,P)<=l1(x,Q),'square_l2_projection_contractive':l2(px,P)<=l2(x,Q),'inclusion_isometric_l1':l1(px,Q)==l1(px,P),'inclusion_isometric_l2':l2(px,Q)==l2(px,P),'norm_one_witness':l1({2:1},P)==l1({2:1},Q),'weights_positive':all(a>0 for a in w.values())};assert all(checks.values())
out={'schema':'marici.conjecture-replay.CR1-candidate-weighted-completion.v1','passed':True,'claim_status':'proved','evidence':[{'class':'SYMBOLIC','claim':'Coordinate inclusions and projections are isometric/contractive for arbitrary positive weighted l1 and l2 direct-sum norms; exact sample checks exercise both rungs.','checker':'research/conjecture_replay/check_CR1_candidate_weighted_completion.py'},{'class':'SOURCE_DERIVED','claim':'The source pair completion is primitive-projective, square-Hilbert-Schmidt, connected-nuclear, with function-valued rapid radial responses retained.','source':'research/conjecture_replay/results/CR1_source_four_presentation_pair_freeze.json'},{'class':'DECLARED','claim':'The radial loading converges in the declared Green graph and rapid-radial seminorms and is cutoff natural.','source':'research/aspect/contracts/theta-rh-g4-radial-interface.v1.json'}],'outcome':'++ candidate completion topology and uniformly bounded cutoff system','completion':{'primitive':'weighted l1/projective direct sum of labelled radial graph modules','square':'weighted l2 Hilbert direct sum; loading is Hilbert-Schmidt','connected':'weighted l1 operator-ideal completion for nuclear returns','linking':'completed projective exterior tensor of the corresponding labelled graph modules','wall_archimedean':'one shared finite wall plane and one shared rigged archimedean line, not repeated per cutoff'},'weights':'Any fixed positive source-compatible coordinate weights for which the already-proved loading estimates converge; changing to an equivalent weight family gives an equivalent candidate, not a target identity.','bonding':'Extension by zero is isometric and coordinate restriction is contractive with norm one on every nonzero rung; the same holds seminorm-by-seminorm on the projective family.','checks':checks,'completion_map':'The algebraic finite-support colimit embeds densely by definition into each declared completion rung.','operators':'Cutoff-diagonal Real, reciprocal, Fourier-orbit, graph metric, and parameter-jet operators extend when their established rung bounds are uniform; no scalar response completion is used.','proved_scope':'Existence of a coherent completed candidate from the source-compatible direct-sum topology and norm-one cutoff maps.','not_proved':['uniqueness among inequivalent global weight systems','uniform coercivity of the infinite primitive loading','closed range of the full arithmetic-analytic pushout','zero confinement or RH'],'remaining':'Compare admissible weight systems via explicit equivalence constants and prove the full source loading lands densely/with the required closed range in this completion.','next':'audit_weight_choice_dependence_and_identify_which_conformance_laws_are_topological_invariants'}
write_result(R/'research/conjecture_replay/results/CR1_candidate_weighted_completion.json',out);print(json.dumps({'passed':True,'projection_norm':1,'inclusion_norm':1,'dense_finite_support':True,'RH':False}))
