#!/usr/bin/env python3
"""Specify the exact G4-to-Xi comparison arrow and audit constructibility."""
import json
from pathlib import Path
from evidence_policy import write_result
R=Path(__file__).resolve().parents[2]
v=json.loads((R/'research/aspect/contracts/theta-rh-interaction-net-state.v3.json').read_text());a=json.loads((R/'research/aspect/contracts/theta-rh-g4-radial-interface.v1.json').read_text())
cs={x['id']:x for x in v['constructors']};required_open=['g4_radial_carrier_and_loading_readback','g4_half_turn_sewing_readback'];assert all(cs[k]['status']=='open' and cs[k]['authority']=='g4_owner_declaration' for k in required_open);assert v['loading']['g4_owner_readback_constructed'] is False
out={'schema':'marici.conjecture-replay.CR1-minimal-G4-comparison-arrow.v1','passed':True,'claim_status':'proved','evidence':[{'class':'SYMBOLIC','claim':'The contract constructor table and loading readback flag were checked for the exact prerequisites of the comparison arrow.','checker':'research/conjecture_replay/check_CR1_minimal_G4_comparison_arrow.py'},{'class':'DECLARED','claim':'Both required G4 readback constructors are explicitly open and owner-controlled.','source':'research/aspect/contracts/theta-rh-interaction-net-state.v3.json'}],'outcome':'authority-blocked','arrow':{'symbol':'T_s','domain':'Dom(G4_joint_max,s) on the retained labelled graph','codomain':'R_s subset C^2_endpoint direct_sum C_source direct_sum E_exp_prime','components':['two strict endpoint coordinates x','source amplitude c','radial Poisson history gamma_rad(s-1/2)c'],'required_laws':{'domain':'T_s maps the declared common graph domain continuously into the relation topology','six_features':'J_or T_s preserves (-rho0,E+,W+;+rho0,E-,W-) labelwise','codiagonal':'D_G4 = B_theta^times gamma_rad after T_s','metric':'T_s transports the G4 Green form to endpoint J direct_sum radial graph metric without equating graph and ambient adjoints','operator':'T_s G4_joint(s)=Q_s T_s','sewing':'T_(1-s) R_G4 = R_Xi T_s','completion':'T_s and its inverse on the source-generated range are continuous uniformly on compact spectral sets'}},'acceptance':'A bijective T_s satisfying these laws identifies kernels, local cokernel modules, and all Xi multiplicity jets with the G4 boundary equation.','audit':{'available':['common retained graph domain','four-port trace','all-jet Laplace readout','radial fold','Real graph/ambient return squares','forward Euler-to-radial loading'],'missing':required_open+['explicit joint-adjoint operator equation/intertwiner'],'constructible_now':False},'conclusion':'No repository-local proof may instantiate T_s without manufacturing owner readback. The blocker is explicit authority plus missing operator data, not an unresolved scalar calculation.','next':'advance_the_source_derived_downstream_Evans_Green_chain_without_claiming_G4_identity'}
write_result(R/'research/conjecture_replay/results/CR1_minimal_G4_comparison_arrow.json',out);print(json.dumps({'passed':True,'outcome':'authority-blocked','required_laws':6,'owner_open':2,'constructible_now':False}))
