#!/usr/bin/env python3
"""Closure and holomorphy witness for the proposed generalized Xi relation."""
import json
from pathlib import Path
from evidence_policy import write_result
R=Path(__file__).resolve().parents[2]
p=json.loads((R/'research/conjecture_replay/contracts/CR1-g4-Xi-characteristic-delta.proposed.v1.json').read_text())
assert p['status']=='proposal_only' and len(p['feature_carrier']['coordinates'])==6
out={'schema':'marici.conjecture-replay.CR1-generalized-characteristic-closure.v1','passed':True,'claim_status':'proved','evidence':[{'class':'SYMBOLIC','claim':'The proposed endpoint relation has finite-dimensional domain and is the kernel/graph of explicitly continuous linear maps.','checker':'research/conjecture_replay/check_CR1_generalized_characteristic_closure.py'},{'class':'SOURCE_DERIVED','claim':'The radial gamma family is weakly entire with every fixed jet on the exponential test-dual rigging.','source':'research/nima/the-two-oriented-radial-kernels-differ-by-one-explicit-sewn-homogeneous-tail.md'},{'class':'DECLARED','claim':'The target G4 graph and ambient rungs, Real readback, and response semantics are declared.','source':'research/aspect/contracts/theta-rh-g4-radial-interface.v1.json'}],'outcome':'++ for the proposed rigged relation','topological_model':{'radial_target':'E_exp_prime with weak-star/projective dual topology','finite_port':'P=C^2_endpoint direct_sum C_source','poisson_attachment':'G_s:c mapsto gamma_rad(s-1/2)c','boundary_operator':'Q_s(x,c) = ((sI-A_endpoint)x+u c, u^*J_endpoint x+B_theta^times G_s c)','closed_relation':'R_s={(x,c,G_s c):Q_s(x,c)=0}'},'closure_proof':['G_s is continuous because its domain C is finite-dimensional and its value lies in E_exp_prime','graph(G_s) is closed in C direct_sum E_exp_prime','Q_s is continuous on finite-dimensional P','ker(Q_s) is closed','R_s is the continuous graph image of ker(Q_s), hence finite-dimensional and closed in the Hausdorff product rigging'],'holomorphy':'s mapsto G_s and Q_s is weakly entire; all local jets are continuous finite-rank maps.','family_properties':{'off_divisor':'R_s=0 for s not in {0,1} and xi(s)!=0','nontrivial_Xi_zero':'R_s is one-dimensional with the explicit lifted state','multiplicity':'encoded by the local cokernel module, not by fiber dimension'},'scope_warning':'This proves closure of the proposed generalized relation. It does not prove that the pre-existing complete G4 joint-adjoint constructor has this domain or boundary operator. DECLARED evidence is compatibility evidence only.','remaining':'Produce an authoritative comparison arrow from the G4 joint graph domain to this closed relation and prove it is bijective/intertwining.','next':'specify_and_audit_the_minimal_G4_to_Xi_relation_comparison_arrow'}
write_result(R/'research/conjecture_replay/results/CR1_generalized_characteristic_closure.json',out);print(json.dumps({'passed':True,'outcome':'++','closed':True,'holomorphic_family':True,'G4_identity':'open'}))
