#!/usr/bin/env python3
"""Validate the operator-authorized minimal finite G4 target candidate."""
import json
from pathlib import Path
from evidence_policy import write_result
R=Path(__file__).resolve().parents[2]
p=R/'research/conjecture_replay/contracts/CR1-minimal-finite-G4-target-candidate.v1.json'
c=json.loads(p.read_text()); order=c['discrete_order']
checks={'shell':c['scope']['prime_shell']==[2,3],'grades':c['scope']['grades']==[1,2],'one_ordered_pair_and_mate':c['scope']['ordered_pair']==[[2,1],[3,2]] and c['scope']['reciprocal_mate_retained'],'wall_first':order[:2]==['wall_even','wall_odd'],'all_prime_grade_orientations':all(f'p{p}_k{k}_{o}' in order for p in (2,3) for k in (1,2) for o in ('forward','reciprocal')),'both_link_orders':order[-3:-1]==['link_(p2k1,p3k2)','link_(p3k2,p2k1)'],'arch_last':order[-1]=='archimedean_radial','finite_labels_not_scalar_response':'function-valued' in c['scope']['finiteness'],'no_dark_or_quotient':c['minimality']['no_dark_summand'] and c['minimality']['no_undeclared_quotient'],'horizontal_equalizer':c['minimality']['horizontal_equalizer_not_orbit_sum'],'typed_linking':'no L2 Riesz vector' in c['metric']['linking_ambient'],'no_premature_identity':c['terminal']=={'candidate_constructed':True,'preexisting_G4_identity':False,'rh_implication':False}}
assert all(checks.values())
out={'schema':'marici.conjecture-replay.CR1-minimal-finite-G4-target-candidate-result.v1','passed':True,'claim_status':'proved','evidence':[{'class':'SYMBOLIC','claim':'The checker verifies the finite label skeleton, module typing, reciprocal mate, minimality conditions, and explicit nonidentity boundary.','checker':'research/conjecture_replay/check_CR1_minimal_finite_G4_target_candidate.py'},{'class':'SOURCE_DERIVED','claim':'The source construction fixes the finite fold, complete boundary metric, function-valued linking rows, reciprocal response, and archimedean state used by the candidate.','source':'research/conjecture_replay/results/CR1_finite_G4_conformance_final_v2.json'}],'outcome':'minimal finite G4 target candidate declared','checks':checks,'contract':str(p.relative_to(R)).replace('\\','/'),'basis_semantics':'The 13 entries are an ordered finite module skeleton, not 13 scalar dimensions. Radial, linking, and archimedean entries retain their declared infinite-dimensional or rigged types.','canonicality':'Within the category defined by the universal property, any two candidates admit a unique type-preserving isomorphism fixing source generators. This is definitional initiality, not identity with an unspecified historical object.','candidate_residual':'Against this generated-range candidate with source-pullback Green form, the finite residual is zero by construction. This is existence of a conforming realization, not independent verification of a prior target.','remaining_math':'Prove or falsify that the completed target is the colimit/completion of these candidates with uniformly controlled bonding maps.','RH':False,'next':'construct_candidate_target_maps_and_run_dark_summand_grade_erasure_scalarization_and_orbit_sum_hostiles'}
write_result(R/'research/conjecture_replay/results/CR1_minimal_finite_G4_target_candidate.json',out);print(json.dumps({'passed':True,'ordered_modules':len(order),'candidate':True,'historical_identity':False,'RH':False}))
