#!/usr/bin/env python3
"""Separate existential specialization arrows from their internal evidence gates."""
import json,sys
from dataclasses import asdict
from pathlib import Path
R=Path(__file__).resolve().parents[2];sys.path.insert(0,str(R/'research/conjecture_net'));from event_log import *
prior=json.loads((R/'research/conjecture_replay/results/PS1_existential_physical_specialization.json').read_text());q=prior['projection'];p=Projection(q['graph_digest'],q['state_id'],frozenset(q['interfaces']),frozenset(q['facts']),q['sunk_cost'],frozenset(tuple(x) for x in q['resolved_actions']),tuple(q['event_ids']))
old=tuple(x['name'] for x in prior['contract']['active_children']);branches=('PS1A_alternate_signed_minor_specialization','PS1B_nearby_cycle_specialization','PS1C_modified_operation_specialization');gates=('PS1A0_axis_incidence','PS1B0_current_specialization','PS1C0_source_admissibility')
contract={'existential_parent':prior['contract']['question'],'terminal_branches':[{ 'name':b,'domain':'algebraic_relative_class','codomain':'physical_BD_class','required_success':'*+'} for b in branches],'internal_gates':[{'name':g,'supports':b} for g,b in zip(gates,branches)],'aggregation':'only terminal branch outcomes participate; microgate outcomes update their owning branch but are never aggregated as specialization arrows','first_gate':'PS1C0_source_admissibility'}
g1=digest({'parent':p.graph_digest,'PS1_typed_repair':contract});top=TopologyEvent(p.graph_digest,'split',branches+gates,old,tuple((o,(b,g)) for o,b,g in zip(old,branches,gates)),tuple(f'{g} -> {b}' for g,b in zip(gates,branches)),g1,'the first PS1 refinement incorrectly aggregated microgates with non-physical codomains as existential branches',(prior['refinement_event']['event_id'],),'2026-09-11T00:01:30Z');log=EventLog.resume(p).append(top);pct={'nonterminal_gates_in_existential_aggregation':-100.,'typed_terminal_branch_count':None,'active_specialization_branch_count':0.,'minimum_next_gate_cost':0.};out={'schema':'marici.conjecture-replay.PS1-branch-gate-typing-correction.v1','event':{'event_id':top.event_id,**asdict(top)},'projection':asdict(log.project()),'corrected_contract':contract,'metric_projection':{'base':'immediately previous PS1 refinement','percent_change_from_previous_base':pct,'zero_base_note':'typed terminal branches rose from zero, so percentage is undefined','absolute_values_omitted_by_policy':True},'next_recommendation':'PS1C0_source_admissibility','passed':True};(R/'research/conjecture_replay/results/PS1_branch_gate_typing_correction.json').write_text(json.dumps(out,indent=2,default=list)+'\n');print(json.dumps({'passed':True,'removed_mistyped_microbranches':len(old),'terminal_branches':len(branches),'next':out['next_recommendation'],'percent_delta':pct}))
