#!/usr/bin/env python3
"""Detect and close the duplicate v10 purity gate introduced by local refinement."""
import json
from pathlib import Path
R=Path(__file__).resolve().parents[2];old=json.loads((R/'research/voevodsky/results/CR1A_v10_PC_purity_executability.json').read_text());new=json.loads((R/'research/voevodsky/results/CR1_target_unlocalized_Koszul_Cech_comparison.json').read_text())
proposed=new['refinement'][0]
checks={'old_action':old['prospective_action']=='CR1A_v10_occurrence_loaded_PC_purity','new_same_semantics':proposed=='CR1PK1a2a1a1a2a_construct_v10_occurrence_loaded_PC_purity','old_resolved':old['resolution']=='--','same_available_packet':all(any(key in x for x in old['available']) for key in ['residue','Koszul-Cech','Tor0']),'same_missing_map':any('actual ringed-PC' in x for x in old['missing']) and 'purity maps are absent' in new['obstruction']}
assert all(checks.values()),checks
out={'schema':'marici.conjecture-replay.CR1-v10-purity-deduplication.v1','proposed_action':proposed,'canonical_action':old['prospective_action'],'relationship':'semantic alias; both ask for the geometric v10 occurrence-loaded purity map into the actual ringed-PC costalk','inherited_outcome':'--','evidence':'research/voevodsky/results/CR1A_v10_PC_purity_executability.json','cycle':'Following the proposed refinement would re-enter the already explored CR1A -> geometric corner restriction -> marked extraordinary Q-leg branch.','disposition':'remove duplicate from frontier; retain its two unsatisfied outputs as requirements rather than opening a new action','retained_requirements':['geometric_v10_corner_restriction','actual_ringed_PC_extraordinary_costalk_identification'],'next_independent':'CR1PK1a3_construct_x1_ringed_PC_Gysin_span','metric_delta':{'formal_coherence_survivors_percent':0.0,'geometrically_certified_complete_paths_percent':0.0,'active_duplicate_actions':-1,'deduplicated_cycles':1,'new_typed_interfaces':0},'checks':checks,'passed':True};p=R/'research/conjecture_replay/results/CR1_v10_purity_deduplication.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'alias_outcome':'--','duplicate_actions_removed':1,'survivors':32,'next':out['next_independent']}))
