#!/usr/bin/env python3
"""Freeze the strongest evidence-typed Xi boundary characteristic theorem."""
import json
from pathlib import Path
from evidence_policy import write_result
R=Path(__file__).resolve().parents[2]
req=['CR1_endpoint_Pontryagin_colligation.json','CR1_theta_bulk_as_radial_boundary_response.json','CR1_bordered_Xi_Krein_symmetry.json','CR1_generalized_rigged_boundary_characteristic.json','CR1_Xi_characteristic_local_cone.json','CR1_generalized_characteristic_closure.json','CR1_weighted_relative_Riesz_core.json','CR1_weighted_Riesz_grade12_mate.json','CR1_weighted_Riesz_reciprocal_return.json','CR1_Xi_halfturn_vs_G4_quarterturn.json']
loaded={n:json.loads((R/'research/conjecture_replay/results'/n).read_text()) for n in req};assert all(x.get('passed') is True for x in loaded.values());assert loaded['CR1_Xi_characteristic_local_cone.json']['claim_status']=='proved'
out={'schema':'marici.conjecture-replay.CR1-Xi-halfturn-characteristic-freeze.v1','passed':True,'claim_status':'proved','evidence':[{'class':'SYMBOLIC','claim':'The endpoint Pontryagin realization, bordered Krein symmetry, Schur equivalence, local cone contraction, and multiplicity statements are exact executable algebra.','checker':'research/conjecture_replay/check_CR1_Xi_characteristic_local_cone.py'},{'class':'SOURCE_DERIVED','claim':'The theta bulk is the bilateral radial Laplace response and has a self-adjoint exponential dilation.','source':'research/grothendieck/the-theta-bulk-has-a-conservative-dilation-realization-but-conservation-does-not-confine-zeros.md'},{'class':'SYMBOLIC','claim':'Weighted-relative Riesz columns provide literal graph-adjoint sampling and the reciprocal half-turn mate square on retained prime/grade labels.','checker':'research/conjecture_replay/check_CR1_weighted_Riesz_grade12_mate.py'},{'class':'DECLARED','claim':'The G4 radial contract declares the matching fold, Green wall form, graph Real readback, response family, and F^2-to-radial comparison.','source':'research/aspect/contracts/theta-rh-g4-radial-interface.v1.json'}],'outcome':'FROZEN ++ at generalized half-turn boundary-characteristic scope','theorem':{'characteristic':'M_s=[[s,0,1],[0,s-1,1],[1,-1,H(s)]]','metric':'K=diag(1,-1,1)','symmetry':'K M_s=M_s^T K and reciprocal left-right covariance under s mapsto 1-s','determinant':'det M_s=2 xi(s)','state_lift':'At every nontrivial Xi zero, (-1/s,-1/(s-1),1) together with gamma_rad(s-1/2) is a nonzero boundary state','multiplicity':'The local cokernel length equals ord_s xi and every multiplicity jet is preserved','closure':'The parameterized relation is closed in the retained rigged relation topology','sampling':'Primitive/square literal arithmetic sampling is the weighted graph adjoint of Riesz evaluation columns, with source-derived -1/2 Wronskian normalization','sewing':'Reciprocal half-turn covariance is constructed and sufficient for the Xi characteristic'},'classification':'A generalized rigged/Krein boundary characteristic and conservative analytic colligation; not an ordinary Hilbert boundary-triplet Weyl function.','explicit_nonclaims':['not the complete four-presentation G4 carrier','not an owner readback of the G4 joint adjoint','not a positive-real Xi impedance','not a zero-confinement theorem','not an RH proof'],'remaining_independent':['G4 owner adoption of weighted_riesz_to_kernel_response','full Fourier quarter-turn F on every response stratum','source-derived mechanism excluding off-seam zeros'],'next':'pursue_zero_confinement_only_from_pre_codiagonal_labelled_theta_structure_not_from_conservation_alone'}
write_result(R/'research/conjecture_replay/results/CR1_Xi_halfturn_characteristic_freeze.json',out);print(json.dumps({'passed':True,'outcome':'FROZEN ++','Xi_zeros_boundary_states':True,'multiplicity':True,'ordinary_Weyl':False,'RH':False}))
