#!/usr/bin/env python3
"""Freeze the evaluable source-derived candidate for U_p^(theta->rad)."""
import json
from pathlib import Path
from evidence_policy import write_result
R=Path(__file__).resolve().parents[2];c=json.loads((R/'research/conjecture_replay/contracts/CR1-weighted-Riesz-U-theta-rad.candidate.v1.json').read_text());assert c['status']=='source_derived_candidate_not_owner_readback' and len(c['laws'])==8
prereq=['CR1_weighted_relative_Riesz_core.json','CR1_weighted_Riesz_grade12_mate.json','CR1_weighted_Riesz_connected_tail.json','CR1_Prel_Gaussian_response_cocycle.json','CR1_weighted_Riesz_reciprocal_return.json','CR1_weighted_Riesz_vs_Lrad.json'];assert all(json.loads((R/'research/conjecture_replay/results'/p).read_text()).get('passed') for p in prereq)
out={'schema':'marici.conjecture-replay.CR1-weighted-Riesz-U-candidate-freeze.v1','passed':True,'claim_status':'proved','evidence':[{'class':'SYMBOLIC','claim':'All prerequisite source-column, transpose, grade-completion, response-cocycle, reciprocal, and coefficient checks were loaded and passed.','checker':'research/conjecture_replay/freeze_CR1_weighted_Riesz_U_candidate.py'},{'class':'DECLARED','claim':'The target interface requires an abstract primewise U_p^(theta->rad) with matching loading coefficient and response laws.','source':'research/aspect/contracts/theta-rh-g4-radial-interface.v1.json'}],'outcome':'FROZEN source-derived candidate','candidate':c,'evaluable_rule':'For each (p,k), solve the weighted Riesz variational equation <m_t,f>_rel=f(t), t=k log p; emit m_t and P_rel m_t=U_t f0 with its K/H_K/J_K responses.','verified_scope':['all prime-power grades','literal graph-adjoint theta sampling','exact declared c_p after grade summation','primitive projective-dual completion','square/connected Hilbert completion','reciprocal half-turn and Real covariance','translation cocycle and every spectral jet','closed retained-source graph'],'authority_status':'This is now an evaluable implementation candidate for U_p^(theta->rad), but the owning G4 surface has not identified its abstract U_p with this rule.','scientific_status':'No scalar fitting remains in this arrow. Rejection or adoption can be decided by comparing the owner implementation on one labelled basis family and its four traces.','next':'owner_readback_or_independent_G4_basis_evaluation_of_U_p_theta_to_rad'}
write_result(R/'research/conjecture_replay/results/CR1_weighted_Riesz_U_candidate_freeze.json',out);print(json.dumps({'passed':True,'outcome':'FROZEN candidate','evaluable':True,'owner_readback':False,'laws':8}))
