#!/usr/bin/env python3
import json,sys
from pathlib import Path
R=Path(__file__).resolve().parents[2];sys.path.insert(0,str(R/'research/conjecture_net'))
from coherence_pyramid import *
from composite_arrow_tests import ArrowPath
# G is split into algebraic gluing and the previously omitted physical-specialization arrow S.
arrows=(TypedArrow('R','problem','exact_packet',8),TypedArrow('D','exact_packet','physical_BD_class',3),TypedArrow('X','exact_packet','exchange_packet',.2),TypedArrow('B','exchange_packet','boundary_packet',2),TypedArrow('G_alg','boundary_packet','algebraic_relative_class',.2),TypedArrow('S_phys','algebraic_relative_class','physical_BD_class',1))
paths=(ArrowPath('direct',('R','D')),ArrowPath('factored',('R','X','B','G_alg','S_phys')))
observed=(('R',frozenset({'++'})),('X',frozenset({'+-'})),('B',frozenset({'-+'})),('G_alg',frozenset({'++'})),('S_phys',frozenset({'+-'})))
coherent=CoherencePyramid(arrows,paths,(CoherenceLayer('observed_split_arrows',arrow_domains=observed),CoherenceLayer('outer_commuting_face',equal_paths=(('direct','factored'),))),).run();assert coherent['survivor_count']==1
solution=CoherencePyramid(arrows,paths,(CoherenceLayer('observed_split_arrows',arrow_domains=observed),CoherenceLayer('physical_solution',equal_paths=(('direct','factored'),),patterns=(PathPattern('direct','*+'),))),).run();assert solution['survivor_count']==0
out={'schema':'marici.conjecture-replay.degree15-split-codomain-coherence-pyramid.v1','repair':{'old_arrow':'G: boundary_packet -> physical_BD_class','new_arrows':['G_alg: boundary_packet -> algebraic_relative_class','S_phys: algebraic_relative_class -> physical_BD_class'],'observed_split_outcomes':dict((a,next(iter(v))) for a,v in observed)},'coherent_projection':coherent,'solution_projection':solution,'forced_direct_arrow':'D=+- in the unique coherent assignment','conclusion':'After correcting the codomain alias, the diagram is coherent but its terminal physical polarity is negative. Adding the necessary *+ solution condition makes the survivor set empty. The degree-15 packet proves algebraic lowering, not physical BD descent through this channel.','metric_projection':{'base':'previous invalid one-survivor pyramid before falsification','percent_change_from_previous_base':{'codomain_alias_count':-100.0,'implicit_specialization_arrows':-100.0,'physical_interface_deficit_on_this_branch':-100.0,'scientific_solution_survivors':-100.0},'interpretation':'The interface deficit drops because S_phys is now explicitly resolved negatively, not because physical descent succeeded.','absolute_values_omitted_by_policy':True},'next':'Return to alternative physical specialization channels or use the degree-15 identity only as an algebraic comparison theorem.','passed':True};p=R/'research/conjecture_replay/results/degree15_split_codomains_pyramid.json';p.write_text(json.dumps(out,indent=2,default=list)+'\n');print(json.dumps({'passed':True,'coherent_survivors':1,'solution_survivors':0,'forced_D':'+-','percent_delta':out['metric_projection']['percent_change_from_previous_base']}))
