#!/usr/bin/env python3
"""Refine the ringed endpoint q-counit using the cross-sheet interior clue."""
import json,subprocess,tempfile
from pathlib import Path
R=Path(__file__).resolve().parents[2]
def run(n):
 s=R/'research/voevodsky'/n;e=Path(tempfile.gettempdir())/(s.stem+'.exe');subprocess.run(['rustc','--edition=2021','-D','warnings','-O',str(s),'-o',str(e)],check=True);return json.loads(subprocess.check_output([str(e)],text=True))
e=run('check_equivariant_face_trace_evenness_no_go.rs');h=run('check_cross_sheet_hexagon_short_facet_filler.rs')
checks={'ordinary_even':e['ordinary_smith_factors']==[2],'unit_unreachable':not e['primitive_value_one_reachable'],'enlarged_primitive':e['minimal_enlarged_row']==[2,-6,1] and e['enlarged_smith_factors']==[1],'edges_faces':e['cross_polytope_edges_constructed_finitely']==6 and e['cross_polytope_faces_constructed_finitely']==8,'boundary_filler_unique':h['minimum_solutions']==1 and h['primitive'],'interior_missing':not e['relative_interior_to_literal_Q_constructed'],'boundary_Q_zero':h['literal_Q_projection']==0}
assert all(checks.values()),checks
out={'schema':'marici.conjecture-replay.CR1-endpoint-q-counit-relative-interior-refinement.v1','parent_gate':'ringed support correspondence implementing endpoint q-counit','resolution':'refined','negative_result':'every ordinary equivariant face trace is 2a-6b and cannot reach unit value','new_action':'CR1QCOUN1_construct_reflection_odd_relative_interior_Q_counit','available_boundary':{'cross_sheet_edges':6,'triangular_faces':8,'unique_primitive_short_facet_hexagon_filler':True,'literal_Q_projection':0},'required_map':'support-typed extraordinary proper/log-excess counit from the cross-polytope relative fundamental class to literal generic Q top','normalization_test':'top trace row must enlarge from [2,-6] to [2,-6,1], whose Smith factor is 1','coherence_requirements':['six edge maps','eight facet Beck-Chevalley cells','endpoint framing','reflection-odd orientation'],'produces':['primitive_odd_relative_interior_Q_counit'],'metric_delta':{'active_q_counit_paths':1,'new_typed_interfaces':1,'ordinary_trace_candidates_eliminated_percent':100.0,'primitive_boundary_fillers':1},'next':'CR1QCOUN1_construct_reflection_odd_relative_interior_Q_counit','checks':checks,'passed':True};p=R/'research/conjecture_replay/results/CR1_endpoint_q_counit_relative_interior_refinement.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'passed':True,'ordinary_row':[2,-6],'enlarged_row':[2,-6,1],'active_q_counit_paths':1,'next':out['next']}))
