{-# OPTIONS --safe --cubical --guardedness #-}
module BoundaryPfaffianResidualRankResetInstance where

open import Cubical.Foundations.Prelude
open import Cubical.Data.Sigma using (_×_; _,_)
open import Cubical.Algebra.CommRing
open import Cubical.Tactics.CommRingSolver
open import BoundaryPfaffianRankReset
open import BoundaryPfaffianResidualFold

module Instance {ℓ} (CR : CommRing ℓ) where
  module RF = ResidualFold CR
  open RF
  open CommRingStr (snd CR)

  residualRankReset : RankResetSystem {ℓ}
  residualRankReset = record
    { Primitive = OddMetric
    ; Defect = OddMetric
    ; Certificate = ResidualSummary
    ; Residual = ResidualSummary
    ; NextPrimitive = ResidualSummary
    ; expose = λ X → X
    ; reconcile = λ X → summarize X , summarize X
    ; retype = λ X → X
    ; minimize = λ X → summarize X , summarize X
    ; rankResetSquare = λ X → refl
    ; Incoming = Carrier
    ; Outgoing = Carrier
    ; residualIncoming = inn
    ; residualOutgoing = out
    ; nextIncoming = inn
    ; nextOutgoing = out
    ; incomingRetyped = λ X → refl
    ; outgoingRetyped = λ X → refl
    }

  polarizedCertificateReversal : (X : OddMetric) →
    fst (reconcile residualRankReset (reverseMetric X)) ≡
    reverseSummary (fst (reconcile residualRankReset X))
  polarizedCertificateReversal = summarizeReversal

  polarizedResidualReversal : (X : OddMetric) →
    snd (reconcile residualRankReset (reverseMetric X)) ≡
    reverseSummary (snd (reconcile residualRankReset X))
  polarizedResidualReversal = summarizeReversal

  -- A future sewing context is a separating gap and a right residual block.
  SewingContext = Carrier × ResidualSummary

  sewingValidity : ContextualValidity residualRankReset
  sewingValidity = record
    { Context = SewingContext
    ; Observation = Carrier
    ; observePrimitive = λ where (gap , Y) X → sew (summarize X) gap Y
    ; observeMinimal = λ where (gap , Y) (_ , X) → sew X gap Y
    ; behaviorPreserved = λ c X → refl
    }

  -- Instantiation of the abstract commuting square for every sewing context.
  residualBehaviorPreserved : (c : SewingContext) (X : OddMetric) →
    observePrimitive sewingValidity c X ≡
    observeMinimal sewingValidity c
      ( fst (reconcile residualRankReset (expose residualRankReset X))
      , retype residualRankReset
          (snd (reconcile residualRankReset (expose residualRankReset X))) )
  residualBehaviorPreserved =
    reconciledBehavior residualRankReset sewingValidity

  -- Arbitrary finite programs generated by pair extension and reversal,
  -- terminated by an ordered sewing observation.
  data ContextProgram : Type ℓ where
    observeWith : Carrier → ResidualSummary → ContextProgram
    extendWith : Carrier → Carrier → ContextProgram → ContextProgram
    reverseThen : ContextProgram → ContextProgram

  runContext : ContextProgram → ResidualSummary → Carrier
  runContext (observeWith gap Y) X = sew X gap Y
  runContext (extendWith e o C) X = runContext C (pairAction X e o)
  runContext (reverseThen C) X = runContext C (reverseSummary X)

  -- Every context program normalizes to one weighted polarized readout.
  data PolarizedReadout : Type ℓ where
    readOut : Carrier → PolarizedReadout
    readIn : Carrier → PolarizedReadout

  evaluateReadout : PolarizedReadout → ResidualSummary → Carrier
  evaluateReadout (readOut weight) X = weight · out X
  evaluateReadout (readIn weight) X = weight · inn X

  extendReadout : Carrier → Carrier → PolarizedReadout → PolarizedReadout
  extendReadout e o (readOut weight) = readOut (weight · e)
  extendReadout e o (readIn weight) = readIn (weight · o)

  reverseReadout : PolarizedReadout → PolarizedReadout
  reverseReadout (readOut weight) = readIn weight
  reverseReadout (readIn weight) = readOut weight

  compileContext : ContextProgram → PolarizedReadout
  compileContext (observeWith gap Y) = readOut (gap · inn Y)
  compileContext (extendWith e o C) = extendReadout e o (compileContext C)
  compileContext (reverseThen C) = reverseReadout (compileContext C)

  compileExtendCorrect :
    (e o : Carrier) (P : PolarizedReadout) (X : ResidualSummary) →
    evaluateReadout P (pairAction X e o) ≡
    evaluateReadout (extendReadout e o P) X
  compileExtendCorrect e o (readOut weight) X = solve! CR
  compileExtendCorrect e o (readIn weight) X = solve! CR

  compileReverseCorrect :
    (P : PolarizedReadout) (X : ResidualSummary) →
    evaluateReadout P (reverseSummary X) ≡
    evaluateReadout (reverseReadout P) X
  compileReverseCorrect (readOut weight) X = refl
  compileReverseCorrect (readIn weight) X = refl

  contextNormalization : (C : ContextProgram) (X : ResidualSummary) →
    runContext C X ≡ evaluateReadout (compileContext C) X
  contextNormalization (observeWith gap Y) X = solve! CR
  contextNormalization (extendWith e o C) X =
    contextNormalization C (pairAction X e o) ∙
    compileExtendCorrect e o (compileContext C) X
  contextNormalization (reverseThen C) X =
    contextNormalization C (reverseSummary X) ∙
    compileReverseCorrect (compileContext C) X

  unitResidual : ResidualSummary
  unitResidual = summarize singleton

  outgoingProbe : ContextProgram
  outgoingProbe = observeWith 1r unitResidual

  incomingProbe : ContextProgram
  incomingProbe = reverseThen outgoingProbe

  outgoingProbeReads : (X : ResidualSummary) →
    runContext outgoingProbe X ≡ out X
  outgoingProbeReads X = solve! CR

  incomingProbeReads : (X : ResidualSummary) →
    runContext incomingProbe X ≡ inn X
  incomingProbeReads X = solve! CR

  twoProbesFaithful : (X Y : ResidualSummary) →
    runContext outgoingProbe X ≡ runContext outgoingProbe Y →
    runContext incomingProbe X ≡ runContext incomingProbe Y →
    X ≡ Y
  twoProbesFaithful X Y outEqual inEqual i = record
    { out = (sym (outgoingProbeReads X) ∙ outEqual ∙ outgoingProbeReads Y) i
    ; inn = (sym (incomingProbeReads X) ∙ inEqual ∙ incomingProbeReads Y) i
    }

  completeFiniteValidity : ContextualValidity residualRankReset
  completeFiniteValidity = record
    { Context = ContextProgram
    ; Observation = Carrier
    ; observePrimitive = λ C X → runContext C (summarize X)
    ; observeMinimal = λ C p → runContext C (snd p)
    ; behaviorPreserved = λ C X → refl
    }

  completeFiniteBehaviorPreserved : (C : ContextProgram) (X : OddMetric) →
    runContext C (summarize X) ≡
    observeMinimal completeFiniteValidity C
      ( fst (reconcile residualRankReset (expose residualRankReset X))
      , retype residualRankReset
          (snd (reconcile residualRankReset (expose residualRankReset X))) )
  completeFiniteBehaviorPreserved =
    reconciledBehavior residualRankReset completeFiniteValidity
