#!/usr/bin/env python3
"""Exact finite torus group generated by modular S,T and C-F duality."""

from __future__ import annotations

import json
from collections import deque
from fractions import Fraction
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
K = ROOT / "research" / "kitaev"
OUT = K / "results" / "s3-torus-protected-gate-group.json"
N = 8


class Z3:
    """Exact a+b*w, w^2+w+1=0."""

    __slots__ = ("a", "b")

    def __init__(self, a=0, b=0):
        self.a, self.b = Fraction(a), Fraction(b)

    def __add__(self, other):
        other = z(other)
        return Z3(self.a + other.a, self.b + other.b)

    __radd__ = __add__

    def __neg__(self):
        return Z3(-self.a, -self.b)

    def __sub__(self, other):
        return self + (-z(other))

    def __mul__(self, other):
        other = z(other)
        return Z3(
            self.a * other.a - self.b * other.b,
            self.a * other.b + self.b * other.a - self.b * other.b,
        )

    __rmul__ = __mul__

    def __eq__(self, other):
        other = z(other)
        return self.a == other.a and self.b == other.b

    def __hash__(self):
        return hash((self.a, self.b))

    def __truediv__(self, other):
        other = z(other)
        norm = other.a * other.a - other.a * other.b + other.b * other.b
        assert norm != 0
        conjugate = Z3(other.a - other.b, -other.b)
        product = self * conjugate
        return Z3(product.a / norm, product.b / norm)

    def __bool__(self):
        return self.a != 0 or self.b != 0

    def text(self):
        def q(value):
            return str(value.numerator) if value.denominator == 1 else f"{value.numerator}/{value.denominator}"
        if self.b == 0:
            return q(self.a)
        return q(self.a) + ("+" if self.b >= 0 else "") + q(self.b) + "*omega"


def z(value):
    return value if isinstance(value, Z3) else Z3(value)


def identity():
    return tuple(Z3(int(i == j)) for i in range(N) for j in range(N))


def multiply(left, right):
    return tuple(
        sum((left[N * i + k] * right[N * k + j] for k in range(N)), Z3())
        for i in range(N)
        for j in range(N)
    )


def power(matrix, exponent):
    out = identity()
    for _ in range(exponent):
        out = multiply(matrix, out)
    return out


def closure(generators):
    unit = identity()
    seen = {unit}
    queue = deque([unit])
    while queue:
        current = queue.popleft()
        for generator in generators:
            candidate = multiply(generator, current)
            if candidate not in seen:
                seen.add(candidate)
                queue.append(candidate)
    return seen


def field_rank(rows):
    work = [list(row) for row in rows]
    rank = 0
    columns = len(work[0])
    for column in range(columns):
        pivot = next((i for i in range(rank, len(work)) if work[i][column]), None)
        if pivot is None:
            continue
        work[rank], work[pivot] = work[pivot], work[rank]
        scale = work[rank][column]
        work[rank] = [entry / scale for entry in work[rank]]
        for i in range(len(work)):
            if i != rank and work[i][column]:
                factor = work[i][column]
                work[i] = [work[i][j] - factor * work[rank][j] for j in range(columns)]
        rank += 1
        if rank == len(work):
            break
    return rank


def rref(rows, columns=None):
    work = [list(row) for row in rows]
    columns = columns if columns is not None else len(work[0])
    rank = 0
    pivots = []
    for column in range(columns):
        pivot = next((i for i in range(rank, len(work)) if work[i][column]), None)
        if pivot is None:
            continue
        work[rank], work[pivot] = work[pivot], work[rank]
        scale = work[rank][column]
        work[rank] = [entry / scale for entry in work[rank]]
        for i in range(len(work)):
            if i != rank and work[i][column]:
                factor = work[i][column]
                work[i] = [work[i][j] - factor * work[rank][j] for j in range(len(work[i]))]
        pivots.append(column)
        rank += 1
        if rank == len(work):
            break
    return work, pivots


def row_basis(rows):
    reduced, _ = rref(rows)
    return [tuple(row) for row in reduced if any(row)]


def nullspace(rows, columns):
    reduced, pivots = rref(rows, columns)
    free = [j for j in range(columns) if j not in pivots]
    basis = []
    for free_column in free:
        vector = [Z3() for _ in range(columns)]
        vector[free_column] = Z3(1)
        for row, pivot in enumerate(pivots):
            vector[pivot] = -reduced[row][free_column]
        basis.append(tuple(vector))
    return basis


def commutant_equations(generators):
    equations = []
    for generator in generators:
        for i in range(N):
            for j in range(N):
                row = [Z3() for _ in range(N * N)]
                # (XG-GX)_ij = sum_k X_ik G_kj - G_ik X_kj.
                for k in range(N):
                    row[N * i + k] = row[N * i + k] + generator[N * k + j]
                    row[N * k + j] = row[N * k + j] - generator[N * i + k]
                equations.append(tuple(row))
    return equations


def generated_algebra_basis(generators):
    basis = row_basis([identity()] + list(generators))
    while True:
        candidates = list(basis)
        for element in basis:
            for generator in generators:
                candidates.append(multiply(element, generator))
                candidates.append(multiply(generator, element))
        enlarged = row_basis(candidates)
        if len(enlarged) == len(basis):
            return enlarged
        basis = enlarged


def representation_profiles(algebra_dim, commutant_dim, center_dim, hilbert_dim):
    # Semisimple image: H = direct_sum_i C^{d_i} tensor C^{m_i};
    # dim A=sum d_i^2, dim A'=sum m_i^2, dim H=sum d_i*m_i.
    profiles = set()

    def rec(pairs, remaining_a, remaining_c, remaining_h, slots, min_pair):
        if slots == 0:
            if remaining_a == remaining_c == remaining_h == 0:
                profiles.add(tuple(pairs))
            return
        for d in range(1, int(remaining_a ** 0.5) + 1):
            for m in range(1, int(remaining_c ** 0.5) + 1):
                pair = (d, m)
                if pair < min_pair:
                    continue
                if d * d <= remaining_a and m * m <= remaining_c and d * m <= remaining_h:
                    rec(pairs + [pair], remaining_a - d * d, remaining_c - m * m,
                        remaining_h - d * m, slots - 1, pair)

    rec([], algebra_dim, commutant_dim, hilbert_dim, center_dim, (1, 1))
    return sorted(profiles)


def main() -> None:
    data = json.loads((K / "results" / "s3-modular-data.json").read_text(encoding="utf-8"))
    S = tuple(Z3(Fraction(value)) for row in data["S_matrix"] for value in row)
    twist_value = {
        "1": Z3(1), "-1": Z3(-1), "0+1*omega": Z3(0, 1),
        "-1-1*omega": Z3(-1, -1),
    }
    twists = [twist_value[data["topological_spins"][label]] for label in data["label_order"]]
    T = tuple(twists[i] if i == j else Z3() for i in range(N) for j in range(N))
    P = [Z3() for _ in range(N * N)]
    p = [0, 1, 5, 3, 4, 2, 6, 7]
    for i, image in enumerate(p):
        P[N * image + i] = Z3(1)
    P = tuple(P)

    I = identity()
    assert power(S, 4) == I
    assert power(T, 6) == I
    assert power(multiply(S, T), 3) == power(S, 2)
    assert power(P, 2) == I
    assert multiply(P, S) == multiply(S, P)
    assert multiply(P, T) == multiply(T, P)

    modular = closure([S, power(S, 3), T, power(T, 5)])
    protected = closure([S, power(S, 3), T, power(T, 5), P])
    p_in_modular = P in modular
    assert not p_in_modular
    assert len(protected) == 2 * len(modular)

    # The permutation subgroup inside the modular image is found exactly by
    # checking one unit entry per row/column and zeros elsewhere.
    def is_permutation(matrix):
        one, zero = Z3(1), Z3()
        return all(sum(matrix[N * i + j] == one for j in range(N)) == 1 for i in range(N)) and all(
            entry in (zero, one) for entry in matrix
        )

    modular_permutations = sum(is_permutation(matrix) for matrix in modular)
    protected_permutations = sum(is_permutation(matrix) for matrix in protected)
    modular_algebra_dimension = field_rank(list(modular))
    protected_algebra_dimension = field_rank(list(protected))
    protected_algebra_basis = row_basis(list(protected))
    commutant_basis = nullspace(commutant_equations([S, T, P]), N * N)
    commutant_dimension = len(commutant_basis)
    combined_span = field_rank(protected_algebra_basis + commutant_basis)
    center_dimension = protected_algebra_dimension + commutant_dimension - combined_span
    profiles = representation_profiles(
        protected_algebra_dimension, commutant_dimension, center_dimension, N
    )
    assert len(profiles) == 1

    # Locate all common one-dimensional generator characters.  A common
    # eigenspace of dimension two is precisely the multiplicity-two blind
    # block: every protected word acts as one scalar on the whole subspace.
    scalar_candidates = {
        "S": [("+1", Z3(1)), ("-1", Z3(-1))],
        "T": [("+1", Z3(1)), ("-1", Z3(-1)), ("omega", Z3(0, 1)),
              ("omega2", Z3(-1, -1))],
        "CF": [("+1", Z3(1)), ("-1", Z3(-1))],
    }
    common_scalar_spaces = []
    for s_name, s_value in scalar_candidates["S"]:
        for t_name, t_value in scalar_candidates["T"]:
            for p_name, p_value in scalar_candidates["CF"]:
                equations = []
                for matrix, value in ((S, s_value), (T, t_value), (P, p_value)):
                    for i in range(N):
                        row = [matrix[N * i + j] for j in range(N)]
                        row[i] = row[i] - value
                        equations.append(tuple(row))
                basis = nullspace(equations, N)
                if basis:
                    support = [
                        data["label_order"][j]
                        for j in range(N)
                        if any(vector[j] for vector in basis)
                    ]
                    common_scalar_spaces.append({
                        "S": s_name, "T": t_name, "CF": p_name,
                        "dimension": len(basis), "sector_support": support,
                        "basis_vectors": [
                            {
                                data["label_order"][j]: coefficient.text()
                                for j, coefficient in enumerate(vector) if coefficient
                            }
                            for vector in basis
                        ],
                    })
    assert sorted(space["dimension"] for space in common_scalar_spaces) == [1, 2]

    # Test every single coherent sector projector as an added Hamiltonian/phase
    # port.  This is associative control closure, not measurement access.
    single_projector_closures = {}
    for label_index, label in enumerate(data["label_order"]):
        projector = tuple(
            Z3(int(i == label_index and j == label_index))
            for i in range(N) for j in range(N)
        )
        single_projector_closures[label] = len(generated_algebra_basis([S, T, P, projector]))
    full_single_ports = [label for label, dimension in single_projector_closures.items() if dimension == N * N]
    pair_projector_closures = {}
    for left in range(N):
        for right in range(left + 1, N):
            projectors = []
            for label_index in (left, right):
                projectors.append(tuple(
                    Z3(int(i == label_index and j == label_index))
                    for i in range(N) for j in range(N)
                ))
            key = data["label_order"][left] + "+" + data["label_order"][right]
            pair_projector_closures[key] = len(generated_algebra_basis([S, T, P] + projectors))
    full_pair_ports = [key for key, dimension in pair_projector_closures.items() if dimension == N * N]

    result = {
        "schema": "marici.kitaev.s3-torus-protected-gate-group.v1",
        "exact_relations": {
            "S_order_divides_4": True,
            "T_order_divides_6": True,
            "ST_cubed_equals_S_squared": True,
            "CF_order_2": True,
            "CF_commutes_with_S": True,
            "CF_commutes_with_T": True,
        },
        "exact_group_counts": {
            "modular_ST_image": len(modular),
            "modular_ST_permutation_matrices": modular_permutations,
            "CF_is_in_modular_ST_image": p_in_modular,
            "modular_plus_CF_image": len(protected),
            "modular_plus_CF_permutation_matrices": protected_permutations,
            "enlargement_factor": len(protected) // len(modular),
            "modular_operator_algebra_dimension_over_Qomega": modular_algebra_dimension,
            "protected_operator_algebra_dimension_over_Qomega": protected_algebra_dimension,
            "ambient_matrix_algebra_dimension": N * N,
            "protected_commutant_dimension": commutant_dimension,
            "protected_center_dimension": center_dimension,
        },
        "group_structure": {
            "CF_is_central_relative_to_modular_image": True,
            "intersection_of_CF_factor_with_modular_image_is_trivial": not p_in_modular,
            "protected_visible_action": "modular_ST_image direct_product Z2_CF",
        },
        "representation_decomposition": {
            "profiles_d_irrep_m_multiplicity": [list(pair) for pair in profiles[0]],
            "profile_is_uniquely_forced_by_dimensions": True,
            "dimension_identities": {
                "sum_d_squared": protected_algebra_dimension,
                "sum_m_squared": commutant_dimension,
                "sum_d_times_m": N,
                "number_of_isotypic_blocks": center_dimension,
            },
            "common_scalar_eigenspaces": common_scalar_spaces,
            "protected_blind_multiplicity_dimension": 2,
            "protected_blind_multiplicity_meaning": "all protected words act by the same scalar on this coherent doublet",
        },
        "coherent_sector_projector_completion": {
            "closure_dimensions": single_projector_closures,
            "full_M8_single_ports": full_single_ports,
            "single_port_suffices": bool(full_single_ports),
            "pair_closure_dimensions": pair_projector_closures,
            "full_M8_projector_pairs": full_pair_ports,
            "minimum_projector_ports": 2 if full_pair_ports else ">2",
            "typing_boundary": "requires coherent projector Hamiltonian/phase control; central measurement or dephasing does not count",
        },
        "operation_class_boundary": {
            "S_T": "mapping-class / code-deformation action on torus ground space",
            "CF": "anyon autoequivalence with source-supported constant-depth or self-dual-lattice realization",
            "shared_fact": "both act on the same canonical character-basis torus Hilbert space",
            "not_claimed": "one common fault-tolerant microscopic schedule",
        },
        "verdict": "The protected C-F duality genuinely enlarges the exact torus modular image by a central factor of two, but protected gates alone span only 15 of 64 operator dimensions. Among coherent sector-projector ports, exactly two are necessary and sufficient for full M8: one of A or B together with one of C or F. This is a direct torus-space algebra theorem; measurement/dephasing access and the label bus do not supply the required coherent controls.",
    }
    OUT.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(result, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
