#!/usr/bin/env python3
"""Exact simple-current explanation of the hidden Wilson orientation C2."""

from __future__ import annotations

import hashlib
import json
from fractions import Fraction
from pathlib import Path


ROOT = Path(__file__).resolve().parents[3]
K = ROOT / "research" / "kitaev"
MODULAR = K / "results" / "s3-modular-data.json"
FULL = K / "results" / "s3-full-wilson-orientation-no-go.json"
OUT = K / "results" / "s3-wilson-orientation-simple-current-torsor.json"


def main() -> None:
    modular = json.loads(MODULAR.read_text(encoding="utf-8"))
    labels = modular["label_order"]
    index = {label: j for j, label in enumerate(labels)}
    S = [[Fraction(value) for value in row] for row in modular["S_matrix"]]
    N = [[[int(sum(S[a][x]*S[b][x]*S[c][x]/S[0][x] for x in range(8)))
           for c in range(8)] for b in range(8)] for a in range(8)]
    assert all(value in (0, 1) for plane in N for row in plane for value in row)

    b = index["B"]
    simple_current_action = []
    for a, label in enumerate(labels):
        outputs = [labels[c] for c in range(8) if N[b][a][c] == 1]
        assert len(outputs) == 1
        simple_current_action.append(outputs[0])
    assert simple_current_action == ["B", "A", "C", "E", "D", "F", "G", "H"]
    permutation = [index[label] for label in simple_current_action]
    assert all(permutation[permutation[a]] == a for a in range(8))
    assert N[b][b][index["A"]] == 1

    dimensions = [6*S[0][a] for a in range(8)]
    assert all(dimensions[permutation[a]] == dimensions[a] for a in range(8))
    coordinate_signs = [-1 if label in ("D", "E") else 1 for label in labels]
    wilson_intertwining = all(
        S[x][permutation[a]] / S[0][permutation[a]]
        == coordinate_signs[x] * S[x][a] / S[0][a]
        for x in range(8) for a in range(8)
    )
    assert wilson_intertwining

    fusion_violations = []
    for a in range(8):
        for c in range(8):
            for d in range(8):
                left = N[a][c][d]
                right = N[permutation[a]][permutation[c]][permutation[d]]
                if left != right:
                    fusion_violations.append((labels[a], labels[c], labels[d], left, right))
    assert len(fusion_violations) == 32
    assert ("A", "A", "A", 1, 0) in fusion_violations

    twists = modular["topological_spins"]
    twist_mismatches = [
        label for a, label in enumerate(labels)
        if twists[label] != twists[labels[permutation[a]]]
    ]
    assert twist_mismatches == ["D", "E"]
    s_permutation_invariant = all(
        S[permutation[a]][permutation[c]] == S[a][c]
        for a in range(8) for c in range(8)
    )
    assert not s_permutation_invariant

    full = json.loads(FULL.read_text(encoding="utf-8"))
    assert full["no_go"]["any_Wilson_eigenvalue_subset_fixes_absolute_orientation"] is False
    result = {
        "schema": "marici.kitaev.s3-wilson-orientation-simple-current-torsor.v1",
        "inputs_sha256": {
            str(path.relative_to(ROOT)).replace("\\", "/"): hashlib.sha256(path.read_bytes()).hexdigest()
            for path in (MODULAR, FULL)
        },
        "simple_current": {
            "object": "B",
            "fusion_action_B_tensor_x": dict(zip(labels, simple_current_action)),
            "B_tensor_B": "A",
            "order": 2,
            "invertible_quantum_dimension": 1,
            "equals_hidden_sector_permutation": True,
        },
        "Wilson_equivariance": {
            "formula": "W_x(B tensor a)=chi_B(x) W_x(a)",
            "character_chi_B": {label: coordinate_signs[j] for j, label in enumerate(labels)},
            "negative_coordinates": ["D", "E"],
            "exact_intertwining_verified": wilson_intertwining,
            "explanation": "Wilson signatures are equivariant under translation by the invertible sign charge B, so after coordinate orientation is forgotten they retain a C2 torsor but no preferred origin",
        },
        "categorical_failure_hierarchy": {
            "preserves_quantum_dimensions": True,
            "preserves_tensor_unit": False,
            "tensor_unit_image": "B",
            "is_fusion_ring_automorphism": False,
            "fusion_tensor_violation_count": len(fusion_violations),
            "minimal_fusion_witness": "A tensor A=A, but B tensor B=A rather than B",
            "preserves_modular_S_by_sector_relabelling": s_permutation_invariant,
            "preserves_topological_twists": False,
            "twist_mismatch_sectors": twist_mismatches,
        },
        "torsor_resolution": {
            "orientation_space": "a C2 torsor generated by B tensor -",
            "mathematical_origin": "the distinguished tensor unit A",
            "one_origin_bit_suffices": True,
            "local_torus_syndrome_supplies_origin": False,
            "operational_requirement": "a noncircular preparation/readout of tensor unit A, an oriented D/E twist calibration, or another B-odd constructor",
        },
        "Carrier_lens_split": {
            "shared_Carrier_geometry": "two-sheet C2 torsor, quotient orbits, and the need for an origin/section",
            "quantum_coefficient_lens": "identifies the deck action as fusion with B, distinguishes tensor unit A, and supplies fusion/twist observables",
        },
        "verdict": "The hidden Wilson orientation is exactly translation by the invertible sign charge B: sigma(a)=B tensor a. This explains the C2 and the D/E sign character of every Wilson coordinate. It is not a categorical gauge symmetry: it moves the tensor unit A to B, violates 32 fusion coefficients, fails modular-S relabelling invariance, and exchanges twists +1 and -1 on D/E. The Wilson packet is therefore a C2 torsor obtained by forgetting its fusion-unit origin. Mathematically A fixes the origin; operationally local torus syndrome does not prepare or identify A, so a noncircular unit, twist, or B-odd constructor remains required.",
    }
    OUT.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps(result, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
