#!/usr/bin/env python3
"""Count independent endpoint contexts generated by four signed shifts."""

import json, math
from itertools import product
from math import comb
from pathlib import Path

def l1_ball_count(rank,depth):
 return sum((2**j)*comb(rank,j)*comb(depth,j) for j in range(rank+1))
def enumerate_count(rank,depth):
 vectors=[v for v in product(range(-depth,depth+1),repeat=rank) if sum(abs(x) for x in v)<=depth]
 return len(vectors),(len(vectors)+1)//2

def main():
 rows=[]
 for k in range(0,9):
  total,half=enumerate_count(4,k);formula=l1_ball_count(4,k)
  assert total==formula and half==(formula+1)//2
  rows.append({'depth':k,'signed_word_vectors':total,'nonnegative_endpoint_contexts':half})
 assert all(rows[i+1]['nonnegative_endpoint_contexts']>rows[i]['nonnegative_endpoint_contexts'] for i in range(len(rows)-1))
 result={'schema':'marici.coherence.signed-shift-context-rank-growth.v1','independent_shift_rank':4,'depths_checked':8,'count_formula':'N_4(k)=(1+sum_(j=0)^4 2^j C(4,j) C(k,j))/2','counts':rows,'strict_growth':True,'asymptotic_leading_term':'k^4/3','conclusion':'endpoint contexts generated by four independent signed shifts do not stabilize at finite realization rank'}
 Path(__file__).with_name('signed-shift-context-rank-growth.v1.json').write_text(json.dumps(result,indent=2)+'\n');print(json.dumps(result,indent=2))
if __name__=='__main__':main()
