#!/usr/bin/env python3
"""Check whether discrete elimination-order comparisons carry any matrix holonomy."""

import json, random
from fractions import Fraction
from itertools import permutations, product
from pathlib import Path
import check_chain_skew_minimal_model as base
import check_elimination_order_comparisons as comp


def main():
 rng=random.Random(20260912);triple_count=0;loop_count=0
 for n in (4,6,8):
  gaps=[Fraction(rng.randrange(1,10),rng.randrange(1,10)) for _ in range(n-1)]
  M=base.chain(gaps);pairs=[(i,i+1) for i in range(0,n,2)];orders=list(permutations(pairs));Ps=[]
  for order in orders:
   _,P=comp.reduce_order(M,order);Ps.append(P)
  inv=[comp.inverse(P) for P in Ps]
  G=lambda a,b:base.mul(inv[a],Ps[b])
  # Exhaust all triples through size six; deterministic bounded triples at size eight.
  triples=product(range(len(Ps)),repeat=3) if n<8 else ((a,b,(7*a+11*b)%len(Ps)) for a in range(len(Ps)) for b in range(len(Ps)))
  for a,b,c in triples:
   assert base.mul(G(a,b),G(b,c))==G(a,c);triple_count+=1
  for a in range(len(Ps)):
   for b in range(len(Ps)):
    assert base.mul(G(a,b),G(b,a))==base.eye(n);loop_count+=1
 result={'schema':'marici.coherence.elimination-comparison-cocycle.v1','triple_comparisons':triple_count,'two_edge_loops':loop_count,'all_cocycles_strict':True,'all_discrete_loop_products_identity':True,'conclusion':'the comparison groupoid generated by G_ab=P_a^-1 P_b is thin and has no matrix holonomy; Maslov data would require additional continuous path or lift choices'}
 Path(__file__).with_name('elimination-comparison-cocycle.v1.json').write_text(json.dumps(result,indent=2)+'\n');print(json.dumps(result,indent=2))
if __name__=='__main__':main()
