

# This file was *autogenerated* from the file /mnt/c/Users/andrey/src/marici/research/nima/_tmp_q_square.sage
from sage.all_cmdline import *   # import sage library

_sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_8 = Integer(8); _sage_const_16 = Integer(16); _sage_const_7 = Integer(7)
R = PolynomialRing(QQ, names=('u', 'v',)); (u, v,) = R._first_ngens(2)
Q=-u**_sage_const_4 +_sage_const_4 *u**_sage_const_3 *v-_sage_const_4 *u**_sage_const_3 -_sage_const_4 *u**_sage_const_2 *v+_sage_const_4 *u**_sage_const_2 -_sage_const_8 *u*v-_sage_const_4 *v**_sage_const_2 +_sage_const_16 *u+_sage_const_16 *v-_sage_const_16 
D=_sage_const_4 *u**_sage_const_4 -_sage_const_4 *u**_sage_const_3 *v+_sage_const_4 *u**_sage_const_3 +_sage_const_4 *u**_sage_const_2 *v-_sage_const_7 *u**_sage_const_2 +_sage_const_2 *u*v-_sage_const_4 *u+v**_sage_const_2 -_sage_const_4 *v+_sage_const_4 
print('res', factor(Q.resultant(D,v)))
K = FunctionField(QQ, names=('u',)); (u,) = K._first_ngens(1)
S = PolynomialRing(K, names=('v',)); (v,) = S._first_ngens(1)
q=S(Q); d=S(D)
L = K.extension(q, names=('vv',)); (vv,) = L._first_ngens(1)
dL=L(d(v=vv))
print('square?', dL.is_square())

