

# This file was *autogenerated* from the file research/nima/_tmp_candidate_flatness.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_5 = Integer(5); _sage_const_6 = Integer(6); _sage_const_7 = Integer(7); _sage_const_8 = Integer(8); _sage_const_1 = Integer(1)
load('research/nima/check_marked_candidate_algebraic_kernel.sage')
conn=json.load(open('research/benincasa/bivariate_soft_gram_connection.json'))
wall=json.load(open('research/benincasa/marked-wall-quotient-connection.json'))
Dwall=F(sage_eval(wall['D'],locals={'u':u,'v':v}));Hwall=F(sage_eval(wall['H'],locals={'u':u,'v':v}))
def pm(s): return F(sage_eval(s,locals={'u':u,'v':v,'D':Dwall,'H':Hwall}))
def aw(axis):
 d=wall[axis]
 return matrix(F,[[pm(d['alpha']),_sage_const_0 ,_sage_const_0 ],[pm(d['beta1']),pm(d['gamma1']),_sage_const_0 ],[pm(d['beta2']),_sage_const_0 ,pm(d['gamma2'])]])
def a4(key):
 A=matrix(F,[[pm(z) for z in row] for row in conn[key]])
 return A.matrix_from_rows_and_columns([_sage_const_5 ,_sage_const_6 ,_sage_const_7 ,_sage_const_8 ],[_sage_const_5 ,_sage_const_6 ,_sage_const_7 ,_sage_const_8 ])
Cu=B['u'].transpose();Cv=B['v'].transpose();Au=aw('u');Av=aw('v');A4u=a4('connection_u');A4v=a4('connection_v')
for tw in [False,True]:
 for ta in [False,True]:
  U=Au.transpose() if tw else Au; V=Av.transpose() if tw else Av
  X=A4u.transpose() if ta else A4u; Y=A4v.transpose() if ta else A4v
  for sd in [_sage_const_1 ,-_sage_const_1 ]:
   for sp in [_sage_const_1 ,-_sage_const_1 ]:
    curv=sd*(Cv.derivative(u)-Cu.derivative(v))+sp*(U*Cv+Cu*Y-V*Cu-Cv*X)
    z=sum(q==_sage_const_0  for q in curv.list())
    if z: print('tw',tw,'ta',ta,'sd',sd,'sp',sp,'zeros',z)

