"""Compute the differential-module cohomology of Entry 798's strict cone."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import sympy as sp


def matrix(items):
    return sp.Matrix([[sp.sympify(x) for x in row] for row in items])


def texts(values):
    return [sp.sstr(sp.factor(x)) for x in values]


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("mixed_flatness", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()

    packet = json.loads(args.mixed_flatness.read_text(encoding="utf-8"))
    t = sp.symbols("t")
    residue = matrix(packet["normal_residue"])
    tangential = matrix(packet["exceptional_t_connection"])
    c = residue[2:, :2]
    a_p = tangential[:2, :2]
    a_e = tangential[2:, 2:]

    kernel = c.nullspace()
    left_kernel = c.T.nullspace()
    if len(kernel) != 1 or len(left_kernel) != 1:
        raise AssertionError("expected rank-one map between two-planes")
    k = kernel[0]
    q = left_kernel[0]

    # dF=A F.  A line generated by a constant column k has scalar action
    # alpha when A_P k=alpha k.  A quotient row q^T is horizontal when
    # q^T A_E is proportional to q^T; here both actions vanish.
    kernel_action = a_p * k
    quotient_action = q.T * a_e

    endpoint = {}
    for label, point in (("plus", 1), ("minus", -1)):
        endpoint_residue = c.applyfunc(lambda x: sp.cancel(sp.limit((t - point) * x, t, point)))
        endpoint[label] = {
            "point": point,
            "residue": [[sp.sstr(x) for x in endpoint_residue.row(i)] for i in range(2)],
            "rank": endpoint_residue.rank(),
            "image_generator": texts(endpoint_residue.columnspace()[0]),
            "same_cokernel_line": sp.cancel((q.T * endpoint_residue)[0]) == 0 and sp.cancel((q.T * endpoint_residue)[1]) == 0,
        }

    result = {
        "schema": "marici.nima.weighted_principal_strict_cone.v1",
        "source": str(args.mixed_flatness).replace("\\", "/"),
        "principal_map": [[sp.sstr(sp.factor(c[i, j])) for j in range(2)] for i in range(2)],
        "generic_rank": c.rank(),
        "cone_cohomology": {
            "H_minus_1_dimension": len(kernel),
            "H_minus_1_generator": texts(k),
            "H_minus_1_connection_action": texts(kernel_action),
            "H_0_dimension": len(left_kernel),
            "H_0_quotient_row": texts(q),
            "H_0_connection_action": texts(quotient_action),
        },
        "endpoint_residues": endpoint,
        "conclusion": "The strict local cone has two rank-one horizontal cohomology objects, one kernel line and one cokernel line. Endpoint residues preserve the same image line and do not select between them.",
        "allocator_claim": "seqclaim-c25eebe56c7464089f9be45a",
    }
    args.output.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"rank": c.rank(), "H_minus_1": len(kernel), "H_0": len(left_kernel), "endpoint_ranks": {k: v["rank"] for k, v in endpoint.items()}}))


if __name__ == "__main__":
    main()
