"""Classify S=alpha=beta=0 for the finite marked CM sextics."""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import sympy as sp


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("census", type=Path)
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    census = json.loads(args.census.read_text(encoding="utf-8"))

    e, a2, b2, p1, p2, p3 = sp.symbols("E A B P1 P2 P3")
    h = p1**2 + p2**2 - p3**2
    triangle = sp.expand((p1-p2-p3)*(p1-p2+p3)*(p1+p2-p3)*(p1+p2+p3))
    k = sp.expand(
        e**4*p3**2 - e**2*a2*p1**2 + e**2*a2*p2**2 - e**2*a2*p3**2
        + e**2*b2*p1**2 - e**2*b2*p2**2 - e**2*b2*p3**2
        - e**2*p1**2*p3**2 - e**2*p2**2*p3**2 + e**2*p3**4
        + a2**2*p1**2 - a2*b2*p1**2 - a2*b2*p2**2 + a2*b2*p3**2
        + a2*p1**4 - a2*p1**2*p2**2 - a2*p1**2*p3**2
        + b2**2*p2**2 - b2*p1**2*p2**2 + b2*p2**4 - b2*p2**2*p3**2
        + p1**2*p2**2*p3**2
    )
    ka, kb = sp.diff(k, a2), sp.diff(k, b2)
    hessian_det = sp.factor(sp.det(sp.hessian(k, (a2, b2))))
    if sp.expand(hessian_det + triangle) != 0:
        raise AssertionError("unexpected CM Hessian determinant")

    critical = {a2: e**2 + p2**2, b2: e**2 + p1**2}
    if sp.expand(ka.subs(critical)) != 0 or sp.expand(kb.subs(critical)) != 0:
        raise AssertionError("universal interior critical point is incorrect")
    interior_value = sp.factor(k.subs(critical))
    if sp.expand(interior_value - e**2 * triangle) != 0:
        raise AssertionError("unexpected interior critical value")

    b_critical_at_a0 = sp.solve(kb.subs(a2, 0), b2)[0]
    a_critical_at_b0 = sp.solve(ka.subs(b2, 0), a2)[0]
    a0_value = sp.factor(k.subs({a2: 0, b2: b_critical_at_a0}))
    b0_value = sp.factor(k.subs({b2: 0, a2: a_critical_at_b0}))
    both_zero_value = sp.factor(k.subs({a2: 0, b2: 0}))

    rows = []
    for row in census["nonparallel_pairs"]:
        a0, b0 = row["marked_point"]["a"], row["marked_point"]["b"]
        rows.append({
            "labels": row["labels"],
            "marked_point": row["marked_point"],
            "interior_critical_equations": [f"({a0})^2=E^2+P2^2", f"({b0})^2=E^2+P1^2"],
            "interior_support_after_gradient": ["E=0", "Lambda(P1,P2,P3)=0"],
            "a_coordinate_boundary": f"{a0}=0",
            "b_coordinate_boundary": f"{b0}=0",
            "classification": "existing marked-coordinate boundary plus total-energy, signed-energy, momentum-triangle, or restricted Cayley-Menger support",
        })

    result = {
        "schema": "marici.nima.finite_sextic_higher_critical_locus.v1",
        "source": str(args.census).replace("\\", "/"),
        "universal_squared_edge_model": "K_CM(E,A=a^2,B=b^2;P1,P2,P3)",
        "momentum_triangle": sp.sstr(sp.factor(triangle)),
        "hessian_determinant": sp.sstr(hessian_det),
        "interior": {
            "open_conditions": ["a0!=0", "b0!=0", "P1*P2*Lambda!=0"],
            "critical_point": {"A": "E^2+P2^2", "B": "E^2+P1^2"},
            "critical_value": sp.sstr(interior_value),
            "support": ["E=0", "Lambda=0"],
        },
        "coordinate_boundary_A0": {
            "critical_B": sp.sstr(sp.factor(b_critical_at_a0)),
            "critical_value": sp.sstr(a0_value),
            "support_factors": ["E-P2", "E+P2", "Lambda"],
        },
        "coordinate_boundary_B0": {
            "critical_A": sp.sstr(sp.factor(a_critical_at_b0)),
            "critical_value": sp.sstr(b0_value),
            "support_factors": ["E-P1", "E+P1", "Lambda"],
        },
        "double_coordinate_boundary": {
            "critical_value": sp.sstr(both_zero_value),
            "classification": "P3^2 times the frozen Cayley-Menger restriction at A=B=0",
        },
        "representatives": rows,
        "new_higher_carrier_stratum": False,
        "conclusion": "The nontransverse loci are generated by marked coordinate boundaries together with total-energy, signed-energy, momentum-triangle, and further frozen Cayley-Menger restrictions. No new unlabelled higher carrier stratum appears.",
        "scope": "set-theoretic support classification; scheme multiplicities and intersections among the listed components are not a primary-decomposition claim",
        "allocator_claim": "seqclaim-6f43d9839010f22ee2cc7d23",
    }
    args.output.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"hessian": sp.sstr(hessian_det), "interior_value": sp.sstr(interior_value), "representatives": len(rows)}))


if __name__ == "__main__":
    main()
