

# This file was *autogenerated* from the file /mnt/c/Users/andrey/src/marici/research/nima/check_q_hom_indicial_obstructions.sage
from sage.all_cmdline import *   # import sage library

_sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_8 = Integer(8); _sage_const_16 = Integer(16); _sage_const_12 = Integer(12); _sage_const_6 = Integer(6); _sage_const_9 = Integer(9); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_20 = Integer(20); _sage_const_21 = Integer(21); _sage_const_44 = Integer(44); _sage_const_100 = Integer(100); _sage_const_5 = Integer(5)
import json
from sage.misc.sage_eval import sage_eval

ROOT = "/mnt/c/Users/andrey/src/marici/research/benincasa"
R = PolynomialRing(QQ, names=('u', 'v',)); (u, v,) = R._first_ngens(2)
F = FractionField(R)
Q = -u**_sage_const_4 +_sage_const_4 *u**_sage_const_3 *v-_sage_const_4 *u**_sage_const_3 -_sage_const_4 *u**_sage_const_2 *v+_sage_const_4 *u**_sage_const_2 -_sage_const_8 *u*v-_sage_const_4 *v**_sage_const_2 +_sage_const_16 *u+_sage_const_16 *v-_sage_const_16 
D = -_sage_const_4 +_sage_const_12 *u-_sage_const_6 *u*v+_sage_const_4 *v-_sage_const_9 *u**_sage_const_2 +_sage_const_4 *u**_sage_const_2 *v-v**_sage_const_2 
H = -_sage_const_2 -_sage_const_3 *u+_sage_const_2 *u*v+v-u**_sage_const_2 *v+u**_sage_const_3 
a9 = json.load(open(ROOT+"/bivariate_soft_gram_connection.json"))
a3 = json.load(open(ROOT+"/marked-wall-quotient-connection.json"))

def parse(x):
    if isinstance(x,(int,Integer)): return F(x)
    return F(sage_eval(str(x).replace("^","**"),locals={"u":u,"v":v,"D":D,"H":H}))

def A3(axis):
    z=F(_sage_const_0 ); d=a3[axis]
    return [[parse(d["alpha"]),z,z],[parse(d["beta1"]),parse(d["gamma1"]),z],[parse(d["beta2"]),z,parse(d["gamma2"])]]

def audit(label,K,u0,v0):
    v1=K((-Q.derivative(u)/Q.derivative(v))(u=u0,v=v0))
    L=LaurentSeriesRing(K,'t',default_prec=_sage_const_4 ); t=L.gen(); uu=L(u0)+t; vv=L(v0)+L(v1)*t
    def residue(entries): return matrix(K,[[parse(x)(uu,vv)[-_sage_const_1 ] for x in row] for row in entries])
    R9=residue(a9["connection_u"])+v1*residue(a9["connection_v"])
    R3=residue(A3("u"))+v1*residue(A3("v"))
    T=identity_matrix(K,_sage_const_3 ).tensor_product(R9)-R3.transpose().tensor_product(identity_matrix(K,_sage_const_9 ))
    cp=T.charpoly(); roots=[n for n in range(-_sage_const_20 ,_sage_const_21 ) if cp(K(n))==_sage_const_0 ]
    return {"label":label,"R9_charpoly":str(factor(R9.charpoly())),"R3_charpoly":str(factor(R3.charpoly())),"Hom_charpoly":str(factor(cp)),"integer_roots":roots}

S = PolynomialRing(QQ, names=('z',)); (z,) = S._first_ngens(1)
KD = NumberField(z**_sage_const_2 -_sage_const_44 *z+_sage_const_100 , names=('wd',)); (wd,) = KD._first_ngens(1)
KH = NumberField(_sage_const_3 *z**_sage_const_2 -_sage_const_6 *z+_sage_const_1 , names=('wh',)); (wh,) = KH._first_ngens(1)
records=[
    audit("Q_cap_D",KD,KD(_sage_const_4 ),wd),
    audit("Q_cap_H",KH,wh,KH(_sage_const_2 )-wh/_sage_const_2 ),
    audit("Q_cap_u_plus_v_minus_2",QQ,QQ(_sage_const_8 )/_sage_const_5 ,QQ(_sage_const_2 )/_sage_const_5 ),
]
print(json.dumps({"schema":"marici.nima.q_hom_indicial_obstructions.v1","records":records},indent=_sage_const_2 ))

