"""Exact D4-abelianization test for the m=2 suspension/Ward line."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
ENTRY = ROOT / "src/ledger/20260813-65 The All-m Suspension Skeleton and Normal-Layer Transgression.md"
RIG = ROOT / "research/nima/results/phase-i-abelianized-rig-groupoid.json"
OUT = ROOT / "research/nima/results/phase-i-m2-ward-d4-factorization.json"


def digest(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


rig = json.loads(RIG.read_text(encoding="utf-8"))
assert rig["verdict"]["maximal_unit_compatible_automorphism_quotient_derived"] is True

Permutation = tuple[int, ...]
identity: Permutation = (0, 1, 2, 3)
rotation: Permutation = (1, 2, 3, 0)
reflection: Permutation = (0, 3, 2, 1)


def compose(left: Permutation, right: Permutation) -> Permutation:
    return tuple(left[right[index]] for index in range(4))


def closure(generators: tuple[Permutation, ...]) -> set[Permutation]:
    group = {identity}
    changed = True
    while changed:
        changed = False
        for left in tuple(group):
            for right in generators + tuple(group):
                value = compose(left, right)
                if value not in group:
                    group.add(value)
                    changed = True
    return group


d4 = closure((rotation, reflection))
assert len(d4) == 8

# H1(C4) is generated by the oriented cycle 0->1->2->3->0. An automorphism
# acts by +1 when it preserves cyclic orientation and -1 when it reverses it.
oriented_edges = ((0, 1), (1, 2), (2, 3), (3, 0))


def cycle_character(value: Permutation) -> int:
    image_first = (value[0], value[1])
    if image_first in oriented_edges:
        return 1
    if (image_first[1], image_first[0]) in oriented_edges:
        return -1
    raise AssertionError("Not a C4 automorphism")


character = {value: cycle_character(value) for value in d4}
assert all(
    character[compose(left, right)] == character[left] * character[right]
    for left in d4
    for right in d4
)
half_turn = compose(rotation, rotation)
assert character[rotation] == 1
assert character[reflection] == -1
assert character[half_turn] == 1

# Every commutator is killed, which is exactly the factor-through-abelianization
# criterion.
def inverse(value: Permutation) -> Permutation:
    result = [0] * 4
    for index, image in enumerate(value):
        result[image] = index
    return tuple(result)


commutators = {
    compose(compose(compose(left, right), inverse(left)), inverse(right))
    for left in d4
    for right in d4
}
assert all(character[value] == 1 for value in commutators)

out = {
    "schema": "marici.nima.phase_i_m2_ward_d4_factorization.v1",
    "status": "exact_source_typed_representation_test",
    "inputs": {
        str(path.relative_to(ROOT)).replace("\\", "/"): digest(path)
        for path in (ENTRY, RIG)
    },
    "sector": "scattering/QTDS m=2 suspension-Ward line",
    "representation": {
        "carrier": "H1(K_2,2)=H1(C4)",
        "dimension": 1,
        "rotation_character": character[rotation],
        "reflection_character": character[reflection],
        "commutator_half_turn_character": character[half_turn],
        "factors_through_D4_ab": True,
    },
    "verdict": {
        "first_scattering_coefficient_detects_killed_commutator": False,
        "first_scattering_coefficient_factors_through_arithmetic_shadow": True,
        "all_sector_factorization_proved": False,
    },
}

OUT.write_text(json.dumps(out, indent=2) + "\n", encoding="utf-8")
print(json.dumps(out))
