#!/usr/bin/env python3
"""Identify cluster Ptolemy flips, hyperbolic lambda lengths, and G_+(2,n) minors."""
import itertools,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];sys.path.insert(0,str(ROOT/'research/benincasa/.tmp_sympy'));import sympy as s
xa,xb,xc,xd=s.symbols('x_a x_b x_c x_d');D=lambda x,y:y-x;identity=s.expand(D(xa,xc)*D(xb,xd)-D(xa,xb)*D(xc,xd)-D(xa,xd)*D(xb,xc));rows=[]
for n in range(4,13):
 x={i:s.Integer(i*i+i+1) for i in range(1,n+1)};positive=all(x[j]-x[i]>0 for i in range(1,n+1) for j in range(i+1,n+1));ptolemy=all(s.expand((x[c]-x[a])*(x[d]-x[b])-(x[b]-x[a])*(x[d]-x[c])-(x[d]-x[a])*(x[c]-x[b]))==0 for a,b,c,d in itertools.combinations(range(1,n+1),4));rows.append({'n':n,'positive_ordered_minors':positive,'all_quadrilateral_ptolemy_relations':ptolemy,'quadrilaterals':int(s.binomial(n,4))})
checks={'symbolic_plucker_ptolemy_identity':identity==0,'all_tested_positive_configurations':all(x['positive_ordered_minors'] for x in rows),'all_flips_are_plucker_relations':all(x['all_quadrilateral_ptolemy_relations'] for x in rows),'tested_n4_through_n12':len(rows)==9}
out={'schema':'marici.nima.nnmhv-plucker-poincare-cluster-bridge.v1','dictionary':{'positive_point_configuration':'C_i=(1,x_i), x_1<...<x_n','grassmannian_minor':'Delta_ij=det(C_i,C_j)=x_j-x_i','hyperbolic_lambda_length':'lambda_ij proportional to Delta_ij/sqrt(epsilon_i epsilon_j)','cluster_flip':'Delta_ac Delta_bd = Delta_ab Delta_cd + Delta_ad Delta_bc','geometry':'Ptolemy relation for an ideal hyperbolic quadrilateral'},'rows':rows,'checks':checks,'passed':all(checks.values()),'meaning':'The associahedral mutation law of history intervals, Ptolemy surgery of hyperbolic geodesics, and the Plücker relation defining G_+(2,n) are the same equation in three presentations.','bridges':['positive Grassmannian Plücker coordinates','type-A cluster exchange','decorated Teichmüller lambda lengths','ideal-hyperbolic Ptolemy theorem','amplituhedron source geometry']};p=ROOT/'research/nima/results/nnmhv-plucker-poincare-cluster-bridge.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'schema':out['schema'],'dictionary':out['dictionary'],'checks':checks,'meaning':out['meaning'],'bridges':out['bridges'],'passed':out['passed']},indent=2));raise SystemExit(0 if out['passed'] else 1)
