"""Audit whether WP8 same-chart flavor doublets are magnitude permutations.

This is a deliberately finite WP10 gate.  It groups the WP7 minima over the
best-fit physical point by the exact sparse chart, finds every chart with two
or more loop phases, and compares the fitted edge magnitudes sector by sector.
"""

import itertools
import json
import math
from pathlib import Path

import numpy as np


ENSEMBLE = Path("research/flavor/results/wp7_ensemble.json")
OUTPUT = Path("research/nima/results/flavor-same-chart-branch-involution.json")
PHYS_TOL_SIGMA = 1e-4


def assignment(left, right):
    """Exact exhaustive minimum-L2 assignment for at most five entries."""
    assert len(left) == len(right)
    best = None
    for perm in itertools.permutations(range(len(right))):
        residual = np.asarray(left) - np.asarray([right[j] for j in perm])
        score = float(residual @ residual)
        if best is None or score < best[0]:
            best = (score, perm, residual)
    return {
        "l2": math.sqrt(best[0]),
        "permutation": list(best[1]),
        "max_abs_residual": float(np.max(np.abs(best[2]))),
    }


def main():
    data = json.loads(ENSEMBLE.read_text(encoding="utf-8"))
    # Import only the authoritative observable reconstruction; this repeats
    # WP8's physical-fiber selection rather than trusting stored grouping.
    import sys
    sys.path.insert(0, "research/flavor/checkers")
    from wp7_ensemble import SIGMA, build_texture, mask_slots, observables17

    points = []
    for orbit in data["orbits"]:
        for item in orbit["viable_minima"]:
            pe = item["phase_edge"]
            theta = np.array(item["log_mags"] + [item["phi"]])
            yu, yd = build_texture(
                item["member"][0], item["member"][1], pe[0],
                (pe[1], pe[2]), theta
            )
            points.append({
                "orbit": orbit["orbit_index"],
                **item,
                "observables": observables17(yu, yd),
            })
    best = min(points, key=lambda x: x["chi2"])
    fiber = [
        x for x in points
        if np.all(np.abs(x["observables"] - best["observables"])
                  <= PHYS_TOL_SIGMA * SIGMA)
    ]
    assert len(fiber) == 61

    groups = {}
    for item in fiber:
        key = (
            item["orbit"],
            tuple(item["member"]),
            tuple(item["phase_edge"]),
        )
        groups.setdefault(key, []).append(item)

    doublets = []
    for key, items in groups.items():
        # Collapse the +/- phase convention and repeated optimizer hits.
        branches = {}
        for item in items:
            branches.setdefault(round(item["phi_folded"], 6), item)
        if len(branches) < 2:
            continue
        assert len(branches) == 2, (key, sorted(branches))
        x, y = [branches[k] for k in sorted(branches)]
        mu, md = key[1]
        nu, nd = len(mask_slots(mu)), len(mask_slots(md))
        assert nu + nd == len(x["log_mags"]) == len(y["log_mags"])

        up = assignment(x["log_mags"][:nu], y["log_mags"][:nu])
        down = assignment(x["log_mags"][nu:], y["log_mags"][nu:])
        identity_l2 = float(np.linalg.norm(
            np.asarray(x["log_mags"]) - np.asarray(y["log_mags"])
        ))
        combined_l2 = math.hypot(up["l2"], down["l2"])
        doublets.append({
            "chart": {
                "orbit": key[0],
                "member": list(key[1]),
                "phase_edge": list(key[2]),
            },
            "phases": sorted(branches),
            "identity_log_magnitude_l2": identity_l2,
            "best_sectorwise_permutation_l2": combined_l2,
            "up_assignment": up,
            "down_assignment": down,
            "is_exact_sectorwise_permutation": (
                up["max_abs_residual"] < 1e-6
                and down["max_abs_residual"] < 1e-6
            ),
        })

    # A deck involution implemented by a universal coordinate permutation
    # would require the same sectorwise permutations on all doublets.
    signatures = {
        (tuple(d["up_assignment"]["permutation"]),
         tuple(d["down_assignment"]["permutation"]))
        for d in doublets
    }
    checks = {
        "wp8_fiber_size_reproduced": len(fiber) == 61,
        "four_same_chart_doublets_reproduced": len(doublets) == 4,
        "all_doublets_exact_sectorwise_permutations": all(
            d["is_exact_sectorwise_permutation"] for d in doublets
        ),
        "one_universal_coordinate_permutation": len(signatures) == 1,
    }
    verdict = (
        "The same-chart fiber is generated by a universal magnitude "
        "permutation."
        if checks["all_doublets_exact_sectorwise_permutations"]
        and checks["one_universal_coordinate_permutation"]
        else
        "The observed same-chart fiber is not the orbit of one universal "
        "coordinate-permutation involution; WP10 requires a genuinely "
        "chart-dependent algebraic branch correspondence."
    )
    out = {
        "checker": "flavor_same_chart_branch_involution",
        "author": "marici.Nima",
        "source": str(ENSEMBLE).replace("\\", "/"),
        "fiber_size": len(fiber),
        "doublets": doublets,
        "permutation_signature_count": len(signatures),
        "checks": checks,
        "verdict": verdict,
        "scope": (
            "Tests permutations of fitted nonzero magnitudes within each "
            "Yukawa sector. It does not exhaust nonlinear birational deck "
            "maps or certify the full physical fiber."
        ),
    }
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(json.dumps(out, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({
        "checks": checks,
        "permutation_signature_count": len(signatures),
        "doublets": doublets,
        "verdict": verdict,
    }, indent=2))


if __name__ == "__main__":
    main()
