

# This file was *autogenerated* from the file research/nima/check_marked_algebraic_horizontal_gauge.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_7 = Integer(7); _sage_const_3 = Integer(3); _sage_const_8 = Integer(8); _sage_const_16 = Integer(16); _sage_const_0 = Integer(0); _sage_const_5 = Integer(5); _sage_const_6 = Integer(6)
import json
import hashlib

R = PolynomialRing(QQ, names=('u', 'v',)); (u, v,) = R._first_ngens(2)
F = R.fraction_field()

y = (u+v)/_sage_const_2 -_sage_const_1 
Ptop = u*(u-_sage_const_2 )*(v-_sage_const_2 )
P6 = _sage_const_1 -u-v+v**_sage_const_2 /_sage_const_4 +u*v/_sage_const_2 -_sage_const_7 *u**_sage_const_2 /_sage_const_4 +u**_sage_const_2 *v+u**_sage_const_3 -u**_sage_const_3 *v+u**_sage_const_4 
D1 = (v-u)*(y-u**_sage_const_2 )*(y+u**_sage_const_2 )
Q = -u**_sage_const_4 +_sage_const_4 *u**_sage_const_3 *v-_sage_const_4 *u**_sage_const_3 -_sage_const_4 *u**_sage_const_2 *v+_sage_const_4 *u**_sage_const_2 -_sage_const_8 *u*v-_sage_const_4 *v**_sage_const_2 +_sage_const_16 *u+_sage_const_16 *v-_sage_const_16 
h = u*(u+v)*(u+v-_sage_const_4 )*P6/_sage_const_4 
alpha = (_sage_const_1 -y**_sage_const_2 )*(y**_sage_const_2 -u**_sage_const_4 )
v_beta = _sage_const_2 *(u**_sage_const_2 +y**_sage_const_2 )
v_gamma = -_sage_const_2 *y**_sage_const_2 *(u**_sage_const_2 +_sage_const_1 )
split_line = matrix(F, _sage_const_1 , _sage_const_4 , [h, alpha, v_beta, v_gamma])

connection_path = 'research/benincasa/bivariate_soft_gram_connection.json'
wall_path = 'research/benincasa/marked-wall-quotient-connection.json'
connection_bytes = open(connection_path,'rb').read()
wall_bytes = open(wall_path,'rb').read()
connection = json.loads(connection_bytes)
wall = json.loads(wall_bytes)

Dwall = F(sage_eval(wall['D'],locals={'u':u,'v':v}))
Hwall = F(sage_eval(wall['H'],locals={'u':u,'v':v}))

def parse(s):
    return F(sage_eval(s,locals={'u':u,'v':v,'D':Dwall,'H':Hwall}))

def wall_matrix(axis):
    d=wall[axis]
    return matrix(F,[[parse(d['alpha']),_sage_const_0 ,_sage_const_0 ],
                     [parse(d['beta1']),parse(d['gamma1']),_sage_const_0 ],
                     [parse(d['beta2']),_sage_const_0 ,parse(d['gamma2'])]])

def final_matrix(key):
    A=matrix(F,[[parse(z) for z in row] for row in connection[key]])
    return A.matrix_from_rows_and_columns([_sage_const_5 ,_sage_const_6 ,_sage_const_7 ,_sage_const_8 ],[_sage_const_5 ,_sage_const_6 ,_sage_const_7 ,_sage_const_8 ])

Wu = wall_matrix('u').transpose()
Wv = wall_matrix('v').transpose()
A4u = final_matrix('connection_u').transpose()
A4v = final_matrix('connection_v').transpose()

# The first marked coefficient coordinate is the top quotient.  Entry 867's
# second algebraic line is v_alg+h*e6, and its character differs from the
# top character by dlog(Ptop*D1).  This gives the surviving triangular gauge.
top_to_split = _sage_const_1 /(Ptop*D1)
X = matrix(F, _sage_const_3 , _sage_const_4 , [top_to_split*z for z in split_line[_sage_const_0 ]] + [_sage_const_0 ]*_sage_const_8 )

checks = {}
for name,t,W,A4 in [('u',u,Wu,A4u),('v',v,Wv,A4v)]:
    residual = X.derivative(t)-W*X+X*A4
    assert residual == _sage_const_0 
    checks[name] = {'horizontal_residual_zero':True}

denominator_lcm = lcm([R(z.denominator()) for z in X.list() if z != _sage_const_0 ])
assert gcd(denominator_lcm,Q) == _sage_const_1 
assert X.rank() == _sage_const_1 

result = {
    'schema':'marici.marked-algebraic-horizontal-gauge.v1',
    'field':'QQ(u,v)',
    'coefficient_convention':'transpose packet matrices; nabla=d-A',
    'connection_sha256':hashlib.sha256(connection_bytes).hexdigest(),
    'wall_connection_sha256':hashlib.sha256(wall_bytes).hexdigest(),
    'generator':'(Ptop*D1)^(-1) q_top^vee tensor (v_alg+h e6)',
    'rank':int(X.rank()),
    'checks':checks,
    'denominator_lcm_factorization':str(factor(denominator_lcm)),
    'Q_coprime_denominator':True,
    'candidate_independent':True,
    'status':'exact_horizontal_gauge_pass',
}

with open('research/nima/marked-algebraic-horizontal-gauge.json','w') as handle:
    json.dump(result,handle,indent=_sage_const_2 ,sort_keys=True)
    handle.write('\n')

print(json.dumps(result,indent=_sage_const_2 ,sort_keys=True))

