#!/usr/bin/env python3
"""Exact D3 commutator detector on a three-direction memory readout."""

import json
from pathlib import Path
def mul(a, b):
    return tuple(tuple(sum(a[i][k] * b[k][j] for k in range(len(b)))
                       for j in range(len(b[0]))) for i in range(len(a)))


def power(a, n):
    out = tuple(tuple(int(i == j) for j in range(len(a))) for i in range(len(a)))
    for _ in range(n):
        out = mul(a, out)
    return out


r = ((0, 0, 1), (1, 0, 0), (0, 1, 0))
s = ((1, 0, 0), (0, 0, 1), (0, 1, 0))
eye = ((1, 0, 0), (0, 1, 0), (0, 0, 1))

assert power(r, 3) == eye
assert power(s, 2) == eye
assert mul(mul(s, r), s) == power(r, 2)

# The constant sample is the scalar/invariant line.  Differences span the
# physical directional (standard) plane.
constant = ((1,), (1,), (1,))
assert mul(r, constant) == constant
assert mul(s, constant) == constant

# Columns are the images of b1=(1,-1,0), b2=(0,1,-1) in that basis.
r2 = ((0, -1), (1, -1))
s2 = ((1, 0), (1, -1))
eye2 = ((1, 0), (0, 1))
assert power(r2, 3) == eye2
assert power(s2, 2) == eye2
assert mul(mul(s2, r2), s2) == power(r2, 2)
assert r2 != eye2

# [D3,D3]=<r>.  The directional memory readout detects its generator.
commutator = mul(mul(mul(s2, r2), s2), power(r2, 2))
assert commutator == r2
assert commutator != eye2

result = {
    "schema": "marici.nima.radiative_memory_d3_commutator.v1",
    "source_readout": "three direction-labelled samples of Delta C_zz = D_z^2 N",
    "group": "D3 celestial-direction symmetry",
    "scalar_line_character": "trivial",
    "directional_plane_rank": 2,
    "rotation_matrix": [list(row) for row in r2],
    "reflection_matrix": [list(row) for row in s2],
    "commutator_subgroup": "C3 generated by r",
    "commutator_detected": True,
    "conclusion": "vector-valued physical memory readout does not factor through D3 abelianization",
    "passed": True,
}
out = Path(__file__).with_name("results") / "radiative-memory-d3-commutator.json"
out.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
print(json.dumps(result, indent=2))
