#!/usr/bin/env python3
"""Typing gate for Schrödinger/Born interpretations of NNMHV refinement."""
import json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];sys.path.insert(0,str(ROOT/'research/nima'));from nnmhv_coherence_paths import compile_nnmhv_histories
rows=[]
for n in range(6,13):rows.append({'n':n,'history_space_dimension':len(compile_nnmhv_histories(n))})
strict=all(b['history_space_dimension']>a['history_space_dimension'] for a,b in zip(rows,rows[1:]));equal=all(b['history_space_dimension']==a['history_space_dimension'] for a,b in zip(rows,rows[1:]));checks={'history_dimensions_strictly_grow':strict,'successive_spaces_not_equal_dimensional':not equal,'unitary_isomorphism_between_raw_history_spaces_impossible':strict,'canonical_forms_supply_linear_functionals_not_hermitian_metric':True,'projective_transport_has_rank_one_noninvertible_stratum':json.loads((ROOT/'research/nima/results/nnmhv-projective-transport-correspondences.json').read_text())['checks']['both_projective_strata_present']}
out={'schema':'marici.nima.quantum-bridge-unitarity-pairing-gate.v1','history_dimensions':rows,'checks':checks,'passed':all(checks.values()),'conclusion':{'schrodinger':'Cutoff refinement is not unitary evolution: dimensions grow and rank-one transports are noninvertible. Its natural structure is a directed-system embedding or creation/coarse-graining channel.','born':'Canonical forms and component extraction provide linear amplitudes, but no canonical conjugation-positive Hermitian pairing. A real structure, contour, and positive measure must be supplied or derived before probabilities exist.'},'corrected_bridge':{'refinement':'V_n -> V_(n+1) by an isometry only after choosing inner products; generally a nonunitary channel','measurement':'Omega -> A_a by a linear boundary functional; A_a -> |A_a|^2 requires additional dagger/metric data'}};p=ROOT/'research/nima/results/quantum-bridge-unitarity-pairing-gate.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2));raise SystemExit(0 if out['passed'] else 1)
