#!/usr/bin/env python3
"""Test physical kernel weights against positive type-A Ptolemy exchange."""
import json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];sys.path.insert(0,str(ROOT/'research/benincasa/.tmp_sympy'));import sympy as s
src=json.loads((ROOT/'research/nima/results/nnmhv-kernel-wall-tail-boundary.json').read_text());K=s.Matrix([[s.sympify(x) for x in row] for row in src['kernel_matrix']]);K0=s.Matrix([[s.sympify(x) for x in row] for row in src['kernel_without_upper_boundary_transport']]);
def residual(A):return s.factor(A[1,0]*A[2,1]-A[2,0]*A[1,1])
r=residual(K);r0=residual(K0);checks={'unupdated_exchange_residual_positive':s.sign(r0)==1,'updated_exchange_residual_negative':s.sign(r)==-1,'boundary_transport_crosses_positive_cluster_wall':s.sign(r0)!=s.sign(r),'physical_weights_fail_positive_ptolemy_completion':r<0}
out={'schema':'marici.nima.nnmhv-cluster-exchange-weight-gate.v1','quadrilateral':{'crossing_pair':'[1,2] and [2,3] -> diagonals (1,4),(2,5)','nested_resolution':'[1,3] and alpha_2 -> diagonals (1,5),(2,4)','inferred_other_channel':'R=K_[1,2]K_[2,3]-K_[1,3]K_alpha2'},'without_boundary_update':{'R':str(r0),'sign':'positive','interpretation':'admits a positive missing Ptolemy channel'},'with_boundary_update':{'R':str(r),'sign':'negative','interpretation':'cannot be completed by a positive missing Ptolemy channel'},'checks':{k:bool(v) for k,v in checks.items()},'passed':all(bool(v) for v in checks.values()),'meaning':'History labels have exact type-A cluster combinatorics, but physical canonical weights are not cluster lambda lengths. Boundary transport drives them across the positive exchange wall into a signed/oriented chamber.','bridges':['cluster exchange defect','signed Ptolemy relation','positive-variety wall crossing','oriented rather than positive coefficient system','separation of combinatorial cluster structure from physical weights']};p=ROOT/'research/nima/results/nnmhv-cluster-exchange-weight-gate.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2));raise SystemExit(0 if out['passed'] else 1)
