#!/usr/bin/env python3
"""Fail-closed gate for a noncircular source-derived rank-two Weil feature."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
files={'gns_correction':'research/nima/correction-gns-is-a-completion-theorem-not-the-rh-bearing-positivity-proof.md','mixed_bezoutian':'research/grothendieck/theta-green-transfer-mixed-bezoutian.md','cross_term':'research/grothendieck/rank-two-positivity-is-a-gamma-prime-cross-term-theorem.md','common_center':'research/voevodsky/rank-two-common-center-coupled-cone.md'}
T={k:(ROOT/v).read_text(encoding='utf-8') for k,v in files.items()}
requirements={'pre_spectral_source_definition':False,'undecomposed_gamma_prime_coupling':False,'positive_carrier_before_target_kernel':False,'green_identity_reproduces_D2':False,'poisson_q_covariance':False}
findings={'sector_direct_sum_rejected':'No block-diagonal Gram factor' in T['cross_term'],'green_transfer_computed':'Mixed Bezoutian identity' in T['mixed_bezoutian'],'green_transfer_not_manifest_square':'manifest square' in T['mixed_bezoutian'] and 'does not occur' in T['mixed_bezoutian'],'common_center_is_identity_not_constructor':'exact completion of the square' in T['common_center'],'target_cholesky_forbidden':'Cholesky factorization' in T['gns_correction'] and 'circular hostile' in T['gns_correction']}
out={'schema':'marici.nima.source-derived-rank-two-constructor-gate.v1','target':'construct R2(t,h) from undecomposed arithmetic source with Gram equal to [[a0,a1],[a1,a2]]','requirements':requirements,'prior_findings':findings,'admitted_constructor_exists':all(requirements.values()),'candidate_dispositions':{'gamma_direct_sum_prime':'rejected: sector minors can both be negative','Green_transferred_K_P_Bezoutian':'exact but remains antisymmetric and not a positive square','common_center':'useful certification chart but assumes the same total determinant inequality','target_kernel_Cholesky':'circular and prohibited'},'first_new_theorem_needed':'a positive comparison principle for the paired source responses K and Phi (equivalently P and I) strong enough to dominate the gamma-prime cross term','passed_audit':all(findings.values()),'rh_proved':False}
p=ROOT/'research/nima/results/source-derived-rank-two-constructor-gate.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2));raise SystemExit(0 if out['passed_audit'] else 1)
