#!/usr/bin/env python3
"""Triangular incidence double and diagonal decoherence of shell blocks."""
import json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];sys.path.insert(0,str(ROOT/'research/benincasa/.tmp_sympy'));import sympy as s
rows=[]
for r in range(1,8):
 upper={(p,q) for p in range(r) for q in range(r) if p<=q};lower={(p,q) for p in range(r) for q in range(r) if p>=q};diag={(p,p) for p in range(r)};full={(p,q) for p in range(r) for q in range(r)};u=s.ones(r,1);rho=u*u.T/s.Integer(r);deph=s.diag(*[rho[i,i] for i in range(r)]);P=rho
 checks={'upper_is_incidence_dimension':len(upper)==r*(r+1)//2,'dagger_upper_is_lower':{(q,p) for p,q in upper}==lower,'intersection_is_diagonal':upper&lower==diag,'triangular_double_spans_full_matrix':upper|lower==full,'dephasing_idempotent':s.diag(*[deph[i,i] for i in range(r)])==deph,'dephased_uniform_state_is_maximally_mixed':deph==s.eye(r)/r,'coherent_detector_probability_one':s.trace(rho*P)==1,'dephased_detector_probability_inverse_r':s.trace(deph*P)==s.Rational(1,r)}
 rows.append({'r':r,'upper_dimension':len(upper),'strict_lower_dimension':len(lower-diag),'full_dimension':r*r,'coherent_uniform_purity':str(s.trace(rho*rho)),'dephased_purity':str(s.trace(deph*deph)),'coherent_uniform_detector':str(s.trace(rho*P)),'dephased_uniform_detector':str(s.trace(deph*P)),'checks':checks})
allchecks={'all_exact':all(all(row['checks'].values()) for row in rows),'coherence_advantage_scales_as_r':all(row['coherent_uniform_detector']=='1' and row['dephased_uniform_detector']==f'1/{row["r"]}' for row in rows if row['r']>1)}
out={'schema':'marici.nima.nnmhv-triangular-double-decoherence.v1','identification':{'left_nested':'upper incidence algebra T_r of the total order','right_nested':'strictly lower part of T_r^dagger','diagonal':'T_r intersection T_r^dagger','full_shell_block':'T_r + T_r^dagger = M_r','classicalization':'E_D(A)=sum_p E_pp A E_pp'},'rows':rows,'checks':allchecks,'passed':all(allchecks.values()),'meaning':'Opposite nesting branches are dagger causal orientations whose double generates the full matrix algebra. Diagonal projection is the canonical classical shadow and deletes all cross-history interference.','bridges':['incidence/nest algebras','causal versus reverse-causal ordering','finite C*-algebra completion','conditional expectation and decoherence','pure-to-maximally-mixed uniform state']};p=ROOT/'research/nima/results/nnmhv-triangular-double-decoherence.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'schema':out['schema'],'identification':out['identification'],'checks':allchecks,'meaning':out['meaning'],'bridges':out['bridges'],'passed':out['passed']},indent=2));raise SystemExit(0 if out['passed'] else 1)
