

# This file was *autogenerated* from the file research/nima/check_algebraic_split_characteristic_zero.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_7 = Integer(7); _sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_5 = Integer(5); _sage_const_6 = Integer(6); _sage_const_8 = Integer(8)
import json
import hashlib

R = PolynomialRing(QQ, names=('u', 'v',)); (u, v,) = R._first_ngens(2)
F = R.fraction_field()

y = (u+v)/_sage_const_2 -_sage_const_1 
P6 = _sage_const_1 -u-v+v**_sage_const_2 /_sage_const_4 +u*v/_sage_const_2 -_sage_const_7 *u**_sage_const_2 /_sage_const_4 +u**_sage_const_2 *v+u**_sage_const_3 -u**_sage_const_3 *v+u**_sage_const_4 
D1 = (v-u)*(y-u**_sage_const_2 )*(y+u**_sage_const_2 )
h = u*(u+v)*(u+v-_sage_const_4 )*P6/_sage_const_4 

alpha = (_sage_const_1 -y**_sage_const_2 )*(y**_sage_const_2 -u**_sage_const_4 )
beta = _sage_const_2 *(u**_sage_const_2 +y**_sage_const_2 )
gamma = -_sage_const_2 *y**_sage_const_2 *(u**_sage_const_2 +_sage_const_1 )
K = matrix(F, [[_sage_const_1 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ], [_sage_const_0 ,alpha,beta,gamma]])

connection_path = 'research/benincasa/bivariate_soft_gram_connection.json'
with open(connection_path,'rb') as handle:
    connection_bytes = handle.read()
packet = json.loads(connection_bytes)

def parse_matrix(key):
    return matrix(F, [[F(sage_eval(q,locals={'u':u,'v':v})) for q in row]
                      for row in packet[key]])

checks = {}
for name,t,A in [('u',u,parse_matrix('connection_u')),
                 ('v',v,parse_matrix('connection_v'))]:
    # The packet records derivatives of basis masters by rows.  Coefficient
    # columns therefore use the transposed final block.
    A4 = A.matrix_from_rows_and_columns([_sage_const_5 ,_sage_const_6 ,_sage_const_7 ,_sage_const_8 ],[_sage_const_5 ,_sage_const_6 ,_sage_const_7 ,_sage_const_8 ]).transpose()
    E = K.derivative(t) + K*A4
    g00 = E[_sage_const_0 ,_sage_const_0 ]
    g01 = E[_sage_const_0 ,_sage_const_1 ]/alpha
    g10 = E[_sage_const_1 ,_sage_const_0 ]
    g11 = E[_sage_const_1 ,_sage_const_1 ]/alpha
    G = matrix(F, [[g00,g01],[g10,g11]])
    closure = E-G*K
    split_residual = h.derivative(t)+(g00-g11)*h+g10

    assert closure == _sage_const_0 
    assert g01 == _sage_const_0 
    assert g00 == -P6.derivative(t)/(_sage_const_2 *P6)
    assert g11 == D1.derivative(t)/D1
    assert split_residual == _sage_const_0 
    checks[name] = {
        'plane_closure':True,
        'g01_zero':True,
        'g00_minus_half_dlog_P6':True,
        'g11_dlog_D1':True,
        'split_residual_zero':True,
    }

result = {
    'schema':'marici.algebraic-split-characteristic-zero.v1',
    'field':'QQ(u,v)',
    'connection_packet':connection_path,
    'connection_sha256':hashlib.sha256(connection_bytes).hexdigest(),
    'matrix_action':'transpose final 4x4 block for coefficient columns',
    'h':str(factor(h)),
    'checks':checks,
    'status':'exact_characteristic_zero_split',
    'Q_denominator_power':int(_sage_const_0 ),
}

with open('research/nima/algebraic-split-characteristic-zero.json','w') as handle:
    json.dump(result,handle,indent=_sage_const_2 ,sort_keys=True)
    handle.write('\n')

print(json.dumps(result,indent=_sage_const_2 ,sort_keys=True))

