#!/usr/bin/env python3
"""Möbius/d'Alembertian source density of the exact n=8 physical kernel."""
import json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];sys.path.insert(0,str(ROOT/'research/benincasa/.tmp_sympy'));import sympy as s
src=json.loads((ROOT/'research/nima/results/nnmhv-kernel-wall-tail-boundary.json').read_text());K=s.Matrix([[s.sympify(x) for x in row] for row in src['kernel_matrix']]);K0=s.Matrix([[s.sympify(x) for x in row] for row in src['kernel_without_upper_boundary_transport']]);m=3;events=sorted(((i,j) for i in range(1,m+1) for j in range(i,m+1)),key=lambda x:(x[1]-x[0],x[0]));leq=lambda x,y:y[0]<=x[0] and x[1]<=y[1];Z=s.Matrix([[1 if leq(x,y) else 0 for y in events] for x in events]);Mu=Z.inv();f=s.Matrix([K[j-1,i-1] for i,j in events]);f0=s.Matrix([K0[j-1,i-1] for i,j in events]);g=s.simplify(Mu*f);g0=s.simplify(Mu*f0);dg=s.simplify(g-g0)
def records(v):return [{'interval':list(events[k]),'value':str(s.factor(v[k])),'sign':int(s.sign(v[k]))} for k in range(len(events)) if v[k]!=0]
checks={'physical_field_reconstructed_by_causal_zeta':Z*g==f,'unupdated_field_reconstructed_by_causal_zeta':Z*g0==f0,'boundary_source_is_local_bounded_support':sum(v!=0 for v in dg)<=5,'source_change_nonzero':dg!=s.zeros(len(events),1),'field_boundary_change_only_on_simple_roots':all((f-f0)[k]==0 for k,e in enumerate(events) if e[0]!=e[1])}
out={'schema':'marici.nima.nnmhv-physical-kernel-wave-sources.v1','equation':'Box_d f = g and f = Z g','event_order':[list(x) for x in events],'physical_sources':records(g),'sources_without_boundary_transport':records(g0),'boundary_induced_source_change':records(dg),'checks':{k:bool(v) for k,v in checks.items()},'passed':all(bool(v) for v in checks.values()),'meaning':'The exact weighted kernel is a causal zeta/Green field of a unique local Möbius source density. Boundary transport changes both the field and its Möbius source only on simple-root events; these diagonal events are primitive sources for the causal zeta propagator.','bridges':['actual canonical weights as a causal Green field','Möbius source reconstruction','local source versus integrated field','boundary data as primitive simple-root wave sources','exact discrete field equation']};p=ROOT/'research/nima/results/nnmhv-physical-kernel-wave-sources.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2));raise SystemExit(0 if out['passed'] else 1)
