"""Exact trivalent-site falloff audit on a triangle with an attached leaf."""


# This file was *autogenerated* from the file /mnt/c/Users/andrey/src/marici/research/nima/check_lollipop_trivalent_loop_falloff.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_101 = Integer(101); _sage_const_211 = Integer(211); _sage_const_431 = Integer(431); _sage_const_863 = Integer(863); _sage_const_4 = Integer(4)
from itertools import permutations, product


def linear_extensions(vertex_count, relations):
    for order in permutations(range(vertex_count)):
        position = {vertex: index for index, vertex in enumerate(order)}
        if all(position[left] < position[right] for left, right in relations):
            yield order


def ordered_time_integral(energies, order):
    value = _sage_const_1 
    for start in range(len(order)):
        value /= sum(energies[order[index]] for index in range(start, len(order)))
    return value


def graph_integrand(site_energies, edges):
    answer = _sage_const_0 
    for states in product("FRB", repeat=len(edges)):
        energies = list(site_energies)
        relations = []
        coefficient = _sage_const_1 
        for state, (left, right, edge_energy) in zip(states, edges):
            if state == "F":
                relations.append((left, right))
                energies[left] -= edge_energy
                energies[right] += edge_energy
            elif state == "R":
                relations.append((right, left))
                energies[left] += edge_energy
                energies[right] -= edge_energy
            else:
                coefficient *= -_sage_const_1 
                energies[left] += edge_energy
                energies[right] += edge_energy
        for order in linear_extensions(len(site_energies), relations):
            answer += coefficient * ordered_time_integral(energies, order)
    for _, _, edge_energy in edges:
        answer /= _sage_const_2  * edge_energy
    return answer


def main():
    polynomial_ring = PolynomialRing(QQ, "w")
    w = polynomial_ring.fraction_field().gen()
    # Vertex 0 lies on the triangle and carries the attached leaf: valence 3.
    integrand = graph_integrand(
        [w, QQ(_sage_const_3 ), QQ(_sage_const_5 ), QQ(_sage_const_7 )],
        [
            (_sage_const_0 , _sage_const_1 , QQ(_sage_const_101 )),
            (_sage_const_1 , _sage_const_2 , QQ(_sage_const_211 )),
            (_sage_const_2 , _sage_const_0 , QQ(_sage_const_431 )),
            (_sage_const_0 , _sage_const_3 , QQ(_sage_const_863 )),
        ],
    )
    numerator_degree = integrand.numerator().degree()
    denominator_degree = integrand.denominator().degree()
    print("loop-trivalent central degrees:", numerator_degree, denominator_degree)
    assert denominator_degree - numerator_degree == _sage_const_4 
    print("loop-trivalent falloff: PASS")
    print("central falloff: w^-4")


main()

