"""Exact normalization checks for the borderline infinity coefficient."""


# This file was *autogenerated* from the file /mnt/c/Users/andrey/src/marici/research/nima/check_borderline_weight_infinity_residue.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_4 = Integer(4); _sage_const_6 = Integer(6)
from itertools import permutations, product


def linear_extensions(vertex_count, relations):
    for order in permutations(range(vertex_count)):
        position = {vertex: index for index, vertex in enumerate(order)}
        if all(position[left] < position[right] for left, right in relations):
            yield order


def ordered_time_integral(energies, order):
    value = _sage_const_1 
    for start in range(len(order)):
        value /= sum(energies[order[index]] for index in range(start, len(order)))
    return value


def graph_integrand(site_energies, edges):
    answer = _sage_const_0 
    for states in product("FRB", repeat=len(edges)):
        energies = list(site_energies)
        relations = []
        coefficient = _sage_const_1 
        for state, (left, right, edge_energy) in zip(states, edges):
            if state == "F":
                relations.append((left, right))
                energies[left] -= edge_energy
                energies[right] += edge_energy
            elif state == "R":
                relations.append((right, left))
                energies[left] += edge_energy
                energies[right] -= edge_energy
            else:
                coefficient *= -_sage_const_1 
                energies[left] += edge_energy
                energies[right] += edge_energy
        for order in linear_extensions(len(site_energies), relations):
            answer += coefficient * ordered_time_integral(energies, order)
    for _, _, edge_energy in edges:
        answer /= _sage_const_2  * edge_energy
    return answer


def coefficient_at_infinity(rational_function, variable, power):
    numerator = rational_function.numerator()
    denominator = rational_function.denominator()
    assert denominator.degree(variable) - numerator.degree(variable) == power
    numerator_lead = numerator.coefficient({variable: numerator.degree(variable)})
    denominator_lead = denominator.coefficient({variable: denominator.degree(variable)})
    return numerator_lead / denominator_lead


def main():
    ring = PolynomialRing(QQ, names=("w", "x1", "x2", "x3", "y1", "y2", "y3"))
    field = ring.fraction_field()
    w, x1, x2, x3, y1, y2, y3 = map(field, ring.gens())
    w_polynomial = ring.gen(_sage_const_0 )

    bivalent = graph_integrand(
        [w, x1, x2],
        [(_sage_const_0 , _sage_const_1 , y1), (_sage_const_0 , _sage_const_2 , y2)],
    )
    bivalent_coefficient = coefficient_at_infinity(bivalent, w_polynomial, _sage_const_3 )
    bivalent_expected = _sage_const_2  / ((x1+y1)*(x2+y2))
    assert bivalent_coefficient == bivalent_expected
    print("bivalent borderline coefficient:", factor(bivalent_coefficient))

    trivalent = graph_integrand(
        [w, x1, x2, x3],
        [(_sage_const_0 , _sage_const_1 , y1), (_sage_const_0 , _sage_const_2 , y2), (_sage_const_0 , _sage_const_3 , y3)],
    )
    trivalent_coefficient = coefficient_at_infinity(trivalent, w_polynomial, _sage_const_4 )
    trivalent_expected = _sage_const_6  / ((x1+y1)*(x2+y2)*(x3+y3))
    assert trivalent_coefficient == trivalent_expected
    print("trivalent borderline coefficient:", factor(trivalent_coefficient))
    print("borderline infinity normalization: PASS")


main()

