

# This file was *autogenerated* from the file research/nima/check_deep_quartic_local_carriers.sage
from sage.all_cmdline import *   # import sage library

_sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_8 = Integer(8); _sage_const_16 = Integer(16); _sage_const_12 = Integer(12); _sage_const_6 = Integer(6); _sage_const_9 = Integer(9); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_32 = Integer(32)
import json
import hashlib
from sage.misc.sage_eval import sage_eval

R = PolynomialRing(QQ, names=('u', 'v',)); (u, v,) = R._first_ngens(2)
F=R.fraction_field()
Q=-u**_sage_const_4 +_sage_const_4 *u**_sage_const_3 *v-_sage_const_4 *u**_sage_const_3 -_sage_const_4 *u**_sage_const_2 *v+_sage_const_4 *u**_sage_const_2 -_sage_const_8 *u*v-_sage_const_4 *v**_sage_const_2 +_sage_const_16 *u+_sage_const_16 *v-_sage_const_16 
D=-_sage_const_4 +_sage_const_12 *u-_sage_const_6 *u*v+_sage_const_4 *v-_sage_const_9 *u**_sage_const_2 +_sage_const_4 *u**_sage_const_2 *v-v**_sage_const_2 
H=-_sage_const_2 -_sage_const_3 *u+_sage_const_2 *u*v+v-u**_sage_const_2 *v+u**_sage_const_3 

paths=['research/benincasa/bivariate_soft_gram_connection.json',
       'research/benincasa/marked-wall-quotient-connection.json']
packet_bytes=[open(path,'rb').read() for path in paths]
packets=[json.loads(data) for data in packet_bytes]

def parse(x):
    return F(sage_eval(str(x).replace('^','**'),locals={'u':u,'v':v,'D':D,'H':H}))

den=R(_sage_const_1 )
for key in ['connection_u','connection_v']:
    for row in packets[_sage_const_0 ][key]:
        for x in row:
            den=lcm(den,R(parse(x).denominator()))
for axis in ['u','v']:
    for key in ['alpha','beta1','gamma1','beta2','gamma2']:
        den=lcm(den,R(parse(packets[_sage_const_1 ][axis][key]).denominator()))

factors=[R(f) for f,e in factor(den)]

S = PolynomialRing(QQ, names=('x', 'y',)); (x, y,) = S._first_ngens(2)
def initial(poly,u0,v0):
    shifted=S(poly(u=u0+x,v=v0+y))
    degrees=[sum(mon) for mon,c in shifted.dict().items() if c != _sage_const_0 ]
    order=min(degrees)
    form=sum(c*x**mon[_sage_const_0 ]*y**mon[_sage_const_1 ] for mon,c in shifted.dict().items() if sum(mon)==order)
    return order,S(form)

records=[]
for point in [(_sage_const_2 ,_sage_const_2 ),(_sage_const_0 ,_sage_const_2 )]:
    van=[f for f in factors if f(u=point[_sage_const_0 ],v=point[_sage_const_1 ])==_sage_const_0 ]
    q_order,q_initial=initial(Q,*point)
    records.append({
        'point':[int(q) for q in point],
        'vanishing_connection_factors':[str(factor(f)) for f in van],
        'Q_order':int(q_order),
        'Q_initial':str(q_initial),
        'carrier_initials':[{
            'factor':str(factor(f)),
            'order':int(initial(f,*point)[_sage_const_0 ]),
            'initial':str(initial(f,*point)[_sage_const_1 ]),
        } for f in van],
    })

assert records[_sage_const_0 ]['Q_initial'] == '-4*x^2 + 24*x*y - 4*y^2'
assert records[_sage_const_1 ]['Q_initial'] == '-4*x^2 - 8*x*y - 4*y^2'

# In the blowup chart x=r, y=r*t, the first tangent cone cuts the
# exceptional divisor at t^2-6t+1=0.  Its roots are distinct from the
# existing connection directions t=0,1,infinity.  At (0,2), the tangent
# cone is -4(x+y)^2 and hence the doubled existing direction t=-1.
T = PolynomialRing(QQ, names=('t',)); (t,) = T._first_ngens(1)
q22_exceptional=t**_sage_const_2 -_sage_const_6 *t+_sage_const_1 
assert q22_exceptional.discriminant() == _sage_const_32 
assert q22_exceptional(_sage_const_0 ) != _sage_const_0  and q22_exceptional(_sage_const_1 ) != _sage_const_0 
q02_exceptional=(t+_sage_const_1 )**_sage_const_2 

result={
    'schema':'marici.deep-quartic-local-carriers.v1',
    'records':records,
    'blowup':{
        '(2,2)':{
            'Q_exceptional_equation':str(q22_exceptional),
            'Q_exceptional_points':'t=3+-2*sqrt(2)',
            'existing_directions':['t=0 (v-2)','t=1 (u-v)','t=infinity (u-2)'],
            'new_exceptional_direction':True,
        },
        '(0,2)':{
            'Q_exceptional_equation':str(q02_exceptional),
            'Q_exceptional_point':'t=-1 with multiplicity two',
            'existing_direction':'u+v-2 has initial x+y and the same t=-1 point',
            'new_exceptional_direction':False,
        },
    },
    'connection_factor_count':int(len(factors)),
    'source_hashes':{path:hashlib.sha256(data).hexdigest()
                     for path,data in zip(paths,packet_bytes)},
    'status':'deep_quartic_tangent_directions_classified',
    'scope':'carrier and tangent-cone classification only; no coefficient or physical activation claimed',
}

with open('research/nima/deep-quartic-local-carriers.json','w') as handle:
    json.dump(result,handle,indent=_sage_const_2 ,sort_keys=True)
    handle.write('\n')

print(json.dumps(result,indent=_sage_const_2 ,sort_keys=True))

