"""Exact univariate audit of the four-insertion terminal asymptotic."""


# This file was *autogenerated* from the file /mnt/c/Users/andrey/src/marici/research/nima/check_four_mass_insertion_terminal_asymptotic.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_11 = Integer(11); _sage_const_23 = Integer(23); _sage_const_17 = Integer(17); _sage_const_10 = Integer(10)
from itertools import permutations, product


def linear_extensions(vertex_count, relations):
    for order in permutations(range(vertex_count)):
        position = {vertex: index for index, vertex in enumerate(order)}
        if all(position[left] < position[right] for left, right in relations):
            yield order


def ordered_time_integral(energies, order):
    value = _sage_const_1 
    for start in range(len(order)):
        value /= sum(energies[order[index]] for index in range(start, len(order)))
    return value


def path_integrand(site_energies, edge_energy):
    edge_count = len(site_energies) - _sage_const_1 
    answer = _sage_const_0 
    for states in product("FRB", repeat=edge_count):
        energies = list(site_energies)
        relations = []
        coefficient = _sage_const_1 
        for left, state in enumerate(states):
            right = left + _sage_const_1 
            if state == "F":
                relations.append((left, right))
                energies[left] -= edge_energy
                energies[right] += edge_energy
            elif state == "R":
                relations.append((right, left))
                energies[left] += edge_energy
                energies[right] -= edge_energy
            else:
                coefficient *= -_sage_const_1 
                energies[left] += edge_energy
                energies[right] += edge_energy
        for order in linear_extensions(len(site_energies), relations):
            answer += coefficient * ordered_time_integral(energies, order)
    answer /= (_sage_const_2  * edge_energy) ** edge_count
    return answer


def main():
    polynomial_ring = PolynomialRing(QQ, "w4")
    w4 = polynomial_ring.fraction_field().gen()
    # Distinct positive primes avoid accidental collisions among interval sums.
    integrand = path_integrand([_sage_const_3 , _sage_const_5 , _sage_const_7 , _sage_const_11 , w4, _sage_const_23 ], QQ(_sage_const_17 ))
    numerator_degree = integrand.numerator().degree()
    denominator_degree = integrand.denominator().degree()
    print("observed terminal degrees:", numerator_degree, denominator_degree)
    assert (numerator_degree, denominator_degree) == (_sage_const_7 , _sage_const_10 )
    assert denominator_degree - numerator_degree == _sage_const_3 
    weighted = w4 * integrand
    assert weighted.denominator().degree() - weighted.numerator().degree() == _sage_const_2 
    print("four-insertion exact univariate derivation: PASS")
    print("terminal degrees:", numerator_degree, denominator_degree)
    print("unweighted terminal falloff: w4^-3")
    print("weighted terminal residue at infinity: zero")


main()

