#!/usr/bin/env python3
"""Detect whether the globally resummed theta route supplies a non-RH-equivalent intermediate theorem."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
paths={'outer':'research/grothendieck/theta-full-source-outer-diagonal-loewner-theorem.md','spread':'research/grothendieck/stieltjes-atoms-saturate-and-mixtures-improve-the-schwarzian-spread-bound.md','heat':'research/grothendieck/the-angular-bernstein-measure-is-the-differentiated-xi-heat-trace.md','remainder':'research/grothendieck/completed-bridge-identifies-the-remainder-cone-as-the-rh-content.md','block':'research/grothendieck/theta-physical-port-high-frequency-reduction.md'}
T={k:(ROOT/v).read_text(encoding='utf-8') for k,v in paths.items()}
checks={'outer_diagonal_source_theorem_proved':'H\'(x)>0' in T['outer'],'rank_two_reduces_to_stieltjes':'Once `S` is Stieltjes' in T['spread'],'spread_not_independent':'not an independent arithmetic gate' in T['spread'],'bernstein_is_xi_heat_trace':'not a second spectral object' in T['heat'],'positive_measure_gate_RH_strength':'RH-strength' in T['heat'],'all_rank_remainder_is_RH_content':'would prove RH' in T['remainder'],'two_band_mechanism_falsified':'physically coupled one-block mechanism is falsified' in T['block']}
out={'schema':'marici.nima.global-theta-resummation-frontier-cycle.v1','checks':checks,'passed':all(checks.values()),'proved_nontrivial_source_result':'outer positive-real diagonal Loewner positivity Hprime(x)>0 for x>1/4','closed_side_routes':['canonical two-band transport','independent conditional-spread theorem','abstract GNS/RKHS refactorization'],'cycle':'global rank-two/all-rank positivity -> positive Stieltjes measure -> positive Xi heat trace -> global Weil positivity','disposition':'the cycle returns to the RH-bearing source positivity gate; it is not a new intermediate lemma','nonredundant_reopening_condition':'an independently positive source factor or comparison law not defined from Xi zeros or the target kernel','rh_proved':False}
p=ROOT/'research/nima/results/global-theta-resummation-frontier-cycle.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2));raise SystemExit(0 if out['passed'] else 1)
