#!/usr/bin/env python3
"""Aggregate certificate for completed arbitrary-length typed word representation."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];R=ROOT/'research/nima/results'
files={'typing':'eight-axis-repeated-typing-automaton.json','history':'eight-axis-typed-path-representation.json','closability':'arithmetic-joint-closability.json','H_stability':'rooted-convolution-lo-graph-stability.json','V_stability':'physical-cut-lo-graph-stability.json','q_stability':'qdlo-leakage-transport.json','polarity':'homeomorphism-candidate-polarity.json','completion':'lax-eighth-completion-coherencer.json'}
d={k:json.loads((R/f).read_text()) for k,f in files.items()}
checks={'all_dependencies_pass':all(x['passed'] for x in d.values()),'partial_action_composes':d['typing']['checks']['partial_action_composition_law'],'history_representation_faithful':d['history']['checks']['all_maximal_histories_unique'],'finite_dependency_families_jointly_closable':d['closability']['checks']['all_vertical_limits_forced_zero'],'H_preserves_graph':d['H_stability']['passed'],'V_preserves_graph':d['V_stability']['passed'],'q_lax_cell_coherent':d['q_stability']['passed'],'D_realification_available':d['polarity']['checks']['dagger_involutive'],'completion_coherencer_available':d['completion']['lax_eighth_coherencer_constructed']}
out={'schema':'marici.nima.completed-typed-word-representation.v1','statement':'Every finite typed word in H,V,D,q,L,C,O,R has a continuous partial real-linear graph-homomorphism on its finite joint graph domain; all words assemble coordinatewise on the projective history-graph carrier.','files':files,'checks':checks,'passed':all(checks.values()),'representation_kind':'pro-locally-convex history-Fock graph 2-representation','untyped_words':'zero/empty typed fiber','route_relations':'retained as declared 2-cells, including nonzero q-R leakage','nonclaims':['one uniform Hilbert norm for all words','all typed word operators invertible','nonzero realization for every formal source label','native historical inverse topology']}
p=R/'completed-typed-word-representation.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2));raise SystemExit(0 if out['passed'] else 1)
