"""Exhaustive exact site-energy falloff audit for small connected graphs."""


# This file was *autogenerated* from the file /mnt/c/Users/andrey/src/marici/research/nima/check_all_small_graph_site_falloff.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_11 = Integer(11); _sage_const_101 = Integer(101); _sage_const_211 = Integer(211); _sage_const_431 = Integer(431); _sage_const_863 = Integer(863); _sage_const_1733 = Integer(1733); _sage_const_3469 = Integer(3469); _sage_const_4 = Integer(4)
from itertools import permutations, product
import networkx as nx


def linear_extensions(vertex_count, relations):
    for order in permutations(range(vertex_count)):
        position = {vertex: index for index, vertex in enumerate(order)}
        if all(position[left] < position[right] for left, right in relations):
            yield order


def ordered_time_integral(energies, order):
    value = _sage_const_1 
    for start in range(len(order)):
        value /= sum(energies[order[index]] for index in range(start, len(order)))
    return value


def graph_integrand(site_energies, edges):
    answer = _sage_const_0 
    for states in product("FRB", repeat=len(edges)):
        energies = list(site_energies)
        relations = []
        coefficient = _sage_const_1 
        for state, (left, right, edge_energy) in zip(states, edges):
            if state == "F":
                relations.append((left, right))
                energies[left] -= edge_energy
                energies[right] += edge_energy
            elif state == "R":
                relations.append((right, left))
                energies[left] += edge_energy
                energies[right] -= edge_energy
            else:
                coefficient *= -_sage_const_1 
                energies[left] += edge_energy
                energies[right] += edge_energy
        for order in linear_extensions(len(site_energies), relations):
            answer += coefficient * ordered_time_integral(energies, order)
    for _, _, edge_energy in edges:
        answer /= _sage_const_2  * edge_energy
    return answer


def main():
    polynomial_ring = PolynomialRing(QQ, "z")
    z = polynomial_ring.fraction_field().gen()
    site_constants = [QQ(_sage_const_3 ), QQ(_sage_const_5 ), QQ(_sage_const_7 ), QQ(_sage_const_11 )]
    edge_constants = [QQ(_sage_const_101 ), QQ(_sage_const_211 ), QQ(_sage_const_431 ), QQ(_sage_const_863 ), QQ(_sage_const_1733 ), QQ(_sage_const_3469 )]

    graphs = [
        graph for graph in nx.graph_atlas_g()
        if _sage_const_2  <= graph.number_of_nodes() <= _sage_const_4  and nx.is_connected(graph)
    ]
    graph_count = _sage_const_0 
    vertex_count = _sage_const_0 
    for graph in graphs:
        graph = nx.convert_node_labels_to_integers(graph)
        edge_pairs = sorted(tuple(sorted(edge)) for edge in graph.edges())
        edges = [
            (left, right, edge_constants[index])
            for index, (left, right) in enumerate(edge_pairs)
        ]
        graph_count += _sage_const_1 
        for distinguished in graph.nodes():
            sites = list(site_constants[: graph.number_of_nodes()])
            sites[distinguished] = z
            integrand = graph_integrand(sites, edges)
            gap = integrand.denominator().degree() - integrand.numerator().degree()
            expected = graph.degree(distinguished) + _sage_const_1 
            assert gap == expected, (
                graph.number_of_nodes(),
                edge_pairs,
                distinguished,
                gap,
                expected,
            )
            vertex_count += _sage_const_1 
        print(
            "PASS graph",
            graph.number_of_nodes(),
            edge_pairs,
            "degrees",
            sorted(dict(graph.degree()).values()),
        )

    print("small-graph census: PASS")
    print("connected unlabeled graphs:", graph_count)
    print("distinguished vertices:", vertex_count)


main()

