#!/usr/bin/env python3
"""Schur-complement/renormalization interpretation of boundary-induced coherence."""
import json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];sys.path.insert(0,str(ROOT/'research/benincasa/.tmp_sympy'));import sympy as s
src=json.loads((ROOT/'research/nima/results/nnmhv-kernel-wall-tail-boundary.json').read_text());K=s.Matrix([[s.sympify(x) for x in row] for row in src['kernel_matrix']]);K0=s.Matrix([[s.sympify(x) for x in row] for row in src['kernel_without_upper_boundary_transport']]);
def effective(A):return s.factor(A[2,0]-A[2,1]*A[1,0]/A[1,1])
e=effective(K);e0=effective(K0);direct=K[2,0];mediated=s.factor(K[2,1]*K[1,0]/K[1,1]);direct0=K0[2,0];mediated0=s.factor(K0[2,1]*K0[1,0]/K0[1,1]);checks={'unupdated_effective_coupling_negative':s.sign(e0)==-1,'updated_effective_coupling_positive':s.sign(e)==1,'boundary_transport_flips_schur_coupling':s.sign(e0)!=s.sign(e),'updated_direct_exceeds_mediated':direct>mediated,'unupdated_direct_below_mediated':direct0<mediated0,'inverse_relation':s.factor(K.inv()[2,0]+e/(K[0,0]*K[2,2]))==0}
out={'schema':'marici.nima.nnmhv-schur-reflow-bridge.v1','decimation':'eliminate middle endpoint b=6','effective_coupling':'K_eff(7,5)=K(7,5)-K(7,6)K(6,5)/K(6,6)','without_boundary':{'direct':str(direct0),'mediated':str(mediated0),'effective':str(e0),'sign':'negative'},'with_boundary':{'direct':str(direct),'mediated':str(mediated),'effective':str(e),'sign':'positive'},'checks':{k:bool(v) for k,v in checks.items()},'passed':all(bool(v) for v in checks.values()),'meaning':'Reflow as elimination of the intermediate endpoint is a Schur complement. Boundary transport changes whether mediated transfer exceeds direct transfer and reverses the renormalized long-range coupling.','bridges':['Schur-complement decimation','real-space renormalization','integrating out an intermediate channel','direct-minus-mediated effective interaction','reflow as coarse-graining']};p=ROOT/'research/nima/results/nnmhv-schur-reflow-bridge.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2));raise SystemExit(0 if out['passed'] else 1)
