#!/usr/bin/env python3
"""Uniform-vector readout and Born quadratic form of a selected shell row."""
import json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];sys.path.insert(0,str(ROOT/'research/benincasa/.tmp_sympy'));import sympy as s
rows=[]
for r in range(1,7):
 w=s.symbols('w0:'+str(r),complex=True);wb=s.symbols('wb0:'+str(r),complex=True);W=s.Matrix([list(w)]);Wd=s.Matrix([[x] for x in wb]);u=s.ones(r,1);rho=Wd*W;augmentation=(W*u)[0];conj_aug=(s.Matrix([list(wb)])*u)[0];born=s.expand(augmentation*conj_aug);diag=sum(w[i]*wb[i] for i in range(r));interference=s.expand(born-diag);projector=u*u.T/s.Integer(r);trace_readout=s.expand(s.trace(rho*projector));checks={'augmentation_is_uniform_amplitude':augmentation==sum(w),'density_is_outer_product':rho==Wd*W,'trace_is_hilbert_norm':s.trace(rho)==diag,'normalized_born_readout':s.factor(trace_readout-born/r)==0,'interference_is_off_diagonal':s.factor(interference-sum(w[i]*wb[j] for i in range(r) for j in range(r) if i!=j))==0};rows.append({'r':r,'augmentation':str(augmentation),'hilbert_norm':str(diag),'born_readout':str(born),'interference_terms':r*(r-1),'checks':checks})
allchecks={'all_uniform_readouts_exact':all(all(x['checks'].values()) for x in rows),'born_contains_interference_for_r_gt_one':all(x['interference_terms']>0 for x in rows if x['r']>1),'one_dimensional_seed_has_no_interference':rows[0]['interference_terms']==0}
out={'schema':'marici.nima.nnmhv-augmentation-uniform-quantum-readout.v1','module':'psi = sum_q w_q E_(3,q) in e A_r','linear_readout':'epsilon(psi) = sum_q w_q = psi |1>','density_operator':'rho = psi^dagger psi','normalized_detector':'P_+ = |1><1|/r','quadratic_readout':'Tr(rho P_+) = |sum_q w_q|^2/r','rows':rows,'checks':allchecks,'passed':all(allchecks.values()),'meaning':'History augmentation is a coherent uniform-mode amplitude. Squaring after summation preserves off-diagonal interference; summing squared history weights would destroy it.','claim_boundary':'This establishes the algebraic Born form of the existing augmentation. It does not establish that this detector is the unique physical measurement or that the history weights are normalized.'};p=ROOT/'research/nima/results/nnmhv-augmentation-uniform-quantum-readout.json';p.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'schema':out['schema'],'linear_readout':out['linear_readout'],'quadratic_readout':out['quadratic_readout'],'checks':allchecks,'meaning':out['meaning'],'passed':out['passed']},indent=2));raise SystemExit(0 if out['passed'] else 1)
