

# This file was *autogenerated* from the file research/nima/check_quartic_intersection_indicial_excess.sage
from sage.all_cmdline import *   # import sage library

_sage_const_4 = Integer(4); _sage_const_12 = Integer(12); _sage_const_6 = Integer(6); _sage_const_9 = Integer(9); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_18 = Integer(18)
import json
import hashlib
from sage.misc.sage_eval import sage_eval

R = PolynomialRing(QQ, names=('u', 'v',)); (u, v,) = R._first_ngens(2)
F = R.fraction_field()
D = -_sage_const_4 +_sage_const_12 *u-_sage_const_6 *u*v+_sage_const_4 *v-_sage_const_9 *u**_sage_const_2 +_sage_const_4 *u**_sage_const_2 *v-v**_sage_const_2 
H = -_sage_const_2 -_sage_const_3 *u+_sage_const_2 *u*v+v-u**_sage_const_2 *v+u**_sage_const_3 

a9_path = 'research/benincasa/bivariate_soft_gram_connection.json'
a3_path = 'research/benincasa/marked-wall-quotient-connection.json'
a9_bytes = open(a9_path,'rb').read()
a3_bytes = open(a3_path,'rb').read()
a9 = json.loads(a9_bytes)
a3 = json.loads(a3_bytes)

def parse(x):
    if isinstance(x,(int,Integer)):
        return F(x)
    return F(sage_eval(str(x).replace('^','**'),locals={'u':u,'v':v,'D':D,'H':H}))

def A3(axis):
    z=F(_sage_const_0 ); d=a3[axis]
    return matrix(F,[[parse(d['alpha']),z,z],
                     [parse(d['beta1']),parse(d['gamma1']),z],
                     [parse(d['beta2']),z,parse(d['gamma2'])]])

A9v = matrix(F,[[parse(x) for x in row] for row in a9['connection_v']])
A3v = A3('v')

# Work over QQ(u), adjoining a generic root of each carrier equation in v.
Ru = PolynomialRing(QQ, names=('uu',)); (uu,) = Ru._first_ngens(1)
Ku = Ru.fraction_field()
Pv = PolynomialRing(Ku, names=('vv',)); (vv,) = Pv._first_ngens(1)

def to_pv(poly):
    p=R(poly)
    return Pv(sum(Ku(Ru(c))*vv**j for (i,j),c in p.dict().items()
                  for _ in [None] if i == _sage_const_0 )) if p.degree(u) == _sage_const_0  else Pv(p(u=uu,v=vv))

def map_fraction(z,K,root):
    return K(z.numerator()(u=uu,v=root))/K(z.denominator()(u=uu,v=root))

def generic_residue(carrier,label):
    carrier_p = Pv(carrier(u=uu,v=vv))
    K = Pv.quotient(carrier_p, names=('root',)); (root,) = K._first_ngens(1)
    dv = F(carrier.derivative(v))
    def residue_matrix(A):
        entries=[]
        for z in A.list():
            normal = F(carrier)*z/dv
            entries.append(map_fraction(normal,K,root))
        return matrix(K,A.nrows(),A.ncols(),entries)
    R9=residue_matrix(A9v)
    R3=residue_matrix(A3v)
    Hom=identity_matrix(K,_sage_const_3 ).tensor_product(R9)-R3.transpose().tensor_product(identity_matrix(K,_sage_const_9 ))
    cp9=R9.charpoly(); x9=cp9.parent().gen()
    cp3=R3.charpoly(); x3=cp3.parent().gen()
    cph=Hom.charpoly(); xh=cph.parent().gen()
    assert cp9 == x9**_sage_const_9 
    assert cp3 == x3**_sage_const_2 *(x3+K(_sage_const_1 )/_sage_const_2 )
    assert cph == xh**_sage_const_18 *(xh-K(_sage_const_1 )/_sage_const_2 )**_sage_const_9 
    return {
        'carrier':label,
        'R9_charpoly':'x^9',
        'R3_charpoly':'x^2*(x+1/2)',
        'Hom_charpoly':'x^18*(x-1/2)^9',
    }

records=[generic_residue(D,'D'),generic_residue(H,'H')]
result={
    'schema':'marici.quartic-intersection-indicial-excess.v1',
    'field':'generic carrier function fields over QQ(u)',
    'records':records,
    'intersection_spectra':'Entry 864: same R9, R3, and Hom characteristic polynomials at Q intersect D and Q intersect H',
    'spectral_excess_at_tested_Q_intersections':False,
    'scope':'generic D/H spectra compared with the exact representative Q intersections; no claim about deeper soft intersections',
    'source_hashes':{
        a9_path:hashlib.sha256(a9_bytes).hexdigest(),
        a3_path:hashlib.sha256(a3_bytes).hexdigest(),
    },
    'status':'no_indicial_spectral_jump',
}

with open('research/nima/quartic-intersection-indicial-excess.json','w') as handle:
    json.dump(result,handle,indent=_sage_const_2 ,sort_keys=True)
    handle.write('\n')

print(json.dumps(result,indent=_sage_const_2 ,sort_keys=True))

