

# This file was *autogenerated* from the file research/nima/check_marked_candidate_algebraic_kernel.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_7 = Integer(7); _sage_const_8 = Integer(8); _sage_const_16 = Integer(16)
import json
import hashlib

R = PolynomialRing(QQ, names=('u', 'v',)); (u, v,) = R._first_ngens(2)
F = R.fraction_field()

def mons(d):
    return [(i,s-i) for s in range(d+_sage_const_1 ) for i in range(s+_sage_const_1 )]

def polynomial(coefficients,degree):
    return R(sum(QQ(c)*u**i*v**j
                 for c,(i,j) in zip(coefficients,mons(degree))))

candidate_path='research/benincasa/marked-extension-charzero-candidate.json'
with open(candidate_path,'rb') as handle:
    candidate_bytes=handle.read()
candidate=json.loads(candidate_bytes)

B={axis:matrix(F,_sage_const_4 ,_sage_const_3 ) for axis in ['u','v']}
for entry in candidate['entries']:
    numerator=polynomial(entry['numerator'],entry['numerator_degree'])
    denominator=polynomial(entry['denominator'],entry['denominator_degree'])
    B[entry['axis']][entry['row'],entry['column']]=F(numerator)/F(denominator)

y=(u+v)/_sage_const_2 -_sage_const_1 
G=matrix(F,[[_sage_const_0 ,_sage_const_1 ,(u**_sage_const_2 +y**_sage_const_2 )/_sage_const_2 ,(u**_sage_const_2 +_sage_const_1 )/_sage_const_2 ],
            [_sage_const_0 ,_sage_const_0 ,-(u**_sage_const_2 +_sage_const_1 )/_sage_const_2 ,-(u**_sage_const_2 +y**_sage_const_2 )/(_sage_const_2 *y**_sage_const_2 )]])
P6=_sage_const_1 -u-v+v**_sage_const_2 /_sage_const_4 +u*v/_sage_const_2 -_sage_const_7 *u**_sage_const_2 /_sage_const_4 +u**_sage_const_2 *v+u**_sage_const_3 -u**_sage_const_3 *v+u**_sage_const_4 
h=u*(u+v)*(u+v-_sage_const_4 )*P6/_sage_const_4 
alpha=(_sage_const_1 -y**_sage_const_2 )*(y**_sage_const_2 -u**_sage_const_4 )
Q=-u**_sage_const_4 +_sage_const_4 *u**_sage_const_3 *v-_sage_const_4 *u**_sage_const_3 -_sage_const_4 *u**_sage_const_2 *v+_sage_const_4 *u**_sage_const_2 -_sage_const_8 *u*v-_sage_const_4 *v**_sage_const_2 +_sage_const_16 *u+_sage_const_16 *v-_sage_const_16 

checks={}
for axis in ['u','v']:
    gysin=G*B[axis]
    quotient=matrix(F,_sage_const_1 ,_sage_const_3 ,[B[axis][_sage_const_1 ,c]/alpha for c in range(_sage_const_3 )])
    e6_split=matrix(F,_sage_const_1 ,_sage_const_3 ,[B[axis][_sage_const_0 ,c]-h*quotient[_sage_const_0 ,c]
                            for c in range(_sage_const_3 )])
    assert all(z==_sage_const_0  for z in gysin.list())
    assert all(z!=_sage_const_0  for z in quotient.list())
    assert all(z!=_sage_const_0  for z in e6_split.list())
    assert all(gcd(R(z.denominator()),Q)==_sage_const_1  for z in B[axis].list())
    checks[axis]={
        'gysin_zero_entries':int(sum(z==_sage_const_0  for z in gysin.list())),
        'gysin_total_entries':int(len(gysin.list())),
        'quotient_nonzero_components':int(sum(z!=_sage_const_0  for z in quotient.list())),
        'e6_split_nonzero_components':int(sum(z!=_sage_const_0  for z in e6_split.list())),
        'Q_denominator_entries':int(sum(gcd(R(z.denominator()),Q)!=_sage_const_1 
                                        for z in B[axis].list())),
    }

result={
    'schema':'marici.marked-candidate-algebraic-kernel.v1',
    'candidate_path':candidate_path,
    'candidate_sha256':hashlib.sha256(candidate_bytes).hexdigest(),
    'candidate_certification_status':candidate['certification_status'],
    'checks':checks,
    'interpretation':'candidate image lies in the full split algebraic plane, with nonzero components on both lines and no Q denominator',
    'source_identity_certified':False,
}

with open('research/nima/marked-candidate-algebraic-kernel.json','w') as handle:
    json.dump(result,handle,indent=_sage_const_2 ,sort_keys=True)
    handle.write('\n')

print(json.dumps(result,indent=_sage_const_2 ,sort_keys=True))

