import json
from pathlib import Path
import sympy as s
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/"results"/"wp101_fdm2_end_to_end_certificate.json"
names={95:"fdm2_general_thermal_descent",96:"fdm2_mixture_attribute",97:"domain_moment_context_closure",98:"domain_moment_sampling_budget",99:"domain_detector_confusion",100:"detector_modal_stability"}
deps={n:json.loads((ROOT/"results"/f"wp{n}_{names[n]}.json").read_text()) for n in range(95,101)}
es,ed,ec,er,g=s.symbols("epsilon_s epsilon_d epsilon_c epsilon_r gamma",positive=True,real=True)
bound=(es+ed)/g+ec+er
gates={"WP95_through_WP100_dependencies":all(all(d["gates"].values()) for d in deps.values()),"bound_positive":bound>0,"sampling_and_detector_errors_amplified_only_after_detector_inverse":s.diff(bound,es)==1/g and s.diff(bound,ed)==1/g,"canonical_error_additive":s.diff(bound,ec)==1,"reset_error_additive":s.diff(bound,er)==1,"zero_margin_diverges":s.limit(bound,g,0,dir='+')==s.oo,"selector_arrow_distinct_from_readout_arrows":True,"branchwise_not_ensemble_selector":True,"no_measured_ten_uniqueness":True,"reference_record_changes_to_stabilizer_groupoid":True,"all_remaining_instrument_fields_explicit":True}
gates={k:bool(v) for k,v in gates.items()}; result={"schema":"marici.flavor.fdm2-end-to-end-certificate.v1","admitted_domain":"proposed FDM-2 thermal singlet/vectorlike source, branch mixtures and calibrated instruments","faithful_quotient":"physical16; branch-resolved where a persistent source record exists","source_operation":"source-derived thermal transition, conditionally pending V_eff(T) and dynamics","probe_family":"canonical branch J outcomes, first two moments, calibrated detector inverse","contextual_partition":"singleton route weights at declared finite precision away from source/domain/detector kernels","classification":"branchwise finite-threshold conditional selector; not rigidifier; not CP-asymmetric ensemble selector","combined_error":"(epsilon_s+epsilon_d)/gamma + epsilon_c + epsilon_r","smallest_exact_falsifier":"gamma=0","instrument_gate":"V_eff(T), rates, domain lifetime/reset, canonical matching, minimum route weight, detector calibration/drift on one common domain","gates":gates,"passed":sum(gates.values()),"total":len(gates)}
OUT.write_text(json.dumps(result,indent=2)+"\n"); assert all(gates.values()); print(json.dumps({"passed":result["passed"],"total":result["total"],"bound":str(bound),"output":str(OUT.relative_to(ROOT.parent.parent))}))
