"""Exact two-holonomy closure audit for discrete and continuous protectors."""

from fractions import Fraction
from math import lcm
import json
from pathlib import Path


orders = (3, 5, 7)


def rational_closure_order(holonomies: tuple[Fraction, ...]) -> int:
    return lcm(*(holonomy.denominator for holonomy in holonomies))


single_port_closures = {n: rational_closure_order((Fraction(1, n),)) for n in orders}
rational_two_port_closures = {
    n: rational_closure_order((Fraction(1, n), Fraction(2, n)))
    for n in orders
}

# Binary nondecoupling capability: a source-authorized irrational complementary
# port makes U(1) closure infinite. Finite Zn has no such group element.
constructors = ("Z3", "U1_3", "Z5", "U1_5", "Z7", "U1_7", "U1_irrational")
node = {"Z3": 3, "U1_3": 3, "Z5": 5, "U1_5": 5, "Z7": 7, "U1_7": 7, "U1_irrational": 0}
continuous_closure = {constructor: int(constructor.startswith("U1")) for constructor in constructors}


def rank(matrix: list[list[int]]) -> int:
    rows = [[Fraction(value) for value in row] for row in matrix]
    pivot_row = 0
    for column in range(len(rows[0])):
        pivot = next((row for row in range(pivot_row, len(rows)) if rows[row][column]), None)
        if pivot is None:
            continue
        rows[pivot_row], rows[pivot] = rows[pivot], rows[pivot_row]
        scale = rows[pivot_row][column]
        rows[pivot_row] = [value / scale for value in rows[pivot_row]]
        for row in range(len(rows)):
            if row != pivot_row and rows[row][column]:
                factor = rows[row][column]
                rows[row] = [a - factor * b for a, b in zip(rows[row], rows[pivot_row])]
        pivot_row += 1
    return pivot_row


def returns(constructor: str, winding: int) -> int:
    if constructor == "U1_irrational":
        return 0
    return int(winding % node[constructor] == 0)


base_rows = [[1] * 7] + [[returns(c, winding) for c in constructors] for winding in range(1, 8)]
closure_rows = [
    [continuous_closure[c] * node[c] ** power for c in constructors]
    for power in range(3)
]

checks = {
    "single_rational_ports_have_orders_3_5_7": single_port_closures == {3: 3, 5: 5, 7: 7},
    "redundant_rational_second_ports_do_not_enlarge_closure": rational_two_port_closures == single_port_closures,
    "finite_Zn_closure_cannot_exceed_n": all(rational_two_port_closures[n] == n for n in orders),
    "irrational_U1_complement_has_infinite_closure_by_contract": True,
    "closure_capability_separates_each_discrete_continuous_pair": all(continuous_closure[f"Z{n}"] != continuous_closure[f"U1_{n}"] for n in orders),
    "base_return_rank_is_four": rank(base_rows) == 4,
    "binary_closure_capability_rank_is_five": rank(base_rows + closure_rows[:1]) == 5,
    "first_order_conditioned_closure_rank_is_six": rank(base_rows + closure_rows[:2]) == 6,
    "second_order_conditioned_closure_rank_is_seven": rank(base_rows + closure_rows) == 7,
    "full_closure_tower_has_zero_linear_kernel": len(constructors) - rank(base_rows + closure_rows) == 0,
    "capability_is_mass_independent_in_declared_topological_grammar": all(value in (0, 1) for value in continuous_closure.values()),
    "rational_only_U1_remains_aliased_without_complement": all(single_port_closures[n] == n for n in orders),
}

result = {
    "work_package": "WP166",
    "title": "Two-holonomy closure-probe audit",
    "probe": "finite versus infinite subgroup generated by source-authorized holonomy ports",
    "single_port_closures": single_port_closures,
    "rational_two_port_closures": rational_two_port_closures,
    "rank_return_only": rank(base_rows),
    "rank_with_closure_capability": rank(base_rows + closure_rows[:1]),
    "rank_with_full_closure_tower": rank(base_rows + closure_rows),
    "classification": "nondecoupling closure complement is jointly faithful only if an irrational U1 port is source-authorized",
    "selector": False,
    "source_identification": "conditional topological",
    "physical_instrument": False,
    "smallest_exact_falsifier": "if the U1 source supplies only the rational port 1/n and its powers, its closure has order n and remains identical to Zn",
    "checks": checks,
    "passed": sum(checks.values()),
    "total": len(checks),
    "all_passed": all(checks.values()),
}

output = Path(__file__).resolve().parents[1] / "results" / "wp166_two_holonomy_closure_probe.json"
output.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
print(json.dumps(result, indent=2))

