"""WP353: exact CP response of a continuous complex-projector deformation."""

import json
import math
from pathlib import Path

import sympy as sp

ROOT = Path(__file__).resolve().parents[1]


def main():
    t = sp.symbols("t", real=True)
    spectral = sp.symbols("lambda")
    identity = sp.eye(3)
    p = sp.diag(1, 0, 0)
    q = sp.Matrix([[sp.Rational(1, 2), sp.Rational(1, 2), 0],
                   [sp.Rational(1, 2), sp.Rational(1, 2), 0],
                   [0, 0, 0]])
    vector_r = sp.Matrix([1, sp.I * t, 1])
    r = sp.simplify(vector_r * vector_r.conjugate().T / (2 + t**2))
    democratic = sp.simplify(p + q + r)
    odd = sp.simplify(p - q)
    hu = sp.simplify((identity + democratic) ** 2)
    hd = sp.simplify((2 * identity + odd) ** 2)
    commutator = sp.simplify(hu * hd - hd * hu)
    cp_trace = sp.factor(sp.trace(commutator**3))
    up_discriminant = sp.factor(sp.discriminant(hu.charpoly(spectral).as_expr(), spectral))
    down_discriminant = sp.factor(sp.discriminant(hd.charpoly(spectral).as_expr(), spectral))
    jarlskog_squared = sp.factor(-cp_trace**2 / (36 * up_discriminant * down_discriminant))
    response_at_one = sp.factor(sp.diff(jarlskog_squared, t).subs(t, 1))
    leading_small_t = sp.limit(jarlskog_squared / t**2, t, 0)
    ensemble = json.loads((ROOT / "results/wp20_valley_audit.json").read_text(encoding="utf-8"))
    maximum_fitted_j_squared = max(float(record["J"]) ** 2 for record in ensemble["records"])
    small_branch_estimate = math.sqrt(34 * maximum_fitted_j_squared)
    checks = {
        "deformed_r_is_rank_one_projector": sp.simplify(r**2 - r) == sp.zeros(3) and r.rank() == 1,
        "real_geometry_is_cp_conserving": jarlskog_squared.subs(t, 0) == 0,
        "wp351_geometry_is_recovered": jarlskog_squared.subs(t, 1) == sp.Rational(1, 543),
        "normalized_cp_responds_to_geometry": response_at_one == -sp.Rational(716, 294849),
        "small_deformation_has_quadratic_cp_law": leading_small_t == sp.Rational(1, 34),
        "fitted_scale_requires_small_deformation_branch": small_branch_estimate < 0.001,
        "complex_conjugate_deformations_share_j_squared": sp.simplify(jarlskog_squared.subs(t, -t) - jarlskog_squared) == 0,
    }
    checks = {name: bool(value) for name, value in checks.items()}
    result = {
        "work_package": "WP353",
        "admitted_state_domain": "the WP350 ray geometry with R generated by the normalized complex ray (1,i*t,1), including real t and excluding spectral-degeneracy roots when normalized invariants are used",
        "faithful_quotient_coordinate": "the normalized CP invariant J^2 as a function of the source geometry parameter t",
        "source_operation": "continuously deform the imaginary component of the third projector ray while keeping the sector-character coefficient directions fixed",
        "cp_trace": str(cp_trace),
        "up_discriminant": str(up_discriminant),
        "down_discriminant": str(down_discriminant),
        "jarlskog_squared": str(jarlskog_squared),
        "response_at_t_equals_one": str(response_at_one),
        "small_t_limit_of_J2_over_t2": str(leading_small_t),
        "maximum_fitted_J_squared": maximum_fitted_j_squared,
        "leading_small_branch_t_estimate": small_branch_estimate,
        "contextual_partition": "J^2 identifies t only up to sign and potentially multiple radial branches; t and -t are complex-conjugate geometries",
        "classification": "a continuous CP-capability deformation, not a selector; fitting t to the ensemble moves numerical authority into the projector geometry",
        "smallest_exact_falsifier": "t=0 gives J^2=0 and t=1 gives J^2=1/543 within the same admitted grammar, with nonzero response at t=1",
        "remaining_physical_instrument_gate": "derive a discrete or stationary value of t from a source action before reading J, prove descent and stability, and then test the resulting branch on the complete ensemble",
        "checks": checks,
        "passed": all(checks.values()),
    }
    output = ROOT / "results/wp353_complex_geometry_deformation.json"
    output.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(result, indent=2))
    if not result["passed"]:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
