"""Exact checker for WP439: invariant gradients cannot linearly break the WP438 stabilizer."""

import json
from pathlib import Path
from itertools import product

import sympy as sp


a, t = sp.symbols("a t", nonzero=True, real=True)
I = sp.I
A = sp.Matrix([[0, a, 0], [a, 0, 0], [0, 0, 0]])
D = sp.Matrix([[0, -I*a, 0], [I*a, 0, 0], [0, 0, 0]])
H = sp.diag(1, 1, -2)

# Four Hermitian directions charged under the residual U(1) generated by H.
charged = [
    sp.Matrix([[0, 0, 1], [0, 0, 0], [1, 0, 0]]),
    sp.Matrix([[0, 0, -I], [0, 0, 0], [I, 0, 0]]),
    sp.Matrix([[0, 0, 0], [0, 0, 1], [0, 1, 0]]),
    sp.Matrix([[0, 0, 0], [0, 0, -I], [0, I, 0]]),
]


def trace_word(word, left, right):
    out = sp.eye(3)
    for letter in word:
        out *= left if letter == "A" else right
    return sp.expand(sp.trace(out))


words = ["".join(w) for degree in range(2, 5) for w in product("AD", repeat=degree)]
derivatives = {}
all_zero = True
for word in words:
    row = []
    for X in charged:
        d_a = sp.diff(trace_word(word, A + t*X, D), t).subs(t, 0)
        d_d = sp.diff(trace_word(word, A, D + t*X), t).subs(t, 0)
        pair = [str(sp.simplify(d_a)), str(sp.simplify(d_d))]
        row.append(pair)
        all_zero = all_zero and pair == ["0", "0"]
    derivatives[word] = row

# Deliberate hostile control: an explicitly oriented linear source is charged
# and therefore has a nonzero directional derivative, but is not invariant.
X0 = charged[0]
hostile = sp.diff(sp.trace((A + t*X0)*X0), t).subs(t, 0)

checks = {
    "wp438_pair_commutes_with_residual_generator": sp.simplify(H*A-A*H) == sp.zeros(3) and sp.simplify(H*D-D*H) == sp.zeros(3),
    "charged_basis_has_four_directions": len(charged) == 4,
    "enumerated_all_binary_words_degrees_two_to_four": len(words) == 4 + 8 + 16,
    "all_invariant_word_first_derivatives_vanish_in_charged_directions": all_zero,
    "hostile_oriented_source_derivative_is_nonzero": sp.simplify(hostile) != 0,
}

result = {
    "work_package": "WP439",
    "claim": "Renormalizable simultaneous-conjugation trace invariants cannot linearly source residual-U(1)-charged directions at the WP438 vacuum.",
    "domain": "Two traceless Hermitian SU(3) adjoints at the WP438 embedded-Pauli representative; trace words of degree 2 through 4.",
    "quotient": "Simultaneous SU(3)_F conjugation; H=diag(1,1,-2) generates the residual stabilizer.",
    "instrument": None,
    "word_count": len(words),
    "charged_direction_count": len(charged),
    "directional_derivatives": derivatives,
    "hostile_noninvariant_source_derivative": str(hostile),
    "checks": checks,
    "passed": all(checks.values()),
    "falsifier": "Any admitted simultaneous-conjugation invariant of degree at most four with a nonzero first derivative along one of the four charged directions.",
    "boundary": "The check does not exclude a charged Hessian instability or a disconnected lower-symmetry vacuum branch.",
}

out = Path(__file__).resolve().parents[1] / "results" / "wp439_residual_stabilizer_gradient_obstruction.json"
out.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
print(json.dumps({"passed": result["passed"], "checks": checks, "output": str(out)}, indent=2))
raise SystemExit(0 if result["passed"] else 1)
