"""Exact WP446 obstruction from the WP443 vacuum algebra to physical16."""

import json
from pathlib import Path

import sympy as sp


root = Path(__file__).resolve().parents[1]
wp445 = json.loads((root / "results" / "wp445_flavor_current_kernel.json").read_text(encoding="utf-8"))
I = sp.I
A = sp.diag(1, -1, 0)
D = sp.Matrix([[0, 1, 0], [1, 0, 0], [0, 0, 0]])
P = sp.diag(0, 0, 1)

# Exact closure test: generators and representative products preserve C^2 + C.
generators = [sp.eye(3), A, D, P]
products = [left*right for left in generators for right in generators]
off_block_entries = [(0, 2), (1, 2), (2, 0), (2, 1)]

# The simplest sector-separated WP435 realization gives the exact 12 rotation.
sqrt2 = sp.sqrt(2)
U_up = sp.eye(3)
U_down = sp.Matrix([[1/sqrt2, 1/sqrt2, 0], [1/sqrt2, -1/sqrt2, 0], [0, 0, 1]])
V_ckm = sp.simplify(U_up.conjugate().T*U_down)
moduli_squared = V_ckm.applyfunc(lambda x: sp.simplify(x*sp.conjugate(x)))
jarlskog = sp.im(V_ckm[0, 0]*V_ckm[1, 1]*sp.conjugate(V_ckm[0, 1])*sp.conjugate(V_ckm[1, 0]))

# PDG 2025 global-fit central values, represented exactly as decimals.
pdg_s13 = sp.Rational(3732, 1_000_000)
pdg_s23 = sp.Rational(4183, 100_000)
pdg_j = sp.Rational(312, 10_000_000)

checks = {
    "wp445_dependency_passed": wp445["passed"],
    "vacuum_generators_preserve_two_plus_one_block": all(matrix[i, j] == 0 for matrix in generators for i, j in off_block_entries),
    "generator_products_preserve_two_plus_one_block": all(matrix[i, j] == 0 for matrix in products for i, j in off_block_entries),
    "representative_ckm_is_unitary": sp.simplify(V_ckm.conjugate().T*V_ckm) == sp.eye(3),
    "third_generation_mixings_are_exactly_zero": all(V_ckm[i, j] == 0 for i, j in off_block_entries),
    "representative_jarlskog_is_zero": jarlskog == 0,
    "pdg_theta13_is_nonzero": pdg_s13 > 0,
    "pdg_theta23_is_nonzero": pdg_s23 > 0,
    "pdg_jarlskog_is_nonzero": pdg_j > 0,
}
checks = {name: bool(value) for name, value in checks.items()}

result = {
    "work_package": "WP446",
    "admitted_yukawa_algebra": "The associative algebra generated by I, A0, D0, and phi0 phi0^dagger in the WP443 vacuum.",
    "invariant_decomposition": "C^3=C^2_(generations 1,2) direct-sum C_(generation 3)",
    "representative_ckm_moduli_squared": [[str(x) for x in row] for row in moduli_squared.tolist()],
    "structural_prediction": {"Vub": "0", "Vcb": "0", "Vtd": "0", "Vts": "0", "J": "0"},
    "pdg_2025_inputs": {"sin_theta13": str(pdg_s13), "sin_theta23": str(pdg_s23), "J": str(pdg_j)},
    "source": "https://pdg.lbl.gov/2025/reviews/rpp2025-rev-ckm-matrix.pdf, Eq. 12.28 and surrounding global-fit text",
    "classification": "The WP443 full-Higgsing vacuum is outside the measured physical16 flavor domain for every Yukawa built from its admitted vacuum algebra.",
    "instrument_gate": "Flavor experiments establish the nonzero CKM entries, but their meson bounds cannot calibrate WP445 until a viable source vacuum supplies the mass-basis map.",
    "smallest_exact_falsifier": "Any admitted polynomial in the frozen vacuum generators with a nonzero 2-to-3 or 3-to-2 matrix entry.",
    "remaining_gate": "Enlarge the source vacuum algebra independently so it acts irreducibly on C^3, then repeat global stability and current matching.",
    "checks": checks,
    "passed": all(checks.values()),
}

out = root / "results" / "wp446_messenger_physical16_obstruction.json"
out.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
print(json.dumps(result, indent=2))
raise SystemExit(0 if result["passed"] else 1)
