"""Exact minimal complex entrance-potential flat-direction audit for WP504."""

import json
from pathlib import Path

import sympy as sp


root = Path(__file__).resolve().parents[1]


def load(name):
    return json.loads((root / "results" / name).read_text(encoding="utf-8"))


wp503 = load("wp503_noncollinear_entrance_vacuum.json")

a, b = sp.symbols("a b", positive=True)
lambda_u, lambda_d, kappa = sp.symbols("lambda_u lambda_d kappa", positive=True)
variables = sp.symbols("ur0:3 ui0:3 dr0:3 di0:3", real=True)
ur = sp.Matrix(variables[0:3])
ui = sp.Matrix(variables[3:6])
dr = sp.Matrix(variables[6:9])
di = sp.Matrix(variables[9:12])

norm_u = ur.dot(ur) + ui.dot(ui)
norm_d = dr.dot(dr) + di.dot(di)
inner_real = ur.dot(dr) + ui.dot(di)
inner_imaginary = ur.dot(di) - ui.dot(dr)
potential = sp.expand(
    lambda_u * (norm_u - a**2) ** 2
    + lambda_d * (norm_d - b**2) ** 2
    + kappa * (inner_real**2 + inner_imaginary**2)
)

vacuum_ur = sp.Matrix([0, 0, a])
vacuum_dr = sp.Matrix([b, 0, 0])
zero3 = sp.zeros(3, 1)
vacuum_vector = sp.Matrix.vstack(vacuum_ur, zero3, vacuum_dr, zero3)
vacuum = {variable: vacuum_vector[i] for i, variable in enumerate(variables)}

gradient = sp.Matrix([sp.diff(potential, variable) for variable in variables])
vacuum_gradient = sp.simplify(gradient.subs(vacuum))
hessian = sp.simplify(sp.hessian(potential, variables).subs(vacuum))

L = [
    sp.Matrix([[0, 0, 0], [0, 0, -1], [0, 1, 0]]),
    sp.Matrix([[0, 0, 1], [0, 0, 0], [-1, 0, 0]]),
    sp.Matrix([[0, -1, 0], [1, 0, 0], [0, 0, 0]]),
]
row_gauge = [
    sp.Matrix.vstack(generator * vacuum_ur, zero3, generator * vacuum_dr, zero3)
    for generator in L
]
hypercharge_gauge = sp.Matrix.vstack(zero3, vacuum_ur, zero3, vacuum_dr)
gauge_tangents = sp.Matrix.hstack(*(row_gauge + [hypercharge_gauge]))

# Four exact kernel witnesses not generated by row rotations or the common
# hypercharge phase.
relative_phase = sp.Matrix.vstack(zero3, vacuum_ur, zero3, -vacuum_dr)
imaginary_u_transverse = sp.Matrix([0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0])
imaginary_d_transverse = sp.Matrix([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0])
imaginary_cross_kernel = sp.Matrix([0, 0, 0, a, 0, 0, 0, 0, 0, 0, 0, b])
physical_zero_witnesses = sp.Matrix.hstack(
    relative_phase,
    imaginary_u_transverse,
    imaginary_d_transverse,
    imaginary_cross_kernel,
)

kernel = sp.Matrix.hstack(*hessian.nullspace())
gauge_plus_physical = gauge_tangents.row_join(physical_zero_witnesses)

sqrt_ab = sp.sqrt(a**2 + b**2)
massive_modes = sp.Matrix.hstack(
    sp.Matrix([0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
    sp.Matrix([0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]),
    sp.Matrix([b, 0, 0, 0, 0, 0, 0, 0, a, 0, 0, 0]) / sqrt_ab,
    sp.Matrix([0, 0, 0, -b, 0, 0, 0, 0, 0, 0, 0, a]) / sqrt_ab,
)
massive_hessian = sp.simplify(massive_modes.T * hessian * massive_modes)
expected_massive_hessian = sp.diag(
    8 * lambda_u * a**2,
    8 * lambda_d * b**2,
    2 * kappa * (a**2 + b**2),
    2 * kappa * (a**2 + b**2),
)

checks = {
    "wp503_dependency_passed": wp503["passed"],
    "orthogonal_complex_vacuum_is_stationary": vacuum_gradient == sp.zeros(12, 1),
    "complex_hessian_rank_is_four": hessian.rank() == 4,
    "complex_hessian_nullity_is_eight": len(hessian.nullspace()) == 8,
    "row_plus_hypercharge_gauge_rank_is_four": gauge_tangents.rank() == 4,
    "all_declared_gauge_tangents_are_hessian_zeros": hessian * gauge_tangents == sp.zeros(12, 4),
    "four_physical_zero_witnesses_are_independent": physical_zero_witnesses.rank() == 4,
    "physical_zero_witnesses_are_exact_hessian_zeros": hessian * physical_zero_witnesses == sp.zeros(12, 4),
    "gauge_and_physical_zero_witnesses_span_full_kernel": gauge_plus_physical.rank() == 8 and kernel.row_join(gauge_plus_physical).rank() == 8,
    "massive_mode_basis_is_orthonormal": sp.simplify(massive_modes.T * massive_modes) == sp.eye(4),
    "massive_modes_are_transverse_to_full_kernel": sp.simplify(massive_modes.T * kernel) == sp.zeros(4, 8),
    "four_positive_massive_modes_are_exact": massive_hessian == expected_massive_hessian,
}
checks = {name: bool(value) for name, value in checks.items()}

result = {
    "work_package": "WP504",
    "domain": "minimal Hermitian complex neutral-row lift of WP503, with two complex SO(3)_E vectors and common hypercharge phase gauged",
    "potential": "lambda_u (u_dagger u-a^2)^2 + lambda_d (d_dagger d-b^2)^2 + kappa |u_dagger d|^2",
    "vacuum": "u=a e3 and d=b e1, both real",
    "hessian": {
        "real_dimension": 12,
        "rank": int(hessian.rank()),
        "nullity": len(hessian.nullspace()),
        "gauge_kernel_dimension": int(gauge_tangents.rank()),
        "physical_kernel_dimension": int(gauge_plus_physical.rank() - gauge_tangents.rank()),
        "positive_mass_squared": [
            str(8 * lambda_u * a**2),
            str(8 * lambda_d * b**2),
            str(2 * kappa * (a**2 + b**2)),
            str(2 * kappa * (a**2 + b**2)),
        ],
    },
    "physical_zero_witnesses": [
        "relative overall phase of the two entrance vectors",
        "imaginary u fluctuation along the row direction transverse to both vevs",
        "imaginary d fluctuation along the row direction transverse to both vevs",
        "imaginary cross fluctuation orthogonal to the |u_dagger d| response",
    ],
    "classification": "Exact obstruction to transporting WP503 through the minimal complex lift: four physical neutral zero modes remain after removing all row and hypercharge gauge tangents.",
    "selector": False,
    "rigidifier": False,
    "instrument": None,
    "smallest_exact_falsifier": "The twelve-real-dimensional Hessian has nullity eight while the admitted row-plus-hypercharge gauge orbit has dimension four, leaving a four-dimensional physical kernel.",
    "remaining_gate": "Enumerate the complete renormalizable electroweak and row-gauge invariant basis, add independently justified phase-sensitive terms, and prove a full charged, CP-even, and CP-odd Hessian whose kernel equals the complete gauge orbit before deriving poles, residues, or widths.",
    "checks": checks,
    "passed": all(checks.values()),
}

out = root / "results" / "wp504_complex_entrance_flat_obstruction.json"
out.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
print(json.dumps(result, indent=2))
raise SystemExit(0 if result["passed"] else 1)
