"""Exact WP595 square-symmetry CP-orientation selector."""

import json
from pathlib import Path

import sympy as sp

sigma, s = sp.symbols("sigma s", real=True)
scale, lam, kappa = sp.symbols("a lambda kappa", positive=True, real=True)
c0, c1, c2, c3, c4 = sp.symbols("c0 c1 c2 c3 c4", real=True)

quartic = c0 * sigma**4 + c1 * sigma**3 * s + c2 * sigma**2 * s**2
quartic += c3 * sigma * s**3 + c4 * s**4
rotation_difference = sp.Poly(
    sp.expand(quartic.subs({sigma: -s, s: sigma}, simultaneous=True) - quartic),
    sigma,
    s,
)
reflection_difference = sp.Poly(
    sp.expand(quartic.subs(s, -s) - quartic), sigma, s
)
constraints = rotation_difference.coeffs() + reflection_difference.coeffs()
invariant_solution = sp.linsolve(constraints, (c0, c1, c2, c3, c4))

radius_sq = sigma**2 + s**2
anisotropy_coordinate = sigma**2 - s**2
potential = lam * (radius_sq - scale**2) ** 2 / 4
potential += kappa * anisotropy_coordinate**2 / 4

vacuum_value = scale / sp.sqrt(2)
vacuum = {sigma: vacuum_value, s: vacuum_value}
hessian = sp.simplify(sp.hessian(potential, (sigma, s)).subs(vacuum))
hessian_eigenvalues = hessian.eigenvals()
orientation_fraction = sp.simplify(s**2 / radius_sq)
vacuum_orientation = sp.simplify(orientation_fraction.subs(vacuum))
rotation = sp.Matrix([[0, -1], [1, 0]])
bare_cp = sp.diag(1, -1)
vacuum_vector = sp.Matrix([vacuum_value, vacuum_value])
generalized_cp = rotation * bare_cp

checks = {
    "quartic_invariant_space_has_two_generators": invariant_solution
    == {(c4, 0, c2, 0, c4)},
    "radial_quartic_is_square_symmetric": sp.simplify(
        radius_sq.subs({sigma: -s, s: sigma}, simultaneous=True) - radius_sq
    )
    == 0,
    "anisotropy_square_is_square_symmetric": sp.simplify(
        anisotropy_coordinate.subs(
            {sigma: -s, s: sigma}, simultaneous=True
        )
        ** 2
        - anisotropy_coordinate**2
    )
    == 0,
    "potential_is_cp_even": sp.simplify(potential.subs(s, -s) - potential)
    == 0,
    "diagonal_vacuum_has_zero_energy": sp.simplify(potential.subs(vacuum)) == 0,
    "diagonal_vacuum_is_stationary": sp.Matrix(
        [sp.diff(potential, sigma), sp.diff(potential, s)]
    ).subs(vacuum)
    == sp.zeros(2, 1),
    "vacuum_orientation_is_one_half": vacuum_orientation == sp.Rational(1, 2),
    "orientation_is_coefficient_independent": not (
        {lam, kappa} & vacuum_orientation.free_symbols
    ),
    "hessian_has_positive_radial_and_angular_modes": hessian_eigenvalues
    == {2 * scale**2 * lam: 1, 2 * scale**2 * kappa: 1},
    "bare_cp_moves_the_diagonal_vacuum": bare_cp * vacuum_vector
    != vacuum_vector,
    "generalized_cp_stabilizes_the_diagonal_vacuum": generalized_cp
    * vacuum_vector
    == vacuum_vector,
    "removing_anisotropy_restores_cp_conserving_vacuum": sp.simplify(
        potential.subs({kappa: 0, sigma: scale, s: 0})
    )
    == 0,
}

if not all(checks.values()):
    raise SystemExit(f"WP595 check failed: {checks}")

checks = {key: bool(value) for key, value in checks.items()}
result = {
    "work_package": "WP595",
    "status": "PASS",
    "checks": checks,
    "source_symmetry": "square symmetry generated by (sigma,s)->(-s,sigma) and CP reflection (sigma,s)->(sigma,-s)",
    "renormalizable_quartic_invariant_dimension": 2,
    "positive_source_potential": "lambda*(sigma^2+s^2-a^2)^2/4 + kappa*(sigma^2-s^2)^2/4",
    "vacuum_set": "(sigma,s)=(plus_or_minus a/sqrt(2), plus_or_minus a/sqrt(2))",
    "selected_relation": "s^2/(sigma^2+s^2)=1/2",
    "hessian_spectrum": ["2*a^2*lambda", "2*a^2*kappa"],
    "hard_to_vary_content": "the orientation ratio is fixed by the zero sets of two representation-derived invariant squares and is independent of positive coefficient magnitudes",
    "generalized_cp_correction": "bare CP moves each diagonal vacuum, but a square rotation composed with CP stabilizes it",
    "classification": "genuine discrete orientation selector; physical CP breaking is not established because a generalized CP stabilizer survives",
    "smallest_exact_falsifier": "kappa=0 restores the O(2) vacuum circle and admits (sigma,s)=(a,0), so the anisotropy invariant is load-bearing",
    "rg_gate": "prove kappa remains positive and that the two-invariant renormalizable surface is closed under the complete coupled theory",
    "higher_operator_gate": "control square-symmetric operators beyond dimension four that can alter angular minima",
    "experiment_gate": "a joined calibrated CP-invariant and singlet/flavor-clock readout is meaningful only after the portal embedding removes every generalized CP stabilizer",
}

out = (
    Path(__file__).resolve().parents[1]
    / "results"
    / "wp595_square_symmetry_cp_orientation.json"
)
out.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
print(json.dumps(result, indent=2))
