"""Exact ordinary-index versus ordered boundary-charge audit."""
import json
from pathlib import Path

import sympy as sp


ROOT = Path(__file__).resolve().parents[1]
n0, npi, T, I = sp.symbols("n_0 n_pi T I", integer=True)

index_map = sp.Matrix([[1, -1]])
diagonal_vectorlike = sp.Matrix([1, 1])
rank_index_map = sp.Matrix([[1, 1], [1, -1]])
rank_index_inverse = rank_index_map.inv()


def contrast(pair):
    ratio = sp.Rational(pair[0], pair[1])
    return sp.factor((ratio**2 - 1) ** 2 / (2 * (ratio**2 + 1) ** 2))


hostile_a = (2, 1)
hostile_b = (3, 2)
index_a = hostile_a[0] - hostile_a[1]
index_b = hostile_b[0] - hostile_b[1]
delta_a = contrast(hostile_a)
delta_b = contrast(hostile_b)
reconstruction = sp.simplify(rank_index_inverse * sp.Matrix([T, I]))

checks = {
    "ordinary_index_map_has_rank_one": index_map.rank() == 1,
    "diagonal_vectorlike_direction_is_in_index_kernel": index_map * diagonal_vectorlike == sp.zeros(1, 1),
    "hostile_pairs_have_same_nonzero_index": index_a == index_b == 1,
    "hostile_pairs_have_different_totals": sum(hostile_a) == 3 and sum(hostile_b) == 5,
    "hostile_pairs_predict_different_portals": delta_a == sp.Rational(9, 50) and delta_b == sp.Rational(25, 338),
    "ordinary_index_does_not_select_portal": delta_a != delta_b,
    "rank_plus_index_map_is_nonsingular": rank_index_map.det() == -2,
    "rank_plus_index_reconstructs_ordered_pair": reconstruction == sp.Matrix([(T + I) / 2, (T - I) / 2]),
    "reconstruction_has_parity_gate": all((total + idx) % 2 == 0 for total, idx in [(3, 1), (4, 2), (5, 1)]),
    "orientation_reversal_flips_index": (hostile_a[1] - hostile_a[0]) == -index_a,
}
checks = {name: bool(value) for name, value in checks.items()}
if not all(checks.values()):
    raise SystemExit(checks)

result = {
    "work_package": "WP762",
    "status": "PASS",
    "checks": checks,
    "admitted_state_domain": "positive ordered boundary zero-mode multiplicities (n0,npi) for a domain-wall Dirac family, including anomaly-neutral diagonal vectorlike additions",
    "faithful_coordinate": "the ordered pair (n0,npi), equivalently the parity-compatible pair (T,I) with T=n0+npi and I=n0-npi",
    "source_authorized_operation": "the ordinary chiral/Fredholm index I=n0-npi of the domain-wall Dirac operator",
    "contextual_partition": "fixed-index classes are infinite rays generated by the diagonal vectorlike direction (1,1)",
    "kernel": "ker(I) is generated over the integer charge lattice by diagonal vectorlike additions",
    "classification": "orientation selector and net-chirality invariant, but not a tadpole-total or portal-magnitude selector",
    "smallest_exact_falsifier": "ordered pairs (2,1) and (3,2) both have index one but predict portal contrasts 9/50 and 25/338",
    "faithful_repair": "the combined rank-index packet reconstructs n0=(T+I)/2 and npi=(T-I)/2 subject to positivity and parity",
    "source_gate": "an ordinary index theorem supplies I but not T; a source-generated rank or total-charge invariant is separately required",
    "rg_threshold_gate": "the topological index can survive continuous deformations while vectorlike threshold pairs change T and the low-energy portal without changing I",
    "instrument_gate": "net chirality does not identify the labelled boundary overlap; a rank-sensitive threshold instrument is required",
    "deutschian_status": "the index explains protected net chirality but is deliberately insensitive to the vectorlike content controlling the portal magnitude",
    "next_source_gate": "derive a relative rank-index class or endpoint-resolved K-theory charge whose two components are both source-fixed and physically readable",
}
(ROOT / "results" / "wp762_chiral_index_vectorlike_kernel.json").write_text(
    json.dumps(result, indent=2) + "\n", encoding="utf-8"
)
print(json.dumps(result, indent=2))
