"""Exact Aspect-germ audit of the source-closed path-polynomial proposal."""

import json
from pathlib import Path

import sympy as sp


def main() -> None:
    x, y, c, lam = sp.symbols("x y c lam", real=True)
    a = x + sp.I*y
    F = sp.Matrix([[0, -sp.I, 0], [0, 0, -sp.I], [0, 0, 0]]) / sp.sqrt(2)
    Y = a*sp.eye(3) + F + c*F**2
    H = sp.simplify(Y*Y.conjugate().T)
    coeffs = H.charpoly(lam).all_coeffs()
    e1, e2, e3 = (-coeffs[1], coeffs[2], -coeffs[3])
    at_unit = [sp.factor(q.subs(c, 1)) for q in (e1, e2, e3)]
    expected = [
        3*(x**2+y**2) + sp.Rational(5, 4),
        3*(x**2+y**2)**2 + sp.Rational(5, 4)*(x**2+y**2)
        - x/sp.Integer(2) + sp.Rational(1, 4),
        (x**2+y**2)**3,
    ]
    hostile_derivative = [sp.factor(sp.diff(q, c).subs({c: 1, x: 1, y: 0}))
                          for q in (e1, e2, e3)]
    basis_matrix = sp.Matrix.hstack(*[M.reshape(9, 1) for M in
                                      (sp.eye(3), F, F**2)])
    tests = []

    def check(name, condition, evidence):
        tests.append({"name": name, "passed": bool(condition),
                      "evidence": str(evidence)})

    check("path_is_nilpotent_of_exact_order_three",
          F**3 == sp.zeros(3) and F**2 != sp.zeros(3), F**2)
    check("native_three_path_occurrences_are_independent",
          basis_matrix.rank() == 3, basis_matrix.rank())
    check("unit_polynomial_invariants_are_exact",
          all(sp.expand(p-q) == 0 for p, q in zip(at_unit, expected)), at_unit)
    check("determinant_is_path_coefficient_independent",
          sp.factor(e3-(x**2+y**2)**3) == 0, e3)
    check("completion_hostile_changes_physical_invariants",
          hostile_derivative[:2] != [0, 0], hostile_derivative)
    check("hostile_is_not_only_an_overall_scale",
          hostile_derivative[2] == 0 and hostile_derivative[0] != 0,
          hostile_derivative)
    check("unit_coefficient_not_fixed_by_path_algebra",
          basis_matrix.rank() == 3, "c is the independent F^2 coordinate")
    check("physical_instrument_gate_remains_open", True,
          "no calibrated coherent three-occurrence physical16 instrument")

    result = {
        "schema": "marici.flavor.path-polynomial-aspect-germ-audit.v1",
        "work_package": "WP863",
        "summary": {"passed": sum(t["passed"] for t in tests),
                    "total": len(tests),
                    "all_passed": all(t["passed"] for t in tests)},
        "admitted_state_domain": "marked length-three complex path algebra generated by F",
        "faithful_quotient_coordinate": "physical16 weak-basis quotient",
        "native_arity": 3,
        "unit_polynomial_invariants": [str(q) for q in at_unit],
        "smallest_exact_falsifier": "Y_c=a I+F+c F^2 with c varied through 1",
        "hostile_invariant_derivative_at_a1_c1": [str(q) for q in hostile_derivative],
        "gates": {
            "marked_germ": "pass",
            "full_weak_basis_fiber": "pass_conditional_on_covariant_transport",
            "native_arity": "pass",
            "completion_authority": "fail",
            "physical_instrument": "open",
        },
        "classification": "candidate rigidifier, not a source-authorized selector",
        "prohibited_inference": "fit c or set c=1 and call the result source-selected",
        "tests": tests,
    }
    output = Path(__file__).parents[1] / "results" / "wp863_path_polynomial_aspect_germ_audit.json"
    output.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(result["summary"], indent=2))
    if not result["summary"]["all_passed"]:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
