import Mathlib.LinearAlgebra.Quotient.Basic
import Mathlib.Tactic

/-!
# Coherent-resolution algebra and the interval mixed difference

This file formalizes only the stable finite algebra isolated by the NNMHV
interval-poset checkers.  It does not identify these objects with a physical
amplitude, a colimit, or a derived-category realization.
-/

namespace MariciFormal

universe u v w

/-- A homological graded object with a degree-lowering differential. -/
structure GradedDifferentialObject (R : Type u) [Ring R] where
  carrier : ℕ → Type v
  moduleCarrier : ∀ q, AddCommGroup (carrier q)
  moduleStructure : ∀ q, Module R (carrier q)
  d : ∀ q, carrier (q + 1) →ₗ[R] carrier q
  d_sq : ∀ q x, d q (d (q + 1) x) = 0

attribute [instance] GradedDifferentialObject.moduleCarrier
attribute [instance] GradedDifferentialObject.moduleStructure

/-- A degree-zero chain map. -/
structure GradedChainMap {R : Type u} [Ring R]
    (C D : GradedDifferentialObject R) where
  component : ∀ q, C.carrier q →ₗ[R] D.carrier q
  commutes : ∀ q x, D.d q (component (q + 1) x) = component q (C.d q x)

/-- A chain homotopy between degree-zero chain maps. -/
structure GradedChainHomotopy {R : Type u} [Ring R]
    {C D : GradedDifferentialObject R} (f g : GradedChainMap C D) where
  homotopy : ∀ q, C.carrier q →ₗ[R] D.carrier (q + 1)
  identity : ∀ q (x : C.carrier (q + 1)),
    f.component (q + 1) x - g.component (q + 1) x =
      D.d (q + 1) (homotopy (q + 1) x) + homotopy q (C.d q x)

/-- A quotient by explicitly typed relation cells. -/
def relationCellQuotient {R M : Type*} [Ring R] [AddCommGroup M] [Module R M]
    (relations : Submodule R M) := M ⧸ relations

/-- An augmentation is a linear readout, with no implied faithfulness. -/
abbrev Augmentation (R M : Type*) [Semiring R] [AddCommMonoid M] [Module R M] :=
  M →ₗ[R] R

/-- A family of probes is faithful when joint equality of all readouts reflects
 equality in the source. -/
def FaithfulProbeFamily {ι R M : Type*} [Semiring R] [AddCommMonoid M] [Module R M]
    (probe : ι → M →ₗ[R] R) : Prop :=
  ∀ x y, (∀ i, probe i x = probe i y) → x = y

section MixedDifference

variable {A : Type*} [AddCommGroup A]

/-- The four-corner mixed finite difference. -/
def mixedDifference (f : ℕ → ℕ → A) (i j : ℕ) : A :=
  f (i + 1) (j + 1) - f i (j + 1) - f (i + 1) j + f i j

/-- The two characteristic boundary channels, with their shared corner counted
only once. -/
def characteristicBoundary (f : ℕ → ℕ → A) : (ℕ → A) × (ℕ → A) :=
  (fun i => f i 0, fun j => f 0 j)

/-- The homogeneous field generated by two endpoint channels.  The subtraction
quotients their common constant mode. -/
def endpointSum (lower upper : ℕ → A) : ℕ → ℕ → A :=
  fun i j => lower i + upper j - lower 0

@[simp] theorem mixedDifference_endpointSum (lower upper : ℕ → A) (i j : ℕ) :
    mixedDifference (endpointSum lower upper) i j = 0 := by
  simp [mixedDifference, endpointSum]
  abel

/-- One recurrence step obtained from vanishing mixed difference. -/
theorem eq_of_mixedDifference_eq_zero_step (f : ℕ → ℕ → A) (i j : ℕ)
    (h : mixedDifference f i j = 0) :
    f (i + 1) (j + 1) = f i (j + 1) + f (i + 1) j - f i j := by
  apply sub_eq_zero.mp
  unfold mixedDifference at h
  abel_nf at h ⊢
  simpa [Nat.add_comm] using h

/-- Complete null-space decomposition of the mixed finite difference: every
homogeneous field is the sum of its two endpoint channels, modulo their shared
constant. -/
theorem mixedDifference_null_decomposition (f : ℕ → ℕ → A)
    (h : ∀ i j, mixedDifference f i j = 0) :
    ∀ i j, f i j = f i 0 + f 0 j - f 0 0 := by
  intro i
  induction i with
  | zero =>
      intro j
      simp
  | succ i ih =>
      intro j
      induction j with
      | zero => simp
      | succ j hj =>
          rw [eq_of_mixedDifference_eq_zero_step f i j (h i j), ih (j + 1), hj, ih j]
          abel

/-- Characteristic reconstruction: boundary traces and bulk mixed differences
jointly determine the complete field. -/
theorem characteristic_reconstruction_unique (f g : ℕ → ℕ → A)
    (hlower : ∀ i, f i 0 = g i 0)
    (hupper : ∀ j, f 0 j = g 0 j)
    (hbulk : ∀ i j, mixedDifference f i j = mixedDifference g i j) :
    f = g := by
  funext i j
  let h : ℕ → ℕ → A := fun a b => f a b - g a b
  have hnull : ∀ a b, mixedDifference h a b = 0 := by
    intro a b
    specialize hbulk a b
    dsimp [h]
    unfold mixedDifference at hbulk ⊢
    calc
      (f (a + 1) (b + 1) - g (a + 1) (b + 1)) -
          (f a (b + 1) - g a (b + 1)) -
          (f (a + 1) b - g (a + 1) b) + (f a b - g a b) =
        (f (a + 1) (b + 1) - f a (b + 1) - f (a + 1) b + f a b) -
          (g (a + 1) (b + 1) - g a (b + 1) - g (a + 1) b + g a b) := by abel
      _ = 0 := sub_eq_zero.mpr hbulk
  have hd := mixedDifference_null_decomposition h hnull i j
  dsimp [h] at hd
  rw [hlower i, hupper j, hlower 0] at hd
  simp at hd
  exact sub_eq_zero.mp hd

/-- The characteristic transform is injective over every additive coefficient
 group. Over `ℤ`, this is the basis-free content needed for the finite
 unimodularity check: no torsion or lattice volume is lost. -/
theorem characteristic_transform_injective :
    Function.Injective (fun f : ℕ → ℕ → A =>
      (characteristicBoundary f, mixedDifference f)) := by
  intro f g h
  apply characteristic_reconstruction_unique f g
  · intro i
    exact congrFun (congrArg Prod.fst (congrArg Prod.fst h)) i
  · intro j
    exact congrFun (congrArg Prod.snd (congrArg Prod.fst h)) j
  · intro i j
    exact congrFun (congrFun (congrArg Prod.snd h) i) j

end MixedDifference

end MariciFormal
