import MariciFormal.FirstDeterminantalIdeal

/-!
The ideal generated by matrix entries is invariant under explicitly reversible
row and column changes. Invertibility is carried by concrete inverse equations.
-/

namespace MariciFormal

variable {R : Type*} [CommRing R]
variable {m n : Type*} [Fintype m] [Fintype n]
  [DecidableEq m] [DecidableEq n]

/-- The ideal generated by all entries of a finite matrix. -/
noncomputable def matrixEntryIdeal (matrix : Matrix m n R) : Ideal R :=
  Ideal.span (Set.range fun ij : m × n => matrix ij.1 ij.2)

theorem bivariate_firstDeterminantalIdeal_eq_matrixEntryIdeal
    (matrix : BivariateMatrix₂) :
    firstDeterminantalIdeal matrix = matrixEntryIdeal matrix := rfl

omit [Fintype m] [Fintype n] [DecidableEq m] [DecidableEq n] in
theorem matrixEntry_mem (matrix : Matrix m n R) (i : m) (j : n) :
    matrix i j ∈ matrixEntryIdeal matrix := by
  apply Ideal.subset_span
  exact ⟨(i, j), rfl⟩

omit [Fintype n] [DecidableEq m] [DecidableEq n] in
theorem matrixEntryIdeal_left_mul_le
    (left : Matrix m m R) (matrix : Matrix m n R) :
    matrixEntryIdeal (left * matrix) ≤ matrixEntryIdeal matrix := by
  rw [matrixEntryIdeal, Ideal.span_le]
  rintro _ ⟨⟨i, j⟩, rfl⟩
  change (left * matrix) i j ∈ matrixEntryIdeal matrix
  rw [Matrix.mul_apply]
  exact Ideal.sum_mem _ fun k _ =>
    Ideal.mul_mem_left _ _ (matrixEntry_mem matrix k j)

omit [Fintype m] [DecidableEq m] [DecidableEq n] in
theorem matrixEntryIdeal_right_mul_le
    (matrix : Matrix m n R) (right : Matrix n n R) :
    matrixEntryIdeal (matrix * right) ≤ matrixEntryIdeal matrix := by
  rw [matrixEntryIdeal, Ideal.span_le]
  rintro _ ⟨⟨i, j⟩, rfl⟩
  change (matrix * right) i j ∈ matrixEntryIdeal matrix
  rw [Matrix.mul_apply]
  exact Ideal.sum_mem _ fun k _ =>
    Ideal.mul_mem_right (right k j) _ (matrixEntry_mem matrix i k)

omit [Fintype n] [DecidableEq n] in
/-- An explicitly reversible row operation preserves the entry ideal. -/
theorem matrixEntryIdeal_left_equivalence
    (left leftInv : Matrix m m R) (matrix : Matrix m n R)
    (hInv : leftInv * left = 1) :
    matrixEntryIdeal (left * matrix) = matrixEntryIdeal matrix := by
  apply le_antisymm
  · exact matrixEntryIdeal_left_mul_le left matrix
  · have hmatrix : leftInv * (left * matrix) = matrix := by
      rw [← Matrix.mul_assoc, hInv, Matrix.one_mul]
    calc
      matrixEntryIdeal matrix =
          matrixEntryIdeal (leftInv * (left * matrix)) := congrArg _ hmatrix.symm
      _ ≤ matrixEntryIdeal (left * matrix) :=
        matrixEntryIdeal_left_mul_le leftInv (left * matrix)

omit [Fintype m] [DecidableEq m] in
/-- An explicitly reversible column operation preserves the entry ideal. -/
theorem matrixEntryIdeal_right_equivalence
    (right rightInv : Matrix n n R) (matrix : Matrix m n R)
    (hInv : right * rightInv = 1) :
    matrixEntryIdeal (matrix * right) = matrixEntryIdeal matrix := by
  apply le_antisymm
  · exact matrixEntryIdeal_right_mul_le matrix right
  · have hmatrix : (matrix * right) * rightInv = matrix := by
      rw [Matrix.mul_assoc, hInv, Matrix.mul_one]
    calc
      matrixEntryIdeal matrix =
          matrixEntryIdeal ((matrix * right) * rightInv) := congrArg _ hmatrix.symm
      _ ≤ matrixEntryIdeal (matrix * right) :=
        matrixEntryIdeal_right_mul_le (matrix * right) rightInv

/-- Explicitly reversible row and column presentation changes preserve the
first determinantal ideal. -/
theorem matrixEntryIdeal_two_sided_equivalence
    (left leftInv : Matrix m m R) (right rightInv : Matrix n n R)
    (matrix : Matrix m n R)
    (hLeft : leftInv * left = 1) (hRight : right * rightInv = 1) :
    matrixEntryIdeal (left * matrix * right) = matrixEntryIdeal matrix := by
  rw [matrixEntryIdeal_right_equivalence right rightInv (left * matrix) hRight]
  exact matrixEntryIdeal_left_equivalence left leftInv matrix hLeft

end MariciFormal
