import MariciFormal.FittingRankStrata

/-!
The determinant collision in `FittingRankStrata` is separated by the ideal
generated by the one-by-one minors, i.e. by the matrix entries.
-/

namespace MariciFormal

open MvPolynomial

/-- The first determinantal ideal of a finite matrix: the ideal generated by
its one-by-one minors (its entries). -/
noncomputable def firstDeterminantalIdeal (matrix : BivariateMatrix₂) :
    Ideal TwoVariablePolynomial :=
  Ideal.span (Set.range fun ij : Fin 2 × Fin 2 => matrix ij.1 ij.2)

theorem productAxis_firstDeterminantalIdeal_eq_top :
    firstDeterminantalIdeal productAxisMatrix = ⊤ := by
  rw [Ideal.eq_top_iff_one]
  apply Ideal.subset_span
  exact ⟨(0, 0), by simp [productAxisMatrix]⟩

theorem separateAxis_firstDeterminantalIdeal_ne_top :
    firstDeterminantalIdeal separateAxisMatrix ≠ ⊤ := by
  let atOrigin : TwoVariablePolynomial →+* Rat := MvPolynomial.eval origin
  have hle : firstDeterminantalIdeal separateAxisMatrix ≤
      Ideal.comap atOrigin ⊥ := by
    rw [firstDeterminantalIdeal, Ideal.span_le]
    rintro _ ⟨⟨i, j⟩, rfl⟩
    change atOrigin (separateAxisMatrix i j) = 0
    fin_cases i <;> fin_cases j <;>
      norm_num [atOrigin, separateAxisMatrix, variableU, variableV, origin]
  intro htop
  have hone : (1 : TwoVariablePolynomial) ∈ Ideal.comap atOrigin ⊥ :=
    hle (by simp [htop])
  simp [atOrigin] at hone

/-- Equal determinant polynomials do not determine the first determinantal
ideal, even for two-by-two matrices over `Q[u,v]`. -/
theorem determinant_does_not_determine_firstDeterminantalIdeal :
    separateAxisMatrix.det = productAxisMatrix.det ∧
      firstDeterminantalIdeal separateAxisMatrix ≠
        firstDeterminantalIdeal productAxisMatrix := by
  refine ⟨determinantPolynomials_agree.1.trans
      determinantPolynomials_agree.2.symm, ?_⟩
  rw [productAxis_firstDeterminantalIdeal_eq_top]
  exact separateAxis_firstDeterminantalIdeal_ne_top

end MariciFormal
