import Mathlib.RingTheory.Ideal.Operations

/-!
Algebraic two-inclusion core of Grothendieck's Mellin source-ideal saturation.
If every source image is divisible by `xi` and `xi` itself occurs in the
source range, the ideal generated by that range is exactly the principal
ideal generated by `xi`.
-/

namespace MariciFormal

variable {B : Type*} [CommRing B]

theorem source_span_eq_principal
    (sourceRange : Set B) (xi : B)
    (hdivisible : sourceRange ⊆ Ideal.span ({xi} : Set B))
    (hxi : xi ∈ sourceRange) :
    Ideal.span sourceRange = Ideal.span ({xi} : Set B) := by
  apply le_antisymm
  · exact Ideal.span_le.mpr hdivisible
  · apply Ideal.span_le.mpr
    intro element helement
    simpa using (Ideal.subset_span hxi)

/-- If the distinguished generator is absent, containment of the source range
in its principal ideal alone need not give equality. -/
theorem generator_membership_is_independent_hostile :
    let sourceRange : Set ℤ := {0}
    sourceRange ⊆ Ideal.span ({2} : Set ℤ) ∧
      Ideal.span sourceRange ≠ Ideal.span ({2} : Set ℤ) := by
  dsimp
  constructor
  · intro element helement
    simpa [Set.mem_singleton_iff.mp helement]
  · intro heq
    have htwo : (2 : ℤ) ∈ Ideal.span ({0} : Set ℤ) := by
      rw [heq]
      exact Ideal.subset_span (Set.mem_singleton 2)
    simpa using htwo

end MariciFormal
