import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import matter from 'gray-matter'
import MarkdownIt from 'markdown-it'
import katexCore from 'katex'
import { katex } from '@mdit/plugin-katex'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const sourceRoot = path.join(root, 'src', 'ledger')
const ledgerOut = path.join(root, 'website', 'research', 'ledger')
const resultsOut = path.join(root, 'website', 'research', 'results')
const marker = '<!-- Generated by scripts/prepare-website.mjs. Edit src/ledger instead. -->'
// Refresh authored content pages without deleting/rebuilding ledger or public assets.
const pagesOnly = process.argv.includes('--pages-only')
let ledgerCount = 0

async function walk(dir) {
  const found = []
  for (const entry of await fs.readdir(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) found.push(...await walk(full))
    else if (/\.md$/i.test(entry.name)) found.push(full)
  }
  return found.sort()
}
const slugify = value => value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
const plain = value => value.replace(/\\\((.*?)\\\)/g, '$1').replace(/\\\[/g, '').replace(/\\\]/g, '').replace(/\$([^$]+)\$/g, '$1').replace(/!\[([^\]]*)\]\([^)]*\)/g, '$1').replace(/\[([^\]]+)\]\([^)]*\)/g, '$1').replace(/[*_>#`]/g, '').replace(/\s+/g, ' ').trim()
const htmlEscape = value => value.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')
const renderTitle = value => {
  const normalized = value.replace(/\\\((.*?)\\\)/g, (_, formula) => `$${formula}$`)
  let html = ''
  let cursor = 0
  for (const match of normalized.matchAll(/\$([^$]+)\$/g)) {
    html += htmlEscape(normalized.slice(cursor, match.index))
    html += katexCore.renderToString(match[1], { throwOnError: false, output: 'htmlAndMathml' })
    cursor = match.index + match[0].length
  }
  return html + htmlEscape(normalized.slice(cursor))
}
const markdown = new MarkdownIt({ html: true, linkify: true }).use(katex, { throwOnError: false, strict: 'error' })
const ledgerPublic = path.join(root, 'website', 'public', 'research', 'ledger')
if (!pagesOnly) {
await fs.copyFile(path.join(root, 'src', 'data', 'epistemic-graph.json'), path.join(root, 'website', 'public', 'epistemic-graph.json'))

// Remove only pages created by this script, leaving hand-authored Markdown alone.
for (const dir of [ledgerOut, resultsOut]) {
  for (const name of await fs.readdir(dir)) {
    if (!name.endsWith('.md') || name === 'index.md') continue
    const file = path.join(dir, name)
    const content = await fs.readFile(file, 'utf8').catch(() => '')
    if (content.startsWith('<!-- Generated by scripts/prepare-website.mjs.')) await fs.unlink(file)
  }
}
await fs.mkdir(ledgerPublic, { recursive: true })
for (const name of await fs.readdir(ledgerPublic)) {
  const candidate = path.join(ledgerPublic, name)
  if (name === 'index.json') { await fs.unlink(candidate); continue }
  const stat = await fs.stat(candidate).catch(() => null)
  if (stat?.isDirectory()) {
    const indexFile = path.join(candidate, 'index.html')
    const html = await fs.readFile(indexFile, 'utf8').catch(() => '')
    if (html.includes(marker)) await fs.rm(candidate, { recursive: true, force: true })
  }
}
const katexRoot = path.join(root, 'node_modules', 'katex', 'dist')
await fs.mkdir(path.join(root, 'website', 'public', 'katex'), { recursive: true })
await fs.copyFile(path.join(katexRoot, 'katex.min.css'), path.join(root, 'website', 'public', 'katex', 'katex.min.css'))
await fs.cp(path.join(katexRoot, 'fonts'), path.join(root, 'website', 'public', 'katex', 'fonts'), { recursive: true })

const records = []
for (const file of await walk(sourceRoot)) {
  const relative = path.relative(sourceRoot, file).replaceAll('\\','/')
  const id = relative.replace(/\.md$/i, '')
  const match = id.match(/(?:^|\/)(\d{8})-(\d+)[ _-](.+)$/)
  if (!match) continue
  const parsed = matter(await fs.readFile(file, 'utf8'))
  if (parsed.data.draft === true) continue
  const [, dateKey, entryText, filenameTitle] = match
  const entry = Number(entryText)
  const title = String(parsed.data.title || parsed.content.match(/^#\s+(.+)$/m)?.[1]?.trim() || filenameTitle)
  const slug = slugify(`${dateKey}-${entryText}-${filenameTitle}`)
  const first = parsed.content.split(/\r?\n\s*\r?\n/).find(block => block.trim() && !/^\s*#{1,6}\s/.test(block) && !/^\s*```/.test(block)) || title
  const description = plain(String(parsed.data.description || first)).slice(0, 280)
  const authorList = Array.isArray(parsed.data.authors) ? parsed.data.authors.map(String) : parsed.data.author ? [String(parsed.data.author)] : /\bcosmolog(?:y|ical|ies)\b/i.test(title) ? ['marici.Benincasa'] : ['marici.Nima']
  const date = `${dateKey.slice(0,4)}-${dateKey.slice(4,6)}-${dateKey.slice(6,8)}`
  const body = parsed.content.replace(/^\s*#\s+.+\r?\n+/, '')
    .replace(/^\s*\\\[[ \t]*$/gm, () => '$$').replace(/^\s*\\\][ \t]*$/gm, () => '$$')
    .replace(/\\\((.*?)\\\)/g, (_, formula) => `$${formula}$`)
  records.push({ entry, date, dateKey, title, slug, description, authorLabel: authorList.join(', '), authors: authorList, kind: String(parsed.data.kind || 'research'), body, source: `src/ledger/${relative}` })
}
records.sort((a,b) => a.entry-b.entry || a.slug.localeCompare(b.slug))
const ids = new Set()
for (const item of records) { if (ids.has(item.entry)) throw new Error(`Duplicate public ledger entry ${item.entry}`); ids.add(item.entry) }
const byEntry = new Map(records.map(item => [item.entry, item]))
for (let i=0;i<records.length;i++) {
  const record = records[i]
  const previous = records[i-1]
  const next = records[i+1]
  let body = record.body
    .replace(/\]\((?:\.\.\/)*(?:research|src)\/([^)]*)\)/g, (_, target) => `](https://github.com/andrey-kokoev/marici/blob/main/${target})`)
    .replace(/\b(?:ledger\s+)?entry\s+(\d{1,5})\b/gi, (all, raw) => {
      const target = byEntry.get(Number(raw))
      return target ? `[${all}](/research/ledger/${target.slug})` : all
    })
  const pageUrl = `/research/ledger/${record.slug}/`
  const article = markdown.render(body)
  const previousLink = previous ? `<a href="/research/ledger/${previous.slug}/">← ${renderTitle(previous.title)}</a>` : '<span></span>'
  const nextLink = next ? `<a href="/research/ledger/${next.slug}/">${renderTitle(next.title)} →</a>` : '<span></span>'
  const document = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${htmlEscape(record.description)}"><title>${htmlEscape(plain(record.title))} · Marici ledger</title><link rel="stylesheet" href="/katex/katex.min.css"><style>body{margin:0;background:#fcfaf7;color:#29251f;font:16px/1.7 system-ui,sans-serif}.site-head,main{max-width:900px;margin:auto;padding:20px}.site-head{border-bottom:1px solid #ddd5cb}.site-head a{margin-right:1.2rem;color:#80502e}main{padding-top:42px}h1{line-height:1.15;letter-spacing:-.03em}h2,h3{margin-top:2em}a{color:#80502e}pre{overflow:auto;padding:1rem;background:#f0ece7;border-radius:8px}code{font-size:.9em}table{border-collapse:collapse;display:block;overflow:auto}td,th{border:1px solid #d9d2c8;padding:.5rem .7rem;text-align:left}.meta{color:#716b64;font-size:.9rem}.pager{display:flex;justify-content:space-between;gap:1rem;border-top:1px solid #ddd5cb;padding-top:1.4rem;margin-top:3rem}.pager a{max-width:48%}</style></head><body>${marker}<header class="site-head"><a href="/">Marici</a><a href="/research/theory/">Theory</a><a href="/research/results/">Results</a><a href="/research/ledger/">Ledger</a><a href="/explore/graph/">Graph</a></header><main><p class="meta">Entry ${record.entry} · ${record.date} · ${htmlEscape(record.authorLabel)} · ${htmlEscape(record.kind)}</p><h1>${renderTitle(record.title)}</h1>${article}<p class="meta"><a href="https://github.com/andrey-kokoev/marici/blob/main/${htmlEscape(record.source)}">View source on GitHub</a></p><nav class="pager">${previousLink}${nextLink}</nav></main></body></html>`
  const pageDir = path.join(ledgerPublic, record.slug)
  await fs.mkdir(pageDir, { recursive: true })
  await fs.writeFile(path.join(pageDir, 'index.html'), document, 'utf8')
  record.url = pageUrl
}
await fs.writeFile(path.join(ledgerPublic, 'index.json'), JSON.stringify(records.map(({body, ...entry}) => entry)), 'utf8')
ledgerCount = records.length
}

const results = JSON.parse(await fs.readFile(path.join(root,'src','data','results-physics.json'),'utf8'))
for (const item of results) {
  const body = `<!-- Generated by scripts/prepare-website.mjs. Edit src/data/results-physics.json instead. -->\n\n# ${item.domain}\n\n**${item.status}**\n\n${item.details}\n\n${item.checker ? `**Checker:** \`${item.checker}\`\n\n` : ''}${item.result ? `**Result artifact:** \`${item.result}\`\n\n` : ''}[Back to results](/research/results/)\n`
  await fs.writeFile(path.join(resultsOut, `${slugify(item.slug)}.md`), body, 'utf8')
}
for (const [source, target] of [
  ['landing-page.md', path.join(root, 'website', 'index.md')],
  ['theory-page.md', path.join(root, 'website', 'research', 'theory', 'index.md')],
  ['results-page.md', path.join(root, 'website', 'research', 'results', 'index.md')],
  ['system-characteristics.md', path.join(root, 'website', 'research', 'system-characteristics', 'index.md')],
]) {
  const content = (await fs.readFile(path.join(root, 'docs', source), 'utf8'))
    .replaceAll('](/results/#bridges)', '](#postnikov-descent)')
    .replaceAll('](/results/#control)', '](#the-universe-as-a-feedback-system)')
    .replaceAll('](/results/#frontier)', '](/research/results/)')
    .replaceAll('](/results/', '](/research/results/')
    .replaceAll('](/theory/', '](/research/theory/')
    .replace(/\]\(\.\.\/research\/([^)]*)\)/g, (_, relative) => `](https://github.com/andrey-kokoev/marici/blob/main/research/${relative})`)
    .replaceAll('](theory-page.md', '](/research/theory/')
  await fs.mkdir(path.dirname(target), { recursive: true })
  await fs.writeFile(target, content, 'utf8')
}
const landingSource = await fs.readFile(path.join(root, 'docs', 'landing-page.md'), 'utf8')
const predictionStart = landingSource.indexOf('## Predictions')
const derivationStart = landingSource.indexOf('**Construction and formalizations**', predictionStart)
const predictions = predictionStart >= 0 ? landingSource.slice(predictionStart, derivationStart > predictionStart ? derivationStart : undefined) : '# Predictions\n\nSee the [landing page](/#predictions).\n'
await fs.mkdir(path.join(root,'website','research','predictions'), { recursive: true })
await fs.writeFile(path.join(root, 'website', 'research', 'predictions', 'index.md'), `# Falsifiable predictions\n\n${predictions.replace(/^## Predictions\s*/,'').replaceAll('](/results/', '](/research/results/').replaceAll('](/theory/', '](/research/theory/')}`, 'utf8')
console.log(pagesOnly
  ? `Prepared authored content and ${results.length} result pages; ledger and public assets unchanged.`
  : `Prepared ${ledgerCount} public ledger entries and ${results.length} result pages.`)
