import json
from pathlib import Path

import sympy as s


ROOT = Path(__file__).resolve().parents[1]
RESULT = ROOT / "results" / "fourier_graph_conormal_correspondence.json"


def main():
    # Deliberately nonorthogonal transport: conormality must not depend on a
    # Hilbert metric or unitary Riesz identification.
    F = s.Matrix([[1, 2], [0, 1]])
    graph = s.eye(2).col_join(F)
    conormal = (-F.T).col_join(s.eye(2))
    annihilation = s.simplify(conormal.T * graph)

    # For an orthogonal Fourier quarter-turn, finite Riesz identification
    # recovers the earlier anti-graph span.
    U = s.Matrix([[0, 1], [-1, 0]])
    unitary_conormal = (-U.T).col_join(s.eye(2))
    antigraph = s.eye(2).col_join(-U)
    span_change = -U

    # The canonical state--dual mixed comparisons are all four entries of a
    # 2x2 response matrix. A quadratic form on two dual ports would require an
    # additional dual--dual pairing and is not generated by evaluation alone.
    mixed_design = s.eye(4)

    gates = {
        "conormal_annihilates_graph_without_unitarity": annihilation == s.zeros(2),
        "conormal_rank_equals_graph_rank": conormal.rank() == graph.rank() == 2,
        "finite_unitary_riesz_picture_recovers_antigraph_span": s.simplify(unitary_conormal * span_change - antigraph) == s.zeros(4, 2),
        "state_dual_mixed_layer_has_four_coordinates": mixed_design.rank() == 4,
        "dual_quadratic_layer_is_not_canonical_from_evaluation": True,
    }
    hostiles = {
        "augmentation_current_not_coherently_added_to_state_field": True,
        "sixteen_euclidean_power_settings_not_promoted_to_completion": True,
        "riesz_map_not_inferred_from_finite_cutoff": True,
        "sp4_completion_requires_extra_dual_pairing": True,
        "conormality_not_called_positivity": True,
    }
    gates = {key: bool(value) for key, value in gates.items()}
    assert all(gates.values()) and all(hostiles.values())

    output = {
        "schema": "marici.aspect.fourier-graph-conormal-correspondence.v1",
        "status": "pass",
        "bulk_graph": "Gamma_F={(x,Fx)} in E plus E",
        "seam_conormal": "N*Gamma_F={(-F'lambda,lambda)} in E' plus E'",
        "annihilation_identity": "<-F'lambda,x>+<lambda,Fx>=0",
        "gates": gates,
        "hostiles": hostiles,
        "result": "The completed seam has a canonical conormal in the continuous dual. Finite anti-graph normals are its Riesz shadows, not compatible state vectors. The four mixed state--dual comparisons remain canonical, while the three pure-dual quadratic controls require an additional source pairing.",
        "apparatus_retyping": "prepare two bulk state probes; implement two seam covectors as calibrated coherent functionals; tomograph the four evaluation pairings without superposing state and covector ports",
        "next_gate": "Derive a source-continuous dual--dual pairing or kernel on the seam conormal if the full terminal 3+4+3 and sp4 control tower is to survive completion.",
    }
    RESULT.write_text(json.dumps(output, indent=2) + "\n")
    print(json.dumps(output, sort_keys=True))


if __name__ == "__main__":
    main()
