#!/usr/bin/env python3
import json
from pathlib import Path
import sympy as s

ROOT=Path(__file__).resolve().parents[1]
RESULT=ROOT/"results"/"schur_jet_interaction_net.json"
q=s.symbols("q")

A=s.Matrix([[1,0,1],[-q,1,0],[1,1,0]])
B=s.Matrix([0,0,1])
C=s.Matrix([[0,-q,0]])
E=s.Matrix([[1]])
R=s.simplify(A.inv())
S=s.simplify(E-C*R*B)

redexes={
    "local_new_cell":s.diff(E,q),
    "incidence_entry":-s.diff(C,q)*R*B,
    "retained_transport":C*R*s.diff(A,q)*R*B,
    "incidence_exit":-C*R*s.diff(B,q),
}
Sprime=s.simplify(sum(redexes.values(),s.zeros(1)))
current=s.simplify((S.inv()*Sprime).trace())
diagonal=s.simplify((E.inv()*s.diff(E,q)).trace())
direct_loop=s.simplify(C*R*B)
cut_residue=s.simplify(-direct_loop)
reduced=s.simplify(E+cut_residue)
AY=A.row_join(B).col_join(C.row_join(E))
det_increment=s.simplify(s.diff(AY.det(),q)/AY.det()-s.diff(A.det(),q)/A.det())

checks={
    "new_cell_diagonal_is_blind":diagonal==0,
    "continuation_loop_is_nonzero":direct_loop!=s.zeros(1),
    "interaction_reduction_is_schur_complement":s.simplify(reduced-S)==s.zeros(1),
    "four_local_jet_redexes_sum_to_schur_jet":s.simplify(Sprime-s.diff(S,q))==s.zeros(1),
    "net_current_is_nonzero":current!=0,
    "net_current_equals_determinant_increment":s.simplify(current-det_increment)==0,
}
hostiles={
    "erase_residue_returns_false_zero":diagonal==0 and current!=diagonal,
    "keep_only_new_cell_rejected":s.diff(E,q)==s.zeros(1) and Sprime!=s.zeros(1),
    "keep_coupling_but_erase_retained_transport_rejected":s.simplify(redexes["local_new_cell"]+redexes["incidence_entry"]+redexes["incidence_exit"]-s.diff(S,q))!=s.zeros(1),
}
out={
    "schema":"marici.aspect.schur-jet-interaction-net.v1",
    "status":"pass" if all(checks.values()) and all(hostiles.values()) else "fail",
    "interaction_rule":"NEW(E) joined to RETAINED(A) by B,C reduces to EFFECTIVE(E-C A^-1 B)",
    "jet_redexes":{k:str(s.simplify(v[0])) for k,v in redexes.items()},
    "schur_complement":str(S[0]),
    "schur_first_jet":str(Sprime[0]),
    "observable_current":str(current),
    "diagonal_shadow":str(diagonal),
    "checks":checks,
    "hostiles":hostiles,
    "explanation":"The observable is generated by the closed continuation loop through the retained state. The isolated new node is silent.",
}
RESULT.write_text(json.dumps(out,indent=2)+"\n",encoding="utf-8")
print(json.dumps(out,indent=2))
raise SystemExit(0 if out["status"]=="pass" else 1)
