#!/usr/bin/env python3
import copy,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];sys.path.insert(0,str(ROOT/"research/aspect/scc"))
from globular_tower_compiler import compile_globular_tower
cpath=ROOT/"research/aspect/contracts/scc-globular-observer-tower.v1.json";rpath=ROOT/"research/aspect/results/scc_globular_observer_tower.json";base=json.loads(cpath.read_text(encoding="utf-8"))
def compiled(mutate=lambda c:None):
    fixture=copy.deepcopy(base);mutate(fixture);return compile_globular_tower(fixture)
def run(name,mutate,expected):
    report=compiled(mutate);return {"id":name,"expected_first_failure":expected,"actual_first_failure":report.get("first_failed_gate"),"passed":report.get("first_failed_gate")==expected}
def static_theta(c):
    c["source_incidence"].update(matrix=[[1,0,0,0,0,0],[0,1,0,0,0,0],[0,0,1,0,0,0],[0,0,0,1,0,0]],required_rank=6)
def dynamic_theta(c):
    c["source_incidence"].update(matrix=[[1,0,0,0,0,0],[0,1,0,0,0,0],[0,0,1,0,0,0],[0,0,0,1,0,0]],required_rank=4)
    c["source_action_observability"]={"source_authorized":True,"observer":[[1,1,1,1,1,1]],"diagonal_labels":["log(2)","log(3)","log(5)","log(7)","log(11)","log(13)"],"distinct_labels_source_derived":True,"powers":[0,1,2,3,4,5],"required_rank":6,"arithmetic_dependency":"strict monotonicity of log on distinct primes"}
    c["completion"]["strictness"]["uniform_over_completion"]=False
static_report=compiled(static_theta);dynamic_report=compiled(dynamic_theta)
hostiles=[run("missing_boundary",lambda c:c["cells"][-1].update(target_boundary="absent"),"globular_boundary"),run("nonparallel_boundary",lambda c:c["cells"][5].update(parallel_signature="other"),"globular_parallelism"),run("frozen_six_boundary_rank_1",lambda c:c["source_incidence"].update(matrix=[[1,1,1,1,1,1]]),"finite_source_incidence_realization"),run("conflate_kernel_cokernel",lambda c:c["residuals"][1]["seed_map"].update(kind="inclusion"),"typed_residual"),run("unboxed_child",lambda c:c["child_towers"][0].update(boxed=False),"boxed_child_tower"),run("unauthorized_promotion",lambda c:c["promotions"][0]["certificates"].update(source_authorized=False),"promotion_authority"),run("unchanged_reentry",lambda c:c["termination"][0].update(after=2),"termination"),run("inconsistent_separation_continuity_margin",lambda c:c["completion"]["incompatibility_cells"][0].update(all_three_admitted=True),"completion_incompatibility"),run("misclassify_fourier_bohr_as_continuous",lambda c:c["completion"]["constructor_branches"][0].update(frequency_norm_continuous=True),"constructor_branch_typing"),run("hybrid_without_rigging",lambda c:c["completion"]["constructor_branches"][0].update(rigging={}),"constructor_branch_typing"),run("diag_1_over_n_nonclosed",lambda c:c["completion"]["strictness"].update(closed_complemented_range=False,continuous_generalized_inverse=False),"completion_strictness"),run("finite_vandermonde_not_uniform",lambda c:c["completion"]["strictness"].update(uniform_over_completion=False),"completion_strictness"),run("unilateral_shift_cokernel",lambda c:c["completion"]["supported_finite_defect"].update(fourier_character=""),"supported_finite_defect"),run("no_contracting_homotopy",lambda c:c["completion"]["acyclicity"].update(source_authorized=False,contracting_homotopy=""),"acyclicity"),run("unjoined_critical_pair",lambda c:c["critical_pairs"][0].update(join_witness=""),"rewrite_confluence"),run("missing_coefficient_lens",lambda c:c.update(global_coherence=[x for x in c["global_coherence"] if x["lens"]!="coefficients"]),"global_coherence")]
positive=compiled();verdicts={"static_carrier":{"rank":4,"of":6,"odd_kernel_dimension":2,"first_failed_gate":static_report.get("first_failed_gate"),"static_boundary_isomorphism":False},"action_generated":{"finite_rank":6,"action":"diag(log p)","static_endpoint_or_archimedean_realization":False,"first_failed_gate":dynamic_report.get("first_failed_gate"),"uniform_lower_bound":False,"arithmetic_dependency":"bounded prime gaps for approximate-kernel hostile","forbidden_promotion":"full-orbit injectivity does not imply a lower frame bound without topology and margin evidence"}}
passed=positive["passed"] and all(x["passed"] for x in hostiles) and verdicts["static_carrier"]["first_failed_gate"]=="finite_source_incidence_realization" and verdicts["action_generated"]["first_failed_gate"]=="completion_strictness"
out={"schema":"marici.aspect.scc-globular-observer-tower-check.v1","positive_passed":positive["passed"],"positive":positive,"theta_verdicts":verdicts,"hostiles":hostiles,"hostile_count":len(hostiles),"passed":passed,"claim":"static incidence and action-generated observability are noninterchangeable verdicts"};rpath.write_text(json.dumps(out,indent=2)+"\n",encoding="utf-8");print(json.dumps(out,indent=2));raise SystemExit(0 if passed else 1)
#!/usr/bin/env python3
import copy,json,sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];sys.path.insert(0,str(ROOT/"research/aspect/scc"))
from globular_tower_compiler import compile_globular_tower
cpath=ROOT/"research/aspect/contracts/scc-globular-observer-tower.v1.json";rpath=ROOT/"research/aspect/results/scc_globular_observer_tower.json";base=json.loads(cpath.read_text(encoding="utf-8"))
def run(name,mutate,expected):
    fixture=copy.deepcopy(base);mutate(fixture);report=compile_globular_tower(fixture)
    return {"id":name,"expected_first_failure":expected,"actual_first_failure":report.get("first_failed_gate"),"passed":report.get("first_failed_gate")==expected}
hostiles=[run("missing_boundary",lambda c:c["cells"][-1].update(target_boundary="absent"),"globular_boundary"),run("nonparallel_boundary",lambda c:c["cells"][5].update(parallel_signature="other"),"globular_parallelism"),run("theta_rank_1_of_6_without_authorized_action",lambda c:c["source_action_observability"].update(source_authorized=False),"finite_source_incidence_realization"),run("conflate_kernel_cokernel",lambda c:c["residuals"][1]["seed_map"].update(kind="inclusion"),"typed_residual"),run("unboxed_child",lambda c:c["child_towers"][0].update(boxed=False),"boxed_child_tower"),run("unauthorized_promotion",lambda c:c["promotions"][0]["certificates"].update(source_authorized=False),"promotion_authority"),run("unchanged_reentry",lambda c:c["termination"][0].update(after=2),"termination"),run("diag_1_over_n_nonclosed",lambda c:c["completion"]["strictness"].update(closed_complemented_range=False,continuous_generalized_inverse=False),"completion_strictness"),run("finite_vandermonde_not_uniform",lambda c:c["completion"]["strictness"].update(uniform_over_completion=False),"completion_strictness"),run("unilateral_shift_cokernel",lambda c:c["completion"]["supported_finite_defect"].update(fourier_character=""),"supported_finite_defect"),run("no_contracting_homotopy",lambda c:c["completion"]["acyclicity"].update(source_authorized=False,contracting_homotopy=""),"acyclicity"),run("unjoined_critical_pair",lambda c:c["critical_pairs"][0].update(join_witness=""),"rewrite_confluence"),run("missing_coefficient_lens",lambda c:c.update(global_coherence=[x for x in c["global_coherence"] if x["lens"]!="coefficients"]),"global_coherence")]
positive=compile_globular_tower(base);out={"schema":"marici.aspect.scc-globular-observer-tower-check.v1","positive_passed":positive["passed"],"positive":positive,"hostiles":hostiles,"hostile_count":len(hostiles),"passed":positive["passed"] and all(x["passed"] for x in hostiles),"active_theta_cutoff_rank":6,"active_theta_first_failure":"completion_strictness","static_boundary_isomorphism":False,"claim":"runtime semantics, not empty schema slots"};rpath.write_text(json.dumps(out,indent=2)+"\n",encoding="utf-8");print(json.dumps(out,indent=2));raise SystemExit(0 if out["passed"] else 1)
