#!/usr/bin/env python3
"""Accept the two-prime witness-bearing physical half-twist candidate fixtures."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];B=ROOT/'research/benincasa/results';R=ROOT/'research/aspect/results';a=json.loads((B/'cosmology_half_twist_syzygy_provenance_p32003.json').read_text());b=json.loads((B/'cosmology_half_twist_syzygy_provenance_p32009.json').read_text());assert a['passed'] and b['passed'];assert a['candidate_count']==b['candidate_count']==8;assert a['special_rank']==b['special_rank']==4275;assert a['dependency_count']==b['dependency_count']==5505;rows=[]
for x,y in zip(a['candidates'],b['candidates'],strict=True):
 assert x['candidate']==y['candidate'];assert x['pivot_column']==y['pivot_column'];assert x['pivot_label']==y['pivot_label'];assert x['source_coefficient_count']==y['source_coefficient_count'];assert set(x['source_coefficients'])==set(y['source_coefficients']);assert set(x['generator_coordinates'])==set(y['generator_coordinates']);assert set(x['derivative_replay_coordinates'])==set(y['derivative_replay_coordinates']);rows.append({'candidate':x['candidate'],'pivot_column':x['pivot_column'],'pivot_label':x['pivot_label'],'source_coefficient_count':x['source_coefficient_count'],'source_support_cross_prime_equal':True,'generator_support_cross_prime_equal':True,'derivative_replay_support_cross_prime_equal':True})
counts=[x['source_coefficient_count'] for x in a['candidates']];assert counts==[21,21,57,101,48,86,111,172]
out={'schema':'marici.aspect.half-twist-syzygy-provenance-acceptance.v1','primes':[32003,32009],'gamma_mode':'half','special_rank':4275,'dependency_count':5505,'candidate_count':8,'candidates':rows,'all_special_replays_zero':a['all_special_replays_zero'] and b['all_special_replays_zero'],'labelled_supports_cross_prime_stable':True,'candidate_coordinates_are_source_version_bound':True,'dual_annihilation_tested':False,'tau_p_map_constructed':False,'passed':True};(R/'half_twist_syzygy_provenance_acceptance.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'status':'passed','candidates':8,'counts':counts}))
