#!/usr/bin/env python3
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];C=ROOT/'research/aspect/contracts/cosmology-tau-lift-constructor-audit.v1.json';O=ROOT/'research/aspect/results/cosmology_tau_lift_constructor_audit.json'
def main():
 c=json.loads(C.read_text());g=c['rank26_gate'];load=lambda k:json.loads((ROOT/c['candidate_inputs'][k]).read_text());q=load('quotient_stability');s=load('syzygy_summary');a=load('syzygy_acceptance');f=load('five_mark_kernel');sp=load('special_provenance');du=load('dual_provenance');ga=load('gamma_sensitivity');ds3=load('candidate_dual_selector_32003');ds9=load('candidate_dual_selector_32009');dsc=load('candidate_dual_cross_prime');tt3=load('dual_to_triple_transport_32003');tt9=load('dual_to_triple_transport_32009');ph=load('physical_half_twist_gate');dl=load('directional_linearity_gate');xs=load('xy_tangent_rank_strata')
 checks={'raw_normal_absorption':q['passed'] and q['all_unit_normal_extensions_after_tangent']==0,'seven_two_prime_fixtures':s['passed'] and s['candidate_count']==g['candidate_count'],'acceptance_passed':a['passed'] and a['principal_three_wall_cone_candidates']==[],'projection_kernel_closes_cancellation':f['passed'] and all(x['extra_family_projection_rank']==g['extra_family_projection_rank'] and x['candidate_kernel_dimension']==g['extra_family_kernel_dimension'] and not x['nonzero_principal_three_wall_descent_exists'] for x in f['results'].values()),'special_full_replay':sp['passed'] and sp['full_rank26_reduction_completed'] and sp['all_dependencies_replay_zero'],'dual_full_replay':du['passed'] and du['full_layer_completed'] and du['all_dependencies_replay_zero'],'seven_dual_annihilation_witnesses_two_prime':dsc['passed'] and all(ds['passed'] and ds['all_seven_annihilated'] and all(x['annihilation_replay_zero'] for x in ds['candidates']) for ds in (ds3,ds9)),'triple_coherence_by_shift_transport':all(tt['passed'] and tt['source_relations_checked']==9780 and not tt['independent_triple_reduction_required'] for tt in (tt3,tt9)),'normal_tangent_equality_gamma_robust':ga['passed'] and ga['normal_tangent_equality_gamma_robust_on_tested_modes'] and not ga['image_rank_gamma_invariant'],'physical_half_twist_is_canonical_and_zero_mod_tangent_through16':ph['passed'] and ph['physical_gamma']=='-1/2' and ph['ambient_degrees']==[8,10,12,14,16] and ph['p_normal_image_mod_tangent_ranks']=={str(d):0 for d in (8,10,12,14,16)} and ph['generic_gamma5_prior_results_are_not_physical_half_twist'],'source_directional_linearity_cell':dl['passed'] and dl['rowwise_verified'] and not dl['surjectivity_of_difference_derived'],'naive_xy_transport_rejected_by_typed_rank_strata':xs['passed'] and xs['rank_drop_explained_on_sample'] and not xs['nearby_specialization_constructed'] and not xs['same_point_normal_image_equality_derived'],'unbounded_no_go_not_claimed':not q['unbounded_stabilization_proved'] and not ph.get('unbounded_stabilization_proved',False)}
 classification='physical_half_twist_through_degree16_normal_image_equals_tangent_no_tau_lift';passed=all(checks.values()) and c['assessment']==classification;out={'schema':'marici.aspect.cosmology-tau-lift-constructor-audit.result.v1','status':'passed' if passed else 'failed','classification':classification if passed else 'audit_failed','checks':checks,'physical_gamma':'-1/2','physical_resolved_image_ranks':ph['resolved_syzygy_image_ranks'],'generic_gamma5_candidate_count':7,'generic_candidates_are_not_physical_target':True,'principal_three_wall_source_packet':False,'surviving_p_normal_line':False,'triple_coherence_status':'constructed_by_dual_shift_transport_for_auxiliary_gamma5_candidates','unbounded_no_go_proved':False,'tau_p_lift_constructed':False,'next_gates':['derive physical half-twist p-tangent absorption from source family identities or prove unbounded stabilization','construct a new source comparison morphism'],'passed':passed};assert passed;O.write_text(json.dumps(out,indent=2)+'\n');print(json.dumps({'status':out['status'],'classification':out['classification']}))
if __name__=='__main__':main()
