"""Source relation and flatness of the two soft-triangle occurrence routes."""

from __future__ import annotations

import json

import sympy as sp


def main() -> None:
    eta, xi, kappa, t = sp.symbols("eta xi kappa t")
    q23 = 2 + eta * xi
    q31 = (t - 1) - eta * kappa / 2

    # Abstract route symbols are represented as a two-component free module.
    relation = sp.Matrix([[q23, -q31]])
    exceptional_relation = relation.subs(eta, 0)
    first_normal_relation = relation.applyfunc(
        lambda value: sp.diff(value, eta).subs(eta, 0)
    )

    # Over Q[[eta]], q23 has constant term two and is a unit.  The explicit
    # section e31 -> ((q31/q23),1) identifies the quotient with one free line.
    section = sp.Matrix([sp.cancel(q31 / q23), 1])
    relation_on_section = sp.simplify((relation * section)[0])

    physical_nodes = [(-1, -1, 3), (-1, 1, 1), (1, -1, 1), (1, 1, 3)]
    fibers = []
    for kap, xx, tt in physical_nodes:
        row = [sp.simplify(value.subs({eta: 0, kappa: kap, xi: xx, t: tt}))
               for value in relation]
        rational_rank = sp.Matrix([row]).rank()
        assert rational_rank == 1
        fibers.append({
            "kappa": kap,
            "xi": xx,
            "t": tt,
            "relation_row": [str(value) for value in row],
            "rational_relation_rank": rational_rank,
            "rational_cokernel_rank": 1,
            "integral_torsion": "Z/2",
        })

    checks = {
        "exact_route_relation": relation_on_section == 0,
        "exceptional_relation": exceptional_relation == sp.Matrix([[2, 1 - t]]),
        "first_normal_relation": first_normal_relation == sp.Matrix([[xi, kappa / 2]]),
        "q23_is_rational_formal_unit": q23.subs(eta, 0) == 2,
        "all_node_fibers_have_one_rational_line": all(
            record["rational_cokernel_rank"] == 1 for record in fibers
        ),
    }
    if not all(checks.values()):
        raise AssertionError({name: value for name, value in checks.items() if not value})

    print(json.dumps({
        "schema": "marici.benincasa.soft-triangle-occurrence-coherence.v1",
        "normalized_relation": "(2+eta*xi)e23-(t-1-eta*kappa/2)e31=0",
        "exceptional_relation": ["2", "1-t"],
        "first_normal_relation": ["xi", "kappa/2"],
        "rational_quotient": "free rank-one line generated by e31",
        "integral_physical_node_fibers": "Z plus Z/2 at t=1 and t=3",
        "integral_defect_classification": "existing occurrence-identification factor two",
        "node_fibers": fibers,
        "checks": checks,
        "status": "source_occurrence_coherence_is_rationally_flat_with_only_existing_integral_factor_two",
        "scope": (
            "route-presentation module only; no claim about the A1 vanishing-cycle "
            "differential, physical period, or integral saturation of the full complex"
        ),
    }, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
