"""Projection discriminants of the dimensionless soft-triangle kernel."""

from __future__ import annotations

import json

import sympy as sp


def main() -> None:
    t, kappa, xi = sp.symbols("t kappa xi")
    kernel = (
        t**4
        - (10 + 8 * kappa * xi) * t**2
        + 16 * kappa**2 + 40 * kappa * xi + 16 * xi**2 + 9
    )
    disc_xi = sp.factor(sp.discriminant(kernel, xi))
    disc_kappa = sp.factor(sp.discriminant(kernel, kappa))
    disc_t = sp.factor(sp.discriminant(kernel, t))

    expected_xi = 64 * (kappa**2 - 1) * (t**2 - 1) * (t**2 - 9)
    expected_kappa = 64 * (xi**2 - 1) * (t**2 - 1) * (t**2 - 9)
    # Even quartic t^4+b t^2+c: its t-discriminant is
    # 16*c*(b^2-4c)^2.
    constant_t = 16 * kappa**2 + 40 * kappa * xi + 16 * xi**2 + 9
    expected_t = sp.factor(
        16
        * constant_t
        * (64 * (1 - kappa**2) * (1 - xi**2)) ** 2
    )

    checks = {
        "xi_projection_closes_on_signed_arrangement": sp.expand(
            disc_xi - expected_xi
        ) == 0,
        "kappa_projection_closes_on_signed_arrangement": sp.expand(
            disc_kappa - expected_kappa
        ) == 0,
        "t_projection_has_only_endpoint_and_zero_root_support": sp.expand(
            disc_t - expected_t
        ) == 0,
    }
    if not all(checks.values()):
        raise AssertionError({
            "failed": {name: value for name, value in checks.items() if not value},
            "disc_t": str(disc_t),
            "expected_t": str(expected_t),
        })

    print(json.dumps({
        "schema": "marici.benincasa.soft-triangle-dimensionless-discriminants.v1",
        "kernel": str(kernel),
        "projection_discriminants": {
            "xi": str(disc_xi),
            "kappa": str(disc_kappa),
            "t": str(disc_t),
        },
        "support_classification": {
            "kappa=+-1": "existing base-triangle endpoint cover",
            "xi=+-1": "existing loop-triangle endpoint cover",
            "t=+-1": "signed a/p face branches; t=1 is the q_g2/q_g31 collision",
            "t=+-3": "signed a/p face branches; t=-3 is the q_g3 marked section",
            "constant_t=0": "even-quartic zero-root collision, inherited from the same Cayley-Menger coefficient kernel",
        },
        "checks": checks,
        "status": "dimensionless_projection_discriminants_close_on_frozen_endpoint_signed_face_and_coordinate_boundary_arrangement",
        "scope": (
            "projection discriminants only; no assertion that every higher-codimension "
            "relative-cohomology extension is generated by these divisors"
        ),
    }, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
