"""Verify the exact generic-lower radical census and homogeneous collapse."""
import json,sys,hashlib
from pathlib import Path
sys.stdout=open(r"C:\Users\andrey\src\marici\research\benincasa\generic_lower_verifier_run.log","w",encoding="utf-8")
sys.stderr=sys.stdout
sys.path.insert(0,r"C:\Users\andrey\src\marici\research\benincasa\.tmp_sympy")
import sympy as sp

root=Path(r"C:\Users\andrey\src\marici")
coll_path=root/"research/benincasa/generic_lower_collision_result.json"
tan_path=root/"research/benincasa/generic_lower_single_tangency_result.json"
coll=json.loads(coll_path.read_text(encoding="utf-8"))
tan=json.loads(tan_path.read_text(encoding="utf-8"))
X1,X2,X3,P1,P2,P3=sp.symbols("X1 X2 X3 P1 P2 P3")
loc={str(v):v for v in (X1,X2,X3,P1,P2,P3)}
lam=(P1-P2-P3)*(P1-P2+P3)*(P1+P2-P3)*(P1+P2+P3)
expected={
 "g1__g2":-4*(P1**2-X1**2)*(P2**2-X2**2)*lam*(P3**2-(X1-X2)**2),
 "g1__g3":-4*(P1**2-X1**2)*(P3**2-X3**2)*lam*(P2**2-(X1-X3)**2),
 "g2__g3":-4*(P2**2-X2**2)*(P3**2-X3**2)*lam*(P1**2-(X2-X3)**2),
 "g2__g23":-4*(P2**2-X2**2)*(P3**2-X3**2)*lam*(P1**2-(X2+X3)**2),
 "g3__g23":-4*(P2**2-X2**2)*(P3**2-X3**2)*lam*(P1**2-(X2+X3)**2)}
checks=[]
for key,want in expected.items():
    got=sp.sympify(coll["pairs"][key]["discriminant"],locals=loc)
    assert sp.expand(got-want)==0,key
    assert sp.factor(got.subs({X1:P1,X2:P2,X3:P3}))==0,key
    checks.append("pair_radical_"+key)

allvars=(X1,X2,X3,P1,P2,P3)
single_factor_count=0
for name,data in tan["planes"].items():
    assert sp.sympify(data["leading_coefficient_U"],locals=loc) != 0
    for field in ("U_zero_factor_list","interior_factor_list"):
        for raw,exp in data[field]:
            q=sp.Poly(sp.sympify(raw,locals=loc),*allvars)
            assert q.total_degree()==1,(name,field,raw)
            assert exp==2,(name,field,raw,exp)
            single_factor_count+=1
    checks.append("single_tangency_linear_"+name)

t123=coll["triples"]["g1__g2__g3"]
t23=coll["triples"]["g2__g3__g23"]
want_h=(P1-P2-P3)**2*(P1-P2+P3)**2*(P1+P2-P3)**2/4
assert sp.expand(sp.sympify(t123["homogeneous_K_value"],locals=loc)-want_h)==0
assert sp.sympify(t23["homogeneous_K_value"],locals=loc)==0
checks += ["triple_123_homogeneous_square","triple_23_homogeneous_zero"]

def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
out={
 "schema":"marici.benincasa.generic_lower_verifier.v1",
 "status":"pass",
 "claim":"generic algebraic extension is generated by frozen Cayley-Menger/marked-plane collision geometry",
 "pair_radicands":{k:sp.sstr(sp.factor(v)) for k,v in expected.items()},
 "unique_pair_radicand_count":4,
 "finite_pair_count":5,
 "single_tangency_factor_occurrences_checked":single_factor_count,
 "single_tangencies_all_signed_linear_squares":True,
 "parallel_collision":"X1-X2-X3",
 "triple_123_homogeneous":"signed momentum-triangle square",
 "triple_23_homogeneous":"zero",
 "homogeneous_pair_radicands_zero":True,
 "new_carrier_datum":False,
 "classification":"Cayley-Menger coefficient and marked-relative-cycle support over unchanged energy/Cut carrier",
 "checks":checks,
 "evidence_sha256":{"collision":sha(coll_path),"single_tangency":sha(tan_path)}}
(root/"research/benincasa/generic_lower_verifier_result.json").write_text(
 json.dumps(out,indent=2)+"\n",encoding="utf-8")
print("GENERIC LOWER ALGEBRAIC LETTER VERIFIER PASS")
print("checks",len(checks),"single_factor_occurrences",single_factor_count)
