"""Source-generated collision currents and their nested-cut law.

No correction is fitted by solving for a metric or subtracting sampled forms.
"""
from pathlib import Path
from itertools import product
import sympy as s
import json,hashlib
ROOT=Path(__file__).resolve().parents[3]
p=ROOT/'research/grothendieck/results/ordinary-middle-block-green-obstruction.json'
prior=json.loads(p.read_text(encoding='utf-8'));assert prior['passed']
I=s.I
C=s.Matrix([[0,0,-1,1],[0,0,-1,1],[-1,-1,0,0],[1,1,0,0]])/2
sig=(1,-1,1,-1);mom=(0,0,1,1)
x,z,wb=s.symbols('x z wbar')
fbar,g=s.symbols('fbar g');F=s.symbols('Fbar0:4');G=s.symbols('G0:4')
flux=sum(C[a,b]*F[a]*G[b] for a in range(4) for b in range(4))
dflux=0;bulk=0;forcing=0
for a,b in product(range(4),repeat=2):
    dF=I*sig[a]*wb*F[a]-x**mom[a]*fbar
    dG=-I*sig[b]*z*G[b]-x**mom[b]*g
    dflux+=C[a,b]*(dF*G[b]+F[a]*dG)
    bulk+=C[a,b]*I*(sig[b]*z-sig[a]*wb)*F[a]*G[b]
    forcing+=C[a,b]*(x**mom[a]*fbar*G[b]+F[a]*x**mom[b]*g)
assert s.expand(dflux+bulk+forcing)==0
assert s.expand(forcing-(fbar*(G[3]-G[2])+(F[3]-F[2])*g))==0
# Signature-transformed observations also use the positive sewn coefficient.
A=(I*s.Matrix([[-1,1,1,1],[-1,1,-1,-1]])/2)*s.diag(I,-I,I,-I)
Mplus=A.H*A
positive_derivative=0;positive_bulk=0;positive_forcing=0
for a,b in product(range(4),repeat=2):
    positive_derivative+=Mplus[a,b]*((I*sig[a]*wb*F[a]-x**mom[a]*fbar)*G[b]+F[a]*(-I*sig[b]*z*G[b]-x**mom[b]*g))
    positive_bulk+=Mplus[a,b]*I*(sig[b]*z-sig[a]*wb)*F[a]*G[b]
    positive_forcing+=Mplus[a,b]*(x**mom[a]*fbar*G[b]+F[a]*x**mom[b]*g)
assert s.expand(positive_derivative+positive_bulk+positive_forcing)==0
assert s.expand(positive_forcing-(fbar*(G[0]+G[1])+(F[0]+F[1])*g))==0
den=-I*(z-wb)
assert s.cancel(dflux/den+(bulk+forcing)/den)==0
E0,Ec,E1=s.symbols('E0 Ec E1')
assert s.expand((E0-Ec)+(Ec-E1)-(E0-E1))==0

# Independent source incidence constructor: a coarsening erases selected
# memory-slot boundaries but leaves ordered features and their spectral labels.
words=((),('a',),('b',))
basis=list(product(words,repeat=3))
def left(u):return (u[0]+u[1],u[2])
def right(u):return (u[0],u[1]+u[2])
def all_(u):return (sum(u,()),)
def same_shape(u,v):return tuple(map(len,u))==tuple(map(len,v))
def kernel(u,v):
    a,b=sum(u,()),sum(v,())
    if len(a)!=len(b):return s.Integer(0)
    # Each factor has its OWN symbolic spectral numerator and denominator.
    out=s.Integer(1)
    for j,(c,d) in enumerate(zip(a,b)):
        out*=s.Symbol(f'N{j}_{c}_{d}')/s.Symbol(f'D{j}')
    return out

def collision(u,v,merge):
    # Enumerate newly matched slots BEFORE consulting any Green form.
    return kernel(u,v) if same_shape(merge(u),merge(v)) and not same_shape(u,v) else s.Integer(0)
def pairing(u,v):return kernel(u,v) if same_shape(u,v) else s.Integer(0)
checks=0;nonzero_collisions=0
for u,v in product(basis,repeat=2):
    tL=collision(u,v,left);tR=collision(u,v,right)
    tAll=collision(u,v,all_)
    assert s.expand(pairing(left(u),left(v))-pairing(u,v)-tL)==0
    assert s.expand(pairing(right(u),right(v))-pairing(u,v)-tR)==0
    assert s.expand(tL+collision(left(u),left(v),all_)-tAll)==0
    assert s.expand(tR+collision(right(u),right(v),all_)-tAll)==0
    if tAll!=0:nonzero_collisions+=1
    checks+=1
assert nonzero_collisions>0
# A separate, source-incidence vacuum term occurs when vertex/cut labels
# are forgotten. It is not generated by a nonzero-forcing integral.
# Both all-vacuum seam shapes have first edge 0->1, last edge 15->31,
# and middle endpoint 15; their first two-event endpoints are 3 and 5.
fine_shapes=((0,1,3,15,15,31),(0,1,5,15,15,31))
def forget_inner_vertex(shape):return shape[:2]+shape[3:]
vacuum_fine=s.Matrix(2,2,lambda i,j:int(fine_shapes[i]==fine_shapes[j]))
vacuum_coarse=s.Matrix(2,2,lambda i,j:int(forget_inner_vertex(fine_shapes[i])==forget_inner_vertex(fine_shapes[j])))
vacuum_current=s.Matrix(2,2,lambda i,j:int(i!=j and forget_inner_vertex(fine_shapes[i])==forget_inner_vertex(fine_shapes[j])))
assert vacuum_fine==s.eye(2) and vacuum_current==s.Matrix([[0,1],[1,0]])
assert vacuum_coarse==vacuum_fine+vacuum_current
# The previously proved ordinary cross-term is the same one-letter current.
weight=s.symbols('w_memory')
N,B,R=s.symbols('N_gh B_gh R_gh')
assert s.cancel((4*weight*N/den).subs(N,B+R)-4*weight*(B/den+R/den))==0
result={'schema':'marici.grothendieck.source-relative-green-sewing.v1','passed':True,
        'obstruction_certificate_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),
        'nested_cut_pairs_checked':checks,'nonzero_memory_shape_collisions':nonzero_collisions,
        'checks':{'tail_ode_generates_green_current':True,'fixed_port_forcing_reduction':True,'signature_transformed_observer_current':True,
                  'spatial_interface_flux_cancels_at_same_tail_state':True,
                  'collision_constructor_recovers_pulled_back_pairing':True,
                  'both_nested_merge_orders_have_identical_total_current':True,
                  'known_ordinary_cross_term_recovered':True,
                  'vacuum_incidence_channel_retained_separately':True},
        'scope':'Formal source-current and finite record-coarsening theorem. No spectral sampling, fitted metric, coarse-carrier isometry, or completed limit.'}
out=ROOT/'research/grothendieck/results/source-relative-green-sewing.json'
out.write_text(json.dumps(result,indent=2)+'\n',encoding='utf-8')
print(json.dumps(result,indent=2))
