"""Exact source-typing audit for surface disjoint union versus coproduct."""

from __future__ import annotations

import hashlib
import itertools
import json
from pathlib import Path

from sympy import Integer


ROOT = Path(__file__).resolve().parents[3]
ENTRY_07 = ROOT / "src/ledger/20260812-07 Surface Operations and the Cut Kernel.md"
ENTRY_10 = (
    ROOT / "src/ledger/20260812-10 Primitive-Symmetric Sewing Requirements.md"
)
ENTRY_46 = (
    ROOT
    / "src/ledger/20260813-46 Closed-Circuit Resolution and the Modular "
    "Counit Target.md"
)
OUT = (
    ROOT
    / "research/grothendieck/results/"
    "phase-i-surface-disjoint-union-typing.json"
)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def rel(path: Path) -> str:
    return str(path.relative_to(ROOT)).replace("\\", "/")


inputs = [ENTRY_07, ENTRY_10, ENTRY_46]
for path in inputs:
    assert path.is_file()

# Minimal object/arrow graph literally typed by entry 07.  A separating cut
# has a connected parent Sigma and disconnected result D = Sigma_L sqcup
# Sigma_R.  Mapping-class arrows are invertible within a surface type.  The
# cut arrow has source Sigma, not either component.
objects = ("Sigma", "Sigma_L", "Sigma_R", "D")
identity_arrows = {(obj, obj, f"id_{obj}") for obj in objects}
cut_arrows = {("Sigma", "D", "Delta_C")}
established_surface_arrows = identity_arrows | cut_arrows

required_coproduct_legs = (
    ("Sigma_L", "D", "left_injection"),
    ("Sigma_R", "D", "right_injection"),
)
observed_coproduct_legs = tuple(
    leg
    for leg in required_coproduct_legs
    if any(
        source == leg[0] and target == leg[1]
        for source, target, _ in established_surface_arrows
    )
)
required_leg_deficit = Integer(len(required_coproduct_legs)) - Integer(
    len(observed_coproduct_legs)
)
assert required_leg_deficit == 2

# Mapping classes preserve connected-component count.  Therefore the
# groupoid freely generated by one connected surface U under disjoint union
# has no morphism U -> U sqcup U, even though its isomorphism classes retain
# distinct finite disjoint-union powers.
cutoff = 8


def unit_power(power: int) -> tuple[str, ...]:
    return tuple("U" for _ in range(power))


unit_powers = tuple(unit_power(power) for power in range(cutoff + 1))
distinct_power_pairs = tuple(
    (left, right)
    for left, right in itertools.combinations(range(cutoff + 1), 2)
    if unit_powers[left] != unit_powers[right]
)
expected_pair_count = Integer(cutoff * (cutoff + 1)) / Integer(2)
assert Integer(len(distinct_power_pairs)) == expected_pair_count

mapping_class_hom_u_to_u2 = tuple()
assert mapping_class_hom_u_to_u2 == tuple()

# Deliberate failure: naming disjoint union as a symmetric monoidal operation
# does not supply the two arrows needed even to state its coproduct universal
# mapping property in the established coefficient-neutral operation graph.
naive_categorical_coproduct_claim = required_leg_deficit == 0
assert naive_categorical_coproduct_claim is False

packet = {
    "schema": (
        "marici.grothendieck.phase_i_surface_disjoint_union_typing.v1"
    ),
    "demonstrated_strength": [
        "unbounded mapping-class groupoid theorem",
        "source-typed finite operation audit",
    ],
    "compatibility_preflight": {
        "coefficient_domain": None,
        "coefficient_prime": None,
        "ambient_carrier": "oriented marked surfaces",
        "source_morphism_classes": [
            "mapping-class isomorphisms",
            "separating cut operation",
        ],
        "filtration_stage": "coefficient-neutral bare surface layer",
        "pole_depths": "not_applicable",
        "input_sha256": {rel(path): sha256(path) for path in inputs},
    },
    "source_typing": {
        "objects": list(objects),
        "disconnected_object": "D = Sigma_L sqcup Sigma_R",
        "established_nonidentity_arrow": {
            "name": "Delta_C",
            "source": "Sigma",
            "target": "D",
        },
        "required_coproduct_legs": [
            {"name": name, "source": source, "target": target}
            for source, target, name in required_coproduct_legs
        ],
        "observed_required_leg_count": len(observed_coproduct_legs),
        "required_leg_deficit": int(required_leg_deficit),
        "universal_mapping_property_well_typed": False,
    },
    "mapping_class_groupoid": {
        "theorem": (
            "mapping-class isomorphisms preserve connected-component count"
        ),
        "hom_U_to_U_squnion_U": list(mapping_class_hom_u_to_u2),
        "categorical_coproduct": False,
        "monoidal_disjoint_union": True,
        "unit_power_cutoff": cutoff,
        "distinct_unit_power_pair_count": len(distinct_power_pairs),
        "all_unit_powers_distinct_through_cutoff": True,
        "unbounded_control": (
            "unique connected-component decomposition makes "
            "U^squnion_m isomorphic to U^squnion_n imply m=n"
        ),
    },
    "coefficient_algebra_escape": {
        "conditional_statement": (
            "in commutative R-algebras, A tensor_R B is a categorical "
            "coproduct with unit-dependent factor maps"
        ),
        "carrier_neutral": False,
        "missing_inputs": [
            "base coefficient ring R",
            "algebra unit maps a -> a tensor 1 and b -> 1 tensor b",
            "proof that this coefficient coproduct reflects a Carrier coproduct",
        ],
        "entry_07_establishes_factorization_only": (
            "A_(Sigma_L sqcup Sigma_R) isomorphic to "
            "A_(Sigma_L) tensor A_(Sigma_R)"
        ),
    },
    "deliberate_failure": {
        "naive_claim": (
            "the established bare surface disjoint union is already a "
            "coefficient-neutral categorical coproduct"
        ),
        "claim_holds": naive_categorical_coproduct_claim,
        "required_injection_leg_count": len(required_coproduct_legs),
        "observed_injection_leg_count": len(observed_coproduct_legs),
        "nonzero_obstruction": {
            "typed_injection_leg_deficit": int(required_leg_deficit)
        },
    },
    "verdict": {
        "surface_disjoint_union_monoidal": True,
        "surface_disjoint_union_coproduct_derived": False,
        "multiplicity_sensitive_pi0_candidate": True,
        "phase_i_finite_coproduct_gate_passed": False,
        "initial_semiring_N_derived": False,
        "group_completion_Z_derived": False,
        "arithmetic_derived": False,
    },
    "scope_boundary": {
        "larger_surface_category_contradicted": False,
        "component_inclusion_morphisms_contradicted": False,
        "formal_finite_family_completion_contradicted": False,
        "precise_missing_datum": (
            "a source-authorized noninvertible morphism class containing "
            "component injections and satisfying the coproduct mapping property"
        ),
    },
    "deferred": [
        "choice between monoidal addition and categorical coproduct",
        "coefficient-neutral component-inclusion category",
        "distributive regional tensor",
        "initial semiring and group completion",
        "Burnside/Witt operations",
    ],
}

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text(json.dumps(packet, indent=2) + "\n", encoding="utf-8")
print(json.dumps(packet))
