"""Classify hypothetical controlled-reference outcomes for the frozen middle task.

Usage: uv run python <this-file> private|reuse CENTER [RADIUS]
CENTER and RADIUS are exact rationals, not measured data generated by this tool.
A valid reference-error guarantee is an EXTERNAL premise. No reference is acquired.
"""
from pathlib import Path
from fractions import Fraction as Q
import importlib.util,json,hashlib,sys,copy

HERE=Path(__file__).resolve().parent
spec=importlib.util.spec_from_file_location('source_task',HERE/'three_channel_source_task.py')
t=importlib.util.module_from_spec(spec);spec.loader.exec_module(t)
OUT=t.RESULTS

class _ConditionedGain(t.SourceTask):
    """Read-only hypothetical restriction; never writes a calibration bundle."""
    def __init__(self,engine,mode,gain):
        self.__dict__=engine.__dict__.copy()
        self.conditioned_mode=mode;self.conditioned_gain=gain
        if not t.contains(engine.calibrations(mode)['positive'],gain):
            raise ValueError('Reference restriction must be nested')
    def calibrations(self,mode):
        gains=super().calibrations(mode)
        if mode==self.conditioned_mode:gains['positive']=self.conditioned_gain
        return gains

class AcquisitionPlan:
    def __init__(self):
        self.report=json.loads((OUT/'source-task-acquisition-plan.json').read_text(encoding='utf-8'))
        for name,digest in self.report['protected_file_hashes'].items():
            if hashlib.sha256((OUT/name).read_bytes()).hexdigest()!=digest:raise ValueError('Stale planning inputs')
        path=OUT/self.report['planning_calibration_file']
        if hashlib.sha256(path.read_bytes()).hexdigest()!=self.report['planning_calibration_sha256']:
            raise ValueError('Stale planning calibration')
        self.engine=t.SourceTask(path)
        frozen=json.loads((OUT/'calibration-refinement-frozen-inputs.json').read_text(encoding='utf-8'))
        self.data={mode:cases['middle_threshold'] for mode,cases in frozen['cases'].items()}
        self.threshold=Q(self.report['threshold_gain_rational'])
        self.radius=Q(self.report['reference_option']['total_absolute_error_radius'])

    def classify_repeat(self,mode,center,radius=None):
        """Add a reading on the UNKNOWN source, without altering calibration."""
        if mode not in self.data:raise ValueError('Choose private or reuse')
        center=t.rational(center);radius=self.radius if radius is None else t.rational(radius)
        if radius<0:raise ValueError('Negative reading radius')
        old=t.interval(self.data[mode]['raw']['positive'])
        joint=max(old[0],center-radius),min(old[1],center+radius)
        answer={'hypothetical':True,'mode':mode,'repeat_center':str(center),'repeat_radius':str(radius),
                'scope':'An additional reading of the SAME positive channel on the unknown source; existing observations and calibration are retained.'}
        if joint[0]>joint[1]:
            answer.update(outcome='READINGS_INCOMPATIBLE',reason='Old and new reading intervals are disjoint.')
            return answer
        combined=copy.deepcopy(self.data[mode])
        combined['raw']['positive']={'center':str((joint[0]+joint[1])/2),'radius':str((joint[1]-joint[0])/2)}
        certificate=self.engine.certify(combined)
        assert certificate['status']!='CERTIFIED_FEASIBLE'
        answer.update(outcome='SOURCE_PRIOR_INCOMPATIBLE' if certificate['status']=='CERTIFIED_INFEASIBLE' else 'UNRESOLVED',
                      joint_positive_interval=t.describe(joint),source_certificate=certificate)
        return answer

    def classify_reference(self,mode,center,radius=None):
        if mode not in self.data:raise ValueError('Choose private or reuse')
        center=t.rational(center);radius=self.radius if radius is None else t.rational(radius)
        if radius<0:raise ValueError('Negative reference radius')
        old=self.engine.calibrations(mode)['positive']
        gain=max(old[0],center-radius),min(old[1],center+radius)
        answer={'hypothetical':True,'mode':mode,'reference_center':str(center),'reference_radius':str(radius),
                'premise':'The SAME positive aggregate is read on the known unit source v_(2,0), with a valid total-error bound. No such reading is asserted here.'}
        if gain[0]>gain[1]:
            answer.update(outcome='CALIBRATION_INCOMPATIBLE',
                          reason='Reference interval is disjoint from the certified physical gain enclosure.')
            return answer
        certificate=_ConditionedGain(self.engine,mode,gain).certify(self.data[mode])
        if certificate['status']=='CERTIFIED_INFEASIBLE':
            outcome='SOURCE_PRIOR_INCOMPATIBLE'
        elif certificate['status']=='CERTIFIED_FEASIBLE':
            assert certificate['nonvacuous_positive_task_certificate']
            outcome='TASK_CERTIFIED_CONDITIONAL_ON_VALID_REFERENCE'
        else:outcome='UNRESOLVED'
        # This equality verifies the decision formula for the requested center;
        # the complete real-line partition is proved in the accompanying note.
        predicted=('SOURCE_PRIOR_INCOMPATIBLE' if center+radius<self.threshold else
                   'TASK_CERTIFIED_CONDITIONAL_ON_VALID_REFERENCE' if center-radius>=self.threshold else
                   'UNRESOLVED')
        assert outcome==predicted
        answer.update(outcome=outcome,conditioned_gain_interval=t.describe(gain),source_certificate=certificate)
        return answer

if __name__=='__main__':
    if len(sys.argv) not in (3,4):raise SystemExit(__doc__)
    plan=AcquisitionPlan()
    result=plan.classify_reference(sys.argv[1],sys.argv[2],sys.argv[3] if len(sys.argv)==4 else None)
    print(json.dumps(result,indent=2))
