"""Exact rational audit of the gamma-phase boundary constant."""

from fractions import Fraction


a = Fraction(1, 4)
gamma_phase_constant_over_pi = (a - Fraction(1, 2)) / 2
argument_principle_base = Fraction(1)
smooth_count_constant = argument_principle_base + gamma_phase_constant_over_pi

assert gamma_phase_constant_over_pi == Fraction(-1, 8)
assert smooth_count_constant == Fraction(7, 8)

result = {
    "gamma_argument": "1/4+iT/2",
    "gamma_phase_constant_over_pi": "-1/8",
    "argument_principle_base": "1",
    "smooth_zero_count_constant": "7/8",
    "quarter_shift_and_boundary_constant_share_archimedean_source": True,
    "remaining_spectral_term": "S(T), to be generated by prime coupling",
}

if __name__ == "__main__":
    import json
    from pathlib import Path

    output = Path(__file__).parents[1] / "results" / "quarter-shift-seven-eighths.json"
    output.write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    for key, value in result.items():
        print(f"{key}={value}")

