{-# OPTIONS --safe --cubical --guardedness #-}
module FreshEquationalConsequences where
open import Cubical.Foundations.Prelude
-- Consequences of the supplied axiom, NOT an adequacy certificate.
module Derived {ℓ : Level} (A : Type ℓ) (stroke : A → A → A)
  (hypothesis : (x0 x1 x2 : A) → (stroke (stroke (stroke x0 x1) x2) (stroke x0 (stroke (stroke x0 x2) x0))) ≡ x2) where
  f0 : (x0 x1 x2 : A) → (stroke (stroke (stroke x0 x1) x2) (stroke x0 (stroke (stroke x0 x2) x0))) ≡ x2
  f0 = hypothesis
  f1 : (x0 x1 x2 : A) → (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x2) x1) (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1)) ≡ x1
  f1 x0 x1 x2 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x2) x1) (stroke (stroke x0 (stroke (stroke x0 x1) x0)) hole))) (f0 x0 (stroke (stroke x0 x1) x0) x1))) ∙ (f0 (stroke x0 (stroke (stroke x0 x1) x0)) x2 x1)) ∙ refl))
  f2 : (x0 x1 x2 x3 : A) → (stroke (stroke x0 x1) (stroke (stroke (stroke x2 x3) x0) (stroke (stroke (stroke (stroke x2 x3) x0) x1) (stroke (stroke x2 x3) x0)))) ≡ x1
  f2 x0 x1 x2 x3 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke hole x1) (stroke (stroke (stroke x2 x3) x0) (stroke (stroke (stroke (stroke x2 x3) x0) x1) (stroke (stroke x2 x3) x0))))) (f0 x2 x3 x0))) ∙ (f0 (stroke (stroke x2 x3) x0) (stroke x2 (stroke (stroke x2 x0) x2)) x1)) ∙ refl))
  f3 : (x0 x1 : A) → (stroke (stroke x0 x0) (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0)) ≡ x0
  f3 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke x0 x0) (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) hole))) (f1 x1 x0 x0))) ∙ (f2 x0 x0 x1 (stroke (stroke x1 x0) x1))) ∙ refl))
  f4 : (x0 x1 x2 : A) → (stroke (stroke x0 x1) (stroke (stroke x2 x0) (stroke (stroke (stroke x2 x0) x1) (stroke x2 x0)))) ≡ x1
  f4 x0 x1 x2 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke hole x1) (stroke (stroke x2 x0) (stroke (stroke (stroke x2 x0) x1) (stroke x2 x0))))) (f2 x2 x0 x0 x0))) ∙ (f0 (stroke x2 x0) (stroke (stroke (stroke x0 x0) x2) (stroke (stroke (stroke (stroke x0 x0) x2) x0) (stroke (stroke x0 x0) x2))) x1)) ∙ refl))
  f5 : (x0 x1 : A) → (stroke (stroke (stroke (stroke x0 x1) x0) x1) (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1)) ≡ x1
  f5 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke hole x1) (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1))) (f2 x0 (stroke (stroke x0 x1) x0) x0 x0))) ∙ (f1 x0 x1 (stroke (stroke (stroke x0 x0) x0) (stroke (stroke (stroke (stroke x0 x0) x0) (stroke (stroke x0 x1) x0)) (stroke (stroke x0 x0) x0))))) ∙ refl))
  f6 : (x0 x1 : A) → (stroke (stroke x0 x0) (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0) x0)) ≡ x0
  f6 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke x0 x0) (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) hole) x0) x0))) (f0 x1 (stroke (stroke x1 x0) x1) x0))) ∙ (f3 x0 (stroke x1 (stroke (stroke x1 x0) x1)))) ∙ refl))
  f7 : (x0 x1 x2 : A) → (stroke x0 (stroke (stroke x1 x2) (stroke (stroke (stroke x1 x2) (stroke x1 (stroke (stroke x1 x0) x1))) (stroke x1 x2)))) ≡ (stroke x1 (stroke (stroke x1 x0) x1))
  f7 x0 x1 x2 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke hole (stroke (stroke x1 x2) (stroke (stroke (stroke x1 x2) (stroke x1 (stroke (stroke x1 x0) x1))) (stroke x1 x2))))) (f0 x1 x2 x0))) ∙ (f0 (stroke x1 x2) x0 (stroke x1 (stroke (stroke x1 x0) x1)))) ∙ refl))
  f8 : (x0 x1 x2 : A) → (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x2) (stroke x1 (stroke (stroke x1 x2) x1))) ≡ x2
  f8 x0 x1 x2 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke hole x2) (stroke x1 (stroke (stroke x1 x2) x1)))) (f7 x1 x0 x0))) ∙ (f0 x1 (stroke (stroke x0 x0) (stroke (stroke (stroke x0 x0) (stroke x0 (stroke (stroke x0 x1) x0))) (stroke x0 x0))) x2)) ∙ refl))
  f9 : (x0 x1 : A) → (stroke (stroke x0 x0) (stroke (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0) x0) x0)) ≡ x0
  f9 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke x0 x0) (stroke (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) hole) x0) x0))) (f1 x1 x0 x0))) ∙ (f3 x0 (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0))) ∙ refl))
  f10 : (x0 x1 x2 : A) → (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x2) (stroke x1 (stroke (stroke x1 x2) x1))) ≡ x2
  f10 x0 x1 x2 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) hole) x2) (stroke x1 (stroke (stroke x1 x2) x1)))) (f0 x0 (stroke (stroke x0 x1) x0) x1))) ∙ (f8 (stroke x0 (stroke (stroke x0 x1) x0)) x1 x2)) ∙ refl))
  f11 : (x0 x1 : A) → (stroke (stroke x0 x0) (stroke (stroke (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0) x0) x0) x0)) ≡ x0
  f11 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke x0 x0) (stroke (stroke (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) hole) x0) x0) x0))) (f1 x1 x0 x0))) ∙ (f6 x0 (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0))) ∙ refl))
  f12 : (x0 x1 x2 : A) → (stroke (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x1) x2) (stroke x1 (stroke (stroke x1 x2) x1))) ≡ x2
  f12 x0 x1 x2 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) hole) x2) (stroke x1 (stroke (stroke x1 x2) x1)))) (f1 x0 x1 x1))) ∙ (f8 (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x1 x2)) ∙ refl))
  f13 : (x0 x1 : A) → (stroke x0 (stroke x0 (stroke (stroke x0 (stroke x1 (stroke (stroke x1 x0) x1))) x0))) ≡ (stroke x1 (stroke (stroke x1 x0) x1))
  f13 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke hole (stroke x0 (stroke (stroke x0 (stroke x1 (stroke (stroke x1 x0) x1))) x0)))) (f0 x1 (stroke (stroke x1 x0) x1) x0))) ∙ (f10 x1 x0 (stroke x1 (stroke (stroke x1 x0) x1)))) ∙ refl))
  f14 : (x0 x1 x2 x3 : A) → (stroke (stroke (stroke (stroke (stroke x0 x1) x2) x3) (stroke x0 (stroke (stroke x0 x2) x0))) (stroke (stroke (stroke x0 x1) x2) (stroke x2 (stroke (stroke x0 x1) x2)))) ≡ (stroke x0 (stroke (stroke x0 x2) x0))
  f14 x0 x1 x2 x3 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke (stroke (stroke x0 x1) x2) x3) (stroke x0 (stroke (stroke x0 x2) x0))) (stroke (stroke (stroke x0 x1) x2) (stroke hole (stroke (stroke x0 x1) x2))))) (f0 x0 x1 x2))) ∙ (f0 (stroke (stroke x0 x1) x2) x3 (stroke x0 (stroke (stroke x0 x2) x0)))) ∙ refl))
  f15 : (x0 x1 : A) → (stroke (stroke x0 x0) (stroke (stroke (stroke (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0) x0) x0) x0) x0)) ≡ x0
  f15 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke x0 x0) (stroke (stroke (stroke (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) hole) x0) x0) x0) x0))) (f1 x1 x0 x0))) ∙ (f9 x0 (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0))) ∙ refl))
  f16 : (x0 x1 x2 : A) → (stroke (stroke (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x1) x1) x2) (stroke x1 (stroke (stroke x1 x2) x1))) ≡ x2
  f16 x0 x1 x2 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) hole) x1) x2) (stroke x1 (stroke (stroke x1 x2) x1)))) (f1 x0 x1 x1))) ∙ (f10 (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x1 x2)) ∙ refl))
  f17 : (x0 x1 : A) → (stroke (stroke (stroke (stroke (stroke x0 x0) x0) x1) (stroke x0 (stroke (stroke x0 x0) x0))) x0) ≡ (stroke x0 (stroke (stroke x0 x0) x0))
  f17 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke (stroke (stroke x0 x0) x0) x1) (stroke x0 (stroke (stroke x0 x0) x0))) hole)) (f0 x0 x0 x0))) ∙ (f14 x0 x0 x0 x1)) ∙ refl))
  f18 : (x0 : A) → (stroke (stroke x0 (stroke x0 (stroke (stroke x0 x0) x0))) x0) ≡ (stroke x0 (stroke (stroke x0 x0) x0))
  f18 x0 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke hole (stroke x0 (stroke (stroke x0 x0) x0))) x0)) (f0 x0 x0 x0))) ∙ (f17 x0 (stroke x0 (stroke (stroke x0 x0) x0)))) ∙ refl))
  f19 : (x0 : A) → (stroke (stroke x0 (stroke (stroke x0 x0) x0)) (stroke x0 (stroke (stroke x0 x0) x0))) ≡ x0
  f19 x0 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke hole (stroke x0 (stroke (stroke x0 x0) x0)))) (f18 x0))) ∙ (f0 x0 (stroke x0 (stroke (stroke x0 x0) x0)) x0)) ∙ refl))
  f20 : (x0 : A) → (stroke (stroke x0 x0) (stroke (stroke x0 (stroke (stroke x0 x0) x0)) x0)) ≡ x0
  f20 x0 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke hole x0) (stroke (stroke x0 (stroke (stroke x0 x0) x0)) x0))) (f19 x0))) ∙ (f1 x0 x0 (stroke x0 (stroke (stroke x0 x0) x0)))) ∙ refl))
  f21 : (x0 x1 x2 : A) → (stroke x0 (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x2) (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x2) (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0)) (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x2)))) ≡ (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0)
  f21 x0 x1 x2 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke hole (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x2) (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x2) (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0)) (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x2))))) (f1 x1 x0 x2))) ∙ (f0 (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x2) x0 (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0))) ∙ refl))
  f22 : (x0 : A) → (stroke x0 (stroke x0 (stroke x0 (stroke (stroke x0 x0) x0)))) ≡ (stroke x0 (stroke (stroke x0 x0) x0))
  f22 x0 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke x0 (stroke x0 hole))) (f18 x0))) ∙ (f13 x0 x0)) ∙ refl))
  f23 : (x0 x1 x2 : A) → (stroke (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x2) x1) (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x1)) ≡ x1
  f23 x0 x1 x2 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x2) x1) (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) hole))) (f1 x0 x1 x1))) ∙ (f0 (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x2 x1)) ∙ refl))
  f24 : (x0 x1 x2 : A) → (stroke (stroke (stroke x0 (stroke (stroke x0 (stroke x1 (stroke (stroke x1 x2) x1))) x0)) x2) (stroke (stroke x1 (stroke (stroke x1 x2) x1)) x2)) ≡ x2
  f24 x0 x1 x2 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke hole x2) (stroke (stroke x1 (stroke (stroke x1 x2) x1)) x2))) (f7 (stroke x1 (stroke (stroke x1 x2) x1)) x0 x0))) ∙ (f1 x1 x2 (stroke (stroke x0 x0) (stroke (stroke (stroke x0 x0) (stroke x0 (stroke (stroke x0 (stroke x1 (stroke (stroke x1 x2) x1))) x0))) (stroke x0 x0))))) ∙ refl))
  f25 : (x0 : A) → (stroke (stroke x0 (stroke (stroke x0 x0) x0)) (stroke (stroke x0 (stroke (stroke x0 x0) x0)) x0)) ≡ x0
  f25 x0 = ((sym (refl ∙ (cong (λ hole → (stroke hole (stroke (stroke x0 (stroke (stroke x0 x0) x0)) x0))) (f18 x0)))) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke x0 hole) x0) (stroke (stroke x0 (stroke (stroke x0 x0) x0)) x0))) (f18 x0))) ∙ (f24 x0 x0 x0)) ∙ refl))
  f26 : (x0 x1 : A) → (stroke x0 (stroke x0 (stroke (stroke x0 (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0)) x0))) ≡ (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0)
  f26 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke hole (stroke x0 (stroke (stroke x0 (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0)) x0)))) (f1 x1 x0 (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) (stroke x1 (stroke (stroke x1 x0) x1)))))) ∙ (f10 (stroke x1 (stroke (stroke x1 x0) x1)) x0 (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0))) ∙ refl))
  f27 : (x0 x1 : A) → (stroke (stroke x0 x0) (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0) x0) x0) x0) x0) x0)) ≡ x0
  f27 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke x0 x0) (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) hole) x0) x0) x0) x0) x0))) (f1 x1 x0 x0))) ∙ (f11 x0 (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0))) ∙ refl))
  f28 : (x0 x1 x2 x3 : A) → (stroke (stroke (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x2) x1) x3) (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1)) (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x2) x1) (stroke x1 (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x2) x1)))) ≡ (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1)
  f28 x0 x1 x2 x3 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x2) x1) x3) (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1)) (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x2) x1) (stroke hole (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x2) x1))))) (f1 x0 x1 x2))) ∙ (f0 (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x2) x1) x3 (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1))) ∙ refl))
  f29 : (x0 x1 x2 : A) → (stroke (stroke (stroke (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x1) x1) x1) x2) (stroke x1 (stroke (stroke x1 x2) x1))) ≡ x2
  f29 x0 x1 x2 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) hole) x1) x1) x2) (stroke x1 (stroke (stroke x1 x2) x1)))) (f1 x0 x1 x1))) ∙ (f12 (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x1 x2)) ∙ refl))
  f30 : (x0 : A) → (stroke x0 (stroke (stroke x0 (stroke (stroke x0 x0) x0)) (stroke x0 (stroke x0 (stroke (stroke x0 x0) x0))))) ≡ (stroke x0 (stroke (stroke x0 x0) x0))
  f30 x0 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke x0 (stroke (stroke x0 (stroke (stroke x0 x0) x0)) (stroke hole (stroke x0 (stroke (stroke x0 x0) x0)))))) (f19 x0))) ∙ (f7 x0 x0 (stroke (stroke x0 x0) x0))) ∙ refl))
  f31 : (x0 x1 x2 : A) → (stroke (stroke (stroke (stroke (stroke x0 x1) x2) (stroke x2 (stroke (stroke x0 x1) x2))) x2) (stroke (stroke x0 (stroke (stroke x0 x2) x0)) x2)) ≡ x2
  f31 x0 x1 x2 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke (stroke (stroke x0 x1) x2) (stroke hole (stroke (stroke x0 x1) x2))) x2) (stroke (stroke x0 (stroke (stroke x0 x2) x0)) x2))) (f0 x0 x1 x2))) ∙ (f24 (stroke (stroke x0 x1) x2) x0 x2)) ∙ refl))
  f32 : (x0 x1 : A) → (stroke (stroke x0 x0) (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0) x0) x0) x0) x0) x0) x0)) ≡ x0
  f32 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke x0 x0) (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) hole) x0) x0) x0) x0) x0) x0))) (f1 x1 x0 x0))) ∙ (f15 x0 (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0))) ∙ refl))
  f33 : (x0 x1 x2 : A) → (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x1) x1) x1) x1) x2) (stroke x1 (stroke (stroke x1 x2) x1))) ≡ x2
  f33 x0 x1 x2 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) hole) x1) x1) x1) x2) (stroke x1 (stroke (stroke x1 x2) x1)))) (f1 x0 x1 x1))) ∙ (f16 (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x1 x2)) ∙ refl))
  f34 : (x0 x1 : A) → (stroke (stroke (stroke x0 (stroke (stroke x0 (stroke (stroke x1 x1) x1)) x0)) (stroke x1 (stroke (stroke x1 x1) x1))) x1) ≡ (stroke x1 (stroke (stroke x1 x1) x1))
  f34 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke hole (stroke x1 (stroke (stroke x1 x1) x1))) x1)) (f7 (stroke (stroke x1 x1) x1) x0 x0))) ∙ (f17 x1 (stroke (stroke x0 x0) (stroke (stroke (stroke x0 x0) (stroke x0 (stroke (stroke x0 (stroke (stroke x1 x1) x1)) x0))) (stroke x0 x0))))) ∙ refl))
  f35 : (x0 x1 x2 x3 : A) → (stroke (stroke (stroke (stroke (stroke (stroke x0 x1) x2) (stroke x2 (stroke (stroke x0 x1) x2))) x3) (stroke x0 (stroke (stroke x0 x2) x0))) (stroke (stroke (stroke (stroke x0 x1) x2) (stroke x2 (stroke (stroke x0 x1) x2))) (stroke x0 (stroke (stroke x0 x2) x0)))) ≡ (stroke x0 (stroke (stroke x0 x2) x0))
  f35 x0 x1 x2 x3 = ((sym (refl ∙ (cong (λ hole → (stroke (stroke (stroke (stroke (stroke (stroke x0 x1) x2) (stroke x2 (stroke (stroke x0 x1) x2))) x3) (stroke x0 (stroke (stroke x0 x2) x0))) (stroke (stroke (stroke (stroke x0 x1) x2) (stroke hole (stroke (stroke x0 x1) x2))) (stroke x0 (stroke (stroke x0 x2) x0))))) (f0 x0 x1 x2)))) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke (stroke (stroke (stroke x0 x1) x2) (stroke hole (stroke (stroke x0 x1) x2))) x3) (stroke x0 (stroke (stroke x0 x2) x0))) (stroke (stroke (stroke (stroke x0 x1) x2) (stroke (stroke (stroke (stroke x0 x1) x2) (stroke x0 (stroke (stroke x0 x2) x0))) (stroke (stroke x0 x1) x2))) (stroke x0 (stroke (stroke x0 x2) x0))))) (f0 x0 x1 x2))) ∙ (f1 (stroke (stroke x0 x1) x2) (stroke x0 (stroke (stroke x0 x2) x0)) x3)) ∙ refl))
  f36 : (x0 x1 : A) → (stroke (stroke (stroke x0 x1) (stroke x0 (stroke (stroke x0 x0) x0))) (stroke x0 (stroke x0 (stroke (stroke x0 x0) x0)))) ≡ (stroke x0 (stroke (stroke x0 x0) x0))
  f36 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke x0 x1) (stroke x0 (stroke (stroke x0 x0) x0))) (stroke x0 hole))) (f18 x0))) ∙ (f0 x0 x1 (stroke x0 (stroke (stroke x0 x0) x0)))) ∙ refl))
  f37 : (x0 : A) → (stroke x0 (stroke (stroke x0 (stroke x0 (stroke (stroke x0 x0) x0))) (stroke x0 (stroke (stroke x0 x0) x0)))) ≡ (stroke x0 (stroke (stroke x0 x0) x0))
  f37 x0 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke x0 (stroke (stroke x0 (stroke x0 (stroke (stroke x0 x0) x0))) hole))) (f36 x0 (stroke x0 (stroke (stroke x0 x0) x0))))) ∙ (f7 x0 x0 (stroke x0 (stroke (stroke x0 x0) x0)))) ∙ refl))
  f38 : (x0 x1 x2 : A) → (stroke (stroke (stroke (stroke x0 x1) (stroke x1 (stroke x0 x1))) x1) (stroke (stroke (stroke x2 x0) (stroke (stroke (stroke x2 x0) x1) (stroke x2 x0))) x1)) ≡ x1
  f38 x0 x1 x2 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke (stroke x0 x1) (stroke hole (stroke x0 x1))) x1) (stroke (stroke (stroke x2 x0) (stroke (stroke (stroke x2 x0) x1) (stroke x2 x0))) x1))) (f4 x0 x1 x2))) ∙ (f24 (stroke x0 x1) (stroke x2 x0) x1)) ∙ refl))
  f39 : (x0 x1 : A) → (stroke (stroke x0 x0) (stroke (stroke (stroke x1 (stroke x0 x0)) (stroke (stroke (stroke x1 (stroke x0 x0)) x0) (stroke x1 (stroke x0 x0)))) x0)) ≡ x0
  f39 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke hole x0) (stroke (stroke (stroke x1 (stroke x0 x0)) (stroke (stroke (stroke x1 (stroke x0 x0)) x0) (stroke x1 (stroke x0 x0)))) x0))) (f0 x0 x0 x0))) ∙ (f38 (stroke x0 x0) x0 x1)) ∙ refl))
  f40 : (x0 x1 : A) → (stroke (stroke (stroke (stroke x0 x0) (stroke x0 (stroke x0 x0))) x0) (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0) x0)) ≡ x0
  f40 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke (stroke x0 x0) (stroke x0 (stroke x0 x0))) x0) (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) hole) x0))) (f1 x1 x0 x0))) ∙ (f38 x0 x0 (stroke x1 (stroke (stroke x1 x0) x1)))) ∙ refl))
  f41 : (x0 x1 : A) → (stroke (stroke (stroke (stroke x0 x0) (stroke x0 (stroke x0 x0))) x0) (stroke (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0) x0) x0)) ≡ x0
  f41 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke (stroke x0 x0) (stroke x0 (stroke x0 x0))) x0) (stroke (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0) hole) x0))) (f23 x1 x0 x0))) ∙ (f38 x0 x0 (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0))) ∙ refl))
  f42 : (x0 x1 : A) → (stroke x0 (stroke (stroke x1 (stroke (stroke x1 (stroke x1 (stroke (stroke x1 x0) x1))) x1)) (stroke x1 (stroke (stroke x1 x0) x1)))) ≡ (stroke x1 (stroke (stroke x1 x0) x1))
  f42 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke hole (stroke (stroke x1 (stroke (stroke x1 (stroke x1 (stroke (stroke x1 x0) x1))) x1)) (stroke x1 (stroke (stroke x1 x0) x1))))) (f0 x1 (stroke (stroke x1 (stroke x1 (stroke (stroke x1 x0) x1))) x1) x0))) ∙ (f1 x1 (stroke x1 (stroke (stroke x1 x0) x1)) x0)) ∙ refl))
  f43 : (x0 x1 x2 : A) → (stroke (stroke x0 (stroke x1 (stroke (stroke x1 x0) x1))) (stroke (stroke (stroke x1 x2) x0) (stroke x0 (stroke (stroke x1 x2) x0)))) ≡ (stroke x1 (stroke (stroke x1 x0) x1))
  f43 x0 x1 x2 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke x0 (stroke x1 (stroke (stroke x1 x0) x1))) (stroke (stroke (stroke x1 x2) x0) (stroke hole (stroke (stroke x1 x2) x0))))) (f0 x1 x2 x0))) ∙ (f2 x0 (stroke x1 (stroke (stroke x1 x0) x1)) x1 x2)) ∙ refl))
  f44 : (x0 x1 : A) → (stroke x0 (stroke x0 (stroke (stroke x0 (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0)) x0))) ≡ (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0)
  f44 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke hole (stroke x0 (stroke (stroke x0 (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0)) x0)))) (f3 x0 x1))) ∙ (f0 x0 x0 (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0))) ∙ refl))
  f45 : (x0 x1 x2 : A) → (stroke (stroke (stroke x0 (stroke (stroke x0 (stroke (stroke x1 (stroke (stroke x1 x2) x1)) x2)) x0)) x2) (stroke (stroke (stroke x1 (stroke (stroke x1 x2) x1)) x2) x2)) ≡ x2
  f45 x0 x1 x2 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke x0 (stroke (stroke x0 (stroke (stroke x1 (stroke (stroke x1 x2) x1)) x2)) x0)) x2) (stroke (stroke (stroke x1 (stroke (stroke x1 x2) x1)) x2) hole))) (f1 x1 x2 x2))) ∙ (f8 x0 (stroke (stroke x1 (stroke (stroke x1 x2) x1)) x2) x2)) ∙ refl))
  f46 : (x0 : A) → (stroke (stroke (stroke (stroke x0 x0) (stroke x0 (stroke x0 x0))) x0) (stroke (stroke (stroke x0 (stroke (stroke x0 x0) x0)) x0) x0)) ≡ x0
  f46 x0 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke (stroke x0 x0) (stroke hole (stroke x0 x0))) x0) (stroke (stroke (stroke x0 (stroke (stroke x0 x0) x0)) x0) x0))) (f20 x0))) ∙ (f45 (stroke x0 x0) x0 x0)) ∙ refl))
  f47 : (x0 : A) → (stroke x0 (stroke (stroke (stroke x0 (stroke (stroke x0 x0) x0)) x0) (stroke x0 (stroke (stroke x0 (stroke (stroke x0 x0) x0)) x0)))) ≡ (stroke x0 (stroke (stroke x0 x0) x0))
  f47 x0 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke hole (stroke (stroke (stroke x0 (stroke (stroke x0 x0) x0)) x0) (stroke x0 (stroke (stroke x0 (stroke (stroke x0 x0) x0)) x0))))) (f10 x0 x0 x0))) ∙ (f14 x0 (stroke (stroke x0 x0) x0) x0 x0)) ∙ refl))
  f48 : (x0 : A) → (stroke (stroke x0 (stroke (stroke x0 x0) x0)) (stroke (stroke (stroke (stroke x0 x0) x0) (stroke (stroke (stroke (stroke x0 x0) x0) x0) (stroke (stroke x0 x0) x0))) x0)) ≡ x0
  f48 x0 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke hole (stroke (stroke (stroke (stroke x0 x0) x0) (stroke (stroke (stroke (stroke x0 x0) x0) x0) (stroke (stroke x0 x0) x0))) x0))) (f17 x0 (stroke (stroke (stroke (stroke x0 x0) x0) x0) (stroke (stroke x0 x0) x0))))) ∙ (f1 (stroke (stroke x0 x0) x0) x0 (stroke x0 (stroke (stroke x0 x0) x0)))) ∙ refl))
  f49 : (x0 x1 x2 : A) → (stroke (stroke (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x1) x2) x1) (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x1) x1)) ≡ x1
  f49 x0 x1 x2 = ((sym (refl ∙ (cong (λ hole → (stroke (stroke (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x1) x2) x1) (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) hole) x1))) (f1 x0 x1 x1)))) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) hole) x2) x1) (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x1) (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1))) x1))) (f1 x0 x1 x1))) ∙ (f1 (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x1 x2)) ∙ refl))
  f50 : (x0 x1 : A) → (stroke (stroke x0 x1) (stroke (stroke x0 (stroke (stroke x0 x0) x0)) (stroke (stroke (stroke x0 (stroke (stroke x0 x0) x0)) x1) (stroke x0 (stroke (stroke x0 x0) x0))))) ≡ x1
  f50 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke hole x1) (stroke (stroke x0 (stroke (stroke x0 x0) x0)) (stroke (stroke (stroke x0 (stroke (stroke x0 x0) x0)) x1) (stroke x0 (stroke (stroke x0 x0) x0)))))) (f19 x0))) ∙ (f0 (stroke x0 (stroke (stroke x0 x0) x0)) (stroke x0 (stroke (stroke x0 x0) x0)) x1)) ∙ refl))
  f51 : (x0 : A) → (stroke (stroke x0 (stroke (stroke x0 (stroke (stroke x0 x0) x0)) x0)) (stroke (stroke x0 x0) (stroke x0 (stroke x0 x0)))) ≡ (stroke (stroke x0 (stroke (stroke x0 x0) x0)) x0)
  f51 x0 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke x0 (stroke (stroke x0 (stroke (stroke x0 x0) x0)) x0)) (stroke (stroke x0 x0) (stroke hole (stroke x0 x0))))) (f20 x0))) ∙ (f4 x0 (stroke (stroke x0 (stroke (stroke x0 x0) x0)) x0) x0)) ∙ refl))
  f52 : (x0 x1 : A) → (stroke (stroke x0 x0) (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0) x0) x0) x0) x0) x0) x0) x0)) ≡ x0
  f52 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke x0 x0) (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0) hole) x0) x0) x0) x0) x0) x0))) (f23 x1 x0 x0))) ∙ (f15 x0 (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0))) ∙ refl))
  f53 : (x0 x1 x2 : A) → (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x1) x1) x1) x1) x1) x2) (stroke x1 (stroke (stroke x1 x2) x1))) ≡ x2
  f53 x0 x1 x2 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x1) hole) x1) x1) x1) x2) (stroke x1 (stroke (stroke x1 x2) x1)))) (f23 x0 x1 x1))) ∙ (f16 (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x1) x1 x2)) ∙ refl))
  f54 : (x0 : A) → (stroke (stroke (stroke (stroke x0 (stroke x0 (stroke (stroke x0 x0) x0))) (stroke x0 (stroke (stroke x0 x0) x0))) x0) (stroke (stroke x0 (stroke (stroke x0 x0) x0)) x0)) ≡ x0
  f54 x0 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke (stroke x0 (stroke x0 (stroke (stroke x0 x0) x0))) hole) x0) (stroke (stroke x0 (stroke (stroke x0 x0) x0)) x0))) (f36 x0 (stroke x0 (stroke (stroke x0 x0) x0))))) ∙ (f24 (stroke x0 (stroke x0 (stroke (stroke x0 x0) x0))) x0 x0)) ∙ refl))
  f55 : (x0 x1 : A) → (stroke (stroke (stroke (stroke x0 x0) (stroke x0 (stroke x0 x0))) x0) (stroke (stroke (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0) x0) x0) x0)) ≡ x0
  f55 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke (stroke x0 x0) (stroke x0 (stroke x0 x0))) x0) (stroke (stroke (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) hole) x0) x0) x0))) (f1 x1 x0 x0))) ∙ (f40 x0 (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0))) ∙ refl))
  f56 : (x0 x1 : A) → (stroke x0 (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0)) (stroke x1 (stroke (stroke x1 x0) x1)))) (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0))) ≡ (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0)
  f56 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke hole (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0)) (stroke x1 (stroke (stroke x1 x0) x1)))) (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0)))) (f1 x1 x0 (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0)) (stroke x1 (stroke (stroke x1 x0) x1)))))) ∙ (f1 (stroke x1 (stroke (stroke x1 x0) x1)) (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0)) ∙ refl))
  f57 : (x0 x1 : A) → (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) (stroke x1 (stroke (stroke x1 x1) x1))) (stroke x1 (stroke x1 (stroke (stroke x1 x1) x1)))) ≡ (stroke x1 (stroke (stroke x1 x1) x1))
  f57 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) (stroke x1 (stroke (stroke x1 x1) x1))) (stroke x1 hole))) (f18 x1))) ∙ (f8 x0 x1 (stroke x1 (stroke (stroke x1 x1) x1)))) ∙ refl))
  f58 : (x0 x1 : A) → (stroke (stroke x0 x0) (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0) x0) x0) x0) x0) x0) x0) x0) x0)) ≡ x0
  f58 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke x0 x0) (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0) hole) x0) x0) x0) x0) x0) x0) x0))) (f23 x1 x0 x0))) ∙ (f27 x0 (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0))) ∙ refl))
  f59 : (x0 x1 x2 : A) → (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x1) x1) x1) x1) x1) x1) x2) (stroke x1 (stroke (stroke x1 x2) x1))) ≡ x2
  f59 x0 x1 x2 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x1) hole) x1) x1) x1) x1) x2) (stroke x1 (stroke (stroke x1 x2) x1)))) (f23 x0 x1 x1))) ∙ (f29 (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x1) x1 x2)) ∙ refl))
  f60 : (x0 x1 : A) → (stroke (stroke (stroke (stroke (stroke (stroke x0 x1) x0) x1) (stroke x1 (stroke (stroke (stroke x0 x1) x0) x1))) x1) (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x1)) ≡ x1
  f60 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke (stroke (stroke (stroke x0 x1) x0) x1) (stroke x1 (stroke (stroke (stroke x0 x1) x0) x1))) x1) (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) hole) x1))) (f0 x0 (stroke (stroke x0 x1) x0) x1))) ∙ (f38 (stroke (stroke x0 x1) x0) x1 x0)) ∙ refl))
  f61 : (x0 x1 : A) → (stroke (stroke (stroke (stroke x0 x0) (stroke x0 (stroke x0 x0))) x0) (stroke (stroke (stroke (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0) x0) x0) x0) x0)) ≡ x0
  f61 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke (stroke x0 x0) (stroke x0 (stroke x0 x0))) x0) (stroke (stroke (stroke (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0) hole) x0) x0) x0))) (f23 x1 x0 x0))) ∙ (f40 x0 (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0))) ∙ refl))
  f62 : (x0 : A) → (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x0) x0)) (stroke x0 (stroke x0 (stroke (stroke x0 x0) x0)))) x0) (stroke (stroke (stroke x0 (stroke (stroke x0 x0) x0)) x0) x0)) ≡ x0
  f62 x0 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x0) x0)) (stroke hole (stroke x0 (stroke (stroke x0 x0) x0)))) x0) (stroke (stroke (stroke x0 (stroke (stroke x0 x0) x0)) x0) x0))) (f25 x0))) ∙ (f45 (stroke x0 (stroke (stroke x0 x0) x0)) x0 x0)) ∙ refl))
  f63 : (x0 x1 x2 x3 : A) → (stroke x0 (stroke x1 (stroke (stroke x1 (stroke (stroke (stroke x2 x3) x1) (stroke (stroke (stroke (stroke x2 x3) x1) x0) (stroke (stroke x2 x3) x1)))) x1))) ≡ (stroke (stroke (stroke x2 x3) x1) (stroke (stroke (stroke (stroke x2 x3) x1) x0) (stroke (stroke x2 x3) x1)))
  f63 x0 x1 x2 x3 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke hole (stroke x1 (stroke (stroke x1 (stroke (stroke (stroke x2 x3) x1) (stroke (stroke (stroke (stroke x2 x3) x1) x0) (stroke (stroke x2 x3) x1)))) x1)))) (f2 x1 x0 x2 x3))) ∙ (f0 x1 x0 (stroke (stroke (stroke x2 x3) x1) (stroke (stroke (stroke (stroke x2 x3) x1) x0) (stroke (stroke x2 x3) x1))))) ∙ refl))
  f64 : (x0 x1 x2 : A) → (stroke x0 (stroke x1 (stroke (stroke x1 (stroke (stroke x2 x1) (stroke (stroke (stroke x2 x1) x0) (stroke x2 x1)))) x1))) ≡ (stroke (stroke x2 x1) (stroke (stroke (stroke x2 x1) x0) (stroke x2 x1)))
  f64 x0 x1 x2 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke hole (stroke x1 (stroke (stroke x1 (stroke (stroke x2 x1) (stroke (stroke (stroke x2 x1) x0) (stroke x2 x1)))) x1)))) (f4 x1 x0 x2))) ∙ (f0 x1 x0 (stroke (stroke x2 x1) (stroke (stroke (stroke x2 x1) x0) (stroke x2 x1))))) ∙ refl))
  f65 : (x0 x1 : A) → (stroke (stroke x0 (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0)) (stroke (stroke x0 x0) (stroke x0 (stroke x0 x0)))) ≡ (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0)
  f65 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke x0 (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0)) (stroke (stroke x0 x0) (stroke hole (stroke x0 x0))))) (f3 x0 x1))) ∙ (f4 x0 (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0) x0)) ∙ refl))
  f66 : (x0 x1 : A) → (stroke x0 (stroke x0 (stroke (stroke x0 (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0) x0)) x0))) ≡ (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0) x0)
  f66 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke hole (stroke x0 (stroke (stroke x0 (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0) x0)) x0)))) (f6 x0 x1))) ∙ (f0 x0 x0 (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0) x0))) ∙ refl))
  f67 : (x0 x1 x2 : A) → (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 (stroke x1 (stroke (stroke x1 x2) x1))) x0)) (stroke x1 (stroke (stroke x1 x2) x1))) x2) (stroke (stroke x1 (stroke (stroke x1 x2) x1)) x2)) ≡ x2
  f67 x0 x1 x2 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 (stroke x1 (stroke (stroke x1 x2) x1))) x0)) (stroke x1 (stroke (stroke x1 x2) x1))) x2) (stroke (stroke x1 (stroke (stroke x1 x2) x1)) hole))) (f0 x1 (stroke (stroke x1 x2) x1) x2))) ∙ (f10 x0 (stroke x1 (stroke (stroke x1 x2) x1)) x2)) ∙ refl))
  f68 : (x0 x1 : A) → (stroke (stroke x0 (stroke (stroke x0 x0) x0)) (stroke (stroke (stroke (stroke x0 x0) x0) x1) (stroke (stroke (stroke (stroke (stroke x0 x0) x0) x1) x0) (stroke (stroke (stroke x0 x0) x0) x1)))) ≡ x0
  f68 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke hole (stroke (stroke (stroke (stroke x0 x0) x0) x1) (stroke (stroke (stroke (stroke (stroke x0 x0) x0) x1) x0) (stroke (stroke (stroke x0 x0) x0) x1))))) (f17 x0 x1))) ∙ (f0 (stroke (stroke (stroke x0 x0) x0) x1) (stroke x0 (stroke (stroke x0 x0) x0)) x0)) ∙ refl))
  f69 : (x0 x1 : A) → (stroke (stroke (stroke (stroke x0 x0) x1) (stroke (stroke x0 (stroke (stroke x0 x0) x0)) x0)) (stroke (stroke x0 x0) (stroke x0 (stroke x0 x0)))) ≡ (stroke (stroke x0 (stroke (stroke x0 x0) x0)) x0)
  f69 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke (stroke x0 x0) x1) (stroke (stroke x0 (stroke (stroke x0 x0) x0)) x0)) (stroke (stroke x0 x0) (stroke hole (stroke x0 x0))))) (f20 x0))) ∙ (f0 (stroke x0 x0) x1 (stroke (stroke x0 (stroke (stroke x0 x0) x0)) x0))) ∙ refl))
  f70 : (x0 x1 x2 x3 x4 : A) → (stroke (stroke (stroke (stroke x0 x1) x2) (stroke (stroke (stroke x3 x4) x0) (stroke (stroke (stroke (stroke x3 x4) x0) x1) (stroke (stroke x3 x4) x0)))) (stroke (stroke x0 x1) (stroke x1 (stroke x0 x1)))) ≡ (stroke (stroke (stroke x3 x4) x0) (stroke (stroke (stroke (stroke x3 x4) x0) x1) (stroke (stroke x3 x4) x0)))
  f70 x0 x1 x2 x3 x4 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke (stroke x0 x1) x2) (stroke (stroke (stroke x3 x4) x0) (stroke (stroke (stroke (stroke x3 x4) x0) x1) (stroke (stroke x3 x4) x0)))) (stroke (stroke x0 x1) (stroke hole (stroke x0 x1))))) (f2 x0 x1 x3 x4))) ∙ (f0 (stroke x0 x1) x2 (stroke (stroke (stroke x3 x4) x0) (stroke (stroke (stroke (stroke x3 x4) x0) x1) (stroke (stroke x3 x4) x0))))) ∙ refl))
  f71 : (x0 x1 : A) → (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 (stroke (stroke x1 x1) x1)) x0)) (stroke (stroke x1 x1) x1)) (stroke x1 (stroke (stroke x1 x1) x1))) x1) ≡ (stroke x1 (stroke (stroke x1 x1) x1))
  f71 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke hole (stroke x1 (stroke (stroke x1 x1) x1))) x1)) (f21 (stroke (stroke x1 x1) x1) x0 x0))) ∙ (f17 x1 (stroke (stroke (stroke x0 (stroke (stroke x0 (stroke (stroke x1 x1) x1)) x0)) x0) (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 (stroke (stroke x1 x1) x1)) x0)) x0) (stroke (stroke x0 (stroke (stroke x0 (stroke (stroke x1 x1) x1)) x0)) (stroke (stroke x1 x1) x1))) (stroke (stroke x0 (stroke (stroke x0 (stroke (stroke x1 x1) x1)) x0)) x0))))) ∙ refl))
  f72 : (x0 x1 : A) → (stroke (stroke (stroke x0 x1) (stroke x0 (stroke x0 (stroke (stroke x0 x0) x0)))) (stroke x0 (stroke (stroke x0 (stroke (stroke x0 x0) x0)) x0))) ≡ (stroke x0 (stroke x0 (stroke (stroke x0 x0) x0)))
  f72 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke x0 x1) (stroke x0 (stroke x0 (stroke (stroke x0 x0) x0)))) (stroke x0 (stroke hole x0)))) (f22 x0))) ∙ (f0 x0 x1 (stroke x0 (stroke x0 (stroke (stroke x0 x0) x0))))) ∙ refl))
  f73 : (x0 x1 x2 : A) → (stroke (stroke (stroke x0 (stroke (stroke x0 (stroke (stroke (stroke x1 (stroke (stroke x1 x2) x1)) x2) x2)) x0)) x2) (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x2) x1)) x2) x2) x2)) ≡ x2
  f73 x0 x1 x2 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke x0 (stroke (stroke x0 (stroke (stroke (stroke x1 (stroke (stroke x1 x2) x1)) x2) x2)) x0)) x2) (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x2) x1)) x2) x2) hole))) (f23 x1 x2 x2))) ∙ (f8 x0 (stroke (stroke (stroke x1 (stroke (stroke x1 x2) x1)) x2) x2) x2)) ∙ refl))
  f74 : (x0 x1 x2 : A) → (stroke (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x2) (stroke x2 (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x2))) x2) (stroke (stroke x1 (stroke (stroke x1 x2) x1)) x2)) ≡ x2
  f74 x0 x1 x2 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x2) (stroke hole (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x2))) x2) (stroke (stroke x1 (stroke (stroke x1 x2) x1)) x2))) (f8 x0 x1 x2))) ∙ (f24 (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x2) x1 x2)) ∙ refl))
  f75 : (x0 x1 x2 : A) → (stroke (stroke (stroke (stroke (stroke (stroke x0 x1) x2) (stroke x2 (stroke (stroke x0 x1) x2))) (stroke x0 (stroke (stroke x0 x2) x0))) x2) (stroke (stroke x0 (stroke (stroke x0 x2) x0)) x2)) ≡ x2
  f75 x0 x1 x2 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke (stroke (stroke (stroke x0 x1) x2) (stroke x2 (stroke (stroke x0 x1) x2))) hole) x2) (stroke (stroke x0 (stroke (stroke x0 x2) x0)) x2))) (f14 x0 x1 x2 (stroke x2 (stroke (stroke x0 x1) x2))))) ∙ (f24 (stroke (stroke (stroke x0 x1) x2) (stroke x2 (stroke (stroke x0 x1) x2))) x0 x2)) ∙ refl))
  f76 : (x0 x1 : A) → (stroke (stroke x0 x0) (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0) x0) x0) x0) x0) x0) x0) x0) x0) x0)) ≡ x0
  f76 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke x0 x0) (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0) hole) x0) x0) x0) x0) x0) x0) x0) x0))) (f23 x1 x0 x0))) ∙ (f32 x0 (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0))) ∙ refl))
  f77 : (x0 x1 x2 x3 x4 : A) → (stroke x0 (stroke (stroke (stroke x1 x2) (stroke (stroke x3 x4) x0)) (stroke (stroke (stroke (stroke x1 x2) (stroke (stroke x3 x4) x0)) (stroke x3 (stroke (stroke x3 x0) x3))) (stroke (stroke x1 x2) (stroke (stroke x3 x4) x0))))) ≡ (stroke x3 (stroke (stroke x3 x0) x3))
  f77 x0 x1 x2 x3 x4 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke hole (stroke (stroke (stroke x1 x2) (stroke (stroke x3 x4) x0)) (stroke (stroke (stroke (stroke x1 x2) (stroke (stroke x3 x4) x0)) (stroke x3 (stroke (stroke x3 x0) x3))) (stroke (stroke x1 x2) (stroke (stroke x3 x4) x0)))))) (f0 x3 x4 x0))) ∙ (f2 (stroke (stroke x3 x4) x0) (stroke x3 (stroke (stroke x3 x0) x3)) x1 x2)) ∙ refl))
  f78 : (x0 x1 x2 : A) → (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x1) x1) x1) x1) x1) x1) x1) x2) (stroke x1 (stroke (stroke x1 x2) x1))) ≡ x2
  f78 x0 x1 x2 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x1) hole) x1) x1) x1) x1) x1) x2) (stroke x1 (stroke (stroke x1 x2) x1)))) (f23 x0 x1 x1))) ∙ (f33 (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x1) x1 x2)) ∙ refl))
  f79 : (x0 x1 : A) → (stroke (stroke (stroke (stroke x0 x0) (stroke x0 (stroke x0 x0))) x0) (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0) x0) x0) x0) x0) x0)) ≡ x0
  f79 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke (stroke x0 x0) (stroke x0 (stroke x0 x0))) x0) (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0) hole) x0) x0) x0) x0))) (f23 x1 x0 x0))) ∙ (f41 x0 (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0))) ∙ refl))
  f80 : (x0 x1 x2 : A) → (stroke (stroke (stroke (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x1) x1) x2) x1) (stroke (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x1) x1) x1)) ≡ x1
  f80 x0 x1 x2 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x1) x1) x2) x1) (stroke (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x1) x1) hole))) (f49 x0 x1 x1))) ∙ (f0 (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x1) x1) x2 x1)) ∙ refl))
  f81 : (x0 : A) → (stroke (stroke x0 (stroke x0 (stroke (stroke x0 x0) x0))) (stroke (stroke x0 (stroke (stroke x0 x0) x0)) (stroke x0 (stroke x0 (stroke (stroke x0 x0) x0))))) ≡ (stroke x0 (stroke (stroke x0 x0) x0))
  f81 x0 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke x0 (stroke x0 (stroke (stroke x0 x0) x0))) (stroke (stroke x0 (stroke (stroke x0 x0) x0)) (stroke hole (stroke x0 (stroke (stroke x0 x0) x0)))))) (f19 x0))) ∙ (f50 x0 (stroke x0 (stroke (stroke x0 x0) x0)))) ∙ refl))
  f82 : (x0 : A) → (stroke (stroke (stroke x0 (stroke (stroke x0 x0) x0)) x0) (stroke x0 (stroke (stroke x0 (stroke (stroke x0 x0) (stroke x0 (stroke x0 x0)))) x0))) ≡ (stroke (stroke x0 x0) (stroke x0 (stroke x0 x0)))
  f82 x0 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke hole (stroke x0 (stroke (stroke x0 (stroke (stroke x0 x0) (stroke x0 (stroke x0 x0)))) x0)))) (f51 x0))) ∙ (f0 x0 (stroke (stroke x0 (stroke (stroke x0 x0) x0)) x0) (stroke (stroke x0 x0) (stroke x0 (stroke x0 x0))))) ∙ refl))
  f83 : (x0 : A) → (stroke (stroke (stroke (stroke (stroke x0 x0) (stroke x0 (stroke x0 x0))) (stroke (stroke x0 (stroke (stroke x0 x0) x0)) x0)) x0) (stroke (stroke (stroke x0 (stroke (stroke x0 x0) x0)) x0) x0)) ≡ x0
  f83 x0 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke (stroke (stroke x0 x0) (stroke x0 (stroke x0 x0))) hole) x0) (stroke (stroke (stroke x0 (stroke (stroke x0 x0) x0)) x0) x0))) (f69 x0 (stroke x0 (stroke x0 x0))))) ∙ (f45 (stroke (stroke x0 x0) (stroke x0 (stroke x0 x0))) x0 x0)) ∙ refl))
  f84 : (x0 x1 x2 x3 x4 : A) → (stroke x0 (stroke (stroke (stroke x1 x2) (stroke (stroke (stroke x3 (stroke (stroke x3 x0) x3)) x4) x0)) (stroke (stroke (stroke (stroke x1 x2) (stroke (stroke (stroke x3 (stroke (stroke x3 x0) x3)) x4) x0)) (stroke (stroke x3 (stroke (stroke x3 x0) x3)) x0)) (stroke (stroke x1 x2) (stroke (stroke (stroke x3 (stroke (stroke x3 x0) x3)) x4) x0))))) ≡ (stroke (stroke x3 (stroke (stroke x3 x0) x3)) x0)
  f84 x0 x1 x2 x3 x4 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke hole (stroke (stroke (stroke x1 x2) (stroke (stroke (stroke x3 (stroke (stroke x3 x0) x3)) x4) x0)) (stroke (stroke (stroke (stroke x1 x2) (stroke (stroke (stroke x3 (stroke (stroke x3 x0) x3)) x4) x0)) (stroke (stroke x3 (stroke (stroke x3 x0) x3)) x0)) (stroke (stroke x1 x2) (stroke (stroke (stroke x3 (stroke (stroke x3 x0) x3)) x4) x0)))))) (f1 x3 x0 x4))) ∙ (f2 (stroke (stroke (stroke x3 (stroke (stroke x3 x0) x3)) x4) x0) (stroke (stroke x3 (stroke (stroke x3 x0) x3)) x0) x1 x2)) ∙ refl))
  f85 : (x0 x1 : A) → (stroke (stroke (stroke (stroke x0 x0) (stroke x0 (stroke x0 x0))) x0) (stroke (stroke (stroke (stroke x1 (stroke x0 x0)) (stroke (stroke (stroke x1 (stroke x0 x0)) x0) (stroke x1 (stroke x0 x0)))) x0) x0)) ≡ x0
  f85 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke (stroke x0 x0) (stroke hole (stroke x0 x0))) x0) (stroke (stroke (stroke (stroke x1 (stroke x0 x0)) (stroke (stroke (stroke x1 (stroke x0 x0)) x0) (stroke x1 (stroke x0 x0)))) x0) x0))) (f39 x0 x1))) ∙ (f45 (stroke x0 x0) (stroke x1 (stroke x0 x0)) x0)) ∙ refl))
  f86 : (x0 x1 : A) → (stroke (stroke x0 x0) (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0) x0) x0) x0) x0) x0) x0) x0) x0) x0) x0)) ≡ x0
  f86 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke x0 x0) (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0) x0) hole) x0) x0) x0) x0) x0) x0) x0) x0))) (f49 x1 x0 x0))) ∙ (f32 x0 (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0) x0))) ∙ refl))
  f87 : (x0 x1 x2 : A) → (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x1) x1) x1) x1) x1) x1) x1) x1) x2) (stroke x1 (stroke (stroke x1 x2) x1))) ≡ x2
  f87 x0 x1 x2 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x1) x1) hole) x1) x1) x1) x1) x1) x2) (stroke x1 (stroke (stroke x1 x2) x1)))) (f49 x0 x1 x1))) ∙ (f33 (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x1) x1) x1 x2)) ∙ refl))
  f88 : (x0 x1 : A) → (stroke (stroke (stroke (stroke x0 x0) (stroke x0 (stroke x0 x0))) x0) (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0) x0) x0) x0) x0) x0) x0)) ≡ x0
  f88 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke (stroke (stroke (stroke x0 x0) (stroke x0 (stroke x0 x0))) x0) (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0) x0) hole) x0) x0) x0) x0))) (f49 x1 x0 x0))) ∙ (f41 x0 (stroke (stroke (stroke (stroke x1 (stroke (stroke x1 x0) x1)) x0) x0) x0))) ∙ refl))
  f89 : (x0 x1 : A) → (stroke (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x1) (stroke x1 (stroke (stroke x1 (stroke (stroke x1 x1) (stroke x1 (stroke x1 x1)))) x1))) ≡ (stroke (stroke x1 x1) (stroke x1 (stroke x1 x1)))
  f89 x0 x1 = ((sym refl) ∙ (((sym (cong (λ hole → (stroke hole (stroke x1 (stroke (stroke x1 (stroke (stroke x1 x1) (stroke x1 (stroke x1 x1)))) x1)))) (f65 x1 x0))) ∙ (f0 x1 (stroke (stroke (stroke x0 (stroke (stroke x0 x1) x0)) x1) x1) (stroke (stroke x1 x1) (stroke x1 (stroke x1 x1))))) ∙ refl))
