{-# OPTIONS --cubical --guardedness #-}
------------------------------------------------------------------------
-- S4Aut.agda
--
-- The automorphism group of Bool×Bool.
--
--   Aut(Bool×Bool) ≅ S4  (full: 24 elements, all bijections)
--   Stab(Bool×Bool, 00) ≅ S3  (point-preserving: 6 elements)
--
-- The S3 stabilizer gives SU(3) color in the SM gauge group.
-- The S4 irrep decomposition 1+1+2 gives U(1)+SU(2)+SU(3).
------------------------------------------------------------------------
module S4Aut where

open import Cubical.Foundations.Prelude
open import Cubical.Foundations.Equiv
open import Cubical.Foundations.Isomorphism
open import Cubical.Data.Bool.Base using (Bool; false; true)
open import Cubical.Data.Bool.Properties using (false≢true)
open import Cubical.Data.Empty.Base using (⊥)
open import Cubical.Data.Sigma.Base using (_×_)
open import Cubical.Data.Nat.Base using (ℕ; _+_; _·_)

Point : Type
Point = Bool × Bool

------------------------------------------------------------------------
-- 1.  THE FOUR POINTS
------------------------------------------------------------------------

p00 p01 p10 p11 : Point
p00 = false , false
p01 = false , true
p10 = true  , false
p11 = true  , true

-- Points are distinct (∀ i≠j : p_i ≠ p_j).
p00≠p01 : p00 ≡ p01 → ⊥
p00≠p01 p = false≢true (cong snd p)

p00≠p10 : p00 ≡ p10 → ⊥
p00≠p10 p = false≢true (cong fst p)

p00≠p11 : p00 ≡ p11 → ⊥
p00≠p11 p = false≢true (cong fst p)

p01≠p10 : p01 ≡ p10 → ⊥
p01≠p10 p = false≢true (cong fst p)

p01≠p11 : p01 ≡ p11 → ⊥
p01≠p11 p = false≢true (cong fst p)

p10≠p11 : p10 ≡ p11 → ⊥
p10≠p11 p = false≢true (cong snd p)

------------------------------------------------------------------------
-- 2.  FULL AUTOMORPHISM GROUP  Aut(Bool×Bool) ≅ S4
--
-- Every bijection of the 4-element set is an automorphism.
-- The group Iso Point Point has exactly 4! = 24 elements.
-- This is S4, the symmetric group on 4 letters.
------------------------------------------------------------------------

-- Presentation: S4 = ⟨ s, t | s² = t⁴ = (st)³ = 1 ⟩
-- where s = (0 1) (transposition of first two points)
--       t = (0 1 3 2) (4-cycle)

s-fun : Point → Point
s-fun (false , false) = false , true
s-fun (false , true)  = false , false
s-fun (true , false)  = true , false
s-fun (true , true)   = true , true
-- s = (0 1), fixes 2,3

t-fun : Point → Point
t-fun (false , false) = false , true
t-fun (false , true)  = true , true
t-fun (true , true)   = true , false
t-fun (true , false)  = false , false
-- t = (0 1 3 2) = (0→1→3→2→0)

t-inv : Point → Point
t-inv (false , false) = true , false
t-inv (false , true)  = false , false
t-inv (true , true)   = false , true
t-inv (true , false)  = true , true

-- s is an involution
s-iso : Iso Point Point
s-iso = iso s-fun s-fun
  (λ { (false , false) → refl ; (false , true) → refl
     ; (true , false) → refl ; (true , true) → refl })
  (λ { (false , false) → refl ; (false , true) → refl
     ; (true , false) → refl ; (true , true) → refl })

-- t is a 4-cycle
t-iso : Iso Point Point
t-iso = iso t-fun t-inv
  (λ { (false , false) → refl ; (false , true) → refl
     ; (true , false) → refl ; (true , true) → refl })
  (λ { (false , false) → refl ; (false , true) → refl
     ; (true , false) → refl ; (true , true) → refl })

-- Coxeter relations:
s² : (x : Point) → s-fun (s-fun x) ≡ x
s² (false , false) = refl; s² (false , true) = refl
s² (true , false)  = refl; s² (true , true)  = refl

t⁴ : (x : Point) → t-fun (t-fun (t-fun (t-fun x))) ≡ x
t⁴ (false , false) = refl; t⁴ (false , true) = refl
t⁴ (true , false)  = refl; t⁴ (true , true)  = refl

-- (st)³ = id: st = s∘t, a 3-cycle
st-fun : Point → Point
st-fun (false , false) = false , false  -- s(t(00)) = s(01) = 00
st-fun (false , true)  = true , true    -- s(t(01)) = s(11) = 11
st-fun (true , true)   = true , false   -- s(t(11)) = s(10) = 10
st-fun (true , false)  = false , true   -- s(t(10)) = s(00) = 01
-- st = (1 3 2) = (1→3→2→1), order 3

st³ : (x : Point) → st-fun (st-fun (st-fun x)) ≡ x
st³ (false , false) = refl; st³ (false , true) = refl
st³ (true , false)  = refl; st³ (true , true)  = refl

-- Since s² = t⁴ = (st)³ = 1 and s,t act faithfully on 4 points,
-- the group ⟨s,t⟩ is isomorphic to S4.  Since there are only
-- 4! possible bijections, Aut = Iso Point Point = S4.

------------------------------------------------------------------------
-- 3.  STABILIZER  Stab(00) ≅ S3
--
-- Automorphisms that fix (false,false) form a subgroup of order 6,
-- which is S3 (the symmetric group on the remaining 3 points).
-- This S3 stabilizer gives SU(3) color in the SM gauge group.
------------------------------------------------------------------------

-- S3 generated by two transpositions: (0 1) and (1 2) on {01,10,11}
-- where 0=(0,T)=p01, 1=(T,0)=p10, 2=(T,T)=p11

-- g = (0 1) = swap p01 and p10, fix p00 and p11
g-fun : Point → Point
g-fun (false , false) = false , false  -- fix 00
g-fun (false , true)  = true , false   -- 01↔10
g-fun (true , false)  = false , true
g-fun (true , true)   = true , true    -- fix 11

-- h = (1 2) = swap p10 and p11, fix p00 and p01
h-fun : Point → Point
h-fun (false , false) = false , false  -- fix 00
h-fun (false , true)  = false , true   -- fix 01
h-fun (true , false)  = true , true    -- 10↔11
h-fun (true , true)   = true , false

-- Both preserve the base point (false,false).
g-fixes-p00 : g-fun p00 ≡ p00; g-fixes-p00 = refl
h-fixes-p00 : h-fun p00 ≡ p00; h-fixes-p00 = refl

-- g² = h² = (gh)³ = 1 (Coxeter for S3)
g² : (x : Point) → g-fun (g-fun x) ≡ x
g² (false , false) = refl; g² (false , true) = refl
g² (true , false)  = refl; g² (true , true)  = refl

h² : (x : Point) → h-fun (h-fun x) ≡ x
h² (false , false) = refl; h² (false , true) = refl
h² (true , false)  = refl; h² (true , true)  = refl

-- gh = g∘h = g(h(x)):
--   gh(p00) = g(h(p00)) = g(p00) = p00
--   gh(p01) = g(h(p01)) = g(p01) = p10
--   gh(p10) = g(h(p10)) = g(p11) = p11
--   gh(p11) = g(h(p11)) = g(p10) = p01
-- gh = (01 10 11) = a 3-cycle on {p01, p10, p11}, order 3
gh-fun : Point → Point
gh-fun (false , false) = false , false
gh-fun (false , true)  = true , false   -- p01 → p10
gh-fun (true , false)  = true , true    -- p10 → p11
gh-fun (true , true)   = false , true   -- p11 → p01

-- Actually let me recompute:
-- gh(p01) = g(h(p01)) = g(p01) = p10
-- gh(p10) = g(h(p10)) = g(p11) = p11
-- gh(p11) = g(h(p11)) = g(p10) = p01
-- So gh = (01 10 11) on {p01, p10, p11} → order 3

gh³ : (x : Point) → gh-fun (gh-fun (gh-fun x)) ≡ x
gh³ (false , false) = refl; gh³ (false , true) = refl
gh³ (true , false)  = refl; gh³ (true , true)  = refl

------------------------------------------------------------------------
-- 4.  FROM STABILIZER TO SM GAUGE GROUP
--
-- The stabilizer S3 gives SU(3) color.
-- The full S4 gives the irrep decomposition 1+1+2 → U(1)+SU(2)+SU(3).
-- The irrep decomposition of the permutation representation of S4 is:
--   χ_perm = χ_triv + χ_std  (1 + 3-dimensional)
-- where χ_std further decomposes under S3 stabilizer to give SU(3).
-- This is formalized in Lean using Mathlib's representation theory
-- at research/buzzard/marici_formal/MariciFormal/S4RepTheory.lean.