<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
const entities = ref<any[]>([])
const relations = ref<any[]>([])
const search = ref(''), kind = ref(''), selected = ref(''), compare = ref('')
const mode = ref<'now'|'at'|'compare'>('now'), from = ref(1), to = ref(1), isolate = ref(false), tooltip = ref<any>(null)
const viewBox = ref({x:0,y:0,w:1200,h:760})
const colors: Record<string,string> = {claim:'#d18b47',conjecture:'#9574c5',criticism:'#b86b84',problem:'#c96868',source:'#499675',test:'#4b87ae'}
const timeline = computed(() => [...new Set(entities.value.map(e=>e.temporal?.entry).filter(Number.isFinite))].sort((a,b)=>a-b) as number[])
const allKinds = computed(() => [...new Set(entities.value.map(e=>e.kind))].sort() as string[])
const maximum = computed(() => timeline.value.at(-1)||1)
const selectedEntity = computed(() => entities.value.find(e=>e.entity_id===selected.value))
const compareEntity = computed(() => entities.value.find(e=>e.entity_id===compare.value))
const temporalEntities = computed(() => entities.value.filter(e=>mode.value==='now'||!Number.isFinite(e.temporal?.entry)||e.temporal.entry<=to.value))
const matches = computed(() => temporalEntities.value.filter(e=>{const q=search.value.trim().toLowerCase();return(!kind.value||e.kind===kind.value)&&(!q||`${e.title} ${e.entity_id} ${e.summary||''}`.toLowerCase().includes(q))}))
const neighborhood = computed(() => {if(!isolate.value||!selected.value)return null;const ids=new Set([selected.value]);for(const r of relations.value){if(r.source_id===selected.value)ids.add(r.target_id);if(r.target_id===selected.value)ids.add(r.source_id)}return ids})
const visibleEntities = computed(() => matches.value.filter(e=>!neighborhood.value||neighborhood.value.has(e.entity_id)))
const visibleIds = computed(() => new Set(visibleEntities.value.map(e=>e.entity_id)))
const visibleRelations = computed(() => relations.value.filter(r=>{const entry=r.temporal?.entry;return(mode.value==='now'||!Number.isFinite(entry)||entry<=to.value)&&visibleIds.value.has(r.source_id)&&visibleIds.value.has(r.target_id)}))
const selectedRelations = computed(() => relations.value.filter(r=>r.source_id===selected.value||r.target_id===selected.value))
const incidentIds = computed(() => new Set(selectedRelations.value.flatMap(r => [r.source_id, r.target_id])))
const positions = computed(() => {const groups=[...new Set(visibleEntities.value.map(e=>e.kind))].sort();const out=new Map<string,{x:number,y:number}>();groups.forEach((g,gi)=>{const ms=visibleEntities.value.filter(e=>e.kind===g),phase=gi/Math.max(1,groups.length)*Math.PI*2-Math.PI/2,cx=600+Math.cos(phase)*260,cy=380+Math.sin(phase)*200;ms.forEach((e,i)=>{const ring=25+Math.floor(i/24)*18,capacity=Math.min(24,ms.length-Math.floor(i/24)*24),angle=(i%24)/Math.max(1,capacity)*Math.PI*2;out.set(e.entity_id,{x:cx+Math.cos(angle)*ring,y:cy+Math.sin(angle)*ring})})});return out})
function restoreUrl(){const p=new URLSearchParams(location.search);selected.value=p.get('entity')||'';compare.value=p.get('compare')||'';const t=p.get('time');mode.value=t==='at'||t==='compare'?t:'now';to.value=Math.min(maximum.value,Math.max(1,Number(p.get('to'))||maximum.value));from.value=Math.min(maximum.value,Math.max(1,Number(p.get('from'))||1))}
function syncUrl(replace=false){const u=new URL(location.href);selected.value?u.searchParams.set('entity',selected.value):u.searchParams.delete('entity');compare.value?u.searchParams.set('compare',compare.value):u.searchParams.delete('compare');if(mode.value==='now'){u.searchParams.delete('time');u.searchParams.delete('to');u.searchParams.delete('from')}else{u.searchParams.set('time',mode.value);u.searchParams.set('to',String(to.value));mode.value==='compare'?u.searchParams.set('from',String(from.value)):u.searchParams.delete('from')}history[replace?'replaceState':'pushState']({},'',u)}
function select(id:string,secondary=false){if(secondary)compare.value=compare.value===id?'':id;else{selected.value=id;isolate.value=false}syncUrl()}
function step(delta:number){const i=visibleEntities.value.findIndex(e=>e.entity_id===selected.value),next=visibleEntities.value[(i+delta+visibleEntities.value.length)%visibleEntities.value.length];if(next)select(next.entity_id)}
function reset(){search.value='';kind.value='';selected.value='';compare.value='';mode.value='now';isolate.value=false;viewBox.value={x:0,y:0,w:1200,h:760};syncUrl(true)}
let drag:{x:number;y:number;bx:number;by:number}|null=null
function pointerDown(e:PointerEvent){if(e.target!==e.currentTarget)return;drag={x:e.clientX,y:e.clientY,bx:viewBox.value.x,by:viewBox.value.y};(e.currentTarget as SVGSVGElement).setPointerCapture(e.pointerId)}
function pointerMove(e:PointerEvent){if(!drag)return;const r=(e.currentTarget as SVGSVGElement).getBoundingClientRect();viewBox.value={...viewBox.value,x:drag.bx-(e.clientX-drag.x)*viewBox.value.w/r.width,y:drag.by-(e.clientY-drag.y)*viewBox.value.h/r.height}}
function zoom(e:WheelEvent){e.preventDefault();const f=e.deltaY>0?1.12:.89,w=Math.min(2400,Math.max(240,viewBox.value.w*f)),h=w*760/1200;viewBox.value={x:viewBox.value.x+(viewBox.value.w-w)/2,y:viewBox.value.y+(viewBox.value.h-h)/2,w,h}}
onMounted(async()=>{const response=await fetch('/epistemic-graph.json'),graph=await response.json();if(graph.schema!=='marici.public-epistemic-graph.v2')throw new Error('Unexpected public graph schema');entities.value=graph.entities||[];relations.value=graph.relations||[];restoreUrl();window.addEventListener('popstate',restoreUrl)})
</script>

<template>
  <section class="graph-app" :class="{'sheet-open':!!selectedEntity,'has-selection':!!selectedEntity}">
    <div class="graph-toolbar"><label>Find an entity <input v-model="search" type="search" placeholder="Search titles or IDs…" /></label><label>Kind <select v-model="kind"><option value="">All kinds</option><option v-for="g in allKinds" :key="g" :value="g">{{g}}</option></select></label><button @click="reset">Reset view</button><span aria-live="polite">{{visibleEntities.length}} / {{entities.length}} entities · {{visibleRelations.length}} relations</span></div>
    <section class="time-controls"><strong>Ledger time: {{mode==='now'?'Now':mode==='at'?`Through entry ${to}`:`Entries ${from}–${to}`}}</strong><div class="mode-buttons"><button v-for="m in ['now','at','compare']" :key="m" :aria-pressed="mode===m" @click="mode=m as any;syncUrl()">{{m==='at'?'At entry':m==='compare'?'Compare':'Now'}}</button></div><label v-if="mode!=='now'">Through entry {{to}} <input type="range" min="1" :max="maximum" v-model.number="to" @change="syncUrl()" /></label><label v-if="mode==='compare'">From entry {{from}} <input type="range" min="1" :max="maximum" v-model.number="from" @change="syncUrl()" /></label><button v-if="selectedEntity" :aria-pressed="isolate" @click="isolate=!isolate">{{isolate?'Show full graph':'Isolate neighborhood'}}</button></section>
    <div class="graph-layout"><div class="graph-canvas-wrap"><svg :viewBox="`${viewBox.x} ${viewBox.y} ${viewBox.w} ${viewBox.h}`" role="img" aria-label="Interactive graph of admitted public epistemic entities" @pointerdown="pointerDown" @pointermove="pointerMove" @pointerup="drag=null" @pointercancel="drag=null" @wheel="zoom"><g class="edges"><template v-for="r in visibleRelations" :key="r.relation_id"><line v-if="positions.has(r.source_id)&&positions.has(r.target_id)" :x1="positions.get(r.source_id)?.x" :y1="positions.get(r.source_id)?.y" :x2="positions.get(r.target_id)?.x" :y2="positions.get(r.target_id)?.y" :class="{added:mode==='compare'&&Number(r.temporal?.entry)>=from,incident:selected&&(r.source_id===selected||r.target_id===selected)}" /></template></g><g v-for="e in visibleEntities" :key="e.entity_id" class="graph-node" :data-id="e.entity_id" :class="{selected:selected===e.entity_id,context:selected&&incidentIds.has(e.entity_id),compared:compare===e.entity_id,'is-time-added':mode==='compare'&&Number(e.temporal?.entry)>=from,'is-time-context':mode==='compare'&&Number(e.temporal?.entry)<from}" :transform="`translate(${positions.get(e.entity_id)?.x},${positions.get(e.entity_id)?.y})`" tabindex="0" role="button" :aria-label="`${e.kind}: ${e.title}`" @click="select(e.entity_id)" @keydown.enter="select(e.entity_id)" @keydown.space.prevent="select(e.entity_id)" @keydown.left.prevent="step(-1)" @keydown.right.prevent="step(1)" @contextmenu.prevent="select(e.entity_id,true)" @pointerenter="tooltip=e" @pointerleave="tooltip=null" @focus="tooltip=e" @blur="tooltip=null"><circle r="7" :fill="colors[e.kind]||'#888'"/><title>{{e.title}} · {{e.kind}} · right click to compare</title></g></svg><div v-if="tooltip" class="graph-tooltip" role="tooltip">{{tooltip.title}}<small>{{tooltip.kind}} · {{tooltip.entity_id}}</small></div><p>Drag to pan · scroll to zoom · click to inspect · right click to compare · arrow keys move between nodes</p></div>
      <aside class="graph-inspector" aria-live="polite"><button v-if="selectedEntity" class="close-details" aria-label="Close details" @click="selected='';compare='';syncUrl()">Close details</button><div v-if="selectedEntity" class="entity-summary"><p class="ledger-meta">{{selectedEntity.kind}} · {{selectedEntity.status||'admitted'}}</p><h2>{{selectedEntity.title}}</h2><p>{{selectedEntity.summary}}</p><p class="ledger-meta" v-if="selectedEntity.temporal?.entry">Admitted through ledger entry {{selectedEntity.temporal.entry}}</p><div class="inspector-actions"><button @click="select(selectedEntity.entity_id,true)">Pin to compare</button><button @click="step(-1)">Previous</button><button @click="step(1)">Next</button></div><h3>Relations ({{selectedRelations.length}})</h3><ul class="relation-list"><li v-for="r in selectedRelations" :key="r.relation_id"><button @click="select(r.source_id===selected?r.target_id:r.source_id)"><strong>{{r.relation_type}}</strong> · {{entities.find(e=>e.entity_id===(r.source_id===selected?r.target_id:r.source_id))?.title}}</button></li></ul></div><p v-else>Select a node to inspect its admitted relations. Right click a node to choose a comparison entity.</p><div v-if="compareEntity" class="entity-summary comparison"><hr/><p class="ledger-meta">Comparison</p><h2>{{compareEntity.title}}</h2><p>{{compareEntity.summary}}</p><button @click="compare='';syncUrl()">Clear comparison</button></div></aside>
    </div>
  </section>
</template>

<style scoped>
.graph-app{display:grid;gap:1rem}.graph-toolbar,.time-controls{display:flex;align-items:end;gap:1rem;flex-wrap:wrap;padding:1rem;border:1px solid var(--vp-c-divider);border-radius:8px}.graph-toolbar label,.time-controls label{display:grid;gap:.3rem}.graph-toolbar input,.graph-toolbar select{padding:.45rem}.mode-buttons,.inspector-actions{display:flex;gap:.4rem;flex-wrap:wrap}.mode-buttons button,.graph-app button{padding:.45rem .7rem;border:1px solid var(--vp-c-divider);border-radius:5px;background:var(--vp-c-bg);color:var(--vp-c-text-1)}[aria-pressed=true]{border-color:var(--vp-c-brand-1)!important}.graph-layout{display:grid;grid-template-columns:minmax(0,2fr) minmax(260px,1fr);gap:1rem}.graph-canvas-wrap{position:relative;min-width:0;border:1px solid var(--vp-c-divider);border-radius:8px;overflow:hidden}.graph-canvas-wrap svg{display:block;width:100%;height:auto;min-height:440px;background:var(--vp-c-bg-soft);touch-action:none;cursor:grab}.graph-canvas-wrap svg:active{cursor:grabbing}.edges line{stroke:var(--vp-c-divider);stroke-width:1;opacity:.55}.edges line.incident{stroke:var(--vp-c-brand-1);stroke-width:2;opacity:1}.edges line.added{stroke:var(--vp-c-brand-1);stroke-width:2}.graph-node{cursor:pointer;outline:none}.graph-app.has-selection .graph-node{opacity:.42}.graph-node.context,.graph-node.selected{opacity:1}.graph-node circle{stroke:var(--vp-c-bg);stroke-width:1.5}.graph-node:hover circle,.graph-node:focus circle{r:11;stroke:var(--vp-c-text-1);stroke-width:3}.graph-node.selected circle{r:12;stroke:var(--vp-c-text-1);stroke-width:3}.graph-node.compared circle{stroke:#d94444;stroke-width:3}.graph-node.is-time-context{opacity:.34}.graph-canvas-wrap>p{padding:0 1rem;color:var(--vp-c-text-2);font-size:.85rem}.graph-tooltip{position:absolute;left:1rem;top:1rem;max-width:280px;padding:.65rem .8rem;border:1px solid var(--vp-c-divider);border-radius:7px;background:var(--vp-c-bg);box-shadow:0 4px 18px #0002;pointer-events:none}.graph-tooltip small{display:block;color:var(--vp-c-text-2)}.graph-inspector{position:relative;padding:1rem;border:1px solid var(--vp-c-divider);border-radius:8px;max-height:680px;overflow:auto}.graph-inspector h2{font-size:1.15rem}.graph-inspector li{margin:.45rem 0}.relation-list{list-style:none;padding:0}.relation-list button{text-align:left}.close-details{display:none}.comparison{margin-top:1.5rem}@media(max-width:850px){.graph-layout{grid-template-columns:1fr}.graph-canvas-wrap svg{min-height:320px}}@media(max-width:560px){.sheet-open .graph-inspector{position:fixed;z-index:30;inset:auto 0 0;max-height:62vh;border-radius:16px 16px 0 0;background:var(--vp-c-bg);box-shadow:0 -8px 30px #0003}.close-details{display:block;float:right}}
</style>
